### ISSUE TITLE
Support submission with multiple DBS datasets, lumi masks

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#2372]
A future thing for CRAB. The current method of analyzing the "whole" CMS dataset is to use 2-3 datasets, 2-3 lumi mask files, and run ranges and submit 2-3 crab tasks. 

There is no technical reason this can't be combined all into one job. This would mean changing the Data section of the client config to something like this:

{{{

[{dataset:'name', lumiMask:'file/url', runs:'run range'},
 {dataset:'name2', lumiMask:'file2/url2', runs:'run range'},
 ...
] 
}}}

**Comment by mmascher** [comment]
Also a really old one, but from time to time we discuss this. However, given that we gave the crab library (and a multicrab like tool) to the users I believe that's not so critical and can be closed. Please reopen if necessary
