### ISSUE TITLE
Allow auto-increment to work for PrivateMC with different primary DS names, but same secondary.

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#3505]
setProcessingVersion does not work (doesn't have right things to key off of) for PrivateMC workflows since there is no inputDataset. Probably have another view with PrimaryDataset, etc for these workflows.

**Comment by mmascher** [comment]
Hi @ericvaandering , can we close this one ?

**Comment by ericvaandering** [comment]
This is super old.
