### ISSUE TITLE
Support writing output to arbitrary endpoint and PFN

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#3977]
See long discussion in crab3-commisioning. Lower priority than #2780, although may be implemented at the same time.

**Comment by mmascher** [comment]
Given the outcome of the UserOutputReview this seems an "hot topic". Setting April as milestone

**Comment by belforte** [comment]
Let's wait for an assessment of the the realtive prioriyt of the issues raised in the review first. It is not obvious that this will be among the ones we want first.

**Comment by belforte** [comment]
realistically.. willl not do. We already support CERN BOX, should rather document that.
