### ISSUE TITLE
Reduce proxy interactions

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4068]
We check proxies a lot - 
- We always see if we should delegate the DN to a new server.
- We look at voms proxy lifetime.
- We check the proxy in MyProxy.

I propose to only do this once every 5-10 minutes in the client.  This way, folks who do more than one "crab status" won't be so frustrated.

**Comment by belforte** [comment]
two things could be done:
1. each crab command calls voms-* too many times
2. all those call are awfully verbose in crab.log (thiis is to change in WMCore I guess)
3. if we really need (but I guess we don't) we could cache voms-proxy-info output in the task work directory, but I believe it is not worth

**Comment by belforte** [comment]
moving to CRAB Client

**Comment by belforte** [comment]
relevant actions copied inthe crabclient issue
