### ISSUE TITLE
Implement lock-breaking for dead / crashed workers and post-scripts

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4082]
The following cases are handled poorly and may cause double-submits or stuck tasks:
1) TaskWorker crashes while handling a job.  We should have a timestamp for when the TaskWorker grabbed the task and expire the lock after N minutes (N=15?).  When the TaskManager starts up, it should expire any locks held by prior invocations.
2) Before TaskWorker submits a task, we should make sure a task of the same name has not already been submitted to HTCondor.  If it has been, don't submit a duplicate and move the task to the SUBMITTED state.
3) The PostJob script should update the file state timestamp once every N minutes (N=15?); if there has been no updates in 3*N minutes, mark the job as failed.

For the job state tracking, we'll likely have a 'cron-like' cleanup task run by the TaskWorker.  This may be useful for the cleanups mentioned above.

**Comment by belforte** [comment]
this will be addressed by new TW state machine https://github.com/dmwm/CRABServer/issues/5076

checking for postJob health is instead still a good topic, see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1297.html

but better open a new issue.

**Comment by belforte** [comment]
post job part now tracked in https://github.com/dmwm/CRABServer/issues/5142
can close
