### ISSUE TITLE
TaskWorker interacts poorly with condor RPM

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABServer#4104]
From a fresh install:

```
2013-11-10 20:57:28,303:DEBUG:Proxy:Executing : 
 command : source /vagrant/dummyEnv.sh && unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/servicecert.pem X509_USER_KEY=/data/certs/servicekey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/185ee64253703308699e8b1752824bdb73b69296 -l "1d303387ed7c323d130e25d1e525a6013b442648" -t 168:00
 output : 
 error: myproxy-logon: /data/srv/TaskManager/3.3.0.pre7/slc6_amd64_gcc481/external/condor/8.0.4/lib/condor/libglobus_common.so.0: no version information available (required by myproxy-logon)
myproxy-logon: /data/srv/TaskManager/3.3.0.pre7/slc6_amd64_gcc481/external/condor/8.0.4/lib/condor/libglobus_common.so.0: no version information available (required by /usr/lib64/libmyproxy.so.5)
myproxy-logon: /data/srv/TaskManager/3.3.0.pre7/slc6_amd64_gcc481/external/condor/8.0.4/lib/condor/libglobus_common.so.0: no version information available (required by /usr/lib64/libglobus_usage.so.0)
```

**Comment by annawoodard** [comment]
I'm now seeing something similar:

 retcode : 127
2015-02-02 18:30:27,874:DEBUG:Proxy:Executing :
 command : unset X509_USER_CERT X509_USER_KEY && env X509_USER_CERT=/data/certs/hostcert.pem X509_USER_KEY=/data/certs/hostkey.pem myproxy-logon -d -n -s myproxy.cern.ch -o /data/certs/creds/98bdb766be053cf432f3454c9768e0bdb715949f.8847 -l "e4965085faacead39a22192c3d5c47f81e665215" -t 168:00
 output : A credential has been received for user e4965085faacead39a22192c3d5c47f81e665215 in /data/certs/creds/98bdb766be053cf432f3454c9768e0bdb715949f.8847.

 error: myproxy-logon: /data/srv/TaskManager/3.3.13.rc1/slc6_amd64_gcc481/external/condor/8.3.1/lib/condor/libglobus_common.so.0: no version information available (required by myproxy-logon)
myproxy-logon: /data/srv/TaskManager/3.3.13.rc1/slc6_amd64_gcc481/external/condor/8.3.1/lib/condor/libglobus_common.so.0: no version information available (required by /usr/lib64/libmyproxy.so.6)

@bbockelm, do you have any recommendations?

**Comment by annawoodard** [comment]
For now, unsetting LD_LIBRARY_PATH is working for me.

**Comment by mmascher** [comment]
Hi Anna,

there is a parameter in the TW called `cleanEnvironment` that can be used to execut these commands in a clean environment (using `env-i`). Moreover, the parameter so source the user grid UI should be unset now that with SLC6 it has been deprecated.
