### ISSUE TITLE
REST/TM deployment feedback

### ISSUE THREAD

**Issue by spigad** [dmwm/CRABServer#4138]
While porting to mysql I re-deployed everything and collected some feedback: 

1. Latest version of rpm I found for the TM is 330.rc6. This is not working because there are missing dependencies. Particularly CRABInterface part is completely missing
1.1 generally speaking, i didn't manage to find a series of compatible tags (cc, cs, tw... ) and the current heads are not compatible

2. Documentation: the only thing I found is here https://twiki.cern.ch/twiki/bin/view/Sandbox/CMSCrabTaskWorker but is not working/up-to-date: 
2.1 CONDOR_CONFIG is not documented
2.2 setup and env-setup is obsolete
2.3 htc_make_runtime is completely absent 
2.4 need to add host to a whitelist is completely absent 
2.5 how to enable the schedd to callback the proper frontend is not defined/written 

3. monitoring: glideinmon is not working. crab status provides me with a url but it is not working at all.. it return "Unknown task name"

**Comment by mmascher** [comment]
Closing, the twikis have been updated since then
