### ISSUE TITLE
Handling of CMSSW python configs

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4224]
Just a place to capture current thoughts. @belforte says that we should consider just packing up the user config and any config fragments found in the user directory and shipping it to the WN. 

This has a couple of implications:

1) For long term reproducibility, we'd have to store the config AND the fragments in the config cache.
2) We could only change/tweak/edit the config file once: on the worker node just before the job runs since we would not save the "fully resolved" config anywhere else.
3) Any pyCfgParams would have to be executed on the worker node, not the submit node. This could really be a problem because environment variables on the submit node would not be present on the worker. This is may be why we do things the way we do in CRAB2
4) Security is maybe not much changed. Now you are running some arbitrary python on the worker node (but of course, we're running arbitrary C++ so I don't see a real difference). 
5) There is no problem with pickling since you're guaranteed to be pickling the process object and unpickling in CMSSW. No worry about injection there.

I think it's clear we need a dedicated discussion to really hash this out. It's not obvious what to do.

**Comment by belforte** [comment]
sounds we'll never do, but keeping it up as documentation in case we get to this

**Comment by belforte** [comment]
Realistically, we;ll never change things in this area unless some other major change is done which may bring something like this as a side effect.
