### ISSUE TITLE
Long and short status do not agree

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4225]
I do a short status or a long status on the same task seconds apart and get wildly different answers:

-bash-3.2$ crab status -t crab_ewv_test_2
Task name:			140228_153500_vocms20:ewv_crab_ewv_test_2
Task status:			SUBMITTED
Monitoring URL:			http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=140228_153500_vocms20%3Aewv_crab_ewv_test_2
Details:			cooloff        18.0% ( 54/300)
				idle            2.0% (  6/300)
				transferring   80.0% (240/300)
Log file is /uscms/home/ewv/CRAB3-test/CMSSW_5_3_12_patch2/src/crab_ewv_test_2/crab.log
-bash-3.2$ crab status -t crab_ewv_test_2 -l 
Task name:			140228_153500_vocms20:ewv_crab_ewv_test_2
Task status:			SUBMITTED
Monitoring URL:			http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=140228_153500_vocms20%3Aewv_crab_ewv_test_2
Details:			cooloff        98.7% (296/300)
				held            0.3% (  1/300)
				idle            0.7% (  2/300)
				running         0.3% (  1/300)

Extended Job Status Table

 Job State        Most Recent Site        Runtime   Mem (MB)      CPU %    Retries      Waste
   1 cooloff      T2_US_Florida           0:00:04          0          0          6    0:00:24
   2 cooloff      T2_US_Florida           0:00:04          0          0          6    0:00:23
   3 cooloff      T2_US_Vanderbilt        0:00:04          0          0          4    0:00:17
   4 cooloff      T2_HU_Budapest          0:00:12          0          0          4    0:01:40
   5 idle         Unknown                 0:00:00          0    Unknown          6    0:00:27
   6 cooloff      T2_HU_Budapest          0:00:02          0          0          4    0:00:14
   7 cooloff      T2_US_Vanderbilt        0:00:03          0          0          4    0:00:16

**Comment by mmascher** [comment]
Closing as duplicate
