### ISSUE TITLE
RetryJob.py should not confuse crab watchdog with condor removal

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4243]
in
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L141

removal reason comes from condor, not from crab3 watchdog.
(the watchdog should better cleanly terminate the job with full logs and proper exit code before pilot boundary if any is hit and the job will look successful to condor)

**Comment by mmascher** [comment]
Closing, there is no CRAB3 watchdog, we call it this way for the users but it's actually the pilot doing this.

**Comment by belforte** [comment]
It is not even the pilot, it is the startd. Anyhow you must fix the message. And do not refer to inexisint watchdogs. Please reopen. Having good error messages is difficult, but long term it helps that users can figure out w/o asking all of the times.

**Comment by mmascher** [comment]
OK, just saying your job has been killed because of the memory usage is
fine then?
Il 13/feb/2015 17:37 "Stefano Belforte" <notifications@github.com> ha
scritto:

**Comment by belforte** [comment]
yes
