### ISSUE TITLE
Allow CRAB to generate jobs based on lists of Xrootd URL's

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABServer#4244]
Originally from : https://github.com/dmwm/CRABClient/issues/4032
From DAMason
"
This is a consequence of https://github.com/dmwm/CRABClient/issues/4032.

The idea is instead of an input dataset you point the config at a list of xrootd URL's (i.e. what would be generated from https://github.com/dmwm/CRABClient/issues/4032). It then generates jobs -- located according to your whitelist probably, and because you don't have event/lumi/run information for these files you would be constrained to split by file "

**Comment by mmascher** [comment]
A nice one that we forgot about..

**Comment by AndresTanasijczuk** [comment]
@nizamyusli will work on this issue (the part that concerns to the last set of comments), but let's define what do we want exactly.
IIUC, @ericvaandering and @belforte both argue that it is important that the CRAB parameter "userInputFile" accepts a python list. Would it be ok if the CRAB parameter would support ONLY a python list, and for users that prefer to have a text file we provide a function (please suggest the name) in CRABClient.UserUtilities that reads a text file and outputs a python list?
And of course we would rename the parameter to "userInputFiles" or "userInputFilesList".

**Comment by ericvaandering** [comment]
Yeah. In fact wouldn't something like handle.readlines() work just fine in turning a text file into a list? Rather than a function, we may want to educate our users in basic python. :-)

userInputFiles (adding "list" is in some sense adding the data type to the variable which is considered poor form)

**Comment by belforte** [comment]
since I was named... +1 with Eric

**Comment by AndresTanasijczuk** [comment]
Ok. No function for the conversion then.

**Comment by ericvaandering** [comment]
You can even just do 
userInputFiles = list(open('list.txt'))

Hard to get simpler than that. :smile:
