### ISSUE TITLE
Move CAFServiceConfig repo

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4245]
Currently the repository for the externalcmsweb REST  configuration is here https://git.cern.ch/web/CAFServicesConfig.git and the owner is the "deprecated" it-es-vos_trac e-group.

We shuold move the repository to a better place and update this https://github.com/dmwm/deployment/blob/master/crabserver/config.py

**Comment by mmascher** [comment]
Maybe we can just change the egroup from it-es-vos_trac to the one we use for crab3 glideinwms. Justas, can you handle that? Low priority

**Comment by juztas** [comment]
https://github.com/dmwm/deployment/pull/167

**Comment by juztas** [comment]
Done. All in this egroup "cms-service-crab3htcondor" has access to change rest configuration
