### ISSUE TITLE
Use WMCore.Lexicon regular expressions

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4262]
We should start using WMCore lexicon regular expression as much as possible. Needs some refactoring on the WMCore side. Something in the line of:

https://github.com/mmascher/WMCore/commit/0796749c53d3332564938d58f6b7634204b87197
https://github.com/mmascher/CRABServer/commit/24a0fb8dd4797e85116686e16c10cf0acc70b0e8

**Comment by mmascher** [comment]
See also: https://github.com/dmwm/CRABServer/issues/4338

**Comment by belforte** [comment]
let's assume by now we did all that we could, at least on such a broad heading.
