### ISSUE TITLE
No longer make a copy of job log file.

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4264]
We currently make a copy of the job_log; this is because "condor_q -userlog" used to take many file locks and we ran into significant lock contention.

This is no longer so; further, the temporary files may be causing disk contention when the schedd fsync's the user log.  We should get rid of the copy.

**Comment by mmascher** [comment]
What about this @juztas ? Still waiting for @bbockelm review ? I see you closed the pull request..

**Comment by juztas** [comment]
I had merge conflicts. Will create new one pull request

**Comment by mmascher** [comment]
assigning to you then @juztas
