### ISSUE TITLE
Jobs that fail to bootstrap are not killable

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4275]
I had jobs that got into this state:

```
> crab st crab_int_5
Task name:			140422_200915_vocms20:bbockelm_crab_int_5
Task status:			UNKNOWN
Error during task injection:	Task failed to bootstrap on schedd <128.142.229.43:4080?sock=30808_6389_3>.

No jobs created yet!
```

However, when trying to kill the task:

```
Error contacting the server.
Server answered with: Execution error
Reason is: There are no jobs to kill. Only jobs not in ['finished'] states can be killed
```

This should be a valid state transition.

**Comment by mmascher** [comment]
I am not sure what this was about. If a task failed to bootstrap there are no jobs to kill. Yes, we can still transition the task status from SUBMITTED to KILLED in the DB, but given that nobody complained about this I would not bother until some user complain :)

For the moment closing the issue, reopen if you think we should do something about that.

**Comment by belforte** [comment]
this task should not stay in SUBMITTED.  We should not wait for users' complain to fix logic errors. Indeed there is no job to kill. I think we discussed already that status = UKNOWN is bad.
