### ISSUE TITLE
Decide to close the publication in ASO after checking the workflow status 

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/CRABServer#4283]
Details are here https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1928/1/1/1/1/1/1.html.

**Comment by mmascher** [comment]
ASO is doing "crab status" now to figure out if it has to close the publication. As far as providing a "crab publish" command to publish what's available now without waiting for 8hours I would wait that a user ask for it. It does not seems a hot topic now.
