### ISSUE TITLE
For privateMC, can we rename 'inputDataset' to something meaningful?

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4292]
From a physics-user point of view, having a parameter called 'inputDataset' in the CRAB config when running privateMC is meaningless. Can we have instead a new parameter, e.g. called 'primaryDatasetName', that is used in privateMC for specifying the primary dataset name, and ignore 'inputDataset'? For privateMC, the user sould not have to specify 'inputDataset', but only specify 'primaryDatasetName', which by the way should be a string without any "/". When running Analysis, this new parameter 'primaryDatasetName' should be ignored.

**Comment by mmascher** [comment]
This has been recently fixed, inputdata is not reused anymore.
