### ISSUE TITLE
crab status shows jobs as running for a killed task

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4297]
I submitted a task with 10 jobs to try the "crab kill" command.
task-name: 140512_141737_crab3test-3:atanasi_crab_tutorial_MC-generation_kill
I killed the task with "crab kill crab_tutorial_MC-generation_kill". 
The crab status shows (even after 2 hours of having done the kill):
Task name:			140512_141737_crab3test-3:atanasi_crab_tutorial_MC-generation_kill
Task status:			KILLED
Monitoring URL:			http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=140512_141737_crab3test-3%3Aatanasi_crab_tutorial_MC-generation_kill
Details:			running       100.0% (10/10)
The node_state.txt file shows that jobs are in "STATUS_SUBMITTED (not_idle)" and the DAG status as "STATUS_ERROR (removed)" (see 
http://vocms96.cern.ch/mon/cms293/140512_141737_crab3test-3:atanasi_crab_tutorial_MC-generation_kill/node_state.txt).
Doing a condor_history for the job #1 shows that the state is X:
[cms293@p01001456783585 ~]$ condor_history 346563.0
 ID     OWNER          SUBMITTED   RUN_TIME     ST COMPLETED   CMD            
346563.0   cms293          5/12 16:18   0+00:16:15 X         ???  /data/srv/glidecondor/condor_local/spool/6561/0/cluster346561.proc0.subproc0/gWMS-CMSRunAnalysis.sh -a san
We could see with Marco in the TW log that the kill requests were successfully sent to all the 10 jobs.
Shouldn't the job state in the node_state.txt file be changed after a successful kill to something reflecting that it was killed instead of being in "STATUS_SUBMITTED (not_idle)"?

**Comment by mmascher** [comment]
Should be all right now.
