### ISSUE TITLE
Change dataset name published in DBS

### ISSUE THREAD

**Issue by hernand** [dmwm/CRABServer#4308]
See discussion in https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1999.html
I think we have agreed to make the following changes:

- Remove the HN user name from the dataset name. This will allow a group of people (e.g. running group skims) to publish into the same dataset.

- change the default publication-name from 
<time-stamp>_crab_<General.requestName>
  to  <General.requestName>

**Comment by mmascher** [comment]
I need to read this carefully and think about it.

**Comment by AndresTanasijczuk** [comment]
The first bullet of this issue is duplicated with https://github.com/dmwm/CRABServer/issues/4825
And the second bullet I think is (partially) done: the timestamp has been removed, but I think crab_ is still there.
Up to @hernand  to keep this issue open or close it.

**Comment by hernand** [comment]
hmm, the other day discussing about #4825 I vaguely remembered that I had already brought us that issue :-) One year ago ... I think we can close it.
