### ISSUE TITLE
Killed job is resume back after being killed

### ISSUE THREAD

**Issue by qunox** [dmwm/CRABServer#4313]
Now if you do crab kill --jobid. The job that has been killed will change state from 
killed -> transferring -> cooloff -> idle / unsubmitted -> running

So the job run back again. This happen when some job are killed but some are left running. 
The example log is here : 
https://docs.google.com/document/d/1TJqkVFkDmQ9VgcxUmQAMnsx32pfBgQJBsOK4skJozv0/edit?usp=sharing

**Comment by mmascher** [comment]
Should be fixed now.
