### ISSUE TITLE
Record information on how to re-run a given job

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4328]
In the job wrapper output, we currently print out the file and lumi list as given to the job - but it's not in a human-friendly format.

If the job fails, we ought to print out the file list and the lumi mask in a format that the user can then copy/paste into their pset and re-run locally.

**Comment by mmascher** [comment]
I think we will consider this deprecated once @annawoodard will finish the `crab verify`. But let' keep this open and move it to June.

**Comment by belforte** [comment]
in the end `crab --dryrun` does not cover this. I am not sure if there's a plan for `crab --verify`. @annawoodard ?
In case I could recast into "allow to re-run job N locally for debugging" and even volunteer to do

**Comment by belforte** [comment]
this is now tracked as:
https://github.com/dmwm/CRABServer/issues/5026
