### ISSUE TITLE
Re-introduce FINAL command for DAG

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4361]
Right now, we always query HTCondor for the task status.

We should re-introduce the DAG FINAL command (this was disabled due to a bug in older HTCondor versions) which set the task status to FINISHED/FAILED in the TaskDB.

In such a case, we would no longer need to query HTCondor for task status by default - only when individual task information is requested.

**Comment by AndresTanasijczuk** [comment]
We could also monitor the publication status (and eventually resubmit publication) in the final DAG node.

**Comment by mmascher** [comment]
Let's keep an eye on this http://condor-wiki.cs.wisc.edu/index.cgi/tktview?tn=4209 if we decide to reintroduce the final node.

**Comment by belforte** [comment]
we agree that it would be useful, simply has not become vital yet. Keeping it open as documentation in case we get to it

**Comment by belforte** [comment]
not relevant any more  in the era of TaskProcess and automaticSplitting with 3 subdags
