### ISSUE TITLE
Monitoring fixes required

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4378]
Fix links on left bar, it shows twice vocms95
vocms20 is crab2 schedd
All schedd list can be taken from rest configuration
ASO links cannot point to local machine, it should point to cmsweb or cmsweb-testbed

Suggestion:
Split left bar monitoring links to prod and preprod
Remove upper links which are not yet used.
Remove examples from repository and leave only which are really used

**Comment by belforte** [comment]
not relevant anymore
