### ISSUE TITLE
Does crab status reports the same as condor_q?

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4383]
Based on this HN thread https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/80.html, @belforte commented that CRAB should either report the same as condor_q, or
an error. 
The task in question is http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=578237
The user was trying to kill the task, but he was seeing that jobs were still running. He did "crab kill" many times without seeing an effect. With Justas we checked in the schedd (btw, this was on vocms96, which had lot of problems since Thu 07-AUG) with condor_q, and saw no jobs for this task (only the dag_bootstrap_star was in H):
condor_q -const 'CRAB_ReqName=?="140806_222446_crab3test-3:namin_crab_QCDtest"'
-- Submitter: crab3test-3@vocms96.cern.ch : <128.142.177.81:4080?sock=54582_3191_35> : p01001456783585.cern.ch
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
2639940.0   cms696          8/7  01:17   0+18:29:02 H  10  0.1  dag_bootstrap_star

**Comment by mmascher** [comment]
See https://github.com/dmwm/CRABServer/issues/4225

**Comment by juztas** [comment]
@AndresTanasijczuk @mmascher do we still want to improve something here? Now CRAB3 tries to use NODE_STATE file if it is up to date and information in NODE_STATE is almost up to date.

**Comment by AndresTanasijczuk** [comment]
Ok. Closing. Can re-open in case inconsistencies are seen again.
