### ISSUE TITLE
Additional Dashboard parameter (Access type)

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4399]
Need to send to dashboard Access type parameter. 

'local' - not using AAA.
'remote' - using AAA.

**Comment by mmascher** [comment]
Do we need to do something more about the reports to popularity? @ericvaandering

**Comment by ericvaandering** [comment]
Hi Marco, you can find here the desired format of the report: https://github.com/dmwm/WMCore/issues/4233  To whit use Remote vs Local for xrootd access.

**Comment by belforte** [comment]
too told to read.. really. If later on comes out that we do something wrong, e.g. when porting to MONIT, we'll fix it then. But let's assume what we do currently is OK
