### ISSUE TITLE
Add data location and dataset to JDL

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4413]
From discussion with @jamesletts
Agreed … it would be useful to have for CRAB3 both:

DESIRED_CMSDataset (singular, the primary dataset being analyzed)
DESIRED_CMSDatasetLocations (plural, the PhedexNodeNames where the dataset exists)

**Comment by mmascher** [comment]
Note for myself: check if has something to do with https://github.com/dmwm/CRABServer/issues/4521 (I haven't read it all)

**Comment by mmascher** [comment]
Duplicated of https://github.com/dmwm/CRABServer/issues/4856
