### ISSUE TITLE
Save schedd name to the task database and not in the taskname

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4430]
with ref. to problems like this
>> Task name:
>> 140916_121612_crab3test-4:santocch_crab_20_aCrab_BJetPlusX_Drereco Task
>> status: UNKNOWN Error during task information retrieval:
>> 140916_121612_crab3test-4:santocch_crab_20_aCrab_BJetPlusX_Drereco:
>> Failed to contact Schedd: .
>>

(see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/152/2.html
)

print the specific sched which did not respond, so we know where to look  for fixing the problems.

**Comment by mmascher** [comment]
Getting there, with a recent commit from @juztas now we are saving the schedd into the task db. Keeping the schedd name in the taskname for backward compatibility

**Comment by belforte** [comment]
??? what does this exactly mean ?

**Comment by juztas** [comment]
Yea, New tasks will not have schedd name in the taskname. For backward compatability (Older tasks submitted before this fix) we are not changing task names or editing database to have schedd saved and late binding of schedd will be improved more in TaskWorker level for April release.

**Comment by mmascher** [comment]
yeah, we are doing things by steps, next month when there will be no tasks submitted with the old policy (scheddname in the taskname and no schedd in the database), we will do phase two and remove it.

**Comment by juztas** [comment]
mm. Already done with late binding of schedd :)
