### ISSUE TITLE
Retire publishDBS URL

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4438]
The parameter is not needed anymore. There is only phys03 where user can publish. Let's keep the url only in the ASO (we'll change it ther ein case we want to test DBS on cmsweb-testbed for example)

That's a first step https://github.com/dmwm/CRABServer/pull/4437, we need to remove it also from the client, server, tastworker and db

**Comment by mmascher** [comment]
IIRC we kept this url in the task DB, but ASO is taking it from the config. As Justas said we should review ASO which should take the publishurl from the taskdb.

**Comment by belforte** [comment]
@dciangot can you confirm that ASO takes publication DBS URL form CRAB DB and not from local config ?

**Comment by dciangot** [comment]
At the moment it still take the URL from the local config. 
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/PublisherWorker.py#L170

**Comment by belforte** [comment]
OK. so we move to an ASO issue

**Comment by dciangot** [comment]
Issue created
