### ISSUE TITLE
Improve error message when dataset is only on tape

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4459]
It should be replicated using '/QCD_Pt-1800_Tune4C_13TeV_pythia8/Spring14dr-castor_PU_S14_POSTLS170_V6-v1/GEN-SIM-RECODEBUG' for example.

Traceback is:

```
Error during task injection:    Problem handling 141008_102426_crab3test-3:sabuzeid_crab_VariableExtraction70X_With_Retracking_Pt1000to1400 because of 'NoneType' object has no attribute 'getFiles' failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.10.rc6/slc5_amd64_gcc461/cms/crabtaskworker/3.3.10.rc6/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 58, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.10.rc6/slc5_amd64_gcc461/cms/crabtaskworker/3.3.10.rc6/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 74, in execute
    self.logger.debug("Got %s files" % len(result.result.getFiles()))
AttributeError: 'NoneType' object has no attribute 'getFiles'
```

See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/191.html

**Comment by AndresTanasijczuk** [comment]
Currently the error message is given if no blocks of the dataset are on disk. But we should also give an error or warning message if the dataset has only a partial copy on disk (i.e. if there is at least 1 block that has no disk location). @belforte should we forbid submission if the dataset is only partially on disk, or should we for example give an error message under normal submission, but add an option to the submit command (or a CRAB configuration parameter, but this goes against the principle of minimizing the number of CRAB configuration parameters) to allow submission under such a circumstance?

**Comment by belforte** [comment]
I would expect that task is created to process only the blocks with a valid location.
IIUC the user I was reading about was reporting complete submission failure.
Indeed the message "data are only on tape" should be used only when all blocks are located on tape only.

**Comment by mmascher** [comment]
The message was improved, but still were not saying explicitely that the dataset was ONLY available on tape.

Just to be sure what to do here:

1) If all the blocks in the dataset are on tape fail with 'cannot submit a task if the input dataset is no tape'
2) Make sure that if a dataset is half on tape and half on disk we process the bit on disk and warn a users that part of the dataset is on tape.

**Comment by belforte** [comment]
The last part of 2) is really optional and very minor. Once you say that only some blocks have a 
valid location, can simply refer the user to DAS. The "problem" to fix is the large and 
easy-to-fall-in trap of the many datasets fully on tape.

**Comment by mmascher** [comment]
I fixed this, see the commit above. I will do a pull request later on. In the meantime if somebody wants to check this I will not merge for a couple of days on the master branch (I might cherry-pick it on the 3.3.15 branch though, I am preparing a new release).

Moving the part about the warning that a part of the dataset is on tape for October.

```
[mmascher@lxplus0059 wf]$ crab st
Task name:			150409_164655:mmascher_crab_testecmmascher-dev6_120
Task status:			FAILED
Error during task injection:	The CRAB3 server backend could not find any location for dataset /WGstarToLNu2E_TuneZ2star_8TeV-madgraph-tauola/Summer12-START50_V13-v2/GEN-SIM in https://cmsweb.cern.ch/dbs/prod/global/DBSReader.
N.B.: your dataset is available at T1_US_FNAL_Buffer,T1_US_FNAL_MSS, but CRAB3 can only submit a task if the dataset is on 'Disk'
```

**Comment by belforte** [comment]
why reference to DBS in the message "could not find location" ?
location is from PhEDEx. Better not to confuse users.

minor message improvements:
Crab3 server (without backend, please) could not submit the task because there is no DISK replica 
for dataset /blah/blah/blah
N.B. dataset is stored at .... but those are TAPE location

**Comment by bbockelm** [comment]
Chris Jones always tells me that error messages should not only tell me what is wrong, but what I should do in response.

Is it possible to also point users at a hypernews / e-group / twiki page which explains how to get the dataset on disk?

Sorry for bikeshedding here!  Hopefully it's worth the extra time.

**Comment by belforte** [comment]
I was thinking about it. But we do not have an up-to-date doc. telling users to contact DDM.
Since details there may change I'd rather not put them in the code.
Could point to Workbook and hope it gets updated, or tell them to contact their physics group.

**Comment by mmascher** [comment]
Actually I would like to keep the distinction between frontend and backend in the error messages. I know, for many users this does not mean anything, but for the few users who listen to the CRAB3 talks or knows a little bit about CRAB3, it might give an hint on where the error was. Furthermore, this also helps developers and operators imho: they know which logs they have to look (e.g., I know if I have to look for the REST interface logs, which are copied from CMSWEB to vocms22, or the TaskWorker logs on vocms052)

For the error message, new try:

```
[mmascher@lxplus0115 wf]$ crab st
Task name:			150411_104843:mmascher_crab_testecmmascher-dev6_136
Task status:			FAILED
Error during task injection:	The CRAB3 server backend could not submit the task because there is no DISK replica for dataset /WGstarToLNu2E_TuneZ2star_8TeV-madgraph-tauola/Summer12-START50_V13-v2/GEN-SIM.Please, check DAS, https://cmsweb.cern.ch/das, and make sure the dataset is accessible at some site disk (CRAB3 cannot analyze dataset on TAPE).
You might want to contact your physics group if you need a disk replica.
N.B.: your dataset is stored at T1_US_FNAL_Buffer,T1_US_FNAL_MSS, but those are TAPE locations.
```

**Comment by belforte** [comment]
hi @mmascher 
need to make a distinction.
Nothing wrong with :
Internal CRAB error, TW thread threw an exception blah.. and more blah..
please reporto to <ourstandarde-mail> providing the full text of this message below..
followed by traceback , file names in webdir and all sort of jargon that makes YOUR life easier
and clearly none else will try to read at this point.

And for sure, if host name is needed in debugging, print it i the message, do not assume that we will always remember where TW runs etc.

But when CRAB3 detects that user did something wrong  nobody cares if it was detected by client,frontend/backend or by the blair witch. Now you wnat to make USER life easier, tell them what they did wrong and how to fix it. So:

Task name:          150411_104843:mmascher_crab_testecmmascher-dev6_136
Task status:            FAILED
Task could not be submitted because there is no DISK replica for dataset /WGstarToLNu2E_TuneZ2star_8TeV-madgraph-tauola/Summer12-START50_V13-v2/GEN-SIM.Please, check DAS, https://cmsweb.cern.ch/das, and make sure the dataset is accessible on DISK.
You might want to contact your physics group if you need a disk replica.
N.B.: your dataset is stored at T1_US_FNAL_Buffer,T1_US_FNAL_MSS, but those are TAPE locations.

I also prefer shorter messages. But on that up to you.

**Comment by belforte** [comment]
ah... by the way:
put a space at the and of dataset name before the dot, to make copy/paste easier.
Maximum friendlyness would be to put the URL for the dataset lookup in DAS rather then the URL for DAS, of course with the proper DBS instance (global/phys03/...).

**Comment by mmascher** [comment]
@belforte maybe it is done already, try on a dataset on tape and check message

**Comment by belforte** [comment]
this is indeed fixed. Message now say:
```
Failure message:		Task could not be submitted because there is no DISK replica for dataset /QCD_Pt-1800_Tune4C_13TeV_pythia8/Spring14dr-castor_PU_S14_POSTLS170_V6-v1/GEN-SIM-RECODEBUG . Please, check DAS, https://cmsweb.cern.ch/das, and make sure the dataset is accessible on DISK You might want to contact your physics group if you need a disk replica.
				N.B.: your dataset is stored at T0_CH_CERN_Export,T0_CH_CERN_MSS, but those are TAPE locations.
```
