### ISSUE TITLE
Add a warning message when tasks are killed because they have too many failed jobs

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4460]
With this feature in CRAB3 tasks are killed when at least 10% of the jobs are failing. However this is not reported to the users. and can cause confusion (see https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/193.html)

We should add a warning to the REST interface and report it to the users  when this happens

**Comment by belforte** [comment]
since we never use this....

**Comment by belforte** [comment]
this is now an expert-only feature and clearly labelled as such in the documentation  and with a warning printed [1] to users who want to use it. In that case they'll figure out.
[1] https://github.com/dmwm/CRABClient/issues/4719
