### ISSUE TITLE
improve status report

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4484]
look at this example. 3 things are bad.
1. task is FAILED yet some jobs are still running, maybe it was supposed to be 60% FAIL ?
2. there is no indication of what/where those failures are
3. when I try to killl it with crab kill it tells me that I need to give a task name, yet there is no
  line in this output which says which that name is, indeed using the Task name as below
   141103_111250_crab3test-2:belforte_crab_20141103_121246 fails and what it really
 wants is the task directory  crab_20141103_121246 

(screen crab3)TC3> crab st
Task name:                      141103_111250_crab3test-2:belforte_crab_20141103_121246
Task status:                    FAILED
Glidemon monitoring URL:        http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=141103_111250_crab3test-2%3Abelforte_crab_20141103_121246
Dashboard monitoring URL:       http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=belforte&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=141103_111250_crab3test-2%3Abelforte_crab_20141103_121246
Details:                        cooloff        10.0% ( 1/10)
                                running        20.0% ( 2/10)
                                transferring   70.0% ( 7/10)

No publication information available yet
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20141103_121246/crab.log
(screen crab3)TC3>

**Comment by mmascher** [comment]
We still need to do the first bullet.

**Comment by belforte** [comment]
long solved
