### ISSUE TITLE
crab kill is not killing jobs on schedd!

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4500]
crab kill command is not killing jobs on schedd and they are still running and I cannot force kill them sending again crab kill command.

**Comment by juztas** [comment]
crab kill works fine in 8.3.2 HTCondor version. It kills all jobs and sets corresponding status in node_state file. I will close this issue when we will have 8.3.2 version in all schedds.

**Comment by mmascher** [comment]
Closing the issue. Condor 832 deployed last week fixed
