### ISSUE TITLE
Move check about inputDataset and PrivateMC to the server 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4512]
Look at this user problem report:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/257/1/1.html

text pasted below for convenience:

*** Discussion title: Computing Tools

Hi,

Thanks for the quick response.

> 1.what is the input dataset and the splitting configuration
> in crab configuration file ?

/RelValTTbar_14TeV/CMSSW_6_2_0_SLHC20-DES23_62_V1_UPG2023SHNoTaper-v1/GEN-SIM
config.Data.splitting = 'EventBased'
config.Data.unitsPerJob = 200
config.Data.totalUnits = 9000

> 2. how was the input dataset obtained and how sure we are
>  that it has no duplicates to begin with ?

It's RelVal.
I've checked that it doesn't have any duplicates, but the events are in a funny order, not contiguously.  E.g. /store/relval/CMSSW_6_2_0_SLHC20/RelValTTbar_14TeV/GEN-SIM/DES23_62_V1_UPG2023SHNoTaper-v1/00000/28EAC556-BD5F-E411-90FB-0025905A60D2.root has events in the order
601-700, 801-900, 1301-1400, 2001-2100, 4001-4100, 4701-4800, 4901-5000, 5301-5500, 6001-6200, 8001-8100

The full set of files has the events numbered 1-9000 but jumbled up in chunks of 100 (sometimes 200) between the files.  No idea why but it's relval so presumably made in a standard way.

> 3. what is the crab task which ran on that datset with the
>    indicated splitting parameters ? Can you point at it
>   and post log ?

http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=879836 <http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=879836&gt;
Logs are still on glidemon, e.g. for job 2
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms841/141114_093645_crab3test-2:grimes_crab_RelValTTbar_14TeV_138xx_140PU_SLHC20p1_DIGI_v06/job_out.2.0.txt <http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms841/141114_093645_crab3test-2:grimes_crab_RelValTTbar_14TeV_138xx_140PU_SLHC20p1_DIGI_v06/job_out.2.0.txt&gt;
and
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms841/141114_093645_crab3test-2:grimes_crab_RelValTTbar_14TeV_138xx_140PU_SLHC20p1_DIGI_v06/postjob.2.0.txt <http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms841/141114_093645_crab3test-2:grimes_crab_RelValTTbar_14TeV_138xx_140PU_SLHC20p1_DIGI_v06/postjob.2.0.txt&gt;

> 4. was the result published in DBS ? If so, which is the dataset
>    and does that show duplicates ?

/RelValTTbar_14TeV/grimes-138xx_140PU_SLHC20p1_DIGI_v06-56e4068627e7081ea7bfe109bd6becfb/USER

DAS doesn't show any indication of duplicates but I don't know where it would show that information.  It's only when I run on all the files that CMSSW starts complaining of duplicate events.  Whether it's just that the events are numbered incorrectly or they're actually duplicates I don't know.

Thanks,

Mark.

 [ MIME part of type text/html without a name stripped ]

-------------------------------------------------------------
Visit this CMS message (to reply or unsubscribe) at: 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/257/1/1.html

**Comment by AndresTanasijczuk** [comment]
A protection was added in the client: if a user specifies JobType.pluginName = 'PrivateMC' then we don't allow him to specify Data.inputDataset (we suggest him that if he really wants to run over an input dataset, then he has to set JobType.pluginName = 'Analysis'). Should we have a similar protection in the server?

**Comment by mmascher** [comment]
Yes that woulb be better imho, let's keep the ticket for the server side
changes then. Low priority.
