### ISSUE TITLE
Tutorial documentation

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4518]
Two issues I noticed when running through the crab tutorial:

1) I'm sure "echo $0" is wonderfully hack-ish, but echo $SHELL is much easier to remember. Can you change that?
2) cd /afs/cern.ch/<work|user>/<first-letter-of-username>/<username>/ is just a fancy and CERN specific way of writing "cd ~"

**Comment by AndresTanasijczuk** [comment]
All the comments in this issue have been taken care of when preparing for the basic tutorial from May 2015.
