### ISSUE TITLE
Configure input sandbox size?

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4520]
A couple of the LPC people have said they find the 100 MB sandbox size limiting and it would be nice to have a way to increase that. i don't think we have a hard limit from the infrastructure like we did in the gilt days, so can we think about this?

The other comment made be a user was that in his case each job only needed one or a few of his inputFiles but in the aggregate they went over 100 MB since we don't have a way to do this. That's a hard problem.

@annawoodard , no need to worry about ticketing this.

**Comment by belforte** [comment]
no. we do not make this configurable.
