### ISSUE TITLE
Target_SE value for dashboard ?

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4521]
@belforte @mmascher @AndresTanasijczuk 

If task is submitted with whitelist T2_KR_KNU, but this dataset can run almost on all sites and TargetSE shows almost all sites. Maybe it should be only T2_KR_KNU? Or I misunderstood this ?

https://github.com/dmwm/CRABServer/commit/43029fb1b9ad3685a6493eccd1996ae64ad57f35

```
2014-11-19 21:44:02,848:DEBUG:DagmanSubmitter:Dashboard job info: {'TargetSE': 'T1_IT_CNAF,T1_ES_PIC,T2_AT_Vienna,T2_CH_CSCS,T2_UA_KIPT,T2_US_Purdue,T2_FI_HIP,T2_UK_SGrid_RALPP,T2_FR_GRIF_LLR,T2_ES_IFCA,T2_DE_RWTH,T2_UK_SGrid_Bristol,T2_FR_IPHC,T2_KR_KNU,T2_DE_DESY,T1_UK_RAL,T1_US_FNAL,T2_IT_Legnaro,T2_US_Caltec
h,T2_UK_London_Brunel,T2_IT_Pisa,T2_US_Vanderbilt,T2_EE_Estonia,T2_IN_TIFR,T2_TW_Taiwan,T1_DE_KIT,T2_IT_Rome,T2_RU_IHEP,T1_FR_CCIN2P3,T2_US_Florida,T2_TH_CUNSTDA,T2_UK_London_IC,T2_IT_Bari,T2_US_Nebraska,T2_FR_CCIN2P3,T2_US_UCSD,T2_ES_CIEMAT,T1_RU_JINR,T2_US_Wisconsin,T2_HU_Budapest,T2_CN_Beijing,T2_US_MIT,T2_BE
_IIHE,T2_CH_CERN,T2_PT_NCG_Lisbon,T2_PL_Swierk,T2_BR_SPRACE', 'ApplicationVersion': 'CMSSW_7_0_4', 'localId': '', 'resubmitter': 'sciaba', 'tool': 'crab3', 'scheduler': 'GLIDEIN', 'broker': 'vocms052.cern.ch', 'jobId': '31_https://glidein.cern.ch/31/141119:204321:crab3test-1:sciaba:HC:99:T2:KR:KNU:20141119125501
_0', 'tool_ui': 'vocms052.cern.ch', 'StatusValue': 'pending', 'JSToolVersion': '3.3.0', 'user': 'sciaba', 'taskId': '141119_204321_crab3test-1:sciaba_HC_99_T2_KR_KNU_20141119125501', 'taskType': 'analysis-crab3', 'CMSUser': 'sciaba', 'bossId': '31', 'vo': 'cms', 'datasetFull': '/GenericTTbar/HC-CMSSW_7_0_4_START
70_V7-v1/GEN-SIM-RECO', 'exe': 'cmsRun', 'sid': 'https://glidein.cern.ch/31/141119:204321:crab3test-1:sciaba:HC:99:T2:KR:KNU:20141119125501', 'GridName': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=sciaba/CN=430796/CN=Andrea Sciaba', 'SubmissionType': 'crab3'}

```

**Comment by belforte** [comment]
I suspect this is not a problem anymore. Assign to myself to remind me to check.

**Comment by belforte** [comment]
Review of status:
conclusion of the discussion was : report DESIRED_Sites list to dashboard as Target_SE
but looks like this was not done (no ptr to a committ in this issue)
Therefore: still open

**Comment by mmascher** [comment]
What is this gonna be used for in dashboard? I am wondering if it has to be DESIRED_Sites or the new DESIRED_DataLocations

**Comment by belforte** [comment]
in dashboard is used to indicate where jobs are expected to run
so DESIRED_Sites is more appropriate then DESIRED_DataLocations since the latter is before black/white lists
of course with overflow the execution site may be one not among DESIRED_Sites, but I will not try to redesign dashboard as long as we overflow <=20% of the jobs

**Comment by belforte** [comment]
I tried to understand what exactly is reported now.
Apparently all work is done in
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py
Staring point is `availablesites` here
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L683
But after ten minutes I was lost in following input arguments through calls, expecially when it comes to the usual (self, *args, **kw) which I never digest.. so I gave up.
Though I have a weak feeling that this `availablesites` here
 https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L462
which maybe, maybe.. is what is used as DESIRED_Sites in JDL but I see that in PreJob.py bw lists are applied again... I am very confused.

**Comment by belforte** [comment]
assign back to Marco as it is above my current understanding of the code

**Comment by belforte** [comment]
I think in the end we keep what we have, dashboard-wise
