### ISSUE TITLE
In new cmscp, use RESTInteractions.py for the logs metadata upload.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4539]
I couldn't use RESTInteractions.py because of failure importing pycurl. I am instead using the Requests class from WMCore (from WMCore.Services.Requests import Requests).

**Comment by belforte** [comment]
@AndresTanasijczuk explained me:
this is about writint filemetadata to Oracle.
when done from the postJob it is done using RESTInteractions.py
now Andres added this also in the WN (so it is done sooner) but had to use a different method.

Would be good to unify using same code everywhere.

**Comment by belforte** [comment]
in ASO on Oracle era, metadta will only be uploaded from postjob
