### ISSUE TITLE
Don't stageout to /store/temp/ logs or outputs if corresponding transfer flag is False. 

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4572]

**Comment by belforte** [comment]
quick questions:
1. by default we never save full logs, right ?
2. comments in the commit say "when runinng scriptExe there are no cmsRun-stdout.log",
    but stdout/stderr from scriptExe needs to be saved (trimmed) exactly like for cmsRUn,
    what is done then ?

**Comment by AndresTanasijczuk** [comment]
1. Right.
2. The comment in the commit should actually be "when runinng scriptExe there might not be a cmsRun-stdout.log file..." because the scriptExe can actually run cmsRun inside the script and we do would have the log file. What we currently do: https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L270-273

**Comment by belforte** [comment]
the comment seems clear,  but I am still wondering where does the stdout of scriptExe go

**Comment by AndresTanasijczuk** [comment]
I just looked in more details the scriptExe code, and actually stdout of scriptExe goes also to a log file called cmsRun-stdout.log. See https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L559. If we wouldn't specify logName = 'cmsRun-stdout.log' in that line, the default name 'scramOutput.log' would be used (see https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Tools/Scram.py#L220-221).
What we didn't have originally (when scriptExe was first introduced) was a cmsRun-stderr.log file. So the comment in the comment should have been "when runinng scriptExe there might not be a cmsRun-stdout.err file". Then Marco made a patch so that we also have a cmsRun-stderr.log file: https://github.com/dmwm/CRABServer/commit/c3f1d83f1105b9dea19e0fbc858a6e6d45d83d35.
@mmascher, if I read the code correctly, we always have now a pair of log files cmsRun-stdout.log and cmsRun-stderr.log when running scriptExe?

**Comment by belforte** [comment]
it is a bit disgusting that the user's application is run by a script called Scram.py
(whether the application is cmsRun or scriptExe does not matter), but good naming is a tricky art.
but other then that it seems all OK then. The fact that stderr is piped to stdout rather then
put on a different file is a matter of taste, but in general would be better to preserve the
distinction and leave it to the user to combine streams. Also it would be better to fix cmscp.py
to deal with missing stderr, rather then forcing code here to know the detailed failure modes
of something else :-(

**Comment by AndresTanasijczuk** [comment]
Currently, if cmsRun-stderr.log (or cmsRun-stderr.log) is missing, cmscp will just not include it is the logs archive. What do you exactly mean by "fix cmscp to deal with missing stderr" ?

**Comment by belforte** [comment]
that sounds fine. then why bother to create an empty one ?
Maybe I misunderstood. Sorry.

**Comment by AndresTanasijczuk** [comment]
Before, cmscp was failing if it was not finding cmsRun-stderr.log or cmsRun-stderr.log. I think Marco and I implemented fixes, independently, more or less at the same time. I changed cmscp so that it doesn't fail if it doesn't find cmsRun-stderr.log or cmsRun-stderr.log and Marco changed scriptExe to always have a cmsRun-stderr.log file.
