### ISSUE TITLE
Add user-defined column to taskDB

### ISSUE THREAD

**Issue by PerilousApricot** [dmwm/CRABServer#4576]
For some API functionality, it would be real convenient to have a 32-byte column in the taskDB that's exposed via the API in a "getTaskByID" call. I'll implement, just wanted to get people's opinions before I started the work

**Comment by mmascher** [comment]
Hi @PerilousApricot , any comment on that?

**Comment by belforte** [comment]
no reply from @PerilousApricot since soooo long. Let's assume it is not really useful. Reopen with details if needed.
