### ISSUE TITLE
Report more info to Dashboard from FJR

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4587]
From hypernews :
```
From the CRAB3 side we are reporting following information when the job
finishes:

{'MonitorID':
'141204_190425_crab3test-5:jbalcas_crab_HG1412-4-TFile_Analysis_LumiBased-L-T_O-F_P-F_IL-F',
'NoEventsPerRun': 1700, 'MonitorJobID': '1_
https://glidein.cern.ch/1/141204:190425:crab3test-5:jbalcas:crab:HG1412-4-TFile:Analysis:LumiBased-L-T:O-F:P-F:IL-F_0
', 'CrabCpuPercentage': 0.8599391304347827, 'CrabUserCpuTime': 98.893,
'NEventsProcessed': 1700, 'ExeTime': 115, 'JobExitCode': 0,
'NbEvPerRun': 1700, 'ExeExitCode': 0}

CRAB3 basically look into 4 things in FJR (TotalJobTime, TotalJobCPU,
exitCode, events) and fills:

JobExitCode and ExeExitCode are the same and are exitCode of the job.
ExeTime is the TotalJobTime from the FJR.
CrabUserCpuTime is taken from TotalJobCPU
CrabCpuPercentage -> CrabUserCpuTime divided ExeTime if both exists.

If we have in FJR input source, we are reporting events as parameters :
NoEventsPerRun, NbEvPerRun, NEventsProcessed

https://github.com/dmwm/CRABServer/blob/c792ad316cb6b9fe10f1b2ff7b500bca2e26d29d/scripts/CMSRunAnalysis.py#L132-L152

There is also the popularity report, which sends :

{'Basename':
'/store/mc/HC/GenericTTbar/GEN-SIM-RECO/CMSSW_5_3_1_START53_V5-v1/0010',
'inputFiles':
'/00CE4E7C-DAAD-E111-BA36-0025B32034EA.root::1::EDM::Local::1',
'BasenameParent': '', 'inputBlocks':
'/GenericTTbar/HC-CMSSW_5_3_1_START53_V5-v1/GEN-SIM-RECO#289639b0-146f-411b-a220-fcdff0a13cd9',
'parentFiles': ''}
===========================================
I think we should add few more parameters. We should agree which ones to
add and unify with the WMAgent reporting.
We should definitely report peakRss. Probably the number of output events
as well.  Maybe the number of cores used (at some point analysis might go
multicore) and probably some I/O statistics to understand the I/O data
volume.
```
More details : https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/1975/1/1/1/1/1/1/1.html

**Comment by hernand** [comment]
getting back to this. Here is a basic proposal to add few parameters. We can add more later if needed:

- PerformanceSummary Metric="ApplicationMemory" Metric Name="PeakValueRss" (maximum value of used RSS by the job)
- PerformanceSummary Metric="StorageStatistics" Metric Name="Timing-tstoragefile-read-totalMegabytes" (total volume of input data)
- PerformanceSummary Metric="StorageStatistics "Metric Name="Timing-tstoragefile-write-totalMegabytes" (total volume of output data)
-NEventsWritten (number of events written to storage by the job)

I would remove the reporting of NoEventsPerRun, NbEvPerRun as they contain the same information as NEventsProcessed

There a are a lot of storage statistics parameters, but according to the twiki https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideStorageStats?redirectedfrom=CMS.SWGuideStorageStats 
tstoragefile:read and the tstoragefile:write are the most significative ones reporting inclusive numbers. It is probably not possible in the general case to distinguish between data read from local disk/LAN/WAN. I've started a thread in the framework HN forum with no response so far: https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3415.html

**Comment by juztas** [comment]
Hi @hernand 
I started to debug how these numbers from fjr comes to json and this is what I find out and what we have:
```
Storage statistics:
%s - Read method
readTotalMB = Timing-%s-read-totalMegabytes + Timing-%s-readv-totalMegabytes
readMBSec = Timing-%s-read-totalMsecs + Timing-%s-readv-totalMsecs
readAveragekB = 1024* readTotalMB / (Timing-%s-read-numOperations + Timing-%s-readv-numOperations)
readMaxMSec = Timing-%s-read-maxMsecs + Timing-%s-readv-maxMsecs
readPercOps = Timing-tstoragefile-readActual-numOperations / Timing-tstoragefile-read-numOperations
readTotalT = 1000 * Timing-tstoragefile-read-totalMSecs
readNOps = Timing-tstoragefile-read-numOperations
writeTime = 1000 * Timing-tstoragefile-write-totalMsecs

%s - writeMethod
writeTotMB = Timing-%s-write-totalMegabytes + Timing-%s-writev-totalMegabytes
readCachOps = Timing-tstoragefile-readViaCache-numSuccessfulOperations / Timing-tstoragefile-read-numOperations
```
I would report everything (readTotalMB, readMBSec, readAveragekB, readMaxMSec, readPercOps, readTotalT, readNOps, writeTime) and do we want to separate readTotalMB(Timing-%s-read-totalMegabytes and Timing-%s-readv-totalMegabytes) and writeTotMB (Timing-%s-write-totalMegabytes and Timing-%s-writev-totalMegabytes) ?

**Comment by hernand** [comment]
I would report quantities that we are sure are meaningful and useful. E.g. I'm not sure what readv is. But if you are sure those quantities are useful and make sense, go ahead. 
Yes, we want to separate readTotalMB from writeTotMB. The output is normally different than the input, or is you question different?

**Comment by juztas** [comment]
Now readTotalMB = Timing-%s-read-totalMegabytes + Timing-%s-readv-totalMegabytes
And separate meaning 
readTotalMB = Timing-%s-read-totalMegabytes
readvTotalMB = Timing-%s-readv-totalMegabytes

readv - http://en.wikipedia.org/wiki/Vectored_I/O

**Comment by hernand** [comment]
In the end I think the important quantities are the total amount of data read and written, so not sure if it is worth reporting separately serial and vector reads/writes

**Comment by mmascher** [comment]
For reference: https://github.com/dmwm/CRABServer/issues/4450

That's what we were talking about Monday at the meeting, for the moment some PSet settings are turned off (e.g.: SimpleMemoryCheck). They might contain useful information we want to report.

**Comment by hernand** [comment]
what I understood from Monday, the problem with SimpleMemoryCheck is that it spits out information to the log which can cause some trouble? I think reporting peakRSS might be useful to see which fraction of the jobs get killed due to excessive RAM consumption.

**Comment by mmascher** [comment]
Yes, but there should be a way to add it so that it does not log. We have to investigate how to do that.

I would like to warn that right now also the CPU and Timing report are diabled https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L316-L317

**Comment by juztas** [comment]
Taking note here, and will ask Julia are these names will be ok for Dashboard.

CRABUserPeakRss - maximum value of used RSS by the job
CRABUserReadMB - total volume of input data
CRABUserWriteMB - total volume of output data

**Comment by juztas** [comment]
@mmascher can you review, Julia said it is fine. 

And reply to your comment https://github.com/dmwm/CRABServer/issues/4587#issuecomment-77124869
I think this is what we need: 
```
process.SimpleMemoryCheck=cms.Service("SimpleMemoryCheck", jobReportOutputOnly = cms.untracked.bool(True))
```
Tested it and it is not printing in the logs Memory usage, but it saves in FJR which we can use
