### ISSUE TITLE
Need exit code for file metadata upload failure.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4589]

**Comment by mmascher** [comment]
@AndresTanasijczuk will decide a number and he will add it to the twiki. @belforte suggestions?

**Comment by belforte** [comment]
we already have: 
60320 - Failure to communicate with ASO server 
can it do ?
is this a failure on the WN or on in the postjob ?

if it is in the WN, I'd classify as job wrapper failure, i.e. create 80001

**Comment by AndresTanasijczuk** [comment]
@belforte File metadata upload is done from the WN for the logs archive, but if this fails it is retried from the post-job. For output files, the file metadata upload is done from the post-job. File metadata is uploaded to the Oracle database, not CouchDB nor ASO server, so 60320 doesn't fit.

**Comment by AndresTanasijczuk** [comment]
I finally used 80001 in cmscp for file metadata upload failure, but currently this exit code is not observed anywhere since file metadata upload can be retried in the post-job, and any failure in the post-job is not shown with an exit code but with "Post-processing failed". I am closing this issue.
