### ISSUE TITLE
PostJob does not get the right state of a couch doc when reinjected from WN.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4592]
See this task: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=dfehling&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=141210_211208_crab3test-1%3Adfehling_crab_TTBar_Powheg7_trigger
See for example job number 3, retries 0 and 1 (i.e. attempts 1 and 2 in dashboard language). Attempt 1 failed in the upload of the output file metadata (well actually it didn't fail, but that's another ticket), but the transfer was ok. In attempt 2 cmscp sees that the document is already in Couch with status = 'done', but our policy is to re-inject a transfer request for each job retry, so it re-injects the document to Couch from WN with status 'new'. The PostJob retrieves the document from Couch and sees status 'done' instead of 'new' (seems it got a cached state, not the actual state) and then when queries the view "JobsIdsStatesByWorkflow" it gets the 'new' status, but in other jobs from this task it happened that it again sees 'done' and of course thinks that the transfer was really done, and continues without monitoring if the transfer was performed successfully or not). The strange thing is that although the status seems to not be the actual status, the start_time seems ok. Following in private e-mail with Hassen.

**Comment by mmascher** [comment]
Is this going to be solved with https://github.com/dmwm/CRABServer/issues/4605, or is this another issue ?

**Comment by AndresTanasijczuk** [comment]
Is the same issue. But I would keep both tickets open.

**Comment by AndresTanasijczuk** [comment]
I expect that we should not suffer from this problem anymore, because now the ASO view returns also the 'start_time' and the PostJob checks if that 'start_time' is the same as in the document (the start_time from the document is saved in the job_report.json file) to make sure the results returned by the view are not stale. 
Since this issue was really rare and it is hard to reproduce, and since I (and I think Marco also) feel confident that it is solved, should we close the issue and eventually reopen if we see the problem happening again?

**Comment by mmascher** [comment]
Yes!
