### ISSUE TITLE
crab resubmit --jobids seems to not work

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4595]
In this computing-tools thread
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/300.html
the user reported that the --jobids option doesn't work in the resubmit command. The client is sending the list of jobs to resubmit correctly. So is a server issue. I am almost sure --jobids was working before. Has anything changed? BTW, I am working on the resubmit command these days.

**Comment by mmascher** [comment]
Andres will check if it works and close the issue if it's the case.

**Comment by AndresTanasijczuk** [comment]
@mmascher You can close this issue. This should have been fixed in #4711
