### ISSUE TITLE
crab report shows "0 files have been processed" for tasks with non-EDM outputs

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4604]
The problem is that for POOLIN files, there are no 'parents'. One should instead take the 'lfn' in https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/report.py#L58
which requires to add in
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L227-231
a line
'lfn' : row[GetFromTaskAndType.LFN]
And one has to be careful, because the 'lfn' in the FMD for input files contains an additional "_<jobid>" https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L1183
so the algorithm in https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/report.py#L54
has to remove that postfix.

**Comment by mmascher** [comment]
That's fixed now.
