### ISSUE TITLE
use executed_site in cmscp::inject_to_aso when can not map SEName using phedex node map

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4607]

**Comment by belforte** [comment]
IIUC you want to use $GLIDEIN_CMSSite and report it to the dashboard via the SyncSite key:
https://github.com/dmwm/CRAB2/blob/da353266500faee40f4892529f346b03c158ba3a/python/SchedulerGrid.py#L205

this is the CMS Site Name set by the factory, which we use for matching.
It is true that it is the same as in local site configuration file, but adding the code to parse that file is likely an overkill.

**Comment by belforte** [comment]
now we always use PNN andnever mape SEName, so this should never happen again, whatever it was.
