### ISSUE TITLE
cmscp exits with 80000 if no output file is produced

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4610]
I think the problem is when we split the output files using this regular expression https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1140-L1141

The output files are `['']` and we are iterating over an empty string. Hence, the `ERROR: Invalid output format ().` error in the logfile. In fact:

```python
>>> s = re.compile(",\s*")
>>> s.split("")
['']
```

See http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0114.cern.ch/mon/cms1056/150105_101232_crab3test-5:melsawy_crab_background_80doubleoffonly/job_out.1.0.txt and  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/297/1/1.html

**Comment by AndresTanasijczuk** [comment]
To avoid merge conflicts, I added the fix for this issue in the pull request #4609

**Comment by mmascher** [comment]
Great, closing this.
