### ISSUE TITLE
Use chirp to report full exit code as a classAd

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4615]
Eventually we want ot get rid of the `short exit code = 65` thing. For that I believe we need to modify the `ExitStatus` classad, please correct me if I am wrong.

Notice that the client is already reporting the right exit code (it is taken from the framework job report). This is an example taken from I user task I `remake` on my lxplus account (*). So I am not sure why the dashboard is showing the short one, probably we are taking the wrong exit code? But I think it will be corrected if we chirped the long exit status, which we need to do for glidemon.

(*)
```
[mmascher@lxplus0078 wf]$ crab remake --task=150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Enter GRID pass phrase for this identity:
Contacting voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=voms2.cern.ch] "cms"...
Remote VOMS server contacted succesfully.


Created proxy in /tmp/x509up_u8440.

Your proxy is valid until Sat Jan 10 10:54:28 CET 2015
WARNING: Incompatible CRABClient version "development"
Server is saying that compatible versions are: ['3.3.12', '3.3.12.patch1', '3.3.12.rc7']
Remaking crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola folder
Remaking the .requestcache for 150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Success: Finish making crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/.requestcache
Log file is /afs/cern.ch/user/m/mmascher/wf/crab.log


[mmascher@lxplus0078 wf]$ crab status crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
WARNING: Incompatible CRABClient version "development"
Server is saying that compatible versions are: ['3.3.12', '3.3.12.patch1', '3.3.12.rc7']
Task name:			150108_113454_crab3test-2:vormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Task status:			FAILED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150108_113454_crab3test-2%3Avormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=vormwald&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150108_113454_crab3test-2%3Avormwald_crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola
Details:			failed        100.0% (16/16)

No publication information available yet

Error summary:
16 jobs failed with exit code 8001:
	CmsRunFailure
	CMSSW error message follows.
	Fatal Exception
	An exception of category 'PluginNotFound' occurred while
	   [0] Constructing the EventProcessor
	Exception Message:
	Unable to find plugin 'PileupJetIdProducer'. Please check spelling of name.

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes
Log file is /afs/cern.ch/user/m/mmascher/wf/crab_GluGluToHTohhTo2Tau2B_mH-260_mh-125_8TeV-pythia6-tauola/crab.log
```

**Comment by belforte** [comment]
dashboard does not look at condor classAd, if it says 65 it must be because Crab3 sends it, 
somewhere, somehow. Need to check all places where it is reported.
In my understanding the full exit code in the class ad was only needed for:
1. glidemon
2. quick monitoring via condor_q like in James pages and/or interactive debugging/troubleshooting

**Comment by mmascher** [comment]
Ok, thanks stefano. Now that I think a little bit, I am not sure it is `ExitStatus` that we need to modify. If we did it, it will probably be rewritten once we exit the job wrapper here https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L158

So we probably need to create a new classad for glidemon and understand why we are reporting to dashboard the wrong code.

I assigned this to you stefano. Imho we should call `condor_chirp` here https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1895, before exiting cmscp. Notice that cmscp is called even when the job wrapper fails. The only thing I am not sure is if we have the full exit code and or the short one in this case.

To test (and develop) this I would send a normal task using the production client and server, and then use these instructions https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#To_run_the_job_wrapper_and_the_s to run the job wrapper. Since you need chirp, you will probably need to run the wrapper on the schedd instead of on lxplus as indicated in the twiki (we only tested the instructions on lxplus though..)

**Comment by belforte** [comment]
ah.. I got my homework then. so I learn to keep my mouth shut :-)
as my daughter says every time she's reproached: I will do my best.
thanks for the tips.

**Comment by mmascher** [comment]
Ahah, that's not a punishment, but an opportunity to learn something ;)

Adding some comments from hypernews before they got lost:

```
To find the condor_chirp binary, you'd need to do something like this in the startup script:
export PATH="$PATH:`dirname $CONDOR_CONFIG`/main/condor/libexec"
```

**Comment by belforte** [comment]
more details in the HN thread:
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2252/1/1/1/2.html

**Comment by belforte** [comment]
I finally mastered scriptExe and made chirp work in a test job. We also need to place
+WantIOProxy = true
in the submit description file of the job.
see  http://research.cs.wisc.edu/htcondor/manual/current/condor_chirp.html
We need to defina a new classAd name, IIUC current usage, I propose:

condor_chirp set_job_attr JOB_Exit_Status 666666

**Comment by bbockelm** [comment]
Hi,

Nope - you probably don't want +WantIOProxy.  That enables a very non-scalable mode of updates to the schedd (blocking and synchronous).

You probably want to use:

condor_chirp set_job_attr_delayed CHIRP_JOB_Exit_Status 6666666

(for various security reasons, these updates must start with "Chirp").

This will utilize the same update mechanism as things like memory / CPU usage and will piggyback the information on the next update.  Hence, the "delayed" in the verb: it can take 5-15 minutes to get to the schedd.

However, since the job is just about to exit, the final update is about to go out anyway and the delay will be short.

Brian

**Comment by belforte** [comment]
thanks @bbockelm !!
I was fearing so and did not like the taste of +WantIOProxy. Good that you pointed this out.
And clearly I did not read down enough in the manual. Sorry.
OTOH the maual does not mention that attr. must start with CHIRP_
I will change accordingly to your indicatins, of course.

My comment was mostly a hurrah scream at my being able to run customized crab TaskWorker with my scriptExe on my VM. Glad it turned out so useful.

**Comment by belforte** [comment]
I tested this in a couple jobs and it works (yeah.. as expected)

export PATH="$PATH:`dirname $CONDOR_CONFIG`/main/condor/libexec"
condor_chirp set_job_attr_delayed CHIRP_JOB_Exit_Status 666666

**Comment by bbockelm** [comment]
Note that @hufnagel has been working similarly in this area.  I think we want two different values, really:
1.  The CMSSW exit code from the FJR.  If we can reuse the WMCore code (not clear, given the differences in how WMRuntime is used), that'd be great.  At the minimum, we should reuse the attribute name.
2.  The exit status returned to Dashboard.  This would include things like stageout failures and failures of the job to even start CMSSW.

**Comment by hufnagel** [comment]
CHIRP_JOB_Exit_Status shouldn't work as an attribute name. The attribute name has to start with Chirp(case sensitive) and according to @bbockelm can only contain alphanumeric characters, so no '_" I assume (although condor_chirp returned exit code 0 for me even with an attribute name like 'Chirp_cmsRun_ExitCode'. Also to keep in mind, at runtime the job exit code is not easily available, you can only report step related parameter (so cmssw exit codes are fine, job exit codes are not).

Already implemented in the WMCore runtime, see #6618

**Comment by bbockelm** [comment]
Ah - indeed, `CHIRP_*` shouldn't work.  Actually `_` is fine, but I didn't want to start enumerating "good" versus "bad" characters (there is a formal definition for ClassAd, but I'd prefer to avoid exploring things).

Within CRAB3, the _job_ exit code should be easily available since we report it straight from the CRAB3 job wrapper to Dashboard (I think this is different from WMAgent?).

**Comment by mmascher** [comment]
Hi, we already report to dashboard two exit codes, one for CMSSW and one for the jobwrapper. But note that we made an effort in CRAB3 to only have one exit code: if CMSSW exits with `<>0` that's what we want as an exit code and what we report to dashboard (it's what the user really care). Basically, if CMSSW exits with <> 0 then the jobwrapper exit code becomes the CMSW exit code. The reason is that having two exit codes is confusing for users.

**Comment by mmascher** [comment]
I named the parameter `Chirp_CRAB3_Job_ExitCode`. Not sure who would like to review this..

**Comment by hufnagel** [comment]
One comment, are you sure you can just use $LONG_EXIT_CODE and $EXIT_STATUS as condor_chirp arguments ? It's a bit picky as far as quoting rules are concerned. Since these are numbers, maybe it's ok.

**Comment by mmascher** [comment]
Hi @hufnagel , AFAICT with numbers condor_chirp does not complain

**Comment by belforte** [comment]
it was tested wuth numbers already, up in this page
https://github.com/dmwm/CRABServer/issues/4615#issuecomment-147632228

**Comment by belforte** [comment]
ref. https://github.com/dmwm/CRABServer/pull/5162
