### ISSUE TITLE
Remove condor_q call on dag bootstrap

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4616]
From Brian's mail here:  https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2252.html

```
3) HTCondor 8.3.2 writes $_CONDOR_JOB_AD for DAGMan jobs; this means the task job no longer needs to do a condor_q from the schedd.  This should be "as simple as" updating HTCondor.  However, we should verify that no condor_q actually occurs (can be done by integration; hopefully no patch needed).
```

I don't think we already have a ticket for this, but IIUC we can get rid of this call now: https://github.com/dmwm/CRABServer/blob/master/scripts/dag_bootstrap_startup.sh#L53-L59

**Comment by juztas** [comment]
@bbockelm 

a) Can we specify where to save and update $_CONDOR_JOB_AD file? I would think about saving it in spool directory
Spool directory `/var/lib/condor/spool/8206/0/cluster38206.proc0.subproc0` and now in beginning it saves .job.ad here : `/var/lib/condor/spool/local_univ_execute/dir_38206_0/.job.ad` but after some time this file does not exist anymore. If it would exist, we can get rid of this code aswell : https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L54-L66
b) crab kill works!
c) If crab kill is executed, we are not creating/updating error_json and error_summary. So in this case user will get Error summary as could not find exit code... And here we should report `Removed by user.`

```
[jbalcas@lxplus0157 src]$ crab status scale_test/crab_submit-4-scale163983/
Task name:			150117_201813_crab3test-9:jbalcas_crab_submit-4-scale163983
Task status:			KILLED
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150117_201813_crab3test-9%3Ajbalcas_crab_submit-4-scale163983
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=jbalcas&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150117_201813_crab3test-9%3Ajbalcas_crab_submit-4-scale163983
Details:			failed        100.0% (10/10)

No publication information available yet

Error summary:
Could not find exit code details for 10 jobs
```
