### ISSUE TITLE
Reduce CPU usage on the schedd by enabling PER_JOB_HISTORY_DIR

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4618]
Again from https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2252.html

5) Right now, we use up an inordinate amount of CPU time on the schedd parsing the job log for each post-job (the job log contains all job transitions for all jobs in a task; as a task progresses - or if it has many jobs - it takes a lot of CPU to parse this).  While the CPU time is "nice"d, it'd be a significant reduction in CPU usage if we didn't need to do this.  We parse the job log to find the ClassAd for all jobs run for a given node in the DAG (this allows us to avoid retries if the failures have already consumed more than X hours of CPU time).  Working with the HTCondor team, we came up with the following idea:
  - Enable the PER_JOB_HISTORY_DIR feature; this writes out the final job ad in a given directory.  (NOTE: if you turn this on, it is *very important* to have a cron job to clean up files >1 day old.  Otherwise, the directory quickly fills).
  - In the post job, read out the final job ad.  If it does not exist, wait 1 second and try again (NOTE: the retry avoids a race condition - DAGMan can launch the post-job as soon as the job terminates, which may be before the final job ad is written).  If it still does not exist, use the old code.
  - Append the job ad to a file named finished_jobs/$NODE.ad.  NOTE: you want to use a subdirectory here to avoid cluttering the parent directory.  You also want all jobs run from a single node to go into a single file.
  - At this point, you now have a file with ads for all the previously-run jobs for the given node.  Parse it into a list of ads; continue with the original logic.  NOTE: Some attribute names may have changed between the two different methods of getting the ad.  Validation will be needed.

**Comment by juztas** [comment]
one of the reasons why we need this if we want to increase max jobs running more than 10k
![cpu-load](https://cloud.githubusercontent.com/assets/646582/8116432/75e0630e-1082-11e5-941c-c6c6d81ea88a.png)

**Comment by PerilousApricot** [comment]
Is the top-left the per-core CPU usage (just curious). What tool is this?

**Comment by juztas** [comment]
I like this tool a lot (htop) ;) CPU Blue - niced; Green - normal threads; Red - kernel threads;

**Comment by PerilousApricot** [comment]
rad - thanks for the heads up and sorry for the thread jack :)

**Comment by annawoodard** [comment]
Woah, and you can scroll up and down and side to side through the list of processes! This is awesome, thanks @juztas
