### ISSUE TITLE
CRABServer does not exclude a down schedd 

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#4620]
I ran a condor_off to stop schedd at vocms058. I did it at collector machine vocms056 running the following command:

sudo condor_off -sched -fast vocms058.cern.ch

the schedd stopped immediately and then I tryed to submit some jobs against my own CRABServer that only points to vocms058 schedd and my CRABServer submitted the task anyway rather than fail and inform me the error.

**Comment by mmascher** [comment]
uhm, I have never used the condor_off command, what does it do? Also, did you get the same error when the TaskWroker submitted the job (doing the equivalent of a condor_submit)? If so, maybe you can try to do condor_submit by yourself and see what happen. If the submission succeds I don't know what we can do on the CRAB3 side.

**Comment by juztas** [comment]
Hi @mmascher. Assign this to me. What we tried to simulate, that if schedd is down, task was still submitted to crabserver and TW reported unable to locate crab3test-8 schedd. I was thinking that if CRABServer is unable to locate schedd, choose good one which is available and up and running.

**Comment by belforte** [comment]
Jadir, what did exactly fail (or not fail) ? Which submission was performed ? client to server ?
or TaskWorker to schedd ?
Expectation is that submission from client is performed and task is kept in Crab server DB
until some condor scheduler is available for submission.
Crab server should not refuse tasks only becasue no schedd is (temporarely) available.
The worst that I expect to happen is that TW tries to submit, fails, and task is marked as failed 
when it would have been enough to wait ten minutes. But that's a soft area for optimization.

**Comment by belforte** [comment]
condor_off shuts down all condor processes on the machine. condor_submit will fail, quickly and 
permanently, until next condor start.

**Comment by juztas** [comment]
@belforte, yes, this is what I was thinking `Crab server should not refuse tasks only becasue no schedd is (temporarely) available.` and now TW tried to submit, failed and marked task as failed

**Comment by jmarra13** [comment]
Hi Stefano,

The submittion was from client to server, here is the output of crab status:

WARNING: Incompatible CRABClient version "3.3.12.patch1" 
Server is saying that compatible versions are: [u'3.3.8', u'3.3.9.rc2', u'3.3.9', u'3.3.10', u'3.3.9.pre2']
Task name:			150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7
Task status:			FAILED
Error during task injection:	The CRAB3 server backend could not submit your jobs to the Grid scheduler. This could be a temporary glitch, please retry again later and contact the experts if the error persist. The submission was retried 5 times, these are the failures: ["Failed to submit task 150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7; 'Unable to locate schedd crab3test-8'", "Failed to submit task 150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7; 'Unable to locate schedd crab3test-8'", "Failed to submit task 150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7; 'Unable to locate schedd crab3test-8'", "Failed to submit task 150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7; 'Unable to locate schedd crab3test-8'", "Failed to submit task 150109_105934_crab3test-8:jmsilva_crab_T2_FR_CCIN2P3_ITB7; 'Unable to locate schedd crab3test-8'"]

No publication information available yet

**Comment by mmascher** [comment]
So, the REST interface selected the schedd which was shut off, and then the TaskWorker failed to submit it. I think the problem was that in this case the schedd should also be deleted from the REST backend urls (https://cmsweb.cern.ch/crabserver/preprod/info?subresource=backendurls , or the equivalent on your VM).

**Comment by belforte** [comment]
that's the drawback of early binding to a specific schedd in the REST. Which I never understood what 
buys. If you can leave it to the TW, of course it will have an easier time in picking the working 
one in a pool. The only other comment is that as long as schedd is set once and kept fixed, it may 
be useful for TW to try a few times, which maybe it does already, before failing.

**Comment by mmascher** [comment]
Merging this pull from justas that excludes from the CRAB3 server configuration the unknown schedulers.

Opening a new issue for the late binding stuff Stefano mentioned.
