### ISSUE TITLE
Write a crab verify command to locally execute user's code

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4621]
The "crab verify" should take the user's sandbox, create a temporary cmssw area, runs the job for 10 events, and returns a per-event median / average memory usage. This works well with the recent patch from @matz-e https://github.com/dmwm/CRABServer/pull/4603 that allows people to use the EventsAwareLumiSplitting

We should write the code so that it is also possible to execute on lxplus an user job, for example for cases like https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/337.html , where a user would like to execute a particular job.

The command couls also be useful for debug

**Comment by belforte** [comment]
do you mean the sandbox prepared by the client ? Or the thing that is prepared by TW/DAGMAN and sent 
to WN ?

**Comment by mmascher** [comment]
I would say the second one and run the job wrapper. Something like this recipe https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#To_run_the_job_wrapper_from_lxpl

At least that's what I had in mind, get everything we need to run the job wrapper (minus stageout)

To be honest I have not thought to the implementation details yet, I will wait for @annawoodard

**Comment by annawoodard** [comment]
Ignore the issue reference explosion above-- that was a mistake, wrong issue number. 

> This works well with the recent patch from @matz-e #4603 that allows people to use the EventsAwareLumiSplitting

I don't follow why the splitting algorithm matters. Shouldn't the memory/event not change very much, regardless of how many events are run, unless there's a memory leak (which I'm not sure we could catch without running on more events)? On that thread though, after we get this in place, we should consider extending it to also include the time/event from the timing module (although the more relevant number for the user, and one we should also calculate and return, would be the estimated total job run time based on the given splitting parameters.)

**Comment by annawoodard** [comment]
Summarizing a chat I just had with @mmascher:
This is related to #4462, that we should add a --dryrun option, which would return how many jobs a task will generate without submitting it. This could be done with a submit-like client subcommand which inserts a task on the server side with a ‘dryrun’ flag, which will tell the TW not to run the dagman submitter, but instead upload everything we need to run the job wrapper (including the task splitting information) to the UFC. Back on the client side, we download the splitting parameters and display them to the user.  The verify command could run on top of --dryrun, executing the job wrapper over a small number of events, then using the splitting parameters to estimate additional quantities to return to the user: memory, disk, and time per-event and per-job.

**Comment by belforte** [comment]
I like this.
for maximum result, we could make it so that only the user who submitted can do this (privacy of your analysis) but also allow "us" to do it (easy of support). We can make all Crab3 people sign a non-disclosure agreement :-)

**Comment by mmascher** [comment]
Hi Stefano,

IIUC that's already implemented in the crabcache! People can only look at their own files, unless they have the "Operator" role in the CRAB3 sitedb group (https://cmsweb.cern.ch/sitedb/prod/admin/group/crab3). We are using this for the uploadlog where operators can have a look at user's logs, but people can only look at their own logfiles.

**Comment by mmascher** [comment]
Hey Anna (and actually also others),

let me share some code I recently developed for running user's code on lxplus. The script takes as argument a taskname, then connects to the schedd to get the spool directory of the task, copy the code from there, and finally create an empty `run_job.sh` where you can put the arguments of the job that I guess you will upload from DagmanSubmitter to the crabcache (right now I am copying and pasting from the logfiles).

Do whatever you want with it, it's code I implemented for personal use so there is no guaranteee about the quality, but I think it might be useful for you :)

```python
#!/usr/bin/env python

import os
import sys
import commands

def get_condor_schedd(taskname):
    scheddlookup = { 'crab3test-1' : 'root@submit-5.t2.ucsd.edu',
                     'crab3test-2' : 'vocms095.cern.ch',
                     'crab3test-3' : 'vocms096.cern.ch',
                     'crab3test-4' : 'vocms0109.cern.ch',
                     'crab3test-5' : 'vocms0114.cern.ch',
                     'crab3test-8' : 'vocms058.cern.ch',
    }
    scheddname = taskname[14:25]
    print "Looking up schedd for", scheddname
    return scheddlookup[scheddname]

def get_spooldir(taskname, schedd):
    cmd = ('gsissh %s condor_q -const \\\'CRAB_ReqName =?='
           ' \\"%s\\" \\&\\& TaskType=?=\\"ROOT\\"\\\' -af Iwd ' % (schedd, taskname))
    print "Getting the spool directory name:", cmd
    ec, spool = commands.getstatusoutput(cmd)
    if ec:
        print "Command failed with exit code", ec, "and stdout:\n\t", spool
    else:
        print "Spool dir is: ", spool

    return spool


if __name__ == '__main__':
    taskname = sys.argv[1]
    schedd = get_condor_schedd(taskname)
    spool = get_spooldir(taskname, schedd)

    ############### Copyting it
    spoolsplit = spool.split('/')
    paramdict = { 'schedd'        :  schedd,
                  'taskname'      :  taskname,
                  'spoolrootdir'  :  os.path.join('/', *spoolsplit[:-1]),
                  'spooldir'      :  spoolsplit[-1]
    }
    cmd = ('gsissh %(schedd)s tar cvzf - -C %(spoolrootdir)s %(spooldir)s'
           ' | cat > tmp.tgz ; tar xvzf tmp.tgz ; rm -rf tmp.tgz;'
           ' mv %(spooldir)s %(taskname)s') % paramdict
    print "Copying the spool directory:", cmd
    ec, out = commands.getstatusoutput(cmd)
    if ec:
        print "Command failed with exit code", ec, "and stdout:\n\t", out

    ############## Creating the run_job.sh script
    with open('%s/run_job.sh' % taskname, 'w') as rj:
        content = """rm -rf jobReport.json cmsRun-stdout.log edmProvDumpOutput.log jobReportExtract.pickle FrameworkJobReport.xml outfile.root PSet.pkl PSet.py scramOutput.log jobLog.* assa wmcore_initialized debug CMSSW_5_3_4 process.id run.sh.old
tar xvzf sandbox.tar.gz
export PYTHONPATH=~/repos/CRABServer/src/python:$PYTHONPATH
export _CONDOR_JOB_AD=.job.ad
export X509_USER_PROXY=/tmp/x509up_u8440
```

**Comment by matz-e** [comment]
@mmascher This script simplifies things greatly!  Maybe it could be included as a helper script in the CRABServer repo?  That way it would be easier to keep it up to date with developments…

**Comment by mmascher** [comment]
Hi @matz-e , my plan is to have the `crab verify` do all these things. I might be useful for us and also for users. But yes, in general having some "helper scripts" might be useful.

**Comment by belforte** [comment]
I assume that this issue is solved now that `crab --verify` is out. If not, please open new one with the missing action items
