### ISSUE TITLE
Review of dag_bootstrap_startup and exit status

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4627]
I have started reviewing and changing dag_bootstrap_startup.sh and have tried invoke several exit statuses. https://github.com/dmwm/CRABServer/blob/master/scripts/dag_bootstrap_startup.sh#L92 

Task status on schedd become HELD and crab status is showing:
```
[jbalcas@lxplus0053 src]$ crab status
WARNING: Incompatible CRABClient version "3.3.12.rc7" 
Server is saying that compatible versions are: ['3.3.4.rc3', '3.3.9.pre2']
Task name:			150113_062223_crab3test-5:jbalcas_crab_exit_test208394
Task status:			UNKNOWN
Error during task information retrieval:	Your task failed to bootstrap on the Grid scheduler <128.142.142.28:4080?noUDP&sock=11915_efd2_3>..
```
Maybe it would be better to raise better error message and not the same message for all bootstrap failures? We could do condor_qedit and update like `BOOTSTRAP_EXIT_MESSAGE = Error: Python2.6 isn't available on 'hostname'. Error: bootstrap execution requires python2.6. Please contact expert.` Dont know yet, but suspect that 8.3.2 HTCondor will update .job_ad if dag_bootstrap_startup will exit with non zero exit code and task goes on HELD.(Have not tested this as I don`t have yet 8.3.2 version) Also if any of failure happen in dag_bootstrap_startup.sh, an expert have to connect to scheduler and check _condor_{stderr,stdout} log files for any failures. Maybe we should create a symlink and allow them to retrieve from http like we do for all other files : http://vocms0114.cern.ch/mon/cms1761/150112_155149_crab3test-5:jbalcas_crab_schedd_ccin2p3122790/

**Comment by belforte** [comment]
Maybe there is no value in many different error messages here. If dag bootstrap fails expert needs to log on machine anyhow and users would not know what to do with the detailed message anyhow. But easy access to logs is always great, surely adding a couple symlinks does not hurt.

**Comment by juztas** [comment]
This is done: https://github.com/dmwm/CRABServer/commit/c498367605b79e6557ca7dea0b060eeb1d1aa5ee https://github.com/dmwm/CRABServer/commit/982f5779ecc29499ec0220f4146cc31f4440b7bd
