### ISSUE TITLE
Add support for gfal2

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4628]
Applies to client, server and ASO. I put here for visibility. Maybe good to open more dedicated issues, link to this, and close when all done.
Plan should be to check for gfal2, use it if found, fall back to current lcg-* if not. Monitor deployment and remove all lcg-* code when appropriate.

**Comment by juztas** [comment]
Mh... Client already have this fallback https://github.com/dmwm/CRABClient/issues/4264 , ASO on production and preprod already uses gfal2 only https://github.com/dmwm/AsyncStageout/pull/4315. CRABServer uses everything from WMCore Stageout and issue exists here https://github.com/dmwm/WMCore/issues/4880 https://github.com/dmwm/CRABServer/blob/5e7f3d6322579c70614d0a961431565176727a12/src/python/TaskWorker/Actions/PostJob.py

**Comment by belforte** [comment]
grrr...  I was misled by seeing gfal-copy etc. commands used and thinking it meant gfal1... sorry.

**Comment by juztas** [comment]
You closed, I did not wanted to say that, we still have one command in CRABServer which uses lcg-cp and also we have to track WMCore issue and test whenever it is available in WMCore code ;)
