### ISSUE TITLE
Late binding of schedd

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4629]
Right now we are binding the schedd name in the REST at submission time. It would be better to do it in the task worker so that automatic submission retries could try to select a new schedd if the selected one does not work.

Requires:
1) A new column in the database for the scheduler name that gets updated before the submission to the schedd
2) Since we are working on this we can also remove the crab3test-1 thing from the taskname
3) Also, maybe we could start using the machine names instead of crab3test-2 for the schedds

See https://github.com/dmwm/CRABServer/issues/4620#issuecomment-69343751

**Comment by juztas** [comment]
@mmascher about 3 I am not sure. With full implementation if I submit a task, I will get <timestamp>_<machine_name>:<username>_crab_<taskname> but if TaskWorker will decide to change machine, this task name will be incorrect. What about staying with <timestamp>:<username>_crab_<taskname> or I misunderstood you ?

Thanks
