### ISSUE TITLE
Use the -f option when doing scram project

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4633]
Request coming from @ktf :

```
I think we understand what is happening. scram project goes and looks for releases.map in order to decide what is the production architecture. Marco, is Crab doing scram project on each worker node? If yes, since I assume you already know which architecture to use at that point, can you please add the -f option to it, so that it does not query for the production architecture?
```

**Comment by mmascher** [comment]
See https://hypernews.cern.ch/HyperNews/CMS/get/swReleases/4149/2/1/1/2/1/1/1/1/1/1.html

**Comment by belforte** [comment]
surely it is easy, but even more surely not urgent. Are we 100% sure that there is no side effect ?

**Comment by belforte** [comment]
also it is not clear that this solves any actual problem, while surely taking away a possibly helpful diagnostics.

**Comment by belforte** [comment]
given the last news from Shahzad and Giulio [1] it can be closed as invalid
[1]
https://hypernews.cern.ch/HyperNews/CMS/get/swReleases/4149/2/1/1/2/1/1/1/1/1/1/3/1/1/1/1/1/1/2/1/1/1.html
