### ISSUE TITLE
crab getlog --short

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4637]
As discussed with @belforte maybe we could implement `crab getlog <taskname> --short` and this command will download truncaded CMSSW output from Scheduler.

a) Save truncated CMSSW output and transfer it back to scheduler together with `job_out.<job_id>.<retry>.txt` and `crab getlog <taskname> --short` will download truncated files from scheduler;
b) `job_out.<job_id>.<retry>.txt` and `crab getlog <taskname> --short` will download these files to user directory

Not sure with which solution to go and use cases what you cannot see in glidemon or dashboard

**Comment by belforte** [comment]
I thought this was simply a different way to see what's in glidemon/dashboard already, not more things. Don't we do a) already ? i.e. the truncated cmsRun output is already on scheduler disk, which is where glidemon reads it from (by the way schedd's http is not visible outside CERN and glidemon proxies for it, we should go for a cmsweb based solution instead).

**Comment by mmascher** [comment]
I agree with Stefano,

the webdir is already available with some simple lines of code:

```python
#The script requires:
# voms-proxy-init -voms cms
# export X509_USER_PROXY=/tmp/x509up_`id -u`
# source /cvmfs/cms.cern.ch/crab3/crab.sh

import os
import sys
from httplib import HTTPException
from RESTInteractions import HTTPRequests

server = HTTPRequests('cmsweb.cern.ch', os.environ['X509_USER_PROXY'], os.environ['X509_USER_PROXY'])

try:
    #argv[1] is the taskname
    print server.get('/crabserver/prod/task', {'subresource':'webdir', 'workflow':sys.argv[1] })
except HTTPException, hte:
    print hte.headers
```

which returns something like:

```
({u'result': [u'http://submit-5.t2.ucsd.edu/CSstoragePath/22/cmsprod/150120_093634_crab3test-1:sciaba_HC_106_AnySite_20150119204901']}, 200, '')
```

Then we can simply add the jobnumber and the retry number to get  the file (even with urllib like we are doing here https://github.com/dmwm/CRABClient/blob/a058e3bdb7a20d3ee3d10abf6b132d5fc4daa4d6/src/python/CRABClient/UserUtilities.py#L81-L104). We only have to figure out the job/retry numbers (suggestions?)

The only thing we need to account is the CERN firewall. Maybe we should talk to Diego and see if he has suggestions.
