### ISSUE TITLE
Additions to the monitor for CSP shifters

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4658]
Before we lost them, here there are some ideas Jadir can look into for the kibana monitor page

1) # of idle old jobs per site: See https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2262/1.html
We can query each CRAB3 schedd and filter on (1) Payload jobs with time()-QDate > 86400 and (2) JobStatus == 1
Then, look at DESIRED_Sites and increase the count for each possible site.
This way we can spot jobs that are idle at a site for a long time.

2) # of task per state in the CRABServer oracle database.
We can implement an API in the server that returns something like "SELECT count(*), tm_task_status from TASKS group by tm_task_status". That way we can spot tasks that either gets stuck in a state (HOLDING/NEW/QUEUED), or overloads of the taskworker that cannot keep up with the submission load.

For reference, here is the current kibana page: https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/97o-BAAkSPaJq8QA-no2HA

**Comment by mmascher** [comment]
As a reference that's the work Justas started: https://github.com/dmwm/CRABServer/pull/4652

**Comment by mmascher** [comment]
Justas: something like this https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/nB3Yo2esRaq5tlA213xH4w with the crab hosts could also be useful. Plus, running/idle/... jobs

**Comment by juztas** [comment]
Example of xml: http://vocms037.cern.ch/XRDFED_CMS-EU.xml

**Comment by belforte** [comment]
please have Jadir get an account and assign to him. It that takes time you can assing to me in the meanwhile, and I'll follow up with him

**Comment by jmarra13** [comment]
Hi, I already have an account it is jmarra13

**Comment by jmarra13** [comment]
@mmascher to get the # of idle jobs per site i did this in one schedd(vocms096)

condor_q -const 'jobstatus == 1&&time()-QDate > 86400' -format '%s\n' DESIRED_Sites | xargs | tr ', ' '\n' | sort | uniq -c | sort -nr

the output is like this:

    275 T2_BE_IIHE
    210 T2_US_Caltech
    210 T2_IT_Rome
    210 T2_FR_CCIN2P3
    201 T3_US_FNALLPC
    200 T3_US_NU
    200 T1_US_FNAL
    154 T2_RU_RRC_KI
     76 T2_CN_Beijing
     63 T2_US_Florida
     39 T3_US_Rutgers
     30 T2_GR_Ioannina
     30 T2_BR_UERJ
     16 T2_DE_DESY
     12 T3_KR_UOS
     12 T3_KR_KISTI
     12 T2_KR_KNU
     12 T2_ES_CIEMAT
     12 T2_CH_CERN
      4 T2_US_UCSD
      4 T2_IT_Bari
      4 T1_FR_CCIN2P3

Am I in the right way?

**Comment by belforte** [comment]
it is the right track. But we also have this informataion already here
http://submit-3.t2.ucsd.edu/CSstoragePath/Monitor/latest.txt
Even if condor_q is not expensive for schedd's now, I think we'll be
better with a single script getting the dump and then all various
monitorings can parse the dump.

Mostly I think you Jadir should start from "anything even hard codes static file"
to simply learn how to build the kibana display. But as getting the right metrics goes,
it will be highly non trivial. You can get a sense of the difficulty by looking
at James page above: every site has 200k jobs which could run there, yet we only
run 50k overall, half of the weekend value. Why ? Nobody knows.

The right questions to me is rather: is kibana a good place to show this
king of metrics ? Does it make sense to have a page broken down by site ?
(we have 100+ sites). Or should we try to extract a few (<5) metrics
that can be uses to check overall health of a schedd and report those
in kibana instead ?

Maybe one could be : #of jobs in Idle since >1 day and matching at least
one site which runs some jobs atm. But I am not advocating implementing that one.
Simply to say that we need global indicators. Not another table by sites.
Maybe a few "open" displays where we can easily insert the metric of the day ?

I still think first priority is: are schedds, TWs, RESTs, ASOs machines healthy ?
Are needed processes running ?

**Comment by jmarra13** [comment]
Ok Stefano, I just found a twiki about kibana at CERN https://twiki.cern.ch/twiki/bin/view/ITSDC/ExperimentCentralServicesMonitoring_inAI
I will look into it, maybe it can give a light.

**Comment by jmarra13** [comment]
Here is a dashboard first dashboard with host metrics for prod schedd, tw, aso and pre prod tw
https://meter.cern.ch/public/_plugin/kibana/#dashboard/temp/AUuSmu0Mtb7_3OTFNYOx

this dashboard is available at gist
https://gist.github.com/jmarra13/a87874b597c3acab31b4

**Comment by hernand** [comment]
Hi, I think for host metrics we already have the ganglia monitoring at nebraska: 
http://hcc-ganglia.unl.edu/?r=day&cs=&ce=&c=crab-infrastructure&h=&tab=m&vn=&hide-hf=false&m=ShadowsRunning&sh=1&z=small&hc=4&host_regex=&max_graphs=0&s=by+name

I think we should concentrate on monitoring metrics that tell us if the system is working fine. Performance, throughput, contention, errors. Not sure what are the best metrics though. Everyone should think about it. People currently monitoring the system by eye have for sure good suggestions. I think we should separate service health monitoring from global job monitoring. In the first category we can monitor for example the number of running/waiting jobs, tasks, postjobs per schedd to check their load, number of successes/failures in task injection in the TWs, etc.  In the second category for example job success and failure rate, average job time latency from injection to schedd to completion, from injection into ASO to completion of the transfer. Things like these that could give us an idea of the performance/load/errors of the system.

**Comment by juztas** [comment]
Get count of jobs with MaxWallTime in minutes. We have seen some jobs having more 2.4 days and this is too long.
```
condor_q -af MaxWallTimeMins | sort | uniq -c
   9002 1400
   4340 1500
    643 2900
      6 30
    557 3000
      9 75
     51 80
```
How much memory job is requesting:
```
condor_q -af RequestMemory | sort | uniq -c
      9 1
      2 1000
      1 1250
   7171 2000
      4 3000
    202 4000
      1 5000
      5 7500
```

**Comment by juztas** [comment]
grep and count glexec failures in Shadow log file (Only newest one). In Shadow log you will see like 
```
02/25/15 11:12:14 (1426237.0) (3590754): ERROR "Error from glidein_4633_755532554@europium-1-5.lsr.nectec.or.th: error changing sandbox ownership to the user: condor_glexec_setup exited with status 768 and the following output: [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 30 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 60 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 90 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile." at line 558 in file /slots/03/dir_59220/userdir/src/condor_shadow.V6.1/pseudo_ops.cpp
```
you have to group them by hostname, group and count.
```
glidein_11052_171041680@rrc091.itep.ru
glidein_2103_248994020@rrc090.itep.ru
glidein_11052_171041680@rrc091.itep.ru
glidein_2103_248994020@rrc090.itep.ru
glidein_11052_171041680@rrc091.itep.ru
glidein_2103_248994020@rrc090.itep.ru
glidein_11052_171041680@rrc091.itep.ru
```
But to retrieve this information you will need to put this into SCHEDD ADS or have a script in schedd which does this and generates separate XML on schedd.

**Comment by belforte** [comment]
isn't this already in James' monitor ?


On 02/25/2015 11:26 AM, Justas Balčas wrote:
> grep and count glexec failures in Shadow log file (Only newest one). In Shadow log you will see like
>
> |02/25/15 11:12:14 (1426237.0) (3590754): ERROR "Error from glidein_4633_755532554@europium-1-5.lsr.nectec.or.th: error changing sandbox ownership to the user: condor_glexec_setup exited with status 768 and the following output: [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 30 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 60 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile.; Glexec exited with status 203; retrying in 90 seconds.; [gLExec]:  LCMAPS failed.;            The reason can be found in the logfile." at line 558 in file /slots/03/dir_59220/userdir/src/condor_shadow.V6.1/pseudo_ops.cpp
> |
>
> you have to group them by hostname, group and count.
>
> |glidein_11052_171041680@rrc091.itep.ru
> glidein_2103_248994020@rrc090.itep.ru
> glidein_11052_171041680@rrc091.itep.ru
> glidein_2103_248994020@rrc090.itep.ru
> glidein_11052_171041680@rrc091.itep.ru
> glidein_2103_248994020@rrc090.itep.ru
> glidein_11052_171041680@rrc091.itep.ru
> |
>
> But to retrieve this information you will need to put this into SCHEDD ADS or have a script in
> schedd which does this and generates separate XML on schedd.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4658#issuecomment-75937481>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by juztas** [comment]
@belforte this one http://submit-3.t2.ucsd.edu/CSstoragePath/Monitor/latest.txt ? If yes, I don`t see glexec failures

**Comment by belforte** [comment]
this one:
http://submit-3.t2.ucsd.edu/CSstoragePath/Monitor/latest-global-history.txt

**Comment by jmarra13** [comment]
To get the top 10 host with glexec failures I run this command

grep ' LCMAPS failed' `condor_config_val SHADOW_LOG` | awk '{print $8}' | tr -d ':' | tr '@' ' ' | awk '{print $NF;}' | sort | uniq -c | sort -k 1 -nr | head -n 10

which output this:

    110 europium-2-2.lsr.nectec.or.th
     72 europium-1-8.lsr.nectec.or.th
     50 europium-2-1.lsr.nectec.or.th
     50 europium-1-9.lsr.nectec.or.th
     36 europium-2-0.lsr.nectec.or.th
     29 europium-1-0.lsr.nectec.or.th
     24 europium-1-5.lsr.nectec.or.th
     22 europium-0-8.lsr.nectec.or.th
     19 europium-1-7.lsr.nectec.or.th
     15 europium-1-6.lsr.nectec.or.th

**Comment by belforte** [comment]
simply let's not have multiple scripts which do condor_q and/or parse condor logs independently. Do it once, then feed to result to all presentation tools.

**Comment by mmascher** [comment]
W.r.t.: https://cms-logbook.cern.ch/elog/GlideInWMS/1810?mail0=28%20recipients

@jmarra13 , can you add to this page (*) a chart that shows the number of tasks per schedd? That should be the result of:

```
condor_status -schedd -pool vocms097.cern.ch -const 'regexp("crab3", Name)' -af:h Name TotalSchedulerJobsRunning
```

Also, have you rpepared a pull request with the code that produces the xml for generating this page (*)

Thank you.

PS not a high priority task as you can imagine

(*)
https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/AUws4PRSUi4v51IQ945Y

**Comment by belforte** [comment]
would be good to see this next to the number of jobs:
condor_status -schedd -const 'CMSGWMS_Type=?="crabschedd"' -af:h Name ShadowsRunning

also I think the above constraint (from Justas) is preferrable to the one with the
explicit collector host name and the regexp on schedd name.
Of course we need discipline in maintaining CMSGWMS_Type

I also think these plots are for us, more then shifters. In the end we need one
web page which we can look at twice a day for 10 seconds and gives us
the warm feeling that everything is ok, or tells us that we better
code development and worry about operations. Takes less effort and give
better result then training CSP's to do it. If all we want is an e-mail
about "metrix X reached level Y" we would be better off by embedding this
in the monitoring. Can kibana do it ?

**Comment by jmarra13** [comment]
Ciao @mmascher, I will update the code to insert this data and after will draw a chart in kibana to display it and In the end the pull request.

**Comment by mmascher** [comment]
Hi @jmarra13 , can we add DAG_NodesReady to the monitor? The idle jobs do not give us the whole picture, there are jobs who are not idle but waiting to get in the condor queue, sort of in a limbo

**Comment by jmarra13** [comment]
Hi @mmascher is this a classAd from schedd or maybe from the collector? Because it try to fetch from schedd and it is undefined, same when I try the collector.

from all schedds.

jmsilva@vocms045 ~/kibana/src> condor_status -pool vocms097 -schedd -const 'CMSGWMS_Type=?="crabschedd"' -af:h Name DAG_NodesReadyName                             DAG_NodesReady
crab3test-1@submit-5.t2.ucsd.edu undefined     
crab3test-2@vocms095.cern.ch     undefined     
crab3test-3@vocms096.cern.ch     undefined     
crab3test-4@vocms0109.cern.ch    undefined     
crab3test-5@vocms0114.cern.ch    undefined     

from collector daemon

jmsilva@vocms045 ~/kibana/src> condor_status -pool vocms097 -coll -af:h Name DAG_NodesReady
Name                                                 DAG_NodesReady
Personal Condor at vocms097.cern.ch@vocms097.cern.ch undefined     
Personal Condor at vocms099.cern.ch@vocms099.cern.ch undefined

**Comment by juztas** [comment]
This classad is in all "ROOT" job ads. Be aware of Held tasks as this value should not be taken of Held task:
`condor_q -g -const 'CRAB_ReqName isnt null && TaskType=?="ROOT" && JobStatus=?=2' -af DAG_NodesReady`

**Comment by jmarra13** [comment]
better to use this one I think, because it is returning several lines with zeros.

condor_q -const 'CRAB_ReqName isnt null && TaskType=?="ROOT" && JobStatus=?=2 && DAG_NodesReady > 0' -af Owner DAG_NodesReady

What do you think @juztas

**Comment by jmarra13** [comment]
Guys, as we have now some metrics to monitor and most of them are condor classAds(DAG_NodesReady, ShadowsRunning, RequestMemory, MaxWallTimeMins, TotalSchedulerJobsRunning)  I think that the best thing to do is have a generic lemon sensor to read a config file or an hiera variable(puppet way) and push this values to elastic search. So next time we need to include a new metric we only will need to include this metric/classAd into a config file or append it into an hiera variable, and will be very easy for anyone to extend this in the future. Of course I already have the basic python code for this. Any comments?

**Comment by jmarra13** [comment]
kibana dashboard is updated with glexec errors per site.
https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/crab3mon::crab3mon

**Comment by juztas** [comment]
Great, Can you group it by domain ? `ihep.ac.cn`
Would be nicer to see by site name :)

**Comment by belforte** [comment]
plot [1] still says "per 5 min" but IIUC those are numbers for every 2hours (updated every 5min, but still showing rate as numbef-of-tasks/2h.
What is the vertical scale in the new glexec error plot ? errors since when ?
seeing by site is better, but eventually site needs node names.
What are the "notifications" ?
Is the ring plot Average # of Tasks by Status now correct ?
thanks

**Comment by jmarra13** [comment]
plot[1] fixed, title and the interval
>What is the vertical scale in the new glexec error plot ? errors since when ?
    total count of errors per remote host, I can change it to these functions count, total_count, min, max, total, mean 
  The number of errors depends on which time frame do you select on top. Since this glexec_metric is pushed today to schedds, you only will see errors starting from today.

> What are the "notifications" ?
    will be the number of active alarms, now all number here are coming from my VM, 

Is the ring plot Average # of Tasks by Status now correct ?
Not yet.

**Comment by jmarra13** [comment]
@juztas I can group it by domain, but by site name I dont know how to map host name to a site name, this info is not on the Shadow log where I'm fetching this info.

**Comment by hernand** [comment]
Hi, I also have a couple of comments concerning the plots:
- plot [1]: Is there any reason to plot the change in the number of tasks in a given state instead of simply plotting the number of tasks in a given state? The latter would also contain the information of the former. From the slopes one can figure the rate of change of the various states.
- In the ring plot, which is the time interval to calculate the number of tasks in the various status? is is simply the values corresponding to the current time? if so, when a task flagged as "killed" will go out of the plot?
- For the three lower plots, I think it would be useful to have an additional line with the totals summing up the contributions from all schedd's

**Comment by belforte** [comment]
Hi Jose. here's some answers:
1.Marco explained to me that by plotting rate we can see also rate into the final (successful) state. Which otherwide it is a very large number which makes everything look flat. Similarly for other states, plotting derivative gives a better idea of what happens right now (or right then). I think we already asked for a plot of the current "level" of the non terminal states, so we can make sure that e.g. #queued is not siliently creeping up.
2. it is understood that the ring plot is currently wrong, let's review once Jadir says he fixed it
3. but such a line with the total would squeeze all the individual ones to the bottom making it difficult to see if any host is having troubles, which is what that plot is there fore. Total number of running jobs is tracked elsewhere.

**Comment by hernand** [comment]
what about using a log scale in the y axis to avoid the problem you mention for 1. and 3.?

**Comment by belforte** [comment]
I really like 3. the way it is now. When Jadir adds a plot with #tasks in a given
status, rather then rate of change, we can try linear and log scale and see how
it looks.

**Comment by belforte** [comment]
@jmarra13 
I see that plot[1] now show correct label "number / 2h" but there is only one entry every two hours which makes it look not as nice. 5min was probably too fine, but one entry every 10 or 30 min should be better. Can this be done ?

**Comment by belforte** [comment]
@hernand you can experiment yourself with different views. E.g. for the bottom plot can change from overalpping to stacked lines, which is another way to see the total. To do this:
- click on the small cogwheel next to [2] Number of Shadows per Schedd
- go to Style tab
- check the "Stack" box
- click on Save

**Comment by belforte** [comment]
@jmarra13 I think in the end we will want some documentation to go with this dashboard, to explain what is plotted, how to change, what to look for etc. The best I can suggest is to create a twiki page and then a short URL link to it (maybe a CERN one ?) then put the short URL as part of the title. It will not be clickable, but one can still select with mouse and then open it.

**Comment by mmascher** [comment]
I think this can be closed. Jadir put all his code here: https://github.com/jmarra13/crab3mon
