### ISSUE TITLE
Possibility for users to ignore CRAB3 backend sites blacklist

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4664]
See discussion here: https://github.com/dmwm/CRABServer/pull/4663

**Comment by mmascher** [comment]
Few notes for Emilis:

* Need a new parameter in the client https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/ClientMapping.py#L16
* Need to add a new column to the database (here a recent pull request that added a column https://github.com/dmwm/CRABServer/commit/3117943d78efd437895aea92fc426644dd027ba5)
* Need to change the TaskWorker to ignore the blacklist if this flag is defined (https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L564-L565)

Should be all

**Comment by juztas** [comment]
Do we really still need that? I delayed it as I would call it most lowest priority... Let me explain:

How many users complained about that? If site is blocked there is a good reason for that, HC failing, SAM failing, etc. If this option will be available, it will happen the same as with ignoreLocality. It will always be default to true and operators will have more to debug and inform sites. If HC or SAM or etc is failing site already gets a ticket and they are aware of that.
There is one gap, if site fixed issue, but it needs to wait 2 days to have good HC results. For this easiest way for them to create a ticket to site support and make site available.

Now about client parameter, there is already plenty of these, maybe reuse activity and if really anyone wants to use run on blacklisted site, he has to set activity to `IDon'tCareCRAB3BackendBlacklist` (Name is just an example) and do the same as with HC. With activity name we could always filter out from the dashboard and see who is using that. Just my 2 cents.

**Comment by belforte** [comment]
I agree that this is not urgent, and it would be even better if it is
not needed, possibly reducing the time it takes for a site to get back
into operation and taking sites off only when they are really broken, not
for temporary glitches. And surely I do not want users start to play around with
different activity names (analysis is good, thanks), nor too many options.
AFAIU this issue was picked up more as a way to get familiar with the code.

**Comment by mmascher** [comment]
Yep, let's start with something low priority for Emilis. But if we don't want to include this at all there are plenty of things emilis could do (https://github.com/dmwm/CRABServer/issues/assigned/emaszs)

I'll let Stefano decide if we need to close this, indeed it does not seem there are user crying and asking for it..

**Comment by mmascher** [comment]
I think the commit above reference the wrong ticket.

Anyway, for this one we were waiting for a patch by @juztas . He was simplifying how boolean flags are passed to the TW without the need of adding an oracle column every time we add a boolean flag.

**Comment by emaszs** [comment]
Marco ended up doing this, PR here: https://github.com/dmwm/CRABServer/pull/5276

**Comment by emaszs** [comment]
Although, it modifies the extraJdl parameter internally instead of using a database column which isn't the best, so maybe I shouldn't close this and implement it in a slightly cleaner way.

**Comment by belforte** [comment]
+1
