### ISSUE TITLE
In case of transfer failure show more information in Postjob log file

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4665]
@hernand comment:
`
One question about the postjob log. It shows that it took more than 6 hours to fail the transfer. I guess this is because there are retries and a cool-off (2h) between retries. Would it be possible to show in the postjob log a message about each transfer failure->cool-off->retry so that the user can know what is going on? For example: transfer failed with error "blah". Going to cool-off for N hours and then retry (M retries left). 
`

https://github.com/dmwm/AsyncStageout/issues/4321#issuecomment-73678349

**Comment by belforte** [comment]
it is not clear how much users can really benefit/use this. Overall ASO monitoring is still not as good as one may desire but I would not rush to code in partial solutions
