### ISSUE TITLE
Validation scripts: add test for 'mixingFiles' input_types

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4666]
See https://cms-logbook.cern.ch/elog/Analysis+Operations/488

Input sandbox in my public: /afs/cern.ch/user/m/mmascher/public/sandbox.tar.gz

**Comment by juztas** [comment]
@mmascher can you close it? I am creating one issue for validation updates

**Comment by belforte** [comment]
will be tracked in #4989. Close
