### ISSUE TITLE
PostJob: failure uploading output dataset to task DB

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4673]
See this task http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=1006228&showResubmits=1 and look at the PostJob log for one of the completed jobs. For example, for job 4, the PostJob log says:

Mon, 16 Feb 2015 15:49:15 CET(+0000):INFO:PostJob ====== Starting upload of output files metadata.
Mon, 16 Feb 2015 15:49:15 CET(+0000):DEBUG:PostJob Uploading file metadata for TreeSUSYtfs.root to https://cmsweb.cern.ch/crabserver/prod/filemetadata: [('outlfn', '/store/user/piedra/QCD_Pt-20toInf_MuEnrichedPt15_PionKaonDecay_Tune4C_13TeV_pythia8/NoSkim/150216_141044/0000/TreeSUSYtfs_4.root'), ('outdatasetname', '/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER'), ('globalTag', 'None'), ('checksumadler32', u'deaa0adc'), ('pandajobid', 4), ('checksumcksum', u'2251143523'), ('outlocation', 'T2_ES_IFCA'), ('outtmplfn', '/store/temp/user/piedra.650f75b4a6db94a22fe5cd021e35a7fce6357c3c/QCD_Pt-20toInf_MuEnrichedPt15_PionKaonDecay_Tune4C_13TeV_pythia8/NoSkim/150216_141044/0000/TreeSUSYtfs_4.root'), ('outsize', 69868748), ('appver', 'CMSSW_7_2_0'), ('outtype', 'TFILE'), ('checksummd5', 'asda'), ('publishdataname', 'NoSkim-62329869d4ed5170f5cf8f311467cdce'), ('taskname', '150216_141044_crab3test-3:piedra_crab_QCD_Pt-20toInf_PU20bx25_PHYS14'), ('acquisitionera', 'null'), ('outtmplocation', u'T2_US_Nebraska'), ('events', 0), ('directstageout', 0)]
Mon, 16 Feb 2015 15:49:15 CET(+0000):DEBUG:PostJob Uploading output datasets to https://cmsweb.cern.ch/crabserver/prod/task: [('subresource', 'addoutputdatasets'), ('workflow', '150216_141044_crab3test-3:piedra_crab_QCD_Pt-20toInf_PU20bx25_PHYS14')]
Mon, 16 Feb 2015 15:49:15 CET(+0000):ERROR:PostJob Error uploading output dataset: {'Content-Length': '714', 'X-Error-Http': '400', 'X-Rest-Time': '66560.984 us', 'Server': 'CherryPy/3.2.2', 'Connection': 'close', 'X-Error-Detail': 'Invalid input parameter', 'CMS-Server-Time': 'D=71612 t=1424098155793015', 'X-Rest-Status': '302', 'Date': 'Mon, 16 Feb 2015 14:49:15 GMT', 'Content-Type': 'text/html;charset=utf-8', 'X-Error-Info': 'Output datasets not found in the input parameters', 'X-Error-Id': '65243a1c54cae7d751ef55332049787a'}
Mon, 16 Feb 2015 15:49:15 CET(+0000):INFO:PostJob ====== Finished upload of output files metadata.
Mon, 16 Feb 2015 15:49:15 CET(+0000):INFO:PostJob ====== Starting upload of input files metadata.
Mon, 16 Feb 2015 15:49:15 CET(+0000):DEBUG:PostJob Uploading file metadata for input file /store/mc/Phys14DR/QCD_Pt-20toInf_MuEnrichedPt15_PionKaonDecay_Tune4C_13TeV_pythia8/MINIAODSIM/PU20bx25_PHYS14_25_V1-v3/10000/DC83F868-ACA6-E411-9C36-0025B3E0648A.root
Mon, 16 Feb 2015 15:49:16 CET(+0000):INFO:PostJob ====== Finished upload of input files metadata.
Mon, 16 Feb 2015 15:49:17 CET(+0000):INFO:PostJob Setting Dashboard state to Done. Dashboard parameters: {'MonitorID': '150216_141044_crab3test-3:piedra_crab_QCD_Pt-20toInf_PU20bx25_PHYS14', 'MonitorJobID': '4_https://glidein.cern.ch/4/150216:141044:crab3test-3:piedra:crab:QCD:Pt-20toInf:PU20bx25:PHYS14_0', 'StatusValue': 'Done'}
Mon, 16 Feb 2015 15:49:17 CET(+0000):INFO:PostJob Post-job finished executing with status code 0.
Mon, 16 Feb 2015 15:49:18 CET(+0000):INFO:PostJob ====== Starting to prepare error report.
Mon, 16 Feb 2015 15:49:18 CET(+0000):INFO:PostJob ====== Finished to prepare error report.
Ended TaskManagerBootstrap with code 0

**Comment by mmascher** [comment]
Hi Andres, that error message is coming from (see 'X-Error-Info'): https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTTask.py#L134

Indeed I cannot find the outputdataset name among the input parameters:  `[('subresource', 'addoutputdatasets'), ('workflow', '150216_141044_crab3test-3:piedra_crab_QCD_Pt-20toInf_PU20bx25_PHYS14')]`

It is set here: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L1428-L1429 and only if there is at least one EDM file.

Question is, what should we do with non-EDM files? The current dataset we upload for the filemetadata is `/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER`. It does not make sense to use it. If so then we should probably just need to add `and output_dataset` here: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L1425

Thoughts Andres?
