### ISSUE TITLE
Improve exit codes reported to dashboard (?)

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4688]
See https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L134 , should we report fjr['jobExitCode'] in this line? `jobExitCode` is cmsRun exit code, while `exitCode` is the jobWrapper exit code. Note, `exitCode=jobExitCode` if `jobExitCode<>0` (unless there are bugs)

**Comment by mmascher** [comment]
`ExeExitCode` is the cmsRun exit code (or scriptExe). Agreed that for dashboard we should put the right code. In other places where we report one (status, glidemon) we want to report only the jobexitcode.

Check what is done and document it here.

PS the right link is https://github.com/dmwm/CRABServer/blob/3.3.14.rc1/scripts/CMSRunAnalysis.py#L134

**Comment by AndresTanasijczuk** [comment]
See more discussion in https://github.com/dmwm/CRABServer/pull/4820
