### ISSUE TITLE
Users running over invalid datasets/blocks

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/CRABServer#4689]
This task http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=1018384 is running over /glugluToX800ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT/sdas-glugluToX800ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633/USER in phys03 which is invalid https://cmsweb.cern.ch/das/request?view=list&limit=10&instance=prod%2Fphys03&input=%2FglugluToX800ToHHTobbbb_13TeV_width1MeV_GEN_SIM_RECO_HLT%2Fsdas-glugluToX800ToHHTobbbb_13TeV_width1MeV_PAT-eed6537107126ba67370b15f62982633%2FUSER

I do not think that we want to allow users running over invalid datasets

**Comment by mmascher** [comment]
Thanks Hassen, I will look into it.

**Comment by belforte** [comment]
since ever CRAB (2,3...) allows to run on invalid datasets. Idea was that they are not visible in DAS so should not be used randomly, but still one may want to figure out exactly what happened.
Of course this could be revised, but let's not do it lightly, nor in a hurry.
I am very fearful in general of a growing trend in Crab3 of slipping in small things here and there since it is quick to code, w/o a clear vision of how things fit in the overall plan.

**Comment by mmascher** [comment]
@HassenRiahi , was there a particular reason you wanted to do that? Is this causing problems during publication?

**Comment by HassenRiahi** [comment]
I do not want to do it I was just asking if this behavior is expected. Within the current production release it is causing problem during the publication since the call to listDatasets API was excluding the invalid datasets https://github.com/dmwm/AsyncStageout/blob/eec06e3bff73e9a91514aa4e691b3b45b3d5b006/src/python/AsyncStageOut/PublisherWorker.py#L502. But it is already fixed in the new release by @AndresTanasijczuk by aligning the publication code with CRAB2

**Comment by belforte** [comment]
we exclude INVALID FILES.
For files situation is "simple", DBS has a is_file_valid = 1 or 0
But INVALID dataset is a complicated thing, dataset has a status,
can be VALID, or one of various strings like DEPRECATED, DELETED etc.
DEPRECATED may simply mean that production did a v2 and deprecated v1,
but this does not mean that v1 can not be useful of needed if you
know what exactly you are doing.

Of course it would have been better to have this discussion when the 
code was changed to align with Crab2. Andres should not be afraid to 
question the wisdom of what Crab2 did. We only progress by revisiting 
past decisions in light of our increased experience and changes in the 
world around :-)

**Comment by AndresTanasijczuk** [comment]
When I changed the code to align with Crab2, all calls to listDatasets were changed to use dataset_access_type = '*' (meaning that all datasets are listed, no matter of the status). That's why @HassenRiahi said "But it is already fixed in the new release by @AndresTanasijczuk by aligning the publication code with CRAB2".
So I am not sure why @belforte says "Of course it would have been better to have this discussion when the code was changed to align with Crab2" which somehow means I broke something with this change.

**Comment by belforte** [comment]
no, what I meant is not that you broke something, but the right time to 
ask "is it good to list all datasets regardless of the VALID status" was 
when you changed the code. It was a good chance to question if maybe 
Stefano had done something stupid or simply something that was needed at 
some point in the past but not anymore.
Sort of: never trust things, always question and criticize, always ask 
why, always make sure there is a good and understood reason for the 
behavious we see. At the least, you educate yourself. At the best, you 
spot a problem. :-)

**Comment by ericvaandering** [comment]
"we exclude INVALID FILES.
For files situation is "simple", DBS has a is_file_valid = 1 or 0"

This may bite us because we have recently asked @yuyiguo to return is_file_valid false for datasets that are not valid. Yuyi can clarify.

**Comment by belforte** [comment]
oh **** ! what's the forum where those things are discussed like
meaning of DBS status flags ? We are not back to google waves, aren't we 
? oh the good old days when people wrote a document (not a twiki) first, 
and build stuff later :-)

**Comment by ericvaandering** [comment]
The DBS patch is here I think https://github.com/dmwm/DBS/pull/454 

I think this is not as dire as I suggested (not changing existing behavior) but I will let Yuyi clarify rather than adding more noise.

**Comment by belforte** [comment]
from first look it seems something we may actually want to use
to simplify CRAB code :-)

**Comment by yuyiguo** [comment]
listDataset API only return valid dataset that is the dataset has a datase_access_type= "VALID" . This is the default  as day one . If one wants to list all the datasets: INVALID, DELETED,  DEPRECATED  or PRODUCTION, you may add dataset_access_type=* when you call the API. 

There were requests for APIs like listFiles, listFileSummary and so on to list only valid files. So I added a new validFileOnly flag to those APIs. If you are not using this flag, there is no change to you. If you use this flag, you will get only valid files. The definition of valid file is : 1. the is_file_valid flag of the file has to be 1.  2. The dataset that the file belong to has to have dataset_access_type=VALID or PRODUCTION. If the dataset_access_type is other value, such as INVALID, DELETED or DEPRECATED , all the files under the DS will be considered as invalid by those APIs.

**Comment by mmascher** [comment]
Closing as duplicated
