### ISSUE TITLE
[improved job splitting] Activate processing time-limit in CMSSW

### ISSUE THREAD

**Issue by matz-e** [dmwm/CRABServer#4690]
Issue to keep track of implementation status: @annawoodard @bbockelm

Activate CMSSW feature to stop cmsRun on full lumis, depending on a given maximal runtime.  Should be internal/optional, as not all CMSSW versions support this.

**Comment by belforte** [comment]
is this something we really want/need ?
this only makes sense IMHO if part of a more complex workflow where
jobs are stamped as needed based on what was processed, rather then
initial splitting decision. A good thing, but not a trivial one.
Before we go too much the WMA way, I'd like to make sure current
issues are under control, starting from status reporting, submission
failures, easier to read logs etc. Not to mention the stage out changes
identified in the review.

**Comment by matz-e** [comment]
This is just the first steps to some automated recovery and smarter splitting which should result in removing the user from splitting decisions.

The argument behind is that users make bad splitting decisions and then waste CPU time.  Instead, we should basically remove the splitting knobs to turn and try to find a good job size.  If we exceed this job size / allowed wall time, we don't fail the job, but process the remaining parts of the job in separate, new jobs.

**Comment by belforte** [comment]
ok, It is certainly a very nice thing to do, as long as it clear that it is "next step" and not delaying the things in the critical path for complete user satisfaction and education in Crab3 by summer.
E.g. it is more urgent to properly report jobs killed by time or memory limit with full stdout.

**Comment by matz-e** [comment]
Parameter in the options to be changed: [`maxSecondsUntilRampdown`](https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/FWCore/Framework/src/ScheduleItems.cc#L126)
