### ISSUE TITLE
[improved job splitting] Find unprocessed lumis

### ISSUE THREAD

**Issue by matz-e** [dmwm/CRABServer#4691]
Issue to keep track of implementation status: @annawoodard @bbockelm 

Depends on #4690.

Look at processed versus submitted lumis of a job in the post-job and fail if they are not equal.  In the future, the difference should be submitted via a sub-dag.

**Comment by matz-e** [comment]
@bbockelm I have some code around that gets the difference in processed lumis.  But when further processing this (and splitting it up), we should really access information such as estimated lumi size in events etc.  Any recommendations how to store or access this information?

It seems like we would duplicate functionality present elsewhere here.  Maybe the WMCore event splitting could be re-used with a lumi mask?  Though this would require dragging quite a bit of metadata along with the task…

**Comment by PerilousApricot** [comment]
Look @ the eventAwareLumiSplitting algorithm from WMCore

**Comment by matz-e** [comment]
That is in fact what I'm using in the first place.  I just think that re-using it might be more involved than we might want?  I could always re-implement a "light" version and just store the estimated events per lumi along with the job information on the schedd.

**Comment by PerilousApricot** [comment]
I'm not sure why re-writing would be a better idea than re-using it...one
of the choices is free (or at least someone else's problem)

**Comment by bbockelm** [comment]
We definitely want to reuse the WMCore algorithms - it might be a pain to invoke, but we at least have examples in CRAB3 to do it correctly.

I don't know how beneficial it is to consider # of events / lumi.  I was thinking of taking the leftover lumis and re-running the splitting with the number of lumis / job (or events / job) divided by 4.  No need to be too complicated.

**Comment by PerilousApricot** [comment]
Of course, the whole idea of "unprocessed lumis" is bogus if the initial
task was doing split-by-events. Should be careful about that.

**Comment by bbockelm** [comment]
(Or split by file, for that matter... this only applies to lumi splitting right now.)

**Comment by PerilousApricot** [comment]
:+1:

**Comment by belforte** [comment]
we do not have #events/lumi currently anyhow[*].
The code simply guesses that all lumis in one file have same #events,
which is OK other then in the cases where some lumi is special, i.e.
useless other then when it would be necessary.
One day we may have proper info and then can do better.

[*] somone (at least me) asked for it years ago, but DMWM of the time
  decided otherwise

**Comment by matz-e** [comment]
OK, I'll see what it takes to invoke the splitting algorithm again.  And the use-case for this currently is using event aware lumi splitting.  I hadn't actually considered splitting by events.  It seems like we could estimate job-runtimes better there (since event based splitting is MC generation only) than when running over data.

**Comment by PerilousApricot** [comment]
@matz-e https://github.com/dmwm/CRABServer/blob/1a7203744b849081acdf4af1ae5e57f4f8e06c58/src/python/TaskWorker/Actions/Splitter.py#L21

**Comment by matz-e** [comment]
Yes, I've seen that already when implementing the EventAwareLumiBasedSplitting.  Just not sure which data exactly I need to buffer on the schedd to not have to query DBS again (and for every post-job.)

**Comment by PerilousApricot** [comment]
When the DAG kicks off, does it still do DBSDataDiscovery on the Schedd?
Just pickle that up and save it and later tasks can get it.

**Comment by matz-e** [comment]
Thanks, that's a good idea.  I don't know if the DAG does any data discovery, but I think we should be able to pickle the initial one before splitting.

**Comment by belforte** [comment]
don't you have at hand already (in DAG domain) the list of arguments
(input and site) used for each job ? the location is surely a classad.

**Comment by ericvaandering** [comment]
Someone (me) also told you, days ago, that we were going to revisit that decision. :-)


> On Mar 24, 2015, at 09:53, Stefano Belforte <notifications@github.com> wrote:
> 
> we do not have #events/lumi currently anyhow[*].
> The code simply guesses that all lumis in one file have same #events,
> which is OK other then in the cases where some lumi is special, i.e.
> useless other then when it would be necessary.
> One day we may have proper info and then can do better.
> 
> [*] somone (at least me) asked for it years ago, but DMWM of the time
> decided otherwise
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/CRABServer/issues/4691#issuecomment-85539473>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 962 7260 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by belforte** [comment]
you said that you would like to change, not that there is a concrete
plan to revisit. WOW ! let's see... it is easy to add to todo list :-)
