### ISSUE TITLE
[improved job splitting] Add run-time estimation

### ISSUE THREAD

**Issue by matz-e** [dmwm/CRABServer#4695]
Issue to keep track of implementation status: @annawoodard @bbockelm

Feed run-time estimates from `crab -verify` into the system to automatically determine job sizes.

**Comment by PerilousApricot** [comment]
Hi all,

It might be kinda difficult to do, but I was thinking that we might have enough information to see when job

**Comment by PerilousApricot** [comment]
Sorry :( I started thinking and then decided against it.

**Comment by matz-e** [comment]
Done with the merging of automatic splitting.
