### ISSUE TITLE
job.ad is owned by root and we can`t edit it

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4701]
In AdjustSites.py we write to job.ad CRAB_USERWebDir and this is failing because .job.ad is owned by root.

[jbalcas@vocms095 cluster1727194.proc0.subproc0]$ ls -l /etc/condor/condor_local/spool/local_univ_execute/dir_1727194_0/.job.ad
-rw-r--r-- 1 root root 5804 Mar  6 12:19 /etc/condor/condor_local/spool/local_univ_execute/dir_1727194_0/.job.ad

```
Traceback (most recent call last):
 File "AdjustSites.py", line 174, in make_webdir
   fd = open(os.environ['_CONDOR_JOB_AD'], 'a')
IOError: [Errno 13] Permission denied: '/etc/condor/condor_local/spool/local_univ_execute/dir_1662754_0/.job.ad'
```

**Comment by mmascher** [comment]
Has something changed in the schedd configuration? AdjustSites.py has not been changed since ages
