### ISSUE TITLE
Set PostJobPrio1 for CRAB3 jobs

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4705]
Currently there is no prioritization between jobs in tasks of the same priority.  Jobs are executed in FIFO order; since DAG submits continuously, jobs are basically executed in random order.

In other words - if I submitted a task yesterday and today with the same priority, then jobs will execute in random order.  It's even possible, for identical tasks submitted at different times, newer ones may finish first.

I think this is different from what users expect.

We can fix this with the (undocumented) PostJobPrio1 attribute.  The schedd will use this as a secondary sorting key.  That means, it will first run jobs by JobPrio - then for jobs with the same JobPrio, run the job with the higher PostJobPrio1

When we adjust the *.submit files when the task is first started, we can set:

+PostJobPrio1 = -%(task_start_time)s

where task start time is the value of the QDate attribute from the DAG job itself.

**Comment by PerilousApricot** [comment]
+1 It doesn't help to have 20 tasks 5% done compared with one task 100% done

**Comment by bbockelm** [comment]
Yeah - I'm happy I found this hidden knob.  It preserves the existing priority system and should greatly decrease task time-to-completion.  Seems like a win-win.
