### ISSUE TITLE
PostJob should report final error code about Memory/Walltime/Disk Usage

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4709]
This [https://github.com/dmwm/CRABServer/pull/4708] pull request reports  50669 and RetryJob which knows real reason of PeriodicRemove of the job should send correct exit code in each function [https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L147-L205]

50660 - Application terminated by wrapper because using too much RAM (RSS)
50662 - Application terminated by wrapper because using too much disk
50664 - Application terminated by wrapper because using too much Wall Clock time

**Comment by AndresTanasijczuk** [comment]
RetryJob is already writing the correct exit code in the fjr. @juztas implemented the fix that at some point. Can we close this issue?

**Comment by juztas** [comment]
I think it is done, no?

**Comment by AndresTanasijczuk** [comment]
Yes, it is done.
