### ISSUE TITLE
Add a warning in the client if people provides unreasonable requirements

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4713]
Need to cache results from factory and in case user specifies 4GB of Memory and site has only 3GB, give a warning message about it and that jobs could stay idle....

**Comment by juztas** [comment]
http://vocms32.cern.ch/gfactory/descript.xml

**Comment by belforte** [comment]
this sounds complicated, possibly fragile and builds dependency on the specific of gWms factory
deep into the CRAB layer. I know that detecting why those jobs stay idle
is difficult and time wasting now, but would rather print a generic warning
whenever user ask for more then the default (2.3GB) and wait for better idea.
Let's aim for good enough, rather then perfect.
If anything we want to make sure that the output of crab submit is
terse enough that warnings are read.

**Comment by mmascher** [comment]
I was talking with Justas about this yesterday, and I thought this was a good idea. The tweak I proposed to him was to do a `condor_status` to get the information we need instead of talking to the gWMS factory. I guess I also had concerns about using the factory and introducing a new dependency.

Indeed we can do something like (*) to get the information we need (well, the equivalent with the python bindings of course). To me it does not sound complicated, provided the information we get from condor_status are reliable.

(*)
```
condor_status -autoformat GLIDEIN_CMSSite GLIDEIN_MaxMemMBs GLIDEIN_Max_Walltime | sort | uniq -c
     48 T2_AT_Vienna 2500 171000
     91 T2_BE_IIHE 2500 171000
     71 T2_BE_UCL 2500 114840
    122 T2_BR_SPRACE 2500 114840
    238 T2_BR_SPRACE 4000 114840
   2500 T2_CH_CERN 2800 603000
    255 T2_CH_CSCS 2500 257400
     53 T2_CN_Beijing 2500 82800
     78 T2_DE_DESY 2500 216000
   5514 T2_DE_DESY 3500 171000
    110 T2_DE_RWTH 2500 171000
    235 T2_EE_Estonia 2500 171000
    360 T2_ES_CIEMAT 2500 232200
   1771 T2_ES_IFCA 3500 171000
    146 T2_FI_HIP 2500 171000
    144 T2_FR_CCIN2P3 4000 86640
    354 T2_FR_CCIN2P3 8000 171000
     81 T2_FR_GRIF_IRFU 2500 171000
     69 T2_FR_GRIF_IRFU 2500 172800
    775 T2_FR_GRIF_LLR 2500 171000
    101 T2_FR_IPHC 2500 171000
      1 T2_GR_Ioannina 2500 171000
     73 T2_IN_TIFR 2500 114840
    207 T2_IT_Bari 2500 169200
    348 T2_IT_Legnaro 2500 171000
...
```

**Comment by belforte** [comment]
Marco, this is called "scope creep" and it is what makes life difficult years later for something that looked such a nice simplification at the time.
You need semi-static information about grid configuration. It is not Crab3 task to obtain it.
We should dump this on CompOps to maintain such a list as you indicated. Whether they do by condor_status or black magic I do not care. It must be a file on the web that Ops maintains and we use and everybody can use and verify.
In the meanwhile, we have a number (2.3GB) which is ugly to put in the code, but the least evil in the short term.
Then if we like to keep up with old habit of using guns to kill flies, we can imagine for that info to be in SiteDB and get REST+Oracle+all paraphernalia where an ascii file on AFS would do. But there uniformity is probably the best value and so be it with the SiteDB.

**Comment by mmascher** [comment]
So, the idea is still good I guess, but the point is where CRAB3 should take the information about the #slots/(site,walltime) and #slots/(site,maxmemory)

**Comment by belforte** [comment]
from my side, yes.

**Comment by juztas** [comment]
@belforte @mmascher are we all are on same page and agree that this information should come from siteDB?

**Comment by belforte** [comment]
yes. Now that we have Processing Location Name in SiteDB (if I remember correctly), these are properties of those Processing Locations. In practice we'll want that everybody provides the required minimum (2.3GB, 48h, 20GB) and use SiteDB to track those who allow more so that factory can be properly configured and CRAB can warn users as needed.

**Comment by juztas** [comment]
@belforte so you still want to use SiteDB for that? For me SiteDB future now is unclear... 

As cms-gwmsmon is used widely (I hope, and I know it is used for Unified & SSB pledge values) maybe we can query it for getting mem, cpu, walltime also for CRAB3? It would not be hardcoded dependency, but in case it is not able to get values from it, it would use old logic... Details can be discussed later

**Comment by belforte** [comment]
fine with me to use cms-gwmsmon, surely it is more flexible than adding stuff to SiteDB,
but  want to know what exactly I find there :-)

**Comment by juztas** [comment]
So for this only one API is needed: http://cms-gwmsmon.cern.ch/poolview/json/totals
In this API you have all CMSSites (site name (PSN) is value from factory config) as a key and each can has a list of entries (1..N). Each entry has a maxMem, MaxCpus, MaxWalltime values, which are taken from all 4 global pool factories. Entries are grouped from different factories, so it is not repeating same entries with same values. For example Nebraska is most complicated:
```
"T2_US_Nebraska": [{"MaxMemMB": 4096, "MaxCpus": 1, "MaxWallTime": 2850}, {"MaxMemMB": 20000, "MaxCpus": 8, "MaxWallTime": 2850}, {"MaxMemMB": 2500, "MaxCpus": 1, "MaxWallTime": 1410}, {"MaxMemMB": 8000, "MaxCpus": 4, "MaxWallTime": 1410}, {"MaxMemMB": 20000, "MaxCpus": 8, "MaxWallTime": 1410}, {"MaxMemMB": 16000, "MaxCpus": 8, "MaxWallTime": 1410}, {"MaxMemMB": 4096, "MaxCpus": 1, "MaxWallTime": 1410}, {"MaxMemMB": 8192, "MaxCpus": 1, "MaxWallTime": 1410}, {"MaxMemMB": 250000, "MaxCpus": 32, "MaxWallTime": 1410}, {"MaxMemMB": 32000, "MaxCpus": 1, "MaxWallTime": 1410}],
```
More documentation would come with code.

I would not add this only in CRAB3, but better would write as a Service in WMCore, same as any other: https://github.com/dmwm/WMCore/tree/master/src/python/WMCore/Services
@ericvaandering is it ok to add new service, like 'gwmsmon' in WMCore?

If so, I can start working on it.

**Comment by belforte** [comment]
If need be, this is enough for CRAB, thanks. About WMCore, of course up to Eric. Question for us is more what to do exactly with the info. A Warning in the client ? Refuse to submit in the server ? In general need to see the site list after data discovery and splitting. Do not want to end with a remake of EGEE ResourceBroker. One thing is to explain a specific case of non-running jobs, another to take decisions.

**Comment by ericvaandering** [comment]
You can write a new service. But if you do, I want you to open an issue "Replace GWSMON with information system when available" since this seems to me to be the kind of thing we would actually ask an information system to handle if we had one.

**Comment by belforte** [comment]
I think we are now calling that "a CMS configuration tool", which will take a Grid Information System (among other things) as input. Talking about "a new information system" raises too many too strong opinions (ruffles too many feathers?).  Surely no intention here to replace OIM or GOCDB.

**Comment by juztas** [comment]
Warning will not help at all. It is just ignored by most of the users...
Refuse to submit to server? We don`t know full site whitelist, so it is not possible. It is possible only if user explicitly whitelisting sites. 
Refuse to submit to scheduler or just give a warning? I think to refuse to submit. Why? Each task is running a dagman on schedd, and from time to time, we reach a limit and you can see multiple tasks submitted with same requirementens, without thinking or asking in Computing tools about mem or CPU or Walltime. Thats why we have a script which checks all available jobs on scheduler and Operator can do decision on these tasks. I was doing this before, but it is one of operational efforts which can be automatized.

So in the end implementation would be a Recurring action, like for Banned sites and you can turn it on/off whenever you want. I skipped idea to add it in wmcore, as prod will not use it (Submitters are using it already before submitting a workflow to prod) and leave it only for CRAB3.
