### ISSUE TITLE
Need a warning for DEPRECATED input datasets

### ISSUE THREAD

**Issue by drkovalskyi** [dmwm/CRABServer#4739]
Dear Developers,

can you please add a warning to crab3 users when they attempt to use a dataset that is DEPRECATED. This status is used for data that soon will be deleted and we want to make sure that people that use it know about and complain if it's critical enough. We would appreciate if you can add a link to JIRA project that manages data and where they should complain: https://its.cern.ch/jira/browse/CMSTRANSF

While you are working on it, please make sure that users can still use both VALID and PRODUCTION datasets as it's possible at the moment.

Thanks,
           Dima

**Comment by juztas** [comment]
Hey @drkovalskyi I have already found it and reported. task will not be submitted to grid scheduler and task status will be failed and currently with crab3 error. I think @mmascher is working on having a nicer message for this. And it should be not a warning, but failure of submitting a task :)  https://github.com/dmwm/CRABServer/issues/4730#issuecomment-86605103

**Comment by AndresTanasijczuk** [comment]
Why a failure? IIUC DEPRECATED doesn't necessarily mean it is a bad/buggy dataset. It just means there is a new one superseding it. https://github.com/dmwm/CRABServer/issues/4689#issuecomment-77128293 Maybe someone wants to run over both datasets and compare the results.

**Comment by mmascher** [comment]
Hi @juztas I aksed Dima to open the github issue. What you reported was happening with a dataset had all the files 'INVALID'. The CRAB3 code basically blow up in this situation, but that's different than checking the dataset status (e.g.: your bug can happen with a 'VALID' dataset that has all 'INVALID' files).

@AndresTanasijczuk : I forgot that issue and that we were already discussing the topic there!

**Comment by mmascher** [comment]
PS I think Dima is asking to add a warning, not to fail the dataset. We can do that, if the status of the dataset is not 'VALID' we upload a warning, but we still run on it.

**Comment by juztas** [comment]
DEPRECATED: This means that deletion campaign started and transfer team set status to DEPRECATED and after ~2-4 weeks all files will be deleted. Even on TAPE. (And if he really wants this dataset not to be deprecated he should complain here: https://its.cern.ch/jira/browse/CMSTRANSF) After that time DEPRECATED dataset will not have any location.
INVALID: It might have some useful information and user might want to run on this, but run only on valid files, but also give error message that you are running on INVALID dataset. 

This is my understanding and maybe I understand something wrong here.

**Comment by AndresTanasijczuk** [comment]
Still, I think we only forbid running on invalid files, because since files can not be erased from DBS, flagging a file as invalid is the way to tell "don't include this file in the dataset".

**Comment by belforte** [comment]
in any case it is DataOps, not us who labels datasets and must thus
define DEPRECATD,INVCALID,DELTED etc.
of course those definitions are not cast in stone and I will not
be surprised of different vision by different people over the yeard.
It is not CRAB task to decide which dataset is good for a given analysis.

**Comment by mmascher** [comment]
Should be done
