### ISSUE TITLE
prevent users form asking unrealistic value for WallTime

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4742]
we must have a maximum allowed wall time (47h in my opinion)
and must prevent users from submitting jobs requesting more
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/515/1.html

**Comment by belforte** [comment]
this could probably be merged with #4713 to reduce issue-pollution

**Comment by mmascher** [comment]
Going to be fixed in https://github.com/dmwm/CRABServer/pull/4758
