### ISSUE TITLE
Add an option to set the number of automatic retries in the client

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4743]
It seems there is a use case where this could be useful in HC. In particular to avoid running jobs that we know they will fail to broken sites (wasting CPU time)

**Comment by belforte** [comment]
sigh.. already have so many options..

**Comment by bbockelm** [comment]
@belforte I think this would be a "hidden HC option", no?  I see no reason why we would acknowledge its existence to users.

(In fact, I would be OK with an implementation that *only* allows this to be used in conjunction with Role=production.)

**Comment by belforte** [comment]
Fully agree including the part in ().  There's a tension between "hidden option" and "option documented enough to be usable by the intended audience and maintainable by today+4year developers".

**Comment by AndresTanasijczuk** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/576/1/1/1.html 
Can we have an option to disable the automatic resubmissions ?

**Comment by belforte** [comment]
Or maybe the use case in https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/576/1/1/1.html could be better addressed by allowing user's ScritpExe to set exit codes indicating "rebubmit me" or  not.
For exit codes that we set and know, we hopefully only resubmit when there are good reasons to believe that the failure was transient and unrelated to anything in user control.

**Comment by belforte** [comment]
whatever it was, we are happy with what we have
