### ISSUE TITLE
take a look into PeriodicRemove for jobs

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4749]
Seems periodicRemove for jobs is not working, if I try with simple condor_q I see plenty jobs which should be deleted by htcondor.
```
( ( JobStatus =?= 5 ) && ( time() - EnteredCurrentStatus > 7 * 60 ) ) || ( ( JobStatus =?= 2 ) && ( ( MemoryUsage > RequestMemory ) || ( MaxWallTimeMins * 60 < time() - EnteredCurrentStatus ) || ( DiskUsage > 100000000 ) ) )
```

**Comment by belforte** [comment]
@juztas do you still think this may be a problem ?

**Comment by juztas** [comment]
It has changed already and I can say crab is doing good job with periodic remove and returning logs. Reopen if needed
