### ISSUE TITLE
newest crabserver fails to resubmit due to TW failure

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4757]
I got exception in my own TW (TW failed to resubmit due to TW code problem), and my task on scheduler is on failed status. I tried to resubmit, and I suspect this should be available, but I get ExecutionError. 
```
[13/Apr/2015:10:47:01]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 97b4201dbcd401c29423f3dcd22d3e5e (Execution error)
[13/Apr/2015:10:47:01]    Traceback (most recent call last):
[13/Apr/2015:10:47:01]      File "/data/user/WMCore/src/python/WMCore/REST/Server.py", line 697, in default
[13/Apr/2015:10:47:01]        return self._call(RESTArgs(list(args), kwargs))
[13/Apr/2015:10:47:01]      File "/data/user/WMCore/src/python/WMCore/REST/Server.py", line 772, in _call
[13/Apr/2015:10:47:01]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[13/Apr/2015:10:47:01]      File "/data/user/WMCore/src/python/WMCore/REST/Server.py", line 1730, in dbapi_wrapper
[13/Apr/2015:10:47:01]        self._dberror(e, format_exc(), False)
[13/Apr/2015:10:47:01]      File "/data/user/WMCore/src/python/WMCore/REST/Server.py", line 1728, in dbapi_wrapper
[13/Apr/2015:10:47:01]        return handler(*xargs, **xkwargs)
[13/Apr/2015:10:47:01]      File "/data/user/CRABServer/src/python/CRABInterface/RESTUserWorkflow.py", line 452, in post
[13/Apr/2015:10:47:01]        userdn=cherrypy.request.headers['Cms-Authn-Dn'])
[13/Apr/2015:10:47:01]      File "/data/user/CRABServer/src/python/CRABInterface/DataUserWorkflow.py", line 131, in resubmit
[13/Apr/2015:10:47:01]        return self.workflow.resubmit(workflow, siteblacklist, sitewhitelist, jobids, maxjobruntime, numcores, maxmemory, priority, userdn, userproxy)
[13/Apr/2015:10:47:01]      File "/data/user/CRABServer/src/python/CRABInterface/DataWorkflow.py", line 301, in resubmit
[13/Apr/2015:10:47:01]        raise ExecutionError(msg)
[13/Apr/2015:10:47:01]    ExecutionError
```
@AndresTanasijczuk can you check ?

**Comment by mmascher** [comment]
@AndresTanasijczuk , should I merge some of the pull requests that are floating around since some time so you can do a more complete test?

**Comment by AndresTanasijczuk** [comment]
@juztas Didn't you get the message "There are no jobs to resubmit. Only jobs in status ['failed', 'held'] can be resubmitted. Jobs in status ['finished'] can also be resubmitted, but only if the jobid is specified." ?

**Comment by juztas** [comment]
and it is not true, because my job is in failed status
```
[jbalcas@lxplus0169 src]$ crab status
Warning: Incompatible CRABClient version "3.3.15.rc1" 
Server is saying that compatible versions are: ['3.3.4.rc3', 'development']
Task name:			150413_074927:jbalcas_crab_resubmit-test168077
Task status:			KILLED
Warning:			You have specified 4000 minutes walltime. CRAB3 changed this value to 2800 minutes..
Warning:			You have specified 4000 memory requirement and jobs can stay idle. Requirement of memory should not exceed 2500MB.
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150413_074927%3Ajbalcas_crab_resubmit-test168077
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150413_074927%3Ajbalcas_crab_resubmit-test168077
Details:			failed        100.0% (1/1)

Error summary:
1 jobs failed with exit code -1:
	Invalid framework job report. The framework job report exists, but it cannot be loaded.
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes
Log file is /afs/cern.ch/user/j/jbalcas/Validation/Roles_GOOD/becms-role/CMSSW_7_0_6/src/aaa/crab_resubmit-test168077/crab.log
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ crab resubmit --walltime=16000
Warning: Incompatible CRABClient version "3.3.15.rc1" 
Server is saying that compatible versions are: ['3.3.4.rc3', 'development']
Sending the request to the server
Resubmit request successfuly sent to the CRAB3 server.
Log file is /afs/cern.ch/user/j/jbalcas/Validation/Roles_GOOD/becms-role/CMSSW_7_0_6/src/aaa/crab_resubmit-test168077/crab.log
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ crab status
Warning: Incompatible CRABClient version "3.3.15.rc1" 
Server is saying that compatible versions are: ['3.3.4.rc3', 'development']
Task name:			150413_074927:jbalcas_crab_resubmit-test168077
Task status:			FAILED
Error during task injection:	Problem handling 150413_074927:jbalcas_crab_resubmit-test168077 because of global name 'HTTPRequests' is not defined failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.15.rc1/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc1/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 74, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.15.rc1/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc1/lib/python2.6/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 129, in execute
    self.execute_internal(*args, **kwargs)
  File "/data/srv/TaskManager/3.3.15.rc1/slc6_amd64_gcc481/cms/crabtaskworker/3.3.15.rc1/lib/python2.6/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 43, in execute_internal
    userServer = HTTPRequests(self.server['host'], kw['task']['user_proxy'], kw['task']['user_proxy'], retry=2)
NameError: global name 'HTTPRequests' is not defined


No jobs created yet!
Log file is /afs/cern.ch/user/j/jbalcas/Validation/Roles_GOOD/becms-role/CMSSW_7_0_6/src/aaa/crab_resubmit-test168077/crab.log
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ 
[jbalcas@lxplus0169 src]$ crab resubmit --walltime=16000
Warning: Incompatible CRABClient version "3.3.15.rc1" 
Server is saying that compatible versions are: ['3.3.4.rc3', 'development']
Sending the request to the server
Error contacting the server.
Server answered with: Execution error
Reason is: There are no jobs to resubmit. Only jobs in status ['held', 'failed'] can be resubmitted. Jobs in status ['finished'] can also be resubmitted, but only if the jobid is specified.
Log file is /afs/cern.ch/user/j/jbalcas/Validation/Roles_GOOD/becms-role/CMSSW_7_0_6/src/aaa/crab_resubmit-test168077/crab.log
[jbalcas@lxplus0169 src]$ 
```

**Comment by AndresTanasijczuk** [comment]
So the first time the resubmission worked, but there is an error in (your?) TW, therefore the task went to status FAILED and it also shows "No jobs created yet!". The second resubmission didn't work I guess because status reports that there are no jobs created.

**Comment by AndresTanasijczuk** [comment]
crab status returned no jobs, because it read that there is a failure in the task DB: https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L264-282

**Comment by mmascher** [comment]
Should we remove the if at line 264 and always do the status? I think so..

**Comment by AndresTanasijczuk** [comment]
In the previous version of the resubmit function in DataWorkflow (before my resubmit patch) the resubmission would have proceeded https://github.com/dmwm/CRABServer/blob/8bd634c9dcfb9b35e5a86dec06a4009f2f3cfe5f/src/python/CRABInterface/DataWorkflow.py#L263-308 because there was no check on whether the resubmitList was an empty list or not, and I think all jobs would have been resubmitted. In the new resubmit function in DataWorkflow I do check if resubmitList is not empty. 

Notice that there was a check on the resubmitList in case a list of jobids was passed in 'crab resubmit': https://github.com/dmwm/CRABServer/blob/8bd634c9dcfb9b35e5a86dec06a4009f2f3cfe5f/src/python/CRABInterface/DataWorkflow.py#L281-289 and in that case the resubmission would have failed with similar error. So I thought we should be consistent, and allow or not allow the resubmission of jobs independently on whether the user gives a list of jobs to resubmit or not. 

I think we should decide whether the status should return the list of jobs even in there was en error or the resubmission should work even if the status doesn't return a a list of jobs.

**Comment by belforte** [comment]
why in helll a failure to REsubmit should prevent from seeing the status of SUBMITTED jobs ?
Are you flagging the REsubmit failure with the same task status as a failure of the initial crab submit ?

**Comment by belforte** [comment]
All commands (status, kill a new resubmit) must work even if a previous REsubmit failed.
Expecially because the "no job is in such a status to be resubmittable now" is a condition which could change.

**Comment by AndresTanasijczuk** [comment]
I seem we agree that even if the task is in FAILED status, we should try to show the status of the jobs. I will work on that then. But not sure if it is as easy as to remove the if in https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L264

**Comment by belforte** [comment]
It all depends on what "task in FAILED" status exactly means.
If RESUBMIT failed because e.g. there is not job in such a status to be resubmitted,
the task should not be in FAILED status.
Hopefully task=FAILED is defined in a non-moving place and code can
e.g. refer to this in the comments. We should make sure nobody needs to go through this discussion again two years from now.

I would not remove that "if".
Possibly because I really do not understand the logic there.

**Comment by mmascher** [comment]
"FAILED" means that the task worker failed to process the task, whatever operation that mean (submit, resubmit, kill). Maybe we just need to introduce RESUBMITFAILED. But still, I would review the logig of the if, in cases like that  https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/8077.html we should show the jobs.

**Comment by belforte** [comment]
HA !! So task=FAILED has nothing to do with the jobs having succeeded or not !
Imagine all is fine, and done, by misktake I type crab kill, the task becomes FAILED.
Is that really so ?
how terribly confusing !

**Comment by mmascher** [comment]
No, the task status is the status of the task for the task worker, which does not know anything about jobs.

> Imagine all is fine, and done, by misktake I type crab kill, the task becomes FAILED.

I believe we introduced KILLFAILED but not RESUBMIT failed at some point (have to check the code). But yes, that's the case for the resubmit, and that's what happened to the user.

**Comment by belforte** [comment]
good luck in teaching this to users :-(

**Comment by mmascher** [comment]
That's one of the reasons why I always put frontend/backend in the error
messages BTW

Anyway, I think we had this conversation before and might have written down
on some tickets how to improve things but never really found the time to do
it :(

**Comment by belforte** [comment]
On 04/17/2015 12:50 AM, Marco Mascheroni wrote:
> That's one of the reasons why I always put frontend/backend in the error
> messages BTW

My problem with that is that you write in the message information
that only make sense/is useful to you, while having it look like
something user should be interested in. In addition to the fact
that CRAB frontend runs as CMSWEB backend, which is confusing for "us" as well.
Which a layer or services like we have, front ad back are too generic.
I encourage you to think about explicit component names whenever
you really feel you need to give more details then "CRAB".
