### ISSUE TITLE
resubmission request is silently ignored

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4759]
see user report here
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/525.html

Maybe this is cured in new version under test now ?

**Comment by AndresTanasijczuk** [comment]
@belforte Do you refer to the general fact that when a user does 'crab resubmit' he/she just gets the message 

Sending the request to the server
Resubmit request successfuly sent to the CRAB3 server.
Log file is ...

while CRAB may not have resubmitted jobs "as expected"?

Notice that 'crab submit' also can fail while the user may just get the message

Will use configuration file ...
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: ...
Please use 'crab status' to check how the submission process proceeds.
Log file is ...

Its only after the user does 'crab status' that he/she will see if the jobs were submitted successfully or not. In that sense it is the same with 'crab resubmit'. With 'crab submit' one can use the --wait option which will kind of do a status and "wait" until the jobs are submitted. This is not available in resubmission.

**Comment by belforte** [comment]
@AndresTanasijczuk I am afraid yes !
So the user was confused. And I was confused.
I agree that it is not easy to convey the right message. But as a start can you add a similar line to what doen for submit ? sort of
"OK I will try to resubmit, but I do not know yet if this is possible, you will know when you do crab status next". And should one wait ... how long ?

It is a tricky situation.

**Comment by AndresTanasijczuk** [comment]
What about simply "Please use 'crab status' to check if jobs were resubmitted."

**Comment by AndresTanasijczuk** [comment]
I made a pull https://github.com/dmwm/CRABClient/pull/4443 adding the message "Please use 'crab status' to check how the resubmission process proceeds." You can comment there if you prefer another message.

**Comment by AndresTanasijczuk** [comment]
Pull dmwm/CRABClient#4443 was merged. @belforte Can we close this issue?

**Comment by belforte** [comment]
yes, we can close. I am closing.
