### ISSUE TITLE
htcondor issue for auto proxy lifetime update

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4760]
https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=5001

**Comment by belforte** [comment]
IIUC this is fixed in HTCondor 8.3.6 (which we'll run soon).
So the action on us is to remove from TW the extra work we do now as indicated in the HTC issue.

**Comment by mmascher** [comment]
The extra work being the update of the classad (this line https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/RenewRemoteProxies.py#L102). Right @bbockelm ?

Of course we shoult test that the condor code actually works first!

**Comment by belforte** [comment]
we run the good HTCondor now.
let's check it works , remove useless code, and close.
