### ISSUE TITLE
TW logging problems

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4762]
Lets say we need to update TW configuration and we nicely kill TW, update configuration, start TW again. 

If you make these steps, twlog.txt.<date> and twlog.txt got corrupted and messing logs. 
proc.master is not flushed and it starts from scratch.

**Comment by mmascher** [comment]
Hi, this should fix it
https://github.com/dmwm/CRABServer/commit/4911b9c6176ba3645086b7b60ea5e719684b8376

Or at least let's reconsider this after the patch is deployed

**Comment by belforte** [comment]
did that commit fix it then ?
(looks to me it was deployed)

**Comment by juztas** [comment]
twlog.txt yes, but not proc.master

**Comment by belforte** [comment]
tw logas are OK now.
