### ISSUE TITLE
Be aware: WMCore RESTError cuts messages longer than 200 characters.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4766]
For reference: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Error.py

For example this message https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L67-71 is cut and the user will not be able to read it all. See for example https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/344.html

**Comment by belforte** [comment]
goes in the direction of doing "nice checks" in the client,
i.e. checks that educate and guide users to solution as well.

While server will assume things are correct and in case spit
terse error in best cmsweb tradition.

**Comment by belforte** [comment]
@AndresTanasijczuk indeed we need to be aware. But unless you suggest we go through all places in the code where a msg can be generated and fix them, we should better closet this ticked and open specific ones when a truncated message is detected. REST code already marks it when this happens:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Error.py#L217-L223

**Comment by mmascher** [comment]
Is the message you pointed there still truncated? If so I would start with that. How long is it?

**Comment by mmascher** [comment]
@dciangot , can you check if the message in question is still cut, please?

**Comment by belforte** [comment]
seems we did not hit a problem in this area in years. Let's close
