### ISSUE TITLE
Fix documentation on how to run (and debug) the Pre(Post)Jobs

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4774]
This recipe is broken with the recent changes: https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#To_run_a_pre_job_on_the_schedd

I had to change the permission of the prejob log directory [1], and the resubmit_info dir. Besides, the .job.ad is not there [2] and I had to recreate a new .job.ad file with `sudo condor_history -l 2248902.0 > /tmp/.job.ad`. If there is no other way at least this should be documented.

[1]
```
Got a fatal exception: [Errno 13] Permission denied: '/data/srv/glidecondor/condor_local/spool/467/0/cluster2250467.proc0.subproc0/prejob_logs/prejob.3.1.txt'
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/data/srv/glidecondor/condor_local/spool/467/0/cluster2250467.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 96, in <module>
    retval = bootstrap()
  File "/data/srv/glidecondor/condor_local/spool/467/0/cluster2250467.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py", line 28, in bootstrap
    return PreJob.PreJob().execute(*sys.argv[2:])
  File "TaskWorker/Actions/PreJob.py", line 440, in execute
    fd_prejob_log = os.open(prejob_log_file_name, os.O_RDWR | os.O_CREAT | os.O_TRUNC, 0644)
OSError: [Errno 13] Permission denied: '/data/srv/glidecondor/condor_local/spool/467/0/cluster2250467.proc0.subproc0/prejob_logs/prejob.3.1.txt'
```

[2]
```
Traceback (most recent call last):
  File "TaskWorker/Actions/PreJob.py", line 156, in get_task_ad
    self.task_ad = classad.parseOld(open(os.environ['_CONDOR_JOB_AD']))
IOError: [Errno 2] No such file or directory: '.job.ad'
```

**Comment by mmascher** [comment]
Point is I don't want to run anything as root, and changing the permission.. well, so boring.. I still do not understand why everything was owned by my username a couple of months ago and changed. I'll talk to Farrukh. For security reasons it is better that files are not owned by root.

The other problem about the `.job.ad` not being available: maybe in the PreJob we can copy the `.job.ad` file of the first job it to the spool directory (only one cp per task if the file is not already there)? It will serve only for debug purposes but could be useful.

**Comment by juztas** [comment]
From 8.3.2 version job.ad is written by schedd and yes, it is owned by root. If it would be not owned by root, IIRC it will allow to do condor_ssh_to_job for anyone and we don't want that.

**Comment by belforte** [comment]
is it useful to keep this open ? i.e. is someone (expert) going to look at it ?
I looked to a couple spool directories and can't find the `.job.ad` file, but maybe it is not needed any more or not supposed to be there at all times ?

**Comment by mmascher** [comment]
Hi Stefano,

I prefer to keep it open untile we update the documentation. Jobads are now saved in finished_jobs in the "spool" direcotry of the task.

**Comment by emaszs** [comment]
I've modified the documentation accordingly, seems to work fine. [1]

[1] https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#To_run_a_post_job_on_the_schedd

**Comment by mmascher** [comment]
I have tested yesterday the prejob and worked. Documentation seems good for postjob, closing this one and reopening if necessary (or actually we can directly edit the twiki if instructions does not work).
