### ISSUE TITLE
Should we show json fjr file in dashboard or not?

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4795]
We are asking dashboard to show job log, postjob log and json fjr for each job. The last one is maybe not needed (we will already ask to show all files in the web directory via a separate link as glidemon does).
Example: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Atanasi&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150506_094811%3Aatanasi_crab_tutorial_May2015_MC_analysis_test1 The "Job Log JSON" link under "Job Log" column is what I am referring to.

**Comment by belforte** [comment]
yes, can skip json if it makes dashboard page more neat looking

**Comment by AndresTanasijczuk** [comment]
Dashboard is not showing this file anymore. Closing this issue.
