### ISSUE TITLE
Implement correction for split lumis in EventAwareLumiBased splitting

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4801]

**Comment by AndresTanasijczuk** [comment]
The lack of the correction explains https://github.com/dmwm/CRABServer/issues/4706

**Comment by belforte** [comment]
Lumi accounting is critical, so I worry that this issue may be forgotten since none is assigned and there's no milestone.
But I can't (easily) understand if this is still an open problem or not and what exactly is affected.
@AndresTanasijczuk @mmascher can you clarify ?

**Comment by AndresTanasijczuk** [comment]
The problem that this issue is referring to is: 2 jobs that analyze the same lumi. In the WMCore LumiBased splitting code there is a function (added by Brian and then improved by Marco) that takes care this doesn't happen. This correction should be implemented also in EventAwareLumiBased splitting, where it is currently missing (CRAB3 was not allowing the use of EventAwareLumiBased splitting at the time the above mentioned correction was implemented).

**Comment by belforte** [comment]
I understand, thanks. But it looks a reasonably complicated task. Our first goal is to make sure we do not produce duplicated events.
I guess the first step is to detect this situation, exit and force user to use LumiBased splitting. Would this be easy ? 
Then the we can see about implementing the correction twice or differently.

**Comment by ericvaandering** [comment]
They are not duplicated events, but rather events from the same lumi that ended up in two different files. In run1 only. The only concern is that if you successfully analyze one of the two files and fail on the other, the lumi calculation will treat it as if you successfully analyzed the whole lumi.

Eric

> On Sep 11, 2015, at 06:34, Stefano Belforte <notifications@github.com> wrote:
> 
> I understand, thanks. But it looks a reasonably complicated task. Our first goal is to make sure we do not produce duplicated events.
> I guess the first step is to detect this situation, exit and force user to use LumiBased splitting. Would this be easy ? 
> Then the we can see about implementing the correction twice or differently.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/CRABServer/issues/4801#issuecomment-139520666>.
> 




Eric W. Vaandering 
Computing Physics Developer
CMS Computing Development Lead

Scientific Computing Division
Fermi National Accelerator Laboratory
630 840 6678 office
www.fnal.gov <http://www.fnal.gov/>

**Comment by belforte** [comment]
shame on me. Should have remembered. Maybe Sicily sun cooked my brain ?
Still I think that if possible we start with simply flagging and then look into optimizing.
Seems to me there's enough in crab3 to do list.

**Comment by mmascher** [comment]
doing this now, should be really easy considered that LumiBased EventAwareLumiBased are really similar

**Comment by belforte** [comment]
maybe, but surely validating a solution is more work than validating a flagging. There are tens and tens of easy to do things in the list. Do whatever you prefer, as long as it is done fast.

**Comment by mmascher** [comment]
Done
