### ISSUE TITLE
Save previous state of the task

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4803]
It would be useful to save 1 previous state of the task for several things:
* crab status can know what was previous state and do not need to guess what was the status by trying to get node_state or querying schedd
* monitoring page and filtering possibility.

**Comment by mmascher** [comment]
Not sure about that. The HOLDING intermediate state is making everything more complicated and things migh not work as expected.

**Comment by AndresTanasijczuk** [comment]
We were discussing a bit with Marco about this yesterday. There is a bug in the design of the MasterWorker code (see https://github.com/dmwm/CRABServer/pull/4976/files#diff-5ea85b84cec1200ade4dbc605696e6ccR253) for which I think saving the previous relevant task status would be useful. Actually, I would save the previous real task status (SUBMITTED, FAILED, COMPLETED, KILLFAILED, etc) and the action (NEW, RESUBMIT, KILL). The later is needed for fixing the bug mentioned above, while the first is needed for what Justas wrote.

**Comment by belforte** [comment]
will be solved with new TM state machine as discussed this week: #5076
