### ISSUE TITLE
Integrated time is exaggeratedly high (evidently not well calculated)

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4808]
See job 6 in http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=1095052&showResubmits=1
In particular retry count 3. PostJob log: http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0114.cern.ch/mon/cms1361/150515_085504:venturi_crab_OOTmultiplicity_minbias_run2012D_v4/postjob.6.3.txt
It is saying "Not retrying a job because the integrated time (across all retries) is 987 hours."

**Comment by juztas** [comment]
it is fixed in new release, which Jadir installed today on production. This was solved in same pull request for job_log file copy.

**Comment by AndresTanasijczuk** [comment]
Ok. Closing then.
