### ISSUE TITLE
do not send errror summary in json format to dashboard

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4810]
@mmascher as discussed with dashboard people

**Comment by belforte** [comment]
maybe a duplicate of #4795

**Comment by AndresTanasijczuk** [comment]
What is meant by "error summary" here?

**Comment by belforte** [comment]
hmm... maybe @mmascher remembers more ?
I would think it refers to this
https://dashb-cms-job-task.cern.ch/dashboard/request.py/jsonprettify?json=http://vocms058.cern.ch/mon/cms1761/150609_120239:jbalcas_crab_TTBar_13_1325_0/job_fjr.1.0.json&prettyprint
as idea was not to send JSON to dashboard

**Comment by mmascher** [comment]
Yes, it is that file and it is a duplicate, closing.
