### ISSUE TITLE
Change how long jobs will sleep in failure or fast jobs

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4818]
Currently in https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.sh and https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh in any case of issue it sleeps 20 minutes, so it might be several issues on site and job will sleep for 40m or 60m...
a) if job is failing and runtime is less than 20 minutes, sleep for left time and job runtime will be ~20minutes.
b) if job ran successfully and runtime was less than 20 minutes, sleep for left time to not flood cmsweb.

Comments?

**Comment by mmascher** [comment]
I discussed this with Justas this morning, it would be nice that the sleep in case of failed job would be done in one place. These sleep are spread around the code (there is also one in CMSRunAnalysis.py), and it would be nice to do one once at the end of the job wrapper imho.

**Comment by belforte** [comment]
+1
with a note:
if game is over, (failed of succeeded is irrelevant) indeed add sleep only at the end to pad to 20min (like Crab2 was doing btw). But in theory those scattered around sleeps my have different reason, like be part of a retry loop.
P.S. I do not understand the note about being nice to cmsweb. Main reason to pad short jobs to 20min (but 10 may do) is to mitigate black holes (which may not always result in failure), then to avoid excessive load on HTC, and to punish user a bit for submitting stuff which fails in first line of code.

**Comment by mmascher** [comment]
About cmsweb I think it's just that it will suffer (as many other services)
it there are many short jobs

**Comment by belforte** [comment]
why do running jobs talk to cmsweb ? ASO ?

**Comment by mmascher** [comment]
Yes, ASO and also a phedex dependency we have never removed to convert the
sename retrieved from the siteconfig to the phedex node name (phedex node
name should be in the siteconfig now). Well, this phedex dependency should
be really light, the ASO one imply an interaction with couch and is more
worrysome..

**Comment by juztas** [comment]
Fixed: https://github.com/dmwm/CRABServer/pull/4882
