### ISSUE TITLE
create tarballs on TW startup

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4826]
it would make developers life easier to modify tarball and test their fixes.

**Comment by belforte** [comment]
I'd like to ask Ivano Talamo to do, but can't find in the Assignee list. We better talk with him anynow.

**Comment by emaszs** [comment]
Could someone go into a bit more detail about which tarball creation we're trying to change here, as well as where they should be created from now on? Thanks

**Comment by juztas** [comment]
Here is the script which I am using. Main part is inside htcondor_make_runtime.sh
```
  1 # Run the script from your github CRABServer directory
  2 CRAB3_VERSION=3.3.0-pre1
  3 RELEASE=3.3.1602.rc3-comp
  4 MYTESTAREA=/data/srv/TaskManager/current
  5 CRABTASKWORKER_ROOT=$MYTESTAREA/slc6_amd64_gcc493/cms/crabtaskworker/$RELEASE
  6 # CRAB_OVERRIDE_SOURCE tells htcondor_make_runtime.sh where to find the CRABServer repository
  7 export CRAB_OVERRIDE_SOURCE=/data/user/
  8 sh bin/htcondor_make_runtime.sh
  9 mv TaskManagerRun-$CRAB3_VERSION.tar.gz TaskManagerRun.tar.gz
 10 mv CMSRunAnalysis-$CRAB3_VERSION.tar.gz CMSRunAnalysis.tar.gz
 11 if [ "$(hostname)" != "balcas-crab2" ]; then
 12    cmd=scp
 13    targethost='jbalcas@balcas-crab2.cern.ch:'
 14 else
 15    cmd=cp
 16    targethost=
 17 fi
 18 $cmd CMSRunAnalysis.tar.gz CRAB3-externals.zip TaskManagerRun.tar.gz $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/AdjustSites.py $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/dag_bootstrap_startup.sh $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/d    ag_bootstrap.sh $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/gWMS-CMSRunAnalysis.sh $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/CMSRunAnalysis.sh $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/cmscp.py $CRAB_OVERRIDE_SOURCE/CRABServer/scripts/Das    hboardFailure.sh $targethost$CRABTASKWORKER_ROOT/data
```

**Comment by juztas** [comment]
So if a bit more details.
Currently these tarballs are created during RPM creation.  If there is any bug on TW, we need to update tarballs which is not straight forward. The point of this ticket is whenever you start TW, it should create all these tarballs from its current directory and code base. This would allow more easily for developers to do changes on scripts which are executed on grid and also in production or pre-production to patch only the bug or add feature.

**Comment by emaszs** [comment]
At the moment I don't see an easy way to grab the correct versions needed for building the tarballs on production. On a private instance it's easy because the developer could put the needed versions into a script (taskworker_env.sh perhaps) and update them as necessary. 

When creating a new RPM though, the versions for the tarballs are taken from the crabtaskworker.spec file itself (https://github.com/cms-sw/cmsdist/blob/comp_gcc493/crabtaskworker.spec#L35-L37). I suppose I could download the spec file and extract the needed information via python, but perhaps there's an easier way?

**Comment by mmascher** [comment]
My idea in production would be that an operator regularly source the TaskWorker environment, and then he would modifiy files like `$CRABTASKWORKER_ROOT/lib/python2.7/site-packages/TaskWorker/Actions/PostJob.py` (where `$CRABTASKWORKER_ROOT` is set by the env script) without worrying of modifying the tarball files.

**Comment by mmascher** [comment]
Hi @emaszs , about this patch, I found this thing https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L253 (I think I told you to check for the existance of it(?)). Anyway, I have never tried it, but it seems that if the `CRAB3_CHECKOUT` variable then DagmanCreator will take the runtime files from this location.

So, I'd like to postpone a little bit merging the patch and review a little bit with you what is done and what we should do. I fear that if I simply merge this the whole thing becomes a bit messy.

**Comment by emaszs** [comment]
@mmascher , yes, `CRAB3_CHECKOUT` is a perfectly fine way to take the runtime files from a different location, including the tarballs. Correct me if I'm wrong, but those tarballs still have to be rebuilt after a change so I don't see how that helps.

**Comment by belforte** [comment]
@emaszs I suspect all that could be done was done. Shall we close ?

**Comment by emaszs** [comment]
Probably close, yeah. To recap, I'm not aware of a relatively simple way to rebuild the tarballs for a taskworker installed from an RPM(like in prod or preprod, where CRABServer repo isn't available). The code from my PR could allow building the tarballs in a dev environment automatically, but I personally wouldn't find that useful and it requires setting an extra environment variable, so maybe the PR should be closed as well.

**Comment by belforte** [comment]
in the end.. not worth the effort.
