### ISSUE TITLE
identify why gsissh hanged requesting password

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4827]

**Comment by belforte** [comment]
usually it is a sign that gsi authentication failed. Which can
be due to many causes. What is that you want to solve ? Make gsi always
work, or when it fails sort of fail immediately rather then wait for password ?

**Comment by juztas** [comment]
Now I can`t test, because they turned off that scheduler. The command which hanged was:
```
gsissh -o ConnectTimeout=60 -o PasswordAuthentication=no gls.hep.brown.edu pwd
```
and it was waiting for password input all the time. Jadir noticed that NEW tasks are increasing, and this command was taking already ~2h.

so ConnectTimeout was not the case, because if I read this correctly waiting for password is not the case:
```
ConnectTimeout
Specifies the timeout (in seconds) used when connecting to the SSH server, instead of using the default system TCP timeout. This value is used only when the target is down or really unreachable, not when it refuses the connection. 
```
But this:
```
PasswordAuthentication
Specifies whether to use password authentication. The argument to this keyword must be ''yes'' or ''no''. The default is ''yes''. 
```
had not to allow to enter the password. So now I suspect that maybe it misses this parameter, but I can`t test it :disappointed: 
```
PreferredAuthentications
Specifies the order in which the client should try protocol 2 authentication methods. This allows a client to prefer one method (e.g. keyboard-interactive) over another method (e.g. password) The default for this option is: ''
gssapi-with-mic, hostbased, publickey, keyboard-interactive, password''. 
```
strace and full debug mode would allow us to identify what is missing

**Comment by belforte** [comment]
in my experience, removing password from PreferredAuthentications works.
I never tried PasswordAuthentication=no
beware that behavior could depend on openssh version

**Comment by juztas** [comment]
what about adding `timeout 60` before gsissh command? In that case if it fails to connect with gsissh it will exit with 124 exit code, which will lead to failure

**Comment by juztas** [comment]
@mmascher @belforte

**Comment by mmascher** [comment]
Using timeout sounds good to me. This way we are safe no matter what
openssh server version we are using

**Comment by belforte** [comment]
sounds good.
