### ISSUE TITLE
Do not enforce srmv2 protocol for direct stageout

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4836]
From the meeting (https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2358/1.html)
> * Q: why are we forcing the srmv2 protocol for direct-stageout instead
> of taking what is specified in SITECONF?
>    * Marco: no particular reason, we should change it

**Comment by belforte** [comment]
it is not a matter of taste . There is only one correct thing to do, the 
same as SAM test does, so that it is validated.

**Comment by juztas** [comment]
SAM tests checking lcg-cp and after that gfal-copy. After discussing with Andrea, he agrees that SAM tests should do what CMS jobs do. I still think we should not enforce only lcg-cp for direct stageout. GFAL2 plugin is available in new WMCore and tested with CRAB3 and WMAgent. (https://github.com/dmwm/WMCore/pull/5956)

**Comment by belforte** [comment]
which SAM test(s) do you exactly refer to ?
I wonder if you and Sciaba' did not understand each other.

At some point in the past SAM was using exactly same code as WMAgent.
Looking at current SAM test log I see that it accesses the local config file to get the stageout protocol and at least in this case no sign of gfal, but I do not know where to find the test source anymore
http://wlcg-sam-cms.cern.ch/dashboard/request.py/metricOutput?host=cream-ce-2.ba.infn.it&metricfqan=org.cms.WN-mc%20%28/cms/Role_production%29&time=2015-06-15T14:05:18Z

but looking for same test at FNAL, it seems it uses xrdcp
http://wlcg-sam-cms.cern.ch/dashboard/request.py/metricOutput?host=cmsosgce.fnal.gov&metricfqan=org.cms.WN-mc%20%28/cms/Role_production%29&time=2015-06-15T14:30:14Z

**Comment by belforte** [comment]
in light of recend discussion in CompOps and my re-reading of the code,
I suspect I misunderstood the subject.
I thought "direct stageout" to mean 'directly to the local SE", but I guess it means "directly to remote SE".
Maybe it would have been better ot use local and remote, but I can understand you do not want to change the source code now.

**Comment by belforte** [comment]
so, names aside. IMHO this has nothing to do with SAM (sorry for confusion) nor SITECONF. We do not ask sites to indicate in the configuration which version of the grid middleware they have. So it should be done like in the current client: look for gfal2 and if not found use lcg-*. If neither work, throw a fatal error.

**Comment by juztas** [comment]
yes

**Comment by belforte** [comment]
and try to code is so that it can also be used in SAM , see:
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/2363/2/2/1/4/1/2/1.html
