### ISSUE TITLE
show TW version on postjob logfiles

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#4840]

**Comment by juztas** [comment]
This should be enough 
```
sed -i "s|__version__ = '.*|__version__ = '%{realversion}'|" src/python/TaskWorker/__init__.py
```
https://cms-http-group.web.cern.ch/cms-http-group/tutorials/environ/dmwm-build.html#getting-pkgtools-and-cmsdist

**Comment by belforte** [comment]
@mmascher can you assign this to someone who understand what it exactly means and set a milestone according to the amount of work ?

**Comment by juztas** [comment]
For next release (October) add this line:
```sed -i "s|__version__ = '.*|__version__ = '%{realversion}'|" src/python/TaskWorker/__init__.py``` here: https://github.com/cms-sw/cmsdist/blob/comp_gcc481/crabtaskworker.spec#L37

**Comment by mmascher** [comment]
Done in https://github.com/dmwm/CRABServer/pull/4990 and I have modified the specfile. Let's close when everything is committed and we verify the __version__ is there on the testbed.

**Comment by AndresTanasijczuk** [comment]
This issue is done and working, right @mmascher ? Should you close this issue?

**Comment by belforte** [comment]
it is there, although a bit cryptic, makes it sound like it is a PostJob version. I'd do
s/Version/TaskWorker Version/
Sun, 22 Nov 2015 16:06:13 PST(+0000):INFO:PostJob ======== Starting post-job execution. Version 3.3.1511.rc1

**Comment by AndresTanasijczuk** [comment]
Sorry Stefano, I don't understand "s/Version/TaskWorker Version/". Can you instead write how would you like that the result looks like in the post-job log? Lets assume TW version is 3.3.1511.rc1.

**Comment by belforte** [comment]
`Sun, 22 Nov 2015 16:06:13 PST(+0000):INFO:PostJob ======== Starting execution. Task Worker Version 3.3.1511.rc1`
