### ISSUE TITLE
Improve error msg for resubmit failure

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4849]
If task is in failed state and it failed on TW for any reason, like this one:
```
INFO 2015-06-17 14:36:57,398: 	 CRAB project directory:		/raid/raid8/bockjoo/newHiggsPatuplizer/CMSSW_5_3_9_patch3/src/Submission_DATA_2012A_8TeV_2012A/MuEG_Run2012A-22Jan2013-v1_193622-193751/crab_20150607_185519
INFO 2015-06-17 14:36:57,398: 	 Task name:			150607_225622:bockjoo_crab_20150607_185519
INFO 2015-06-17 14:36:57,398: 	 Task status:			FAILED
ERROR 2015-06-17 14:36:57,399: 	 Error during task injection:	The CRAB3 server backend could not submit any job to the Grid scheduler:
splitting task 150607_225622:bockjoo_crab_20150607_185519 on dataset /MuEG/Run2012A-22Jan2013-v1/AOD with LumiBased method does not generate any job
INFO 2015-06-17 14:36:57,399: 	 
No jobs created yet!
```
Resubmit option is possible, and it will end up to:
```
ERROR 2015-06-19 15:56:22,650: 	 Error during task injection:	The CRAB3 server backend could not resubmit your task because the Grid scheduler answered with an error.
This is probably a temporary glitch, please try it again and contact an expert if the error persist.
Error reason: Trapped exception in Dagman.Fork: <type 'exceptions.RuntimeError'> Unable to edit jobs matching constraint <traceback object at 0x2c1c2d8> 
  File "/data/srv/TaskManager/3.3.1506.rc3/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1506.rc3/lib/python2.6/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 111, in execute_internal
    schedd.edit(rootConst, adparam, str(task['resubmit_'+taskparam]))
```
Which is correct, but error message after resubmit needs to be improved.

**Comment by belforte** [comment]
and at least in this case it was not a temporary glitch, task was never submitted to begin with
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/704/1.html

**Comment by juztas** [comment]
Also true

**Comment by AndresTanasijczuk** [comment]
In https://github.com/dmwm/CRABServer/pull/4976 I am introducing a new task status 'SUBMITFAILED' which will be assigned to a task for which the original submission has failed, and tasks in that state will not be able allowed to be resubmitted. Would that fix this issue?

**Comment by mmascher** [comment]
I think so, this will help at least understanding if resubmit is possible or not

**Comment by AndresTanasijczuk** [comment]
You mean it will help users to understand if resubmit is possible or not? 
Should I add "Fixes #4849" to the commit in #4976 ?

**Comment by mmascher** [comment]
Yes, and us giving a proper error message

**Comment by belforte** [comment]
What will happen to those tasks then since they can't be resubmitted?  Is this a terminal state? 
Sent from Stefano's mobile 
On Aug 28, 2015 10:36, Andres Tanasijczuk <notifications@github.com> wrote:In #4976 I am introducing a new task status 'SUBMITFAILED' which will be assigned to a task for which the original submission has failed, and tasks in that state will not be able allowed to be resubmitted. Would that fix this issue?

**Comment by AndresTanasijczuk** [comment]
'SUBMITEDFAILED' will be a terminal unrecoverable state.

**Comment by belforte** [comment]
How does this differ From FAILED?  Can failed tasks be resubmitted (forever)? 
Sent from Stefano's mobile 
On Aug 29, 2015 18:05, Andres Tanasijczuk <notifications@github.com> wrote:'SUBMITEDFAILED' will be a terminal unrecoverable state.

**Comment by AndresTanasijczuk** [comment]
FAILED is for tasks that have completed but some job has failed. They can be resubmitted (forever). If resubmission succeeds, the status of the task will become SUBMITTED; if it fails it will become RESUBMITFAILED, which is also resubmittable. I will prepare a diagram to explain all possible task statuses, how one can go from one status to another, etc.

In the future, we will implement the DAG Final node to monitor (and resubmit) publications and to set the task status into COMPLETED or FAILED in the TaskDB. So FAILED will correspond to tasks for which the DAG has finished running and something (a job or a publication) has failed.

**Comment by AndresTanasijczuk** [comment]
This issue can be closed now that https://github.com/dmwm/CRABServer/pull/4976 was merged.

**Comment by AndresTanasijczuk** [comment]
Can this issue be closed?
