### ISSUE TITLE
kibana monitor: show tasks in RESUBMIT and KILL

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4871]
Right now it seems the TW digested all the tasks in the `NEW` state, but there are still a queue of tasks in resubmit that needs to be processed. It would be nice to show them in the monitor page:

https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/crab3mon::crab3mon

**Comment by jmarra13** [comment]
Will be added next monday.

Sent from my phone
Em 16/07/2015 21:04, "Marco Mascheroni" <notifications@github.com> escreveu:

**Comment by mmascher** [comment]
Sure, no hurry. Since you are at that, we should also change the way we get the number for states that are "not final". I mean, for final states it's ok to take the last two hours, but for "temporary" states we should get the absolute number.

We can get this using a high number of minutes: `https://cmsweb-testbed.cern.ch/crabserver/prod/task?subresource=counttasksbystatus&minutes=1000000000`

So I would do two calls, one for `KILL, RESUBMIT, NEW` with `minutes=1000000000` and one for `SUBMITTED, FAILED, KILLED, KILLFAILED, UPLOADED` with `minutes=120` (or whatever we have now)

**Comment by belforte** [comment]
mixing rates and levels in the same display will be very confusing.
I thought the number in non-final states is for the donut colored shape at left

**Comment by mmascher** [comment]
True.

I think the donut is still a sort of average of the values you have in the right chart. In practice it does not make any sense :)

Any proposal on how to better display temporary and final states? Like the donut for final states and the right chart for temporary states?

**Comment by belforte** [comment]
I thought we had agreed on that long time ago. Can surely chance donut to a time chart
to see how "transient" states population evolve in time. Or add...
But then let's have two such charts first. If anything, the vertical scale is different !
Need to look  at things for a while, before settling on the best visualization

**Comment by mmascher** [comment]
Yes, I think something like that was agreed some time ago, but no action was taken.

Thinking a little bit about that I think it's useful to see the evolution over time of all the states. E.g., both NEW and SUBMITTED can give you a lot of information (NEW might increase because of a submission spike..)

Imho even though my initial proposal seems comfusing:

>So I would do two calls, one for KILL, RESUBMIT, NEW with minutes=1000000000 and one for SUBMITTED, FAILED, KILLED, KILLFAILED, UPLOADED with minutes=120 (or whatever we have now)

it's a good way to have a overall picture. Maybe we can use two charts per time so it's clear what an operator is looking at?

For the donut I would give a picture given of the timerange selected, i.e.: minutes=timerange

**Comment by belforte** [comment]
didn't you have an SQL call to use to get the tasks in the transient states
w/o the minutes=veryverylarge hack ?
anyhow, I am happy with two time charts, one for levels, one for rates.
the donut is likely useless and totally misleading at that point

By the way, what about QUEUED ? Is SUBMITTED the final status ? Doesn't task proceed to
anything different once all singing and dancing is over ?

On 07/17/2015 03:30 PM, Marco Mascheroni wrote:
> Yes, I think something like that was agreed some time ago, but no action was taken.
>
> Thinking a little bit about that I think it's useful to see the evolution over time of all the
> states. E.g., both NEW and SUBMITTED can give you a lot of information (NEW might increase because
> of a submission spike..)
>
> Imho even though my initial proposal seems comfusing:
>
>     So I would do two calls, one for KILL, RESUBMIT, NEW with minutes=1000000000 and one for
>     SUBMITTED, FAILED, KILLED, KILLFAILED, UPLOADED with minutes=120 (or whatever we have now)
>
> it's a good way to have a overall picture. Maybe we can use two charts per time so it's clear what
> an operator is looking at?
>
> For the donut I would give a picture given of the timerange selected, i.e.: minutes=timerange
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4871#issuecomment-122275150>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by mmascher** [comment]
Yes, `QUEUED` has to be added to the in the temporary state list, while at the moment SUBMITTED is a final state,  we do not change it once the dag is done.

**Comment by belforte** [comment]
I file a request to look into adding a state for when the task is gone out of active scope

**Comment by mmascher** [comment]
makes sense

**Comment by mmascher** [comment]
Hi @jmarra13 , you have done this right? Let me know if I can close it. Also, I think we already have a ticket for introducing the final DAG node and update the task to the completed state.

**Comment by jmarra13** [comment]
Yes @mmascher, i did it. About the final DAG node I need to find this ticket.

**Comment by AndresTanasijczuk** [comment]
This is the issue: https://github.com/dmwm/CRABServer/issues/4361
