### ISSUE TITLE
Improve error message when schedd is not responding

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4878]
I would like to improve the error message we get when the schedd is unresponsive:

```
     crab status crab_projects_21July_fromRaw/crab_SingleElectron/
     Error contacting the server.
     Server answered with: Execution error
```

I grepped on vocms022 the id of the error I found in the client logfile and the message I found is here [1] when trying to access the apache server on the schedd.

My proposal is an error message like:

`Failed to contact Grid scheduler vocms066.cern.ch. This might be a temporary error, please retry later and contact an operator if the error persist.`
or
`Failed to contact schedd vocms066. The schedd is not among the active schedds at the moment, which indicates a serious server problem. Please submit a new task`

depending if the schedd is in the `htcondorPool` in the backendurls or not.

The logic is that if the error is serious and the schedd is removed then people would better submit a new task.

Thoughts? I'll start implementing the basic version.

[1]
```
find /build/srv-logs/ | grep crabserver | xargs cat | grep -C 10 fcdea2202136ab0d14b98584eba28200
[...]
[21/Jul/2015:17:22:06]  SERVER DATABASE ERROR 500/403 Execution error pycurl.error fcdea2202136ab0d14b98584eba28200 [instance: prod] ((7, 'Failed to connect to vocms066.cern.ch port 80: No route to host')); last statement: SELECT tm_taskname, panda_jobset_id, tm_task_status, tm_user_role, tm_user_group,              tm_task_failure, tm_split_args, panda_resubmitted_jobs, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl,              tm_output_dataset, tm_collector, tm_schedd, tm_dry_run              FROM tasks WHERE tm_taskname=:taskname; binds: (), {'taskname': '150721_073502:amassiro_crab_SingleElectron'}; offset: None
[21/Jul/2015:17:22:06]    Traceback (most recent call last):
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/WMCore/REST/Server.py", line 1728, in dbapi_wrapper
[21/Jul/2015:17:22:06]        return handler(*xargs, **xkwargs)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/RESTUserWorkflow.py", line 493, in get
[21/Jul/2015:17:22:06]        result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/DataUserWorkflow.py", line 143, in status
[21/Jul/2015:17:22:06]        return self.workflow.status(workflow, userdn, userproxy, verbose=verbose)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/Utils.py", line 186, in throttled_wrapped_function
[21/Jul/2015:17:22:06]        return fn(*args, **kw)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/Utils.py", line 144, in wrapped_func
[21/Jul/2015:17:22:06]        return func(*args, **kwargs)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 326, in status
[21/Jul/2015:17:22:06]        taskStatus = self.taskWebStatus(DBResults, verbose=verbose)
[21/Jul/2015:17:22:06]      File "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py", line 563, in taskWebStatus
[21/Jul/2015:17:22:06]        curl.perform()
[21/Jul/2015:17:22:06]    error: (7, 'Failed to connect to vocms066.cern.ch port 80: No route to host')
[21/Jul/2015:17:22:06] vocms0163.cern.ch 188.184.68.98 "GET /crabserver/prod/workflow?verbose=0&workflow=150721_073502%3Aamassiro_crab_SingleElectron HTTP/1.1" 500 Internal Server Error [data: 6105 in 726 out 3014605 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=amassiro/CN=669328/CN=Andrea Massironi" "" ] [ref: "" "CRABClient/3.3.1507" ]
```

**Comment by mmascher** [comment]
@juztas , review?

**Comment by belforte** [comment]
error is serious, but I suspect best action for user may
change according to the "reason of the day". I would simply
tell to contact support where we can say if problem will
be solved today or not. In case we can put more in a FAQ,
which we can change more easily than code !

Even if schedd is down, it is expected to restart with all
tasks inside and fully recover, so I would not encourage
to submit again things that will be running anyhow a few
hours from now.

Surely having the schedd name in the message is good !

On 07/21/2015 07:24 PM, Marco Mascheroni wrote:
> I would like to improve the error message we get when the schedd is unresponsive:
>
> |      crab status crab_projects_21July_fromRaw/crab_SingleElectron/
>       Error contacting the server.
>       Server answered with: Execution error
> |
>
> I grepped on vocms022 the id of the error I found in the client logfile and the message I found is
> here [1] when trying to access the apache server on the schedd.
>
> My proposal is an error message like:
>
> |Failed to contact Grid scheduler vocms066.cern.ch. This might be a temporary error, please retry
> later and contact an operator if the error persist.|
> or
> |Failed to contact schedd vocms066. The schedd is not among the active schedds at the moment, which
> indicates a serious server problem. Please submit a new task|
>
> depending if the schedd is in the |htcondorPool| in the backendurls or not.
>
> The logic is that if the error is serious and the schedd is removed then people would better submit
> a new task.
>
> Thoughts? I'll start implementing the basic version.
>
> [1]
> ```[21/Jul/2015:17:22:06] SERVER DATABASE ERROR 500/403 Execution error pycurl.error
> fcdea2202136ab0d14b98584eba28200 instance: prod <(7,>); last statement: SELECT tm_taskname,
> panda_jobset_id, tm_task_status, tm_user_role, tm_user_group, tm_task_failure, tm_split_args,
> panda_resubmitted_jobs, tm_save_logs, tm_username, tm_user_dn, tm_arguments, tm_input_dataset,
> tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl, tm_output_dataset,
> tm_collector, tm_schedd, tm_dry_run FROM tasks WHERE tm_taskname=:taskname; binds: (), {'taskname':
> '150721_073502:amassiro_crab_SingleElectron'}; offset: None
> [21/Jul/2015:17:22:06] Traceback (most recent call last):
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/WMCore/REST/Server.py",
> line 1728, in dbapi_wrapper
> [21/Jul/2015:17:22:06] return handler(/xargs, */xkwargs)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/RESTUserWorkflow.py",
> line 493, in get
> [21/Jul/2015:17:22:06] result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/DataUserWorkflow.py",
> line 143, in status
> [21/Jul/2015:17:22:06] return self.workflow.status(workflow, userdn, userproxy, verbose=verbose)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/Utils.py",
> line 186, in throttled_wrapped_function
> [21/Jul/2015:17:22:06] return fn(/args, */kw)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/Utils.py",
> line 144, in wrapped_func
> [21/Jul/2015:17:22:06] return func(/args, */kwargs)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py",
> line 326, in status
> [21/Jul/2015:17:22:06] taskStatus = self.taskWebStatus(DBResults, verbose=verbose)
> [21/Jul/2015:17:22:06] File
> "/data/srv/beHG1507f/sw.pre/slc6_amd64_gcc481/cms/crabserver/3.3.1507.rc5/lib/python2.6/site-packages/CRABInterface/HTCondorDataWorkflow.py",
> line 563, in taskWebStatus
> [21/Jul/2015:17:22:06] curl.perform()
> [21/Jul/2015:17:22:06] error: (7, 'Failed to connect to vocms066.cern.ch port 80: No route to host')
> [21/Jul/2015:17:22:06] vocms0163.cern.ch 188.184.68.98 "GET
> /crabserver/prod/workflow?verbose=0&workflow=150721_073502%3Aamassiro_crab_SingleElectron HTTP/1.1"
> 500 Internal Server Error [data: 6105 in 726 out 3014605 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic
> Units/OU=Users/CN=amassiro/CN=669328/CN=Andrea Massironi" "" ] [ref: "" "CRABClient/3.3.1507" ]
>
> ||
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/dmwm/CRABServer/issues/4878>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by mmascher** [comment]
I am thinking of adding the schedd name to the crab status as you suggested
some time ago :)

Anyhow, I was suggesting to make the message variable depending or not if
the schedd is in the "CRAB3 active scheduler". Meaning if there is an
operator intervation and the schedd is taken out from the list because it
is really bad, then the message switch to "please resubmit the task". That
is today's case by the way..

You are saying to remove the part about "contact an operator" at all?

On Tue, Jul 21, 2015 at 10:07 PM, Stefano Belforte <notifications@github.com

**Comment by juztas** [comment]
I like your first proposal message also with contact expert, but also maybe we should add a metric in another host, which is not schedd and queries all crab3 schedds. if schedd is not responsive for 30minutes, create alarm. This is done on cmsweb for services.
Now we did not got any alarm or user complain, Marco by mistake was submitting to that schedd and you failed and you noticed that.  Alarm would help here

**Comment by belforte** [comment]
Basically, I do not understand why people should resubmit the task, even today.
If vocms066 comes back up tomorrow morning, it will do all needed
resubmission. Or was it retired ?
Contact operator is fine. I think in the code we can tell
"expected, try again" from "unexpected, let ops know asap",
but for general issues like "schedd is down" there's no way to give
a fit-all-cases solution.
As a general strategy better have a few standardized errors and
have FAQ's for those.

**Comment by juztas** [comment]
@belforte is right, they should not resubmit, whenever machine is back all jobs goes back to the queue

**Comment by belforte** [comment]
Indeed we should be ashamed that a schedd was down for the whole day and nobody noticed.
One more thing for Jadir to worry about.
while we are here, why nobody can reboot it ?

**Comment by juztas** [comment]
I tried to ping Production, CRAB3, GlideInWMS team if they have access to Production openstack project.No one has. In that case we can not do anything without Ivan. 
This machine is kind of special one with huge ssd disk, but on Production project

**Comment by belforte** [comment]
I see. German organization had a glitch here. Make sure Christoph^2 know :-)

**Comment by belforte** [comment]
replace "contact an operator" (meaningless to users) with
"contact support" (we write everywhere we can that to get
help and support you write to hn-cms-computingTools@cern.ch)

**Comment by mmascher** [comment]
Ok, will do. Should we complain on compOps about not being able to reboot the schedd? I think the original sin is that the machine is on the wrong group (Production vs Analysis)

In the second case Justas/Jadir would have been able to reboot it..

**Comment by belforte** [comment]
a kind message to compOps will do. Like...
"please.. is there anybody there whom I did not talk to already who can
reboot a production schedd while Ivan is away ?"

**Comment by juztas** [comment]
I created snow ticket, but I can't escalate ticket to IT directly and it hope it will be rebooted tomorrow

**Comment by belforte** [comment]
thanks Justas ! reboot tomorrow is fine IMHO.

**Comment by mmascher** [comment]
On Tue, Jul 21, 2015 at 10:22 PM, Stefano Belforte <notifications@github.com
> wrote:

> Basically, I do not understand why people should resubmit the task, even
> today.
> If vocms066 comes back up tomorrow morning, it will do all needed
> resubmission. Or was it retired ?
>

Yes, if the schedd comes back tomorrow jobs will restart, but I feel like
if a schedd is down for more than 24hours we should suggest people to
resubmit.. So everything that cannot be solved before going to bed means
we  remove the schedd from the "crab schedd submission list" and we go to
bed knowing that people will be told to resubmit :)

Also things like a broken HD fall into this category

**Comment by belforte** [comment]
Marco, all I am saying is to have that discussion case by case,
in front of the actual issue, and do not hardwire the outcome in the code.
I am not arguing now what would be the optimal action tonight.
By the way CrabServer can't tell if HD was broken !

**Comment by mmascher** [comment]
That's why the "submit a new task" message is triggered by an operator. He has to remove the schedd from the external configuration.

Anyway, I see you don't like the idea and it's less code to write for me, so I should stop arguing :)

I will modify the error message to point to computing-tools.

**Comment by mmascher** [comment]
Message fixed, I'll merge it if there are no objections
