### ISSUE TITLE
job stdout prints wrong thing for Destination site

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4880]
looking e.g. at this
http://vocms096.cern.ch/mon/cms846/150721_190908:vmariani_crab_2b_runDtest/job_out.5.0.txt
(which will not stick around forever, of course)

I spotted the following [*]. Either the wrong value or the wrong name is used for "Destination site".

[*]
======== HTCONDOR JOB SUMMARY at Wed Jul 22 07:43:34 GMT 2015 START ========
CRAB ID: 5
Execution site: T2_IT_Pisa
Current hostname: se1wn18
Destination site: /store/temp/user/vmariani.1a6f52368cfff53ec63cb7bf18f84508111f73f9/MinimumBias/crab_2b_runDtest/150721_190908
Output files: TwoBody_DATAprova.root=TwoBody_DATAprova_5.root

**Comment by mmascher** [comment]
This message comes from here https://github.com/dmwm/CRABServer/blob/3.3.1509.rc5/scripts/gWMS-CMSRunAnalysis.sh#L42-L47 and https://github.com/dmwm/CRABServer/blob/3.3.1509.rc5/scripts/gWMS-CMSRunAnalysis.sh#L65

Honestly I vote for completely removing the message, we print the whole jobad in case we need to know the value of this parameter.. Is it ok for you @belforte ?

**Comment by belforte** [comment]
+1
if we want to search classAds for something, expecially custom Ads, we need an ad hoc method that is
documented and kept up to date, scattering strings here and there which at some
time maybe matched a classAd that was introduced and then removed... brr...

On 08/12/2015 04:50 PM, Marco Mascheroni wrote:
> This message comes from here
> https://github.com/dmwm/CRABServer/blob/3.3.1509.rc5/scripts/gWMS-CMSRunAnalysis.sh#L42-L47 and
> https://github.com/dmwm/CRABServer/blob/3.3.1509.rc5/scripts/gWMS-CMSRunAnalysis.sh#L65
>
> Honestly I vote for completely removing the message, we print the whole jobad in case we need to
> know the value of this parameter.. Is it ok for you @belforte <https://github.com/belforte> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4880#issuecomment-130328866>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by AndresTanasijczuk** [comment]
So far, in https://github.com/dmwm/CRABServer/pull/4977 I have changed "Destination site" to "Destination temp dir".

**Comment by AndresTanasijczuk** [comment]
I would like to close this issue. As I pointed out above, now it should print "Destination temp dir". Do you want me to remove this message completely? Or @mmascher you can do it directly on github :-)

**Comment by belforte** [comment]
I think it was Open waiting for the change to be merged and deployed. It it is, close.

**Comment by mmascher** [comment]
Let's keep the messages and close this
