### ISSUE TITLE
Do not query phedex and take stageout site from site-local-config.xml

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4895]
It requires WMCore patch. This will need to be adjusted: https://github.com/dmwm/CRABServer/pull/4894
```
import WMCore.Storage.SiteLocalConfig as SiteLocalConfig>>> 
import os
os.environ['CMS_PATH'] = '/cvmfs/cms.cern.ch'
os.environ['WMAGENT_SITE_CONFIG_OVERRIDE'] ='/cvmfs/cms.cern.ch/SITECONF/T1_IT_CNAF/JobConfig/site-local-config.xml'
slc = SiteLocalConfig.loadSiteLocalConfig()
dir(slc)
['__doc__', '__init__', '__module__', 'eventData', 'fallbackStageOut', 'frontierProxies', 'frontierServers', 'localStageOut', 'localStageOutCommand', 'localStageOutOption', 'localStageOutSEName', 'read', 'siteConfigFile', 'siteName', 'trivialFileCatalog']
slc.localStageOut
{'catalog': 'trivialcatalog_file:/opt/exp_software/cms/SITECONF/local/PhEDEx/storage.xml?protocol=srmv2', 'command': 'srmv2-lcg', 'option': '-v ', 'se-name': 'storm-fe-cms.cr.cnaf.infn.it'}
```

**Comment by mmascher** [comment]
I think this could be instructive for either @emaszs or @jmarra13 . Let me know when/if you want to work on that guys. Low priority.

**Comment by belforte** [comment]
I am not sure this is a good idea. What exactly is the problem ? Which stageout is this, local or 
remote ? And is this being done on Server or on WN ?

**Comment by mmascher** [comment]
On the worker node. We need to change the way we figure out the Phedex Node Name (PNN) for the local stageout, which is then used by ASO to build the input pfn for the file it needs to transfer.

Right now we are taking the storage element (SE) name from the SiteLocalConfig and converting it to the PNN querying phedex using the nodes API (https://cmsweb.cern.ch/phedex/datasvc/xml/prod/nodes). Last year at some point sites were required to directly put in their SiteLocalConfig the PNN, this was in the context of the PNNS/PSN consolidation.

**Comment by belforte** [comment]
OK. Long overdue :-)

**Comment by mmascher** [comment]
Some comments for Emuilis:

* This must only be used as a fallback. https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L433-L448 . By default we need to use the value we find in the SiteLocalconfig (comments are welcome!!)
* WMCore.Storage.SiteLocalConfig needs to be modified because now it can't give you the phedex node name
* I propose to add the phedex node here together with the executed-site https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L381 and then read it in cmscp

**Comment by mmascher** [comment]
About the othe github issue, also this if will be modified https://github.com/juztas/CRABServer/commit/abc75834961ba86cca95f888321e7778ffe0f431#diff-cfe3289eafba17ae56955db45d4b3cf9R1171
