### ISSUE TITLE
Should crab status not show COMPLETED if publication was not finished?

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4898]

**Comment by belforte** [comment]
the way to answer is to list all possible current values of status for a TASK
Then I suspect the question is rather: should other statuses be added to track
post-job activities ?

**Comment by AndresTanasijczuk** [comment]
Publication has nothing to do with post-job, but that simply would mean to reformulate your question to: should other statuses be added to track post-job and/or ASO-publication activities?

**Comment by PerilousApricot** [comment]
If a user asks to have an output published, and publication fails, should
you tell them everything was OK, or should you report back the failure?

**Comment by belforte** [comment]
sorry, I thought post-job waits for ASO to be done, including publication, is it not so ?
does it wait for xfer only ?

**Comment by belforte** [comment]
clearly we MUST report this Andrew, this is only about where exatly
track is lost and how to fix it in most clean way, no question about
the "have to do it"

**Comment by AndresTanasijczuk** [comment]
Stefano, post-job is not tracking publication status, only transfer status.

**Comment by PerilousApricot** [comment]
That's super bad! Unless you want everyone to disbelieve DBS, you have to
make publication a first class citizen.

**Comment by belforte** [comment]
+1

**Comment by AndresTanasijczuk** [comment]
Publication is done in blocks of 100 files, and we allow only 20 post-jobs running in parallel. That's why I think post-jobs are not monitoring publication status. However, with the new feature of post-jobs deferral, monitoring publication status in post-job would be possible I think.

**Comment by belforte** [comment]
we also have DAG_FINAL node.
and already each post-job updates ASO status for all jobs.
But again.. this is implementation, there must be design first,
then one look into how to do it, possibly changing things.


On 07/29/2015 11:06 AM, Andres Tanasijczuk wrote:
> Publication is done in blocks of 100 files, and we allow only 20 post-jobs running in parallel.
> That's why I think post-jobs are not monitoring publication status. However, with the new feature of
> post-jobs deferral, monitoring publication status in post-job would be possible I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4898#issuecomment-125886810>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by AndresTanasijczuk** [comment]
You are right; I take back what I said.

**Comment by belforte** [comment]
I guess we have to decide first if to move publication to task process, that will make this easy
