### ISSUE TITLE
job kill is not proprely reported to dashboard

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4900]
*** Discussion title: CRAB Development

Dear all,

Triggered by the mail of  Kenyi see below,
I investigated the issue and found out that we have a serious bug in 
reporting for killed jobs.
The problem is the following:
- the report for killed jobs does not contain 
the correct task name and contains 'unknown' instead.
- the jobid reported with killed job status is not consistent with the 
name of the job elsewhere (from the server, or from the wn).

Below is the example of the report.
The first field is the time stamp when dashboard got a report, the second 
field is the name of the task, the third one is the job 
identifier with an attached IP address and further you have the name of 
the attribute and its' value.
The correct task name should be 
150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703

And the job identifier in this buggy report
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0

essentially looks correct to me, but is inconsistent with other reports, 
where the job identifier has in many places ':' instead of '_'

1_https://glidein.cern.ch/1/150726:152733:sciaba:HC-95-T2:US:Purdue-17506-20150726024703_0

As a result, for Dashboard these are two different sets of jobs mapped to 
different tasks and different meta attributes.
Jobs which were killed are not updated to state 'Cancelled' in Dashboard. 
And we duplicate job records and get wrong statistics for all cancelled jobs.

The fact that the cancelled jobs were mapped to the Notre Dame site and 
were mapped to wmagent and reprocesisng jobs, was a bug on the Dashboard 
side which is corrected now. This was due to the fact that the task with 
the name 'unknown' got a wrong set of meta attributes in Dashboard.
This  was not visible so far, since we should not get 'unknown' task, the 
task should be always properly resolved.

Could you, please, look into it.

Let me know when you want me to test anything.

Thank you

CHeers
Julia

17:58:27        unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
NodeName        java.lang.String:128.142.200.184

17:58:27        unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
bossId  java.lang.String:1

17:58:27        unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
sid 
java.lang.String:https://glidein.cern.ch/1150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703

17:58:27        unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
StatusValue     java.lang.String:killed

17:58:27        unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
broker  java.lang.String:vocms052.cern.ch

17:58:27         unknown 
1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0_128.142.200.184 
jobId 
java.lang.String:1_https://glidein.cern.ch/1/150726_152733:sciaba_HC-95-T2_US_Purdue-17506-20150726024703_0

---------- Forwarded message ----------
Date: Tue, 28 Jul 2015 14:15:41 +0200
From: Julia Andreeva <Julia.Andreeva@cern.ch>
To: Julia Andreeva <Julia.Andreeva@cern.ch>
Subject: FW: Dashboard bug affecting Notre Dame?

________________________________________________________________________________________________________________________________________________________________________
From: Kenyi Paolo HurtadoAnampa [khurtado@nd.edu]
Sent: 17 July 2015 20:42
To: Julia Andreeva
Cc: Kevin Patrick Lannon
Subject: Dashboard bug affecting Notre Dame?

Hi Julia,

There is something strange that has been happening for months and we just recently noticed here at Notre Dame with respect to the dashboard.
We are seeing thousands of jobs with almost the same id being reported to our T3 and to some other resource. These jobs are reported at about the same time and the
submission tool information is different.

For example:
- SchedulerJobId = A:B:C_0 shows it was a CRAB job running at e.g some Tier2.
- SchedulerJobId = A_B_C_0 shows it was a "wmagent" job that entered our T3 and then was immediately killed.
The first case has a valid unique TaskMonitorId linked, while the second case is always linked to the same TaskMonitorId="Unknown".

There is no evidence such jobs actually reach our batch scheduler, which makes me thing this might be a bug in either CRAB or the dashboard itself.

Do you have an idea of what could be making this happen?

More details are below:
---------------------------------

You can see such jobs here:
http://dashb-cms-jobsmry.cern.ch/dashboard/request.py/dailysummary#button=jobstatus&sites[]=T3_US_NotreDame&sitesSort=3&start=2015-01-01&end=2015-07-15&timerange=daily
&granularity=Daily&generic=0&sortby=5&series=All&submissions[]=wmagent

As I wrote before, we haven't found evidence in our condor logfiles that those jobs actually reach our condor batch scheduler.
The interactive view shows the taskMonitorId for all of them are "unknown", as I mentioned before:

http://dashb-cms-job.cern.ch/dashboard/templates/web-job2/#user=&refresh=0&table=JobDetailedView&p=1&records=25&activemenu=0&usr=&site=T3_US_NotreDame&submissiontool=w
magent&application=&activity=reprocessing&status=cancelled&check=submitted&tier=&date1=2015-07-14+15%3A52&date2=2015-07-15+15%3A52&sortby=subtoolver&scale=linear&bars=
20&ce=&rb=&grid=&jobtype=&submissionui=&dataset=&submissiontype=&task=&subtoolver=1.0.0.pre3&genactivity=&outputse=&appexitcode=&offset=0&count=1498&exitcode=&fail=&ca
t=

Here is a real example:

If you pick one "wmagent" job reported as killed at Notre Dame from the interactive view table:

http://dashb-cms-job.cern.ch/dashboard/request.py/detailView?schedulerJobId=https://glidein.cern.ch/1/150714_154826:nfalterm_crab_DATA_edm_2_0

And you replace all but the last "_" to ":" in the ID:
http://dashb-cms-job.cern.ch/dashboard/request.py/detailView?schedulerJobId=https://glidein.cern.ch/1/150714:154826:nfalterm:crab:DATA:edm:2_0

Then you see it's a CRAB job that ran at CIT_CMS_T2 and the worker node is not unknown, as in the first case.

Here is another example from a different user:
http://dashb-cms-job.cern.ch/dashboard/request.py/detailView?schedulerJobId=https://glidein.cern.ch/1/150714_153056:sciaba_HC-98-T2_CH_CSCS-17053-20150713162502_0

http://dashb-cms-job.cern.ch/dashboard/request.py/detailView?schedulerJobId=https://glidein.cern.ch/1/150714:153056:sciaba:HC-98-T2:CH:CSCS-17053-20150713162502_0

And as you can see, even when the jobs are from different users, they all link to this "unknown" taskId that has "wmagent" as submission tool and ndcms as the
SubmissionUI in it:

http://dashb-cms-job.cern.ch/dashboard/request.py/detailTaskView?taskMonitorId=unknown

I have randomly picked a few other JobIds from the interactive table and it's always the same.

Could this be a Dashboard bug? Or maybe a CRAB bug?

Thanks in advance!

Best Regards,
â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"
Â  Â  Â  Â  Â Kenyi Hurtado Anampa
Â  Â  Â 405 Nieuwland Science Hall
Â  Â  Â  Â University of Notre Dame
Â  Â  Â  Â  Â  Â  Â (574) 631-7311
â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"â?"

-------------------------------------------------------------
Visit this CMS message (to reply or unsubscribe) at: 
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2404.html

**Comment by juztas** [comment]
Solved. We can close this one. Opened new one to make report from one place https://github.com/dmwm/CRABServer/issues/4903
