### ISSUE TITLE
Make dashboard report from one place

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4903]
See comment here: https://github.com/dmwm/CRABServer/pull/4901#issuecomment-126324272

**Comment by emaszs** [comment]
Discussion with Marco:

The first step would be to remove code duplication from DagmanKiller.py (https://github.com/juztas/CRABServer/blob/95ddcd43ecfcc1049c5c4ae463bface48bff952b/src/python/TaskWorker/Actions/DagmanKiller.py#L82-L83 ,
https://github.com/juztas/CRABServer/blob/95ddcd43ecfcc1049c5c4ae463bface48bff952b/src/python/TaskWorker/Actions/DagmanKiller.py#L149-L150). Later other present duplications would be corrected.

This could be done by creating a ServerUtilities.py function which takes an arbitrary dictionary as well as some parameters and updates the dictionary by inserting the computed jobId and sid values.

**Comment by emaszs** [comment]
@mmascher, I made a ServerUtilities function and removed code duplication from 4 places. I don't see "jobId" and "sid" being used anywhere else. Does this look good? By the way, latest commit contains all of the changes.
