### ISSUE TITLE
do not use /store/temp/group for temporary output

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4907]
as Brian (never-be-praised-enough) Bockelman pointed out, 
only the first user which create a directory  in /store/temp/group/<groupname> will be able to keep writing there. And we can't pre-create all possible group directories with world-write protection.

Need to put all temporary files created on local SE for user U under /store/temp/user/U
something as stupid as
/store/temp/user/U/group/blah... could e.g. do

**Comment by PerilousApricot** [comment]
How is this a problem for /store/temp/group and not /store/group? Won't the
same issue be tripped?

**Comment by bbockelm** [comment]
We assume that the group has arranged a special setup at the destination site to handle permissions (CERN EOS ties everything into e-groups, I think).

However, we can't assume the users have an arrangement with every site in CMS.

**Comment by belforte** [comment]
So far the site needs to create /store/group/blah first.  Not every site hosts all group spaces. Hope is to implement store/results with everything owned by production. 
On Jul 31, 2015 18:49, Andrew Melo <notifications@github.com> wrote:How is this a problem for /store/temp/group and not /store/group? Won't the
same issue be tripped?

**Comment by belforte** [comment]
@AndresTanasijczuk did you forget to make a PR for this, or do you think your commit is not complete

**Comment by AndresTanasijczuk** [comment]
@belforte I made the pull request https://github.com/dmwm/CRABServer/pull/4977 but we need to be 100% ASO is ready for this change. When I made the pull I thought ASO was not ready, but I was wrong on the reason why I thought that. Now I think ASO is indeed ready for this change, but would like to have a confirmation from @HassenRiahi

**Comment by belforte** [comment]
can we test ASO for this ?

**Comment by HassenRiahi** [comment]
> Now I think ASO is indeed ready for this change

Yes, it should work but of course some testing are needed.

**Comment by AndresTanasijczuk** [comment]
We can test it, but what /store/group/ destination lfn and site should we use?

**Comment by belforte** [comment]
the important thing is to make sure that the problem with local stage out is
solved, i.e. try a group where local stage out would fail otherwise
so destination should be:  /store/group/phys_higgs

and make sure jobs run at T2_US_Nebraska

I will be happy enough to see ASO trying to xfer to any final T2 and
fail due to lack of permission. But just for fun you can try with a T2
which does not have a history of being careful about user permission
e.g. T2_IT_Pisa.

**Comment by PerilousApricot** [comment]
I believe I have it set so the crab3 devs can write anywhere @ T2_US_Vanderbilt (shhh, it's a secret)

**Comment by AndresTanasijczuk** [comment]
Test was successful using ASO 1.0.3pre14 from test-bed: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Andres+Jorge+Tanasijczuk&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150921_184043%3Aatanasi_crab_test_store_group_Vanderbilt_store_temp_user_Nebraska_2

Execution site: T2_US_Nebraska
Stageout destination site: T2_US_Vanderbilt
Stageout output directory: /store/group/phys_higgs/trash/. 
Local stageout was made to /store/temp/user/atanasi.\<hash\>/phys_higgs/trash/ in T2_US_Nebraska.
I can see the files in srm://se1.accre.vanderbilt.edu:6288/srm/v2/server?SFN=/lio/lfs/cms/store/group/phys_higgs/trash/SingleMu/test_store_group_Vanderbilt_store_temp_user_Nebraska_2/150921_184043/0000/[log/] and I was able to retrieve the logs and outputs from Vanderbilt with `crab getlog` and `crab getoutput`.
Outputs were published: https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=dataset%3D%2FSingleMu%2Fatanasi-test_store_group_Vanderbilt_store_temp_user_Nebraska_2-f765a0f4fbf582146a505cfe3fd08f3e%2FUSER (I had to change in the ASO config the `DBSPublisher.cache_area` parameter for a while to point to my private CRAB server VM)

I am doing now the same test with production ASO.

**Comment by AndresTanasijczuk** [comment]
Direct stageout works as well.
