### ISSUE TITLE
format error in dryrun

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4913]
Task status: UPLOADED

Creating temporary directory for local test run (needed for timing
estimates) in /tmp/tmpvc1aZ4
Executing test, please wait...
Using LumiBased splitting
ERROR: TypeError: %d format: a number is required, not float

see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/818.html

**Comment by matz-e** [comment]
Seems due to old-style formatting.  Any objections to use `str.format()` instead?

**Comment by matz-e** [comment]
Actually, I don't see how there's anything but a `int` possible at that location. I think this is the offending line:
```
self.logger.info("Task consists of %i jobs to process %s" % (splitting['total_jobs'], quantities['total']))
```
where `splitting['total_jobs']` is set [here](https://github.com/dmwm/CRABServer/blob/55aceed724f55104c76ad4ad8f873ab1057117f3/src/python/TaskWorker/Actions/DryRunUploader.py#L101):
```
 'total_jobs': len(self.lumisPerJob),
```
Unless there's a newer report of this, with a reproducible config, I think this could be closed.

**Comment by belforte** [comment]
OK. Let's close as UNREPRODUCIBLE.
