### ISSUE TITLE
Add execution hostname to crab3 FrameworkJobReport-*.xml

### ISSUE THREAD

**Issue by indianajam** [dmwm/CRABServer#4916]
Hi,

I have a request for next crab3 releases: adding the execution hostname in FrameworkJobReport-*.xml.
Note that it is already available in the job log pointed from the dashboard: should not be hard adding it to the fjr.
It would have been a lot useful in the tests made by Bologna over Cloud infrastructures: getting all needed info from fjs instead of doing crazy merge with the job log.
In general I consider the info very useful also for debug purposes.

Cheers,

Giuseppe

**Comment by PerilousApricot** [comment]
If it's not in the FJR, you'll need to get the CMSSW guys to put it in there, it comes straight from cmsRun.

**Comment by ericvaandering** [comment]
Yes, as Andrew says, that XML is not created by CRAB, but by cmsRun.

**Comment by belforte** [comment]
@indianajam Giuseppe, where exactly do you want to look ? Directly in cmsRun output (see notes from Andrew and Eric) or in the FJR returned by CRAB ? (same name is used for two slightly different files, alas).

**Comment by indianajam** [comment]
@belforte: I was exactly talking of the FJR returned by CRAB (actually put in the tgz in the storage).
Parsing an xml is way easier and safer than parsing a free text output.

**Comment by PerilousApricot** [comment]
Unfortunately that's the one that comes from CMSSW :)

-- 
Sent from Gmail Mobile

**Comment by juztas** [comment]
@indianajam for this case you can save additional output files (even if they created not by you). HTCondor send job_ads file, which has a hostname defined. So if you have this file, you can use python bindings or simple `$ cat .job_9.ad | grep 'RemoteHost'`. To get this files stored in your final destination, you have to use `config.JobType.outputFiles = ['.job.ad']`

**Comment by indianajam** [comment]
@juztas thanks, this is a good step ahead :-) My aim was to have everything in a single file, but like this st least I have all the files in a single place.

Giuseppe

**Comment by belforte** [comment]
@indianajam I suspect that's still the cmsRun FJR. The one manipulaed by 
the crab job wrapper is JSON. And available w/o need to untar.
Can you be _very_ specific, please ?


That said I think Giuseppe has a good point that the wrapper FJR could
be a real summary of all useful info, in the hope that full stdout is
almost never needed. But then I would not simply add hostname, but
also site, timestamps, CMSSW version, etc.. in any case it falls in
the 'frosting' category, let's cook the cake first.

**Comment by indianajam** [comment]
dear @belforte: you got the point :-)
Whatever is the format (json, xml, frameework report or crab report) having all relevant info in a single place may help a lot.
To be clear, I'm almost sure I was talking about cmsRun FJR, e.g. the one I find hrere for instance:

srm://sebo-t3-01.cr.cnaf.infn.it:8444/srm/managerv2?SFN=/cms/store/user/gcodispo/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/crab_CLOUD_TESTS_crab3_openstack_juno/150804_073918/0000/log/cmsRun_10.log.tar.gz

I was not using the json report instead in the last tests.

**Comment by belforte** [comment]
Giuseppe, but this is via Crab3, right ? So why bother to look in the SE ?
what's wrong with this  (random example) :
http://vocms059.cern.ch/mon/cms293/150731_154344:atanasi_crab_test_report_on_doublelumis_input_dataset_2/job_fjr.1.0.json

that URL requires ssh tunnel from outside CERN currently, but
very shortly it will be replaced with a cmsweb.cern.ch one with
worldwide access for CMS'ers.

What is the use case here ? Look for errors by hostname ?
Dashboard has that already.

**Comment by indianajam** [comment]
Yes, crab3.
Nothing wrong with the json: when I started working was faster for me playing with th xml, now I may have the time to converto to json :-) I will be even happier when the cmsweb acces will be enabled.

About the use cases: in my case, I was trying to distinguish among jobs running on standard Bologna T3 nodes and the ones running over dinamycally addes nodes. It was an "offline" metric study. 
I would have found it useful also in the past months, debugging some CMS analysis jobs from random users: being able to easili collect the vn lists where the jobs run to figure out if it the problem was localized in a single wn or generalized.

**Comment by belforte** [comment]
I see that dashboard task monitor page does not show the WN anymore.
Let's wait for the final version of that page (some changes we requested 
have not been done yet). Then we may think whether to ask for it to be 
added, I used to find it useful.
