### ISSUE TITLE
remove jobs after IDLE for a week

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4920]
modify PeriodicRemove expression in DagmanCreator to remove jobs which have been idle for a week
(as discussed at CRAB3 dev.meeting today)

**Comment by belforte** [comment]
Jadir agreed to do it, btw

**Comment by mmascher** [comment]
That's what we need to modify https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L141-L154

Plus the retry job so to report the correct remove reason to the client: we need to add something similar to [1], e.g. a `check_expired_jobs`

[1]
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L240-L247

**Comment by belforte** [comment]
I agree that current RetryJob needs modifying as well. But I do not like that solution.
Why do we need to have specific code for each possible condition, rather then list
all condition that lead to one behavior ?

I do not see why removed jobs need anything other then being marked as FatalError,
why should one resubmit automatically removed jobs ?
and am puzzled by current code like:
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L395-L397
which expects check_empty_report to rise either Recoverable or Fatal but that method only
rises Recoverable
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L343-L348

maybe I am simply having a hard time understanding that FatalError corresponds to
return JOB_RETURN_CODES.OK

maybe I simply do not understand (and surely do no like) use of exceptions to simply
pick one of two possibly legal conclusion for the code. I would expect resubmit_me or
not_resubmit_me to be communicated via return arguments, not via "raise".
Try/Except should be used around statements that usually succeed but in special
cases may fail, not as a replacement for if/then/else.

Maybe I am too old ? Surely this code is more difficult to read then it could.
Is this because it is "very pythonic" rather then "C-like" ?

I am confused by things like
try:
except:
  print "blah"
  raise
raise

sounds like no matter what happen, you always raise,
how can these lined be executed ?
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L410-L413

OK. If all of that simply means I can't read this code, do not bother to reply in here,
if it ever comes that I need to contribute to Crab3 code someone will have to sit
with me for 10 min and teach :-)

**Comment by mmascher** [comment]
Hi,

On Wed, Aug 5, 2015 at 11:36 AM, Stefano Belforte <notifications@github.com>
wrote:

> I agree that current RetryJob needs modifying as well. But I do not like
> that solution.
> Why do we need to have specific code for each possible condition, rather
> then list
> all condition that lead to one behavior ?
>

Maybe we can refactor RetryJob a little bit, but for memory and cpu removal
we do custom actions.


>
> I do not see why removed jobs need anything other then being marked as
> FatalError,
> why should one resubmit automatically removed jobs ?
> and am puzzled by current code like:
>
> https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L395-L397
> which expects check_empty_report to rise either Recoverable or Fatal but
> that method only
> rises Recoverable
>
> https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L343-L348


that comment refers to exit_code



>
>
> maybe I am simply having a hard time understanding that FatalError
> corresponds to
> return JOB_RETURN_CODES.OK
>

you mean JOB_RETURN_CODES.FATAL_ERROR ?


>
> maybe I simply do not understand (and surely do no like) use of exceptions
> to simply
> pick one of two possibly legal conclusion for the code. I would expect
> resubmit_me or
> not_resubmit_me to be communicated via return arguments, not via "raise".
> Try/Except should be used around statements that usually succeed but in
> special
> cases may fail, not as a replacement for if/then/else.
>
> Maybe I am too old ? Surely this code is more difficult to read then it
> could.
> Is this because it is "very pythonic" rather then "C-like" ?
>

> I am confused by things like
> try:
> except:
> print "blah"
> raise
> raise
>

This surely is really pythonic :)

But I agree that's not easy to read:
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L394-L408

You've got to know that check_exitcode raises fatal or recoverable errors,
and these are propagated by the raise here
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L408
unless these three
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L402-L404
raises fatal exception (true if the periodic remove kicked in)

All in all a good code commenting should do it instead of rewriting the
code, even though I have to admit it's a bit too pythonic now (aka messy :))

**Comment by belforte** [comment]
Maybe in some cases internal functions called in RetryJob.execute_internal
can raise FatalError which is not catched in execute_internal and
bubbles up to execute. I think I am slowly getting it, but... gee !

  Maybe as simple as: the code should list the exceptions it expects ?
  Or better something like://
  this method returns possible outcomes by throwing
  various exceptions, namely:....

Problem is that now one reads a piece of code, and can't
know what it does since some times things happens inside
the functions that are called which simply leak
upstream as exceptions, and not because of "incidents" but
as normal part of flow.
The fact that "function output" even when legal may not
be returned as a return value, makes harder to work
with code which does not obey to old tradition of having
a comment part which describes exactly the input and output.


I tried to read some stuff on the web on the line of
"you should use exceptions in python more freely than you think"
I guess my confusion can be summarised as
"is it proper to use exception to return some of the
possible outcomes of a function and a return value for the others ?"

a phrase I liked from internet:
     You shouldn't throw exceptions for things that happen all the time. Then they'd be "ordinaries".
I liked this also:
   http://www.joelonsoftware.com/items/2003/10/13.html

I understand exceptions carry almost no performance penalty in Python,
differently from C etc., but arguments there are not about performance,
but about how to have code which you can read and understand.

This execute function looks a bit schizophrenic to me
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L417-L435

**Comment by jmarra13** [comment]
addressed by #4946
