### ISSUE TITLE
check stage out location before submitting tasks

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4921]
before the first submission of a task to the schedd, the TW should check the stageout location.
We want to avoid submitting tasks if destination SE is down, or full, or permission is missing.
It is true that those could in theory be solved while the jobs are pending, but in practice we currently suffer more than we gain by hitting against those walls.
One mitigation could be to treat like schedd failure, i.e. try a few times with exponential backoff to avoid glitches in SE availability.

**Comment by bbockelm** [comment]
For what it's worth - we have discussed doing some variation of this many times over the past two years.  Each time we decided that there were too many other high priority tasks.

I believe we have enough high priority things taken care of to look into this.

**Comment by belforte** [comment]
yeah.. like I was against it for some time, then changed my mind :-)
also now we have a tested procedure to validate the stageout location
(crab checkwrite). Surely code should be shared, not replicated with the 
client. Do not want to parse same message differently in two places.

**Comment by juztas** [comment]
@belforte what do you mean by first submission? If I submit 10 tasks one after other, check for each task that it is able to do stageout?

**Comment by belforte** [comment]
I mean do not check when there is a resubmit. So, yes. I think tasks are processed independently, so you can not know that 100 more similar one are coming in next minute. hmmm ideally we could cache the writecheck result for O(1h), but I fear it is not worth the effort. While we like client to be done quickly, task submission is OK to take one minute.

**Comment by juztas** [comment]
It is implemented and in preprod already https://github.com/dmwm/CRABServer/pull/4944
