### ISSUE TITLE
PSet should not be mandatory when running scriptExe

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4922]
See https://github.com/dmwm/CRABClient/issues/4528#issuecomment-127640775 which is a summary of what was agreed on the 4th of August 2015 at the CRAB3 meeting

**Comment by mmascher** [comment]
https://github.com/dmwm/CRABServer/pull/4938 seems a prerequisite of this

**Comment by belforte** [comment]
all in all it is not too difficult to submit a dummy pset.
