### ISSUE TITLE
Checking tasks stuck in QUEUED state

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4926]
I was checking out of curiosity how many task got stuck in the QUEUED state in the past month, and since July 1st I see:

```
SQL> 	select count(*),TRUNC(tm_start_time) from tasks where tm_task_status='QUEUED' group by TRUNC(tm_start_time) ORDER BY TRUNC(tm_start_time);

  COUNT(*) TRUNC(TM_ST
---------- -----------
       118 01-JUL-2015
	 1 03-JUL-2015
	13 06-JUL-2015
       168 07-JUL-2015
	79 08-JUL-2015
	22 15-JUL-2015
	 2 16-JUL-2015
	17 17-JUL-2015
	 6 21-JUL-2015
	 1 23-JUL-2015
	 1 28-JUL-2015
	 4 29-JUL-2015
```

I tried to check one of the task stuck on the 19th:

```
SQL> select tm_taskname from tasks where TRUNC(tm_start_time)='29-JUL-2015' and tm_task_status='QUEUED';

TM_TASKNAME
--------------------------------------------------------------------------------
150729_220913:sciaba_HC-94-T2_RU_JINR-17635-20150729181102
[...]
```

but I could not find a reasonable explanation for that. For the moment I am just adding few instructions tu better understand what was happening.

I would like to implement what we discussed at some point at a crab3 meeting: to introduce a recurring action to check which tasks are in QUEUED for more than N hours, and if those tasks are not in the task worker queue mark them as FAILED with an appropriate reason.

**Comment by belforte** [comment]
good idea, but hopefully can stay at low priority for a while longer

**Comment by mmascher** [comment]
See https://github.com/dmwm/CRABServer/issues/4082

**Comment by belforte** [comment]
should be fixed when we recover QUEUED tasks in TM

**Comment by belforte** [comment]
now absorbed in #5076
