### ISSUE TITLE
crab kill not always send info to dashboard

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4930]
Here is the ggus ticket https://ggus.eu/index.php?mode=ticket_info&ticket_id=115381
So seem we have to do this in try: except and check if results are got. At this point what happened, results are empty list and there is 0 documents in transfer, so we are not sending kill to dashboard. We need to know crab job_id and retry_id if we want to send kill. 

Wrong line: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanKiller.py#L77

Or maybe we can send kill without job_id and retry_id? Need to ask Julia

**Comment by belforte** [comment]
solved since long
