### ISSUE TITLE
resubmit --blacklist site leads to undefined

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4933]
If task which is submitted has only one site in DESIRED_Sites and user resubmit with blacklisting that site, DESIRED_Sites will be undefined and jobs will not run (They will stay idle all the time)

**Comment by juztas** [comment]
DagmanResubmitter will execute condor_q through python bindings and will check if DESIRED_Sites - userBlacklist is not empty list. If it is empty, fail to resubmit and give proper error message

**Comment by belforte** [comment]
smells of a check down too late in the chain. why do we need to ask condor for parameters that we 
tell it to begin with ?

**Comment by belforte** [comment]
solved since long

**Comment by juztas** [comment]
not solved. See [1] and 450 jobs, and also you can check with this command: `condor_q -const 'CRAB_ReqName isnt null && TaskType =!= "ROOT" && DESIRED_Sites =?= ""' -g `
```
[1]
$ condor_q -const 'CRAB_ReqName isnt null && TaskType =!= "ROOT"' -g -af DESIRED_Sites | sort | uniq -c
    450 
    112 T1_DE_KIT
      2 T1_DE_KIT,T2_CH_CERN
     44 T1_DE_KIT,T2_CH_CERN,T2_FR_IPHC
      1 T1_DE_KIT,T2_DE_DESY,T2_CH_CERN
      8 T1_DE_KIT,T2_FR_IPHC,T2_US_Wisconsin,T2_IT_Legnaro,T2_BE_IIHE,T2_CH_CERN
    123 T1_DE_KIT,T2_UK_London_IC,T2_DE_DESY,T2_CH_CERN
      1 T1_DE_KIT,T2_US_UCSD,T2_FR_IPHC,T2_US_Wisconsin,T2_US_Florida,T2_IT_Legnaro,T2_CH_CERN
    683 T1_DE_KIT,T2_US_Wisconsin,T2_CH_CERN
    305 T1_ES_PIC
      4 T1_ES_PIC,T2_CH_CERN,T2_FR_IPHC
```

**Comment by belforte** [comment]
the same happens if user resubmits putting in white list a site which does not have the input dataset.
DESIRED_Sites will be undefined and jobs will not run (They will stay idle all the time).
See:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2829.html

**Comment by belforte** [comment]
And it is particularly nasty if in the end the user select a site which generally has the dataset, but simply was missing for a few of the original jobs, like dataset copy was not full at some sites). See:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3008/1/1/1/2/2.html

**Comment by belforte** [comment]
looks like the site list is defined in here. We could fail if there's nothing left:
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PreJob.py#L447

**Comment by belforte** [comment]
I have a fix to PreJob to skip grid submission, so at least we do not have idle-forever jobs.
The trick now is to properly catch it in the postJob, currently such jobs have exit code -1 and message is like:
```
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/LOCAL/crab_20170704_173625
Task name:			170704_153631:belforte_crab_20170704_173625
Grid scheduler:			crab3-5@vocms059.cern.ch
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb.cern.ch/crabserver/ui/task/170704_153631%3Abelforte_crab_20170704_173625
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=belforte&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=170704_153631%3Abelforte_crab_20170704_173625
Status on the scheduler:	FAILED

Jobs status:                    failed        100.0% (5/5)

No publication information available yet

Error Summary:

4 jobs failed with exit code 50664:

	4 jobs failed with following error message: (for example, job 2)

		Not retrying job due to wall clock limit (job automatically killed on the worker node)

1 jobs failed with exit code -1:

	1 jobs failed with following error message: (for example, job 1)

		The framework job report could be loaded, but no error message was found there.

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.

Extended Job Status Table:

 Job State        Most Recent Site        Runtime   Mem (MB)      CPU %    Retries   Restarts      Waste       Exit Code
   1 failed       T2_ES_CIEMAT            0:05:09         26          1          0          0    0:00:09              -1
   2 failed       T3_UK_London_RHUL       0:05:11         26          3          0          0    0:00:10           50664
   3 failed       T2_CH_CERN              0:05:09         15         18          0          0    0:00:08           50664
   4 failed       T2_ES_CIEMAT            0:05:10         28          1          0          0    0:00:10           50664
   5 failed       T2_CH_CERN              0:05:10         18         22          0          0    0:00:09           50664

Summary:
 * Memory: 26MB min, 28MB max, 23MB ave
 * Runtime: 0:05:09 min, 0:05:11 max, 0:05:09 ave
 * CPU eff: 1% min, 22% max, 9% ave
 * Waste: 0:00:46 (3% of total)
```
while dashbaord only reports the first failed submission. But this perfecting of the message can wait

**Comment by belforte** [comment]
will open another issue about improving the PostJob to better catch this, which is not trivial

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/5537
