### ISSUE TITLE
Improve the way we set up the publishname parameter

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4947]
Currently in the client [1] we set `publisname` to `<Data.publishDataName>-<isbchecksum>` if the user defines Data.publishDataName, and `publishname = <isbchecksum>` otherwise.

In the server then [2] we add the task name (the project directory name, which is called workflow) so that we end up with a "consistent" name (`<Data.publishDataName>-<isbchecksum>` or `projectdir-<isbchecksum>`)

This `isbchecksum` is only used as a placeholder and is replaced by the real pset hash which can only be calculated in the worker node[3]. The replacement is done here in the postjob [4].

The architectural reason (if any) for using this placeholder is kind of lost in the past, but @AndresTanasijczuk mentioned this is useful because in case of errors you put outputs in a different dataset (he said he saw this for Andrew Melo workflow).

However this placeholder does not need to be a checksum, and imho it would be better to be a string like `00000000...` if not a string like `IwillBeReplacedWithThePSetHashOfedmProvDump`

Also it should be set in the server and the client should just set `publisname` to `<Data.publishDataName>` or `None`

[1] https://github.com/dmwm/CRABClient/blob/0005abc9c096be26b0188106799439e8e28b70dc/src/python/CRABClient/Commands/submit.py#L119-L122
[2] https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/DataWorkflow.py#L239
[3] https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L711
[4] https://github.com/dmwm/CRABServer/blob/3.3.1509.rc5/src/python/TaskWorker/Actions/PostJob.py#L1709

**Comment by belforte** [comment]
Could we review the reason why the HashOfEdm has to be computed on the WN ?
I know the technical answer, that full provenance info includes also some values set in the code, not in the pset, so can only be known run time. But .... what EXACTLY we use this hash for ? Does it REALLY need to be so accurate ? Does the benefit outweight the pain of using a placeholder etc. ?

IIRC, the rational for the hash was to avoid that user by mistake change the pset and mix in the same dataset output computed with different settings, when running multiple crab tasks with same publishname. BUT to begin with, we do not make any check that the shared libraries in the tarball are the same as in a previous task with same pset !

**Comment by mmascher** [comment]
This hash is put in DBS. Not sure then what it is used for, and what would change if we used another hash we calculate in the client. Who should we ask?

**Comment by belforte** [comment]
we have to ask ourselves. It would be worth to ask CompOps how they use it for Production.

**Comment by mmascher** [comment]
If it was for me I would use a unique hash for everything calculated from the sandbox content (to include libraries). I'll ask @ericvaandering what the pset hash is used for once it is put in DBS.

But let's start with baby steps.

What I don't like here and what I am proposing to fix is that in the client we are calculating two different hashes from the sandbox (one MD5 and one SHA256). One is rightfully used for the sandbox (and stored in the DB). The other one is put in the publishname as a placeholder. I would like to start eliminating this duplication in the client and setting the placeholder in the server (we can even use a hash of the taskname if we don't like to put `00000..`, it will not make any difference)

It's a small improvement that will avoid an headache to the people that will look at the client code in the next 5 years :)

Then we can do other baby steps toward a reviewed solution that uses the hash from the client and not from the WN if possible.

**Comment by belforte** [comment]
+1
fine with 00000 or, if we stay hex, the good old "deadbeef" which clearly points to a dummy value :-)
