### ISSUE TITLE
CRAB doesn't resubmit jobs for which post-job got SIGKILL

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4960]
In https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/866.html the user had 1 job (job number 59) that was failed and she wanted to resubmit it, but CRAB would not resubmit because in the RunJobs.dag.nodes.log file the last post-job event logged for Job59 was something like:
```
Abnormal termination (signal 9)
``` 
instead of the typical and expected
```
Normal termination (return value 2)
```
In AdjustSites.py we search for events like the second one for the jobs that were asked to be resubmitted and change these events to
```
Normal termination (return value 1)
```
so that DAGMan would resubmit these jobs.
Should we extend to also search for the first kind of events?

**Comment by belforte** [comment]
I hope sigkill of DAG is rare enough that we better treat as special exception : stop,  fail and investigate. Not hide. 
Sent from Stefano's mobile

**Comment by belforte** [comment]
rare enough that a recovery task should take care
