### ISSUE TITLE
Make sure we don't write to two different datasets if edmProvDump fails

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4964]
After this: https://github.com/dmwm/CRABServer/issues/4947 , and what we discussed yesterday at the meeting, we now need to make sure we do not write to the "placeholder" dataset when the pset hash is computed (see https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L555-L565)

First check if `edmProvDump` fails and raise an error, and then make sure the pset_hash is there when we upload in the postjob

**Comment by AndresTanasijczuk** [comment]
Currently we calculate the pset_hash only when there is an EDM output file in the job (https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L740-L742). Other type of output files do not have the pset_hash in the job report. So adding a check in the postjob about the pset_hash being in the job report should only be done for EDM files.

**Comment by belforte** [comment]
the correct distinction would be "only for files that we'll publish".
Is this known about the file as a flag/property ? Or is it computed every time based on file name 
and/or format from .. where ? We still want to be able to publish non-EDM files.

**Comment by mmascher** [comment]
To be reviewed together with https://github.com/dmwm/CRABServer/issues/5141

**Comment by belforte** [comment]
I think was solved. We will worry if and when problems surface again
