### ISSUE TITLE
Make the analysis of growing input datasets "easier"

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4982]
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/915.html

**Comment by belforte** [comment]
I volunteer to provide the needed python to do this in the crabConfig

**Comment by AndresTanasijczuk** [comment]
Can this be closed? We have documentation in place, and we have the function getLumiListInValidFiles available in 3.3.1510 client.

**Comment by belforte** [comment]
yes. closing
