### ISSUE TITLE
Ops monitoring improvements

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4983]
Hi all,

the new monitoring Emilis was working on is now in production, see https://cmsweb.cern.ch/crabserver/ui

There are a few minor things we noticed and we would like to improve:

1. If the webdirprx API returns an empty list we should fallback to non-proxied link for the web dir. This for anything that needs to be looked up in the sandbox (user crab client config and pset + scriptexe)
1. The loading of the sandbox might take a while, I suggested to put an animated gif while waiting so users know they are waiting.
1. There is an issue for people who repeatedly has to click to the firefox message "I trust this resource" when navigating cmsweb. This prevents pages for opening. We need to catch this error and point to a FAQ page that explains how to set firefox so that you do not receive these messages (Diego Gomes showed this to me some time ago)

**Comment by juztas** [comment]
For 3. you need these both certs installed and mark that you trust them when importing: https://cafiles.cern.ch/cafiles/certificates/Download.aspx?ca=grid

**Comment by emaszs** [comment]
I remember doing this previously, but when I did it again, I seem to not be getting the "I understand the risks" window any more. I still get the less annoying User Identification Request window from time to time.
