### ISSUE TITLE
uncaught site error in  CMSRunAnalysis.sh 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4988]
notices a lot of failed jobs at FNAL, looked at one [#] and found this  [##]

it is clearly some site issue, but should not have resulted in UNKNOWN error but rather in
10020 - Shell script cmsset_default.sh to setup cms environment is not found 

FWIW, crab status says exit code -1 [###]

[#]
https://cmsweb.cern.ch/scheddmon/096/cms185/150910_231834:padeken_crab_TTJets_SingleLeptFromT_13TeVMLM_MCRUN2_74_V9_ext1-v1_MG/job_out.51.2.txt

[##]
'''
======== CMSRunAnalysis.sh STARTING at Thu Sep 10 23:44:04 GMT 2015 ========
Local time : Thu Sep 10 18:44:04 CDT 2015
Current system : Linux cmswn1664.fnal.gov 2.6.32-504.30.3.el6.x86_64 #1 SMP Tue Jul 14 11:18:03 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
==== CMSSW pre-execution environment bootstrap STARTING ====
+ '[' x '!=' x ']'
+ '[' x '!=' xUNAVAILABLE ']'
+ echo 'OSG style'
OSG style
+ set +x
./CMSRunAnalysis.sh: line 45: UNAVAILABLE/cmssoft/cms/cmsset_default.sh: No such file or directory

real	0m0.006s
user	0m0.001s
sys	0m0.003s
CMSRunAnalysis.sh complete at Thu Sep 10 23:44:04 GMT 2015 with (short) exit status 1
======== CMSRunAnalsysis.sh at Thu Sep 10 23:44:04 GMT 2015 FINISHING ========
'''
[###]
'''
UN2_74_V9_ext1-v1_MGTC3> crab status -d crab_TTJets_SingleLeptFromT_13TeVMLM_MCR 
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_TTJets_SingleLeptFromT_13TeVMLM_MCRUN2_74_V9_ext1-v1_MG
Task name:			150910_231834:padeken_crab_TTJets_SingleLeptFromT_13TeVMLM_MCRUN2_74_V9_ext1-v1_MG
Task status:			SUBMITTED	on schedd: crab3test-3@vocms096.cern.ch
Warning:			The CRAB3 server got a non-critical error while checking stageout permissions. Please use checkwrite to check if everything is fine.
Warning:			The CRAB3 server got a non-critical error while checking stageout permissions. Please use checkwrite to check if everything is fine.
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150910_231834%3Apadeken_crab_TTJets_SingleLeptFromT_13TeVMLM_MCRUN2_74_V9_ext1-v1_MG

Jobs status:			failed         33.2% ( 374/1128)
				idle            0.5% (   6/1128)
				running         1.0% (  11/1128)
				transferring   65.3% ( 737/1128)

No publication information (publication has been disabled in the CRAB configuration file)

Error Summary: (use --verboseErrors for details about the errors)

 372 jobs failed with exit code -1

   2 jobs failed with exit code 60307

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_TTJets_SingleLeptFromT_13TeVMLM_MCRUN2_74_V9_ext1-v1_MG/crab.log
belforte@lxplus0092/TC3> 
'''

**Comment by mmascher** [comment]
Closing as duplicated
