### ISSUE TITLE
Improve crab3 validation scripts

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4989]
a) add missing templates (mixing inputFiles) (Similar was: https://github.com/dmwm/CRABServer/issues/4666)
b) add validation for deprecated, invalid dataset/files. (Similar was: https://github.com/dmwm/CRABServer/issues/4736)
c) check crabclient commands on validation tasks (Also has to run with old client) with status/resubmit/getlog/output/checkwrite and etc...
d) We made this for production (https://github.com/juztas/scripts/blob/master/workload-checker.py) which I think Alan is using and similar thing could be done for crab.

**Comment by belforte** [comment]
@jmarra13 was this done ?

**Comment by jmarra13** [comment]
>a) add missing templates (mixing inputFiles) (Similar was: #4666)

not yet.

>b) add validation for deprecated, invalid dataset/files. (Similar was: #4736)

Analysis_Use_Invalid.py            done
Analysis_Use_Deprecated.py    done
will append both on this PR #5104

>c) check crabclient commands on validation tasks (Also has to run with old client) with status/resubmit/getlog/output/checkwrite and etc...

I ran this tests by hand, needs to put it on script

>d) We made this for production (https://github.com/juztas/scripts/blob/master/workload-checker.py) which I think Alan is using and similar thing could be done for crab.

not yet

**Comment by belforte** [comment]
OK, thanks. Let's keep it open and let me know when it is done.

**Comment by belforte** [comment]
@jmarra13 any update ? Is it realistic to do all that was listed ? I guess we need a new milestone

**Comment by jmarra13** [comment]
current status is (b) and (c) done, (a) and (b) on going.

**Comment by emaszs** [comment]
Let's say this was done.
