### ISSUE TITLE
Weird things happening if $OSG_APP=UNDEFINED

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4996]
With reference to  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/944.html , let me describe the situation.

The OSG_APP variable at FNAL was set to UNDEFINED (see the ggus attached to the hypernews), and this resulted in this line failing:

https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.sh#L45

It is not clear how (to me), but we exited CMSRunAnalysis with exit code 1, see this line printed by gWMS-CMSRunAnalysis.sh:

`CMSRunAnalysis.sh complete at Thu Sep 17 00:39:59 GMT 2015 with (short) exit status 1`

Despite OSG_APP being set to a wrong value, we find the COMP python (apparently in cvmfs), and execute cmscp, which fails immediately since ServerUtilities is not there (it is in another tar.gz and unpacked by CMSRunAnalysis which was not executed). Same is for DashboardFailure.sh which is not found (and not executed) here:

https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L161-L165

The postjob finally kick in and what the user sees is:

```
'exit message' = The framework job report could be loaded, but no error message was found there.
```

which is the same thing reported in dashboard.

I think what I would mostly fix here is that the `ExitCode` in dashboard is NA, and the error reason reported by the postjob is "misleading" (well not too much, we say no error messages were found). We should report the correct reason (probably by creating an ad_hoc fwjr.json in the worker node).

This is the logfile:

https://cmsweb.cern.ch/scheddmon/096/cms1097/150917_003311:pgras_crab_ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1-0001/job_out.6.2.txt

and this is the interesting snippet:

```
======== CMSRunAnalysis.sh at Thu Sep 17 00:39:59 GMT 2015 STARTING ========
======== CMSRunAnalysis.sh STARTING at Thu Sep 17 00:39:59 GMT 2015 ========
Local time : Wed Sep 16 19:39:59 CDT 2015
Current system : Linux cmswn2057.fnal.gov 2.6.32-504.30.3.el6.x86_64 #1 SMP Tue Jul 14 11:18:03 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
==== CMSSW pre-execution environment bootstrap STARTING ====
+ '[' x '!=' x ']'
+ '[' x '!=' xUNAVAILABLE ']'
+ echo 'OSG style'
OSG style
+ set +x
./CMSRunAnalysis.sh: line 45: UNAVAILABLE/cmssoft/cms/cmsset_default.sh: No such file or directory

real	0m0.007s
user	0m0.001s
sys	0m0.004s
CMSRunAnalysis.sh complete at Thu Sep 17 00:39:59 GMT 2015 with (short) exit status 1
======== CMSRunAnalsysis.sh at Thu Sep 17 00:39:59 GMT 2015 FINISHING ========
======== python2.6 bootstrap for stageout at Thu Sep 17 00:39:59 GMT 2015 STARTING ========
+ '[' x '!=' x ']'
+ '[' x '!=' xUNAVAILABLE ']'
+ set +x
/storage/local/data1/condor/execute/dir_53957/glide_VeH2ZM/execute/dir_48390/condor_exec.exe: line 110: UNAVAILABLE/cmssoft/cms/cmsset_default.sh: No such file or directory
+ '[' -e /COMP/slc5_amd64_gcc434/external/python/2.6.4/etc/profile.d/init.sh ']'
+ '[' -e UNAVAILABLE/cmssoft/cms/COMP/slc5_amd64_gcc434/external/python/2.6.4/etc/profile.d/init.sh ']'
+ command -v python2.6
+ rc=0
+ set +x
Found python2.6 at:
/usr/bin/python2.6
======== python2.6 bootstrap for stageout at Thu Sep 17 00:39:59 GMT 2015 FINISHING ========
======== Attempting to notify HTCondor of file stageout ========
	Error: 22 (Invalid argument)
======== Stageout at Thu Sep 17 00:39:59 GMT 2015 STARTING ========
Traceback (most recent call last):
  File "./cmscp.py", line 19, in <module>
    from ServerUtilities import cmd_exist
ImportError: No module named ServerUtilities
======== ERROR: Unable to initialize WMCore at Thu Sep 17 00:39:59 GMT 2015 ========
sh: ./DashboardFailure.sh: No such file or directory

```

**Comment by belforte** [comment]
seems the same as this, right ?
https://github.com/dmwm/CRABServer/issues/4988

I think we should simply exit with e.g.
10020 - Shell script cmsset_default.sh to setup cms environment is not found 
(indeed we should cleanup the exit codes there, there's a zilion of them in the 1003x range
where one or two would do. Let's skip on why is that way, but

**Comment by mmascher** [comment]
Yes, this is a duplicatd, I would keeping this one as it has a little bit better description.

**Comment by belforte** [comment]
yes, this saves me the investigation effort which was the reason for the october milestone :-)

**Comment by mmascher** [comment]
One thing I did not mention for the implementation is that (imho) we do not need to execute cmscp in this case.

**Comment by belforte** [comment]
should better happen naturally everytime there is a failure in the setup before calling cmsRun (or 
scriptExe). not be added ad hoc for this particular case.

**Comment by mmascher** [comment]
about:

>It is not clear how (to me), but we exited CMSRunAnalysis with exit code 1

that's normal:

```bash
MacBook-Air-di-Marco:~ mmasche$ cat tmp.sh
echo pre
source cccccc
echo post
MacBook-Air-di-Marco:~ mmasche$ sh tmp.sh
pre
tmp.sh: line 2: cccccc: No such file or directory
```

**Comment by mmascher** [comment]
This pull from @juztas should improve things a little https://github.com/dmwm/CRABServer/pull/5008

**Comment by belforte** [comment]
Marco pointed me to one current task with this problem and exit code is now correctly 10031
http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=200&sorting[]=2&sorting[]=asc&activemenu=2&status=&site=&tid=150930_151846%3Alecriste_crab_B0toMuMuPP_datasetD_withJpsiInclTrigg

yet other odd things happen
1. almost all jobs have site = unknown and report 0 time
  looking at job stdout, it is truncated, what could have happened ?
e.g.
https://cmsweb.cern.ch/scheddmon/096/cms382/150930_151846:lecriste_crab_B0toMuMuPP_datasetD_withJpsiInclTrigg/job_out.139.1.txt

2.  for jobs where job wrapper completed properly and properly reported to dashboard, why didn't the wrapper add the sleep time to reach the specified minimum duration (15min ? 20min ?) which was put there exactly to avoid that a few bad WN's become a black hole (likely to have happened here)

**Comment by juztas** [comment]
I would say it is site problem not setting correctly env variable and we can't poke around to find there it is... Currently we do almost same as production, just one diff what prod is doing [1]. This for sure should be same (Prod, Ana, SAM), but it is not the case right now.

For unknown, due to that failure, we did not reported correct parameters to dashboard only about stageout failure, which did not happened at all. Which parameter dashboard expects? se, ce, sitename?

About sleep, here is not correct: https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L16 will fix soon

[1]
https://github.com/dmwm/WMCore/blob/master/etc/submit.sh#L32-L34

**Comment by belforte** [comment]
looking at stdout for a job which dashboard says : site=unknown and one for which it says T2_US_Purdue, there is no significative difference. It could be lost UDP message, but so many it is hard to accept. Apparently dashboard did not CE name either. Let's assume it was some random congestion, if it keeps happening we can ask dashboard to investigate or simply send the site info a couple of times. I like that site failures show up labelled with the bad site name

anyhow yes, this cam be closed as solved, the sleep is a different thing

**Comment by belforte** [comment]
solved. Although I do not have a pointer to the precise commit with the tix

**Comment by juztas** [comment]
https://github.com/dmwm/CRABServer/pull/5008
