### ISSUE TITLE
 CMSRunAnalysis.py and cmscp.py should be using the same python

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4998]
With reference to https://github.com/dmwm/CRABServer/pull/4884 and this comment: https://github.com/dmwm/CRABServer/pull/4884#issuecomment-141045493

We should modify https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh to use the same python for `CMSRunAnalysis.py` and `cmscp.py`

**Comment by belforte** [comment]
we really nedd to do something about this line
`PYTHONUNBUFFERED=1 python2.6 cmscp.py` in
https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L217
since we can't expect python2.6 to be there forever !
So I am rasing priority. Needs to be done in 2016.
