### ISSUE TITLE
skip input data blocks which are open in phedex

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5013]
currently this happens only accidentally because they have no location, but there is nothing to guaranteed that they will never have a location.
So make it clear, and skip them.
(as discussed in Crab3 meeting today)

**Comment by AndresTanasijczuk** [comment]
*Note*: This has to be done in DBSDataDiscovery.

**Comment by belforte** [comment]
DBSDataDiscovery does not talk to PhEDEx directly.
Location is looked up via `listFileBlockLocation` in WMCore/Services/DBS but that already is limited to blocks `complete` in PhEDEx:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L641

**Comment by belforte** [comment]
I suspect the initial discussion was based on wrong information.
PhEDEx has the concept of complete blocks, and they are skipped.
DBS has the concept of open blocks, but those have always been processed.

I.e. nothing to do.
