### ISSUE TITLE
Update code to be modern, more python 3 compatible

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#5014]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/DMWMTutModernPython describes how to do this with the futurize command. I suggest you do this a fixer or two at a time, starting with the top of the list to figure out what might cause problems and what might not.

**Comment by ericvaandering** [comment]
@belforte please update the milestone to November or December. That is the agreement within DMWM.

**Comment by belforte** [comment]
@mmascher says it is done in the Master, will be in Febraury release
