### ISSUE TITLE
Link in the webdir for input and output tarballs

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5024]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/989/1/1.html

It's an easy change, I will take care of it now https://github.com/dmwm/CRABServer/blob/master/scripts/AdjustSites.py#L186

**Comment by AndresTanasijczuk** [comment]
Btw, wouldn't it be better to preserve the file/directory names in the symbolic links?
