### ISSUE TITLE
allow to kill tasks in all states (exp. QUEUED)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5025]
From a user's feedback:

(7) "crab kill" was recently fixed (thanks!) but still doesn't work in most states other than 
"running".  For example, if I caught a mistake immediately after submitting, then "crab kill" just 
says something like "can't kill when in QUEUED state".  I normally don't have the patience to wait 
until it reaches a kill-able state.

**Comment by mmascher** [comment]
Uhm... very dangerous, `QUEUED` means the TaskWorker has acquired the task and is working on it, and the task state will be changed to the permanent state afterwards. If you want to kill a task while it is QUEUED.. well, you might better queue the kill request and then execute it after the TW released the task.

**Comment by AndresTanasijczuk** [comment]
Currently (or at least from tomorrow October release) we allow to kill tasks in statuses [`SUBMITTED`, `KILLFAILED`, `RESUBMITFAILED` and `FAILED`. And concerning individual jobs statuses, we permit to kill anything that is not `finished`. I killed today a task after submission, when the task was SUBMITTED and job was idle.

**Comment by AndresTanasijczuk** [comment]
The other not transient task statuses that we have are: `COMPLETED`, `SUBMITFAILED`, `KILLED`, for which accepting a kill doesn't make sense.

**Comment by mmascher** [comment]
I was thinking we could address this like we are doing with `submit --wait`

**Comment by belforte** [comment]
let's review once we have the code in the TaskManager which recovers QUEUED tasks

**Comment by belforte** [comment]
not relevant any more
