### ISSUE TITLE
allow to run a single job from a task

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5026]
It seems there are times when this is useful. But details of what exactly is desired need to be clarified.
So far we got this thread:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/989.html

and this feedback:

> On Oct 4, 2015, at 08:33, Alex George george@physics.ucsb.edu wrote:
> (1) We would like to be able to run only a single job from a task.  For example, if one task completes partially and becomes unrecoverable, our only recourse is to submit an entire separate task and then either wait for it to finish, or try to mix-and-match the outputs (and mix-and-match doesn’t always work even when our instructions haven’t changed, not sure why).

**Comment by belforte** [comment]
follow up:

On 10/05/2015 11:08 AM, Alex George wrote:
> The desired workflow from my point of view is the following:
> (a) I submit and run a task as follows
> (b) A few days later, I come back and see that a few jobs failed and I cannot resubmit them for some reason (maybe I deleted the crab dir, maybe a communications error, etc.)
> (c) So I run the same crab submit script as before, but this time I pass something like a --runOnly 50,183, which will submit only jobs 50 and 183.  Ideally, these would have a very high priority, since they are only two jobs and they are holding up my entire task.


if you deleted the crab dir, you can do:

crab remake --task=<task_name>
crab resubmit --jobIds=50,183

And indeed CRAB gives higher priority to resubmission

Communication errors are transient, sort of by definition, of course to resubmit you need to talk to the condor schedd which was working your task to begin with, and if that happens to be down, you have to wait. In such a case it is quite questionable that submitting another instance of the full task on another schedd will complete any faster. And of course one can't say in advance.

Of course at times CRAB client does not clearly say: schedd vocms018 is temporarely down, please try again in one hour or so. That's to be improved IMHO.

Finally we are left with situations where the schedd is down for longish time or the internal bookkeeping was messed up for some failure. The former is a know HTC shortcoming and I am sure we can set something up, but it will be a while before it is top priority. The latter.. well  a recovery task seems the only way, in lack of recovery information indeed you will have to restart.

But maybe there's some other possibility which I missed ?

**Comment by belforte** [comment]
I set MIletone permanent because so far it is a discussion thread. If it evolves in specific actions, will open specific issues.

**Comment by mmascher** [comment]
Hi Stefano,

summarizing, we can already resubmit a single job in a task assuming the schedd is alive, dagman is running, or in general the task is not brokem. What we want is to improve the way we submit recovery tasks adding the possibility to specify a set of jobid from a task?

**Comment by belforte** [comment]
I think so. But let's wait for more specific examples.
Because to do this we'd need full info about that task and
a way to avoid race conditions. The latter is particularly worrying.

**Comment by belforte** [comment]
this is in the end a duplicate of #5140 
We will make it clear in the documentation that this is mostly a debugging tool, or a way to do local submission, but it is not a way to complete a running task.
