### ISSUE TITLE
Query for lastFailures needs to be changed

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5028]
This is why https://cmsweb.cern.ch/crabserver/prod/task?subresource=lastfailures&minutes=360 is not showing any task. Now we have `SUBMITFAILED`, `KILLFAILED` and `RESUBMITFAILED` and this query is only getting `FAILED` https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/TaskDB/Oracle/Task/Task.py#L36 

BTW @AndresTanasijczuk , do we still have `FAILED` ?

@jmarra13

**Comment by AndresTanasijczuk** [comment]
Yes, we still have `FAILED`.

**Comment by AndresTanasijczuk** [comment]
@mmascher @jmarra13 This issue is now fixed, right?

**Comment by jmarra13** [comment]
@AndresTanasijczuk  seems not, now it is raising a 500 Internal Server Error
