### ISSUE TITLE
Fix regular expression for primary dataset name

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5031]
In case of an Analysis task without an input dataset, a user is required to use
Data.primaryDataset = '/A/B/C' while it should be enough to specify Data.primaryDataset = 'A'. The problem is that this regex https://github.com/dmwm/CRABServer/blob/3.3.1510.rc8/src/python/CRABInterface/Regexps.py#L32 has changed recently to require the full dataset name pattern. This regex is used in https://github.com/dmwm/CRABServer/blob/86acd5b12f274c5dfab2d033b8b7e9c2603239df/src/python/CRABInterface/RESTUserWorkflow.py#L352-L353
This is in general correct, except that "inputdata" is actually the primary dataset name (in the form "/A" form) when a task doesn't require an input dataset but a primary dataset name.
So we either generalize this regex or use RX_LFNPRIMDS instead as in https://github.com/dmwm/CRABServer/blob/86acd5b12f274c5dfab2d033b8b7e9c2603239df/src/python/CRABInterface/RESTUserWorkflow.py#L364

**Comment by belforte** [comment]
what is an Analysis task w/o input dataset ? A task where input comes form a list of LFN's ?
Isn't this different enough from Analysis on a DBS dataset that
we should have a new jobtype, with the proper validation in
`CRABInterface/RESTUserWorkflow.py`

Also.. why should a primary dataset be handled in "inputdata" ?
IIUC a primary dataset is only indicated by the user to create the dataset path for output publication.

**Comment by AndresTanasijczuk** [comment]
Q: what is an Analysis task w/o input dataset ? A task where input comes form a list of LFN's ?
A: Yes, that's what I meant.

Q: Why should a primary dataset be handled in "inputdata" ?
A: Coded this way since the very beginning. I personally prefer to have a separate server parameter for storing the primary dataset name. (I always prefer to have meaningful parameter names even if that implies proliferation of parameters.) The mix here comes because in an Analysis task with an input dataset, the primary dataset name for publication is extracted from the input dataset name. The server (postjob) does something like `primarydatasetname_for_publication = inputdata.split('/')[1]`. So it was "easier" in an Analysis task with no input dataset to put the primary dataset name in the `inputdata` server parameter as well (adding a '/' in front).

Q: IIUC a primary dataset is only indicated by the user to create the dataset path for output publication.
A: And also for LFN path.

**Comment by belforte** [comment]
that's part of the publication process, still nothing to do with input

**Comment by belforte** [comment]
I fully agree that it was coded in a very bad way wince the very beginning. Was a quick hack and now 
it shows the lack of flexibility.
The only sensible solution is to do it properly.

Until that is done, my opinion is that we can't support publication for "input is a list of files".
And do not waste time trying to fix this in some other hacky way.

**Comment by annawoodard** [comment]
> I personally prefer to have a separate server parameter for storing the primary dataset name. (I always prefer to have meaningful parameter names even if that implies proliferation of parameters.) 

I agree with this. Wouldn't that solve the problem in a 'proper' way without needing a new jobtype?

**Comment by belforte** [comment]
yeah, no new jobtype unless needed. But if code ends up in being full of
`if input is a list of file` it may be more clean with a different jobtype,
e.g. DBS access is to be fully skipped, seems to me hard to do w/o an `if`.
Otherwise, why do we have jobtypes ? E.g.CRAB2 was effectively doing
`if inputdataset==None then jobtype=MC else jobtype=analysis`
