### ISSUE TITLE
crab status and crab status --long show different status for killed jobs

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5032]
For example in https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1014.html
crab status showed 'running' while crab status --long showed 'killed'. 

Why do we get status information from different places for `crab status` (form node_state) and `crab status --long` (from job_log)? Can't we use the same source of information for both (I would say job_log, since it seems more precise)? And if we want to have the option for using a different source, maybe we can add an option-for-experts in crab status for that.

**Comment by AndresTanasijczuk** [comment]
Another example:  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1197.html
This task had 1 killed job for which crab status showed it as 'running' while crab status --long showed it as transferring.

**Comment by belforte** [comment]
will be sorted out as part of the crab status unification in the new status impementation @emaszs is doing
