### ISSUE TITLE
Allow resubmission of killed jobs

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5033]
We currently only allow resubmission of 'failed' (and 'finished' if --force) jobs.

**Comment by belforte** [comment]
yes, we should.  Changing title.

**Comment by belforte** [comment]
should make sure if killed means killed by user or killed by condor_rm because of periodic_remove or operator action. We may want different policies.

**Comment by belforte** [comment]
this requires changing stuff in DAGMAN or/and the way we interact with it, it is not immediately trivial and expert help will be needed.

**Comment by mmascher** [comment]
I am not sure how useful this is in real life. Given that it is not obvious how to do, and that we rather encourage recovery tasks.. let's put in low priority and will close if nothing new appears by end of the year or so

**Comment by belforte** [comment]
we keep it like it is and tell user to run recovery tasks.
In the end the main use case for kill is to make sure that processing has stopped before preparing a recovery task.
