### ISSUE TITLE
user specified site white list does not work for PrivateMC ?

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5051]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1082.html
i.e.
https://cmsweb.cern.ch/crabserver/ui/task/151026_230005:jfaulkne_crab_WWAToLNu2jA_4f_NLO_TuneCUETP8M1_13TeV-amcatnlo-pythia8
here's from the crab config
config.section_('Site')
config.Site.whitelist = ['T2_CH_CERN', 'T3_US_FNALLPC']

and here from TW log

Blocks: ['MCFackBlock']
Locations: ['T3_US_PuertoRico', 'T2_FI_HIP', 'T2_UK_SGrid_RALPP', 'T2_FR_GRIF_LLR', 'T3_US_Baylor', 'T3_UK_London_QMUL', 'T3_TW_NTU_HEP', 'T3_US_UIowa', 'T3_US_Omaha', 'T2_KR_KNU', 'T2_RU_SINP', 'T3_US_UMD', 'T2_CH_CERN_AI', 'T3_US_Colorado', 'T3_IT_Napoli', 'T3_NZ_UOA', 'T2_TH_CUNSTDA', 'T3_US_Kansas', 'T3_GR_IASA', 'T2_IT_Bari', 'T2_US_UCSD', 'T1_RU_JINR', 'T3_US_Vanderbilt_EC2', 'T2_RU_IHEP', 'T2_RU_RRC_KI', 'T3_US_JHU', 'T3_BY_NCPHEP', 'T3_US_TTU', 'T3_GR_Demokritos', 'T3_US_UTENN', 'T3_US_UCR', 'T3_TW_NCU', 'T2_CH_CSCS', 'T2_UA_KIPT', 'T3_RU_FIAN', 'T2_RU_PNPI', 'T2_IN_TIFR', 'T3_UK_London_UCL', 'T3_US_Brown', 'T3_US_UCD', 'T3_CO_Uniandes', 'T3_KR_KNU', 'T2_FR_IPHC', 'T3_US_OSU', 'T3_US_TAMU', 'T1_US_FNAL', 'T2_IT_Rome', 'T2_UK_London_Brunel', 'T3_IN_PUHEP', 'T3_IT_Trieste', 'T2_EE_Estonia', 'T3_UK_ScotGrid_ECDF', 'T2_CN_Beijing', 'T2_US_Florida', 'T3_CH_CERN_HelixNebula', 'T3_US_Princeton_ICSE', 'T3_IT_MIB', 'T3_US_FNALXEN', 'T3_US_Rutgers', 'T1_DE_KIT', 'T3_IR_IPM', 'T2_US_Wisconsin', 'T2_HU_Budapest', 'T2_DE_RWTH', 'T2_US_Vanderbilt', 'T2_BR_SPRACE', 'T3_UK_SGrid_Oxford', 'T3_US_NU', 'T2_CH_CERN', 'T2_BR_UERJ', 'T3_MX_Cinvestav', 'T3_US_FNALLPC', 'T1_UK_RAL', 'T3_IT_Firenze', 'T3_US_Cornell', 'T2_ES_IFCA', 'T3_US_UVA', 'T3_ES_Oviedo', 'T3_US_NotreDame', 'T2_DE_DESY', 'T3_KR_KISTI', 'T3_HU_Debrecen', 'T2_US_Caltech', 'T3_FR_IPNL', 'T3_UK_London_RHUL', 'T3_CN_PKU', 'T2_UK_London_IC', 'T2_US_Nebraska', 'T2_ES_CIEMAT', 'T3_US_Princeton', 'T2_PK_NCP', 'T3_US_FSU', 'T3_KR_UOS', 'T3_IT_Perugia', 'T1_IT_CNAF', 'T3_US_Minnesota', 'T2_TR_METU', 'T2_AT_Vienna', 'T2_US_Purdue', 'T3_US_Rice', 'T3_HR_IRB', 'T2_BE_UCL', 'T3_US_FIT', 'T2_UK_SGrid_Bristol', 'T2_PT_NCG_Lisbon', 'T3_US_UMiss', 'T1_ES_PIC', 'T2_IT_Legnaro', 'T2_RU_INR', 'T3_US_SDSC', 'T3_US_FIU', 'T2_RU_JINR', 'T2_IT_Pisa', 'T2_GR_Ioannina', 'T3_UK_ScotGrid_GLA', 'T3_US_MIT', 'T3_US_Princeton_ARM', 'T3_US_UCSB', 'T2_MY_UPM_BIRUNI', 'T1_FR_CCIN2P3', 'T2_FR_GRIF_IRFU', 'T3_US_NERSC', 'T2_FR_CCIN2P3', 'T2_CH_CERN_HLT', 'T2_PL_Warsaw', 'T2_US_MIT', 'T2_BE_IIHE', 'T2_RU_ITEP', 'T2_PL_Swierk', 'T3_CH_PSI', 'T3_IT_Bologna']
Possible sites: ['T3_US_PuertoRico', 'T2_FI_HIP', 'T2_UK_SGrid_RALPP', 'T2_FR_GRIF_LLR', 'T3_US_Baylor', 'T3_UK_London_QMUL', 'T3_TW_NTU_HEP', 'T3_US_UIowa', 'T3_US_Omaha', 'T2_KR_KNU', 'T2_RU_SINP', 'T3_US_UMD', 'T2_CH_CERN_AI', 'T3_US_Colorado', 'T3_IT_Napoli', 'T3_NZ_UOA', 'T2_TH_CUNSTDA', 'T3_US_Kansas', 'T3_GR_IASA', 'T2_IT_Bari', 'T2_US_UCSD', 'T1_RU_JINR', 'T3_US_Vanderbilt_EC2', 'T2_RU_IHEP', 'T2_RU_RRC_KI', 'T3_US_JHU', 'T3_BY_NCPHEP', 'T3_US_TTU', 'T3_GR_Demokritos', 'T3_US_UTENN', 'T3_US_UCR', 'T3_TW_NCU', 'T2_CH_CSCS', 'T2_UA_KIPT', 'T3_RU_FIAN', 'T2_RU_PNPI', 'T2_IN_TIFR', 'T3_UK_London_UCL', 'T3_US_Brown', 'T3_US_UCD', 'T3_CO_Uniandes', 'T3_KR_KNU', 'T2_FR_IPHC', 'T3_US_OSU', 'T3_US_TAMU', 'T1_US_FNAL', 'T2_IT_Rome', 'T2_UK_London_Brunel', 'T3_IN_PUHEP', 'T3_IT_Trieste', 'T2_EE_Estonia', 'T3_UK_ScotGrid_ECDF', 'T2_CN_Beijing', 'T2_US_Florida', 'T3_CH_CERN_HelixNebula', 'T3_US_Princeton_ICSE', 'T3_IT_MIB', 'T3_US_FNALXEN', 'T3_US_Rutgers', 'T1_DE_KIT', 'T3_IR_IPM', 'T2_US_Wisconsin', 'T2_HU_Budapest', 'T2_DE_RWTH', 'T2_US_Vanderbilt', 'T2_BR_SPRACE', 'T3_UK_SGrid_Oxford', 'T3_US_NU', 'T2_CH_CERN', 'T2_BR_UERJ', 'T3_MX_Cinvestav', 'T3_US_FNALLPC', 'T1_UK_RAL', 'T3_IT_Firenze', 'T3_US_Cornell', 'T2_ES_IFCA', 'T3_US_UVA', 'T3_ES_Oviedo', 'T3_US_NotreDame', 'T2_DE_DESY', 'T3_KR_KISTI', 'T3_HU_Debrecen', 'T2_US_Caltech', 'T3_FR_IPNL', 'T3_UK_London_RHUL', 'T3_CN_PKU', 'T2_UK_London_IC', 'T2_US_Nebraska', 'T2_ES_CIEMAT', 'T3_US_Princeton', 'T2_PK_NCP', 'T3_US_FSU', 'T3_KR_UOS', 'T3_IT_Perugia', 'T1_IT_CNAF', 'T3_US_Minnesota', 'T2_TR_METU', 'T2_AT_Vienna', 'T2_US_Purdue', 'T3_US_Rice', 'T3_HR_IRB', 'T2_BE_UCL', 'T3_US_FIT', 'T2_UK_SGrid_Bristol', 'T2_PT_NCG_Lisbon', 'T3_US_UMiss', 'T1_ES_PIC', 'T2_IT_Legnaro', 'T2_RU_INR', 'T3_US_SDSC', 'T3_US_FIU', 'T2_RU_JINR', 'T2_IT_Pisa', 'T2_GR_Ioannina', 'T3_UK_ScotGrid_GLA', 'T3_US_MIT', 'T3_US_Princeton_ARM', 'T3_US_UCSB', 'T2_MY_UPM_BIRUNI', 'T1_FR_CCIN2P3', 'T2_FR_GRIF_IRFU', 'T3_US_NERSC', 'T2_FR_CCIN2P3', 'T2_CH_CERN_HLT', 'T2_PL_Warsaw', 'T2_US_MIT', 'T2_BE_IIHE', 'T2_RU_ITEP', 'T2_PL_Swierk', 'T3_CH_PSI', 'T3_IT_Bologna']
Resulting available sites: ['T3_US_PuertoRico', 'T2_FI_HIP', 'T2_UK_SGrid_RALPP', 'T2_FR_GRIF_LLR', 'T3_IT_Trieste', 'T3_US_Omaha', 'T2_KR_KNU', 'T3_US_UMD', 'T3_US_Colorado', 'T3_KR_KISTI', 'T3_NZ_UOA', 'T3_US_Kansas', 'T2_IT_Bari', 'T2_US_UCSD', 'T1_RU_JINR', 'T3_US_Vanderbilt_EC2', 'T2_RU_IHEP', 'T2_CH_CERN', 'T3_BY_NCPHEP', 'T3_US_TTU', 'T3_GR_Demokritos', 'T3_US_UTENN', 'T3_US_UCR', 'T3_TW_NCU', 'T2_UA_KIPT', 'T2_PK_NCP', 'T2_IN_TIFR', 'T3_UK_London_UCL', 'T3_US_Brown', 'T3_CO_Uniandes', 'T3_KR_KNU', 'T2_FR_IPHC', 'T3_US_OSU', 'T3_US_TAMU', 'T1_US_FNAL', 'T2_IT_Rome', 'T2_UK_London_Brunel', 'T3_IN_PUHEP', 'T2_US_Vanderbilt', 'T2_EE_Estonia', 'T3_UK_ScotGrid_ECDF', 'T2_CN_Beijing', 'T2_US_Florida', 'T3_CH_CERN_HelixNebula', 'T3_IT_MIB', 'T3_US_FNALXEN', 'T3_US_Rutgers', 'T1_DE_KIT', 'T3_IR_IPM', 'T2_US_Wisconsin', 'T2_HU_Budapest', 'T2_DE_RWTH', 'T2_BR_SPRACE', 'T3_UK_SGrid_Oxford', 'T3_US_NU', 'T3_US_NERSC', 'T2_BR_UERJ', 'T3_MX_Cinvestav', 'T3_US_FNALLPC', 'T3_US_UIowa', 'T3_IT_Firenze', 'T3_US_Cornell', 'T2_ES_IFCA', 'T3_US_UVA', 'T3_ES_Oviedo', 'T2_DE_DESY', 'T1_UK_RAL', 'T3_HU_Debrecen', 'T2_US_Caltech', 'T3_FR_IPNL', 'T3_UK_London_RHUL', 'T3_CN_PKU', 'T2_UK_London_IC', 'T2_US_Nebraska', 'T2_ES_CIEMAT', 'T3_US_Princeton', 'T3_UK_ScotGrid_GLA', 'T3_US_FSU', 'T3_KR_UOS', 'T3_IT_Perugia', 'T1_IT_CNAF', 'T3_US_Minnesota', 'T2_AT_Vienna', 'T2_US_Purdue', 'T3_US_Rice', 'T3_HR_IRB', 'T2_BE_UCL', 'T3_US_FIT', 'T2_UK_SGrid_Bristol', 'T1_ES_PIC', 'T3_US_JHU', 'T2_IT_Legnaro', 'T3_US_SDSC', 'T3_US_FIU', 'T2_RU_JINR', 'T2_IT_Pisa', 'T2_GR_Ioannina', 'T3_US_MIT', 'T3_US_Princeton_ARM', 'T3_US_UCSB', 'T1_FR_CCIN2P3', 'T2_FR_GRIF_IRFU', 'T3_US_UMiss', 'T2_FR_CCIN2P3', 'T2_US_MIT', 'T2_BE_IIHE', 'T3_CH_PSI', 'T3_IT_Bologna']

Submission finished
Pushing information centrally {'status': 'SUBMITTED', 'subresource': 'success', 'jobset': '-1', 'workflow': '151026_230005:jfaulkne_crab_WWAToLNu2jA_4f_NLO_TuneCUETP8M1_13TeV-amcatnlo-pythia8'}
Dashboard job info: {'TargetSE': 'T3_US_PuertoRico,T2_FI_HIP,T2_UK_SGrid_RALPP,T2_FR_GRIF_LLR,T3_IT_Trieste,T3_US_Omaha,T2_KR_KNU,T3_US_UMD,T3_US_Colorado,T3_KR_KISTI,T3_NZ_UOA,T3_US_Kansas,T2_IT_Bari,T2_US_UCSD,T1_RU_JINR,T3_US_Vanderbilt_EC2,T2_RU_IHEP,T2_CH_CERN,T3_BY_NCPHEP,T3_US_TTU,T3_GR_Demokritos,T3_US_UTENN,T3_US_UCR,T3_TW_NCU,T2_UA_KIPT,T2_PK_NCP,T2_IN_TIFR,T3_UK_London_UCL,T3_US_Brown,T3_CO_Uniandes,T3_KR_KNU,T2_FR_IPHC,T3_US_OSU,T3_US_TAMU,T1_US_FNAL,T2_IT_Rome,T2_UK_London_Brunel,T3_IN_PUHEP,T2_US_Vanderbilt,T2_EE_Estonia,T3_UK_ScotGrid_ECDF,T2_CN_Beijing,T2_US_Florida,T3_CH_CERN_HelixNebula,T3_IT_MIB,T3_US_FNALXEN,T3_US_Rutgers,T1_DE_KIT,T3_IR_IPM,T2_US_Wisconsin,T2_HU_Budapest,T2_DE_RWTH,T2_BR_SPRACE,T3_UK_SGrid_Oxford,T3_US_NU,T3_US_NERSC,T2_BR_UERJ,T3_MX_Cinvestav,T3_US_FNALLPC,T3_US_UIowa,T3_IT_Firenze,T3_US_Cornell,T2_ES_IFCA,T3_US_UVA,T3_ES_Oviedo,T2_DE_DESY,T1_UK_RAL,T3_HU_Debrecen,T2_US_Caltech,T3_FR_IPNL,Many_More', 'ApplicationVersion': 'CMSSW_7_1_19', 'localId': '', 'resubmitter': 'jfaulkne', 'tool': 'crab3', 'scheduler': 'GLIDEIN', 'broker': 'vocms052.cern.ch', 'jobId': '1_https://glidein.cern.ch/1/151026:230005:jfaulkne:crab:WWAToLNu2jA:4f:NLO:TuneCUETP8M1:13TeV-amcatnlo-pythia8_0', 'tool_ui': 'vocms052.cern.ch', 'StatusValue': 'pending', 'JSToolVersion': '3.3.0', 'user': 'jfaulkne', 'taskId': '151026_230005:jfaulkne_crab_WWAToLNu2jA_4f_NLO_TuneCUETP8M1_13TeV-amcatnlo-pythia8', 'taskType': 'analysis', 'CMSUser': 'jfaulkne', 'bossId': '1', 'vo': 'cms', 'datasetFull': '/WWAToLNu2jA_4f_NLO_TuneCUETP8M1_13TeV-amcatnlo-pythia8', 'exe': 'cmsRun', 'sid': 'https://glidein.cern.ch/1151026:230005:jfaulkne:crab:WWAToLNu2jA:4f:NLO:TuneCUETP8M1:13TeV-amcatnlo-pythia8', 'GridName': '/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jfaulkne/CN=742265/CN=James Anthony Faulkner', 'SubmissionType': 'crab3'}

**Comment by juztas** [comment]
Its not crab bug, but glideinwms of overflow. The same happens for T3_US_Tamu and Farrukh is aware of that. He can specify "config.Debug.extraJDL = ['+CMS_ALLOW_OVERFLOW=False']" and in this case overflow will not be taken into account.

**Comment by juztas** [comment]
Stefano, we had somewhere a ticket about what we should report for TargetSE. With current data locations, desired sites, whitelist, blacklist, crab3 blacklist in the end what I am always looking is the log file [1] in which you can see == JOB AD: DESIRED_SITES = "T3_US_FNALLPC,T2_CH_CERN". I would not call it a bug, but more improvement of TW log file.

It was private mail with debugging T3_US_Tamu and I will add you in that mail.
[1]
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0109.cern.ch/mon/cms082/151026_230005:jfaulkne_crab_WWAToLNu2jA_4f_NLO_TuneCUETP8M1_13TeV-amcatnlo-pythia8/job_out.1.0.txt

**Comment by belforte** [comment]
@juztas thanks
Indeed I could not open webdir last night (need ssh tunnel) and was not aware that TW log reports does not print what it puts in JDL :-(
It is anyhow a bug that target_se is reported to dashboard with the full list of all possible SE's. Should be the same string as in DESIRED_SItes.
Let's open an ad hoc issue for TW log.

IIUC the problem is that current overflow expression is triggered by any desired site to be of the form *_US_*, so having T3_US_FNALLPC there triggers overflow in the US region. That is actually the correct behavior.

What I do not like is that T3_US_FNALLPC is listed among PSN's.

**Comment by juztas** [comment]
for Target_SE: https://github.com/dmwm/CRABServer/issues/4521

for PSN's  it is longer discussion, but there might be a bug. So what was done 1 year that all sites who had PNN also have same PSN, with exceptions for T1.  And he added T3_US_FNALLPC, which as same PNN and PSN, but mapping of PNN -> PSN shows to add T1_US_FNAL. If T1_US would be in desired_sites, overflow expression also would be triggered.

**Comment by belforte** [comment]
I still do not see any way that T3_US_FNALLPC should appear as DESIRED_SITE, other then a bug.

**Comment by belforte** [comment]
Justas pointed out that T3_US_FNALLPC is in the PSN's list in SiteDB even if no PNN points to it.
Everything is understood.

**Comment by AndresTanasijczuk** [comment]
Let me comment about the TW log: 
1) What you see as "Locations" is the set of sites at which the block is available (or the set of all CMS sites in PrivateMC).
2) What you see as "Possible sites" is the set 1) if ignoreLocality == False. Otherwise is the set of all CMS sites.
3) What you see as "Resulting available sites" is the set 2) minus the sites that are blacklisted in the CRAB server. 
4) The set 3) is written into files "site.ad" and "site.ad.json" to the schedd. 
5) The user specified whitelist and blacklist are written into job ad attributes CRAB_SiteWhitelist and CRAB_SiteBlacklist.
6) Then it is the PreJob who applies to 4) the user specified blacklist and whitelist 5) and writes the result into the relevant condor attribute DESIRED_SITES. 
7) We do not apply the user specified blacklist and whitelist in the TW, because the whitelist and blacklist are allowed to change when the user resubmits jobs. So we have no other choice (I think) than applying them at PreJob level.
8) Of course we could still add a message in the TW log saying something like this: "The user specified whitelist is ... The user specified blacklist is ... CRAB will apply them at the pre-job stage. This will result in DESIRED_SITES = .... "

**Comment by belforte** [comment]
thanks Andres. So TW log is not enough to know the submission JDL. I need to keep that in mind.
THat said making a bit more clear what Possible and Resulting means is important. In the end both words are hints, but convey absolutely no information.
