### ISSUE TITLE
Put shutil.copy commands inside a try/except clause in PostJob code.

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5065]

**Comment by belforte** [comment]
handle exceptions nicely is good. But in particular with reference to the case you described in HN
 https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1115/1.html

what could do PostJob but declare a failure ?

**Comment by AndresTanasijczuk** [comment]
Was thinking about the same... I am not sure if post-job could consider this as a harmless failure and continue.

**Comment by belforte** [comment]
after revieweing, I think the only think that we may want to do is
"make sure that PostJob errors are reported to the user in a readable way".
Since error reporting is being rewritten by @emaszs let's close this and we'll see how it looks like in the new code.
