### ISSUE TITLE
double dash not supported in scriptArgs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5069]
it appears that jobType.pyCfgParams fails when one wants to pass to the pset parameterswhich need the --option=value syntax, i.e. this works
`jobType.pyCfgParams=["arg1=1", "arg2=2"] `
but this fails
`jobType.pyCfgParams=["--arg1=1", "--arg2=2"]`

see discussion in this thread
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/987/1/1/1/1.html

**Comment by belforte** [comment]
put a warning in
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile

**Comment by swertz** [comment]
Sorry to reopen this old issue, is there a reason why this was not implemented in the end for `jobType.scriptArgs`?

As noted in the HN the syntax `arg=value` is not really "standard" w.r.t. the standard argument parser libraries... plus if the job runs a custom script executable that is a simple bash script, just passing a simple list of arguments `["arg1", "arg2"]` would also be nice?
