### ISSUE TITLE
When resubmitting tasks in SUBMITFAILED, either ignore or give error message if --jobids is specified

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5070]
For a task in SUBMITFAILED status there were no jobs created, so the --jobids option makes no sense. If one specifies it, one currently gets an error message like this:

```
$ crab resubmit --jobids=1
...
The server answered with an error.
Server answered with: Execution error
Reason is: CRAB3 server refused to resubmit the following jobs: [1]. Only jobs in status ['failed'] can be resubmitted. Jobs in status ['finished'] can also be resubmitted, but only if the jobid is specified ...
```

**Comment by belforte** [comment]
but I guess `crab status` would have shown that there is no jobid=1 to resubmit, right ?

**Comment by AndresTanasijczuk** [comment]
yes, but in the current resubmission code this is equivalent as if jobs do exist but none is in 'failed' status.

**Comment by belforte** [comment]
not urgent then. A matter of avoiding question from users who do not read crab status output.
