### ISSUE TITLE
TaskWorker leaves task in QUEUED after resubmission

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5076]
this has happened both after successful resubmission and after failed resbmissions.

See examples from user reports:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1111/1/1/1/1/1.html
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1131/1/1/2.html

**Comment by belforte** [comment]
quite possibly connected with the fact that the number of tasks stuck in QUEUED in continuously growing in the DB, as shown in Kibana
https://cms-logbook.cern.ch/elog/Analysis+Operations/700

**Comment by belforte** [comment]
and very likely simply the same as discussed already months ago
https://github.com/dmwm/CRABServer/issues/4926
https://github.com/dmwm/CRABServer/issues/4082

**Comment by belforte** [comment]
Marco and Stefano had a long discussion today, in light also of the current Task Status Diagram picture prepared by Andres, and came to following conclusions. To be further reviewed with all before implementing:

1.
Slightly change status names to be more explanatory, we may not want to change
this everywhere in the code, but.. at least in our mind:

NEW --> NEWCOMMAND  meaning a new command has been issued for this task
HOLDING --> could not find a good new name here, this is a technical status only needed to allow a certain sequence of Oracle commands, it would not be needed if Oracle would return the list of changed tasks when we ask it to change 20 tasks from NEW to a different status 
QUEUED --> COMMANDQUEUED i.e. a new command is queued for being executed by some Task Worker subprocess

2.
store in the DB the command to be executed, this will be done at the time the task status is set to NEW

3.
we do not need anymore the status RESUBMIT and KILL

4.
when reporting status to users (crab status) we can then print things like
"command blah.. queued for execution on this task". Anyhow make it clear that SUBMITTED task still is SUBMITTED and jobs are being run etc. even if now the sever is busy resubmitting or killing a few failed jobs.

5. TaskMaster at startup should verify that no worker is running, then it can pick all QUEUED tasks which by definition are left-overs from previous uncomplete TM running and execute the QUEUED command on each. In the rare case that resubmit or kill are executed twice, so be it. We need to protect submit though, DagmanSubmitter must verify that schedd field is empty and if not check if task already exists on that schedd, see also 2) in #4082 

We have not checked yet what happens to dryRun and UPLOADED in the "new state diagram". I do not like that UPLOADED is seen as a fork in flow, I think UPLOADED is a natural status in the path from a newtask (which we need to keep different from newcommand !) to a SUBMITTED one. If one used --dryrun the TW stops at UPLOADED, otherwise goes on. But we need to discuss this.

**Comment by mmascher** [comment]
Fixed in https://github.com/dmwm/CRABServer/pull/5175 . I'm keeping this open in case of any discussion arises from the pull request.

**Comment by belforte** [comment]
AFAICT this was fixed by the new state machine implementation.,
