### ISSUE TITLE
crab report includes secondary files when reporting analyzed files/events

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5096]
Facts:
1) When reporting how many files/events have been processed, 'crab report' takes into account all the input files for which we have uploaded the FMD.
2) Since we upload the FMD for each and all the input files appearing in the FJR, and since the FJR includes primary as well as secondary input files, 'crab report' ends up counting the secondary files as well.
3) Secondary files which were not used by the job (because they don't contain any lumi that the job had to analyze) have "events: 0" in the FJR, so they do not affect the input event counting in 'crab report'. They do affect the counting of files that have been processed. Note that this would be fixed in this PR: https://github.com/dmwm/CRABServer/pull/5095. But if we conclude that CRAB should skip the upload of FMD for secondary input files, then that PR may be not necessary.

As @bbockelm pointed out in https://hypernews.cern.ch/HyperNews/CMS/get/edmFramework/3604.html, maybe we should just skip the secondary input files when processing the FJR. That means, not upload the FMD for secondary input files. I am not sure about that, as I don't know all the use cases of secondary input files. Aren't there cases where knowing some details (lumis, number of events, ...) of the analyzed secondary input files is important?

**Comment by belforte** [comment]
primary and secondary are only conventional names due to the way data
reading is organized. We must report all file names of files which contributed data.
The reason is that if a problem is found in file X, we want to know which other
file used its content.
Of course if a file contributed no data it is fine to avoid listing it in the FMD/parents,
even if it was included in some input list.

**Comment by bbockelm** [comment]
I'm fine if we track which input files were used in a job - for example for DBS registration.  However,
1.  We shouldn't be tracking run/lumi information from secondary files.  I think the framework will simply be removing this information as a 'fix'.
2.  We shouldn't report these as "files analyzed".  It makes no sense from a framework point of view.

The worst case I can think of: It should be possible to misconfigure a job such that, when the MixingModule is used, it reads an event from every event from the pileup dataset (so thousands of input files).  Are we prepared for such a case?

**Comment by belforte** [comment]
+1
let's rewrite:
list of analysed files/runs/lumis (e.g. for crab report) : comes from PRIMARY input
list of parent files for DBS : includes both primary and secondary files (if actually read)

**Comment by bbockelm** [comment]
That's also my understanding.

@ericvaandering @amaltaro @ticoann - what does WMAgent do when injecting to DBS?  Does it list the secondary files in the parentage of a given file?  Are there any other special considerations CRAB3 should make when doing this (is there a field to denote secondary input)?

**Comment by AndresTanasijczuk** [comment]
From the CRAB3 side: When publishing a file, all the input files appearing in the 'input' field of the corresponding 'output' part of the FJR are put in the 'file_parent_list' field (we use the `insertBulkBlock` DBS API). And from my example in https://github.com/dmwm/CRABServer/issues/5061, this 'input' field includes whatever CRAB3 has defined as input files in the pset. That means then that this PR https://github.com/dmwm/CRABServer/pull/5095 is now relevant no matter what we decide to do with the FMD of the input files.

**Comment by amaltaro** [comment]
I'm not sure I followed this question
>  Does it list the secondary files in the parentage of a given file?

For instance, I have a workflow reading RECO in the input, a RAW secondary dataset (IncludeParents) and it produces a RAW-RECO sample. 

So, the question is whether each RAW-RECO file in DBS has its parents (RECO files) _and_ the parents of these RECO files (RAW files)? If that's the question (I don't think so), then the answer is no.

**Comment by bbockelm** [comment]
@belforte - since WMAgent doesn't record both sets of inputs (this can be deduced through transitivity, no?), is there also an argument for not recording this in CRAB3?  Or should we argue that WMAgent is doing it wrong?

**Comment by belforte** [comment]
yes. things are trickier than I wrote. Alan is correcf that there there is no point in
listing parents of parents as additional parents (yes, we do believe in transitivity there).
OTOH I think if WMA does a pileup simulation it lists as parent both the signal and the min-bias 
files. Right ? Same if one does event mixing in general.

**Comment by bbockelm** [comment]
Hm - this is triggering some neurons.  Is pileup a secondary file?  I think it may not be, as there's no "primary" input to pair the events with...

(Does anyone have a FJR from a case like this?)

**Comment by belforte** [comment]
let's tale a breathing break and read the original incident !

**Comment by AndresTanasijczuk** [comment]
Maybe we should concentrate in this issue only about 'crab report' (as the issue subject says) and leave for another issue the discussion about publication.
About 'crab report', I am starting to think that the best we can do is to report separately how many files/events have been processed from primary sources and how many from secondary sources. By the way, does primary and secondary cover all the spectrum of input source types?

**Comment by bbockelm** [comment]
I would say never report files / events processed from secondary sources in `crab report`.

**Comment by AndresTanasijczuk** [comment]
@belforte Did you close this issue by mistake? Can you re-open it?

**Comment by belforte** [comment]
yup, was closed my missclick. reopeing

**Comment by belforte** [comment]
I agree with @bbockelm , sorry if I obfuscated the issue due to a misunderstanding, let's repeat:
   * list of analysed files/runs/lumis (e.g. for crab report) : comes from PRIMARY input
   * crab report contains the following run/lumi lists, all of which refer to the PRIMARY input dataset:
      * the input (primary input dataset AND lumimask AND runselection)
      * what was processed among those
      * the missed ones (i.e. difference of the above two, redundant since it can be obtained easily, but listed for users convenience)
      * the ones in failed jobs (i.e. running, growing copy of the above one, to allow user to sort of get started with resubmission)

**Comment by belforte** [comment]
labeled as BUG since in the end I can't see any reason to include run/lumis from secondary files in crab report. I do not know exactly what crab report does currently, but there are good chances that it is wrong.

**Comment by AndresTanasijczuk** [comment]
Fixed in https://github.com/dmwm/CRABServer/pull/5097
