### ISSUE TITLE
Local fallback stageout issues

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5101]
Andrew pinged me about his problems. So in summary: Job finishes on T2_US_UCSD, CRAB tries to do local stageout and fails with permission denied, after that comes fallback stageout, which can point to any other site (but usually nearest one) in this case Caltech and fallback stageout succeeds. CRAB uploads doc to couch in which it says that output is at UCSD. And of course FTS fails to transfer file as it does not exist.

do we want to do fallback stageout? 
    a) if yes, site reporting to ASO should be fixed.
    b) If not, CRAB should say that to WMCore not to do fallback stageout and in case of local stageout failures do remote. 

For example log file:
http://submit-4.t2.ucsd.edu/CSstoragePath/54/uscms3895/151204_113644:anlevin_crab_fr_muon_ntuples_v10000/job_out.138.0.txt

**Comment by belforte** [comment]
indeed the only way to deal with fallback stageout is that it is
fully transparent. I think we only have option a) and bump it to the
site to make it work or disable it. Of course CRAB must have proper
handshake with the site to send the correct site/PFN location to ASO !

**Comment by juztas** [comment]
This becomes problematic now...

**Comment by belforte** [comment]
OK, but the only fix a crab code change anyhow, right ?

**Comment by juztas** [comment]
I am checking it now which is the easiest way...

**Comment by juztas** [comment]
@mmascher, which tag of WMCore you used in new rpm release?

I still see issues, but after looking around, seems we are using too old WMCore version, which does not have this fix: 

Either apply this patch, or start new validation with WMCore version which WMA validated. 
https://github.com/dmwm/WMCore/commit/22db3d94f67a8025140669d9aec01ed10e1a1c5b

It is available in:
1.0.12 1.0.12.pre2 1.0.12.pre1 1.0.12.patch1 1.0.11 1.0.11.pre8 1.0.11.pre7 1.0.11.pre6 1.0.11.pre5 1.0.11.pre4 1.0.11.pre3 1.0.11.pre2

Please re-poen...

**Comment by AndresTanasijczuk** [comment]
For CRAB @mmascher is using https://github.com/mmascher/WMCore/tree/3.3.1510 I think

**Comment by mmascher** [comment]
I am using https://github.com/mmascher/WMCore/tree/3.3.1511 which is based on 1.0.9.pre4. It's on my (immediate) todo list to update to a new WMCore :)

Maybe it's better to apply it on top of my WMCore this time. I'll prepare and RPM for tomorrow morning

**Comment by juztas** [comment]
I guess we are short on time, What I would suggest to do is during creation of RPM patch WMCore storage plugins and do not do any fallback stageout (comment it out or add if False:). In that case we are good. To validate full WMCore might take much more time and it can be fragile to do before vacations...

**Comment by mmascher** [comment]
Done, I pinged you an @jmarra13 in private
