### ISSUE TITLE
retry with timeouts upload of filemetadata

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5102]
better to retry up to N (maybe 3) times with timeouts
```
Sun, 06 Dec 2015 21:19:43 CET(+0000):DEBUG:PostJob Uploading file metadata for input file /store/data/Run2015D/DoubleEG/MINIAOD/PromptReco-v3/000/257/805/00000/DE055B16-CE68-E511-906C-02163E01291F.root
Sun, 06 Dec 2015 21:20:57 CET(+0000):ERROR:PostJob Fatal error uploading input files metadata: (35, 'Unknown SSL protocol error in connection to cmsweb.cern.ch:443 ')
Traceback (most recent call last):
  File "TaskWorker/Actions/PostJob.py", line 1556, in execute_internal
    self.upload_input_files_metadata()
  File "TaskWorker/Actions/PostJob.py", line 1830, in upload_input_files_metadata
    self.server.put(self.rest_uri_no_api + '/filemetadata', data = urllib.urlencode(configreq))
  File "RESTInteractions.py", line 75, in put
    return self.makeRequest(uri = uri, data = data, verb = 'PUT')
  File "RESTInteractions.py", line 113, in makeRequest
    capath=caCertPath)#, verbose=True)# for debug
  File "WMCore/Services/pycurl_manager.py", line 158, in request
    curl.perform()
error: (35, 'Unknown SSL protocol error in connection to cmsweb.cern.ch:443 ')
Sun, 06 Dec 2015 21:20:57 CET(+0000):INFO:PostJob ====== Finished upload of input files metadata.
```

**Comment by belforte** [comment]
It used to be a mantra: every remote service may fail or hang,
any operation needs to be done inside a timeout wrapper and
retried with exponential backoff. Sounds the praying was stopped
too soon :-(

On 12/06/2015 10:36 PM, Justas Balčas wrote:
> better to retry up to N (maybe 3) times with timeouts

Best is to have a general utility to handle timeout and retry
and reuse it everywhere. Does any such one exist in the code base now ?

**Comment by juztas** [comment]
yes,  it is in WMCore. just need to pass value to it.

**Comment by juztas** [comment]
Mh.. it is already configured to retry on some error codes, but not this one. So for future I would add more debug info. Not good to retry blindly also.


https://github.com/dmwm/CRABServer/blob/master/src/python/RESTInteractions.py#L110

**Comment by mmascher** [comment]
I think this is a `pycurl.error` and we probably need to add `pycurl.error` in addition to `except HTTPException` to the code you posted. The difference is that HTTPExceptions are proper errors returned by the cmsweb frontend, pycurl.errors happens when we are not even able to get in contact with the frontend. Makes sense to retry also the latter.
