### ISSUE TITLE
improve error message on illegale output file names

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5105]
When output file name indicated in crab config fails the regexp check, a proper message should be reported by server. See:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1194/1.html

according to Marco this requires a small change in
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L381
i.e. adding a `custom_error` as now supported in
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Validation.py#L106
etc.

 There are actually several parameter checks done when submitting to the REST for which a better message can be returned, all in RESTUserWorkflow.py

**Comment by mmascher** [comment]
This is one of the error that https://github.com/dmwm/CRABServer/issues/4588 should fix
