### ISSUE TITLE
review recent transfer problems with user files

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5106]
see this mail from Justas and references in there
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2464.html

Some of that but not all was covered in last CRAB dev. meeting
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2466/1/1/1.html
 but we should understand and solve for good all issues there

**Comment by juztas** [comment]
4 separate issues created. This can be closed.
https://github.com/dmwm/CRABServer/issues/5112
https://github.com/dmwm/CRABServer/issues/5113
https://github.com/dmwm/CRABServer/issues/5114
https://github.com/dmwm/CRABServer/issues/5115

**Comment by mmascher** [comment]
Too bad github does not allow to group issues and break down in subissues
