### ISSUE TITLE
Set an appropriate limit in the CRAB3 JDL for Disk usage

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5113]
Currently it is 100GB. SystemPeriodicRemove kills job after 27GB, so our should be lower if we want to catch it.
Also RetryJob can check classad values for diskUsage, Memory usage and see if user exceeded it.

**Comment by belforte** [comment]
periodic remove kills at 20GB now, which is is safely below the minimum that CMS requires.
I think that's enough.
https://github.com/dmwm/CRABServer/commit/cb1e579464fed8e87c2944dc30174802743dc078
