### ISSUE TITLE
Improve reporting to Dashboard

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5117]
For example: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=default&refresh=0&table=Jobs&p=5&records=25&activemenu=2&status=&site=&tid=151210_162047%3Adgulhan_crab_20151210_172035

This makes harder for us to debug, if exit code is 0, which should be 60302. We need to talk with dashboard people and to know how this can be improved.

**Comment by belforte** [comment]
improvements, if any, can only happen in new monitoring based on CERN MONIT... whenever it will happen
