### ISSUE TITLE
cmscp should not use fallback PNN when it used direct stagetout protocol

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5124]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1226/1/2.html

cmscp (or whatever) used the local stage out destination, but there was no PNN indicated in the conifg, so it picked the PNN from the fall-back section of the configuration file.

**Comment by mmascher** [comment]
Tracing this back I can see there is a wrong value in the fjr: http://submit-4.t2.ucsd.edu/CSstoragePath/77/uscms5953/160105_225617:sethzenz_crab_1_1_0_MuonEG_Run2015D-PromptReco-v4_00/job_fjr.5.0.json

```json
{

    "task": null,
    "skippedFiles": [ ],
    "phedex_node": "T2_UK_London_IC",
    "exitMsg": "OK",
    "executed_site": "T2_UK_London_Brunel",
    "aso_start_timestamp": ​1452048379,
    "postjob": 

```

**Comment by mmascher** [comment]
Which in turn comes from: https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L965-L968

Interestingly enopugh trying the WMCore code on vocms052 (sourcing `source /data/srv/TaskManager/env.sh`) I can see that T2_UK_London_IC is not picked up from the SLC[1]. Is there the remote chance that the siteconfig used on the worker node is not the one I can see in cvmfs? Otherwise I am a bit lost with this.

[1]
```python
import WMCore.Storage.SiteLocalConfig as SiteLocalConfig
import os
os.environ['CMS_PATH'] = '/cvmfs/cms.cern.ch'
os.environ['WMAGENT_SITE_CONFIG_OVERRIDE'] ='/cvmfs/cms.cern.ch/SITECONF/T2_UK_London_Brunel/JobConfig/site-local-config.xml'
slc = SiteLocalConfig.loadSiteLocalConfig()
slc.localStageOut
{'catalog': 'trivialcatalog_file:/storage/for/exp_software/cms/SITECONF/local/PhEDEx/storage.xml?protocol=srmv2', 'command': 'srmv2-lcg', 'option': '-Dsrmv2 -b', 'se-name': 'dc2-grid-64.brunel.ac.uk'}
```

**Comment by belforte** [comment]
yes there is such a remote chance, in case the site does not use the file out of CVMFS.
I do not remember if Brunel does it. But will try to check.

**Comment by belforte** [comment]
and indeed :-(
http://wlcg-sam-cms.cern.ch/dashboard/request.py/metricOutput?host=dc2-grid-21.brunel.ac.uk&time=2016-01-07T13:01:31Z&metricfqan=org.cms.WN-basic%20%28/cms/Role_lcgadmin%29

that was yesterday, today SAM reports agreement between local copy and GIT
http://wlcg-sam-cms.cern.ch/templates/ember/#/historicalsmry/heatMap?flavours=ARC-CE%2CCREAM-CE&group=Tier2s&metrics=org.cms.WN-basic%20%28%2Fcms%2FRole_lcgadmin%29&profile=CMS_CRITICAL_FULL&site=T2_UK_London_Brunel&view=Test%20History

Although it is possible that a few WN's only were/are affected.
Indeed if the local file indicates the wrong PNN, we are helpless. Let's close this and I'll open a GGUS for site admins.
