### ISSUE TITLE
unzip in resubmit leads to EOF failure

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5126]
From condor_stderr 
```
+ unzip CRAB3.zip
replace RESTInteractions.py? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
```
```
Jan 12 11:34:18 vocms0109 abrtd: Directory 'pyhook-2016-01-12-11:34:18-1875660' creation detected
Jan 12 11:34:19 vocms0109 abrtd: Executable '/data/srv/glidecondor/condor_local/spool/2887/0/cluster2582887.proc0.subproc0/TaskWorker/TaskManagerBootstrap.py' doesn't belong to any package and ProcessUnpackaged is set to 'no'
Jan 12 11:34:19 vocms0109 abrtd: 'post-create' on '/var/spool/abrt/pyhook-2016-01-12-11:34:18-1875660' exited with 1
Jan 12 11:34:19 vocms0109 abrtd: Deleting problem directory '/var/spool/abrt/pyhook-2016-01-12-11:34:18-1875660'
```

Need to change unzip to unzip -o to force overwrite.

**Comment by mmascher** [comment]
Do you have the taskname? I want to check if it was submitted twice..

**Comment by mmascher** [comment]
All in all I think the PR can be merged. That said I would keep the isse open and rename it to something like: "dag_bootstrap_startup.sh should detect that a task has already been submitted"

Something like let's do something like:
```
if exit_code==0:
    touch submitted_to_dagman
```

and at the beginning of dag_bootstrap_startup.sh let's check if this file exist. Then using `-o` in unzip or not becames less important imho.

Also, we nprobably need to better handle "bootstrap failures", so when the job gets submitted to the schedd but not to dagman. In this case crab3 would think everything is successfull.

Thoughts?
