### ISSUE TITLE
crab report became VERY slow

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5130]
following up on user report
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1264.html

For this short task 160115_154041:aapopov_crab_Wjets
I did a crab remake  [2]
and then tested crab report.

crab report is taking 1h according to user. I gave up after 5min.
But using July version of the client it completes in a few seconds [1]

IIRC crab report was possibly using the wrong input (full dataset from DBS rather
then list of input runlumi to the tasks) but was otherwise working, so I suspect in some
fix introduced in the summer something went wrong.

[1]
belforte@lxplus0074/andrey> which crab
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1507/bin/crab
belforte@lxplus0074/andrey> time crab report -d crab_Wjets/
1615 files have been processed
72207128 events have been read
0 events have been written
Analyzed luminosity sections written to /afs/cern.ch/work/b/belforte/CRAB3/TC3/andrey/crab_Wjets/results/lumiSummary.json
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/andrey/crab_Wjets/crab.log

real	0m8.325s
user	0m4.751s
sys	0m0.874s
belforte@lxplus0074/andrey> 

[2]
belforte@lxplus0010/andrey> crab status -d crab_Wjets/
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/andrey/crab_Wjets
Task name:			160115_154041:aapopov_crab_Wjets
Grid scheduler:			crab3test-3@vocms096.cern.ch
Task status:			COMPLETED
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=160115_154041%3Aaapopov_crab_Wjets

Jobs status:			finished      100.0% (324/324)

No publication information (publication has been disabled in the CRAB configuration file)
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/andrey/crab_Wjets/crab.log
belforte@lxplus0010/andrey>

**Comment by juztas** [comment]
It is already solved. I double checked same task with pdb and with current release it is stuck, with previous works fine and with new crab release works also fine:
```
$ time crab report crab_Wjets/
Warning: Incompatible CRABClient version development
Server is saying that compatible versions are: ['3.3.1506', '3.3.1507', '3.3.1509', '3.3.1510', '3.3.1511', '3.3.1512', '3.3.1512.rc2']
1615 files have been processed
72207128 events have been read
0 events have been written
Analyzed luminosity sections written to /afs/cern.ch/user/j/jbalcas/crab_Wjets/results/lumiSummary.json
Log file is /afs/cern.ch/user/j/jbalcas/crab_Wjets/crab.log

real	0m10.280s
user	0m6.778s
sys	0m0.780s
```
Ended in same location and fix is here and it is in upcoming crab client release: https://github.com/dmwm/CRABClient/commit/4aa5a09c1b2e395d079b412338ead112e8363265

**Comment by belforte** [comment]
thanks Justas !!
