### ISSUE TITLE
resubmit should check stageout before resubmitting 

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5132]
I noticed this not with one user, but with multiples. They are blindly resubmitting (or using scripts to do that) and not chekcing what issues are.

During resubmit CRAB3 could check stageout is it ok, if permanent failure got, there is no reason to resubmit. Also it should check if destination site is blacklisted or not. For example: https://lcgfts3.gridpp.rl.ac.uk:8449/fts3/ftsmon/#/?vo=&source_se=&dest_se=srm:%2F%2Fcms-0.mps.ohio-state.edu&time_window=1

One site due to network card driver problems most of the transfers were failing, fts was lowering number of active transfers and user was resubmitting several times. This added a huge backlog to FTS queue and it might take some time to finish.  Also last few days he resubmitted again and this leads to add new file transfers to the end. But seems there are ~300K fts docs pending, which will take more than 24h, which will lead to job failures.

**Comment by juztas** [comment]
@belforte assign to me and for next release.

**Comment by belforte** [comment]
I think it was done. In any case we are happy with the current level of checking
