### ISSUE TITLE
T2_TW_NCHC is not accepted as valid destination

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5139]
see mail exchange below in HN:

Looking at SiteDB there is not T2_TW_NCHC PhEDEx Node, is that correct ?
Curiosity aside (first case of a disk-less T2), it may be that the way
CRAB looks up the list of sites does not work in this particular case
and it may have to be changed.
We will look into this.
Stefano

On 02/01/2016 10:05 AM, Yuan Chao wrote:
>
> *** Discussion title: Computing Tools
>
> Dear experts,
>
>    We are having a new site TW_NCHC to support CMS in Taiwan. Currently it has been tested on grid functionalities as a T3 site and we are promoting it as a T2. However, we are having problem submitting jobs via crab3.
>
> Though we've asked to add it into the glidein factory (https://ggus.eu/index.php?mode=ticket_info&ticket_id=119053), crab3 still can't recognize it as a valid site:
>
> Sending the request to the server
> The server answered with an error.
> Server answered with: Invalid input parameter
> Reason is: The parameter T2_TW_NCHC is not in the list of known CMS sites [u'T3_BY_NCPHEP', u'T2_IT_Bari', u'T3_US_Baylor', u'T2_CN_Beijing', u'T3_IT_Bologna', u'T2_UK_SGrid_Bristol', u'T3_US_Brown', u'T2_UK_...
> Error Id: 1f041b239e8bbc9b1195bc0cc7ac58bb
> Log file is /wk_cms/yuanchao/cms/CMSSW_7_4_1_patch4/src/crab_projects/crab_TTbarFCNC_cZpbW_PY6_13TeV_DIGI-2-/crab.log
>
> I also checked the crab version used, though the error should be from the server side as shown in the message.
>
> $ ls -l /cvmfs/cms.cern.ch/crab3/crab.csh
> lrwxrwxrwx 1 314 314 89 Dec  3 20:22 /cvmfs/cms.cern.ch/crab3/crab.csh -> /cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.1512/etc/profile.d/init.csh
>
> I checked that 'processing' attribute on siteDB is added. So I'm wondering what's still missing to be in the "known CMS sites list".
>
> Thanks a lot in advance.
>
> ---
> Regards,
> Yuan CHAO
>
> -------------------------------------------------------------
> Visit this CMS message (to reply or unsubscribe) at:
> https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1287.html
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by juztas** [comment]
Did you tried to submit a task? CRAB looks correctly to list of sites.
Problem which I foresee for disk-less sites is HC.
```
$ crab status
Warning: Incompatible CRABClient version 3.3.1602.rc3
Server is saying that compatible versions are: ['3.3.1506', '3.3.1507', '3.3.1509', '3.3.1510', '3.3.1511', '3.3.1512', '3.3.1512.rc2']
CRAB project directory:		/afs/cern.ch/work/j/jbalcas/VALIDATE/HG1509a/CMSSW_7_0_6/src/site-test/crab_NCHC-test
Task name:			160201_115243:jbalcas_crab_NCHC-test
Task status:			SUBMITFAILED
Warning:			The following sites from the user site whitelist are blacklisted by the CRAB server: ['T2_TW_NCHC']. Since the CRAB server blacklist has precedence, these sites are not considered in the user whitelist.
Failure message:		The CRAB server backend refuses to send jobs to the Grid scheduler. You put ['T2_TW_NCHC'] as site whitelist, but the input dataset 'None' can only be accessed at these sites: [u'T3_US_PuertoRico', u'T2_FI_HIP', u'T2_UK_SGrid_RALPP', u'T2_FR_GRIF_LLR', u'T3_IT_Trieste', u'T3_US_Omaha', u'T2_KR_KNU', u'T3_US_UMD', u'T3_US_Colorado', u'T3_NZ_UOA', u'T2_IT_Bari', u'T3_US_HEPCloud', u'T2_US_UCSD', u'T1_RU_JINR', u'T3_US_Vanderbilt_EC2', u'T2_RU_IHEP', u'T2_CH_CERN', u'T2_US_Vanderbilt', u'T3_GR_Demokritos', u'T3_US_UTENN', u'T3_US_UCR', u'T3_TW_NCU', u'T2_CH_CSCS', u'T2_UA_KIPT', u'T2_PK_NCP', u'T3_US_Brown', u'T3_KR_KNU', u'T2_FR_IPHC', u'T3_US_OSU', u'T3_US_TAMU', u'T1_US_FNAL', u'T2_IT_Rome', u'T2_UK_London_Brunel', u'T3_US_OSG', u'T3_US_TTU', u'T2_EE_Estonia', u'T2_IN_TIFR', u'T2_CN_Beijing', u'T2_US_Florida', u'T3_CH_CERN_HelixNebula', u'T3_IT_MIB', u'T3_US_Rutgers', u'T1_DE_KIT', u'T2_US_Wisconsin', u'T2_HU_Budapest', u'T2_DE_RWTH', u'T2_BR_SPRACE', u'T3_UK_SGrid_Oxford', u'T3_US_NERSC', u'T2_BR_UERJ', u'T3_MX_Cinvestav', u'T3_US_UIowa', u'T3_IT_Firenze', u'T3_US_Cornell', u'T2_ES_IFCA', u'T3_US_UVA', u'T2_DE_DESY', u'T1_UK_RAL', u'T3_HU_Debrecen', u'T2_US_Caltech', u'T3_FR_IPNL', u'T2_UK_London_IC', u'T2_US_Nebraska', u'T2_ES_CIEMAT', u'T3_IT_Perugia', u'T1_IT_CNAF', u'T3_US_Minnesota', u'T2_AT_Vienna', u'T2_US_Purdue', u'T3_HR_IRB', u'T2_BE_UCL', u'T3_US_FIT', u'T2_UK_SGrid_Bristol', u'T2_PT_NCG_Lisbon', u'T1_ES_PIC', u'T2_IT_Legnaro', u'T3_US_SDSC', u'T3_US_FIU', u'T2_RU_JINR', u'T2_IT_Pisa', u'T2_GR_Ioannina', u'T3_US_Princeton_ARM', u'T3_US_UCSB', u'T1_FR_CCIN2P3', u'T2_FR_GRIF_IRFU', u'T3_US_UMiss', u'T2_FR_CCIN2P3', u'T2_US_MIT', u'T2_BE_IIHE', u'T2_RU_INR', u'T2_PL_Swierk', u'T3_IT_Bologna']. Please check your site whitelist.
```
And site is not usable automatically because of HC.

**Comment by mmascher** [comment]
thanks Justas
