### ISSUE TITLE
check for dead posJobs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5142]
see #4082
3) The PostJob script should update the file state timestamp once every N minutes (N=15?); if there has been no updates in 3*N minutes, mark the job as failed.

**Comment by belforte** [comment]
let's review once task process is working and postjob role is much decreased

**Comment by emaszs** [comment]
Could someone clarify what problem we're trying to solve here, or if there even is such a problem anymore? To check if the PostJob is somehow hung on some part of the code is an interesting problem, but not something that has a clear solution I don't think.

**Comment by belforte** [comment]
the problem is exactly to detect situations where postJobs get hung.
It is certainly true that this did not happen in recent times. But it is part of a good tool to have this king of self-diagnosing capability to lessen the need for someone to check things periodically.
It is surely not an urgent topic given that current PostJobs run nicely (other then things like bad CEPH volumes which we notice anyhow).
Maybe we can generalize as:
Task Process should detect if task status is not updateded for abnormaly long time. I can't say what is abnormal, but i we can imagine to start with things as simple as "no update in 24h" and refine checks as we hit things.
I thik the mileston here refers more to review what TaskProcess does vs. what PostJob does then to implementing any specific final solution.

**Comment by emaszs** [comment]
To summarize, while this would be nice to have, my view is that this is something hard to achieve and not worth the effort knowing that the PostJobs don't seem to die randomly.
