### ISSUE TITLE
Rest config move from git.cern.ch to gitlab.cern.ch

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5144]
See: https://indico.cern.ch/event/461084/contribution/9/attachments/1223470/1791795/VCS_update_for_ITUM_Feb_2016.pdf

```
Phasing out git.cern.ch
• No new repo since September 2015
• Propose to shut down git.cern.ch by end
September 2016
• No new repository allowed from now on
• Voluntary migration in progress: KB0003111
• git.cern.ch to be Read-Only as of end June

```

**Comment by AndresTanasijczuk** [comment]
Remember to change the documentation in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabRESTInterface

**Comment by belforte** [comment]
was all done by @jmarra13 long ago
