### ISSUE TITLE
crab status --long on backend takes too much time

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5147]
If there is a big task submitted, crab3 backend takes more than 5 minutes to process all the log files and return the output back to the client.
For example, this task during that time had to download ~260MB and calculate all the output back to client. Tried to do simple curl/wget and it was less than 2s to download files.

Leaving user for 5 minutes without any response back what it is doing is not good. Whenever connection is open, server can talk back with the client and report the status. Of course this is not easy to do in current implementation.

Real issue is to overlook which function is taking most time and improve it to respond faster. 
Connection is closed by frontend and we are out of knowledge there it was stuck. Another implementation could be to stop function before cmsweb frontend and report where it was stuck. 

https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1328.html

**Comment by belforte** [comment]
we should not process 10k log files on the fly :-(

**Comment by belforte** [comment]
and should not do intensive/extensive operations in the cmsweb frontend, where we have no direct access and can't change things quickly.

**Comment by belforte** [comment]
basically we should review status --long

**Comment by juztas** [comment]
it is not processing 10k log files. it is just processing 4 files . About intensive/extensive operation I think @mmascher can agree with me, that client has to be lightweight and for this command there is nothing else where to move it.

**Comment by belforte** [comment]
Why does it download more than 250MB then ?
Client has to stay light of course, but we could use postjobs to keep uptodate a file
with the needed info. And we may also discover that crab --long prints too much or only makes sense 
if issued for one job at a time. Pulling back hundreds of MB's to the client is hardly useful.
Also, now that we have http connection to the schedd's, we can have the client pull
the status file directly from there.

**Comment by juztas** [comment]
` this task during that time had to download ~260MB and calculate all the output back to client.`
which means backend had to download and calculate and return only json to client
Here are more details and we had also some discussions `condor_q` vs `download file and parse locally`: 
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py

**Comment by belforte** [comment]
this is now being worked on by @emaszs

**Comment by belforte** [comment]
Let's imagine that by August release this is if not in production at least 'done' to the level that we have specific issues, rather than a general "let's do it"

**Comment by belforte** [comment]
the new task status is something we do w/o need to have this issue open
