### ISSUE TITLE
CRABServer web interface can get confused.

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5153]
from @PerilousApricot  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1346.html
```
Hello,

Poking around at some tasks, I followed a link to:

https://cmsweb.cern.ch/crabserver/ui/task/160212_041411:meloam_crab_v9_DYJetsToLL_M-50_TuneZ2Star_8TeV-madgraph-tarball_gurrola-DYJetsToLL_M-50_0jSkimPat

Clicking over to the "config" tab it shows the config for a different
task (still from my user, just not the task it was supposed to be),
however.

Figure'd I'd point it out.

Thanks,
Andrew
```

I suspect this is related to the known problem of non-uniqueli named sandbox in UFC. But I do not know the mechanism enough to be sure

**Comment by mmascher** [comment]
Exactly Stefano, we calculate the hash of the sandbox using this function: https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/UserFileCache/UserFileCache.py#L18-L77

The point is that certain files (including the `crabConfig.py`, the `debug` directory) are not taken into account since they are not actually used for run the job, but may cause the sandbox to be different and not recycled. `PSet.pkl` is another of such files (this time used on the WN)

**Comment by belforte** [comment]
something like we create and store in UFC two different sandboxes with the same hash
so the second overrides the first ?
And this sandbox is only used by dryrun and crabserver ui ?

**Comment by mmascher** [comment]
Yes, something like that (I don't remember if we actually avoid to upload the sandbox or overwrite, but the result is the same)
This is the actual sandbox sent to the schedd and eventually to the WNs. The sandbox for the dryrun is a different one.

**Comment by belforte** [comment]
?? do we send the wrong sandbox to the schedd and WMs ?

**Comment by mmascher** [comment]
The sandbox content is the same (the debug directory does not matter for
the execution of the job). It's for the crab library when you send
identical sandboxes with different parameters (e.g.: input dataset)

On Mon, Feb 22, 2016 at 10:29 AM, Stefano Belforte <notifications@github.com

**Comment by belforte** [comment]
simply to note down that I reviewed and still looks there is something to change in the crab monitor page. like pset and config are taken from a common /recycled sandbox rather then from the schedd.  Somehow a better naming of sandboxes and possibly splitting the libs from the config could be a more clear solution.
Still in @emaszs hands.
