### ISSUE TITLE
typo in HTCondorDataWorkflow.py line 344

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#5159]
this line

`res['dbsInLimilistNewClientOldTask'] = LumiList(runsAndLumis=_compactLumis(inputDetails)).getCompactList()`

should be

`res['dbsInLumilistNewClientOldTask'] = LumiList(runsAndLumis=_compactLumis(inputDetails)).getCompactList()`

**Comment by belforte** [comment]
maybe was done and only need closing ?

**Comment by emaszs** [comment]
Typo doesn't exist anymore.
