### ISSUE TITLE
CrabMonitor fails to find TW log

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5167]
I was looking at this user's task
160307_183013:sbreeze_crab_run260627_zb
which is in SUBMIT FAILED
crab monitor page is
https://cmsweb.cern.ch/crabserver/ui/task/160307_183013:sbreeze_crab_run260627_zb
Main, TaskInfo and Upload log tabs work as expected, but TaskWorker log returns
```
x-error-http: 400
x-error-detail: required object is missing
x-error-id: 716e1b76f76983cd22ec7cc072798625
x-rest-status: 303
x-error-info: not such file
```
but the file is actually there on the TW machine:
```
belforte@vocms052/~> ls -l /data/srv/TaskManager/current/logs/tasks/sbreeze/160307_183013:sbreeze_crab_run260627_zb.log
-rw-r--r--. 1 crab3 zh 2540 Mar  7 19:35 /data/srv/TaskManager/current/logs/tasks/sbreeze/160307_183013:sbreeze_crab_run260627_zb.log
belforte@vocms052/~> 
```
is this a defect in the monitor page, or ???

In other cases TWlog is present even if submission failed

**Comment by emaszs** [comment]
@belforte I personally don't see the sbreeze folder. It shouldn't be deleted automatically this soon, right? Also, the monitoring just uses the logfile API [1] which doesn't have much in terms of settings and usually works fine, so I don't see what could be wrong from the mon's perspective. Maybe the API itself malfunctioned?

[1] https://cmsweb.cern.ch/crabcache/logfile?name=160307_215226:bundocka_crab_run260627_SM_emu_TaskWorker.log&username=bundocka

**Comment by juztas** [comment]
This issue and this: https://github.com/dmwm/CRABServer/issues/5168 are connected. If TW fails in MyProxyLogon and in case we do not have users proxy, we cannot upload log file to crabcache. Solution which I see would be to use service cert&key if users proxy is not available.

**Comment by emaszs** [comment]
Got it, that makes sense. Thanks.

**Comment by belforte** [comment]
indeed if we rely on "something" to upload task log file to crabcache, a zilion things could go 
wrong :-(
let's reassign to Marco to get the description of how it is supposed to work

**Comment by belforte** [comment]
OK. no need for Marco :-)
by the way the directory  /data/srv/TaskManager/current/logs/tasks/sbreeze is iindeed gone. Maybe those are cleaned as soon as log is uploaded to crabcache ?

**Comment by juztas** [comment]
Boh... Just for reference  https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Handler.py#L133

**Comment by juztas** [comment]
Nop, this directory exists. current is a symlink only to current release and Jadir redeployed today a TW which has a different tag

**Comment by belforte** [comment]
ah !! THat explains a lot! I had seen this disappearance earlier as well, now I understand.
Had forgotten that ../current/.. can move around

**Comment by belforte** [comment]
Bottom line:
change https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Handler.py#L133 to use hostcert instead of user proxy

**Comment by belforte** [comment]
in the end this is invalid. Log 'disappears' when TW is upgraded.

**Comment by mmascher** [comment]
Indeed I suggested @jmarra13 to use a "shared" directory for logs instead of a directory inside current that changes every release (i.e.: start the TW one directory above)

**Comment by jmarra13** [comment]
@mmascher and @belforte, I changed env.sh and start.sh to preserve the log folder after  new installations.

**Comment by belforte** [comment]
thanks @jmarra13 do those changes need to be saved in .. ? git  ? twiki ?

**Comment by jmarra13** [comment]
Those scripts are on the TW since ever I guess, but we can create a new folder on crabserver repo only for shell scripts and put there.

**Comment by belforte** [comment]
for the time being should be enough to update in here: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabTaskWorker#Start_stop_the_TaskWorker
