### ISSUE TITLE
Incomplete error_summary files returned to crab status

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5170]
I happen to submit a big task (10k jobs) that produced a lot of failed jobs, and consequently a big `error_summary.json` file.

During the `crab status` this file is retrieved from the schedd where the file is exposed using httpd. I observed that getting the complete file was basically impossible, and despite my several retries I was only getting a partial file. The worst part of this was that I was not even able to kill my task since the kill relies on the status ant it was repetadly failing. Weirdly enough apache httpd was sospiciusly answering with 200.

After stracing httpd[2] I found out that the `sendfile` linux kernel syscall is used to stream the file over TCP, and quoting the man page of the syscall[1] it may happen that the syscall does not read the whole file:

```
       If the transfer was successful, the number of bytes written to out_fd
       is returned.  Note that a successful call to sendfile() may write
       fewer bytes than requested; the caller should be prepared to retry
       the call if there were unsent bytes.
[...]
       If out_fd refers to a socket or pipe with zero-copy support, callers
       must ensure the transferred portions of the file referred to by in_fd
       remain unmodified until the reader on the other end of out_fd has
       consumed the transferred data.
```

So, IMHO httpd is missing the check about the file being sent completely, and it thinks the whole file has been transfered since sendfile exits with something different than 0. The reason why sendfile does not read the whole file is that we are constantly truncating and rewriting the file in the postjob. Originally we were synchronizing using file movement, but this was a changed and we started using a lock because of this https://github.com/dmwm/CRABServer/issues/4780#issuecomment-97609793

After a quick chat with @belforte we agreed to keep the strategy synching using the lockfile (call it error_summary.lock), but to go back to each postjob writing to its own error_summary.pid.json that is moved over error_summary.json before releasing the lock.

[1] http://man7.org/linux/man-pages/man2/sendfile.2.html
[2]

```
accept4(5, {sa_family=AF_INET6, sin6_port=htons(62421), inet_pton(AF_INET6, "::ffff:128.141.136.55", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28], SOCK_CLOEXEC) = 10
getsockname(10, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::ffff:169.228.38.37", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 0
fcntl(10, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(10, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
read(10, "GET /CSstoragePath/52/uscms3685/160308_151028:mmascher_crab_test_marprod_2/error_summary.json HTTP/1.1\r\nHost: submit-4.t2.ucsd.edu\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:44.0) Gecko/20100101 Firefox/44.0\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3\r\nAccept-Encoding: gzip, deflate\r\nCookie: _ga=GA1.2.852900990.1446020675\r\nDNT: 1\r\nConnection: keep-alive\r\nRange: bytes=2539520-\r\nIf-Range: W/\"972e0b-b5f829-52d8cec061e04\"\r\nCache-Control: max-age=0\r\n\r\n", 8000) = 552
stat("/home/remoteGlidein/52/uscms3685/160308_151028:mmascher_crab_test_marprod_2/error_summary.json", {st_mode=S_IFREG|0644, st_size=11936388, ...}) = 0
open("/home/remoteGlidein/52/uscms3685/160308_151028:mmascher_crab_test_marprod_2/error_summary.json", O_RDONLY|O_CLOEXEC) = 11
fcntl(11, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
fcntl(11, F_SETFD, FD_CLOEXEC)          = 0
setsockopt(10, SOL_TCP, TCP_CORK, [1], 4) = 0
writev(10, [{"HTTP/1.1 200 OK\r\nDate: Tue, 08 Mar 2016 17:29:33 GMT\r\nServer: Apache/2.2.15 (CentOS)\r\nLast-Modified: Tue, 08 Mar 2016 17:29:32 GMT\r\nETag: W/\"972e0b-b62284-52d8ceca83037\"\r\nAccept-Ranges: bytes\r\nContent-Length: 11936388\r\nConnection: close\r\nContent-Type: application/json\r\n\r\n", 272}], 1) = 272
sendfile(10, 11, [0], 11936388)         = 352
```

**Comment by belforte** [comment]
in one line:
it is a bad idea to play with a file content while someone may be reading it  :-)

let's also review the need of a fresh cras status output in order to kill

**Comment by belforte** [comment]
this is made obsolete by task process
