### ISSUE TITLE
Document slow job release (for HC)

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5178]
See this new feature https://github.com/dmwm/CRABServer/pull/5163, we should document it in some twiki.

**Comment by emaszs** [comment]
Slow job release has been documented here: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3TipsAndTricks#Slow_job_release_for_Hammer_Clou

Unless someone has suggestions on how to improve it, I'll close this issue.
