### ISSUE TITLE
Upload a warning if job runtime is less than 20 minutes

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5179]
Discussion started here: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2512.html

**Comment by belforte** [comment]
this is part of the wide problem
"make user run longer jobs".
currently we hope it will be solved by automatic splitting. Let's see if we really can offer that to users, in case we clearly will need to invest a lot on these kind of feedbacks and we will see then what's the best way to catch users attention.
