### ISSUE TITLE
allow stageout file removal to fail for CMS@Home

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5187]
since this commit
https://github.com/dmwm/CRABServer/commit/72dd2f7c6853168900efb4082964d73f6419d08c
StageoutCheck.py fails permanently, disallowing submission, if it is not possible to delete the stage out files from remote destination. See
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/StageoutCheck.py#L88

But it turns out that this is a feature for CMS@Home, where users are allowed to write, but not to deleted.
So we need to do something.
A simple possibility is to change the check so that failure to remove is never fatal, all in all, if we could write, it means everyhing is OK and fialure to remove in general could only be some glitch. If user directs stageout to a write-once file system.. well.... so be it.

Any reason not to do that ?

**Comment by juztas** [comment]
I would have more questions and what is on our system:
If transfer fails, but it created a partial file on destination, it will fail to delete. what will happen with next job as it will try to stageout to same file path and you have partial file already? Is overwrite allowed?
Never looked into deeper details of gfal2, but it would require more testing.

**Comment by belforte** [comment]
this was meant for the stageout check test.
When doing actual stageout, IIUC current code: if initial copy is OK, all fine, otherwise there will 
be permanent failure for that job. I see no point in trying to improve that.

**Comment by belforte** [comment]
CMS@Home has a (temporary at least) solution now:
from https://cern.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=c3c0406c4f229600b8cbca1f0310c7b6%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true

We have managed to bypass the problem by changing the protocol in the TFC T3_CH_Volunteer/PhEDEx/storage.xml from https to davs, e.g.
<lfn-to-pfn protocol="http" path-match="/+store/(.*)" result="davs://data-bridge-test.cern.ch/myfed/cms-boinc/output/$1"/>

**Comment by belforte** [comment]
realistically, we'll never run CRAB on CMS@HOME
