### ISSUE TITLE
do we really want to retry 3 times SIGKILLed job ?

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5190]
see
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L351-L352

what was the rational for that decision ? At first sight I think we have no indication that it can help, looking at dashboard (but of course things can change with time) for Apr 1-13  (which I was doing for other reasons) I found that exitcode 137 accounts for 8% of total WallClock time wasted in failed jobs. Not a big gain if we reduce it, but may an easy one.

**Comment by bbockelm** [comment]
Hi Stefano,

I believe the observation is that many batch system kills (particularly, PBS) will show up as a `SIGKILL`.  Typically, this isn't the user code's fault - it was often a site or pilot misconfiguration that led to the pilot exhausting its allocated runtime.

Memory leaks often lead to different error messages.

Brian

**Comment by belforte** [comment]
thanks Brian, I looked at a couple log files of jobs with 137 (not on PBS, for generality) and agree. Let's keep it as it is and I add a bit of info in the comment in the code.
