### ISSUE TITLE
Adjust the list of sites when ignoreLocality is used

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5191]
When ignoreLocality is used we simply take the whole list of sites from sitedb: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L642

IMHO this is wrong, if anything we should do the same thing we do for PrivateMC jobs where we take out T1s (https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/MakeFakeFileSet.py#L24-L33). I know we need something better in the SSB, but we can start with this.

BTW, this is another reason (in addition to PrivateMC) that caused the T0 to be in the DESIRED_Sites for CRAB3 jobs. That specific problem is now solved by manually blacklisting the T0 in the SSB. But I wonder what would happen if SSB is down, do we ignore it and simply do not apply the "global blacklist"? Also, we said we should provide a way for users to ignore the global blacklist, we may want to think about that twice if we used the global blacklist for avoid to put the T0 in the DESIRED_Sites.

**Comment by belforte** [comment]
The T0 was not a problem, only aesthetic, as I tried to explain. Here's how I'd approach this:
1. change the semantic of "ignoreLocality" to the Crab2 style of "overrideDataLocation"
   if user do not like our list, they provide theirs and take their risk and responsibility
2. if CRAB jobs are harmful to a PSN (HLT e.g.) they must be blocked in the infrastructure, not relying on users, nor on CRAB classAds
3. you have a good point that once we take our list from SSB we have to worry about the http fetching to fail and a cache looks a good way to me. But this is general for many things, like getting the list of PSN from SiteDB etc. So either we cache everything, or take the hit and fail submission. I see no evidence for SSB to be less available than SiteDB, and long term if we go on with "CRIC" we will take both PSN/PNN and blacklists from the same server

**Comment by belforte** [comment]
note that if you do no like to change the parameter name from the dreaded "ignoreLocality", you can simply make it mandatory to put a site white list when ignoreLocality is used.

**Comment by belforte** [comment]
I think my comment addresses the implicit question at the end of the initial issue text. The part about using the same default list of sites in case there is no data location to guide site selection is of course fine. Odd that it was not coded like that since the beginning, but surely OK to unify.

**Comment by mmascher** [comment]
On Fri, Apr 15, 2016 at 9:35 AM, Stefano Belforte <notifications@github.com>
wrote:

> The T0 was not a problem, only aesthetic, as I tried to explain. Here's
> how I'd approach this:
> 1. change the semantic of "ignoreLocality" to the Crab2 style of
> "overrideDataLocation"
> if user do not like our list, they provide theirs and take their risk and
> responsibility
> 2. if CRAB jobs are harmful to a PSN (HLT e.g.) they must be blocked in
> the infrastructure, not relying on users, nor on CRAB classAds
>
Ok to have a safety net on the infrastructure for corner cases (see below).
But T0 should not be there to begin with in the CRAB3 classads.


> 3. you have a good point that once we take our list from SSB we have to
> worry about the http fetching to fail and a cache looks a good way to me.
> But this is general for many things, like getting the list of PSN from
> SiteDB etc. So either we cache everything, or take the hit and fail
> submission. I see no evidence for SSB to be less available than SiteDB, and
> long term if we go on with "CRIC" we will take both PSN/PNN and blacklists
> from the same server
>

Well, if sitedb is not available I know we fail, so it is not a problem, we
will detect it. I've just checked what we do when the SSB is not available,
and I verified we fail silently and use the cached data. And if no cache is
available and the SSB is down we ignore the global blacklist. This is a
corner case that might bite back us, but it's so rare that I would not
worry.

**Comment by mmascher** [comment]
If we go with the "make whitelist mandatory when using ignoreLocality" (and
maybe add a message that ignoreLocality should be used with care), we won't
need that as the only place where we need a default list of sites where to
run is PrivateMC. Everything else would be guided by data locations or
user's whitelists.

Question is, I have always thought we never did it because the management
did not like it. Is it ok to do it now or should this be discussed (maybe
an email to comp-ops)?

**Comment by belforte** [comment]
I think you want to say:
  CRAB3 should not put T0 there itself intentionally
But trying to guarantee that users can't put it there no matter what,
would be too much effort and take away some useful flexibility, IMHO.

**Comment by belforte** [comment]
is it difficult to change this to screaming failure ?

**Comment by mmascher** [comment]
Yes, that's what I wanted to say. Change what to screaming failure, SSB cache not available? I don't think so.

**Comment by belforte** [comment]
yes. But after looking up the code in https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/BanDestinationSites.py and https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py I agree that an empty black list can only be due to some global failure like disk full, bad installation, accidental file deletion.. lets' not worry.

**Comment by belforte** [comment]
about the
 "make whitelist mandatory when using ignoreLocality ...  we never did it because the management did not like it."
I am not sure who in management would care. Let's start from what we think will work best. I'd rather show a proposal to "management" than a question !

**Comment by belforte** [comment]
assigning to me to recap and define short action list

**Comment by belforte** [comment]
overridden by #5293
