### ISSUE TITLE
avoid sending huge json files to client

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5208]
We can't send files of 45MB or more on http with a 30sec timeout. Even if at  times it works.

see example in 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/1603.html

as verified on the schedd

```
root@submit-5 ~# ls -lLh /home/remoteGlidein/70/uscms5336/160421_152242:hogul_crab_20160421_102219/error_summary.json
-rw-r--r-- 1 uscms5336 uscms 44M Apr 25 14:50 /home/remoteGlidein/70/uscms5336/160421_152242:hogul_crab_20160421_102219/error_summary.json
root@submit-5 ~# 
```

There are at least 2 things to do:
1. this is not an error summary,  the file now contains a log snipped for each job
2. even if sensing all that info in one go to the client (note that this was a simple crab status, w/o the --long option) were usefulm the file should be zipped.

I think longer timeout is not an option.

A proper solutoin should be part of the new cfrab status that @emaszs is working on

**Comment by mmascher** [comment]
Hi Stefano,

I'd like to revisit how we produce the error summary file anyway adding it to the "task process" (which would solve https://github.com/dmwm/CRABServer/issues/5170)

BTW, we never show the whole list of errors anyway, so it does not probably make sense to ask for it.

**Comment by belforte** [comment]
hopefully status2 will be production soon and we can close at that point

**Comment by belforte** [comment]
@emaszs can you confirm that this will be no problem with status2/taskprocess ?

**Comment by emaszs** [comment]
It shouldn't be, we'll only send the last retry errors to the client instead of all of them.

**Comment by belforte** [comment]
I think we can close now that status2 is deployed.
