### ISSUE TITLE
remove debug printout

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5217]
Is this  line a left-over debug printout ? It pollutes (uselessly I think) nohup.out
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/RenewRemoteProxies.py#L70

looks like @mmascher originally put it there. see
https://github.com/dmwm/CRABServer/commit/4b7acb88f48bf917ad84bb284b249d32783c0615#diff-89241d5cec18d2af9a36423fcc0926efR63

**Comment by mmascher** [comment]
Looks like a leftover. Not sure I put it there, in that commit I simply moved some code and renamed a file (i't still there in that diff https://github.com/dmwm/CRABServer/commit/4b7acb88f48bf917ad84bb284b249d32783c0615#diff-648a4c8b967d000784336e39bc47606cL59)

Anyway, it doesn't matter! Let's remove it
