### ISSUE TITLE
add a flag for each schedd in TW configuration  

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5252]
THIS IS A PROPOSAL. I open an issue to have a place to discuss and possibly approve and then do the changes.

In REST configuration [1] we have this 

```
            "htcondorSchedds" : {
                "crab3@vocms021.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/021"
                },
                "crab3-4@vocms066.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/066"
                },
                "crab3@vocms0106.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/0106"
                },
...
```

[1]  https://gitlab.cern.ch/crab3/CRAB3ServerConfig/blob/master/cmsweb-rest-config.json

I propose to add one numeric flag for each schedd with values:

0 : schedd disabled
1: schedd enabled
that will simplify taking schedd's in/out of the pool

could also use value other then 0/1 to indicate:
x: relative weigth - this schedd will receive x-times the number of tasks that it would be receiving otherwise.

the latter will simplify the case where we simply want to load more one schedd to see how it behaves under stress, or to give it  a break or simply easily and simply teask the schedd picking algorithm.
It is not meant to replace the memory-weiighted choice we have now nor the distance-from-limit-wieighted that we discussed, but coudl complement it in the meanwhile.

**Comment by belforte** [comment]
@jmarra13 this should be what we talked about, feel free to comment, of course

**Comment by jmarra13** [comment]
```
            "htcondorSchedds" : {
                "crab3@vocms021.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/021",
                    "statusFlag": 1
                },
                "crab3-4@vocms066.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/066"
                    "statusFlag": 2
                },
                "crab3@vocms0106.cern.ch" : {
                    "proxiedurl": "https://cmsweb.cern.ch/scheddmon/0106"
                    "statusFlag": 0.5
                },
...
```
so something like this:

statusFlag=1   a regular enabled schedd
statusFlag=2   a 2 times boosted schedd
statusFlag=0.5 or any value between 0 and 1 for a limitted schedd.

@mmascher can this addictional element break the current code?

**Comment by belforte** [comment]
yes, that's the idea.

**Comment by belforte** [comment]
after talking with @mmascher the idea is to change HTCondorLocator.schedd to add the weigth from the configuration to the one from the picker function (add = multiply, of course):
https://github.com/dmwm/CRABServer/blob/master/src/python/HTCondorLocator.py#L58

**Comment by belforte** [comment]
now tracked in https://github.com/dmwm/CRABServer/issues/5344
