### ISSUE TITLE
put TM config in GIT ?

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5253]
Shouldn't  we put the TaskManager configuration template `TaskWorkerConfig.py ` in here
https://github.com/dmwm/CRABServer/tree/master/src/python/TaskWorker
?
rather than only on the twiki ?
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabTaskWorker#Configuration

I may make it easier to maintain it. E.g. now it needs adding the scheddPickerFunction

**Comment by mmascher** [comment]
We can the example that now in on the twiki, but IMHO what is being used in production should stay on a separate configuration repository (maybe on gitlab where only CERN users have access). Maybe we can use the same used for the REST interface? What do you think @jmarra13 ? Then the start.sh script you use can download (a read only copy of) it from there.

**Comment by belforte** [comment]
that'd have the advantage that the current configuration is backedup and that changes are tracked.

**Comment by jmarra13** [comment]
I like the idea @mmascher, I can put it on gitlab together with REST configs.

**Comment by jmarra13** [comment]
Done https://gitlab.cern.ch/crab3/CRAB3ServerConfig/commit/e90ba7d71e6183786f459231ffbf2ef07cb9132f

start.sh was updated to fetch the configuration file before starting TW.
