### ISSUE TITLE
TW should not try to submit if a user certificate is revoked.

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#5254]
see https://cmsweb.cern.ch/crabserver/ui/task/160704_062009:cirkovic_crab_20160704_082000/dbver/prod

**Comment by belforte** [comment]
thanks @jmarra13 
this is the same as https://github.com/dmwm/CRABServer/issues/5242
let's keep one issue only. I'll comment in there

**Comment by jmarra13** [comment]
Just to inform, I dont know is this user certificate is really revoked or if this is due to [1].
@belforte I agree that the issue should be treated in the same way but an expired cert is a bit different than a revoked one, anyway revoked or expired does not matter TW must stop in both cases.



[1] https://ggus.eu/?mode=ticket_info&ticket_id=122500

**Comment by belforte** [comment]
even if different reason, the solution is in same place in TW and should be similar.
So let's keep one issue, which anyhow has pointer to this one as well. By the way that ticket
you mention is about a GGUS internal problem, and is thus unrelated.
