### ISSUE TITLE
job wrapper wrongly reports JobExitCode=0 to dashboard

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5257]
from
https://cmsweb.cern.ch/scheddmon/021/cms922/160704_114918:lbrianza_crab_TTbar_powheg/job_out.15.0.txt

```
Dashboard stageout failure parameters: {'MonitorID': '160704_114918:lbrianza_crab_TTbar_powheg', 'MonitorJobID': '15_https://glidein.cern.ch/15/160704:114918:lbrianza:crab:TTbar:powheg_0', 'JobExitCode': 0, 'StageOutReport': [{'SEName': 'dcache-se-cms.desy.de', 'StageOutType': 'LOCAL', 'LFN': '/store/temp/user/lbrianza.a797e9194b6912729678a3f2262ed435695ce555/dpg_ecal/alca_ecalcalib/ecalMIBI/lbrianza/ntuple_MC_4jul_v2/TTbar_powheg/TT_TuneCUETP8M1_13TeV-powheg-pythia8/crab_TTbar_powheg/160704_114918/0000/failed/ReducedSelection_15.root', 'StageOutExit': 0, 'PNN': 'T2_DE_DESY', 'StageOutCommand': None}]}
```

while JobExitCode must be 8001, e.g. later in the log:
```
Dashboard stageout failure parameters: {'MonitorID': '160704_114918:lbrianza_crab_TTbar_powheg', 'MonitorJobID': '15_https://glidein.cern.ch/15/160704:114918:lbrianza:crab:TTbar:powheg_0', 'JobExitCode': 8001}
====== Mon Jul  4 12:18:46 2016: cmscp.py FINISHING (status 8001).
======== Stageout at Mon Jul  4 12:18:46 GMT 2016 FINISHING (short status 65) ========
======== gWMS-CMSRunAnalysis.sh FINISHING at Mon Jul  4 12:18:46 GMT 2016 on batch0912.desy.de with (short) status 65 ========
Local time: Mon Jul  4 14:18:46 CEST 2016
Short exit status: 65
======== Figuring out long exit code of the job for condor_chirp ========
==== Long exit code of the job is 8001 ====
```

I think the two messages are sent to the dashboard at almost same time and there's then a race in UDP collectors and randomly the first of the latter wins.
That task this job belogs to has all jobs with same error (user is looking for objects not present in the dataset) but in the dashboard almost a half appear with exit code = 0.

THere is no reason for the stageout script to report a JobExitCode based only on stageout result !

**Comment by belforte** [comment]
the report is generated by
https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1964
via
https://github.com/dmwm/CRABServer/blob/master/src/python/DashboardAPI.py#L250-L277

need to track logic more upstream

**Comment by belforte** [comment]
no. there are 4 places in cmscp.pc where reportFailureToDashboard is called... not sure yet which one was involved here.

**Comment by belforte** [comment]
the previous line in stdout is:
PNN is defined in site-local-config ...
which points to the wrong exit code to be reported by
https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L511
which indeed is inside an `if retval == 0:` which is not really in agreement with
`DashboardAPI.reportFailureToDashboard(retval, ....` pff....

**Comment by mmascher** [comment]
Good chance to refactor cmscp. @belforte might try to find a fix sooner.

**Comment by belforte** [comment]
In the end I think we could fix this by changing in line
https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L511
from
```
DashboardAPI.reportFailureToDashboard(retval, ... )
```
to
```
DashboardAPI.reportFailureToDashboard(G_JOB_WRAPPER_EXIT_CODE, ... )
```

The way to test would be to cook up some jobs where cmsRun fails but stageout works.
I will try to find them.

**Comment by belforte** [comment]
I tested that on  a couple jobs and it worked, to test more I need to make my VM work

**Comment by belforte** [comment]
tested more. All fine. Made a PR
