### ISSUE TITLE
updating instructions for "Deployment of CRAB REST Interface" 

### ISSUE THREAD

**Issue by jmarra13** [dmwm/CRABServer#5258]
There is a missing information about CRAB REST interface that we(me @emaszs)  found out yesterday. If a developer wants to debug any issue related to TW and any schedd outside CERN(e.g. UCSD ones) he/she wont be able to do it using a personal CRAB server because AdjustSites.py will fail to updated REST interface with webdir location since the VM is behind CERN firewall.

**Comment by belforte** [comment]
since we decided to omly run schedd's at CERN, we'll see about this if and when we put one off-site again
