### ISSUE TITLE
cmscp little bug

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5262]
In https://github.com/dmwm/CRABServer/blob/3.3.1607.rc3/scripts/cmscp.py#L511, `stageout_info` is not defined when `local_stageout_mgr` fails in https://github.com/dmwm/CRABServer/blob/3.3.1607.rc3/scripts/cmscp.py#L464

**Comment by jmarra13** [comment]
I catch the same error today, Jul 28, when submitting jobs to validate a new schedd.

>jmsilva@lxplus008 ~/workspace/schedValidation> crab status /afs/cern.ch/work/j/jmsilva/schedValidation/validation/crab_vocms0121-mc-1469700404-52 --verboseErrors
CRAB project directory:		/afs/cern.ch/work/j/jmsilva/schedValidation/validation/crab_vocms0121-mc-1469700404-52
Task name:			160728_100654:jmsilva_crab_vocms0121-mc-1469700404-52
Grid scheduler:			crab3@vocms0121.cern.ch
Task status:			SUBMITTED
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=jmsilva&table=Mains&pattern=160728_100654%3Ajmsilva_crab_vocms0121-mc-1469700404-52
>
Jobs status:			failed          0.6% (   6/1000)
				finished       94.2% ( 942/1000)
				transferring    5.2% (  52/1000)
>
No publication information (publication has been disabled in the CRAB configuration file)
>
Error Summary:
>
   6 jobs failed with exit code 60318:
>
	   6 jobs failed with following error message: (for example, job 238)
>
		CmsCpFailure
		cmscp error message follows.
		ERROR: Unhandled exception when performing stageout of user logs archive file.
		Traceback (most recent call last):
		  File "cmscp.py", line 1612, in main
		    is_log = True, inject = transfer_logs)
		  File "cmscp.py", line 433, in perform_stageout
		    source_site, is_log, inject)
		  File "cmscp.py", line 511, in perform_local_stageout
		    if stageout_info['StageOutReport']:
		UnboundLocalError: local variable 'stageout_info' referenced before assignment
>
Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
Log file is /afs/cern.ch/work/j/jmsilva/schedValidation/validation/crab_vocms0121-mc-1469700404-52/crab.log

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/5270

**Comment by belforte** [comment]
closed via #5270

**Comment by AndresTanasijczuk** [comment]
The issue is still not fixed. See for example this job log file: https://cmsweb.cern.ch/scheddmon/0121/cms1515/171011_143656:amagitte_crab_Run2016G_SingleMuon/job_out.2.7.txt

Possible fixes:

1) You could change https://github.com/dmwm/CRABServer/blob/3.3.1710.rc2/scripts/cmscp.py#L435 to 
```
stageout_info = {}
```
to initialize it to an empty dictionary.
2) You could change https://github.com/dmwm/CRABServer/blob/3.3.1710.rc2/scripts/cmscp.py#L481 to 
```
if stageout_info and stageout_info.get('StageOutReport'):
```

**Comment by belforte** [comment]
Thanks @AndresTanasijczuk   . On my list.

**Comment by AndresTanasijczuk** [comment]
Hi @belforte,

Sorry, I was not precise in the suggestion you implemented. Just defining stageout_info as an empty dictionary is not enough. You also need to change https://github.com/dmwm/CRABServer/blob/3.3.1710.rc2/scripts/cmscp.py#L435 to
```
if stageout_info.get('StageOutReport'):
```
Because ```stageout_info['StageOutReport']``` will raise a KeyError exception if the key 'StageOutInfo' is not in the stageout_info dictionary, while the get() method will instead return None and the if will evaluate to False.

**Comment by AndresTanasijczuk** [comment]
I mean, 'StageOutReport' key, not 'StageOutInfo'.

**Comment by belforte** [comment]
thanks @AndresTanasijczuk . Sorry for my sloppy reading of the code :-(

**Comment by belforte** [comment]
@mmascher there already 2 commits which I pushed in tag 3.3.1710.rc2.patch1 which need changing. What is the best way forward ? Shall  we patch that or roll back and create new fixes for old master branch ?
