### ISSUE TITLE
About clearing /store/temp when upload of filetransfersdb to oracle fails

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5274]
Hi, I am opening this to keep track something we might want to discuss at some point when @belforte is back.

Assume:

1) Job runs at T2_X and does local stageout in /store/temp
2) postjobs fails to upload metadata to oracle
3) job gets retried

Then who is going to clear the file in /store/temp?

For the moment we are relying on the site to do that since the postjob is not going to do gfal-rm. I guess this is fine, but in case the job gets retried on the same site then stageout to /store/temp might fail and the job is going to do the direct stageout.. which is still fine, but seems sub-optimal.

**Comment by belforte** [comment]
every site is supposed to clean every file >2weeks old.
We surely can not rely on CRAB/ASO to delete all files all of the time,
it is simply impossible. Remote delete always has a non zero chance
of failing in spite of repeated attempts.

**Comment by belforte** [comment]
Seems we forgot to close. The previous comment clearly says "we can't do anything"
