### ISSUE TITLE
force user to provide a site white list when using xrootd

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5293]
i.e. remove ignore_locality and replace with override_location a' la CRAB2 or make it mandatory to provide a site white list when using ignore_locality.
Maybe we want to force users to be more specific than T2\* in this case ?
This will need changes also on client side.

**Comment by belforte** [comment]
see extended discussion in
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2573/1/1.html
and following replies

**Comment by belforte** [comment]
corresponding client issue:
https://github.com/dmwm/CRABClient/issues/4646

**Comment by ericvaandering** [comment]
Seems to me one setting vs. two is better. So your proposal (I skimmed the HN) is to have override_location (I'd suggest force_location) instead and it obeys the same rules for data location that site whitelists do for processing locations?

**Comment by belforte** [comment]
Back to this old issue. Yes, as you wrote @ericvaandering . I am fine with force_location, let's not reuse CRAB2 lingo :-)

**Comment by belforte** [comment]
I forgot.. the bad thing in a new setting is that it needs a change in the DB schema and all DB accessing function. Why each possible configuration parameter is a DB column, beats me, but that's they way things have been coded. And I do not want reuse ignoreLocality with a different semantic.

Ideally one could write the code so that the list of DB column is only in one place. Than this would not be so hard, but until that, I am afraid that I will go for the easy solution, even if it surely is ugly.

**Comment by belforte** [comment]
check implemented on the client.
https://github.com/dmwm/CRABClient/issues/4646
nothing to be done on the server
