### ISSUE TITLE
accept job range --jobids ... in crab status --long

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5294]
status --long prints very nice info about jobs (mem, time, node, error, restarts... I would like to add disk) but it is sort of useless and only confusing to print for K's of jobs. Better let user pick a few example jobs, print them, dig on them. At least will help me in telling them what to do. I know job list is also on dashboard, but it is nice to see mem/time/disk e.g. which are the indicator for 5066x

This may actually be client only. I am not sure yet, in case we can move the issue

**Comment by belforte** [comment]
make this part of status2 ? Or is it there alrady. @emaszs what do you think ?

**Comment by belforte** [comment]
@emaszs says it can be easily made. So assigning to him

**Comment by emaszs** [comment]
Should be fixed with https://github.com/dmwm/CRABClient/pull/4681
