### ISSUE TITLE
bad dashbaord URL in CrabServer MOnitor

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5310]
in https://cmsweb.cern.ch/crabserver/ui/task/...
the Link to dashboard is wrongly constructed as e.g.
`http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=gsfs&table=161025_125446:gsfs_crab_AllQCDPhoton15_RAW$table=Mains&pattern=161025_125446:gsfs_crab_AllQCDPhoton15_RAW`
Note that `table` appear twice, clearly the 2nd win, so it still works

But would be much better to have the same as in crab status, namely:
`http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=gsfs&table=Mains&pattern=161025_125446%3Agsfs_crab_AllQCDPhoton15_RAW`

**Comment by emaszs** [comment]
Ah, good spot, I changed the url generation after the dashboard url was updated in the status but did so simply incorrectly.
