### ISSUE TITLE
add link to output dataset DAS in Server Monitor

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5311]
in the main tab  of pages like
https://cmsweb.cern.ch/crabserver/ui/task/161025_125446:gsfs_crab_AllQCDPhoton15_RAW
change Link to DAS to be actually two links, one to INPUT dataset (like now ) and one to OUTPUT dataset in DBS3 (when publication is enabled)

**Comment by emaszs** [comment]
@belforte Do you know if/when there can be more than one output dataset and if I should take that into  account? Marco said it's possible and foreseen but wasn't sure if it ever happens.

**Comment by belforte** [comment]
it will be such an extensive change (validation wise, if anaything) that we
can surely worry about changing the monitor page at that time.

Some piece of the code supports it, I think, e.g. in publication
area, but at the very least we need to change configuration file,
crab status and crab report.

Given the amount of work that it may be and the fact that
so far we could live w/o it, I think we will only do it when
forced at gun point.
