### ISSUE TITLE
prevent users from running cmsRUn with more threads than there are cores 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5315]
See this thread:
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3269/3/1/1/1/1/1/1/1/1/2.html

**Comment by ericvaandering** [comment]
As @belforte says, the devil is in the details. Do you silently set the pset back to the CRAB value, refuse to proceed, set the crab value to the pset value and print a message, ...

As David Lange points out, with script exe its really hard to keep people from abusing things, but you can at least catch the simple cases.

**Comment by belforte** [comment]
thanks @ericvaandering 
From the incident referred to in initial comment, I think the first thing is to protect against users who unknowingly recycle production psets which are now multithreaded, see comment from @dan131riley at
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3269/3/2.html

So I propose:

1. EDM folks point us to or make us a call to tell the number of threads requested in a pset, w/o CRAB doing `grep`, like done for the output files
2. CRAB looks for the simple case where the pset pointed to in crab config has an explicit numThreads larger then the ncores in crab config and plainly refuse to submit, pointing user to fix the pset

That basically leaves multiple threads for those who have some sense and do it explicitely and those who blindly copy paste some combination that works.

For all those cases, when users starts too many threads, I'd pass the ball to HTCondor and ask them to kill the payload, relieving Daniela.

Main problem I see: in a few months, rumor will spread that if you set numCores = 4 (or 8)  in crab config you avoid some problems, so people will put it in all tasks even if totally useless. This will lead to heavily underutilizes slots. glideinWMS is now set to penalize those users, charging them for as many cores as they ask even if they do not use them, but... I really do not see how to avoid this.

I welcome ideas on how to prevent the empty slots.
Parsing user scripts to figure out how they manipulate numThreads based on `/usr/bin/nproc` (a common habit atm) is IMHO not viable.

**Comment by hufnagel** [comment]
How about going even simpler ? CRAB runtime *always* modifies the user provided config and overrides it with the requested number of cores (so 1 by default).

As for users just blindly asking for more cores. There is no way to prevent that. But user jobs can be inefficient for many reasons, not just because their code isn't very multi-threading efficient.

Unless we are willing to measure the job efficiency somehow and refuse to submit a task if it's too bad, we cannot avoid this problem.

**Comment by davidlange6** [comment]
why be different from production (or at least my understanding of it)? The request specifies Ncores, and whatever is in the config gets overwritten by whats in the request.

**Comment by belforte** [comment]
I think we did all that we possibly can:
- set a default ncores if it was missing
- force ncores to be 2,4 or 8
- force ncore in crab config to be the same and numthreads in cmssw pset
anything else is basically "users run thier script and do whatever forking they like and who knows if they do it sensibly", the best  defense there is something in the pilot.
