### ISSUE TITLE
remove checksum from direct stage out

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5319]
when trying to stage out directly to remote CE should not use checksu,m since not all sites support it and gfal is not capable to fall back graciously to not using it, so we get zilions of failed stageout (esp. at FNAL EOS) which create lots of other problems like last week.
See this thread for discussion
https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/3313.html

**Comment by PerilousApricot** [comment]
FWIW, FNAL claims their EOS supports checksums now

**Comment by belforte** [comment]
I still think that the right way is to be careful in FTS (as per the issue that @PerilousApricot just opend in ASO) but when we come to needing a fallback, just maximize the chance of success.
The problem is not FNAL. Is that we do not have a clear requirement on sites nor a procedure in Ops to verify that all sites comply to the requirement and that this is working etc.

**Comment by PerilousApricot** [comment]
@belforte The most recent PhEDEx release (which was required to be installed in December) uses checksumming universally. It might not be a written down ops requirement, but functionally it is there

**Comment by belforte** [comment]
hmmm....  sorry @PerilousApricot but I just do not want to have something to chase site by site. We'll ask FTS to use it, which is likely the same as PhEDEx does. But the rest I want to keep very simple. We have already more problems and more new stuff to do then we can really handle

**Comment by PerilousApricot** [comment]
@belforte I'm not sure I understand the distinction. If FTS is using it, then it has to work, right? In what case would it work with FTS, but then not if you used it manually?

**Comment by PerilousApricot** [comment]
Or put another way, FTS itself uses gfal-X underneath the hood to move files.

**Comment by belforte** [comment]
yes @PerilousApricot , I understand that. But I am still not feeling comfortable and do not have the time in this days to investigate down to tiny details to be sure. So am sticking with the simplest and safest fallback.
We have plenty of obscure issues to deal with anyhow.
Do you really expect this to be a problem ? I would be happy to say: you change it back to enable checksum but if any problem ever appears, you deal with it, not me !

**Comment by PerilousApricot** [comment]
@belforte If you don't think that sites can do checksums via gfal, then you shouldn't enable it for ASO either -- ASO ends up using gfal at the bottom.

At the scales we work at, yes, files get mangled in flight. That's why PhEDEx made it mandatory. You're not PhEDEx, of course, so you can choose to do what you want. I'm trying to point out that disabling checksums via GFAL while simultaneously enabling checksums for ASO+FTS is nonsense since FTS ends up calling GFAL to perform the actual transfers.
