### ISSUE TITLE
port DAG boostrap to python 2.7

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5320]
I thought all of CRAB was python 2.7 compliant, even 3.0 ready. 
But serendiptiously I found this while looking at a faile bootstrap:
```
[root@vccondorce02 cluster1239.proc0.subproc0]# tail _condor_stderr
+ command -v python2.6
+ rc=1
+ [[ 1 != 0 ]]
++ hostname
+ echo 'Error: Python2.6 isn'\''t available on vccondorce02.cern.ch.'
Error: Python2.6 isn't available on vccondorce02.cern.ch.
+ echo 'Error: Bootstrap execution requires python2.6'
Error: Bootstrap execution requires python2.6
+ condor_qedit 1239.0 DagmanHoldReason ''\''Error: Bootstrap execution requires python2.6.'\'''
+ exit 1
[root@vccondorce02 cluster1239.proc0.subproc0]#
```

**Comment by PerilousApricot** [comment]
Hi Stefano,

Heh, the bootstrap got copied over from the WMA one. I originally put that
test in WMA because a lot of hosts only had python2.4 instead of python2.6.
I didn't intend for it to break the opposite way this many years later!
