### ISSUE TITLE
can't find tw log in crab monitor UI

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5323]
I am looking at this task
https://cmsweb.cern.ch/crabserver/ui/task/161122_112924:cpistone_crab_DoubleEG_Run2016B_23Sep2016v3_13TeV_MINIAOD
but when I click on task worker log I get
```
x-error-http: 400 x-error-detail: required object is missing x-error-id: ccf4bad0e9e444d840fbb7cc865b4ac6 x-rest-status: 303 x-error-info: not such file
```
even if log is there in the expected place in task worker disk

belforte@vocms052/cpistone> ls -l /data/srv/TaskManager/logs/tasks/cpistone/161122_112924:cpistone_crab_DoubleEG_Run2016B_23Sep2016v3_13TeV_MINIAOD.log
-rw-r--r--. 1 crab3 zh 59003 Nov 24 10:44 /data/srv/TaskManager/logs/tasks/cpistone/161122_112924:cpistone_crab_DoubleEG_Run2016B_23Sep2016v3_13TeV_MINIAOD.log
belforte@vocms052/cpistone> 

What could be the reason ?

**Comment by mmascher** [comment]
Files gets removed from the crabcache after a few days.

**Comment by belforte** [comment]
is tw log copied to file cache ???

**Comment by belforte** [comment]
@mmascher explained that a copy of tw log is uploaded to crabcache every time a command is completed (submit, resubmit, kill...) and deleted after a few days. Which explains why at times I find in crab monitor the tw log for a week old task, but this time I didn't.
Long term solution is the now "famous" one to get rid of this UFC etc., push all logs to some long term storage like EOS/HDFS... whatever, where we can get O(100TB) of http accessible space and cleanup once/year.
Seems a good project for a technical student, to me.
