### ISSUE TITLE
make #cores and #threads consistent

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5337]
as discussed in CRAB meeting on Dec 20th 2016: CRAB should
- if user specified either numcores in crab config or numthreads in pset, verify that they are the same and if not refuse submission
- refuse submission unless numcores is one of: 1 (default), 4 or 8.
We have not defined what to do when scriptexe is used and there is no pset.py. Some users run scripts which benefit from multiple cores there, even if we have seen them requesting 8 cores and start 64 processed. Initially we tolerate that, only enforcing a 1/4/8 for numcore.

**Comment by emaszs** [comment]
Fixed with https://github.com/dmwm/CRABClient/pull/4662
