### ISSUE TITLE
remove dependency from AFS

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5338]
all of these can be removed
https://github.com/dmwm/CRABServer/blob/master/scripts/dag_bootstrap.sh#L85-L92

correct ?

**Comment by belforte** [comment]
basically we should remove that code now to make sure that things work even if AFS is not there.
Would be good to turn off AFS on a test schedd.  Maybe something Todor could do at any time.

**Comment by belforte** [comment]
@emaszs says he tested removing those references

**Comment by belforte** [comment]
also run a test task worker w/o AFS

**Comment by belforte** [comment]
need to assign to Todor
@ericvaandering can you add Todor to the proper team so we can assign to him ?
he already has a github account : @todor-ivanov

**Comment by ericvaandering** [comment]
should be done once he accepts the invitation to join us.

**Comment by belforte** [comment]
@todor-ivanov a quick way could also be:
when you have a good day in front of you, grab ITB TaskWorker and schedd, stop afsd service,  unmount afs.. and make sure they still work , restart etc.

**Comment by todor-ivanov** [comment]
Hi Stefano,
That is exactly what I am doing this morning now.
As far the Tw has no dependency on /afs
even before the restart

~#lsof |grep  afs

didn't show any file opened from afs. Nevertheless I had it restarted  without the relevant service.
And now I am preparing  a schedd the same way and will make a test submission afterwards.

I will keep you in touch.

Regards,
Todor
________________________________

**Comment by todor-ivanov** [comment]
Hi Stefano,

The test  is done now.
I unmounted afs on the itb taskworker and on one of the schedd connected to the itb pool, stopped puppet, automount, afs  services, restarted and then submitted a task and it started  perfectly well. We just have to remember to switch it back on once the task finishes.
The schedd  in question is vocms0115.
The itb tw is vocms0118.

About these few lines in the dag_bootstrap.sh script [1] that are referring  to the  cms_ui_env.sh, we can safely try to move this bootstrap script to /cvmfs  and go forward.

Regards,
Todor

[1]
https://github.com/dmwm/CRABServer/blob/master/scripts/dag_bootstrap.sh#L85-L92

________________________________
From: Todor Trendafilov Ivanov
Sent: 15 February 2017 11:30
To: dmwm/CRABServer; dmwm/CRABServer
Cc: Mention
Subject: RE: [dmwm/CRABServer] remove dependency from AFS (#5338)

Hi Stefano,
That is exactly what I am doing this morning now.
As far the Tw has no dependency on /afs
even before the restart

~#lsof |grep  afs

didn't show any file opened from afs. Nevertheless I had it restarted  without the relevant service.
And now I am preparing  a schedd the same way and will make a test submission afterwards.

I will keep you in touch.

Regards,
Todor
________________________________

**Comment by belforte** [comment]
thanks Todor, but we should simply remove those lines, not point to CVMFS
Didn't you already prove that those are not needed ?

**Comment by emaszs** [comment]
I did run a test without the references to afs and it should be good to go. Will test once more during validation of course.

**Comment by emaszs** [comment]
To summarize, no more references to AFS in production code (it was obsolete anyhow), @todor-ivanov also ran a test by unmounting afs from a Task Worker and a schedd. Closing.
