### ISSUE TITLE
site black list does not work on resubmit ?

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5363]
see this thread.
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2567.html
In that case at least, it did not work.
I verified that the black list is there in task worker log at resubmission time, but looking at classads of jobs started after than from their stdout, the DESIRED_SItes was not changed.
Expert investigation is needed, since I could not figure out the way in which the server currently sets DESIRED_Sites

I do not have time to pursue this further now, am opening the issue so we do not forget.

**Comment by arizzi** [comment]
anyone looking into it? 
if you need example jobs please contact me.

**Comment by mmascher** [comment]
Hi @arizzi I just created a PR that fixes this. I took the liberty of applying the fix to 170128_122107:arizzi_crab_VHBB_V25_002_TT_TuneCUETP8M2T4_13TeV-powheg-Py8__RunIISummer16MAv2-PUMoriond17_80r2as_2016heIV_v6-v1
the task mentioned in the hypernews @belforte forwarded to me (each task has its own copy of the code on the schedd).

If you want to do a resubmit of that task and check if the fix works it would be great!

**Comment by arizzi** [comment]
@mmascher thanks, but meanwhile I resub from scratch that sample (because it was important) and it already finished.
On the other hand if you want me to make a test I can point to some other tasks.

**Comment by mmascher** [comment]
Hi, yes, I think that would be good. If it is considered important I can also make a recipe to make users fix it by themselves once we are certain it works.

**Comment by belforte** [comment]
Only Andrea appeears to it atm. Other users will find it fixed in new release, right ? Or is it "in 
tasks submitted with new release" ?

**Comment by arizzi** [comment]
well, I'm not sure I'm the only one having run with crab in past week... (I see 200k pending jobs) so perhaps it is of general use, or perhaps it is not because it is fixed and it is just cheaper to resubmit the whole thing

**Comment by mmascher** [comment]
AFAIK Emilis included the fix in the February release, so the fix will be "in tasks submitted with the new release" which should be deployed soon (if not already deployed).

**Comment by emaszs** [comment]
Yes, it was just deployed.

**Comment by emaszs** [comment]
Oops, accidentally pressed the reopen button.. closing again
