### ISSUE TITLE
post job wrongly sets exit code 60321 in case of timeout

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5364]
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2581/1/1/1/1/2/2.html

here's an example postjob log
```
Tue, 31 Jan 2017 16:51:52 CET(+0000):DEBUG:PostJob (Parsed job ad.)
Tue, 31 Jan 2017 16:51:52 CET(+0000):DEBUG:PostJob Using cached ASO results.
Tue, 31 Jan 2017 16:51:52 CET(+0000):INFO:PostJob Got statuses: done, acquired; 23.0 hours since transfer submit.
Tue, 31 Jan 2017 16:51:52 CET(+0000):INFO:PostJob Defering the execution of the post-job.
Ended TaskManagerBootstrap with code 4
Tue, 31 Jan 2017 17:21:52 CET(+0000):DEBUG:PostJob (Parsed job ad.)
Tue, 31 Jan 2017 17:21:53 CET(+0000):DEBUG:PostJob Using cached ASO results.
Tue, 31 Jan 2017 17:21:53 CET(+0000):INFO:PostJob Got statuses: done, acquired; 23.5 hours since transfer submit.
Tue, 31 Jan 2017 17:21:53 CET(+0000):INFO:PostJob Defering the execution of the post-job.
Ended TaskManagerBootstrap with code 4
Tue, 31 Jan 2017 17:51:54 CET(+0000):DEBUG:PostJob (Parsed job ad.)
Tue, 31 Jan 2017 17:51:54 CET(+0000):DEBUG:PostJob Using cached ASO results.
Tue, 31 Jan 2017 17:51:54 CET(+0000):INFO:PostJob Got statuses: done, acquired; 24.0 hours since transfer submit.
Tue, 31 Jan 2017 17:51:54 CET(+0000):WARNING:PostJob Post-job reached its timeout of 86400 seconds waiting for ASO transfers to complete. Will cancel ongoing ASO transfers.
Tue, 31 Jan 2017 17:51:54 CET(+0000):INFO:PostJob ====== Starting to cancel ongoing ASO transfers.
Tue, 31 Jan 2017 17:51:54 CET(+0000):INFO:PostJob In case of cancellation failure, will retry up to 2 times.
Tue, 31 Jan 2017 17:51:54 CET(+0000):INFO:PostJob Cancelling ASO transfer b1e06566b4c004a02d5b87d9e321a8b026803bcb0edc677f3ed91aea with following reason: Cancelled ASO transfer after timeout of 86400 seconds.
Tue, 31 Jan 2017 17:54:56 CET(+0000):INFO:PostJob This is cancellation retry number 1.
Tue, 31 Jan 2017 17:57:56 CET(+0000):INFO:PostJob This is cancellation retry number 2.
Tue, 31 Jan 2017 17:57:56 CET(+0000):INFO:PostJob ====== Finished to cancel ongoing ASO transfers.
Tue, 31 Jan 2017 17:57:56 CET(+0000):INFO:PostJob ====== Finished to monitor ASO transfers.
Tue, 31 Jan 2017 17:57:56 CET(+0000):ERROR:PostJob Got fatal stageout exception:
Stageout failed with code 1.
There were 1 failed/killed stageout jobs. 1 of those jobs had a permanent failure.
Failure reasons (per document) follow:
- b1e06566b4c004a02d5b87d9e321a8b026803bcb0edc677f3ed91aea:
  ['Cancelled ASO transfer after timeout of 86400 seconds.']
  The last failure reason is permanent.
Tue, 31 Jan 2017 17:57:56 CET(+0000):ERROR:PostJob There was at least one permanent stageout error; user will need to resubmit.
Tue, 31 Jan 2017 17:57:56 CET(+0000):INFO:PostJob ====== Starting to prepare/send report to dashboard.
Tue, 31 Jan 2017 17:57:56 CET(+0000):DEBUG:PostJob Dashboard exit code is defined by Postjob execution.
Tue, 31 Jan 2017 17:57:57 CET(+0000):INFO:PostJob Setting Dashboard state to Aborted. Dashboard parameters: {'MonitorID': '170128_125240:arizzi_crab_VHBB_V25_002_WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-Py8__RunIISummer16MAv2-v6_ext2-v1', 'MonitorJobID': '65_https://glidein.cern.ch/65/170128:125240:arizzi:crab:VHBB:V25:002:WJetsToLNu:HT-100To200:TuneCUETP8M1:13TeV-madgraphMLM-Py8::RunIISummer16MAv2-v6:ext2-v1_3', 'StatusValue': 'Aborted', 'JobExitCode': 60321}
Tue, 31 Jan 2017 17:57:57 CET(+0000):INFO:PostJob ====== Finished to prepare/send report to dashboard.
```

**Comment by belforte** [comment]
Offending line:
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L2082

I will set 60324 instead and define it as a new error code.

**Comment by belforte** [comment]
Actually we had 60317 for this, which was commented out because not used, let's put it back
```
60317: "Forced timeout for stuck stage out.", # (To be used in CRAB3/ASO)
```
in
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py

**Comment by belforte** [comment]
NOPE !!!
PostJob is likely blameless.
The assignement of the exit code 60321 in case of timeout happens here
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py#L260-L272

I need to think more carefully before changing things

**Comment by belforte** [comment]
orginal sin seems to have put in that WMCore file, in the list of gfal error messages, an ASO specific thing
https://github.com/dmwm/WMCore/blame/master/src/python/WMCore/WMExceptions.py#L260
clearly "aso" string should never appear in WMCore :-(

Not clear to me yet how to rework this in a direct way w/o spending inordinate amount of time on it.

**Comment by belforte** [comment]
I will have to postpone this.

**Comment by aabdelal** [comment]
sorry for inconvenience, I have this error "Ended TaskManagerBootstrap with code 4" in my PrivateMC job. My Job log looks fine and the root output file is already in temp directory but transferring failed.
here you can find the postjob log
https://cmsweb.cern.ch/scheddmon/0106/cms1634/170807_112326:aabdelal_crab_GEN_LongLived/postjob.1.2.txt
any help will be appreciated.

**Comment by belforte** [comment]
In the end I see no alternative to fixing WMCore

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMExceptions.py#L263-L265
should refer to 60317

**Comment by belforte** [comment]
the fix in WMCore did not have the precise, needed, capitalization.
Made a new PR
https://github.com/dmwm/WMCore/pull/8980
once that is integrated and tested to work, we can close.

**Comment by belforte** [comment]
changing prio to High to male sure I pay attention, test, and close.

**Comment by belforte** [comment]
still fails in Task Worker Version 3.3.1903.rc3
see e.g.
https://cmsweb.cern.ch/scheddmon/0120/cms225/190313_224259:beaucero_crab_Run2018C/postjob.30.0.txt

**Comment by belforte** [comment]
Should have been fixed in WMCore  1.1.20.pre3. Production TW 1903.rc3 was build with 1.1.20.pre4.
Need to debug.

**Comment by belforte** [comment]
Line 2090 here clearly is wrong
https://github.com/dmwm/CRABServer/blob/a9f0986af32ab1ad95b94f464433c8ec635ede48/src/python/TaskWorker/Actions/PostJob.py#L2085-L2090
should set 60317 there

**Comment by belforte** [comment]
In the end the problem was in PJ not doing the cancellation properly and failing in odd ways (see  #5853 ) and WMCore was OK since the comparison is made after turning ASO message to lower case.
Rather than bugging Alan again and to be safe, I now convert everything to lowercase before comparison, see: https://github.com/dmwm/CRABServer/pull/5859/commits/08189b1140df2aca81c4d245a78d7d072815e387
