### ISSUE TITLE
align FJR JSON file with WMA schema

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5366]
Moving here the mail thread we had.
A useul reference:
https://github.com/dmwm/WMArchive/blob/master/src/python/WMArchive/Schemas/FWJRProduction.py

Also an example from CRAB:
 [crab_fjr.json.txt](https://github.com/dmwm/CRABServer/files/750779/crab_fjr.json.txt)

```
I do not see why we should not have a common structure
with common code. But of course there's some work to
do to change the CRAB code. I defer to Marco and Eric
to guess how much it is and how could do it.
Overall CRAB is very short of skilled manpower,
with simple changes taking very long time to get done.

Stefano

On 03/02/17 14:49, Valentin E. Kuznetsov wrote:
> Stefano,
> that a start. But first view over the data lead me to conclude to difference
> between CRAB JSON file and WMAgent/WMArchvie ones [1]. For instance, "steps"
> sub-structure is somewhat overlap with WMArchive one, but it uses cmsRun
> as a key, instead as a value within a dict. And, there are unique to CRAB
> fiels, e.g. aso_start_time, executed_site, etc.
>
> My question to you/Seangchan can we align CRAB FWJR doc with WMAgent/WMArchive
> schema [1] to avoid usage of explicit keys, such as cmsRun and put
> CRAB specific key-value pairs into individual, CRAB, section.
>
> Also I need to know if file reference will be enforced, i.e. so far I see
> empty skippedFiles, fallbackFiles lists, but I don't see LFNArray, LFNArrayRef,
> etc. ones in CRAB FWJR.
>
> The *COMMON* JSON schema will pay back at analytics step when we'll need to
> do the aggregation, run Spark jobs, etc. since using common schema will
> allow to develop *COMMON* code which will parse CRAB and WMArchive docs.
>
> Best,
> Valentin.
>
> [1] https://github.com/dmwm/WMArchive/blob/master/src/python/WMArchive/Schemas/FWJRProduction.py
>
> On  0, Stefano Belforte <stefano.belforte@cern.ch> wrote:
>> I am afraid we stay at no progress.
>> here's an example
>> https://cmsweb.cern.ch/scheddmon/0198/cms823/170128_125240:arizzi_crab_VHBB_V25_002_WJetsToLNu_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-Py8__RunIISummer16MAv2-v6_ext2-v1/job_fjr.100.0.json
>> there are of course many more similar json files in that directory, which is http-browseable.
>> But I still have to find "selected examples of various kind".
>>
>> feel free to ping, maybe open a twiki or an issue where we can append files for
>> permanent documentation ?
>>
>> Stefano
>>
>> On 02/02/2017 09:51 PM, Valentin E. Kuznetsov wrote:
>>> Hi,
>>> where are we standing on this? I have already code which can push any info
>>> to CERN MONIT system. The sooner I'll see CRAB FWJR example the easier would be
>>> perform its integration.
>>>
>>> Please don't delay that we can move forward.
>>> Thanks,
>>> Valentin.
>>>
>>> On  0, Stefano Belforte <stefano.belforte@cern.ch> wrote:
>>>> yeah.. the part of CRAB server which can do this runs on the schedd's
>>>> I'll collect examples.
>>>> Stefano
>>>>
>>>> On 01/13/2017 03:45 PM, Eric W Vaandering wrote:
>>>>>
>>>>>> On Jan 13, 2017, at 7:15 AM, Valentin E. Kuznetsov <vkuznet@gmail.com> wrote:
>>>>>>
>>>>>> Stefano, Eric,
>>>>>> it is better to see actual docs, rather than implicitly apply they should be
>>>>>> the same. In WMArchive we follow doc schema, therefore to avoid conflicts
>>>>>> or missing bits we need to inspect and verify that CRAB FWJR == WMAgent FWJR.
>>>>>> If this not the case we'll need to adopt the schema to either cover
>>>>>> both types of FWJR or have a separate schema for WMAgent adnd CRAB FWJR.
>>>>>>
>>>>>
>>>>> Or adapt the CRAB FWJR to be the same as the WMAgent one.  Or vice versa.
>>>>>
>>>>> And Stefano, correct, we want to inject from the Schedd or the CRABServer into WMArchive, not from Worker nodes. Most likely the CRABServer since that’s where the massaging that Valentin talks about should happen (it’s in WMAgent as well).
>>>>>
>>>>>
>>>>>> The schema is required since WMArchive converts JSON's to Avro data-format
>>>>>> based on provided schema. Only attributes presented in schema are
>>>>>> written, and data-types are fully typed, i.e. you can't assign
>>>>>> for the same key different data types (it easy to do in python).
>>>>>>
>>>>>> I would appreciate if you'll collect several CRAB FWJR elsewhere to
>>>>>> represent common use cases, e.g. successful job, failed job, aborted job, etc.
>>>>>> Once we inspect those and iterate on possible changes, we may discuss
>>>>>> how to turn on (through WMCore component) the injection of CRAB docs
>>>>>> into WMArchive.
>>>>>>
>>>>>> Best,
>>>>>> Valentin.
>>>>>>
>>>>>> On  0, Stefano Belforte <stefano.belforte@cern.ch> wrote:
>>>>>>> Valentin, is what Eric wrote enough, or should we fish out a couple
>>>>>>> of example CRAB FWJR json doc ?
>>>>>>>
>>>>>>> CRAB does some manipulation to those files, e.g. to add
>>>>>>> errors which may happen after job completed (stageout,
>>>>>>> better error diagnosis based condor info in case job
>>>>>>> was killed...) but I think this only means that we
>>>>>>> already have places where we can adjust the documents
>>>>>>> whichever way you like. I guess we always want to
>>>>>>> archive from the schedd (or WMA node), not from the WN, anyhow.
>>>>>>>
>>>>>>> Stefano
>>>>>>>
>>>>>>> On 01/06/2017 04:07 PM, Eric W Vaandering wrote:
>>>>>>>> I don’t have time to look into all the details at the moment. We should set up a meeting. But CRAB should be FWJR docs. There are differences in terms of steps and so forth, but CRAB actually uses the WMCore runtime code. So we should expend our efforts getting things looking almost the same rather than two different bits doing the same thing.
>>>>>>>>
>>>>>>>> I’ll start by cc’ing Marco and Stefano.
>>>>>>>>
>>>>>>>> Eric
>>>>>>>>
>>>>>>>>
>>>>>>>>> On Jan 6, 2017, at 8:39 AM, Valentin Kuznetsov <vkuznet@gmail.com> wrote:
>>>>>>>>>
>>>>>>>>> Eric,
>>>>>>>>> I adjusted WMArchive code to support multiple document types, e.g. FWJR and CRAB.
>>>>>>>>> If you're serious about storing CRAB docs to WMArchvie a few things should be
>>>>>>>>> clarified:
>>>>>>>>>
>>>>>>>>> - first of all I need to see a "typical" CRAB document to be stored into
>>>>>>>>> WMArchive and we should come up with a schema for CRAB docs. Please note,
>>>>>>>>> that schema should not be changed often. Even though we support schema
>>>>>>>>> evolution the changes should "expand" existing schema rather "shrink" it,
>>>>>>>>> i.e. we can add additional fields, but we can't delete existing one since
>>>>>>>>> it will affect data look-up procedure.
>>>>>>>>>
>>>>>>>>> - we need to clarify data injection rate as well as total data volume to be
>>>>>>>>> stored on HDFS per year
>>>>>>>>>
>>>>>>>>> - we need to decide if we want to put CRAB docs along with FWJR ones or into
>>>>>>>>> a separate HDFS area. Both approaches have cons and pros. For instance,
>>>>>>>>> if we put together FWJR and CRAB then it would be easier to run spark
>>>>>>>>> job over their collection and extract info from them, but a downside is
>>>>>>>>> that total number of docs will increase and may affect look-up procedure.
>>>>>>>>> While storing them in separate areas on HDFS will not affect look-up
>>>>>>>>> procedure, but we'll probably loose ability to scan "both" collections
>>>>>>>>> at a time.
>>>>>>>>>
>>>>>>>>> - eventually we'll also need to come up with an aggregate document structure
>>>>>>>>> for CRAB docs which we'll push to CERN analytics. Therefore it would be nice
>>>>>>>>> to know/discuss what we can extract from those docs.
>>>>>>>>>
>>>>>>>>> If you give me a CRAB document I can come up with its schema and test WMArchive
>>>>>>>>> code to handle it.
>>>>>>>>>
>>>>>>>>> Best,
>>>>>>>>> Valentin.
>>>>>>>>>
>>>>>>>>> P.S. Feel free to add relevant CRAB people to this thread if necessary.
>>>>>>>>
>>>>>

```

**Comment by ericvaandering** [comment]
@vkuznet has taken the first steps of replacing the dashboard with this info by pushing some WMAgent FWJRs to the CERN MONIT. This new infrastructure should be able to satisfy ~real time dashboard-like needs and data-mining needs as well. We should aim to be rid of Apmon sometime this year, I hope. (I'd like to be more ambitious than that)

**Comment by belforte** [comment]
@ericvaandering sure, that's nice. But in order to get rid of Apmon I think it is more urgent for us to have the feeding of HTC classAds to CERN MONIT, so we can replace current data feeding including job submissions, start etc. FJR's are only avaliable when jobs complete, and sometimes not even then. Or do you imagine that info to also proceed via FJR's , sort of like we create and feed to "Valentin" one at jobs submission time and then CRAB server monitors the job, and updates the FJR when something relevant happen and push it along as needed ?

**Comment by vkuznet** [comment]
Stefano,
there is no need to discuss what should be feed first or second. It does not
matter. We developed code how to do that.

The question here is how to make CRAB docs to be complaint with common schema.
I think you understand benefits of common schema which will allow apply
the same set of tools and make aggregation easy.

If HTC classAds can be complaint with schema it is even better, but it is not
required either.

Best,
Valentin.

**Comment by belforte** [comment]
yes, no question about "the question here". Docs should be made compliant.
BTW, what will be the mechanism to geed those FJR's to "whatever" ?
Will schedd's need to run something to push them, will something come read those ?
If there's going to be a small script which read and feeds the FJR's, maybe it can start by 
reformatting the current ones. THat'd be faster then changing the format to begin with, as this 
requires changing the code which writes them and the code which uses them atm.

**Comment by vkuznet** [comment]
Stefano,
the mechanism is implemented as part of WMCore component. Such component
takes docs and send POST request to WMA server, that's it. If schedd relies
on WMCore everything is already done for it, it will need to call proper
component.

I'm CC'ing Seangchan and Alan (@ticoann, @amaltaro) to answer details about WMCore component
which push docs to WMArchive.

Valentin.

**Comment by belforte** [comment]
so IIUC it is on us to implement something which calls this component "at the right time, from the right place, with the right credentials". I guess @mmascher can talk with @amaltaro. Next week I'll also be at CERN.
I will still like to understand the whole design though, including the role HTC class ads play, monitoring of transfers etc.

**Comment by vkuznet** [comment]
Stefano,
yes, you collect your docs and invoke WMCore call.

Which design are you talking about? WMArchive or CERN MONIT?

The former can be found here [1] and later was discussed during last C&O week,
but see all details here [2] with all relevant links to CERN MONIT
architecture.

1. https://github.com/dmwm/WMArchive/wiki/WMArchive-architecture
2. https://github.com/dmwm/WMArchive/wiki/MONIT-and-AMQ-support-in-WMArchvie

**Comment by amaltaro** [comment]
The schedd itself doesn't do anything, besides transferring back to the agent (in your case it would be TaskWorker, I think) the CMSSW FJR.

Then on the agent side, this component
https://github.com/dmwm/WMCore/blob/master/src/python/WMComponent/ArchiveDataReporter/ArchiveDataPoller.py#L39

reads the docs available and post it to WMArchive server (in slices and not more than a fixed value per cycle).

**Comment by belforte** [comment]
thanks Alan, we'd need to run that on the schedd, but that does not change things.

**Comment by belforte** [comment]
@vkuznet about design, when you asked
> Which design are you talking about? WMArchive or CERN MONIT?
I am talking about the overall plan on how to replace current CRAB monitoring functionality that we have via the old job dashboard, the FTS dashboard and their linking, gwmsmon and the kibana3 dashboards build so far for ASO and CRAB. A concrete work plan, not the simple "we'll do it using new CERN MONIT setup". I assume there will be phases, steps, developments and many people will have to collaborate.

**Comment by vkuznet** [comment]
I'll leave it up to CRAB developers to decide, but in WMArchive we took a
gradual approach, i.e. we develop data streaming to CERN MONIT and still write
everything as is in WMArchive. Doing so we duplicate our aggregated info
into both sinks, but it allows us to experiment/develop CERN MONIT plots
while keeping existing ones from WMArchive infrastructure. You may do that as
well. Streaming data into additional destination does not affect your current
infrastructure and you can play around with new source to adjust it as you wish
to match you current one(s).

**Comment by belforte** [comment]
yes, I am assuming we do that as well. But when Eric suggests a definte timeline to get rid of ApMon 
(which is a goald I agree on), I have to ask myself what's needed to get there !
CRAB monitoring is not based on the FJR's, sending those to "WMArchive" is good, but not an 
immediate replacement for all functionalities we have.

**Comment by belforte** [comment]
Of course we will not do this by last release.
I am moving to April, but the milestone here is really for @mmascher to open one or two ad hoc issues about the work to be done with some time estimate.

**Comment by belforte** [comment]
@mmascher I suspect this can be closed, maybe with a short explanation of how you solved the WMArchive thing in the end (IIRC a single FJR )

**Comment by belforte** [comment]
THis was solved with the current WMArchive Uploader
