### ISSUE TITLE
duplicated function in ServerUtilities

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5377]
Seems to me that getLock is defined twice with identical code in
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L331-L335
and in
https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L441-L445

No idea why python does not complain, but I would think that there should
be only one definition.

Or do I simply do not understand something ?

**Comment by emaszs** [comment]
There definitely shouldn't be two definitions, but python simply overwrites the previous one with the next one, so it does no harm. I missed this when merging the autosplitting changes.
