### ISSUE TITLE
TW goes into infinite loop while doing splitting

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5418]
see:
https://cms-logbook.cern.ch/elog/Analysis+Operations/1281

I verified that a task on that dataset with split by File puts the TW into an infinite loop.
Interestingly one cant' even use strace to tell what's going on, it prints nothing, even waiting hours, while CPU usage keeps increasing.

This basically kills one worker slave every time it happens, so we need to find out what's going on.

**Comment by emaszs** [comment]
I think there's a bug here https://github.com/dmwm/WMCore/blob/1.1.0_crab/src/python/WMCore/JobSplitting/FileBased.py#L64 which causes the splitting to be slow for datasets with a lot of files. The list here gets sorted after every new lfn addition, which doesn't really make sense to me and is very slow for ~160k files. I didn't run it for the complete dataset but it took around 15 minutes to get through 35k iterations and it was slowing down with each one, which would explain the stuck tasks.

**Comment by belforte** [comment]
Code does indeed look like a typo in indentation. Since you seem to have at hand a way to run this sort of interactively, maybe you can also test the fix ?

**Comment by emaszs** [comment]
I've tested it and the problematic dataset was processed in a reasonable time. I think this can go into the new taskworker being deployed tomorrow.

**Comment by mmascher** [comment]
FYI Other splitting algorithms have a similar piece of code and have the right (fixed) indentation

**Comment by belforte** [comment]
@emaszs did you fix this then ? Can you close, in case ?

**Comment by emaszs** [comment]
Yes, this should be fixed now with https://github.com/dmwm/WMCore/pull/7695

**Comment by belforte** [comment]
ah.. right, I forgot that the fix is in WMCore.
is this in the WMCore branch which we deploy now ?

**Comment by emaszs** [comment]
Yes, prod Task Worker is using the WMCore tag which has the fix.
