### ISSUE TITLE
Be able to use new DBS APi with #event/lumi

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5432]
Make sure CRAB runs as now with no issues when DBS API's are changed.
From Eric meeting notes in a mail with subject "Re: Desire to expand the DBS schema for events/lumi" :
```
On 03/01/2017 06:02 PM, Eric W Vaandering wrote:
> 
> - We agreed that all APIs that currently return run-lumi pairs will now return run-lumi-event
> triplets. This makes things consistent for DAS and no new parameters for DBS.
```
I guess we'll need a DBS version with the new API's for a real test.

**Comment by ericvaandering** [comment]
What I was more worried about is that FWJR parsing doesn't break when new data starts showing up from CMSSW. But I've verified it doesn't cause problems in WMCore and you are using the WMCore part, you are good to go.

Verifiying that we can use the API is great. @yuyiguo  will ensure this, of course.

**Comment by belforte** [comment]
ah.. I had not realized that risk exist, thank Eric.
Thanks also to Yuyi.

**Comment by emaszs** [comment]
Fairly certain we have this covered already
