### ISSUE TITLE
add #events/Lumi to FileMetadata

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5434]
when number of events in each lumi is avaiulable, it should be propagated to File Metadata

**Comment by belforte** [comment]
@belforte and @mmascher discussed this with @ericvaandering during CRAB meeting on June 6 and agreed that it is important to do this now.
@emaszs @dciangot can you get this done by July release ?

this is hopefully trivial since it simply means the dictionary we put in metadata has one key more, but need to to verify of course, and may have the impact of making metadata larger, failures more likely etc. Let's hope it is not so disruptive to mean that we need a different way to manage those metadata

**Comment by belforte** [comment]
@dciangot I think we can close, right ?

**Comment by dciangot** [comment]
yes
