### ISSUE TITLE
insert #lumi/event information in DBS when publishing user dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5435]
this is really for ASO. But to make things easier to track I open it here as well:
when information about number of events in each lumi in each output file is available, it should be inserted in DBS when publishing output data

**Comment by belforte** [comment]
@belforte and @mmascher discussed this with @ericvaandering during CRAB meeting on June 6 and agreed that it is important to do this now.
@emaszs @dciangot can you get this done by July release ?

**Comment by emaszs** [comment]
@belforte I think July is reasonable. At least for the PostJob/CRABServer part of uploading metadata, I have some code which should work (in theory), while also being backwards compatible with old PostJobs. Need to test it still.

**Comment by belforte** [comment]
good. My main concern is exploding metadata size. Once the modified dictionary is propagated I expect publication in DBS to be straightforward

**Comment by belforte** [comment]
@dciangot can you comment if this was done ? I think so, but want to be sure.

**Comment by dciangot** [comment]
yes, done
