### ISSUE TITLE
Drop files with publish = 0 in statistics query (RESTFiletransfers)

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5453]

**Comment by belforte** [comment]
@dciangot is this part of https://github.com/dmwm/CRABServer/issues/5513 ?
can you take care ? Or should @mmascher be the one to do the code change ?

**Comment by dciangot** [comment]
I can do that and @mmascher can review afterward I suppose.

**Comment by belforte** [comment]
@dciangot what's the status here ?
