### ISSUE TITLE
catch early illegal Output LFN's

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5504]
e.g. when there is a double slash in the path.
Need to validate using lexicon as soon as possible in the flow.
See
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2933/1/4.html

Realated issue: #4588

**Comment by PerilousApricot** [comment]
I spent some time digging through DBS' code when I saw the user's report, and I'm confused about what the error was. This is the underlying error that DBS is throwing:

https://github.com/dmwm/DBS/blob/34efdec694c31c5084abb2ebf3358f134a96ea23/Server/Python/src/dbs/utils/DBSInputValidation.py#L27

```
regexp = r'^/store/([A-Za-z0-9._\-/])+/([A-Za-z0-9._\-])+(.root|.lhe(.xz){0,1})$'
```

Perhaps I'm misreading the regex, but it doesn't look like double slashes are prohibited.

**Comment by belforte** [comment]
I tried reply by mail, which seems to have failed. So am pasting my reply below.
Also adding a note: DBS is more liberal in accepting LFN's to look up then in LFN's to write,
since old LFN's from DBS2 era have to still be accessible, while there was a conscious effort to limit
chaos in DBS3.

I passed through WMCore's lexicon the file name with and w/o the double slash,
only the latter passed. I did not save python lines to paste here,
I guess we should "standardize" a simple standalone
script to help these checks. Now... it is surely possible that DBS validation
is not the same as what Lexicon provides, but it would be very unwelcome 
Let's assume Lexicon.py is the authoritaty on this, and everybody else has
to use or reproduce it. 

It seems to me tath the Lexicon check does not allow double `/`, but I really bad with regexp's: 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L314-L317
LFN has to fail all of those 4 regexp's to be illegal, IIUC.

**Comment by belforte** [comment]
the way to check is:
```
testLfn=<the LFN to check>
from WMCore import Lexicon
Lexicon.lfn(testLfn)
```
but  Lexicon.lfn checks against a series of regexp and only fails if all gave errors, so there' s no solid way to say what the problem is, it would be enough for one regexp to be OK.

**Comment by belforte** [comment]
the line that should validate the LFN is
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L347

**Comment by belforte** [comment]
not really. that line is only some preliminary sanity check, a more proper test could be done in here
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L63-L78
but that only has the LFN_BASE to look at. A check there would not catch bad stuff from e.g. the output file name in cmsRun.
I'd rather do the check later inside the TW when the output PFN is prepared.

**Comment by belforte** [comment]
hmm.. looks like LFN path and file name are only combined in cmscp.py. Too late.
https://github.com/dmwm/CRABServer/blob/master/scripts/cmscp.py#L1679

**Comment by belforte** [comment]
so I think I will add a check in the TW (easier to debug and change than REST) using the DB params for out lfn dir and out file name. Assuming that what CRAB adds for has, directory number, datasetname etc. is allright. I.e. only check what user specified. This could go into DagmanCreator
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py
