### ISSUE TITLE
put dag_bootstrap (Task) in HOLD, not remove, at CRAB_TaskEndTime

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5508]
see point 5. here
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

current task have instead
```
belforte@vocms0194/CRABServer> condor_q 7674510.0 -l|grep -i period
PeriodicRemove = ( ( time() - CRAB_TaskSubmitTime ) > 3456000 )
PeriodicRelease = false
PeriodicHold = false

```

**Comment by belforte** [comment]
@mmascher any update ? Did you maybe did this already w/o reference to this issue ?

**Comment by emaszs** [comment]
Yes, @mmascher did this, https://github.com/dmwm/CRABServer/commit/fccc08c00b3f437c49da9b0720348a6e6572b87c#diff-4ebe5cee1489f0300479a5b30ec336f5R485. Closing.
