### ISSUE TITLE
use  new classAd  CRAB_TaskEndTime to decide when to clean schedd directories

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5510]
see
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

of course have to wait until all tasks have this defined

**Comment by todor-ivanov** [comment]
now testing in production. See the commit in SubmissionInfrastructurScripts bellow:

https://gitlab.cern.ch/CMSSI/SubmissionInfrastructureScripts/commit/772b8aa961b0c7a7099023800a5743476acbbd25

**Comment by belforte** [comment]
@todor-ivanov confiremed that this is now done and in production
