### ISSUE TITLE
deprecate crab kill --jobId

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5512]
see May 30 meetiung minutes
https://indico.cern.ch/event/640918/note/
and with reference to
https://github.com/dmwm/CRABServer/issues/5472

need to fix documentation (if any) and make client/server refuse the option and/or print proper messages

**Comment by belforte** [comment]
@emaszs I will fix documentatoin, can you change the client ?

**Comment by emaszs** [comment]
`crab kill --jobids` will be disabled on the client with https://github.com/dmwm/CRABClient/commit/bc460d37f3dc07e6df182340feefb3c64b3d919a, I'll also get rid of `--jobids` code in the server.

**Comment by belforte** [comment]
I could not find a place where usage of `crab kill --jobid` was documented in the pages pointed to from https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideCrab. So I think this is all done now.

**Comment by belforte** [comment]
I added some "documentation" for the crab kill command (there was none) which hopefully makes it clear what and why of this:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Commands#crab_kill
