### ISSUE TITLE
implement proper handshake between PostJob and ASO

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5513]
with reference to minutes of May 30 meeting
https://indico.cern.ch/event/640918/
in particular point `1. workflows kill/resubmit`
and to @dciangot diagrams:
https://github.com/dmwm/CRABServer/wiki/CRAB-Recovery-after-kill-design
https://github.com/dmwm/CRABServer/wiki/Kill-and-resubmission-workflow-discussion

the communication protocol between PostJob and ASO should be:
1 PJ writes a new entry in TransferDB table in Oracle with xfer status = NEW
2. ASO polls Oracle, finds the document, sets xfer status to acquired
3. ASO submits xfer job to FTS
4. ASO sets xfer status to submitted
5. eventually ASO sets xfer status to Done or Failed
6. PJ polls Oracle, when xfer status Failed is detected decides if to resubmit or not etc.
7. when PJ detects xfer status Done, if publication in DBS for this file is enabled, PJ uploads file metadata to Oracle
8. if metadata upload was OK, PJ sets publication status to NEW in the TransferDB table for this file
9. PJ ends
10. ASO periodically polls TransferDB table in Oracle for files to publish and does the needed things

The current implementation of the PJ instead does 7. at the same time as step 1. creating a race between steps 7. and 10. and difficult-to-debug failure if step 7. fails.

**Comment by belforte** [comment]
@dciangot please review. In particular IIUC no chance is needed on ASO side, only PostJob fixes

**Comment by dciangot** [comment]
Yes, that's all good. The only change needed with this solution is on PJ
