### ISSUE TITLE
postjob never able to retrieve transfer failure reason 

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5526]
Every time there is a failure for a transfers the postjob looks like this (*) showing failure reason: 'Failure reason unavailable.'

It is most probably due to a bug in the query GetTaskStatusForTransfers_sql that is not returning the transfer failure reason.

(*)
https://cmsweb.cern.ch/scheddmon/059/cms1299/170621_110351:dciangot_crab_asotest3dev4/postjob.116.0.txt

**Comment by belforte** [comment]
the bad thing here is that PostJob consider all transfer failures recoverable and resubmits the job. I have seen a couple of days ago a task where the user had no permission to write at the destination site.. several tasks, thousands of jobs :-(
Can you put this close to the top of your  priority list ?
