### ISSUE TITLE
do not ship libcurl to the WN's

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5527]
we do not need it anymore since we do not write to the DB from the WN
And in any case it is a fragile dependency in view of having to run on multiple architectures (SL6/7 e.g.)
If we need any binary, should rely on what is in CVMFS

**Comment by emaszs** [comment]
I assume this is as simple as removing it from our TW runtime tarballs, for example here [1]?

[1] https://github.com/dmwm/CRABServer/blob/32d43b0b5c9caf8c834a35d301423b4d6a8b397d/bin/htcondor_make_runtime.sh#L47

**Comment by belforte** [comment]
hope so, i.e. there's nothing else which checks for it, adds it, use it.. whatever

**Comment by belforte** [comment]
it will come automatically since we will remove libcurl from the tarball to avoid shipping it to the schedd's  and use puppet or CVMFS to make libcurl available to the schedd's.
FOllow up in:  https://github.com/dmwm/CRABServer/issues/5528
