### ISSUE TITLE
properly manage libcurl dependency in TW and schedd's

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5528]
currently e.g. the schedd's rely on libcurl to be send from the TW via the runtime tarball
https://github.com/dmwm/CRABServer/blob/master/bin/htcondor_make_runtime.sh#L38-L52

This is fragile, since we rely on a frozen libcurl.so put in the github repository long ago
https://github.com/dmwm/CRABServer/tree/master/lib

Should instead use the one from COMP environment,  so that it is also compatible with the gcc version.
And of course need to take care of schedd and TW possibly using different op.system e.g. SL7/SL6.

I think best option is that schedd's have the COMP environment available and postjobs pick libcurl from there in order to talk to cmsweb REST. This is likely a common need for WMA, so we could share configuration in puppet etc. Worth to talk with @amaltaro 

Other strategies may work, even better, but we should outgrow relying on a .so in github
e.g. it may be that system libcurl works on SL7 so we put our own on SL6 schedd's via some puppet trick

**Comment by todor-ivanov** [comment]
> I think best option is that schedd's have the COMP environment available and postjobs pick libcurl from > there in order to talk to cmsweb REST.

I will try to do it, but need more information. For the moment the picture related to the COMP environment is a little bit blurred to me.

**Comment by emaszs** [comment]
So looking slightly deeper, I think it's fine to move the library to wherever we deem convenient and I agree that it's not needed on the WNs. However, the libcurl we're currently using is compiled with openssl (as per comment from [1]). The libcurl that's present on the schedd by default does not it seems [2]. And this does break the communication with CRABServer from what I can tell [3] , so I think if we change the place where we're taking it from, it should still be the same thing we have currently. I don't think we have such a package somewhere in cvmfs, of course we can put it there ourselves if needed.

[1] https://github.com/dmwm/CRABServer/blob/master/bin/htcondor_make_runtime.sh#L38-L52
[2]
pycurl.version using our own libcurl
`'libcurl/7.19.7 OpenSSL/1.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2'`
pycurl.version using the default libcurl
`'libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2'`
[3] adjust_out.txt on the schedd
```
2017-07-04 11:29:51.117895: Webdir has been set up. Uploading the webdir URL to the REST
2017-07-04 11:29:51.117999: Uploading webdir http://vocms059.cern.ch/mon/cms1425/170704_112926:erupeika_crab_libcurl_removed_from_TW_tarballs_test1 to erupeikadev.cern.ch
2017-07-04 11:29:51.277805: Traceback (most recent call last):
  File "AdjustSites.py", line 245, in updateWebDir
    server.post(uri, data=urllib.urlencode(data))
  File "/data/srv/glidecondor/condor_local/spool/9504/0/cluster6209504.proc0.subproc0/RESTInteractions.py", line 85, in post
    return self.makeRequest(uri = uri, data = data, verb = 'POST')
  File "/data/srv/glidecondor/condor_local/spool/9504/0/cluster6209504.proc0.subproc0/RESTInteractions.py", line 128, in makeRequest
    capath=caCertPath)#, verbose=True)# for debug
  File "/data/srv/glidecondor/condor_local/spool/9504/0/cluster6209504.proc0.subproc0/WMCore/Services/pycurl_manager.py", line 207, in request
    raise exc
HTTPException: url=https://erupeikadev.cern.ch/crabserver/dev/task, code=403, reason=Forbidden, headers={'Date': 'Tue, 04 Jul 2017 11:29:51 GMT', 'Transfer-Encoding': 'chunked', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=6050 t=1499167791270880', 'Server': 'Apache'}
```

**Comment by belforte** [comment]
it is an old problem that libcurl in linux 5/6 does not have SSL. I do not know if moving to SL7 will solve.
But a proper libcurl is in the CMSSW distribution, and there shold be one in COMP as well.
I suggest to start looking at how WMA manages this. We may have to keep the libcurl from GIT in the runtime tarball sent by TW to schedd's for use in the Post/Pre jobs, TP etc.  but would be good not to send it to WN's

**Comment by belforte** [comment]
@todor-ivanov remember to check this in the context of moving to SL7, if problem goes away, we close.

**Comment by todor-ivanov** [comment]
For the current situation I think  we already distributed the correct version of libcurl but Yes I will check for this in SLC7 and hopefully will nt have this problem there. Thanks for noticing.

**Comment by belforte** [comment]
the point is that I do not want CRAB TaskWorker to distribute its own version of licurl, whether correct or not.

**Comment by belforte** [comment]
we are getting there, see:
https://cms-logbook.cern.ch/elog/Analysis+Operations/2602

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/5873
