### ISSUE TITLE
Different method for setting  the +AccountingGroup calssAd.

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/CRABServer#5547]
After the upgrade to condor 8.6.3 the Site Support Team noticed that Hammer Cloud jobs were failing. Here is the ticket with the results from the investigation on that [1]. As a summary there are different methods for setting the string for the +AccountingGroup classAd both in and outside condor. In CRAB the method with creating the string before passing it to condor is used [2] (which is the old method according to the HTCondor documentation [3]). We should move to the newer one at some point.

[1]
https://ggus.eu/?mode=ticket_info&ticket_id=129556

[2]
https://github.com/dmwm/CRABServer/blob/e7e1c2f917ce4cc33df919c37d309b143b8772db/src/python/TaskWorker/Actions/DagmanCreator.py#L499

[2]
https://research.cs.wisc.edu/htcondor/manual/latest/3_6User_Priorities.html#sec:group-accounting

**Comment by emaszs** [comment]
Fixed with https://github.com/dmwm/CRABServer/pull/5549
