### ISSUE TITLE
reduce minimum enforced wall clock time to 1min

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5552]
@mmascher I thought you did this already, but I found this
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L47
and this
https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L29-L31

Maybe you never did ? Or am I confused.
I believe that we should not sleep is job was OK and if there was an error should reduce from 20 to 10min.

While the sleep after error has some usefulness in mitigating black holes, the one for OK job had as only rational to make user "pay" with reduced share the bad habit of running awfully short jobs. But in the end this never acted as incentive to do better and we rather introduce automatic splitting. While we are criticised for wasting resources on sleeping jobs.

I am not changing right away since in light of the fact that I thought this was done, am worried that maybe I miss something.
What's your take here ? Are those two places the (only) ones to change ?

**Comment by emaszs** [comment]
There is no penalty currently because https://github.com/dmwm/CRABServer/blob/master/scripts/gWMS-CMSRunAnalysis.sh#L32. I thought this behavior was by design as there were some talks about removing(?) it previously, though now I see it's a line mistakenly left for autosplitting debugging. Should I set it to be 10 minutes?

**Comment by belforte** [comment]
See my previous comment for the rational.
Sleep time should be:
- 0 if job was successful
- 10 (or 5) min if job failed
I am currently a bit puzzled about when those lines are relevant, this a shell function named (unappropriately I guess) `finish` which is apparently only executed if `trap` is called.
I think that earlier I thought this to mean "when there is an external signal", but now I see that `trap on signal EXIT` means "executed when shell is exited" so it should be set to dummy (can keep the function in case we need it for something else or want to introduce a sleep later).

Now.. let's find out where it is that we put the sleep in case of error. I believe it is the line I mentioned earlier:
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L47

**Comment by belforte** [comment]
update. The PLAN is:
Originally we had two motivation for the 20min enforced minimum time:

    avoid black holes
    charge users some CPU i.e. HTCondor share if they fill the system with buggy, failing jobs
    But in the end 2. is not working and for 1. a shorter time is good enough, esp. with the increasingly extensive validation that the pilots do.
    At the same time those sleeping jobs are affecting the CPU/Wall clock time which funding agencies look at.
    So we must change to:
    A) no sleep time for successful jobs
    B) 5 min overall for failing jobs (to avoid black holes)

**Comment by belforte** [comment]
Indeed as @emaszs pointed out in https://github.com/dmwm/CRABServer/issues/5552#issuecomment-320504993
currently good jobs only add 1 sec of sleep time, even if the stdout is a bit "alarming":
```
Job Running time in seconds:  178
Job runtime is less than 20minutes. Sleeping  1
```
I will change so that things are more clear.

**Comment by belforte** [comment]
failing jobs have instead
```
==== Failure sleep STARTING at Wed Sep 13 14:07:14 2017 ====
Sleeping for 1164 seconds due to failure.
==== Failure sleep FINISHING at Wed Sep 13 14:26:39 2017 ====
```
which indeed comes from the lines indicated initially:
https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L47

**Comment by belforte** [comment]
At times jobs can fail and still have no sleep time added.
When the failure is early enough in the wrapper flow that `CMSRunAnalysis.py` is not started. E.g.
```
======== CMSRunAnalysis.sh STARTING at Wed Sep 13 17:27:34 GMT 2017 ========
Local time : Wed Sep 13 19:27:34 CEST 2017
Current system : Linux cfarm008.ts.infn.it 2.6.32-696.6.3.el6.x86_64 #1 SMP Tue Jul 11 14:22:34 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
==== CMSSW pre-execution environment bootstrap STARTING ====
+ '[' -f /cvmfs/cms.cern.ch/cmsset_default.sh ']'
+ echo 'LCG style'
LCG style
+ set +x
+ declare -a VERSIONS
+ VERSIONS=($(ls $VO_CMS_SW_DIR/$SCRAM_ARCH/external/python | egrep '2.[67]'))
++ egrep '2.[67]'
++ ls /cvmfs/cms.cern.ch/slc6_amd64_gcc472/external/python
+ PY_PATH=/cvmfs/cms.cern.ch/slc6_amd64_gcc472/external/python
+ echo 'python version: ' 2.6.4
python version:  2.6.4
+ set +x
==== CMSSW pre-execution environment bootstrap FINISHING at Wed Sep 13 17:27:35 GMT 2017 ====
==== Python discovery STARTING ====
Python found in /cvmfs/cms.cern.ch/slc6_amd64_gcc472/external/python/2.6.4
./CMSRunAnalysis.sh: line 109: /cvmfs/cms.cern.ch/slc6_amd64_gcc472/external/python/2.6.4/etc/profile.d/init.sh: Input/output error

real	0m1.184s
user	0m0.005s
sys	0m0.003s
CMSRunAnalysis.sh complete at Wed Sep 13 17:27:36 GMT 2017 with (short) exit status 1
======== CMSRunAnalsysis.sh at Wed Sep 13 17:27:36 GMT 2017 FINISHING ========
======== python2.6 bootstrap for stageout at Wed Sep 13 17:27:36 GMT 2017 STARTING ========
+ '[' -f /cvmfs/cms.cern.ch/cmsset_default.sh ']'
+ set +x
+ '[' -e /cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.6/etc/profile.d/init.sh ']'
+ set +x
+ command -v python2.7
+ rc=0
+ set +x
Found python2.7 at:
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.6/bin/python2.7
======== python2.7 bootstrap for stageout at Wed Sep 13 17:27:36 GMT 2017 FINISHING ========
======== Attempting to notify HTCondor of file stageout ========
/localdisk/home/pilcms005/home_cream_500528679/CREAM500528679/glide_2KACeZ/execute/dir_25875/condor_exec.exe: line 219: condor_chirp: command not found
======== Stageout at Wed Sep 13 17:27:36 GMT 2017 STARTING ========
Traceback (most recent call last):
  File "cmscp.py", line 24, in <module>
    from ServerUtilities import cmd_exist, parseJobAd, TRANSFERDB_STATES, isCouchDBURL
ImportError: No module named ServerUtilities
======== ERROR: Unable to initialize WMCore at Wed Sep 13 17:27:36 GMT 2017 ========
Cannot find condor_chirp to set up the job exit code (ignoring, that's for monitoring purposes)
Job Running time in seconds:  3
Job runtime is less than 20minutes. Sleeping  1
```

**Comment by belforte** [comment]
With reference to attached, hopefully self-explanatory, plots.

we currently have:
1- a small fraction of CRAB jobs which fail and exit within seconds
2- a large number (~50%) of failed CRAB jobs which are forced to sleep up to 20min
3- good jobs which are getting shorter and shorter, running a few min most of times
4- a small mistery to be understood

1. was not expected, but is understood, anyhow it is not a problem
2. is what I am fixing now, but those are so many that 10 or 5 min sleep seems still
   too much. But I do not dare to cut to 0 sleep and I do not like anyhow
   jobs which fail and restarts in 3 seconds anyhow.
   So I amd thinking of starting by putting 1 minute minimum for everything
3. we can't do anything about this until automatic splitting is in widespread use
   yet in the past this was better, let's not get too carried away.
4. I am looking at it, should not change the big picture

Given 3. CPU-efficiency can't be good :-(

URL's to kibana if you want to make same/similar plots:
https://monit-kibana.cern.ch/goto/46043d3d69da004dacb6f68e7aa48b78
https://monit-kibana.cern.ch/goto/8a03a02795bb4ca2d90ef1e5c6e72662
https://monit-kibana.cern.ch/goto/80263ed21f4eb933f6b50f89e4303fca
![wallclockcrab](https://user-images.githubusercontent.com/1837785/30424213-882c8f12-9945-11e7-84f1-d924f0d985f0.png)

**Comment by belforte** [comment]
So I changed this issue's title to say "reduce to 1minute"
