### ISSUE TITLE
workflow api subresource=data timing-out

### ISSUE THREAD

**Issue by vlimant** [dmwm/CRABServer#5565]
Some of our analysis tools are failing because this call

https://cmsweb.cern.ch/crabserver/prod/workflow/?workflow=170815_051556:sixie_crab_prod_Run2RazorNtuplerV3p15_ToCERN_Data_Rereco2016_v5_78e00cf22d4f23cd7fee6369028a9ec8_v2&subresource=data&limit=-1

which used to work for some other tasks, is now timing-out. How can I make this call to function ? Is there a way I can set limit=10&offset=0, then cycle on offset+=1 until exhausted.

Please indicate a possible alternative rest api I can use to get the list of the lfn of the outputs

**Comment by belforte** [comment]
Seems a question for computingTools forum, not a GIT issue. I.e. there's no indication that a code change is needed.  AFAIU you are basically re-implementing the CRAB Client. That's not advised of course, buut if you want.. feel free. In this case you may want to look at existing implementation in order to figure out how to do things, and be aware that it is not a public API, things may change w/o notice and there's no support.
Why can't you use the python command API ?
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABClientLibraryAPI

**Comment by vlimant** [comment]
@belforte I will take a look at the crab api. 
I redirected my question to computing tools.

Regardless, it will end up making a call to that url above if I want to get the lfn for each of the output. How do we get this without timing-out ?

I hardly think that having a timing-out API is not a GH issue, and I'd like to know what is causing it to time out for what looks like a trivial call.

**Comment by vlimant** [comment]
https://cmsweb.cern.ch/crabserver/prod/workflow/?workflow=170815_051556:sixie_crab_prod_Run2RazorNtuplerV3p15_ToCERN_Data_Rereco2016_v5_78e00cf22d4f23cd7fee6369028a9ec8_v2&subresource=data&jobids=1-500 does not seem to function

**Comment by vlimant** [comment]
I still think that https://cmsweb.cern.ch/crabserver/prod/workflow/?workflow=170815_051556:sixie_crab_prod_Run2RazorNtuplerV3p15_ToCERN_Data_Rereco2016_v5_78e00cf22d4f23cd7fee6369028a9ec8_v2&subresource=data&limit=-1 should not timeout, what is wrong internally that it does ?

**Comment by belforte** [comment]
this works:
```
python
>>> from CRABAPI.RawCommand import crabCommand
>>> cdir='/afs/cern.ch/user/b/belforte/WORK/CRAB3/TC3/dbg/sixie/crab_prod_Run2RazorNtuplerV3p15_ToCERN_Data_Rereco2016_v5_78e00cf22d4f23cd7fee6369028a9ec8_v2'
>>> res = crabCommand('getoutput',dir=cdir,dump=True,jobids='1-500')
```

**Comment by belforte** [comment]
even if it took almost 4 minutes for 500 jobids, doing less jobs at a time may help, given that data is retrieved via cmsweb which has a 5min limit on fronted connections IIRC
```
>>> time.time()
1505304818.517881
>>> res = crabCommand('getoutput',dir=cdir,dump=True,jobids='1-500')
time.time()
>>> time.time()
1505305046.215267
>>> 1505305046.215267-1505304818.517881
227.69738602638245
>>> 

```

**Comment by vlimant** [comment]
can the timing out restapi be totally deprecated ?

**Comment by belforte** [comment]
I wish I knew. The person who did the work left abruptly two weeks ago.
One would need to check if it is used in any other place in CRAB than crab status.
