### ISSUE TITLE
Update WMCore version to make local stageout work again at CERN

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#5566]
https://cmsweb.cern.ch/scheddmon/0121/cms596/170818_070053:oglez_crab_og08_18_090049_SingleElectron_2017B_Prompt_v1_MINIAOD/job_out.190.1.txt

It seems like when there is a stageout error cmscp is exiting with: TypeError: 'NoneType' object has no attribute '__getitem__'
We need to fix this.

Also, something weird is going on with the xrdcp plugin that is giving: `xrdcp: Invalid option, '--wma-disablewriterecovery'.`

**Comment by belforte** [comment]
the error with the xrdcp plugin that is giving: xrdcp: Invalid option, '--wma-disablewriterecovery' is rather harmful since it makes CERN always fail local stageout. I hope that WMA jobs do not fail same way. So why is CRAB affected ? Maybe we are not using correct /altest WMCore or not using correctly ? See
https://github.com/dmwm/WMCore/commit/447080bf0bd4ce8a6d1665a85ca9431b776300b3
maybe worth that @mmascher and @amaltaro have a chat next week and sort out how to use xrdcp pluging ? But mostly how to keep crab branch properly functional :-(

**Comment by amaltaro** [comment]
@mmascher @belforte would you still have the logs for the "cmscp" error? BTW, are you calling cmscp the posix cp stage out? Otherwise I don't know which plugin is that.

For the --wma-* option, Dirk updated the CERN site-local-config and we updated the WMCore code (as you found out) to reflect those changes. So the stage out command behaviour is slightly different now (well, for at least a couple of months now). Sorry, I thought CRAB was using the stage out plugins under Plugins (not Backends). If CRAB is using a WMCore tag >= 1.1.4.pre5, then it should have all these changes.

**Comment by belforte** [comment]
thanks @amaltaro . Sorry I did not notice you posting until now.
Here's a recent log [1], as usual the stageout part is not that easy to read (we already had a thread with @ticoann about improving WMCore in that area). In a way the plan always was 'to stage out locally to site in exactly the same way as production does' exactly to make things easier.
Now I hope you can sort out things with @mmascher , because I do not understand the difference Plugins and Backends (oh my ! do things really need to be so confusing ?) and you make it sound like in CRAB since a few months we picked some but not all needed changes. That's be really something to fix ASAP. In particular we do not want CRAB and main branch in WMCore to diverge to the point where we can't easily converge again !
If I could have a saying there, we should not have a separate branch, WMCore should be common and kept working for both CRAB and WMA. Things which can not have a stable public interface should be moved out of WMCore into the tool-specific repositories.

But I am really not equipped to discuss the details of WMCore tags and branch, at least now and here.


[1]
https://cmsweb.cern.ch/scheddmon/0195/cms852/170928_155339:gsfs_crab_Hydjet_Quenched_MinBias_Cymbal5Ev8_GEN_SIM_XeXe_9_2/job_out.123.0.txt

**Comment by belforte** [comment]
anyhow I hope everybody agrees that if Dirk changes something and that breaks CRAB stageout, w/o CRAB code having changed, it is not a CRAB problem ! 
I leave to @ericvaandering and JR to find the way to avoid this kind of things to happen again

**Comment by belforte** [comment]
@mmascher do we still have a problem with WMCore / CRAB being misaligned here ? I.e. are we using a good WMCore tag now ?

**Comment by belforte** [comment]
Error with xrdcp plugin is still there :-(
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2702.html

**Comment by belforte** [comment]
I tried current WMCore
https://github.com/dmwm/CRABServer/issues/5673

but still have the same error
```
xrdcp --force --nopbar --wma-disablewriterecovery  "kk.root"  "root://eoscms.cern.ch//eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_112519/0000/kk_2.root" 

2018-07-01T11:51:10 : Running the stage out...
Local File Size is: 42348790
xrdcp: Invalid option, '--wma-disablewriterecovery'.

Usage:   xrdcp [<options>] <src> [<src> [. . .]] <dest>

Options: [--cksum <args>] [--debug <lvl>] [--coerce] [--dynamic-src]
         [--force] [--help] [--infiles <fn>] [--license] [--nopbar]
         [--path] [--posc] [--proxy <host>:<port>] [--recursive]
         [--retry <n>] [--server] [--silent] [--sources <n>] [--streams <n>]
         [--tpc {first|only}] [--verbose] [--version] [--xrate <rate>]
         [--parallel <n>] [--zip <file>]
<src>:   [[x]root://<host>[:<port>]/]<path> | -
<dest>:  [[x]root://<host>[:<port>]/]<path> | -
[ERROR] Server responded with an error: [3011] Unable to stat /eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_112519/0000/kk_2.root
```

**Comment by belforte** [comment]
I suspect the problem relates to what @amaltaro wrote last year:
"Sorry, I thought CRAB was using the stage out plugins under Plugins (not Backends)."
Indeed the --wma-disablewriterecovery is in wmcore/.../Backends/.. not plugins.
I will have to dissect the code to find out where such a decision is made.

**Comment by belforte** [comment]
here's what I find in WMCore. In current latest version the bad option is there in 
`./src/python/WMCore/Storage/Backends/XRDCPImpl.py`

```
(screen-vm2 TWorker)WMCore> git log|head -5
commit f8c783363f4e24273ab38e5027497f1c1e4e0c66
Author: amaltaro <alan.malta@cern.ch>
Date:   Thu Jun 14 14:03:44 2018 +0200

    1.1.14.crab1
(screen-vm2 TWorker)WMCore> pyfind disablewriterecovery
        eosStageOutParams['option'] = overrides.get('option', "--wma-disablewriterecovery")
./src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
        eosStageOutParams['option'] = "--wma-disablewriterecovery"
./src/python/WMCore/WMSpec/Steps/Executors/LogArchive.py
        parser.add_argument('--wma-disablewriterecovery', action='store_true')
        if args.wma_disablewriterecovery:
./src/python/WMCore/Storage/Backends/XRDCPImpl.py
(screen-vm2 TWorker)WMCore> 

```

**Comment by belforte** [comment]
And now with ref. to what @amaltaro wrote last year https://github.com/dmwm/CRABServer/issues/5566#issuecomment-332494504
``` 
I thought CRAB was using the stage out plugins under Plugins (not Backends).
```
So the offending code is in Backends, meaning we do use Backends.

What am I missing then ? Where is the problem ?
Does WMA uses `WMCore/Storage/Backends/XRDCPImpl.py` or not ? If yes, how can t work ?

Full log of the CRAB job which I just ran is here, but it does not really have more info:
https://cmsweb-testbed.cern.ch/scheddmon/0199/cms1627/180701_112519:belforte_crab_20180701_132510/job_out.2.0.txt

**Comment by belforte** [comment]
hmm...  I have a feeling I am have missed some things along the line of...
where does the job running on the CERN WM take WMCore from ?

**Comment by belforte** [comment]
Yeah... I updated the tarball to be included in the jobs and finally got a successful local stage out at CERN !!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by belforte** [comment]
So I believe this is understood and fixed. Will close and only keep #5673 open until we have WMcore tag 1.1.14.crab1 in production

**Comment by belforte** [comment]
for the record, stageout log for jobs running at CERN:
```
Stageout policy: local, remote
====== Sun Jul  1 14:02:52 2018: Starting job report validation.
Job report seems ok (it has the expected structure).
Retrieved payload exit code ('jobExitCode') = 0 from job report.
Retrieved job wrapper exit code ('exitCode') = 0 from job report.
====== Sun Jul  1 14:02:52 2018: Finished job report validation (status 0).
====== Sun Jul  1 14:02:52 2018: Starting to check if user output files exist.
Output file kk.root exists.
====== Sun Jul  1 14:02:52 2018: Finished to check if user output files exist (status 0).
====== Sun Jul  1 14:02:52 2018: Starting to check if user output files are in job report.
Output file kk.root found in job report.
====== Sun Jul  1 14:02:52 2018: Finished to check if user output files are in job report (status 0).
====== Sun Jul  1 14:02:52 2018: Starting initialization of stageout manager for local stageouts.
       -----> Stageout manager log start
INFO:root:StageOutMgr::__init__()
INFO:root:==== Stageout configuration start ====
INFO:root:Local Stage Out Implementation to be used is: xrdcp
Local Stage Out PNN to be used is T2_CH_CERN
Local Stage Out Catalog to be used is trivialcatalog_file:/cvmfs/cms.cern.ch/SITECONF/T2_CH_CERN/PhEDEx/storage.xml?protocol=eos
Trivial File Catalog has been loaded:
	lfn-to-pfn: protocol=eos path-match-re=/+store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/(.*) result=root://eospps.cern.ch//eos/pps/mw-test/phedex/store/mc/HCtest/GenericTTbar/GEN-SIM-RECO/CMSSW_7_0_4_START70_V7-v1/$1
	lfn-to-pfn: protocol=eos path-match-re=/+store/(.*) result=root://eoscms.cern.ch//eos/cms/store/$1
	lfn-to-pfn: protocol=xrootd path-match-re=/+store/(.*) result=root://xrootd-cms.infn.it//store/$1
	lfn-to-pfn: protocol=srmv2 path-match-re=/+store/user/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/user/$1
	lfn-to-pfn: protocol=srmv2 path-match-re=/+store/group/(.*) result=srm://srm-eoscms.cern.ch:8443/srm/v2/server?SFN=/eos/cms/store/group/$1
	pfn-to-lfn: protocol=eos path-match-re=root://eoscms.cern.ch//eos/cms/store/(.*) result=/store/$1
	pfn-to-lfn: protocol=srmv2 path-match-re=.*\?SFN=/eos/cms(.*) result=$1
There are 0 fallback stage out definitions.

INFO:root:==== Stageout configuration finish ====
       <----- Stageout manager log finish
Initialization was ok.
====== Sun Jul  1 14:02:52 2018: Finished initialization of stageout manager for local stageouts (status 0).
Will use gfal2 commands for direct stageout.
====== Sun Jul  1 14:02:52 2018: Starting initialization of stageout implementation for direct stageouts.
Initialization was ok.
====== Sun Jul  1 14:02:52 2018: Finished initialization of stageout implementation for direct stageouts (status 0).
====== Sun Jul  1 14:02:52 2018: Starting local stageout of user output files.
-----> Sun Jul  1 14:02:52 2018: Starting local stageout of kk.root.
       -----> Stageout manager log start
INFO:root:==>Working on file: /store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root
INFO:root:===> Attempting Local Stage Out.
INFO:root:LFN to PFN match made:
LFN: /store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root
PFN: root://eoscms.cern.ch//eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root

INFO:root:Creating output directory...
INFO:root:Running the stage out...
INFO:root:Command exited with status: 0
Output message: stdout: Local File Size is: 42348790
Remote File Size is: 42348790

stderr: 
INFO:root:===> Stage Out Successful: {'LFN': '/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root', 'PNN': 'T2_CH_CERN', 'StageOutCommand': 'xrdcp', 'StageOutReport': [], 'PFN': 'root://eoscms.cern.ch//eos/cms/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root'}
       <----- Stageout manager log finish
INFO: PNN is defined in site-local-config. T2_CH_CERN changed to T2_CH_CERN
Setting temp_storage_site = 'T2_CH_CERN', storage_site = 'T2_IT_Pisa', local_stageout = True for file kk.root in job report.
Dashboard stageout failure parameters: {'MonitorID': '180701_131354:belforte_crab_20180701_151345', 'MonitorJobID': '2_https://glidein.cern.ch/2/180701:131354:belforte:crab:20180701:151345_2', 'JobExitCode': 0, 'StageOutReport': [{'StageOutType': 'LOCAL', 'LFN': '/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/CRAB3_test-SB/180701_131354/0000/kk_2.root', 'StageOutExit': 0, 'StageOutCommand': None, 'PNN': 'T2_CH_CERN'}]}
<----- Sun Jul  1 14:02:55 2018: Finished local stageout of kk.root (status 0).
====== Sun Jul  1 14:02:55 2018: Finished local stageout of user output files (status 0).
====== Sun Jul  1 14:02:55 2018: cmscp.py FINISHING (status 0).
======== Stageout at Sun Jul  1 14:02:55 GMT 2018 FINISHING (short status 0) ========
```
