### ISSUE TITLE
Disable userlog file copy for probe jobs of the Automatic splitting mode

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5620]
From [this](https://cmsweb-testbed.cern.ch/scheddmon/0137/cms382/180111_103143:lecriste_crab_AutomaticSplitting_data/job_out.0-3.0.txt) probe job_out it seems the log file is copied from the WN to the SE of the WN site.

Should we disable it for probe jobs?

**Comment by belforte** [comment]
yes. Probe jobs are not part of the dataset processing (their output is discarded) so there's no need for long term preservation and having extra log files in the SE may confuse those users who do use them.

**Comment by matz-e** [comment]
Short status update: I have a potential fix ready, I will file a PR once (a) an automatic splitting task and (b) a regular splitting task have completed.

**Comment by matz-e** [comment]
Just had my two tasks complete, I'd appreciate if someone else could have a look over it.

**Comment by belforte** [comment]
@lecriste can you test this ?

**Comment by lecriste** [comment]
I confirm the copy of probe jobs log has not occurred in my recent task with Automatic splitting mode.
E.g.: https://cmsweb.cern.ch/scheddmon/0199/cms382/180117_150241:lecriste_crab_AutomaticSplitting_data_noUnitsPerJob_oneRun/job_out.0-1.0.txt

**Comment by belforte** [comment]
@lecriste this was not merged yet, how did you test it ?

**Comment by todor-ivanov** [comment]
@belforte should I merge it and create a temporary version of the TW and deploy in dev/preprod in order to test it

**Comment by belforte** [comment]
I think we should expand 3.3.18.rc1 to include all these new fixes and also Marco's one.
I can start working on this tonight. Am not really comfortable with the way described in the twiki and which I used to cherry pick all commits into a new tag, maybe it will be simpler to make a new branch so that we can push fixes if needed. @mmascher I will go with your advice here, what do you suggest ? I am ready to do what I think is worse, if you think it is better, and get myself educated in the process :-)

**Comment by mmascher** [comment]
I agree with @belforte that we should expand 3.3.1801 (and create an rc2). No need to branch/cherrypick on preprod, unless we wanna keep it stable for the automatic splitting tests. But given there are no cmsweb changes and we can take our time to test everything I'd do the simpler thing and merge everythin we want and create 3.3.1801.rc2.

**Comment by mmascher** [comment]
And if by testing the automatic splitting we find other unrelated bugs it's probably even better :)

**Comment by lecriste** [comment]
I submitthed a [task](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=lecriste&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=180121_141651%3Alecriste_crab_AutomaticSplitting_data_noUnitsPerJob_oneRun_preprod) with Automatic splitting mode to preprod on which Stefano installed 3.3.1802 on Friday.
I confirm the copy of probe jobs log and output has not occurred although both transferLogs and transferOutputs flags were set to True.

The probe job [log](https://cmsweb-testbed.cern.ch/scheddmon/0107/cms382/180121_141651:lecriste_crab_AutomaticSplitting_data_noUnitsPerJob_oneRun_preprod/job_out.0-1.0.txt) reads:

> The user has not specified to transfer the log files. No log files stageout (nor log files metadata upload) will be performed.
> The user has specified to not transfer the output files. No output files stageout (nor output files metadata upload) will be performed.
> Stageout wrapper has no work to do. Finishing here.

**Comment by belforte** [comment]
+1
