### ISSUE TITLE
Automatic job splitting units

### ISSUE THREAD

**Issue by hernand** [dmwm/CRABServer#5623]
This issue is to discuss and converge on a definition for automatic job splitting parameters totalUnits and UnitsPerJob. 

- **totalUnits**: I think this parameter is currently ignored. There was a proposal to use the values (0,1] to indicate the fraction of the input dataset to be processsed, and use >1 to indicate the total number of lumis to process. Do people agree with this proposal?
- **UnitsPerJob**: It currently specifies the number of seconds jobs should last. Jobs running for longer will gracefully stop and the remaining work will be taken over by tail jobs. There is the question whether it makes sense to let users to specify the target job duration, given that automatic splitting should use the most optimal value. The agreement seems to be that for some cases (testing, jobs where RAM increases with number of events, ...) the user might need to set that parameter. In any case, the default value should be sensible (we have to agree on a number; what about 4 hours?), and there should probably be a minimum value (10 minutes?) to avoid too short jobs. I would also propose to use minutes rather than seconds for the parameter units.

**Comment by matz-e** [comment]
* To clarify about **totalUnits**: should the fraction be in terms of lumis? To be consistent with the use case of `> 1`, I think fraction and total count in terms of lumis makes sense.

* Switching **unitsPerJob** to minutes can be done on the client side, units of seconds on the server side are sensible, IMO, to avoid having the translation in a weird place.

  As per the [wiki](https://github.com/dmwm/CRABServer/wiki/Automatic-Splitting:-TaskWorker), the default minimum runtime is: `config.TaskWorker.minAutomaticRuntime = 3 * 60 ** 2`, 3 hours. This can be configured on the TW…

  Within the [client source](https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/ClientMapping.py#L31), the default runtime is set to 8 hours. I thought that this value would be a good way to reduce the global job count. [Note that the splitting targets around 75% of this value!](https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PreDAG.py#L189)

**Comment by hernand** [comment]
> To clarify about totalUnits: should the fraction be in terms of lumis? To be consistent with the use case of > 1, I think fraction and total count in terms of lumis makes sense.

Agreed

> Switching unitsPerJob to minutes can be done on the client side, units of seconds on the server side are sensible, IMO, to avoid having the translation in a weird place.

ok

> As per the wiki, the default minimum runtime is: config.TaskWorker.minAutomaticRuntime = 3 * 60 ** 2, 3 hours. This can be configured on the TW…

I think that's probably too long. I could imagine that a smaller value would be helpful for users for testing purposes. 

> Within the client source, the default runtime is set to 8 hours. I thought that this value would be a good way to reduce the global job count. Note that the splitting targets around 75% of this value!

It's sounds like a sensible value

**Comment by matz-e** [comment]
>>    Switching unitsPerJob to minutes can be done on the client side, units of seconds on the server side are sensible, IMO, to avoid having the translation in a weird place.
> ok

After looking at the code, I'm going to backpedal here. Taking the job runtime that the user can specify as a guide, we should be consistently use minutes, and do the translation at the very last moment possible. To be safe, I should rename all the parameters to include the unit, as was done for the job runtime.

>>    As per the wiki, the default minimum runtime is: config.TaskWorker.minAutomaticRuntime = 3 * 60 ** 2, 3 hours. This can be configured on the TW…
> I think that's probably too long. I could imagine that a smaller value would be helpful for users for testing purposes.
That may always lead to abuse, once someone uses a short parameter in production, short jobs will spread as a way to "hack" the system. User configurations have a habit of being copied around… A good way to get around this and allow some sensible testing would be to couple the allowed minimum runtime to the amount of data processed.

That being said, if a user wants to test something really quick, why wouldn't they just specify to process a small amount of lumis?

**Comment by matz-e** [comment]
>> To clarify about totalUnits: should the fraction be in terms of lumis? To be consistent with the use case of > 1, I think fraction and total count in terms of lumis makes sense.

> Agreed

Another addendum: automatic splitting uses `EventAwareLumiBasedSplitting` under the hood, so both the fraction and the total count should be in terms of events. In my opinion, that will actually make it more graspable for users, I hope (lumis are a fairly abstract unit, and randomly defined for MC).

**Comment by belforte** [comment]
I tend to agree with @matz-e here. In particular in keeping a decent minimum value on TW, if needed I'd rather config. preprod or dev TW with a different value to help testing.
About seconds vs. minutes vs. hours it would help if we could use the same in all places, so I vote for minutes.

**Comment by hernand** [comment]
> I tend to agree with @matz-e here. In particular in keeping a decent minimum value on TW, if needed I'd rather config. preprod or dev TW with a different value to help testing.

yeah, I'm also in favour of a decent minimum value. The question is what is a decent value? 3 hours seems to me too long. By testing I meant users testing their workflows before sending large amounts of jobs. Another use case could be jobs that slowly increase their used RAM as the number of processed events increases, and they finally get killed due to exceeding usage of RAM. Users might have valid reasons to run jobs lasting less than 3 hours, I  suppose.

**Comment by belforte** [comment]
I see nothing wrong in starting with:
default 8h
enforced minimum 1h
and see how it goes. If we get what we need via gentle prodding and some finger slapping it will be better, but we can always use the stick if needed.
Testing of workflow (is code right ? etc.) is better done using splitbylumi and requesting 100~1k lumis or so.  Anyhow this does not require a code change. It is simply a matter of TW configuration

**Comment by hernand** [comment]
ok. It is true that the other manual job splitting methods will remain, unless we have to enforce/favour somehow automatic splitting if people continue to select manual splitting of very short jobs.

**Comment by matz-e** [comment]
@belforte I think we can close this issue. Units are in minutes now, and #5633 deals with the rest.

**Comment by belforte** [comment]
agreed
