### ISSUE TITLE
Account for output files size in Automatic splitting mode

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5630]
Apparently the Automatic splitting mode does not take into account the size of the output files.
E.g. most of the main jobs of this [task](https://cmsweb.cern.ch/crabserver/ui/task/180124_171854%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue) failed with exit code 50662, then a number of tail jobs triple than the main ones were created and finished successfully. Probe jobs were also successful.

Probably that's a corner case as the analyzer I used was just skimming the input dataset.

**Comment by matz-e** [comment]
Good point. That should be an easy-ish fix. I'll try to wrap up the resubmission and then circle back to this.

**Comment by matz-e** [comment]
@belforte I'm thinking about turning the maximum output size into a configuration parameter. There's an upper limit of 20 GB somewhere in the CRAB code, but that sounds a bit large to me…

What's a good maximum size for the output? Would 4 GB by default be an acceptable maximum?

**Comment by belforte** [comment]
20GB was there simply to be sure to kill job genlty before WN local disk gets full and job dies w/o info. It is supposed to be a limit on used disk space all inclued, not on output size. As output size goes, i.e. to make sure file can be transferred around , I think 5GB is a good number for default max. And if some user wants
to stage to a location which deals poorly with such files,they will specify a lower limit for the splitting tuning.
Ideally we should introduce this as an additional parameter, not overload the "total disk used on WN".
This new parameter does not need to be exposed to condor.

**Comment by matz-e** [comment]
Thank you for the input. It will be a new parameter, for now only configurable on the TaskWorker.

**Comment by belforte** [comment]
+1
