### ISSUE TITLE
Resubmission with automatic splitting

### ISSUE THREAD

**Issue by matz-e** [dmwm/CRABServer#5635]
Improvements to resubmission with automatic splitting are in #5627 and dmwm/CRABClient#4738, and a quickfix in #5634. Current status:

- [x] When resubmitting jobs, the status shows finished jobs going back to `running`, even though the DAGMan (i.e. `RunJobs1.subdag.dagman.out`) log shows only failed jobs being resubmitted.
  - Note that this "fixes" itself after a few more status calls over time: in the end, the correct status prevails.
  - [x] Investigate why status changes like that
- [x] Kills should be final

**Comment by matz-e** [comment]
I just found out that we confuse DAG upon resubmission, since `AdjustSites.py` concatenates all tail DAGs. Fix is in the works, should be tested in ~2 hours.

**Comment by lecriste** [comment]
`crab kill` is not yet final.
I successfully resubmitted this task jobs after killing it:
https://cmsweb-testbed.cern.ch/crabserver/ui/task/180207_143738%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting/dbver/preprod

From [dashboard](http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=lecriste&refresh=0&table=Jobs&p=1&records=-1&activemenu=2&status=&site=&tid=180207_143738%3Alecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc4_testDefaultSplitting) resubmitted jobs are `running`, `crab status` keeps showing them as `failed`.

**Comment by belforte** [comment]
is it final for non-automatic-splitting tasks ?
sorry.. I guess I should know.. but..

**Comment by matz-e** [comment]
It currently is not final. It'll be a one-line change with after the PR I'm about to submit.
