### ISSUE TITLE
New client not compatible with preprod in Automatic splitting mode?

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5636]
With the latest /crabclient/3.3.1802.rc1/ and the current preprod instance (3.3.1802.rc1)
`crab submit --wait`
gives, for whatever valus of `config.Data.unitsPerJob`,
> ...
> Success: Your task has been delivered to the CRAB3 server.
> Waiting for task to be processed
> Checking task status
> Task status: NEW
> Please wait...
> Task status: SUBMITFAILED
> Error: The submission of your task has failed.
> Failure message:	Problem handling 180201_163854:lecriste_crab_AutomaticSplitting_data_oneRun_transferLogsTrue_preprod3-3-18-02-rc1 because of 'minutes_per_job' failure, traceback follows
> 			Traceback (most recent call last):
> 			  File "/data/srv/TaskManager/3.3.1802.rc1/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1802.rc1/lib/python2.7/site-packages/TaskWorker/Actions/Handler.py", line 77, in executeAction
> 			    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
> 			  File "/data/srv/TaskManager/3.3.1802.rc1/slc6_amd64_gcc493/cms/crabtaskworker/3.3.1802.rc1/lib/python2.7/site-packages/TaskWorker/Actions/Splitter.py", line 78, in execute
> 			    kwargs['task']['tm_split_args']['minutes_per_job'] < minRuntime:
> 			KeyError: 'minutes_per_job'
> ...

**Comment by lecriste** [comment]
Actually I have the same error with the previous client as well:
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab

**Comment by belforte** [comment]
didn't we say that --wait is deprecated ? AFAIK it is broken since a while and nobody uses it. We simply need to remove it from the options

**Comment by mmascher** [comment]
Yes, --wait is deprecated.

As far as the minutes_per_seconds goes I am afraid we need a change in the
REST:
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/DataWorkflow.py#L42
Pretty sure this is still the old version with seconds_per_job.

**Comment by lecriste** [comment]
I tried first with `crab submit` and `crab status` and I got the same error.
I would say something wrong with the current preprod instance (3.3.1802.rc1).

**Comment by matz-e** [comment]
https://cmsweb-testbed.cern.ch/crabserver/preprod/info shows me the following:
```
{
  "desc": {
    "columns": [
      "null"
    ]
  },
  "result": [
    {
      "crabserver": "Welcome",
      "version": "3.3.1711.rc4"
    }
  ]
}
```
Looks like there's a mismatch between the frontend and the taskworker.

**Comment by belforte** [comment]
@matz-e why is that relevant ? We do not expect changes in the frontend.
Does the new client nees some change in the REST ? like @mmascher  wrote yesterday ?
https://github.com/dmwm/CRABServer/issues/5636#issuecomment-362371733

That was not planned and while we can push a fix we can't roll it in production next week.
Or did @lecriste hit some different problem ?

**Comment by matz-e** [comment]
@belforte the client does not need changes, but I changed the units on the server side, which requires a REST update, since the units are in the variable name. I think I can get a quick backwards-compatible fix in, though. Something in the `Splitter` like:
```
            elif kwargs['task']['tm_split_algo'] == 'Automatic':
                # REST backwards compatibility fix
                kwargs['task']['tm_split_args']['minutes_per_job'] = kwargs['task']['tm_split_args']['seconds_per_job']
                splitparam['algorithm'] = 'FileBased'
                …
```

**Comment by belforte** [comment]
but I thought the client needs to store minutes_per_job not seconds_per_job in the DB, so there's need for client/REST alignement as well. No ? If nothing else, to name things in consistent ways.
But maybe I miss one thing or two !

Maybe you can even use a samll try/except in the Splitter so it handles both (and  coverts to same unit for internal use) and we do not need to syncronize client/rest/tw in next deployment ? Only if needed of course, simply that syncronization of changes is a pain
