### ISSUE TITLE
verify that crab resubmit restarts the task_process if needed

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5641]

**Comment by belforte** [comment]
Apparently it should be restarted. Detailed debugging is needed.
For a task where TP was missing the _condor_stdout from the crab resubmit is
```
[cms1707@vocms0155 SPOOL_DIR]$ cat _condor_stdout 
Beginning dag_boostrap_startup.sh at Mon Feb  5 16:25:44 CET 2018
On host: vocms0155.cern.ch
At path: /data/srv/glidecondor/condor_local/spool/1141/0/cluster18121141.proc0.subproc0
As user: cms1707
Execute AdjustSites.py ...
CONDOR_ID set to 18121141.0
Proxy found at 2111f9927fcb352736578ab43c0d4dc3aa672383
/etc/enable_task_daemon not found or task_process/task_process_runing found, not submitting the daemon task
executing condor_dagman
Executing condor dagman ... 
[cms1707@vocms0155 SPOOL_DIR]$ 
```
so it looks like it found the `task_process/task_process_running`  file there.

Maybe when TP is condor_rm'ed it does not properly remove the running file. I think we should trap signals in the task_proc_wrapper.sh and flag that it is not running when it is not !!
Or do a condor_q.. since condor knows better !

**Comment by belforte** [comment]
N.B. I believe the `_condor_stdout` file I quotes above is the output from `dag_bootstrap_startup.sh`
We need better naming and/or documentation here. Can't rediscover these things every time.

**Comment by belforte** [comment]
so I am closing this as invalid and will open and ad hoc issue

**Comment by belforte** [comment]
I think I will rename this as:
have a more robutst way to tell if task_process is running
or create a new ad hoc issue.

**Comment by todor-ivanov** [comment]
Related to this one here: 
Today with @lecriste we added few lines to the tp_kill script which was not removing the lock files when clearing the task_processes older than 48 hours. Now it is doing condor_rm $tp_clusterid  and rm -f $iwd/task_process/task_process_running

**Comment by belforte** [comment]
+1sent from Stefano's mobileOn Feb 22, 2018 02:12, todor-ivanov <notifications@github.com> wrote:Related to this one here:
Today with @lecriste we added few lines to the tp_kill script which was not removing the lock files when clearing the task_processes older than 48 hours. Now it is doing condor_rm $tp_clusterid  and rm -f $iwd/task_process/task_process_running

**Comment by todor-ivanov** [comment]
we may close this one it is now solved outside the github repository - directly in the script for tp_kill

**Comment by belforte** [comment]
You may have made tp_kill to be a bit more careful in communicating that it killed the TP, but still it is a fragile solution. When DAG is restarted by a resubmit we should not rely only on present of a disk file to make sure that a TP is running

**Comment by belforte** [comment]
we will live with current fragile solution until we have evidence of problems
