### ISSUE TITLE
sometimes splitting sets wrongly the number of units to float(s)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5651]
-------- Forwarded Message --------
Subject: Error in the generation of a CRAB job
Date: Wed, 7 Mar 2018 14:25:47 +0100
From: Andrea Sciaba' <Andrea.Sciaba@cern.ch>
To: hn-cms-crabFeedback@cern.ch

*** Discussion title: CRAB Feedback

Hello,

I am running a special task using scritpExe with the attached
configuration, where the job splitting is defined as follows:

config.Data.unitsPerJob = 10
NJOBS = 10
config.Data.totalUnits = config.Data.unitsPerJob * NJOBS
config.Data.splitting = 'EventBased'

which generates 10 jobs which execute a full step chain to generate 10
events each (all jobs in the task are identical).

What happens is that the last job in the task always fails. For example:

http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=sciaba&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=180307_090738%3Asciaba_crab_sciaba_chain_premix_7

and by looking at the log, one sees something very weird:

Arguments are -a sandbox.tar.gz
--sourceURL=https://cmsweb.cern.ch/crabcache --jobNumber=10
--cmsswVersion=CMSSW_10_0_1 --scramArch=slc6_amd64_gcc630
--inputFile=job_input_file_list_10.txt --runAndLumis=job_lumis_10.json
--lheInputFiles=False --firstEvent=91 --firstLumi=10 --lastEvent=101.0
--firstRun=1 --seeding=AutomaticSeeding --scriptExe=premix-run.sh
--eventsPerLumi=10 --maxRuntime=-60 --scriptArgs=[] -o {}

note the --lastEvent=101.0! Why a float?? And why 101 and not 100?

The job then fails with producing error messages starting with

==== CMSSW Stack Execution FAILED at Wed Mar  7 09:20:46 2018 ====
ERROR: Cannot dump CMSSW stdout; perhaps CMSSW never executed (e.g.:
scriptExe was set)?
...
Beginning TweakPSet
 arguments: ['/srv/TweakPSet.py', '--location=/srv',
'--inputFile=job_input_file_list_10.txt',
'--runAndLumis=job_lumis_10.json', '--firstEvent=91',
'--lastEvent=101.0', '--firstLumi=10', '--firstRun=1',
'--seeding=AutomaticSeeding', '--lheInputFiles=False',
'--oneEventMode=0', '--eventsPerLumi=10', '--maxRuntime=-60']
One event mode disabled until we can put together a decent version of
WMCore.
TweakPSet.py is going to force one event mode
Traceback (most recent call last):
  File "/srv/TweakPSet.py", line 200, in <module>
    pset()
  File "/srv/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py",
line 739, in __call__
  File "/srv/WMCore.zip/PSetTweaks/WMTweak.py", line 320, in applyTweak
  File "/srv/WMCore.zip/PSetTweaks/WMTweak.py", line 197, in setParameter
  File
"/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_10_0_1/python/FWCore/ParameterSet/Mixins.py",
line 62, in setValue
    raise ValueError(str(value)+" is not a valid "+str(type(self)))
ValueError: 10.0 is not a valid <class 'FWCore.ParameterSet.Types.int32'>

note the last error: where does the 10.0 come from?

I wonder if this is a bug in CRAB (likely) or a mistake in my
configuration (possible, but it shouldn't cause CRAB to fail in this way).
from CRABClient.UserUtilities import config

config = config()

config.General.requestName = 'sciaba_chain_premix_7'
config.General.transferOutputs = True
config.General.transferLogs = True

config.JobType.pluginName = 'PrivateMC'
config.JobType.psetName = 'premix_step1.py'
config.JobType.scriptExe = 'premix-run.sh'
config.JobType.eventsPerLumi = 10
config.JobType.inputFiles = ['step_configs.tgz']
config.JobType.outputFiles = ['step3.root']

config.Data.unitsPerJob = 10
NJOBS = 10
config.Data.totalUnits = config.Data.unitsPerJob * NJOBS
config.Data.splitting = 'EventBased'
config.Data.publication = False
#config.Data.ignoreLocality = True

config.Site.blacklist = ['T3*']
config.Site.storageSite = 'T2_CH_CERN'
#config.Site.whitelist = ['T2_*']

-------------------------------------------------------------
Visit this CMS message (to reply or unsubscribe) at: 
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/8420.html

**Comment by sciaba** [comment]
From what I can see, Splitter.py in CRAB basically just uses SplitterFactory from WMAgent, and in particular the EventBased.py plugin:

https://github.com/dmwm/WMCore/blob/6f580f444dca6ed8d3f1c1c34680b197bfeaf574/src/python/WMCore/JobSplitting/EventBased.py

which is a subclass of JobFactory.py:

https://github.com/dmwm/WMCore/blob/6f580f444dca6ed8d3f1c1c34680b197bfeaf574/src/python/WMCore/JobSplitting/JobFactory.py

And here is where I stopped for now...

**Comment by amaltaro** [comment]
Andrea, I had a quick look at the code and I don't see any place that would allow it (EventsPerJob) to be anything different than int (at least not in WMCore/WMAgent land).

The workflow specification defines EventsPerJob as int:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/StdBase.py#L1161

the automatic splitting - if needed - is also casted to int:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMSpec/StdSpecs/MonteCarlo.py#L108

and the EventBased job splitting is supposed to be dealing with integer only:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L117

the relational database also defines the events column as integer.

Of course, CRAB is not using all this machinery, so we might be getting this float from a different place. When did it start happening? Was there any change on the CRAB infrastructure in the last days/weeks? It's weird that this issue gets reported only now (by one user only(?)...)

**Comment by belforte** [comment]
Whatever the cause, it is likely to have come with recent changes by Matthias to allow for fractional total units.
Code is indeed a bit difficult to follow and understand, which is why I think we tackle other issues first.

**Comment by sciaba** [comment]
Hi Stefano,

are you sure that those changes are relevant also for PrivateMC tasks? I have the impression that all code changes related to fractional total units only apply to Analysis tasks, see

https://github.com/dmwm/CRABServer/commit/3117037d1d599270a2e0bd4337d0e877ed8485ba#diff-cfe3a71abfd0fccb8d9f251d0aea1001

**Comment by belforte** [comment]
no. I am not sure.

**Comment by sciaba** [comment]
Is it possible to learn something from the CRAB server logs? For example, in case they give any information about the job splitting.
Another question: from what I see, the subjobs are created by executing createSubDag

https://github.com/dmwm/CRABServer/blob/258293c55df1dd8c1431e76b9863067e0da64e75/src/python/TaskWorker/Actions/DagmanCreator.py#L681

from

https://github.com/dmwm/CRABServer/blob/8f22654f9f1c393dd7864fc3b9a36840a8895ba2/src/python/TaskWorker/Actions/PreDAG.py

and createSubDag generates the DAG specs from makeDagSpecs:

https://github.com/dmwm/CRABServer/blob/258293c55df1dd8c1431e76b9863067e0da64e75/src/python/TaskWorker/Actions/DagmanCreator.py#L542

which is the place where the argument of --lastEvent is extracted from job['mask']['LastEvent']. But job comes from jobgroup which comes from splitterResult which comes from

https://github.com/dmwm/CRABServer/blob/8f22654f9f1c393dd7864fc3b9a36840a8895ba2/src/python/TaskWorker/Actions/PreDAG.py#L231

and Splitter.py does almost nothing for PrivateMC, it calls SplitterFactory, so I still think that the problem is somehow in WMCore.
If only I could understand where the splitting in WMCore decides which is the value of lastEvent of a subjob, I could make progress...

**Comment by belforte** [comment]
I can reproduce the  `lastEvent="101.0" ` in file `RunJobs.dag `
should be able to investigate by running the TW in debug mode
useful pointer:
https://github.com/dmwm/CRABServer/blob/258293c55df1dd8c1431e76b9863067e0da64e75/src/python/TaskWorker/Actions/DagmanCreator.py#L977

**Comment by belforte** [comment]
no problem when submitting to my VM. Maybe prod. TW is missing some commit ?

**Comment by belforte** [comment]
nope WMCore files in my VM and production TW are identical

**Comment by belforte** [comment]
This is taking an awful amount of time to sort out, but I begin seeing the light.
The problem is likely that in CRAB taskdb now 'tm_totalunits' is a FLOAT
```
(Pdb) kwargs['task']['tm_totalunits']
100.0
```
whit it was an INT before, and still is an INT in my private instance where indeed things work
``(Pdb) self._task['tm_totalunits']
100
(Pdb) 
```
this value gets propagated to WMCore as totalevents in one of those ununderstandable data structures used inside WMCore splitting factory and thanks to lack of explicit casting, no typing and all that Python niceties.. ends in 101.0 instead of 101 for last event of last job.
 
will try to force a INT here, but need to make sure that it does not break the places where Matthias added code to specifically handle fractional totalunits
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/MakeFakeFileSet.py#L39

**Comment by belforte** [comment]
@amaltaro with ref to https://github.com/dmwm/CRABServer/issues/5651#issuecomment-371434830
actually CRAB does use
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py

but as I wrote above, a float managed to slip in via `eventsInFile = f['events']` 
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L96
via
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L75
and the way it gets into the locationDict ... (not to mention that using location word here is very confusing) is very twisty/

May I am simply too bad in python and get confused by smart code like this
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L73-L75
It does take a long timhttps://github.com/dmwm/WMCore/blob/master/src/python/WMCore/JobSplitting/EventBased.py#L73-L75e at least to me to figure out how to read code like this
```
for location in locationDict:
    fileList = locationDict[location]
```

**Comment by belforte** [comment]
thanks @amaltaro indeed I am slowly starting to understand that code :-)
