### ISSUE TITLE
GetDocsTransfer0_sql query removed from REST but needed

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5656]
During the campaign against "SELECT *", GetDocsTransfer0_sql query was removed cause considered useless. Well, I'm making a pull request to reintroduce it since I was wrong. 
That query is used in ASO to gather files to be killed, so the transfer killing is broken since then.

**Comment by belforte** [comment]
@dciangot can you confirm that this is now solved in the REST deployed in production ?

**Comment by dciangot** [comment]
Yes, all good.
