### ISSUE TITLE
Removing fmd_creation_time from UPdate_sql query

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/CRABServer#5658]
We are trying  to update column according to which we are  partitioning  the table and that  tries to move records between partitions, which basically causes problems and breaks resubmissions. The Update_sql query is called only during resubmissions and tries to change the fmd_creation_time but it is not searched anywhere else in the code.

>>> [19/Mar/2018:01:00:03]  RESTSQL:cTBRYHnXxDgV prepare [UPDATE filemetadata SET fmd_tmp_location = :outtmplocation, fmd_size = :outsize, fmd_creation_time = SYS_EXTRACT_UTC(SYSTIMESTAMP), fmd_tmplfn = :outtmplfn                     WHERE tm_taskname = :taskname AND fmd_lfn = :outlfn]
>>> [19/Mar/2018:01:00:03]  RESTSQL:cTBRYHnXxDgV executemany: ([{'outsize': '11822', 'outtmplfn': '/store/group/lpcsusyhad/Stop_production/TriggerStudies2017/SinglePhoton/Fall17_94X_Mar_2017_SinglePhoton-Run2017C/180303_205200/0002/log/cmsRun_2693.log.tar.gz', 'taskname': '180303_205200:snorberg_crab_SinglePhoton-Run2017C', 'outtmplocation': 'T2_US_Vanderbilt', 'outlfn': '/store/group/lpcsusyhad/Stop_production/TriggerStudies2017/SinglePhoton/Fall17_94X_Mar_2017_SinglePhoton-Run2017C/180303_205200/0002/log/cmsRun_2693.log.tar.gz'}],) {}
>>> [19/Mar/2018:01:00:03]  SERVER DATABASE ERROR 500/403 Execution error cx_Oracle.DatabaseError c7fcd179317a660566ce77c3cbd32276 [instance: prod] (ORA-14402: updating partition key column would cause a partition change); last statement: <**>UPDATE filemetadata SET fmd_tmp_location = :outtmplocation, fmd_size = :outsize, fmd_creation_time = SYS_EXTRACT_UTC(SYSTIMESTAMP), fmd_tmplfn = :outtmplfn                     WHERE tm_taskname = :taskname AND fmd_lfn = :outlfn; binds: ([{'outsize': '11822', 'outtmplfn': '/store/group/lpcsusyhad/Stop_production/TriggerStudies2017/SinglePhoton/Fall17_94X_Mar_2017_SinglePhoton-Run2017C/180303_205200/0002/log/cmsRun_2693.log.tar.gz', 'taskname': '180303_205200:snorberg_crab_SinglePhoton-Run2017C', 'outtmplocation': 'T2_US_Vanderbilt', 'outlfn': '/store/group/lpcsusyhad/Stop_production/TriggerStudies2017/SinglePhoton/Fall17_94X_Mar_2017_SinglePhoton-Run2017C/180303_205200/0002/log/cmsRun_2693.log.tar.gz'}],), {}; offset: 0
>>> [19/Mar/2018:01:00:03]    Traceback (most recent call last):
>>> [19/Mar/2018:01:00:03]      File "/data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/crabserver/3.3.1711.rc4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1739, in dbapi_wrapper
>>> [19/Mar/2018:01:00:03]        return handler(*xargs, **xkwargs)
>>> [19/Mar/2018:01:00:03]      File "/data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/crabserver/3.3.1711.rc4/lib/python2.7/site-packages/CRABInterface/RESTFileMetadata.py", line 96, in put
>>> [19/Mar/2018:01:00:03]        directstageout=directstageout)
>>> [19/Mar/2018:01:00:03]      File "/data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/crabserver/3.3.1711.rc4/lib/python2.7/site-packages/CRABInterface/DataFileMetadata.py", line 113, in inject
>>> [19/Mar/2018:01:00:03]        self.api.modify(self.FileMetaData.Update_sql, **update_bind)
>>> [19/Mar/2018:01:00:03]      File "/data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/crabserver/3.3.1711.rc4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2173, in modify
>>> [19/Mar/2018:01:00:03]        c, _ = self.executemany(sql, kwbinds, *binds)
>>> [19/Mar/2018:01:00:03]      File "/data/srv/beHG1803c/sw/slc7_amd64_gcc630/cms/crabserver/3.3.1711.rc4/lib/python2.7/site-packages/WMCore/REST/Server.py", line 2082, in executemany
>>> [19/Mar/2018:01:00:03]        return c, c.executemany(None, *binds, **kwbinds)
>>> [19/Mar/2018:01:00:03]    DatabaseError: ORA-14402: updating partition key column would cause a partition change
>>> [19/Mar/2018:01:00:03] vocms0165.cern.ch 188.184.91.243 "PUT /crabserver/prod/filemetadata HTTP/1.1" 500 Internal Server Error [data: 3214 in 746 out 9364 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=snorberg/CN=696603/CN=Scarlet Rachel Norberg" "" ] [ref: "" "CRABClient/0.0.0" ]

**Comment by todor-ivanov** [comment]
the hypernwes related to the initial discovery of the problem is:
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2742/1.html

And the following change of the database can have triggered the ERROR [1]. And the ERRORs start when the records try to cross the boundery of the partitions and in our case this is exactly 14.MM.YY 

[1]https://cms-logbook.cern.ch/elog/Analysis+Operations/1942

**Comment by belforte** [comment]
This is now merged in master branch and tagged in 3.3.1804.rc1 (currently running in cmsweb-testbed) and later. So I am closing.
