### ISSUE TITLE
Duplicated (run,lumi,event) values among the output files of a 'PrivateMC' task using 'inputFiles'

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5670]
A 'PrivateMC' task using 'inputFiles' (e.g. LHE files) produces an output dataset with duplicated (run,lumi,event) values among the files.

Example:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3549.html

**Comment by belforte** [comment]
5 years old. No details. Not clear if it can be reproduced. Closing
