### ISSUE TITLE
improve UI Main tab

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5690]
remove useless fields, add other useful stuff.
I think I finally decoded how the javascript part sort of works.
https://github.com/dmwm/CRABServer/blob/master/src/script/task_info.js

In the end it almost only formats and prints what comes from crabserver REST, so all serious work will have to be done there (where it is easier).
In particular Main tab shows the result of this kind of query
https://stefanovm2.cern.ch/crabserver/dev/workflow?workflow=180601_202137%3Abelforte_crab_20180601_222131
cfr:
https://github.com/dmwm/CRABServer/blob/master/src/script/task_info.js#L775

which is a json like this [1]

relevant things (being data the json loaded into a python dict for similarity with `data' variable in the JS)
```
>>> data.keys()
[u'result', u'desc']
>>> data['desc']
{u'columns': [u'tm_taskname', u'panda_jobset_id', u'tm_task_status', u'tm_task_command', u'tm_user_role', u'tm_user_group', u'tm_task_failure', u'tm_split_args', u'panda_resubmitted_jobs', u'tm_save_logs', u'tm_username', u'tm_user_dn', u'tm_arguments', u'tm_input_dataset', u'tm_dbs_url', u'tm_task_warnings', u'tm_publication', u'tm_user_webdir', u'tm_asourl', u'tm_asodb', u'tm_output_dataset', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'clusterid', u'tm_start_time']}
>>> 

```

[1]
```
{u'result': [{u'status': u'FAILED', u'username': u'belforte', u'jobsPerStatus': {u'failed': 10}, u'jobs': {u'10': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'1': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'3': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'2': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'5': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'4': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'7': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'6': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'9': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}, u'8': {u'State': u'failed', u'Error': [90000, u"Stageout failure: Couldn't upload document to ASO database", {}]}}, u'publication': {}, u'taskWarningMsg': [], u'schedd': u'crab3-5@vocms059.cern.ch', u'publicationFailures': {}, u'outdatasets': None, u'statusFailureMsg': u'', u'taskFailureMsg': u'', u'failedJobdefs': 0, u'ASOURL': u'https://cmsweb.cern.ch/crabserver/prod', u'command': u'SUBMIT', u'totalJobdefs': 0, u'submissionTime': 1527884497, u'jobdefErrors': [], u'collector': u'cmsgwms-collector-global.cern.ch,cmssrv221.fnal.gov', u'jobList': [[u'failed', 10], [u'failed', 1], [u'failed', 3], [u'failed', 2], [u'failed', 5], [u'failed', 4], [u'failed', 7], [u'failed', 6], [u'failed', 9], [u'failed', 8]]}], u'desc': {u'columns': [u'tm_taskname', u'panda_jobset_id', u'tm_task_status', u'tm_task_command', u'tm_user_role', u'tm_user_group', u'tm_task_failure', u'tm_split_args', u'panda_resubmitted_jobs', u'tm_save_logs', u'tm_username', u'tm_user_dn', u'tm_arguments', u'tm_input_dataset', u'tm_dbs_url', u'tm_task_warnings', u'tm_publication', u'tm_user_webdir', u'tm_asourl', u'tm_asodb', u'tm_output_dataset', u'tm_collector', u'tm_schedd', u'tm_dry_run', u'clusterid', u'tm_start_time']}}

```

**Comment by belforte** [comment]
what is shown in the UI seems the content of `dd['result'][0]`

```>>> pprint.pprint(dd['result'][0].keys())
[u'status',
 u'username',
 u'jobsPerStatus',
 u'jobs',
 u'publication',
 u'taskWarningMsg',
 u'schedd',
 u'publicationFailures',
 u'outdatasets',
 u'statusFailureMsg',
 u'taskFailureMsg',
 u'failedJobdefs',
 u'ASOURL',
 u'command',
 u'totalJobdefs',
 u'submissionTime',
 u'jobdefErrors',
 u'collector',
 u'jobList']
>>> 


```

**Comment by belforte** [comment]
when that REST call is made, crabsever log shows
```

[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN ENTER crab3_belforte@devdb11 CRABInterface.RESTBaseAPI.RESTBaseAPI (GET dev workflow) inuse=0 idle=0
[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN instantiating a new connection
[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN connected, client: 11.2.0.4.0, server: 11.2.0.4.0, stmtcache: 50
[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN ping
[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN check [select sysdate from dual]
[06/Jun/2018:16:36:05]  RESTSQL:QzkhTpZsDfuN connection established
[06/Jun/2018:16:36:06]  RESTSQL:QzkhTpZsDfuN prepare [SELECT tm_taskname, panda_jobset_id, tm_task_status, tm_task_command, tm_user_role, tm_user_group,              tm_task_failure, tm_split_args, panda_resubmitted_jobs, tm_save_logs, tm_username,              tm_user_dn, tm_arguments, tm_input_dataset, tm_dbs_url, tm_task_warnings, tm_publication, tm_user_webdir, tm_asourl,              tm_asodb, tm_output_dataset, tm_collector, tm_schedd, tm_dry_run, clusterid, tm_start_time              FROM tasks WHERE tm_taskname=:taskname]
[06/Jun/2018:16:36:06]  RESTSQL:QzkhTpZsDfuN execute: () {'taskname': '180601_202137:belforte_crab_20180601_222131'}
[06/Jun/2018:16:36:06] stefanovm2.cern.ch 188.185.73.37 "GET /crabserver/dev/workflow?workflow=180601_202137%3Abelforte_crab_20180601_222131 HTTP/1.1" 304 Not Modified [data: 3797 in - out 1125662 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" ]
[06/Jun/2018:16:36:06]  RESTSQL:QzkhTpZsDfuN release with rollback
[06/Jun/2018:16:36:06]  RESTSQL:QzkhTpZsDfuN RELEASED crab3_belforte@devdb11 timeout=300 inuse=0 idle=1

```

**Comment by belforte** [comment]
so it looks like this involves the REST call `HTCondorDataWorkflow`
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py

**Comment by belforte** [comment]
hmm...
calling `HTCondorDataWorkflow` is defined in the configuration file `/data/srv/current/config/crabserver/config.py`
```
data.workflowManager = 'HTCondorDataWorkflow'
```

so my question is how the URL `.../workflow?workflow=<taskname>` ends with calling the `status` function

**Comment by belforte** [comment]
oh well..
if I am not mistaken, when REST detects the `workflow` in the URL path ` /crabserver/dev/workfow`, it decides to use `RESTUserWorkflow` methods
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTBaseAPI.py#L56
which will call the `status` function if there is no `subresource` defined:
https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTUserWorkflow.py#L682-L683
```
if not subresource:
   result = self.userworkflowmgr.status(workflow, verbose=verbose, userdn=userdn)

```
and I presume that `self..userworkflowmgr` is defined dynamically to point to what the config. indicates,in this case 'HTCondorDataWorkflow`

@mmascher do you have the stomach to read and confirm/deny my understanding here ?

**Comment by belforte** [comment]
since I suspect that HTCondorDataWorkflow.status is used in a lot of places, I guess I will not try to change it and resort to hacking the javascript :-(

**Comment by belforte** [comment]
@mmascher do you have some suggestion how I could find the places in the code base where a call this  REST url is done ?

**Comment by belforte** [comment]
there's hope... crab status uses RESTTask not HTCondorDataWorkflow  (from server side logs)

**Comment by mmascher** [comment]
Are you looking for this @belforte https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTBaseAPI.py#L56 ?

Anyway, the Task Info tab comes from RSTTask as you said. In particular this is the code: https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTTask.py#L74 that does a select *.

The Main tab comes does a status call IIRC (HTCondorWorkflow), but I am not sure how it evolved when we switched to status2..

**Comment by mmascher** [comment]
Oh yes, I saw here https://github.com/dmwm/CRABServer/issues/5690#issuecomment-395115256 you already figured it out

**Comment by belforte** [comment]
@mmascher thanks
if only I had the strength to document this well... anyhow. I think I understand the code, what I do not know is what I could affect if I change it. Looks like there is no sure way to tell where some REST URL may be used, although most calls use a common naming and I am getting convinced that HTCondorWorkflow is only used by the UI.
I guess I'll break it in my VM and see what fails !

**Comment by mmascher** [comment]
HTCondorWorkflow is also used by the client!

In general (probably you have already figured out, but):
* client uses /workflow
* task worker uses /workflowdb
* aso and postjob uses filemetadata and filetransfers
* finalley /task and /info are miscellaneus small API used in different places to modify/read task attributes directly in the DB and to get info about the external configuration respectively.

**Comment by belforte** [comment]
thanks Marco,
that list is truly an excellent thing !
but  when I did crab status from the client it called RESTTask not HTCondorDataWorkflow. Maybe I should try the other commands.

I guess I could also copy current worflow.status in a new `subresource=uinfo` or similar and call that from the UI (I think I can manage that change) so will be free to modify what's returned.
Anyhow I spent a bit on this sort of as carried away by other things, and decided to document my current understanding, bur surely improving the UI is not first, nor second, on my list !

**Comment by mmascher** [comment]
Notice that HTCondorDataWorkflow is inherits from DataWorklow. Commands like submit/resubmit/kill/proceed are in the latter. Conceptually everything that was scheduler independant (e.g.: condor vs panda) went there, in DataWorkflow. Everything that was dependant went in a specific class (HTCondorDataWorkflow) that you can select in the config. Example are status, logs, output, report(?).

However, remember that when we re-implemented the status we moved all the logic that now is in HTCondorDataWorkflow.status in the task process on the schedd. This is why crab status does not use it anymore. The status now just gets the task row from the database using /task, then get some DAG root node classads from /workflow (using subresource=taskads), and the publication info again from /workflow (publicationstatus). The rest is taken from the status_cache file on the schedd.

Possibly ASO and the UI still uses HTCondorDataWorkflow.status , but in principle it is deprecated. So my advice is that in the monitor you use the same things that are used in the client and leave the old status alone. Hopefully one day we will be brave and remove the code from HTCondorDataWorkflow :)

**Comment by belforte** [comment]
Right. And IIRC what Emilis was reporting, the UI does not work "out of the box" with the new status implementation. So more work may be needed to retire all of  HTCondorDataWorkflow.status that we ever manage to. Yet a new subresource with same code, but only used by the UI for freedom to hack still sounds attractive.

**Comment by belforte** [comment]
THis is what my previous comment is about:
https://github.com/dmwm/CRABServer/issues/5474
I guess we can fix the current  HTCondorDataWorkflow.status so that is does not crash and the Main tab is preserved, but w/o the job details for automatic splitting.
The fact that the status call crashes for automatic splitting and "nobody noticed" points toward "only UI uses it".

**Comment by mmascher** [comment]
Would you base the new API on the old HTCondorDataWorkflow.status? I fear that it might finally break at some point, and if you base the new API on that deprecated code the monitor would break as well. How about basing it on the client status somehow? Too much work? Anyway, I'll leave it up to you.

**Comment by belforte** [comment]
Emilis described the challange in adapting the UI to the new status. I think pros and cons are clear.
We could also make another, more compact, JSON file in the task_process and use that for the job summary,
ideally upload the summary as a blob to the DB and keep the UI at "works form DB info even if schedd is down".
always more options than manpower !
I am not going to do any significant work now anyhow. I am glad that I could figure out a bit the path here.

**Comment by belforte** [comment]
Last on this for a while: it is difficult to do testing since there's so much caching that changes do not seem to propagate, anyhow I verified that if I change 
https://github.com/dmwm/CRABServer/blob/master/src/script/task_info.js#L599
e.g. adding a dummy column [1]
the change appears in the displayed page. So I have found the right code hook.

[1]
from 
```
attrValue += "<tr><td>" + foundStatus + " </td><td> " + sumObject[foundStatus] + "</td></tr>";
```
to
```
append("<tr><td>" + attrName + "</td><td>SB" +"</td><td>" + attrValue + "</td></tr>");
```

**Comment by belforte** [comment]
In the end, the javascript part is totally dummy and only prints the table that it gets from HTCondorDataWorkflow

So all improvements can simply be done there.
As a start I removed the *defs (Panda legacy) and added taskWorker name and splitting algo,
which often I'd like to know right away.
