### ISSUE TITLE
move HTCondor submission wrapper to WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5706]
replace usage of  CRABServer/src/python/HTCondorUtils.py
with  new code for WMCore developed by @amaltaro 
at least the authenticated process part, hopefully all of this file.

**Comment by mmascher** [comment]
Needless to say, but make sure it is the same version, I modified it at some point.

**Comment by belforte** [comment]
@mmascher  AFAIK @amaltaro just wrote it for WMCore copying and adapting from CRBASever one. Which other version is there ?

**Comment by amaltaro** [comment]
Good point Marco. Checking the link Brian sent, it indeed doesn't point to the master branch:
https://github.com/dmwm/CRABServer/blob/e5624407aaa6a8b73a0934369581933d6c7de4a2/src/python/HTCondorUtils.py#L42

but it points to the latest commit, which is the same as the master one :)

I didn't migrate the module in full by the way, the `quote` and `unquote` methods are already available in the htcondor we build in comp. I guess this causes 2 or 3 other line changes in the CRAB code.

**Comment by mmascher** [comment]
As long as you are getting the master version we are good :)

I think the quote/unquote stuff should be easy to handle, but @belforte has the final say

**Comment by belforte** [comment]
I have no idea what quote/unquote is, let's see how @todor-ivanov and @amaltaro sort it out, I will be all ears in case of rational complains in any direction.

**Comment by belforte** [comment]
@mmascher I'd like your input here. Looking at current 
https://github.com/dmwm/CRABServer/blob/master/src/python/HTCondorUtils.py
there are 3 things:
quote/unquote --> to be replaced with calls directly to htcondor
authenticated submission --> to be replaced with what Alan wrote
and then this "interesting" line https://github.com/dmwm/CRABServer/blob/master/src/python/HTCondorUtils.py#L28
```
readEvents = getattr(htcondor, 'readEvents', htcondor.read_events)
```
which AFAICT is some sort of inline quick functoin definition, which is only used in two places
in the code base [1] and at least in task_process/cache_status.py would greately
benefit from using directly import htcondor to simplify the hack early in that file to fix sys.path
on the fly.

What do you thing. Am I missing something ?
I'd rather not keep around a file just for that line !!!
Could we simply inline the htcondor call instead ? Easier to read, bu the way !


[1]
```
    for event in HTCondorUtils.readEvents(fp):
./scripts/task_process/cache_status.py
        for event in HTCondorUtils.readEvents(fp):
./src/python/CRABInterface/HTCondorDataWorkflow.py

```

**Comment by mmascher** [comment]
Yes, I suggest to directly use condor for that. We used the readEvents wrapper because the name of the function changed in the condor python bindings  at some point. But now it can be removed.

**Comment by belforte** [comment]
thanks Marco. I'll look into this then. #5708

**Comment by belforte** [comment]
we do no need AuthenticatedSubprocess anymore and are removing it from the code !
#8277
