### ISSUE TITLE
skip early blocks without valid files

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5730]
There's no point i looking up locations etc. for blocks which have no valid files.
While e.g. asking them to be recalled from tape may lead to issues with Dynamo, see

https://hypernews.cern.ch/HyperNews/CMS/get/comp-ops/4170/1/2/1/1/1/1.html

**Comment by belforte** [comment]
@lecriste does the fix which you just committed for DBSReader problem solve this as well ?

**Comment by lecriste** [comment]
No. But we can apply the same solution here by replacing [blocks](https://github.com/dmwm/CRABServer/blob/bc099acfd9a41170314d67a32182c7e80ce9b73c/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L158) with [locationsMap.keys()](https://github.com/dmwm/CRABServer/blob/bc099acfd9a41170314d67a32182c7e80ce9b73c/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L218)
Agreed?

**Comment by belforte** [comment]
should be better to redefine blocks right after 
https://github.com/dmwm/CRABServer/blob/bc099acfd9a41170314d67a32182c7e80ce9b73c/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L149
(or wherever appropriate)
and only use the new list from then on.
