### ISSUE TITLE
Block publication fails when files contain many lumis

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5740]
Sometimes, when blocks contain files with many lumis, their publication fails with:
```
2018-09-10 14:32:16
GMT:ERROR:PublisherWorker:DBSPublisher-Worker-arizzi:
180904_090442:arizzi_crab_NanoDnRM2DYJetsToLL_M-105To160_TuneCUETP8M1_13TeV-
HTTPError: HTTP Error 502: Proxy Error

``` 
By reducing the number of files to be published in each block, things worked (< 40 for the task above).

More details in
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4146.html

**Comment by belforte** [comment]
addressed in https://github.com/dmwm/CRABServer/issues/6670
