### ISSUE TITLE
Task submission fails for invalid blocks

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5746]
Since October CMSWEB upgrade (October 2nd 2018), the [checkBlocksSize](https://github.com/dmwm/CRABServer/blob/29f1d5e26c594d1afa3b6f75b48a48eb121ecbdb/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L215) function returns an Exception when a block is not valid, thus failing the task submission.
Since invalid blocks are skipped at a [later stage](https://github.com/dmwm/CRABServer/blob/29f1d5e26c594d1afa3b6f75b48a48eb121ecbdb/src/python/TaskWorker/Actions/DataDiscovery.py#L42), the task submission must not fail here.

**Comment by belforte** [comment]
for history. IIUC, This was not due to code change. Most likely a coincidence of the upgrade with users trying to read a dataset with some blocks which had no valid files.

**Comment by lecriste** [comment]
A coincidence was my first guess but look for the number of different
cases: https://github.com/dmwm/CRABServer/pull/5747#issue-221510965
