### ISSUE TITLE
use PSS not RSS in PeriodicRemove

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5785]
see
https://cms-logbook.cern.ch/elog/GlideInWMS/6438
reporting text here for convenience:
```
What about setting PayloadMemory as [1] and making [2] the new periodicRemove expression?

[1]+PayloadMemory = ifthenelse(ProportionalSetSizeKb =!=UNDEFINED, (ProportionalSetSizeKb * 0.001024),
ifthenelse(ResidentSetSize =!= UNDEFINED, ResidentSetSize * 0.001024, UNDEFINED))

[2]New PeriodicRemove expression:
( ( JobStatus =?= 5 ) && ( time() - EnteredCurrentStatus > 7 * 60 ) ) || ( ( JobStatus =?= 1 ) && ( time() -
EnteredCurrentStatus > 7 * 24 * 60 * 60 ) ) || ( ( JobStatus =?= 2 ) && ( (RequestMemory > PayloadMemory) || (
MaxWallTimeMins * 60 < time() -
EnteredCurrentStatus ) || ( DiskUsage > 20000000 ) ) ) || ( time() > CRAB_TaskEndTime ) || ( ( JobStatus =?= 1 )
&& ( time() > ( x509UserProxyExpiration + 86400 ) ) )
```

**Comment by belforte** [comment]
@ddavila0  so PayloadMemory or CMS_PayloadMemory ?

**Comment by belforte** [comment]
@ddavila0 why `* 0.001024` rather than `/1024.` ? note that  `1./1024=0.0009765625`
Mayebe multuple RequestMemory by 1024 and compare with PayloadMemoryKb ?
Is this going to be used by CRAB only ?

**Comment by belforte** [comment]
should take care also of #5709 at same time

**Comment by ddavila0** [comment]
@belforte:
Going through the thread with the devs, I found that there might be a way to modify MemoryUsage by only modifying the startd configuration. In that case we won't need to change anything on CRAB. I'm not sure this will work, I'll test it and come back to you.

About your previous questions:
1. "PayloadMemory" was actually the name you suggested, but if you want to change it to CMS_PayloadMemory it's fine for me. 
2. The standard condor way is: (ProportionalSetSizeKb+1023)/1024, so we can use that instead, and yes, this will only be used by CRAB.

**Comment by belforte** [comment]
thanks a lot Diego. I have a preference for doing this inside HTC as you suggested in 2. and according to what you just wrote in e-log https://cms-logbook.cern.ch/elog/GlideInWMS/6624
Anyhow I need to change the PeriodicRemove expression anyhow to take care of #5709 so in case there is no problem in doing a change here as well.

**Comment by ddavila0** [comment]
In principle, we could use the same approach to force MemoryUsage to be always defined, something like: 
"If neither PSS nor RSS are defined then set MemoryUsage to 0", I think this could do the trick. I'll test it and come back to you

**Comment by belforte** [comment]
thanks !

**Comment by ddavila0** [comment]
I tried to set an initial value for MemoryUsage but didn't work (tried both in the schedd and in the startd). I guess this value must come from the Startd and as long as the update is not sent to the Schedd, the value at the Schedd would remain undefined.  We still need  #5709

**Comment by belforte** [comment]
thanks. I am taking care then.

**Comment by belforte** [comment]
Actually #5709 was dealt with in September, but issue stayed open. I have no closed it.

**Comment by belforte** [comment]
Most likely it will be done in HTC side and there's no code to change.
Being foolowed up in gWms e-log: https://cms-logbook.cern.ch/elog/GlideInWMS/6625

**Comment by belforte** [comment]
Solution deployed in production pool by SI
https://cms-logbook.cern.ch/elog/GlideInWMS/6647

No action needed on our side !
