### ISSUE TITLE
make sure that high_prio can only be used by users in a restricted list

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5814]

**Comment by belforte** [comment]
Yes. It is so.
see
https://github.com/dmwm/CRABServer/blob/5e894449fb2fcbdbf86f917dfea0f337d825d80b/src/python/TaskWorker/Actions/DagmanCreator.py#L485-L489

this can be overridden using extrJdl option which by design is there exactly to override what CRAB does and is inserted as last list in submission JDL. But users are never told to use that way.

**Comment by lecriste** [comment]
The [list](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/blob/master/code/templates/crab/crabtaskworker/TaskWorkerConfig.py.erb#L73) name in the TW config is 'highPrioUsers' and is commented.
Our code looks for 'highPrioEgroups' instead:
https://github.com/dmwm/CRABServer/issues/5814#L485

**Comment by belforte** [comment]
we should verify that it works, just for eductaion.
Then I am afraid I do not know how to attach an expiration date to an user

**Comment by belforte** [comment]
Verified. highPriority use is tied to e-groups list indicated in TW config file
