### ISSUE TITLE
mismatched directory counter in Job vs ASO

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5827]
There are  cases where job writes in `.../0000/...` but ASO will try to find the file in `.../0001/...`
See
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4596.html

I suspect that the problem is this line
https://github.com/dmwm/CRABServer/blob/c83476e68bea7cef70533589f90ec9ac2be617a5/scripts/cmscp.py#L1018
where I'd rather would like a `[1]`
But am puzzled by this commit:
https://github.com/dmwm/CRABServer/commit/4a9e2932ec74f845cbdd70ea51b5bfb4ff3c13ac

Of course the root cause is that we try to compute the directory number in two places,
the one above and this other one:
https://github.com/dmwm/CRABServer/blob/c83476e68bea7cef70533589f90ec9ac2be617a5/src/python/TaskWorker/Actions/DagmanCreator.py#L636

so that the DagmanCreator passes the counter as part of the arguments to the PostJob, while the job itself computes it independently inside cmscp.py in spite of the counter to be also indicated in the classAd like:
```
== JOB AD: CRAB_Destination = "gsiftp://cms-lvs-gridftp.hep.wisc.edu//hdfs/store/user/uhussain/UWVVNtuples_13Feb2019/SingleMuon/Run2017C-31Mar2018-v1/190213_175718/0001/log/cmsRun_1-1000.log.tar.gz, gsiftp://cms-lvs-gridftp.hep.wisc.edu//hdfs/store/user/uhussain/UWVVNtuples_13Feb2019/SingleMuon/Run2017C-31Mar2018-v1/190213_175718/0001/ntuple_1-1000.root"
```
and yet that jobs wrote in `.../0000/...`

**Comment by belforte** [comment]
@lecriste I assign to you because last year when you started we said that you were going to own automatic splitting. But this is a tricky thing and I believe we need to both look at it.

**Comment by belforte** [comment]
for a few weeks more we can e.g. compare this job stdout
https://cmsweb.cern.ch/scheddmon/0137/cms927/190213_175718:uhussain_crab_UWVVNtuples_13Feb2019_SingleMuon_Run2017C-31Mar2018-v1/job_out.1-1000.0.txt
with the corresponding PostJob
https://cmsweb.cern.ch/scheddmon/0137/cms927/190213_175718:uhussain_crab_UWVVNtuples_13Feb2019_SingleMuon_Run2017C-31Mar2018-v1/postjob.1-1000.0.txt

**Comment by belforte** [comment]
@lecriste ping
I really want a second opinion before pushing this in. It is a simple change.

**Comment by lecriste** [comment]
I don't understand the message of that puzzling commit: both 0 (probe job) and 1 (main job) divided by 1000 in the next line give 0...
I would also like a `[1]`, i.e. revert that commit.

How hard is to fetch the counter from the classAd instead of recomputing it in cmscp.py?

**Comment by belforte** [comment]
It is not hard. Of course the danger is always to overlook some side effect and get problems in some edge case where e.g. the counter is not passed in the classAd for some reason which I can't imagine now. 
I am puzzled that Matthias committed this change and wrote something about it (not clear what he meant, I agree) bu one would expect that he had some problem and this solved it.
Yet.. you can't argue with facts, current code is clearly broken.
