### ISSUE TITLE
Task process stuck by transfers.py

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5833]
I noticed on the schedd transfers.py processes stuck without any reason in the middle of different operations (looking at the logs). So it seems kind of host related (temporarily out of resources? just a guess), but indeed not reproducible and with no error messages.

Killing the transfers.py solve the issue and the tp restarts its normal operations afterwards.

Shall we detach the transfers.py from the task process? e.g. not waiting for it to finish? 

What do you think? @belforte

**Comment by belforte** [comment]
need to think about this. IDeally the code shoudl detect this situation

**Comment by mmascher** [comment]
Why not execute transfer.py with a timeout commant, and monitor the exit code to see if it exit successfully, like:

```
[mmascher@lxplus023 ~]$ timeout 5s sleep 10s
e[mmascher@lxplus023 ~]$ echo $?
124
[mmascher@lxplus023 ~]$ timeout 5s sleep 3s
[mmascher@lxplus023 ~]$ echo $?
0
```

How long transfer.py usually take?

**Comment by dciangot** [comment]
mmm yeah, way better.. we may even not be interested in the exit code, but only in terminating it.

**Comment by mmascher** [comment]
Also, executing it in backgroud with &, seems like a recipe for disaster (i.e.: I can see the task process spawning multiple python processes that do not end, eventually consuming the schedd memory)

**Comment by belforte** [comment]
yeah.. something like that. one eay or another we need to keep track of what's happening
can'j just fork and forget

**Comment by dciangot** [comment]
ok, agree --> +1 for timeout stuff on tp wrapper

**Comment by belforte** [comment]
see e.g.
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4653.html
I killed the process which was executing `python task_process/transfers.py`
And captured this output in the stderr of the task_process:
seems it was stuck in a fts3.submit.
We shoulst start by making sure that all calls to FTS client have a timeout.
As the golden rule goes:
"every call to a remote servere may fail and/or hang up indefintely at any time"
and may even be impossible to kill at times..

Do we have some generic wrapper for such calls ?


```
ms295@vocms0137 task_process]$ cat    daemon.err.34831305.0 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "task_process/transfers.py", line 249, in run
    jobid = fts3.submit(self.context, job)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/easy/submission.py", line 260, in submit
    delegate(context, delegation_lifetime, force_delegation, delegate_when_lifetime_lt)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/easy/delegate.py", line 36, in delegate
    return delegator.delegate(lifetime, force, delegate_when_lifetime_lt)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/delegator.py", line 235, in delegate
    remaining_life = self._get_remaining_life(delegation_id)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/delegator.py", line 135, in _get_remaining_life
    r = self.get_info(delegation_id)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/delegator.py", line 228, in get_info
    return json.loads(self.context.get('/delegation/' + delegation_id))
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/context.py", line 180, in get
    "%s/%s" % (self.endpoint, path))
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/pycurlRequest.py", line 161, in method
    self._handle_error(url, self.curl_handle.getinfo(pycurl.HTTP_CODE), response_str)
  File "/usr/lib/python2.6/site-packages/fts3/rest/client/pycurlRequest.py", line 117, in _handle_error
    raise ServerError(str(code))
ClientError: Client error: Server error: 500

/data/srv/glidecondor/condor_local/spool/1303/0/cluster34831303.proc0.subproc0/task_process/task_proc_wrapper.sh: line 12: 1958999 Terminated              python task_process/transfers.py
```

**Comment by dciangot** [comment]
mmm, the timeout of the call is in the fts3 code and set by default to 30 (don't know the units though).
So, if I'm not missing something, that cannot happen for a connection stall.

**Comment by dciangot** [comment]
https://gitlab.cern.ch/fts/fts-rest/blob/develop/src/fts3/rest/client/context.py#L149

**Comment by belforte** [comment]
guess we need to find another and check again, then possibly escalate to FTS devs.
Surely a timeout + logging on our side will not hurt.

**Comment by dciangot** [comment]
we can find another just looking to old transfers.py process on the schedds I think

**Comment by dciangot** [comment]
Just received an email telling me that FTS is having some strange issues for jobs with reuse connection activated. The jobs are going stuck at the 2nd retry. 

Although it looks uncorrelated to this issue IMO, they suggest to disable reuse connection while the problem is investigated.

@belforte should I push the change and create a tag?

**Comment by dciangot** [comment]
https://its.cern.ch/jira/browse/FTS-1392

**Comment by belforte** [comment]
yes to make a hot fix for this and put in production, but it will only affect new tasks. So unless this FTS issue lasts many days, it may hardly matter. As usual a bit of context helps when problems are communicated.

**Comment by belforte** [comment]
If it is really serious and urgent, we can consider editing all transfers.py files in active spool directories, a bit like we did at ASOv1/v2 time. It should be quite safe. And hopefully a simple sed will do.

**Comment by belforte** [comment]
anyhow xfers stuck in FTS can't make transfer.py hang. It is unrelated

**Comment by belforte** [comment]
the fix is now deployed in production. transfers.py is executed with a timeout.
