### ISSUE TITLE
Files in tmp area are not removed by asov2

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5834]
I have a fix for this, but we need gfal on schedds in order to trigger tmp file deletion

Is it doable? @belforte @todor-ivanov

**Comment by belforte** [comment]
gfal2 is in epel and can be installed via yum. So it is surely doable (and may be convenient to have gfal commands available when logged on schedd's for debugging). 
@todor-ivanov please look into adding to puppet and pushing to all schedd's

**Comment by belforte** [comment]
once installed, I will reassign from @todor-ivanov to myself for finalizing PR

**Comment by belforte** [comment]
gfal installed

**Comment by belforte** [comment]
fixed in ths PR from Diego
https://github.com/dmwm/CRABServer/pull/5828
