### ISSUE TITLE
PostJob stuck in waiting for ASO forever

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5842]
when a job is resubmitted due to ASO failure, so that the file metadata have alread been uploaded, the aso start time stamp in the JobRerpot.xml is not udpated so that PostJon keeps comparing current time with None, prints that 0.0 hours have been elapsed, and waits forever.
If second ASO retry succeeds, it is all OK. But when it should timeout, the timeout does not happen.
So it is rare to notice, but fatal.
See example here:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4686/1.html

**Comment by belforte** [comment]
@dciangot please read the description of this issue and let me know if I missed or misreported something important

**Comment by belforte** [comment]
the PJ code is of course very tricky to read correctly, but I suspect that the problem starts from the fact that ASO timed out for the first job, but failed to put the document in killed status in the transferDB when it did.
This makes the PF for the retried job print
```
File transfer status is not terminal ('done', 'failed' or 'killed'). Will not inject a new document for the current job retry.
```
and skip the ASO start time update.
So once we fix the bookkeping or the timeout tranfers (as per    https://github.com/dmwm/CRABServer/pull/5828/commits/e2623b7283a82a692aa366ebbdbe13cb934d7b14     )
this PJ stuck forever may disappear.

It still looks like there is something wrong in the code, since there is some input combination (asked to retry whille previous ASO is in progress) which is not correctly handled. But first thing here is to make the timing out work.
In a way, if the job was resubmitted and the previous transfer is still in progress.. I'd rather fail terminally or inject a new document.
The problem is that even if i make the PJ call it fatal, the user can still resubmit the job and I do not know what will happen. Given that the file was in transferDB already.

But we go back to: re-write all this resubmit stuff so that the policy and design is clear

**Comment by belforte** [comment]
@dciangot at this point I am inclined to pushing your fix for kill in postjob in production and do not do anything here. Do you agree ?
We still need to investigate why `transfers.py` does not submit to FTS, unless that is also because the previous transfer was apparently still going on

**Comment by belforte** [comment]
Nope. I checked the transferdb lastupdate for one of thos jobs with stuck PJ and it was never updated since the first time. I.e. 

1.  job ran
2.  PJ uploaded the document with transfer status NEW
3.  ASOv2 never submitted an FTS xfer and PJ timedout
4.  job was re-run
5. second PJ went in wait-forever loop
6. no idea why ASO did't pick it up the second time or in any case what the communication with it is supposed to be

**Comment by dciangot** [comment]
> @dciangot at this point I am inclined to pushing your fix for kill in postjob in production and do not do anything here. Do you agree ?

+1

**Comment by dciangot** [comment]
> Nope. I checked the transferdb lastupdate for one of thos jobs with stuck PJ and it was never updated since the first time. I.e.
> 
> 1. job ran
> 2. PJ uploaded the document with transfer status NEW
> 3. ASOv2 never submitted an FTS xfer and PJ timedout
> 4. job was re-run
> 5. second PJ went in wait-forever loop
> 6. no idea why ASO did't pick it up the second time or in any case what the communication with it is supposed to be

If the second time the PJ don't go for a different transfer, no signal (meaning new line in transfers.txt) is sent to transfer.py

**Comment by belforte** [comment]
thx Diego, sounds like we understand how things should work now.
Simply there is no parachute if the PJ times out waiting for ASO but does not mark things in transferDB.
While rare, this is not impossible in general (bugs aside).

**Comment by belforte** [comment]
I have made a small change to the PJ log to make situation more clear, should it happen again
https://github.com/dmwm/CRABServer/pull/5845

I still think that in this case (job is re-run but old transfer request is still not terminated) the ASO start time should be updated in the job report, but am not sure how to do it now without risking odd side effect, so in the spirit of "it works, don't fix it" I leave it as is. We can keep this bug open at low priority.

**Comment by belforte** [comment]
Now that I have an understanding of the situation and the code, I decided to fix the fact that the ASO start time is not recorded for job resubmissions when the xfer request had already been uploaded to ASO in earlier jobs.
I simply make sure that the PJ for each job stores ASO start time at the beginning in #5847

**Comment by belforte** [comment]
keeping open as a remind to check that everything is OK now

**Comment by belforte** [comment]
6 months later, it clearly did not create problems.
