### ISSUE TITLE
port to WMCore 1.2.0

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5846]
there is some non-backward compatible change e.g. in scram(), see:
https://github.com/dmwm/WMCore/pull/8989
and
https://github.com/dmwm/WMCore/issues/9113

**Comment by belforte** [comment]
@lecriste this should tell how to temporarely switch logging to a specific file
https://docs.python.org/2.7/howto/logging-cookbook.html#using-a-context-manager-for-selective-logging
@amaltaro we will try to work around your change to scram() module that way, it is a useful learning opportunity but quite some work. For the future I would recommend that when you write a module which can be used in many places you take a logger instance as argument (not a file !) so that you can always put in your code
```
import logging
def mything(blah.. , logger=None):
  if logger:
    mylogger=logger  # use logger provided by caller
  else:
    mylogger = logging.getLogger() # user root logger
  blah...
  mylogger.info(...)
  mylogger.debug(...)
```
this way you get the current (new) behavior simply by calling scram() w/o a logger arg. and when we want to messages in some specific file or pipe or whatever, we can still do

**Comment by belforte** [comment]
@amaltaro  i.e. use simple `logging.info()` calls when writing a standalone script,  but for a library use a logger object.

**Comment by amaltaro** [comment]
Yes, it makes sense for code that can be shared among different projects (like everything that goes under Services). I'll keep that in mind in the future though.

**Comment by belforte** [comment]
@lecriste for additional credit you may add a handler to the root logger, use the new handler to log info messages (like the stdout from edmProvDump) to an ad hoc file, and keep the root logger logging debug and error to stdout. All in all it would be nice to have a clear message when edmProvDump fails, w/o being confused by a failure to open the out and read the hash from the first line.

**Comment by lecriste** [comment]
Cross posting:
https://github.com/dmwm/WMCore/issues/9113#issuecomment-483779596
