### ISSUE TITLE
report to MONIT the information  from PostJobs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5854]
like ASO status and refinement of ExitCode.
Should use Brian's suggestion to keep jobs in HTC queue until PJ has run.

**Comment by belforte** [comment]
see first comment from Brian here
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2830/2/1.html

**Comment by belforte** [comment]
@amaltaro @stiegerb this is  what I was talking about in monitoring meeting a bit ago, indeed you have no issue about this AFAIK, quoting Brian (see comment above):
```
Benjamin, Alan, and I were chatting about this last week in the WMAgent context.  You can tell HTCondor to keep the job ad in the queue until the postjob is run, allowing the postjob to make final updates to the ad.  They can fill in the details probably.
```
feel free to send us other info/details if you like, anyhow things look pretty clear to me, PJ can do a few condor_edit as needed to adjust job status and exit code.
We may need to add job statuses like "transferring" . we'll see

**Comment by belforte** [comment]
reference: https://its.cern.ch/jira/browse/CMSMONIT-59

**Comment by belforte** [comment]
@lecriste @todor-ivanov I do not remember if you both had interest in fixing this, or only one. Please comment. This is  rather urgent since we need the full picture in order to progress in validating and finalizing the new dashboard

**Comment by lecriste** [comment]
I started to look at it with Christian. Brian's comment is a good news as it impies we can rely on Benjamin's script to update job status and exit code also during transferring.

**Comment by lecriste** [comment]
@belforte's hint:
Need to modify the `LeaveJobInQueue` classAd from `False` to `True` until the last postJob has finished.
Mind the case in which the postJob crashes, leaving the classAd value to `True`. Such jobs must be cleaned up after the task expiration time (1 month).

**Comment by belforte** [comment]
From HTCondor manual https://research.cs.wisc.edu/htcondor/manual/v7.6/10_Appendix_A.html

```
LeaveJobInQueue:
    A boolean expression that defaults to False, causing the job to be removed from the queue upon completion.
```
What happens then is that the job needs to be explicitely remove from the queue with a `condor_rm` or a `PeriodicRemove`

I looked at one running grid job and indeed `LeaveJobInQueue` has the default `False` setting:
```
condor_q -run
[...]
37683387.0   cmsprd          5/8  20:42   0+00:03:01 slot1_3@glidein_97143_10231314@cms012.kipt.kha
[...]

belforte@vocms0194/config.d> condor_q 37683387.0 -l|grep -i leave
LeaveJobInQueue = false
belforte@vocms0194/config.d> 
```

We had a long history of managing `LeaveJobInQueue` for jobs in Scheduler Universe (jobuniverse==7) i.e. dagBoostraps, i.e. tasks [1]. But never touched this for jobs.
So we should set it to `True` when submitting and to False "after" PostJob has run and added the final ExitCode classAd. It may be enough to set it to False right then since "Ben's script" should pick up recently removed jobs as well and report them, but if we need to keep it around for a while should look into a PeriodicRemove to get rid of the job after a couple hours.
@lecriste @cronosnull you want to make sure that you understand the way and timing that classAds are reported in order to make a proper plan here. Then code changes should be simple. I believe that the ad for jobs can be changed at the beginning of this file, of course it needs testing:
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py
In particular you want to understand the PeriodicRemove in line 172 and following in case it needs to be adapted.


[1]
Here are some references for past discussioni of this topic in dagBootstrap context, which may help to understand

https://github.com/dmwm/CRABServer/issues/5506 
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

https://github.com/dmwm/CRABServer/issues?q=is%3Aissue+label%3A%22Area%3A+Kill%2FResubmit%2FDelete+cleanup%22+is%3Aclosed


https://github.com/dmwm/CRABServer/blob/74d1eef1ee32012b7ede24b0232242fdc42c8da0/src/python/TaskWorker/Actions/DagmanSubmitter.py#L469

https://github.com/dmwm/CRABServer/blob/74d1eef1ee32012b7ede24b0232242fdc42c8da0/src/python/TaskWorker/Actions/DagmanSubmitter.py#L499-L508

https://github.com/dmwm/CRABServer/blob/74d1eef1ee32012b7ede24b0232242fdc42c8da0/src/python/ServerUtilities.py#L37-L46

**Comment by lecriste** [comment]
> So we should set it to `True` when submitting and to False "after" PostJob has run and added the final ExitCode classAd. It may be enough to set it to False right then since "Ben's script" should pick up recently removed jobs as well and report them, but if we need to keep it around for a while should look into a PeriodicRemove to get rid of the job after a couple hours.
> @lecriste @cronosnull you want to make sure that you understand the way and timing that classAds are reported in order to make a proper plan here. Then code changes should be simple. I believe that the ad for jobs can be changed at the beginning of this file, of course it needs testing:
> https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py

@belforte I set `LeaveJobInQueue` to `true` as you said above and it works.

Upon a discussion with @cronosnull, we think the best approach is to add a job ClassAd for the postJob status, and read it in the monitoring script so that it can be used in the dashboard as a condition to change the displayed status of Condor completed jobs.

That said, the current PostJob.py values are listed [here](https://github.com/dmwm/CRABServer/blob/6a67a61b80ecba10d4c9095a9dc8c6d5c0a30e2b/src/python/TaskWorker/Actions/PostJob.py#L2594-L2598). Shall we simply use these status names in the new dashboard or stick to the [old dashboard values](https://gitlab.cern.ch/exp_dashboard/cosmic/blob/ad06a2fa0155efe292c527572f800ab18a4edbc5/dashboard.web-task-analysis-cms/lib/dashboard/dao/oracle/web-task-analysis/OracleWebAnDAO.py#L378-386)?

I think we should try to align to the values assigned to `info["State"]` in the `scripts/task_process/cache_status.py`, which reflect in the `crab status` output.

**Comment by belforte** [comment]
thanks for pointing out inconsistencies. Indeed it is time that we sort out wnpostproc vs. cooloff  etc.
Indeed we want the same statuses as in crab status output, which does not mean that we should not improve if possible. Does cooloff there really mean that job has failed and will be retried after a delay, or simply that PostJob has not run yet ?

**Comment by lecriste** [comment]
Looking at the code ([here](https://github.com/dmwm/CRABServer/blob/6a67a61b80ecba10d4c9095a9dc8c6d5c0a30e2b/src/python/TaskWorker/Actions/PostJob.py#L1676) and [here](https://github.com/dmwm/CRABServer/blob/6a67a61b80ecba10d4c9095a9dc8c6d5c0a30e2b/src/python/TaskWorker/Actions/PostJob.py#L2717)) it really means that job has failed and will be retried, I have seen this happening sometimes.

**Comment by belforte** [comment]
thanks. I have always been puzzled why old dashboard almost always says wnpostproc and only rarely toRetry. I guess they never changed wnpostproc to transferring.
