### ISSUE TITLE
Keep GenerateMONIT.py entirely in github

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/CRABServer#5867]
Keep the code of GenerateMONIT entirely in github and create a wrapper in the gitlab repository which should be used to act as a protection against multiple instances of the script and not having a duplicate data in ES. The wrapper to be a template configurable through puppet  machinery - this is the better alternative to the hard-coded name of the machine allowed to run the GenerateMONIT.py inside the script itself.

The script needs to be distributed in a different way now  since puppet will not do it for us any more it needs to enter into the .rpm package, so a change to the specc file is needed.

**Comment by belforte** [comment]
the work to do on CRAB side is now tracked in #5875 
@todor-ivanov if you like we can keep this open for the puppet/gitlab part

**Comment by belforte** [comment]
DOne long time ago
