### ISSUE TITLE
Move HTCcondor python bindings to v8.8.3

### ISSUE THREAD

**Issue by khurtado** [dmwm/CRABServer#5884]
Hello CRAB team,

I'm planning to upgrade the version of HTCondor in cmsdist (see issue below) for WMAgent. My question is... is there any test that has to be done at the CRAB side with a new condor version? 

https://github.com/cms-sw/cmsdist/issues/4877

**Comment by belforte** [comment]
crab can't currently work with 8.8
  will send ptrs to full thread later

**Comment by belforte** [comment]
actually CRAB should work with 8.8.2
@todor-ivanov is going to test it
see #5829 in particular the last few entries

@khurtado I am a bit puzzled as to what you exactly ask, since the condor version which we run in the schedd's is not defined in cmsdist, nor for CRAB, nor for WMA. Maybe this is about changing the condor binding library ? I am not sure were CRAB picks it, i.e. if it points to a specific version or uses whatever is in cmsdist... but I woud surely hope that if it chnges, changes are backward compatible !
In any care, surely, it is necessary to test CRAB TaskWorker (the only place where we use condor bingings) with the new version. I never had to deal with this, so have no clue as to where to start :-(

**Comment by khurtado** [comment]
@belforte Yes, this is more about the python bindings and making sure 8.8.1 doesn't break anything on your end. We use them in BossAir in WMAgent and are going to migrate to some new submission methods only available in v8.8.x. In CRAB's case, I am also expecting full backward compatibility, but wanted to create an issue, since some tests should probably still be done just in case.

https://github.com/dmwm/WMCore/pull/9133/files#diff-db6fcfce53a1897a040949c2657d39f3R149

**Comment by belforte** [comment]
OK. I renamed so that it is clear to me. Do  you know how exactly we pick the new (of old) bindings for testing ? Is this via this ?
https://github.com/cms-sw/cmsdist/blob/47aa1eb94f9eb1ef6c45c5ccbb97bf0eb42d1e01/crabtaskworker.spec#L16
we do not have a version number there !

**Comment by khurtado** [comment]
@belforte 
I think whenever a new package version is built (e.g.: htcondor), the packages depending on it will be rebuilt too (e.g.: CRAB), with the new dependency version for a specific branch/tag in cmsdist. The new package will append a 'comp(X)' attribute in the RPM name, where 'X' is the number of times that version has been built (X is 'empty' for the 1st one, then 2,3,4, etc).

For example, at present, condor uses version [8.5.7](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condor.spec#L1) in branch `comp_gcc630`.

If I look in my personal  [cmsrepo](http://cmsrep.cern.ch/cgi-bin/repos/comp.khurtado/slc7_amd64_gcc630?C=M;O=D) for [cms+crabtaskworker+3.3.1905.rc1](http://cmsrep.cern.ch/cmssw/repos/comp.khurtado/slc7_amd64_gcc630/0000000000000000000000000000000000000000000000000000000000000000/RPMS/d9/d9927344eafa280d3dfc33a04fd2da57/cms+crabtaskworker+3.3.1905.rc1-1-1.slc7_amd64_gcc630.rpm), built on April 24, the condor dependency version listed is indeed 8.5.7.

Then, if I look at my rebuilt version (comp): [cms+crabtaskworker+3.3.1905.rc1-comp-1] (http://cmsrep.cern.ch/cmssw/repos/comp.khurtado/slc7_amd64_gcc630/7f9b043717c5784489758d9aaa858f9cf97b93bd49aacc4a0451307ea5cecf02/RPMS/64/64380ffd9db03d9c2ddfc5d7b7cb96a2/cms+crabtaskworker-webdoc+3.3.1905.rc1-comp-1-1.slc7_amd64_gcc630.rpm), the dependency listed was automatically changed to 8.8.1, without me changing anything in the crab taskworker spec.

```
$ ls -l
total 9632
-rw-r--r-- 1 khurtado campus 4963165 Apr 24 08:09 cms+crabtaskworker+3.3.1905.rc1-1-1.slc7_amd64_gcc630.rpm
-rw-r--r-- 1 khurtado campus 4899700 Apr 26 12:49 cms+crabtaskworker+3.3.1905.rc1-comp-1-1.slc7_amd64_gcc630.rpm
$ rpm -qpR cms+crabtaskworker+3.3.1905.rc1-1-1.slc7_amd64_gcc630.rpm | grep condor
external+condor+8.5.7-comp3
$ rpm -qpR cms+crabtaskworker+3.3.1905.rc1-comp-1-1.slc7_amd64_gcc630.rpm | grep condor
external+condor+8.8.1
```

**Comment by khurtado** [comment]
@belforte I changed the title to change the condor bindings version, I updated it to 8.8.2 now.

**Comment by belforte** [comment]
OK. and thanks for the hints for testing. If I understand correctly at some point htcondor will be
updated in COMP repository and we will all use that. So we should check things before the same as you did. Or install the rpm which you built e.g. in preprod for a few days.
I am assigning to me and @lecriste for testing.

**Comment by belforte** [comment]
8.8.2 did not restore the API that we need, it should be in 8.8.3

**Comment by khurtado** [comment]
@belforte I have updated the cmsdist PR with 8.8.3 and built all packages in my personal repo. Could you give it a try?

http://cmsrep.cern.ch/cgi-bin/repos/comp.khurtado/slc7_amd64_gcc630?C=M;O=D

```
[khurtado@vocms055 /build/khurtado/883/tmp]$ rpm -qpR cms+crabtaskworker+3.3.1905.rc1-comp5-1-1.slc7_amd64_gcc630.rpm | grep condor
external+condor+8.8.3
```

**Comment by belforte** [comment]
Thanks Keny. WIll do.

**Comment by belforte** [comment]
That URL 
http://cmsrep.cern.ch/cgi-bin/repos/comp.khurtado/slc7_amd64_gcc630?C=M;O=D
is only accessible from inside CERN and I really do not know how to use it.
But I guess you meant to pick `cms+crabtaskworker+3.3.1905.rc1-comp5` from repository comp.khurtado
which I just did and indeed comes with HTCondor 8.8.3
differently from last attempt, now TaskWorker starts.
I will proceed to testing it.
Next we need a schedd with 8.8.3 @todor-ivanov can you get back one with this ?

**Comment by belforte** [comment]
Submitting one task worked:
https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=190604_233139%3Abelforte_crab_20190605_013131

I propose to update htcondor in cmsweb so we can build with it the version we have in pre-prod and give it a more through shake. Anyhow, this already confirm that the famous API is back, so I do not expect any problem.

**Comment by belforte** [comment]
Since ticket is a bit long and confused. Conclusion is that CRAB code works fine with 8.8.3 and later. And in any case the only piece of code where we had an issue is only executed on the schedd where htcondor is used from local installation, not from COMP.
COMP env. can be migrated at any time.
