### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5906]
As expected from the [if condition](https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L1081), [this line](
https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L1084) throws the error in the subject:
https://cms-logbook.cern.ch/elog/GlideInWMS/6920

**Comment by belforte** [comment]
hmmm... that code was there since years. I agree that it is buggy, but why does the error surface now ? Are we sure that it is OK that the reason is None at times ? We do not want to simply hide another problem.

**Comment by lecriste** [comment]
> hmmm... that code was there since years. I agree that it is buggy, but why does the error surface now ?

We triggered [this sighandler](https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L108) with the latest PostJob:
https://cms-logbook.cern.ch/elog/GlideInWMS/6927?mail0=40%20recipients

Not sure how likely it is that `sighandler` to be called. Anyhow that exception is catched so it might have been raised often without any effect, we just noticed it now by chance.


> Are we sure that it is OK that the reason is None at times ? We do not want to simply hide another problem.

I have no idea about what reason we may put here:
https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L110

**Comment by belforte** [comment]
I was not complaining about setting None in the new code, but why do we enter this `if doc_ids_reasons is None:` at all.  I never saw this message in years of looking at PostJob logs but yesterday I looked at two jobs at random and both had it. So I am asking why all of a sudden we trigger this condition.

**Comment by lecriste** [comment]
I would say: because we never triggered one of these
https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L112-L114

**Comment by belforte** [comment]
makes sense, but why did we do now ? Who is sending those signals to the PostJobs ?

**Comment by lecriste** [comment]
I think the subprocess reported in the second WARNING of [this postJob log](https://cmsweb.cern.ch/scheddmon/0194/cms1976/190607_100604:knash_crab_ZprimeToTT_M-1250_W-125_TuneCUETP8M1_13TeV-madgraphMLM-
pythia8imagednn_2016topv10/postjob.6.0.txt), as I said here:
https://cms-logbook.cern.ch/elog/GlideInWMS/6927?mail0=40%20recipients

**Comment by belforte** [comment]
that should have signaled the child, not the parent. Let's be sure that we have a full understanding.

**Comment by lecriste** [comment]
Indeed the parent terminated smoothly, see these lines after that WARNING: [1]
But the signaled child continued till the end of the PostJob (see these lines after the exception: [2]).
I thought that the child would live only within [this `with`](https://github.com/dmwm/CRABServer/blob/d970eac2bb258b7b6451984b38297a45bd7acf85/src/python/TaskWorker/Actions/PostJob.py#L2649). 

[1]
```
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob ====== Starting to prepare error report.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):DEBUG:PostJob Acquiring lock on error summary file.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):DEBUG:PostJob Acquired lock on error summary file.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob Updating error summary for jobid 6 retry 0 with following information:
'exit code' = 0
'exit message' = OK
Fri, 07 Jun 2019 13:48:48 CEST(+0000):DEBUG:PostJob Writing error summary file
Fri, 07 Jun 2019 13:48:48 CEST(+0000):DEBUG:PostJob Written error summary file
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob ====== Finished to prepare error report.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob ====== Starting to prepare WMArchive report.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob WMArchiveReport.6.0.json , /data/srv/WMArchiveWD/new/190607_100604:knash_crab_ZprimeToTT_M-1250_W-125_TuneCUETP8M1_13TeV-madgraphMLM-pythia8imagednn_2016topv10_WMArchiveReport.6.0.json
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob ====== Finished to prepare WMArchive report.
Fri, 07 Jun 2019 13:48:48 CEST(+0000):INFO:PostJob ======== Finished post-job execution with status code 0.
Ended TaskManagerBootstrap with code 0
```
[2]
```
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob ====== Starting to prepare error report.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):DEBUG:PostJob Acquiring lock on error summary file.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):DEBUG:PostJob Acquired lock on error summary file.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob Updating error summary for jobid 6 retry 0 with following information:
'exit code' = 90000 ('Post-processing failed')
'exit message' = Failure during post-job execution.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):DEBUG:PostJob Writing error summary file
Fri, 07 Jun 2019 13:48:56 CEST(+0000):DEBUG:PostJob Written error summary file
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob ====== Finished to prepare error report.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob ====== Starting to prepare WMArchive report.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob WMArchiveReport.6.0.json , /data/srv/WMArchiveWD/new/190607_100604:knash_crab_ZprimeToTT_M-1250_W-125_TuneCUETP8M1_13TeV-madgraphMLM-pythia8imagednn_2016topv10_WMArchiveReport.6.0.json
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob ====== Finished to prepare WMArchive report.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob Will not write postjob_env.txt file. Continue.
Fri, 07 Jun 2019 13:48:56 CEST(+0000):DEBUG:PostJob ------ Job classad values for debug purposes:
...
Fri, 07 Jun 2019 13:48:56 CEST(+0000):INFO:PostJob ======== Finished post-job execution with status code 1.
Ended TaskManagerBootstrap with code 1
```

**Comment by belforte** [comment]
sounds like those signhandler are invoked for all python code in the process, including the authenticated suprocess. So then it times out the handler is called and we get the odd error which likely triggters the `90000 ('Post-processing failed')`, then the subprocess closed and we go on normally, but w/o the classAds.
