### ISSUE TITLE
CMS_WMTool and CMS_TaskType for HammerCloud Jobs

### ISSUE THREAD

**Issue by cronosnull** [dmwm/CRABServer#5926]
Hello, 

According with https://github.com/dmwm/CRABServer/issues/5666#issuecomment-448685062 I was expecting to have jobs with CMS_WMTool set with HammerCloud and CMS)TaskType with either HCtest or HCother. 

Am I missing something?

Related to #5819, #5666 

Thanks,

**Comment by belforte** [comment]
something is indeed wrong
```
belforte@vocms0195/~> condor_q 41461726.0 -af:h cms_wmtool cms_tasktype crab_reqname
cms_wmtool cms_tasktype crab_reqname                                                      
USER       cmsRun       190730_031133:sciaba_crab_HC-95-T3_US_Rutgers-78042-20190730050305

```

**Comment by belforte** [comment]
Note that CRAB acknowledged the task as HC:
```belforte@vocms0195/cluster41435909.proc0.subproc0> condor_q 41461726.0 -af:h crab_hc
crab_hc
true   
```

**Comment by lecriste** [comment]
One problem can be in this line
https://github.com/dmwm/CRABServer/blob/f44bfd04e78c62ba1560cf79cbf0da9086759727/src/python/TaskWorker/Actions/DagmanCreator.py#L421
which looks for capital `HC` in `task['tm_activity']` which is `hctest`.

Should be `HC` in `HCTest` or `hc` in `hctest`?

**Comment by belforte** [comment]
hmm... we need to check, indeed it is a fragile check, since we do not control what HammerCloud people put in the activity field in the submission config. But clearly we want to use same check everywhere, and then consider making it case insensitive.
