### ISSUE TITLE
Pass file checksum to FTS

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5940]
requires adding it to transferdb
I guess this is why it was not done in #5893 
But now we have evidence of good output ending as 0 size files after ASO, so this will help to diagnose.
Ref:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5231/2.html

**Comment by belforte** [comment]
A simpler alternative would be to add code to transfer.py to check file size of the final copy at the the destination site and compare with the size stored in transfer db.
@dciangot does any of this impact the Rucio branch ? If you'll need the checksum in there I think we should through the effort of adding a column to transferdb

**Comment by dciangot** [comment]
Indeed this will come with the RUCIO-CRAB PR as soon as tests finishes on dev instance.

**Comment by dciangot** [comment]
#5951

**Comment by belforte** [comment]
See also #5034

**Comment by dciangot** [comment]
As Andrea pointed out recently, we are passing checksum 0000000 also when the filesize is not zero.
We have to understand at which point we are calculating this checksum and why it differs from the file size.
