### ISSUE TITLE
CRAB-Rucio integration v0.1

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5951]
Create a version of CRAB working with both plain FTS and Rucio transfers.

Data location and DBS publication still untouched.

doc reference: https://docs.google.com/document/d/1xwGexR9r-Pmd3Am12_tmQ0CHlfxMpV5Gn3D4MwAdvA4

**Comment by dciangot** [comment]
#6034 to be implemented for correct RUCIO dataset registration.
Tested on dev instance.

**Comment by dciangot** [comment]
From @belforte comment [here](https://github.com/dmwm/CRABServer/pull/6038#issuecomment-618654580).

R1. CRAB publication flag true/false stays in user control
R2. When publication is True, dataset name will be the same in DBS/Rucio
R3. When publication is False, Rucio dataset name will not have the numerical pset hash
     and will end with /Rucio/USER
R4. When doing data discovery for USER tier, TaskWorker will always check initially
    if dataset is in Rucio so to decide if use that or DBS origin_site for data location

**Comment by dciangot** [comment]
about R2. @belforte @amaltaro 
Making some tests with publication enabled I see the following:
```
Your task speficies an output LFN which fails validation in
 WMCore/Lexicon and therefore can not be published in DBS
Error detail: LFN candidate: /store/test/rucio/int/user/dciangot/TTJets_TuneCUETP8M2T4_13TeV-amcatnloFXFX-pythia8/crab_Rucio_20200427_112052/200427_092103/0001/DS2b_17_10000.root doesn't match any of the following regular expressions:
  /([a-z]+)/([a-z0-9]+)/(([a-zA-Z0-9\-_]+))/([a-zA-Z0-9\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)((/[0-9]+){3}){0,1}/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /([a-z]+)/([a-z0-9]+)/([a-z0-9]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)((/[0-9]+){3}){0,1}/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /store/(temp/)*(user|group)/(([a-zA-Z0-9\.]+)|([a-zA-Z0-9\-_]+))/([a-zA-Z][a-zA-Z0-9\-_]*)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /store/(temp/)*(user|group)/(([a-zA-Z0-9\.]+)|([a-zA-Z0-9\-_]+))/([a-zA-Z][a-zA-Z0-9\-_]*)/(([a-zA-Z0-9\-_]+)/)+([a-zA-Z0-9\-_]+).root
  /store/(backfill/[0-9]/){0,1}(t0temp/|unmerged/){0,1}(data|express|hidata)/([a-zA-Z0-9\-_]+)/([a-zA-Z][a-zA-Z0-9\-_]*)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([0-9]+)/([0-9]+)(/([0-9]+))?/([a-zA-Z0-9\-_]+).root
  /store/data/([a-zA-Z0-9\-_]+)/([a-zA-Z][a-zA-Z0-9\-_]*)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([0-9]+)/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /store/mc/(([a-zA-Z0-9\-_]+))/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)(/([a-zA-Z0-9\-_]+))*/([a-zA-Z0-9\-_]+).root
```
Now I see that clearly `/store/test/rucio/int` was not taken into consideration, but I think for the test with Rucio INT server we might need it. The question is, should work around this at CRAB level or this has any implication that can make publication to dbs fail?

**Comment by amaltaro** [comment]
@dciangot Diego, can't we drop the "int" bit of the LFN? After all, it already has the "test" part of the LFN.
I believe DBSServer uses the same lexicon to validate files that can be inserted, but perhaps @yuyiguo could confirm it.

**Comment by dciangot** [comment]
@amaltaro yes I think we can drop it, but anyhow still failing:

```
Error detail: LFN candidate: /store/test/rucio/user/dciangot/TTJets_TuneCUETP8M2T4_13TeV-amcatnloFXFX-pythia8/crab_Rucio_20200428_110137/200428_090241/0001/tree_10000.root doesn't match any of the following regular expressions:
  /([a-z]+)/([a-z0-9]+)/(([a-zA-Z0-9\-_]+))/([a-zA-Z0-9\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)((/[0-9]+){3}){0,1}/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /([a-z]+)/([a-z0-9]+)/([a-z0-9]+)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)((/[0-9]+){3}){0,1}/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /store/(temp/)*(user|group)/(([a-zA-Z0-9\.]+)|([a-zA-Z0-9\-_]+))/([a-zA-Z][a-zA-Z0-9\-_]*)/([a-zA-Z0-9\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([a-zA-Z0-9\-_]+).root
  /store/(temp/)*(user|group)/(([a-zA-Z0-9\.]+)|([a-zA-Z0-9\-_]+))/([a-zA-Z][a-zA-Z0-9\-_]*)/(([a-zA-Z0-9\-_]+)/)+([a-zA-Z0-9\-_]+).root
  /store/(backfill/[0-9]/){0,1}(t0temp/|unmerged/){0,1}(data|express|hidata)/([a-zA-Z0-9\-_]+)/([a-zA-Z][a-zA-Z0-9\-_]*)/([A-Z\-_]+)/([a-zA-Z0-9\-_]+)/([0-9]+)/([0-9]+)/([0-9]+)(/([0-9]+))?/([a-zA-Z0-9\-_]+).root```

**Comment by belforte** [comment]
yeah, we need to change Lexicon.py and build DBS with new WMCore.
this may take a bit. Until very recently it was assumed that
user data moved by Rucio are non in DBS.
I guess we always start with a software flag which makes that happens
and we can say "RUcio works in CRAB" while waiting for the above.

**Comment by belforte** [comment]
that said, i.e. explicitely allowing /store/test/rucio in LFN will make things more clear,
I do not see whay e.g. the second regexp is not matching. But parsing regexp in mind is such a pain !

**Comment by amaltaro** [comment]
@belforte I like using this website to learn more about regular expressions ;)
https://regex101.com/#python

**Comment by belforte** [comment]
@amaltaro thanks for the link, it is a nice tool. But .. let's stay with : I have no idea what odd use case those two unreadable regext are meant to capture, but if we want to store in DBS /store/test/* stuff, we should better make it explicit and clear in `Lexicon.py`

**Comment by belforte** [comment]
recap:  in order to register in DBS user files placed in RUCIO StorageElements, we need to update WMCore/Lexicon.py and rebuild DBS with the new WMCore.

We may want revisit the "naive" plan https://github.com/dmwm/CRABServer/issues/5951#issuecomment-620406657
after reviewing the name space policy

**Comment by yuyiguo** [comment]
DBS use the same naming conventions defined in the lexicon. Different data would go into different database, so we would not need to distinguish them on the names, right?
Yuyi

**Comment by belforte** [comment]
thank @yuyiguo but the real question is:
does DBS uses Lexicon.py, or does it implement same checks with independent code ?

In other words, assuming that we have good reasons to allow more LFN kinds (and I agree that we
need to be careful here), is it enough to update Lexicon.py and rebuild DBS, or do you need to change the source code as well ?

**Comment by yuyiguo** [comment]
DBS uses Lexicon.py. Any changes in Lexicon.py will affect DBS. This is an agreement between the data generator and bookkeeper to make sure the consistent checking.

**Comment by dciangot** [comment]
@belforte should we close this in favor of  #6041 ? to avoid confusion mainly? or we still need to keep track of this somehow?
