### ISSUE TITLE
Rucio transfer failing

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5969]
First attempt at validating the Rucio integration
https://cmsweb-test.cern.ch/crabserver/ui/task/191031_184111%3Abelforte_crab_20191031_194107/dbver/preprod

the transfer script fails to run :

```
[cms1627@vocms069 task_process]$ pwd
/home/grid/cms1627/191031_184111:belforte_crab_20191031_194107/SPOOL_DIR/task_process
[cms1627@vocms069 task_process]$ cat daemon.out.15085.0
[2019-10-31 19:42] Starting a new task_process, creating task_process_running file
[2019-10-31 19:42] REQUEST_NAME: 191031_184111:belforte_crab_20191031_194107
[2019-10-31 19:43] Starting task daemon wrapper
[2019-10-31 19:43] Running cache_status.py
[2019-10-31 19:43] Running transfers.py
[2019-10-31 19:43] No transfers.txt found, waiting for jobs to finish.
[2019-10-31 19:48] Running cache_status.py
[2019-10-31 19:48] Running transfers.py
[2019-10-31 19:48] No transfers.txt found, waiting for jobs to finish.
[2019-10-31 19:53] Running cache_status.py
[2019-10-31 19:53] Running transfers.py
[2019-10-31 19:53] ERROR: transfers.py exited with 1
[cms1627@vocms069 task_process]$ cat daemon.err.15085.0
Traceback (most recent call last):
  File "task_process/RUCIO_Transfers.py", line 10, in <module>
    from TransferInterface.RegisterFiles import submit
ImportError: No module named TransferInterface.RegisterFiles
[cms1627@vocms069 task_process]$ 

```

**Comment by belforte** [comment]
seem that Rucio client is missing on vocms069

1. we need to deploy really on ALL schedd's
2. a better error message would help
3. we need a general solution to the fact that errors in transfers.py can only be looked at by logging on the schedd

**Comment by dciangot** [comment]
Mmm, no.. This is the task worker tarball that is not fine. It Is missing
the Rucio transfer code. On which tw they are running?

D.

Il gio 31 ott 2019, 20:00 Stefano Belforte <notifications@github.com> ha
scritto:

**Comment by dciangot** [comment]
https://github.com/dmwm/CRABServer/blob/master/bin/htcondor_make_runtime.sh#L108

This in particular.

Il gio 31 ott 2019, 20:56 Diego Ciangottini <diego.ciangottini@gmail.com>
ha scritto:

**Comment by belforte** [comment]
crab-preprod-tw01  running 3.3.1911.rc3.patch1

**Comment by belforte** [comment]
the `CRAB3.zip` file inside
```
/data/srv/TaskManager/3.3.1911.rc3.patch1/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1911.rc3.patch1/data/TaskManagerRun.tar.gz
```
does not contain `CrabInterface' nor `TransferInterface` etc. which are indicated in
https://github.com/dmwm/CRABServer/blob/638971b36db43a479ae530e9e26dfe4bf1d934c4/bin/htcondor_make_runtime.sh#L108

Did this ever work for you in a TW built on vocms055 ?

**Comment by belforte** [comment]
in any case we still need Rucio client in the preprod schedd's

**Comment by belforte** [comment]
I believe that this is bugged and not working. it fails to propagate the new libraries even if I used it locally to patch my private TW. I have no idea how it could have ever worked, or how this new code was tested.
https://github.com/dmwm/CRABServer/blob/638971b36db43a479ae530e9e26dfe4bf1d934c4/bin/htcondor_make_runtime.sh

**Comment by belforte** [comment]
it is a bit tricky since the updateTMRuntime.sh creates a
/data/user/CRABServer/tmp/runtime/CRAB3.zip 
which has the new stuff...
somehow we (me? Diego?) managed to break the TW tarball creation. Needs to be tackled with fresh mind and clear determination, and fixed.

**Comment by belforte** [comment]
a bit of progress

differently from `src/python/TaskWorker`, `src/python/CRABInterface` is not put in `build/lib` by the build script, hence it does not go into `CRAB3.zip` for distribution to the schedd's via
https://github.com/dmwm/CRABServer/blob/638971b36db43a479ae530e9e26dfe4bf1d934c4/bin/htcondor_make_runtime.sh#L55-L56

full understanding still fails me. But clearly it is not enough to create a subirectory in src/python in order to get code into the schedd tarball

**Comment by belforte** [comment]
I suspect that this was bad
https://github.com/dmwm/CRABServer/pull/5954/commits/a2b09740453457f296cb6e4a95e5983de50c5fe1
where it changed `CRAB3_VERSION=3.3.0-pre1` to `CRAB3_VERSION=3.3.1706.rc2`

for sure it breakes the `updateTMRuntime.sh` which we use to update the tarballs when installing by hand in VM's since here che copy fails:
https://github.com/belforte/CRABServer/blob/f4afd9c9ff7b229663784c91720b99e60efd560d/scripts/Deployment/TaskWorker/updateTMRuntime.sh#L17-L18

Now.. if I only could find the equivalent of that `updateTMRuntime.sh`  in the build process....

**Comment by belforte** [comment]
reverting to `CRAB3_VERSION=3.3.0-pre1` does indeed fix the installation on private VM

**Comment by belforte** [comment]
I guess I will start by simply testing with this change in a build, then try to understand.

**Comment by belforte** [comment]
anyhow when building rpms' the call to https://github.com/dmwm/CRABServer/blob/638971b36db43a479ae530e9e26dfe4bf1d934c4/bin/htcondor_make_runtime.sh is in the spec file
https://github.com/cms-sw/cmsdist/blob/b0e4d6b2ec815dbcf045f76b1f4ba5f196ae7c1c/crabtaskworker.spec#L36-L42

relevant lines are:
```
sed -i 's|CRAB3_VERSION=.*|CRAB3_VERSION=%{realversion}|' bin/htcondor_make_runtime.sh
sed -i 's|CRABSERVERVER=.*|CRABSERVERVER=%{realversion}|' bin/htcondor_make_runtime.sh
sed -i 's|WMCOREVER=.*|WMCOREVER=%{wmcver}|' bin/htcondor_make_runtime.sh

RPM_RELEASE=1 ./bin/htcondor_make_runtime.sh
```

**Comment by belforte** [comment]
I rolled back the change in 3.3.1911.rc3.patch2 but it still
didn't work for the rpm build. I still get the old `CRAB3.zip` w/o `TransferInterfaces`

**Comment by belforte** [comment]
damn...  creation of the CRAB3.zip is done TWICE in the htcondor_make_runtime !!!!
at this line when RPM's are made (and which does not indicate the new TransferInterface directory)
https://github.com/dmwm/CRABServer/blob/4dc39d11b86b677efde379465197c49edc88cf1c/bin/htcondor_make_runtime.sh#L56
and at this other line when building on a VM:
https://github.com/dmwm/CRABServer/blob/4dc39d11b86b677efde379465197c49edc88cf1c/bin/htcondor_make_runtime.sh#L108

* the former was not updated by @dciangot 
* the latter was made useless by the failing to copy in `updateTMRuntime.sh`

**Comment by belforte** [comment]
closed too soon. I forgot that TransferInterace is missing in the build directory:
```
belforte@vocms055/lib> ls /build/belforte/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1911.rc3.patch3/CRABServer-3.3.1911.rc3.patch3/build/lib 
ApmonIf.py	    CRABQuality.py	 HTCondorUtils.py	 PandaServerInterface.py   RESTInteractions.pyc
ApmonIf.pyc	    CRABQuality.pyc	 HTCondorUtils.pyc	 PandaServerInterface.pyc  ServerUtilities.py
apmon.py	    DashboardAPI.py	 Logger.py		 ProcInfo.py		   ServerUtilities.pyc
apmon.pyc	    DashboardAPI.pyc	 Logger.pyc		 ProcInfo.pyc		   taskbuffer/
CMSGroupMapper.py   HTCondorLocator.py	 MultiProcessingLog.py	 Publisher/		   TaskWorker/
CMSGroupMapper.pyc  HTCondorLocator.pyc  MultiProcessingLog.pyc  RESTInteractions.py
belforte@vocms055/lib> 
```
even if the zip command is now correct, it can't find it.

**Comment by belforte** [comment]
hmm...
```
belforte@vocms055/cmsdist> grep 'creating build' /build/belforte/w/BUILD/slc7_amd64_gcc630/cms/crabtaskworker/3.3.1911.rc3.patch3/log |tail -10
creating build/lib/WMCore/FwkJobReport
creating build/lib/WMCore/JobSplitting
creating build
creating build/lib
creating build/lib/TaskWorker
creating build/lib/TaskWorker/Actions
creating build/lib/TaskWorker/DataObjects
creating build/lib/TaskWorker/Actions/Recurring
creating build/lib/taskbuffer
creating build/lib/Publisher
belforte@vocms055/cmsdist> 

```
why only TaskWorker Publisher and taskbuffer go into the build ?

**Comment by belforte** [comment]
mayebe something wrong in `__init__.py` in TransferIntefaces ? Surely it should not be uses as it is now to contain modules which should better belong in named files. But it seems to lack
```
__all__ = []
```
when compared with `__init__` in TaskWorker or Publisher subdirs.

**Comment by belforte** [comment]
I think that @dciangot had forgot about this https://github.com/dmwm/CRABServer/pull/5610  :-(

In particular these lines appear in need of an editing
https://github.com/dmwm/CRABServer/blob/a34e67070fa28a8df6456e9c56d625e24e79a66e/setup.py#L47-L48

Or avoid a new directory alltoghther.. is this only for two files ? 
I am really confused as to how code is organized for Rucio.
