### ISSUE TITLE
Add rucio quota check before submitting in Rucio mode

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5977]

**Comment by amaltaro** [comment]
In case it helps, I started working on this PR:
https://github.com/dmwm/WMCore/pull/9394

Still some final tests/tuning to be made though.

**Comment by dciangot** [comment]
@amaltaro I think that could be useful indeed

@belforte what do you think?

**Comment by belforte** [comment]
thanks @amaltaro We will work to use what you provide

**Comment by belforte** [comment]
duplicate of #6172
