### ISSUE TITLE
Use WMCore/Services/Rucio for CRAB-Rucio interactions

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5982]
Finally converged toward the decision on using WMCore for any Rucio interaction.
The Rucio service class is a WIP (see also (*)) and I'm going to test it and contribute for the missing part on CRAB side.
As agreed with @amaltaro , we need to coordinate a bit for having a baseline for development.

(*)
https://github.com/dmwm/WMCore/pull/9401

**Comment by dciangot** [comment]
same applies to #5978 #5982

**Comment by belforte** [comment]
this is now done for TaskWoker components. ON schedd we directly use RucioClient, could change at some point.. but not urgent

**Comment by dciangot** [comment]
I think we converged on using plain RUCIO client API for the output transfer part right? Should we close this issue? Or we still have some item to solve? @belforte

**Comment by belforte** [comment]
thanks Diego ! +1
For the record, let's summarize:
We came to the conclusion that WMCore Rucio class is not a generic wrapper, but something heavily customized for internal WMA/WMCore needs. And in agreement with WMCore developers have stopped using it everywhere. Rucio python client is clean and simple enough that using it directly makes code easier to read and to change.
