### ISSUE TITLE
Introduce tool for inserting local data into Rucio

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5986]
prototype here (*) has to be imported somehow to be discussed yet

(*)https://github.com/dmwm/CMSRucio/tree/master/docker/CMSRucioClient/scripts#synccmssitespy

**Comment by dciangot** [comment]
Need to follow this (*)

(*) https://github.com/cms-sw/cmsdist/issues/5199

**Comment by dciangot** [comment]
Rahul is implementing something on this line to be available soon via cvmfs https://github.com/dmwm/CMSRucio/issues/275

**Comment by belforte** [comment]
I propose to close then. Or move to a "documentation" issue i..e try it out and add a (couple of) FAQs wating for a place where to put this in the SWGuide or the workbook, or maybe it will appear in Rucio twiki ?
