### ISSUE TITLE
liimit requested memory as a function of requested cores

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5995]

**Comment by belforte** [comment]
see: https://github.com/dmwm/CRABServer/issues/5965#issuecomment-562334857

all in all the requests with >=10GB and 4 or 8 cores are likely reasonable, and I think the cut should be
```
max(5, ncores*2.5)
```

**Comment by lecriste** [comment]
+1
Will do the same in
https://github.com/dmwm/CRABClient/issues/4853

**Comment by belforte** [comment]
FYI @lecriste I have just deployed this in preprod-tw01
will test later tonight. going home now.
