### ISSUE TITLE
T3_CH_CERN_Opendata is not a viable location

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6005]
so it should be skipped from what PhEDEx reports and in case tape recall request issued.
See:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/4369/2/1/1/1/1/1/1/1/2/1/1/1.html
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5460/2/1/1/1.html

**Comment by lecriste** [comment]
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5460/2/1/1/1/1/1.html

**Comment by belforte** [comment]
indeed it was done already, sorry that I forgot
https://github.com/dmwm/CRABServer/pull/5806
