### ISSUE TITLE
move available schedd's in a separate file

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6009]
with more crabserver clusters coming online with K8s, it is not convenient to have a single external REST conifg URL where a long list of schedd's is repeated many times, or (worse) a plethora of external config files. Since that makes it tedious to change one schedd status and will lead in time to diverging lists (as happened already in the past) for no good reason.
Better that the ext. config file only has what is specific of a given cluster (cache and DB urls) and can refer to the list of schedd's as a separate URL. Then we maintain simply a list of schedd's for e.g. Production and Test. It may even be that a single schedd list is enough, currently all CRAB clusters use the same. We should keep the possibility to explicitely specify a fee schedds'  though, as this could be useful for small tests.
This will require to change 
https://github.com/dmwm/CRABServer/blob/5d86abef9c69e9450c205f2d218af5a49353956d/src/python/CRABInterface/Utils.py#L87
so that it looks for an URL listing schedd's and if needed download it and inserts it in the config.

This may also be a good time to look into replacing `cherrypy.log` with same logger as everywhere else, possibly moving up the call to `initLogger` in `RESTBaseAPI.py`
https://github.com/dmwm/CRABServer/blob/5d86abef9c69e9450c205f2d218af5a49353956d/src/python/CRABInterface/RESTBaseAPI.py#L65

**Comment by belforte** [comment]
@ddaina let's talk about this.I think it will be a good first execise for you to get some insight into CRAB services configuration, besides it will hopefully simplify our configuratin management as we move from puppet to docker and K8s

**Comment by ddaina** [comment]
Link to the new config files: 
cmsweb-rest-config.json: https://gitlab.cern.ch/ddirmait/CRAB3ServerConfig/-/blob/%236009_fix/cmsweb-rest-config.json
cmsweb-shedds-config.json: https://gitlab.cern.ch/ddirmait/CRAB3ServerConfig/-/blob/%236009_fix/cmsweb-shedds-config.json

**Comment by belforte** [comment]
@ddaina I tested that we can make one more minor, yet useful simplification:
in this line
https://gitlab.cern.ch/ddirmait/CRAB3ServerConfig/-/blob/%236009_fix/cmsweb-rest-config.json#L6
replace `cmssrv623.fnal.gov:9620` with `cmsgwms-collector-global.fnal.gov`
We could also make same change in config json which we use now, can you do it ?

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6037
