### ISSUE TITLE
validate WMCore 1.3.1

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6025]
Need to switch to 1.3.1.pre2 or later from current 1.2.9

**Comment by belforte** [comment]
works on my VM via /data/user.  Will test a build. CRAB Client also appears OK

**Comment by belforte** [comment]
built 3.3.2003.rc4 with WMCore 1.3.1.pre2
and installed TW in stefanovm.cern.ch

**Comment by belforte** [comment]
tested OK both on stefanovm and stefanovm2
@ddaina please use this  3.3.2003.rc4 with WMCore 1.3.1.pre2 also to build the container and have it deployed on test k8s cluster. Should then make a PR for crab* spec files in cmsdist so that we can have it in preprod as well. Even if TaskWorker in this version does not use new myproxy credential, I think it is important to do a good test that our code works with WMCore 1.3.,1

**Comment by ddaina** [comment]
New TW version (3.3.2003.rc4) was deployed on crab-preprod-tw02

**Comment by belforte** [comment]
Daina built it in COMP and installed on preprod-tw02
I ran a first test task and it is OK.

**Comment by belforte** [comment]
let's run a few more tasks before closing

**Comment by belforte** [comment]
all done and deployed in production
