### ISSUE TITLE
Modify the value for CMS_WMTool

### ISSUE THREAD

**Issue by cronosnull** [dmwm/CRABServer#6031]
As we are working to add the `CMS_WMTool` in the job monitoring InfluxDB condor data, we found that we have `CMS_WMTool` as `USER` for CRAB jobs and User for CMSConnect. As the other values in that attribute are all Titled case, can you please modify the set value to be `User`?
I think it is done in this method: https://github.com/dmwm/CRABServer/blob/bace6ecddb3c941a1d9d474a4c744043d4424e83/src/python/TaskWorker/Actions/DagmanCreator.py#L427

Also, as a related issue, there are still some jobs that have type "analysis" (with quotes) [1]. Last time we checked that with @lecriste, they were "virtual" jobs as I understood (e.g. they don't have either an assigned site or CRAB_Id).

[1] https://monit-kibana.cern.ch/kibana/goto/4db1e334377a6685a80b42d1fab4f9a6

**Comment by belforte** [comment]
thanks @cronosnull . Will do.

**Comment by leggerf** [comment]
Why are we monitoring virtual jobs? Is it useful to have them in the monitoring? Remember we can also set the Type to DONOTMONIT and then we don't store them.

@cronosnull maybe it is better to fix USER -> User in the spider for the moment (until it is fixed in CRAB), so that we can give green light to the MONIT team to proceed, otherwise this is going to drag again

**Comment by cronosnull** [comment]
@leggerf sure, I can deploy it on Monday with the change to ES7.

**Comment by belforte** [comment]
indeed even if I change this in CRAB "now" and rush it into production deployment, user tasks submitted before will keep reporting using old code, for up to one month.

**Comment by belforte** [comment]
@leggerf @cronosnull @lecriste  what is a virtual job ?

**Comment by lecriste** [comment]
I think Christian means a job with jobUniverse != 5.

**Comment by cronosnull** [comment]
Thanks @lecriste, yes that was the case.

**Comment by belforte** [comment]
@leggerf @cronosnull  were is the authoritative reference for these attributes naming, including case ? We want to be sure we do not discover capitalization issues (or name typos) one at a time. I thought there was a plan to validate attributes before reporting, I vaguely remember Valentin had written a prototype, but I can't find pointers to details.

**Comment by belforte** [comment]
still need to address this:

there are still some jobs that have type "analysis" (with quotes) [1]. Last time we checked that with @lecriste, they were "virtual" jobs as I understood (e.g. they don't have either an assigned site or CRAB_Id).

[1] https://monit-kibana.cern.ch/kibana/goto/4db1e334377a6685a80b42d1fab4f9a6

**Comment by leggerf** [comment]
values are in the google sheet we agreed upon many months ago

https://docs.google.com/spreadsheets/d/1x73SxboZqNvpYKHmaJ9PioT3itpw4qQrTjUecnKLTi4/edit#gid=0


Il 27/03/2020 16:30, Stefano Belforte ha scritto:

**Comment by belforte** [comment]
@leggerf THANKS !

**Comment by belforte** [comment]
about `data.Type:"analysys"` with the extra quotes, interstingly those jobs apperas to have the extra quotes also around other attributes e.g.
https://monit-kibana.cern.ch/kibana/app/kibana#/doc/monit_prod_condor_raw_metric_v002-*/monit_prod_condor_raw_metric_v002-2020-03-27/raw_metric?id=crab3-5@vocms059.cern.ch%2338567.0%231563101823%231585323361&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))

```
data.CMS_WMTool | "USER"
data.TaskType | "cmsRun"
data.Type | "analysis"
```
at initial look those all have splitting mode automatic. And are all in status Held.

**Comment by belforte** [comment]
also very few jobs, 60 in last week. Sees like when something goes wrong some bad default slips in. I will check a couple jobs on condor side.
here's one
```
-- Schedd: crab3@vocms0121.cern.ch : <137.138.152.48:4080?... @ 03/27/20 20:57:51
 ID          OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD
41101054.0   cms1379         7/20 00:55   1+00:17:34 H  10   0.3 condor_dagman -p 0 -f -l . -Lockfi

Total for query: 0 jobs; 0 completed, 0 removed, 0 idle, 0 running, 0 held, 0 suspended 
```

It is quite odd that it runs condor_dagman, not the dagman bootstrap script.

**Comment by belforte** [comment]
Oh my ... those jobs are from last July !!!
```
    "metadata.timestamp": [
      "2020-03-27T19:36:02.000Z"
    ],
    "data.QDate": [
      "2019-07-19T22:55:14.000Z"
    ],
    "data.JobCurrentStartDate": [
      "2019-07-19T22:55:23.000Z"
    ],
    "data.EnteredCurrentStatus": [
      "2019-07-20T23:12:57.000Z"
    ],
```

A good cleanup is due.
I will take care. No code change is needed, nor would help.

**Comment by belforte** [comment]
I asked Prajesth to clean up:
https://cms-logbook.cern.ch/elog/GlideInWMS/7325

**Comment by belforte** [comment]
@cronosnull @leggerf @ddaina I have hacked the CRAB TaskWorker in production (crab-prod-tw01) so that CMS_WMTool has proper capitalization. This will only be for newly submitted tasks.

**Comment by leggerf** [comment]
thanks Stefano!

Il 27/03/2020 22:26, Stefano Belforte ha scritto:
