### ISSUE TITLE
NANOAOD discovery with RUCIO WMCore

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#6035]
I have a dedicated instance up and running that is ready for testing NANOAOD discovery within other issues related to including RUCIO WMCore class into CRAB transfers.

@amaltaro @belforte regarding the NANOAOD discovery I have a couple of points to discuss with you techinally:
- will the NANOAOD be only moved by RUCIO or also the DBS metadata will be stored?
- in other words, correct me if I'm wrong, but we have to 2 points to solve for CRAB implementation
 1- lfn2pfn
 2- jobsplitting

Regarding 1 I think that with some work we would like to be in the situation where RUCIO is used as fallback source of truth w.r.t. PhEDEx

About 2 it really depends on how things will be managed, staying with DBS will require probably ~0 effort.

**Comment by dciangot** [comment]
Ok, just got from @ericvaandering that the DBS discovery will stay there. So the whole work collapse into having a fallback to Rucio when looking for available data location

**Comment by dciangot** [comment]
Since we are using this (*) (@belforte am I right?), shall we add a third fallback here(**) ?

(*) https://github.com/dciangot/CRABServer/blob/master/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L145
(**) https://github.com/dmwm/WMCore/blob/1.3.3.pre1/src/python/WMCore/Services/DBS/DBS3Reader.py#L639

**Comment by amaltaro** [comment]
Diego, I don't know how exactly the fallback is used within CRAB. However, I think it would be cleaner to actually have the fallback call to be done by the client (if possible), instead of adding multiple data sources into the same WMCore wrapper module.

**Comment by dciangot** [comment]
ok, so if this (*) fails, we go for Rucio one? This is what you suggest?
Even though since the WMCore wrapper already has the dbs and phedex options, I thought that third one for rucio could have been of more general use (and  the use this option in the fallback implemented on clientside). Other than that I don't have a particular preference, so that's ok for me.

(*) https://github.com/dciangot/CRABServer/blob/master/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L145

**Comment by amaltaro** [comment]
Yes, I know it's functional to have phedex (or rucio) implemented within that DBS data discovery, but it sometimes makes things a bit more difficult to maintain in WMCore. 
If possible, I would like to avoid referencing difference services on those wrapper modules. It won't be a big problem if we have to add Rucio APIs into the DBS wrapper module though.

**Comment by dciangot** [comment]
Ok, for me it's fine to put Rucio stuff on client side, not much of a difference. I just got confused seeing phedex option in there.

**Comment by amaltaro** [comment]
Thanks, Diego. This module should give you all the necessary APIs for data discovery:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py

Please let us know if there is anything missing there.

**Comment by ericvaandering** [comment]
Maybe I misunderstood your question. In terms of location information, DBS should not be used for NanoAOD, only PhEDEx and Rucio. Once we make this switch, Rucio will be preferred for NanaAOD(SIM)

DBS is still the source of information for runs, lumis, events per file, etc. and parentage. 

For USER tier data, DBS for now, but eventually Rucio may have better information about that data than DBS.

**Comment by belforte** [comment]
Hi @ericvaandering 
AFAIU this discussion sums up to
* do not use `WMCore/Services/DBS/DBSReader/listfFileBlockLocation` to find where data are ! [1]
* only use DBS to find block/file/run/lumi/event info
* then explictly call Rucio or PhEDEx or use DBS orgin_site as appropriate 

Which of course makes perfect sense. As @amaltaro pointed out, it is a bit unfortunate that original developers tried too hard to encapsulate internals, and hid calls to PhEDEx inside calls to DBS, making unclear which Service one is talking with and overall making it hard to understand how exactly DBS API's are called and at times impossible to control how those are called.

So it sounds like this is the time that we should go for some more cleanup.
@amaltaro how do you plan to do this WMA side ? Will you stop using `DBSReader/listfFileBlockLocation` as well ? Or maybe you already do not use it ? If that's there only for CRAB, we may gain by fully removing it from WMCore to avoid anyone being confused 5 years from now, when possibly none of us will be there to explain.

[1]
https://github.com/dmwm/WMCore/blob/c330ad532a96b1a367872e3c0d1318bc8a903f3c/src/python/WMCore/Services/DBS/DBS3Reader.py#L606

**Comment by ericvaandering** [comment]
Ah, I had not read all of Alan's comments. Yeah, that does seem strange.

**Comment by dciangot** [comment]
So, couple of questions:
1 - will we have a dataset that is not available in Phedex while it is in Rucio? In other words, the fallback order for NANOAOD should be Rucio then  Phedex or Phedex then Rucio? 
2 - I think we are going to need a crab-rucio account with no quota anywhere just for data location, aren't we?

**Comment by dciangot** [comment]
3 - do we have a dataset that I can test against?

**Comment by belforte** [comment]
I can give partial replies, Eric and Nick should fill in
> So, couple of questions:
> 1 - will we have a dataset that is not available in Phedex while it is in Rucio?
I'd rather be prepared for it to happen
> In other words, the fallback order for NANOAOD should be Rucio then Phedex or Phedex then Rucio?
Rucio first
> 2 - I think we are going to need a crab-rucio account with no quota anywhere just for data location, aren't we?
I can't answer
> 3 - do we have a dataset that I can test against?
I can't answer

**Comment by ericvaandering** [comment]
On Apr 16, 2020, at 7:08 AM, Stefano Belforte <notifications@github.com<mailto:notifications@github.com>> wrote:



I can give partial replies, Eric and Nick should fill in

So, couple of questions:
1 - will we have a dataset that is not available in Phedex while it is in Rucio?
I'd rather be prepared for it to happen
In other words, the fallback order for NANOAOD should be Rucio then Phedex or Phedex then Rucio?
Rucio first

Correct



2 - I think we are going to need a crab-rucio account with no quota anywhere just for data location, aren't we?
I can't answer

Yeah, I guess so. Do you have an X509 certificate for the CRAB service? Send me the DN.

3 - do we have a dataset that I can test against?
I can't answer

~All the data on Disk should be registered in the integration Rucio.

**Comment by belforte** [comment]
Hi @ericvaandering we have several service certificates, each named after one specific TaskWorker instance (VM). I am not sure any of those would fit here, none is expected to last forever. Can you give me some context ? Is CRAB expected e.g. to always use a specific DN to query about data location ? Something like "what we use now to access CMSWEB" ? (the latter would be the inclusive set of all the TW ones).

**Comment by ericvaandering** [comment]
No, you could use any of your DNs and they would all get mapped to one account in Rucio. 

But I'd need the DNs of all certs

**Comment by belforte** [comment]
ok, basically same use case as for cmsweb. does it matter wether they are in VOMS ?
currently we have:
 ```
/DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw01.cern.ch
 /DC=ch/DC=cern/OU=computers/CN=tw/crab-prod-tw02.cern.ch
 /DC=ch/DC=cern/OU=computers/CN=tw/crab-preprod-tw01.cern.ch
 /DC=ch/DC=cern/OU=computers/CN=tw/crab-preprod-tw02.cern.ch
 /DC=ch/DC=cern/OU=computers/CN=tw/crab-preprod-tw03.cern.ch
 /DC=ch/DC=cern/OU=computers/CN=tw/crab-dev-tw01.cern.ch
```
the beauty of DN's with the machine name in it is that they are renewed automatically via puppet, the pain is of course that machine names can change

**Comment by dciangot** [comment]
Just created I first draft PR for the needed changes. Please take a look.
Also, we need to keep in mind to put Rucio client in the TW build at this point @belforte .

**Comment by dciangot** [comment]
Also, as discussed at the meeting today with @ericvaandering . For the moment it would be safer to keep the Rucio location active only for NanoAOD* datasets. So I'm going to add this filter

**Comment by belforte** [comment]
:+1:

**Comment by belforte** [comment]
can you elaborate on "put Rucio client in the TW build" ? I think we spoke about it but I forgot the details. It would be good to have a separate issue about that.

**Comment by dciangot** [comment]
Well, we did avoid it since we put rucio client on schedds. But now we are going to need it on TW side for this location procedure.  

Ticket here #6039

**Comment by dciangot** [comment]
Well, we did avoid it since we put rucio client on schedds. But now we are going to need it on TW side for this location procedure.  

Ticket here #6039

**Comment by ericvaandering** [comment]
OK, I have added all the DNs above to use the crab_server Rucio account. Please try it. 

If these are registered centrally (CRIC or otherwise) we can add a connector to do this automatically. If not, manually is OK (eventually I think you will ask the transfer ops Cat-A).

**Comment by belforte** [comment]
yes, those are in CRIC, which is how they get authorization for CMSWEB

**Comment by belforte** [comment]
you can find them on the browser by going to
https://cms-cric.cern.ch/accounts/account/list/
and typing `CN=tw` in the "filter by DN" box.
I presume there's also a way to get this via API, but do not know which, Panos can surely help !

**Comment by belforte** [comment]
I believe that everything covered here was done and CRAB TaskWorker
version 3.3.2005.rc3 now running in preprod has all.
So this could be closed.
@dciangot do you agree ?

**Comment by dciangot** [comment]
Yep, I'm closing this.
