### ISSUE TITLE
deploy simpler WMArchive structure from WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6036]
need to build TW tarballs with a WMcore version which includes this
https://github.com/dmwm/WMCore/pull/9631
so that new PostJobs will not send lumi/event lists to WMArchive

**Comment by amaltaro** [comment]
Stefano, anything starting in tag 1.3.3.pre2 will have it. Cheers!

**Comment by belforte** [comment]
I have built a TaskWorker 3.3.2004-comp2 in repo comp.belforte with WMCore 1.3.3 and am testing it in stefanovm2.
My usual HammerCloud dataset does not have enough lumis to see a difference. Need to find a good example to verify all is OK.

**Comment by belforte** [comment]
Tested now. All OK.
These are reports from same task submitted to TW with old/new WMCore
```
belforte@vocms059/WMArchiveWD> ls -s processed/2020-04-23/200423_042922:belforte_crab_20200423_062918_WMArchiveReport.5.0.json
4 processed/2020-04-23/200423_042922:belforte_crab_20200423_062918_WMArchiveReport.5.0.json
belforte@vocms059/WMArchiveWD> ls -s processed/2020-04-23/200423_043036:belforte_crab_20200423_063026_WMArchiveReport.5.0.json
8 processed/2020-04-23/200423_043036:belforte_crab_20200423_063026_WMArchiveReport.5.0.json
belforte@vocms059/WMArchiveWD> 
belforte@vocms059/WMArchiveWD> wc -w processed/2020-04-23/200423_042922:belforte_crab_20200423_062918_WMArchiveReport.5.0.json
272 processed/2020-04-23/200423_042922:belforte_crab_20200423_062918_WMArchiveReport.5.0.json
belforte@vocms059/WMArchiveWD> wc -w processed/2020-04-23/200423_043036:belforte_crab_20200423_063026_WMArchiveReport.5.0.json
657 processed/2020-04-23/200423_043036:belforte_crab_20200423_063026_WMArchiveReport.5.0.json
belforte@vocms059/WMArchiveWD> 

```

**Comment by belforte** [comment]
spec files updated. Next CRAB TaskWorker build wll have the fix

**Comment by belforte** [comment]
ref: https://github.com/cms-sw/cmsdist/pull/5776
