### ISSUE TITLE
Include Rucio client in TW build

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#6039]
We did avoid it so far, since we put rucio client on schedds. But now we are going to need it on TW side for NANOAOD data location.

**Comment by belforte** [comment]
? I thought we use an API from WMCore, does that need more client code ? I would have thought that whatever is needed is part of WMCore. No ?
Does not Rucio have an http interface to do queries ?
Anyhow.. if you can make it explicit what exactly is needed... is this adding one item to the crabtaskworker.spec file in `cmsdist`` ? Or ... ?

**Comment by belforte** [comment]
@amaltaro why have same thing in cvmfs and CMS COMP ? How do I decide which one to use ?
Do we really have hosts where we run services which can't mount CVMFS ? I would expect we try to reduce what we build and maintain.

**Comment by amaltaro** [comment]
I believe the cvmfs deployment came after we had built things in COMP.
I'm also not sure how robust it would be to have such services (WMAgent, MicroServices) relying on packages deployed in cvmfs. One thing is to load the libraries and use it; another thing is to use use all year round.

**Comment by belforte** [comment]
thanks Alan. So I presume this will do
https://github.com/cms-sw/cmsdist/pull/5768
Diego is it easy for you to test your own build, before we merge it ?

**Comment by amaltaro** [comment]
It should be enough. I have recently updated the client version and the default configuration, see:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/rucio-config.file

What you might need to test though is that the (I think it's RUCIO_HOME) environment variable points to the correct rucio.cfg file.

**Comment by belforte** [comment]
@dciangot I have build TW 3.3.2004-comp in repo comp.belforte with this and installed it in stefanovm2.cern.ch
I see that rucio client has appeared in current/slc7_amd64_gcc630/external/ but it would be good to test. thanks

**Comment by belforte** [comment]
tested. all OK.
