### ISSUE TITLE
handling of user produced data in Rucio

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6041]
I am using this at the very least to collect useful hints which have
been coming scattered around now closed PR's and Issues and from other places:

https://github.com/dmwm/WMCore/pull/9667

https://github.com/dmwm/CRABServer/pull/6038#issuecomment-620846000

**Comment by belforte** [comment]
@dciangot I am not sure what to do with this. Do you ?
We have something that put outputs in Rucio, but maybe those discussion are useful in order to refine what we exactly do ?

**Comment by belforte** [comment]
we need to have time to think... after py3 migration ?

**Comment by belforte** [comment]
adding this ref for the time we will start really commissioning Rucio in CRAB and review all this mess
dmwm/CMSRucio#159 (comment)

**Comment by dciangot** [comment]
#6872 started a draft PR. Soon circulating here the document with the discussed implementation

**Comment by dciangot** [comment]
Just to add a reference for the implementation proposal here: 

https://docs.google.com/document/d/1D9Ps67gx7kFRohnHyS8HMXIJ3WUDCAmrkOHIFAVlUKA

I'll keep track of the open items in PR #6872 soon after few tests that I'm doing right now

**Comment by belforte** [comment]
all work items menioned here are done. I think that this issue serves no purpose at this time
