### ISSUE TITLE
make it easy to deal witth multiple REST host/DB instances

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6050]
see:
https://github.com/dmwm/CRABServer/wiki/INSTANCES:--versions,-REST-hosts,-clusters,-DataBases

the part relevant here is:

* Do exactly like for CRABClient, but there is no default instance.
* Make things more clear by renaming config.TaskWorker.mode to config.TaskWorker.instance
* **THEREFORE** in TaskWOrker  the restHost/dbInstance mode is activate via setting
   * `config.TaskWorker.instance = 'other'`
   * in which case the configuration file must contain:
      * `config.TaskWorker.restHost = 'stefanovm.cern.ch` # or similar fqdn
      * `config.TaskWorker.dbInstance = one of [prod|preprod|dev] `

**Comment by belforte** [comment]
@ddaina can you comment on the plan indicated here ? Will that do for your ?

**Comment by belforte** [comment]
Need to check that recurring actions still work after the changes
- [ ] taperecall
- [ ] renewproxies

**Comment by belforte** [comment]
need to do something about the fact that TaskRecall uses things from config directly, instead of the derived `self.restHost` and `self.restURInoAPI`
Maybe a relic from when RecurringActions were independent scripts ?
Now they are actions like other and should have access to all that is in `self`.
Need to investigate and clean up.
- [ ] cleanup usage of restURInoAPI

**Comment by ddaina** [comment]
So am I right here that `config.TaskWorker.instance = 'other'` will allow us to make submissions like this: 

1. ```config.TaskWorker.restHost = 'cmsweb-test2.cern.ch' ```
```config.TaskWorker.dbInstance = 'preprod' ```

**Comment by belforte** [comment]
you are correct on everything. 
But I agree that
```
config.TaskWorker.instance = 'test'
```
is not very clear, so I have also added to the predefined instances:
```
'test2': {'restHost':'cmsweb-test2.cern.ch', 'dbInstance':'dev'},
```
and same for all `test*`. This is the kind of details where I find it difficult to converge, in lack
of pressing reasons to do one way  or another.

**Comment by ddaina** [comment]
Can you confirm that even though client can submit to different DB instances using the same restHost, we still going to have only one TW for a given resthost and we will be simply updating  dbInstance in the TW configuration file as needed?

Also, maybe a different topic, but going forward, which TW combinations (restHost and dbInstance) we should run on crab-dev-tw0(1|2) and crab-preprod-tw0(1|2) (especially taking into account flexibility of submitting to different DB)?

**Comment by belforte** [comment]
Not really.
Let's not mix what is possible with which configuration we use in a specific period.

Each TW will only process tasks from ONE DataBase instance.
But we could run multiple such TW's at same time for load share or high availability if we wanted.
And each TW can use whatever REST host they like as long as it provides access to the proper DB.

Of course with so much flexibility we need to specify some simple setup that
we put in place in operations. I am pretty much in favour of clean, clear, static
configurations for ops. But if we need to make some special test, or accomodate
a hot fix for a problem, I hope it can be done w/o hacking the code.
We should discuss actual configurations for the current machines elsewhere.

Let's keep in mind that this is all "for us". Users know nothing, and submit to `cmsweb.cern.ch`
cluster using DB Instance `prod`.

**Comment by belforte** [comment]
explicitly, from  https://github.com/belforte/CRABServer/blob/5d496c0cc9ca9e2676e20b3e946469bf75d60ce9/src/python/ServerUtilities.py#L32-L44
```python
SERVICE_INSTANCES = {'prod': {'restHost':'cmsweb.cern.ch', 'dbInstance':'prod'},
                     'preprod': {'restHost':'cmsweb-testbed.cern.ch', 'dbInstance':'preprod'},
                     'k8s': {'restHost':'cmsweb-k8s-testbed.cern.ch', 'dbInstance':'preprod'},
                     'dev': {'restHost':'cmsweb-test2.cern.ch', 'dbInstance':'dev'},
                     'test': {'restHost':'cmsweb-test.cern.ch', 'dbInstance':'dev'},
                     'test1': {'restHost':'cmsweb-test1.cern.ch', 'dbInstance':'dev'},
                     'test2': {'restHost':'cmsweb-test2.cern.ch', 'dbInstance':'dev'},
                     'test3': {'restHost':'cmsweb-test3.cern.ch', 'dbInstance':'dev'},
                     'test4': {'restHost':'cmsweb-test4.cern.ch', 'dbInstance':'dev'},
                     'test5': {'restHost':'cmsweb-test5.cern.ch', 'dbInstance':'dev'},
                     'test6': {'restHost':'cmsweb-test6.cern.ch', 'dbInstance':'dev'},
                     'other': {'restHost':None, 'dbInstance':None},
                     }
```
this definition will be also imported in CRABClient so the instances are defined in one place only.
And we should decide if to keep the generic (and indeed confusing) instances "dev" and "test".

**Comment by belforte** [comment]
last actions:

- [ ] remove 'test' and 'dev' from service instances list
- [ ] test recurring actions
