### ISSUE TITLE
improve TW stop.sh to deal with recurring action

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6054]
when recurrring action proxy renew is in progress it may take hours,
but it can be safely killed.
OTOH normal workers should be given a few min to complete, but after 5-10 min
they can also be killed,  possibly with a warning and something logged.

**Comment by ddaina** [comment]
as per what has been discussed yesterday during the CRAB meeting - @belforte look for a hack to identify if slave by any chance is running proxy renewal process.

**Comment by belforte** [comment]
I had looked at this, but could not find any way to tell RenewRemoteProxies action to stop.
Since it is  executed withing a normal worker, I do not see how to identify such worker either via e.g. a ps command, so that the stop.sh script can get rid of it.

**Comment by belforte** [comment]
One idea:
the slaves log is like (this is from `crab-preprod-tw02:.../logs/processes/proc.c3id_1.pid_1892.txt` )
```
2020-06-17 21:34:45,771:DEBUG:Worker:Process-1: Starting <function handleRecurring at 0x7fd2e4e257d0> on TaskWorker.Actions.Recurring.RenewRemoteProxies
2020-06-17 21:50:39,359:DEBUG:Worker:Process-1: ...work on TaskWorker.Actions.Recurring.RenewRemoteProxies completed in 953 seconds: None
```
So the slave could use those two moments, when its starts and compltes an action to maintain a file in `logs/processes` called something like `state.c3id_1.pid_1892` where it records the name of the action it is working on. In this way stop.sh can get a picture of what's happening and decide if to send SIGKILL to somebody. It may also help debugging and troubleshooting.
I think we coudl only update those file when handleRecurrint of handleTask are called, i.e. do not bother to track the various actions for dealing with each task, but only note down which task each slave is working on.

**Comment by belforte** [comment]
Actually for normal tasks the slave logs when it finished each action, but not when it starts, nor when it starts the task nor when the last action on the task is done. This could also be improved, so that if a slave gets stuck inside some action, we know which one. Almost any action prints intermediate messages, but a clean start/stop will help, e.g. if one day we push everything to logstash or similar.

**Comment by belforte** [comment]
@ddaina @dciangot I am waiting for some feedback on this. Thanks

**Comment by dciangot** [comment]
> Actually for normal tasks the slave logs when it finished each action, but not when it starts, nor when it starts the task nor when the last action on the task is done. This could also be improved, so that if a slave gets stuck inside some action, we know which one. Almost any action prints intermediate messages, but a clean start/stop will help, e.g. if one day we push everything to logstash or similar.

+1

**Comment by dciangot** [comment]
I might miss something here, but I don't see a reason to do complicate things on the bash script. What about waiting a bit for killing and then print out the PID of the process that still pending? Is this what you were thinking about?

**Comment by belforte** [comment]
that's a good idea, yes I'll do. The thing discussed above is how to make it easy to tell what that PID is doing so that operator (or script) may send an educated SIGKILL.

**Comment by belforte** [comment]
will not be needed anymore once we have dealt with the task interrruped by TW stop. Recurring actions are sage to kill at any time.

**Comment by ddaina** [comment]
@belforte, for automatic TW stop/start, shall we change this line:

https://github.com/dmwm/CRABServer/blob/master/src/script/Deployment/TaskWorker/stop.sh#L4

to something like this:
`for SIG in 15 9 ; do kill -$SIG $TaskMasterPid || break ; sleep 5m ; done` ?

5m delay should be more than enough taking into account that SUBMIT, KILL, RESUBMIT on average takes (last 7 days average):
<img width="684" alt="paveikslas" src="https://user-images.githubusercontent.com/60326190/104959976-a10eb800-59d3-11eb-88ac-ac4aed102756.png">

So maybe we could even go for 2 minutes.

**Comment by belforte** [comment]
yes, but please have pity of those like me who are not such bash wizards
or anyhow have trouble keeping many things in mind at same time,
and try to make it more explicit even if it takes a few more lines. Thanks
in the spirit "done in next puppet run" which happens... every 2 hours ? 5 min is fine.
Maybe can ask grafana to compute percentiles and cut at 99% ? But distribution is likely to vary in time.
I am mildly annoyed that at times datadiscovery takes almost half an hour, but have no time to investigate.
The other lengthy action is dagmanSubmitter but I guess that is simply sleeping and trying various schedd's
so it will only gain by being paused for a few min.
anyhow it will be easy to change the sleeping time based on experience.

**Comment by ddaina** [comment]
my idea was to have 2 signals sent to `TaskMasterPid`: kill 15 and kill 9 in given order. After each signal, wait N minutes before sending next kill signal. But I think that provided oneliner will not do, because it will sleep regardless of the fact that pid was killed, so there will be a sleep delay in most of the cases even after successful kill operation 
 
 But now when I think more, why can't we use `docker stop` command to stop running container and processes inside? Need some reading to understand how this command works and to which PID signals are sent
  
 > Maybe can ask grafana to compute percentiles and cut at 99% ? But distribution is likely to vary in time.

I have added this graph for now: https://monit-grafana.cern.ch/d/XQzAns0Gz/crab-taskworker-internals?orgId=11&from=now-7d&to=now&refresh=5s&var-TWHost=crab-prod-tw01.cern.ch&var-Test=crab_logs&var-PublisherHost=crab-prod-tw02.cern.ch&viewPanel=52
Looking into last 7 days and doing a cut at 99%, we should set sleeping time to ~4min.
Looking into last 30 days and doing a cut at 99%, we should set sleeping time to ~3min.

**Comment by belforte** [comment]
thanks for looking up the percentiles distributions.
I suggest to start with a stop.sh script which issues kill to master like now, then checks every 30 sec until all processes are gone or 3 minutes are elapsed. After 3 min, sigkill everybody.
The 3min should be set as a variable so it is easy to change.
Then you can look into how to make docker stop execute this by trapping signals etc.
