### ISSUE TITLE
test new httplibs

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6058]
once this is merged
https://github.com/cms-sw/cmsdist/pull/5838
we need to build new rpms for crabserver, crabcache and crabtaskworker and check that they still work. No problem is expected so this can also be part of building new rpms for other reasons, but we need to make sure to test well before next deployment in production

**Comment by belforte** [comment]
new httplibs will be put in the build soon after HG2006 is out, to be tested in time for HG2007

**Comment by ddaina** [comment]
I saw that you submitted few tasks both to cmsweb-testbed and cmsweb-k8s-testbed and confirmed to Imran that everything is OK. I did submit few tasks too, things worked as usual, nothing unexpected happened.

**Comment by belforte** [comment]
sounds all good then. I propose to close and make a comment about this in the HG validation ticket.
