### ISSUE TITLE
Make Rucio removes files on temp area when transferred.

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#6064]
As per Nick suggestion:
"When a file is the only source replica Rucio knows not to delete it until transfer is done"

So if we create a rule with some a short liftetime for the files staged on the temporary area, we can make Rucio delete files when the transfer succeeded. Without worring of doing it manually as done now.

**Comment by belforte** [comment]
"limited lifetime" and "when transfer suceeded" are a contradiction.
maybe you mean:
when transfer succeed or permanenty fails or in any case after some proper time in case Rucio does not get to act on the file in any way (e.g. a site/RSE goes down for 10 days, jobs have since long re-run, and we want to cleanup temp disk on restart).
So.. yes.. rules can help, but  with usual care for all details.
Still Rucio should do "move" not "replica", i.e. delete file on temp after successful xfer. Space in temp areas is precious.

**Comment by dciangot** [comment]
Yeah, the point is that there is no move in rucio.. only replica...
The mechanism is more tricky than what you said above. Limited lifetime is meant in the sense that ,as soon as the rule for having a replica of that file on the final destination has been created, the rule on tmp file can expire without causing the file to disappear, since rucio will not touch it until the transfer requested by the definitive rule is satisfied. 

So the lifetime can be minutes.. but on the safe side you can put hours/1day whatever..

**Comment by belforte** [comment]
I see. Pretty nice. I was not aware of such multiple rules interplay, thanks.

I still do not see how we deal with transfers which can't be executed for a longish time, esp. if jobs are resubnmitted. Do we have again to worry about killing old pending xfer requests, failing in doing that, and have races and files disappear days after having put in final places ?

I wonder if we need to change policy/expectations/rules for users... :-(

**Comment by dciangot** [comment]
Well, me too.

But for multiple retries the only think that count is the replica at destination, so whoever between the previous job and the current manage to transfer data win.

I don't know if then stops the other transfer, that's interesting. We might have some decision to take here, but first we need to figure out most of the possible extreme case

**Comment by belforte** [comment]
++1

**Comment by dciangot** [comment]
Resuming this due to re-write ongoing in #6225
@belforte what should do we this then?

Is putting a rule with a short lifetime for data on /tmp enough? I don't remember the conclusions here :/

**Comment by belforte** [comment]
yes, that's enough.
I think in my first reply I was simply confused. Then we diverged into what to do with resubmissions.Which is a different thing.

Let's talk about resubmissions in ad hoc thread, if needed. The point is how to deal with timeout. Do we need to ?

**Comment by belforte** [comment]
adding this ref for the time we will start really commissioning Rucio in CRAB and review all this mess
https://github.com/dmwm/CMSRucio/issues/159#issuecomment-917190558

**Comment by dciangot** [comment]
closing in favor of #7423
