### ISSUE TITLE
get old TW logs out of the way

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6072]
currently the `logs` and `twlogs/processes` directories contain logs since last cleanup. Especially in `processes` this makes it hard to identify logs from running processes from logs from old ones. When TW start it should move old logs out of the way, either mv to a different directory or rename.
The `twlog.txt` is simply appended to at every restart and rotated daily, that not too bad, but not ideal either.

**Comment by belforte** [comment]
least intrusive solution is that when TW start it moves all files in logs/processes to
logs/processes/OldLogs-YYMMDD
see: https://indico.cern.ch/event/872596/note/

**Comment by ddaina** [comment]
Both preprod containers crashed after the container restart because of the:
```
[crab3@crab-preprod-tw01 TaskManager]$ cat nohup.out
/data/srv/TaskManager/v3.200612/slc7_amd64_gcc630/external/py2-cryptography/2.4.2-comp2/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py:163: CryptographyDeprecationWarning: OpenSSL version 1.0.1 is no longer supported by the OpenSSL project, please upgrade. A future version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning
Traceback (most recent call last):
  File "/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/v3.200612/lib/python2.7/site-packages/TaskWorker/MasterWorker.py", line 403, in <module>
    mw = MasterWorker(configuration, logWarning=options.logWarning, logDebug=options.logDebug, sequential=options.sequential, console=options.console)
  File "/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/v3.200612/lib/python2.7/site-packages/TaskWorker/MasterWorker.py", line 136, in __init__
    self.logger = setRootLogger(logWarning, logDebug, console, name)
  File "/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/v3.200612/lib/python2.7/site-packages/TaskWorker/MasterWorker.py", line 112, in setRootLogger
    createAndCleanLogDirectories(logsDir)
  File "/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/v3.200612/lib/python2.7/site-packages/TaskWorker/MasterWorker.py", line 93, in createAndCleanLogDirectories
    shutil.move(currentProcessesDir+ '/' + f, oldProcessesDir)
  File "/data/srv/TaskManager/v3.200612/slc7_amd64_gcc630/external/python/2.7.13-comp/lib/python2.7/shutil.py", line 306, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path './logs/processes/OldLogs-200613/proc.c3id_master.pid_7.txt' already exists
```

1. In` crab-preprod-tw01` new code moved all the logs from June 13 to `OldLogs-200613` and after the restart it tried again to move the same logs and failed since those logs already exists in the `OldLogs-200613 `directory. 
2. In `crab-preprod-tw02` new code tried to move `proc.c3id_1.pid_13.txt` from Jun 13 to `OldLogs-200613`, however this directory already has file called `proc.c3id_master.pid_13.txt` from Jun 11. 

Since I cannot start `v3.200612` in any preprod machine, to have something running in preprod, I've started `v3.200531` release in `crab-preprod-tw01`. 

In case you want to investigate `crab-preprod-tw01`, start again `v3.200612`. In case you want to investigate `crab-preprod-tw02`, just login to the container. **Note.** Container in `crab-preprod-tw02` is running, but TW inside - no.

**Comment by belforte** [comment]
I ovrlooked that proceess log file have the same name when container restarts, since they have same process id. I could add HH::MM::SS to the subidrectory name, but that may be simply verbose and annoying. SO..
- [ ] review and make sure of the diagnosis
- [ ] find a solution to the non-unique log file name problem

OTOH everthing should work when you start from a empty logs directory, which is fine
for preprod, and if only the TW processes, not the container, are restarted.

**Comment by belforte** [comment]
fails. see: https://cms-submit-infra.slack.com/archives/DSYUJEDM2/p1592219485001300
error on crab-preprod-tw01 is

```
  File `"/data/srv/TaskManager/current/slc7_amd64_gcc630/cms/crabtaskworker/v3.200615/lib/python2.7/site-packages/TaskWorker/MasterWorker.py",` line 98, in createAndCleanLogDirectories
    if files and latestLogDir:
UnboundLocalError: local variable 'latestLogDir' referenced before assignment
```

**Comment by belforte** [comment]
there's also another bug, the code would correcty pick the more recent Latest* directory since this loop needs a break:
https://github.com/dmwm/CRABServer/blob/35ee9d32327f6c356698f2966df1235e0d558bbb/src/python/TaskWorker/MasterWorker.py#L96-L97
