### ISSUE TITLE
cleanup DBSDataDiscovery

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6073]
the addition of Rucio was done too much in a hurry and this code now needs a good cleanup, besides what's in #6070.
At least:
- [x] avoid abusing exceptions. There should be a logical flow to follow and exception reserved for extraordinary events like a server failed. Current code is too hard to understand
- [x] the removal of tape locations should be done in one place only, after trying Rucio and/or PhEDEx
- [x] messages should be more in tune with what done elsewhere and aimed to a situation of use in production, not testing
- [x] secondary datasets does not need to be the same tier as input, so the logic for using Rucio for it is simply wrong now. IMHO this is a **BUG**
- [x] should add to the final part the needed config. param. to be able to test standalone also with Rucio
 
https://github.com/dmwm/CRABServer/blob/b0e79f8284fc16086bf2e0593087c94acb16b1c7/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L127-L297

**Comment by belforte** [comment]
@dciangot I am assuming that code refactoring and messages cleanup is on me, but can you please say if I am mistaken and what I think is a bug was instead done for a reason which I am missing ?
Also I would like your opinion on the fact that removal of nondisk locations is currently done in two places inside the "if rucio" if block and later inside the "if phedex" block. Oversight, or again a reason which I am failing to see ?

**Comment by belforte** [comment]
reference to the code "before Rucio" https://github.com/dmwm/CRABServer/blob/a4aa634d241a0a3f157f1199118ae983b8efb996/src/python/TaskWorker/Actions/DBSDataDiscovery.py

**Comment by belforte** [comment]
@dciangot did you intentionally add checks for secondary datasets (location found, blocks on disk), or was this added by accident. I am not saying that we should not check, but since we never did... the change shoudl be at least noted down and tested. And we should have a different message for the user.

**Comment by belforte** [comment]
all the secondary dataset handling is a bloody hack (and always was). THere should be a common method used to find disk locations which raises when it fails (possibly asking for tape recall) and the code should not be replicated.  All that manipulation of location maps simply distracts from the main logic flow and is totally incidental to  a simple "found/not-found"
I will fork this in a separate issue since I think it is less important. For the time being keep the secondary dataset lookup with minimal checking and make sure that the main use case is properly dealt with.

**Comment by dciangot** [comment]
> the addition of Rucio was done too much in a hurry and this code now needs a good cleanup, besides what's in #6070.

I'd say that the code needed a good cleanup even before, but can't disagree in the end.

> * [ ]  avoid abusing exceptions. There should be a logical flow to follow and exception reserved for extraordinary events like a server failed. Current code is too hard to understand

same as above, this is a general truth for most of the code, isn't it? :) For sure looks like a good point where to start to change this "feature".

> * [ ]  the removal of tape locations should be done in one place only, after trying Rucio and/or PhEDEx

I'm afraid that this cannot be handled without either moving the Phedex part out of DBS wrapper or putting the Rucio part in there. Also, I was quite sure at the time that the two removal would have never been triggered together, but I suppose I was wrong then? 

> * [ ]  messages should be more in tune with what done elsewhere and aimed to a situation of use in production, not testing
> * [ ]  secondary datasets does not need to be the same tier as input, so the logic for using Rucio for it is simply wrong now. IMHO this is a **BUG**

right, I can't see the overall picture here, to understand how much impact this can have at the end. Did you say that this gonna have a separate issue?

> * [ ]  should add to the final part the needed config. param. to be able to test standalone also with Rucio
> 

I'm not following here, can you explain a bit?

> https://github.com/dmwm/CRABServer/blob/b0e79f8284fc16086bf2e0593087c94acb16b1c7/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L127-L297

**Comment by belforte** [comment]
Thanks Diego. I agree that cleanup was needed even before and that a lot of CRAB code could use some refactoring.. to put it mildly.
Anyhow I looks like we agree. So I will make a PR with the changes I have done so far and you can use that to answer questions you had. So far I only tested in standalone mode for NANO and non-NANO. Did not try tape datasets nor secondary yet. Just lack of time, I will and update the PR if/as needed.
Feel free to comment more in here or in the PR.

**Comment by belforte** [comment]
the PR is: https://github.com/dmwm/CRABServer/pull/6074

**Comment by belforte** [comment]
Also OK for TAPE data. 
Now I need to address:

secondary datasets does not need to be the same tier as input, so the logic for using Rucio for it is simply wrong now. IMHO this is a BUG

anyhow. Better make that a separate issue and test what I did so far. I did not change the logic about using Rucio or not for secondary dataset.

**Comment by belforte** [comment]
solved via #6074
