### ISSUE TITLE
cleanup GenerateMONIT.py

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6088]
I tried to remove pylint warnings from https://github.com/dmwm/CRABServer/blob/master/src/script/Monitor/GenerateMONIT.py
while working  on on the first PR's after Jenkins run again: 
but it is becoming too many changes for a PR which has nothing to do with this cose, better
to have an ad-hoc issuer.

After I fixed simple things, I ended up with
https://cmssdt.cern.ch/dmwm-jenkins/view/All/job/DMWM-CRABServer-PR-test/453/artifact/artifacts/PullRequestReport.html
but when I created a main() function to avoid global scope variables and hence errors like
```
 W0621, line 111 in CRAB3CreateJson.__init__: Redefining name 'resthost' from outer scope (line 300) 
```
as suggested by  https://stackoverflow.com/a/25072186/13696042
I found that some variables defined in old __main__ are used globally, in particular `logger`
This should be avoided. Small utility functions may not really need to log anything, leaving
logging to the `main()`. Otherwise `logger` has to be passed as argument.
Also there is no need to call logger(msg) before raising an exception(msg)
- [x] pass `logger` as argument to functions called in main as needed

other things:

- [x] currently exceptions are raised but not catched, so in case of exception the lock file is not removed.
- [x] `now` is defined in two places.

**Comment by belforte** [comment]
@ddaina do you want to work on this while I will be away (and there will be less flow of requests ?) Or I can do this before leaving. I like to get as little errors as possible from pylint

**Comment by ddaina** [comment]
I reviewed pylint report, I can work on this one. But I cannot fix all of things mentioned there, for instance where it complains about missing docstring -to have meaningful content, I think it should be added by you.
