### ISSUE TITLE
improve delegation and logging for FTS_Transfers

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6089]
there are indications of delegation problems with FTS
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5700/1/1/1/1.html
so we should enhance logging and periodically check status of delegated crendtial if possible.

THe current logging is anyhow buggy:
1. the proxy used is only printed in `task_process/daemon.out....` 
```
[2020-06-21 00:02] Running transfers.py
Proxy: %s /data/srv/glidecondor/condor_local/spool/5582/0/cluster49775582.proc0.subproc0/cfa0cb32f2043a8042e1290debf652b8fd62334e
[2020-06-21 00:02] transfers.py exited.
```
2. the FTS_Transfer log file  starts like
```
2020-06-20 23:32:35,357[   580]MainThread: No FTS job ID to monitor yet
2020-06-20 23:32:35,358[   580]MainThread: starting from line: 0
2020-06-20 23:32:35,487[   710]Thread-1: Processing transfers from: T2_US_Vanderbilt
2020-06-20 23:32:35,488[   710]Thread-1: Submitting 5 transfers to FTS server
2020-06-20 23:32:35,562[   784]Thread-1: Marking submitted 5 files
2020-06-20 23:32:35,681[   904]MainThread: Marked submitted ['6b182159c15132ba2c88908a4850cf0bef233536c7cc73e7459a5f09', 'a1e76766fb4787ec3a65585faa8e6d624e82c7ce5cd6a15bc9d9e599', 'f38b175d5902928ece1bd8732a33d7b25fefbc8b11c24faa7f54f1cc', 'a80943586521cb0ef812d44deb9e93bf690342d3efe897300db89d8d', 'e0a842b72a97c320751b0f48c03237bd0cd4a4ce2ab5b02dbe6c2dac'] files
```
with no sign of the messaged from these line
https://github.com/dmwm/CRABServer/blob/ce3b4f8321c5f8abccad9836923deac4d53760bf/scripts/task_process/FTS_Transfers.py#L564

**Comment by belforte** [comment]
I fear that the most likely explanation is that if FTS
has a credential for a user with still a short time to live,
it ignores a new delegation.
Maybe we shoudl be using this in CRAB FTS_Transfer
https://github.com/cern-fts/fts-rest/blob/fd883f54b14068884f394d9dbe8845b161ff4f00/src/fts3/rest/client/easy/delegate.py#L20
while we currently call it simply as
https://github.com/dmwm/CRABServer/blob/ce3b4f8321c5f8abccad9836923deac4d53760bf/scripts/task_process/FTS_Transfers.py#L564

**Comment by dciangot** [comment]
I miss the point here sorry. The default as I see in the fts code is that if lifetime is less then 2hrs then the proxy is redelegated. What am I missing?

**Comment by dciangot** [comment]
Ah ok, now from the edit message is clear, sorry for the noise

**Comment by belforte** [comment]
well.. I may surely be off track. But if credential has 2.5 to live and is not re-delegated it is possivle that transfers are attempted when it is expired. I also do not know how it works with multiple servers etc.
Atm this is only an hypothesis. Surely it is a rare event. If FTS_transfers.py runs again in the 2h before delegation expires, it would delegate again.
SO maybe some rare combination of events. 
Or maybe with multiple FTS servers they do not keep proper track...
clearly this is a rare event.

**Comment by juztas** [comment]
Maybe have a script running next to FTS_Transfers.py and check all users proxies (just make sure that is the case of 2h expiration)? Looks to be possible https://gitlab.cern.ch/fts/fts-rest/-/blob/master/src/fts3/rest/client/delegator.py#L227

**Comment by belforte** [comment]
@juztas we alredy have plenty of scripts which run at all times there, let's use one of them to do all needed actions !

**Comment by belforte** [comment]
I tried to contact FTS support via mail, which was routed to SNOW, but am not getting a real expert help so far...  https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2468402

**Comment by belforte** [comment]
Control of the remainging delefation time needs to tied to how long it may take for submitted transfer to happen. I am puzzled but this lines which apparently say that jobs can be queued for 10min max
https://github.com/dmwm/CRABServer/blob/ce3b4f8321c5f8abccad9836923deac4d53760bf/scripts/task_process/FTS_Transfers.py#L295-L297
vs. the current FTS documentation which indicates that the limit is 600 hours
```
max_time_in_queue Max time the job can be on the queue. Accepts an integer without suffix (interpreted as hours), or with a suffix s (seconds), m (minutes) or h (hours). e.g 60s
```
see: http://fts3-docs.web.cern.ch/fts3-docs/fts-rest/docs/easy/submit.html

Now.. 600 hours is such that we should never have transfers killed because thay stayed in queue too long, yet that is a common occurrence.
FTS documentation is very low quality, even in the same page there are inconsistencies... I am not sure we can trust it.
ANyhow FTS cose appears to confirm that it is 600 hours
https://github.com/cern-fts/fts-rest/blob/fd883f54b14068884f394d9dbe8845b161ff4f00/src/fts3rest/fts3rest/lib/JobBuilder.py#L471
https://github.com/cern-fts/fts-rest/blob/fd883f54b14068884f394d9dbe8845b161ff4f00/src/fts3rest/fts3rest/lib/JobBuilder.py#L265-L288

**Comment by belforte** [comment]
this is a bloody mess, but on the practical side I propose to change
https://github.com/dmwm/CRABServer/blob/ce3b4f8321c5f8abccad9836923deac4d53760bf/scripts/task_process/FTS_Transfers.py#L564
to 
```python
logging.debug("Delegating proxy to FTS: "+fts3.delegate(ftsContext, lifetime=timedelta(hours=48), delegate_when_lifetime_lt=timedelta(hours=24), force=False))
```

**Comment by belforte** [comment]
was closed by a missclick. sorry.

**Comment by belforte** [comment]
@dciangot I guess you are very busy, and all changes suggest in this issue so far are very small. So I can surely do them for you. But I'd like very much that you review thiese proposed changes first. Maybe I miss something importat. Maybe there is something else that must be done in addition or instad ?

**Comment by dciangot** [comment]
mmm, I think that 24h should be safe enough. So I don't see any big problem so far.

**Comment by belforte** [comment]
how to check delegated credential, from http://fts3-docs.web.cern.ch/fts3-docs/fts-rest/docs/sh-delegation.html

```
curl -E "${X509_USER_PROXY}" --cacert "${X509_USER_PROXY}"--capath /etc/grid-security/certificates https://fts3-devel.cern.ch:8446/delegation/2d19e65bb16481cf

{
  "termination_time": "2014-06-27T14:32:00"
}

```

(see https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2468402 )

> 
> If you want to interact with the FTS REST API, you can access https://<fts-instance>:8446/whoami to retrieve your `delegation_id`.
> Then, to check your delegation details, you can do a GET against https://<fts-instance>:8446/delegation/<delegation_id>
>

**Comment by belforte** [comment]
I tested all that from python shell on vocms059 and it all works as expected.

**Comment by belforte** [comment]
new code tested and comitted.
