### ISSUE TITLE
test and deploy new TaskWorker v3200816

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6119]
I have created a new version https://github.com/dmwm/CRABServer/releases/tag/v3.200816
which in particular is needed to be able to make new CRABClient and close
on the long saga of myproxy credential name https://github.com/dmwm/CRABClient/issues/4931

I have tested the various PR's in my private VM

@ddaina please build and test this and once you confirm that it is OK, deploy in production.
Please note that in the spec file you need to request WMCore tag `1.3.6.crab1`

**Comment by ddaina** [comment]
I deployed and tested TW `v3.200816 `with WMCore `1.3.6.crab1` tag on crab-preprod-tw02. I'd suggest to deploy to prod  tomorrow morning.

**Comment by belforte** [comment]
+1
