### ISSUE TITLE
need a way to cleanup files in /data/srv/Publisher_files

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6122]
see https://github.com/dmwm/CRABServer/issues/6100#issuecomment-651381393

**Comment by belforte** [comment]
I do not want to add recurring actions to Publisher like for TaskWorker where there is one to clear tmp area.
All in all Publisher_files has only one file per task, and most are small. See how it goes but a crontab which removes one month-old files should be enough.
Or we could be bold and delete those json files as soon as publication was done successfully. But I'd wait to have some experience with running in production first.

**Comment by belforte** [comment]
Will close once turned into an action for @sharmaprajesh  to create the proper crontab in putter, needs also proper mount point from @ddaina as I suspect that this directory is not mentioned in instruction twiki

**Comment by ddaina** [comment]
Hi,

@sharmaprajesh, we updated directory structure in all crab-(pre)prod machines, so now crontab should delete following directories (both in qa and prod branches):

1. /data/container/TaskWorker/logs
2. /data/container/Publisher*/logs
3. /data/container/Publisher*/PublisherFiles

**Comment by ddaina** [comment]
@sharmaprajesh,

IIUC, this is [code](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/master/code/manifests/profiles/crabtaskworker.pp#L487) for prod branch where list of directories is defined (do we have the same in qa branch?). Do you mind if I change it from:
```
"/data/container/logs/TaskWorker             -maxdepth 1 -type f"
"/data/container/logs/TaskWorker/processes   -maxdepth 1 -type f"
"/data/container/logs/TaskWorker/tasks       -maxdepth 2 -type f"
```
to
```
"/data/container/*/logs/             -maxdepth 1 -type f"
"/data/container/*/logs/processes   -maxdepth 1 -type f"
"/data/container/*/logs/tasks       -maxdepth 2 -type f"
"/data/container/Publisher*/PublisherFiles/             -maxdepth 1 -type f"
```
?

**Comment by ddaina** [comment]
I tested in dev machine that `*` syntax in directory names works and cleans files both from Publisher and TaskWorker directories. Tomorrow morning (11-25) I will update puppet and next time it runs, it will delete log files (including Publisher files, if there are any) older than 60 days.

**Comment by ddaina** [comment]
Done via https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/5c721d360a27641fb92890cd92cb815597a80099
