### ISSUE TITLE
improve bulk retrieve of filemetadata in TaskPublish

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6124]
see: https://github.com/dmwm/CRABServer/issues/6100#issuecomment-651490469

somehow have to limit to 10 files at a time atm to avoid CMSWEB errors with long LFNs
This makes things very slow.
Also I am curious how it can work in old ASO Publisher.

I changed chunk size from 50 to 10 and it works. But this is a very stupid strategy.
Should start from known the limit in the API and then figure out a decent chunk possibly
optimized for the task at hand. Or even something smarter. Surely it is quite slow now.

**Comment by belforte** [comment]
so the problem is in the list of LFN passed in input to the query.
@dciangot tried to ask CRAB REST only for the needed metadata passing a list of filenames
Instead old code in ASO always gets the full list of metadata for a given task even if this at times is thousands of files i.e. does no set anything for the `lfn` list
https://github.com/dmwm/AsyncStageout/blob/dff630eeeab327ff21fe84f65301763e1895e576/src/python/AsyncStageOut/PublisherWorker.py#L786-L818

the REST call always queries the full list from Oracle anyhow, the list of LFNs is apparently used only to fileter what to return
https://github.com/dmwm/CRABServer/blob/67f8ba0a27dcfbd072ec8ec31a613ef7137061b3/src/python/CRABInterface/DataFileMetadata.py#L25-L36

Old code in ASO does not pass a `howmany` value either, so this defaults to -1,  i.e. but also @dciangot sets `howmany` either. So in every case the full filemetadata for the task are retreived from Oracle to the rest and naively I woudl think that in the new code below simply the same call is repeaded many times (once for each chunk) getting only a small subset back to the client every time
https://github.com/dmwm/CRABServer/blob/67f8ba0a27dcfbd072ec8ec31a613ef7137061b3/src/python/Publisher/PublisherMaster.py#L253-L291

@dciangot what do you think ?

**Comment by belforte** [comment]
IN a way... I appreciate the original effort by Marco et al. to make it possible not to retrieve all possible filemetadata for a task with potentially many thousands of files, but w/o a way to flag in the filemetadata DB wether a file has been already published or not, even things like "only retrieve the most recent N" (IIUC what the `howmany` argument does, can never guarantee that only needed info is reported.
https://github.com/dmwm/CRABServer/blob/67f8ba0a27dcfbd072ec8ec31a613ef7137061b3/src/python/Databases/FileMetaDataDB/Oracle/FileMetaData/FileMetaData.py#L64-L68
I suspect that there is no alternative to the old way of getting full dump from the REST, update list on local disk, and select from there as needed.
If the API had a way to select after a certain time, we could use that. But a file count ... 

I will try to check with @mmascher in case I am missing something

**Comment by dciangot** [comment]
Hi @belforte , I think that the reconstruction is correct. The only thing I can say is that I don't know, I probably miss a piece of knowledge here, if the call is somehow cached at the REST level and/or at Oracle level.

**Comment by belforte** [comment]
Thanks @dciangot 
Indeed caching is a tricky business. Surely Oracle has its own (extensive) caching so repeating same query after a few seconds may not add load to the DB engine, but the amount of data transferred from Oracle server to CRABServer REST is always the same. Surely CRAB REST can't cache the output of the query, since there is no guaranteed that same query gives same result when repeated, only Oracle can know that. Then of course http server (apache) inside CRABServer rest has its own caching, but since every time we send a different URL (with a different set of LNF's) there's no way of reusing output the only thing that is gained is reduction of data volume sent from REST to Publisher. While the amount of data moved from Oracle to REST is always the same. So I do not see much of a gain for the REST. If this is significant in term e.g. of reducing load on CMSWEB FE, I can't say.  What we know for sure is that we can not send a long LFN list in the query since the GET has a lenght limit on the URL.
One could change to a POST, so the list from client could be very long. But I am not feeling like messing with CRAB REST APIs !

**Comment by belforte** [comment]
@dciangot anyhow I would be more than happy to get suggestion on how to proceed. I am tempted to go for the "old ASO way" of getting the full list of filemetadata for a given task every time and dump on the local file. We know that this works. I understand that at times this means that one needs to allocate a large memory structure client side, which maybe current "by chunk" way avoids, but... hopefully the slave which bloats this way does not live long anyhow. 

A more complex option would be to change the REST API (or create a new one) where the client passes a timestamp and gets all metadata inserted after that time, instead of passing a list of LFN. But this is surely more work, and one has to be very careful with what happens when processes are killed badly (reboot e.g.) in order to keep good track of last query time, avoid duplicate entries in utility json files etc...

**Comment by dciangot** [comment]
Well, I'd also avoid to change the REST API for sure. I don't know how we can be sure of the memory size on the first case, but probably as you said, we could be able to clean up that memory soon enough.

**Comment by belforte** [comment]
I did a bit of testing with one very simple situation, wirh LFN of the kind ` /store/user/belforte/GenericTTbar/crab_20200817_234039/200817_214044/0000/kk_28.root` sort of.. can't get any shorter.
A task with 1K jobs (very typical and on the small side if anything).

If I try chunks of 100 LFNs (meaning that the call to REST to get filemetadata needs to be done 10 times),
I get that the data field in the URI is 9035 bytes. And already I get the URI too long exception, consistently with the "rumor" that usual limit is 8K (but can be configured in the server) as per https://stackoverflow.com/a/54088675/13696042

With chunks of 10 files the data field is of course OK and one call to the REST completes in 0.2 seconds:
```
HTTP/1.1" 200 OK [data: 9270 in 11214 out 204747 us ]
```
But I would need 100 of those !

OTOH if I ask for the full thing, no list of LFN in the URI, completes in 2.5 seconds
```
HTTP/1.1" 200 OK [data: 7500 in 3905833 out 248508 us ]
```
I.e. much faster than 0.2*100 = 20 seconds

So... since I had already hit an error with chunks of 50 LFN, and chunks of 10 are annoyingly small... I will cut it here and go for always asking the full list and filtering by the needed list of LFN's in the Publisher code.

Hopefully most (!?!) users will move on to RUcio before we have to worry about optimizing the REST query itself by finding a proper way to ask Oracle only for what's needed.

**Comment by belforte** [comment]
tested OK on one 1000-job task
