### ISSUE TITLE
Testing HTCondor 8.9.7 python bindings

### ISSUE THREAD

**Issue by khurtado** [dmwm/CRABServer#6126]
Hello,

We are trying to move to the HTCondor 8.9.7 python bindings in WMAgent.

I have a PR in [cmsdist](https://github.com/cms-sw/cmsdist/pull/5967) for it, and my personal repo has wmagent, crab, etc compiled against it:

http://cmsrep.cern.ch/cgi-bin/repos/comp.khurtado/slc7_amd64_gcc630?C=M;O=D 

Could you please test and let me know if you see any issues in CRAB?

**Comment by belforte** [comment]
@ddaina what are the chances to quickly deploy this in an hoc TaskWorker container and test in e.g. crab-preprod-tw01) ? Is that something that now we can "do easily and quickly", or pretty much same effort as "ever". We only need to verify that we can still submit jobs to the schedd's.
Most of the HTCondor interaction happens in the Dagman management scripts which are part of TW code, but are executed in the schedd's with the HTCondor version installed there (by the way we alreayd have vocms059 as a schedd which runs 8.9.7 and it works).  In other words I do not expect any problem here, but it is always good to test.

**Comment by ddaina** [comment]
I deployed this in crab-preprod-tw01. My submissions worked fine.

**Comment by ddaina** [comment]
@khurtado, I am confirming that it works fine and closing this issue.
