### ISSUE TITLE
make a plan for smooth switching from ASO DBSPublisher to standalone Publisher

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6139]
as discussed in CRAB meeting today  https://indico.cern.ch/event/946600/

**Comment by dciangot** [comment]
```
Diego, Marco and Stefano talked and we now have
      a plan to switch one schedd at a time just for new tasks (i.e.any CRAB task will
      be published either all by old publisher or all by new publisher). This requires
      a bit of code changes: Stefano will open GIT issues. Diego points out that retries
      and resubmits are always very tricky and we need to make sure to check those
      carefully before claiming success.
```

**Comment by belforte** [comment]
here's the summary of that plan. Will open issues for specific points as proper and track them here.
It is a bit hacky since relies on overloading the meaning of the `asoworker` field in the transfersdb,  but that fiels is effectively useless now and we do not like to change DB schema or similar.

* The following will make new and old Publishers work on disjoint sets of files so that they can run at same time pointing to same Oracle DB instance

- [ ] do not change any REST query
- [ ] inroduce a new `asoworker` name, e.g. "schedd", while now it is hardcoded to `asoless`
- [ ] DBSPublisher on vocms0105 (aka old Publisher) will keep like know to select for publication all records in transferdb marked with 'asoless' or with no value for `asoworker` (i.e. files which have been stagedout directly from WN to user destination w/o using ASO not even in the current task-process-based implementation aka `asoless`   https://github.com/dmwm/CRABServer/blob/e03c2b5b6185255d8893350d2cb9bf9fcdc0d3ed/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py#L27-L33
 - [ ] modify new standalone publisher to only select records in transfersdb which have the new `asoworker` name https://github.com/dmwm/CRABServer/blob/e03c2b5b6185255d8893350d2cb9bf9fcdc0d3ed/src/script/Deployment/Publisher/PublisherConfig.py#L11

* The following will allow us to do limited testing of the new Publisher and slowly ramp up while we watch

- [ ] we will switch one schedd at a time via the usual method of a flag file `/etc/ENABLE_NEW_PUBLISHER `
- [ ] when a task will start on a schedd where that file exist, DAG bootstrap script will create a local file in the spool directory 'USE_NEW_PUBLISHER' marking that task. The PostJob, task_process, task_trasnfer etc., will check for this file to take appropriate decisions
 - [ ] modify PostJob so that if `USE_NEW_PUBLIS` is present it sets `asoworker = "schedd"` (or whatever name we like better) in all output file metadata records, including those that require no transfers (now the field is not set for those). Therefore tasks marked for `USE_NEW_PUBLISHER` will never have `asoworker=NULL` in Oracle
- [ ] modify relevant scripts in `crabserver/scripts/task_process` so that when transfer is done via FTS or Rucio, for tasks which `USE_NEW_PUBLISHER`, they do not overwrite asoworker field with 'asoless'
- [ ] introduce a new config.flag for TaskWorker so that we can force preprod tasks to always do this, no matter where thy run, so we can exercise things with preprod DB first
- [ ] find some way to allow to force publication through new method via a flag in submission, for initial testing before switching the first production schedd. (e.g. via `extraJDL`?)  But we can surely start with vocms059 which is reserved for us.

**Comment by belforte** [comment]
code ready and tested. Now moving to implementing this plan.
