### ISSUE TITLE
make log message more detailed: add work type

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABServer#6159]
Make following log message:
`2020-09-10 04:56:52,583:DEBUG:Worker:Process-6: ...work on TaskName completed in 2 seconds: None`
 https://github.com/dmwm/CRABServer/blob/9bebefd1349d7c61a477960be1cb100f9a467a3a/src/python/TaskWorker/Worker.py#L104
more detailed:

- [x] add information whether the work was submit, resubmit or kill;

- [x] figure out what last part saying `None`/ `-1` means and if necessary replace it with something else.

**Comment by belforte** [comment]
you can try to merge with this https://github.com/dmwm/CRABServer/pull/6166
then it will better give it a good shake in testbed in case my changes create an error in some situation

**Comment by ddaina** [comment]
this should be changed from

**Comment by ddaina** [comment]
this should be changed from 
https://github.com/dmwm/CRABServer/blob/e4b1bfbe4d32dd665fa0f58984a687ee85bc962c/src/python/TaskWorker/Actions/Recurring/BaseRecurringAction.py#L40 to 
`return Result(task=task['tm_taskname'], err="RecurringAction FAILED")`

**Comment by ddaina** [comment]
done via #6171
