### ISSUE TITLE
use *TapeRSE methods from WMCore Rucio Client

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6165]
when filtering our tape locations in DBSDataDiscovery, should use the new `isTapeRSE` and/or `dropTapeRSEs' methods to allow consistent future evolution, if any. ref. https://github.com/dmwm/WMCore/pull/9930/files

**Comment by amaltaro** [comment]
Stefano, in case you're evaluating RSE expressions too, I'm making this change to the wrapper API signature:
```
    def evaluateRSEExpression(self, rseExpr, useCache=True, returnTape=True):
```

so you could pass `returnTape=False`, and it would return a list of RSEs free of Tape endpoints.

**Comment by belforte** [comment]
I think I only need `dropTapeRSEs(listRSEs):`
