### ISSUE TITLE
Plan to replace Phedex lfn2pfn with Rucio

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#6201]
As requested by Stefano here (https://github.com/dmwm/WMCore/pull/9977), here the ticket for planning replacement

- The draft PR with all the places that needs a change is here:
https://github.com/dmwm/CRABServer/pull/6183

- The  only place to  implement a cache are transfer scripts

- other things?

**Comment by dciangot** [comment]
Other components involved:
- `src/python/TaskWorker/Actions/DagmanCreator.py`
- `src/python/CRABInterface/HTCondorDataWorkflow.py`
- `src/python/CRABInterface/DataWorkflow.py`

**Comment by belforte** [comment]
I d rather check if we can remove such calls. Makes no sense to me to do lfn lookup in RESTSent from. Stefano's phoneOn Oct 20, 2020 10:53, dciangot <notifications@github.com> wrote:
Other components involved:
src/python/TaskWorker/Actions/DagmanCreator.pysrc/python/CRABInterface/HTCondorDataWorkflow.pysrc/python/CRABInterface/DataWorkflow.py

**Comment by belforte** [comment]
no point in having another ticket. already have
https://github.com/dmwm/CRABServer/pull/6183
and
https://github.com/dmwm/CRABServer/issues/6102

**Comment by belforte** [comment]
moved to #6102
