### ISSUE TITLE
use new DBSReader with no PhEDEx

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6217]
see https://github.com/dmwm/WMCore/pull/9929
now it is possible to switch

**Comment by belforte** [comment]
this is now available in WMcore tag 1.3.6.crab3
as per https://github.com/dmwm/WMCore/pull/9929

will test building with that.
@ddaina can you remind me which WMCore tag you have used e.g. in building v3.201026 crabserver ?

**Comment by ddaina** [comment]
it was `1.3.6.crab1`

**Comment by belforte** [comment]
thanks. The differentce in 1.3.6.crab2 is something related to py3 compatibility which I cant're remember why I asked for but apparently we can do w/o. Anyhow no need to make an intermediate step on 1.3.6.crab2.  But we'll need to rebuild with 1.3.6.crab3 before PhEDEx goes offline. Hopefully after that we'll integrate the new py3 compatible WMCore and stop using a special branch. The sooner the better. Diverging branches bring in too much work.

**Comment by ddaina** [comment]
I should have been more specific when answering your question, so doing it now:
TW uses `1.3.6.crab2` tag, while crabserver and crabcache uses `1.3.6.crab1`. The reason why TW uses different tag was this: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5786/1/2/1.html

**Comment by belforte** [comment]
Thanks for reminding !!!! Everything makes sense now. Indeed there is no good reason why we should not be using that for crabserver and crabcache as well, let's remember to update next time we build (and of course test). Indeed for mind sanity it helps that we always use same wmcore tag everywhere, and if at times we need to diverge, realign asap.

**Comment by amaltaro** [comment]
FYI., if you want to have a quick check of their differences, this should do:
https://raw.githubusercontent.com/dmwm/WMCore/1.3.6_crab/CHANGES

**Comment by belforte** [comment]
rpms for TaskWorker  v3.201027 built with wmcore 1.3.6.crab3 are now in  `repo=comp.belforte`

**Comment by ddaina** [comment]
How about crabserver, was it built with `1.3.6.crab3` as well? Somehow I thought that this tag was meant to be used for crabserver and there were no changes for TW.

Also, should I deploy crabserver to test2 cluster?

**Comment by belforte** [comment]
Yes, I built crabserver and crabcache as well . I did a full build via
```
pkgtools/cmsBuild -c cmsdist --repository comp -a slc7_amd64_gcc630 --builders 8 -j 5 --work-dir w build comp
```
and created `HG2011c-comp`

About tags, it is a never ending discussion !
My understanding was to have  a single tag in the repository and if we want to build one service with a particular tag, different from the other service, we do via spec files. At least that was the "past".
Indeed spec files live in another repo and things are a bit unclear.
The best I can do atm is to make it clear in release notes what has been changed. Maybe we agreed on a different way for the future, and I forgot ? Never trust old people memory !

Yes, it will be useful to have the new crabserver and crabcache on test2, so we can all give it a try, differently from stefanovm2 which only I can submit to.

**Comment by ddaina** [comment]
I deployed crabserver and crabcache to test2 cluster. But I did not make any changes to currently running TW, i.e. neither I  updated currently running version nor did I touch `TaskWorkerConfig.py`.

**Comment by belforte** [comment]
yeah.. there's nothing to change in TW until I have completed the LFN2PFN stuff. There's no point in building with only partial PhEDEx removal. I have already tested that TW works with the new DBSReader.

**Comment by belforte** [comment]
Anyhow, this has been tested and code in mater is ready. Only a matter of deploying new tags. Can close
