### ISSUE TITLE
Move logstash configuration from private repo

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABServer#6234]
We need to find place where to store `logstash` configuration for parsing logs: https://github.com/ddaina/CMSKubernetes/blob/getFilebeat/docker/crabtaskworker/crabTWLogstash.conf
 One possibility is to store it in `CRABServer` repo. Another one - store it in [CMSMonitoring](https://github.com/dmwm/CMSMonitoring/tree/master/doc/logstash) repo. My suggestion would be to keep it in our repo while we are using `logstash` instance on our own k8s cluster. This way we will have more freedom to update it if needed. Once we are sure that it runs fine and doesn't break anything and we decide to move to the logstash instance on `vocms055` - where CMSMonitoring teams runs it - then possibly we move configuration file to CMSMonitoring repo as well (first of all agree with Valentin/Ceyhun). 

@belforte, what are your thoughts?

**Comment by belforte** [comment]
Yes.
And given the tight coupling with log format I think it will be better to keep it in CRAB repo forever, if possible,
avoid the need to change two repositories if we change one message.

If anything, it is a place where we may need to setup unit tests, there is a high danger of disrupting log parsing w/o noticing
and waiting for something odd to show up in grafana may not be good enough. Now we willl pay attention, but in two years....

**Comment by ddaina** [comment]
Would it be ok if I put it next to `GenerateMONIT.py` script in https://github.com/dmwm/CRABServer/tree/master/src/script/Monitor?

**Comment by belforte** [comment]
sounds perfect, thanks.

**Comment by ddaina** [comment]
thanks. Regarding:

>  there is a high danger of disrupting log parsing w/o noticing and waiting for something odd to show up in grafana may not be good enough

maybe we could simply start by adding a comment to the code saying that this line is used for logs parsing? I used so far following 3 log lines to parse:

```
1. 2020-10-21 00:11:41,973:DEBUG:Worker,111:Process-6: KILL work on 201020_214355:mimacken_crab_2017_LFVAnalysis_SingleEle_F completed in 2 seconds: Status: OK
2. 2020-09-10 04:56:49,748:DEBUG:Worker,104:Process-6: Starting <function handleResubmit at 0x7f65ea4b5b90> on 200901_130305:wjang_crab_NanoAODv7_v0_QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
3. 2020-09-10 04:48:50,091:INFO:Handler,104:Finished <TaskWorker.Actions.MyProxyLogon.MyProxyLogon object at 0x7f65e821a610> on 200901_125412:wjang_crab_NanoAODv7_v0_QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 in 1 seconds
```
and IIUC logging for those 3 lines respectively happens in the following places:
https://github.com/dmwm/CRABServer/blob/7a043eb6907e050eae79585feb6f0a93250b6d37/src/python/TaskWorker/Worker.py#L111
https://github.com/dmwm/CRABServer/blob/7a043eb6907e050eae79585feb6f0a93250b6d37/src/python/TaskWorker/Worker.py#L90
https://github.com/dmwm/CRABServer/blob/e4b1bfbe4d32dd665fa0f58984a687ee85bc962c/src/python/TaskWorker/Actions/Handler.py#L129

**Comment by belforte** [comment]
excellent idea ! WIll you make a PR ?

**Comment by belforte** [comment]
well.. adding comments is pretty safe, you can even commit directly to master branch e.g. editing files in GH

**Comment by ddaina** [comment]
I will put it in the same branch where I added logstash configuration and then create a PR with those two commits.
