### ISSUE TITLE
use operation arg in lfns2pfns via Rucio

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6242]
since at times the default (check all operations) may fail
should use proper argument and possibly use other operation as fallback if I need a resolution to try anyhow
see mail thread with @ericvaandering in
https://github.com/dmwm/CRABServer/issues/6238#issuecomment-722675773

This will future-proof against the possibility that at some point a site requires different protocols for read or wtite, so need to be sure to pick the correct one.

@amaltaro this requires changes in
https://github.com/dmwm/WMCore/blob/51e3e2f6975b92abbbd9bf7291cf7e8d8eabd2e3/src/python/WMCore/Services/Rucio/Rucio.py#L285
I will make a PR, but you can surely comment already

see Rucio API documentation:
https://rucio.readthedocs.io/en/latest/api/rse.html

**Comment by amaltaro** [comment]
Makes sense! If possible, start creating your changes against the master branch please (such that it goes through the CI system). Once we converge on the final implementation, we can backport that to 1.3.6_crab branch.

**Comment by belforte** [comment]
thanks Alan. Indeed it is always a mistake to wrap some external tool and not to expose all arguments. I should not have done this, esp. since I complained for years about DBS3Reader obfuscating/removing useful DBS API functionalities :-(

**Comment by amaltaro** [comment]
I have probably done the same with other Rucio APIs... we try to simplify the code, sometimes it works for 10 years without using those parameters, others we need it for the coming week. Anyhow, those API documentation aren't very great too, so it makes our life harder sometimes!

**Comment by belforte** [comment]
Places  I need to change:
- [ ] WMcore/Rucio since it is used in TW
- [ ] stageout check in TW
- [ ] FTS transfer script(s) which call directly Rucio Client (via some old CMSRucio.py wrapper I'd rather not talk about)
- [ ] checkwrite in CRABClient which calls directly Rucio python API

**Comment by belforte** [comment]
made PR's for WMCore for master branch     https://github.com/dmwm/WMCore/pull/10122    and  CRAB branch https://github.com/dmwm/WMCore/pull/10121

**Comment by belforte** [comment]
Made PR for TaskWorker part:  https://github.com/dmwm/CRABServer/pull/6279

**Comment by belforte** [comment]
code ready, will close when WMCore is updated and can properly test.
Note that atm the only sites where we file to get a `write` PFN and hence this is relevant, are:
```
T3_KR_UOS    T3_TW_NTU_HEP    T3_US_TAMU
```
