### ISSUE TITLE
check effect of new Rucio Exception from WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6249]
check implication for CRAB code of this:
https://github.com/dmwm/WMCore/pull/10023#discussion_r521324829

**Comment by todor-ivanov** [comment]
Hi Stefano @belforte, 
Just a heads up - We are about to merge this change during the weekend eventually. And it will be in effect from Monday. But for the moment we are not planning to patch the CRAB branch or anything, so I believe it will not affect you until your next deployment cycle at least. But anyway in case you find we are breaking the code here we will still have time to work it out.

**Comment by belforte** [comment]
CRAB does not use WMCore Rucio client anymore

**Comment by amaltaro** [comment]
That means we have the green light to remove the backwards phedex compatibility then.

**Comment by belforte** [comment]
yes Alan, I meant to find the issue where we have that question and comment in there,  but did not have the time to do it yet.
