### ISSUE TITLE
validate v3.201111

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6251]
test in preprod and then put in production asap.
things to check:
- [x] automatic splitting works
- [x] send a task where checkstageout will fail and check that TW log is indeed improved

code changes for automatic splitting is only in parts which are only executed in that case, so should be pretty safe as far as side effects. No need for extended validation

**Comment by ddaina** [comment]
worked fine. Do we move to prod today?

**Comment by belforte** [comment]
yes

**Comment by ddaina** [comment]
moved to prod: https://cms-logbook.cern.ch/elog/Analysis+Operations/3275
