### ISSUE TITLE
Publisher log to logstash to MONIT

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6276]
This is the place where to keep track of issues, decisions, discussions on what/how to send from Publisher log(s) to MONIT ElasticSearch via filebeat and logstash e.g. for monitoring via Grafana

**Comment by belforte** [comment]
initial step(s)
```
Regarding logs format - it easy to parse it as it is now. So no requests from my side to change something only for this purpose.

I will create a ticket to MONIT team (or ask Ceyhun) for a new  ’type’ to classify data sent (will call it ‘publisher’).  once they create it, I will redeploy logstash on k8s with the new configuration to send data to the new endpoint with Publisher logs. 

I would suggest to create a GH issue to track it. Also, to document decisions on the way.

Daina

> On 2020-11-27, at 15:04, Stefano Belforte <Stefano.Belforte@cern.ch> wrote:
>
> Hi Daina,
> about logstash for Publisher, I suggest to start by looking for this kind of lines
> 2020-11-27 14:25:16,191:INFO:PublisherMaster,545:Taskname 201127_011713:anstahll_crab_AODSkim_HIMinimumBias14_HIRun2018_04Apr2019_DiMuMassMin2_20201117 is OK. Published 37 files in 1 blocks.
>
> So you can track number of published files and blocks over time.
> Note also the "is OK" which flags successful runs of  TaksPublish.py
>
> while publication failures are currenty reported like:
> 2020-11-21 01:45:32,789:ERROR:PublisherMaster,550:Taskname 201118_182833:vcepaiti_crab_QCD_Pt-80to120_EMEnriched_TuneCUETP8M1_13TeV_pythia8-2016_NANOX_201117 : 1 blocks failed for a total of 11 files
>
> there also internal (script) failures like
> 2020-11-26 19:23:27,737:ERROR:PublisherMaster,554:Exception when calling TaskPublish!
> where I definetly need to add details.

```

**Comment by belforte** [comment]
for refence (from Daina):
Here is ticket when MONIT created ’type’ for TW logs: https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF1647500

**Comment by ddaina** [comment]
As of today Publisher logs are being send to MONIT (however, currently there is now way to filter between prod/preprod enviroments, will add that). 

Datasource called `monit-timber-cms-crab-publisher` was created in grafana to access this data. So we can start using it.

Following 3 log lines have been configured to be filtered by logstash:
```

1. 2020-11-27 14:25:16,191:INFO:PublisherMaster,545:Taskname 201127_011713:anstahll_crab_AODSkim_HIMinimumBias14_HIRun2018_04Apr2019_DiMuMassMin2_20201117 is OK. Published 37 files in 1 blocks.
2. 2020-11-21 01:45:32,789:ERROR:PublisherMaster,550:Taskname 201118_182833:vcepaiti_crab_QCD_Pt-80to120_EMEnriched_TuneCUETP8M1_13TeV_pythia8-2016_NANOX_201117 : 1 blocks failed for a total of 11 files
3. 2020-11-26 19:23:27,737:ERROR:PublisherMaster,554:Exception when calling TaskPublish!

```
I expect tomorrow to finalize logstash configuration and push changes to CRABServer repo.

**Comment by ddaina** [comment]
I started drafting dashboard for Publisher logs: https://monit-grafana.cern.ch/d/ufSLA10Mk/ddirmait_publisher?orgId=11&from=now-24h&to=now 
Well, now it is only one graph, we don't have any log entries with Publication failures or Exceptions when calling TaskPublish.

**Comment by belforte** [comment]
what is count of publications ? # of publication tasks which ran ?
what about #blocks ?
Now that I think about it, it will be nice to have some block size statistics, but I suspect now the log
does not have #files in each block when publishing more than one block.
Let's make a not to add it at some point. maybe better to collect a few changes to log formats
before doing one at a time

**Comment by ddaina** [comment]
> what is count of publications ? # of publication tasks which ran ?

yes. Does this number makes sense to look at?

> what about #blocks ?

I did not add it initially because I was not sure about the meaning of this number.

**Comment by belforte** [comment]
yes, they all can be usefl, I will explain blocks another time

**Comment by ddaina** [comment]
@belforte , one question, if we start multiple Publishers (Publisher_rucio, Publisher_assoles, Publisher_scheddy etc), then IIUC logging messages still will be the same. So, do we want to be able to filter between different publishers in the dashboard?

**Comment by belforte** [comment]
possibley all done here. @ddaina please review and put a final comment before closing, with pointers to PR if relevant

**Comment by novicecpp** [comment]
Closing this issue. Superseded by https://github.com/dmwm/CRABServer/issues/7115

**Comment by belforte** [comment]
thanks @novicecpp for the cleanup !
