### ISSUE TITLE
Allow ActivitiesToRunEverywhere to run at T1's even if jobType.pluginName is PrivateMC

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6280]
looks like a bug was introduced at some point,
e.g. this config
```
from CRABClient.UserUtilities import config

config = config()

config.General.requestName = 'Andrea_Test'
config.General.transferOutputs = False

config.JobType.pluginName = 'PrivateMC'
config.JobType.scriptExe = 'bmk_script_HC2.sh'
config.JobType.psetName = 'PSet.py'
config.JobType.inputFiles=['FJR.xml']
#config.JobType.outputFiles = ['mytest.log']

config.Data.totalUnits = 1
config.Data.splitting = 'EventBased'
config.Data.unitsPerJob = 1
config.Data.publication = False

config.Site.storageSite = 'T2_CH_CERN'
config.Site.whitelist = ['T1_DE_KIT', 'T1_ES_PIC', 'T1_IT_CNAF']
```
produces this error
```
Failure message from server:    The CRAB server backend refuses to send jobs to the Grid scheduler. No locations found for dataset 'None'. (or at least for the part of the dataset that passed the lumi-mask and/or run-range selection).
                                 Found 1 (out of 1) blocks present only at blacklisted sites. Global CRAB3 blacklist is set([u'T3_US_UCR', u'T3_US_CMU', u'T2_AT_Vienna', u'T3_KR_KISTI', u'T3_US_Kansas', u'T3_RU_FIAN', u'T3_US_MIT', u'T3_US_Brown', u'T3_US_UCD', u'T3_US_PSC', u'T3_US_NERSC', u'T3_US_NotreDame', u'T2_RU_SINP', u'T1_US_FNAL', u'T2_IT_Rome', u'T3_US_SDSC', u'T3_IN_PUHEP', u'T3_US_OSG', u'T3_FR_IPNL', u'T2_IN_TIFR', u'T2_CH_CERN_HLT', u'T3_US_FNALLPC', u'T3_CH_CERNBOX', u'T3_CH_CERN_HelixNebula', u'T3_US_Princeton_ICSE', u'T3_IN_TIFRCloud', u'T3_CH_CERN_OpenData', u'T0_CH_CERN', u'T3_GR_IASA', u'T3_CN_PKU', u'T3_US_Rutgers', u'T0_CH_CSCS_HPC', u'T3_IR_IPM', u'T3_US_JHU', u'T3_BY_NCPHEP', u'T3_US_TACC', u'T3_KR_UOS', u'T3_CH_PSI', u'T3_US_UMiss', u'T3_IT_MIB']).
                                 User whitelist is set([u'T1_DE_KIT', u'T1_IT_CNAF', u'T1_ES_PIC']).
```

**Comment by belforte** [comment]
I can't reproduce the problem. Have asked the person who reported this for more details.

**Comment by belforte** [comment]
Problem reproduced.Investigating.
The error comes from DagmanCreator, and it may be a case of "wrong message", subdag creation fails for other reasons but the error is handled by the same code which handles "no site left after black list"

**Comment by belforte** [comment]
The problem is due to this
```
config.Site.whitelist = ['T1_DE_KIT', 'T1_ES_PIC', 'T1_IT_CNAF']
```
somehow when submitting `PrivateMC` a default site list is created "early" which contains all T2's and T3's but no T1's.
Then in DagmanCreator this is ANDed with the user whitelist, resulting in the empty set.

Seem to me that this combination was overlooked in the original implementation.
Since most users who submit PrivateMC try to target as many sites as possible, we decided early on
to "push them toward T3's and T2's" and avoid filling the scarce analysis resources at T1's.
I still believe that it was a wise decision. But we did not protect for the possibility that a "PrivateMC" kind of task may want to run at a T1.
It is one of those situations where it is clear that we need to allow this for HC and other special tests, but indeed opening to all users for all their applications may be bad.
In a way, it is a matter of picking the least evil.

**Comment by belforte** [comment]
the initial site list for `PrivateMC` is set here
https://github.com/dmwm/CRABServer/blob/eba483325e4fba333dc96f7c7b449b327d045172/src/python/TaskWorker/Actions/MakeFakeFileSet.py#L23-L34

**Comment by belforte** [comment]
My preference is to allow only `activities which can run anywhere` to bypass that and force such jobs to run at T1's
https://github.com/dmwm/CRABServer/blob/eba483325e4fba333dc96f7c7b449b327d045172/src/script/Deployment/TaskWorker/TaskWorkerConfig.py#L88
@andrea.sciaba@cern.ch

**Comment by sciaba** [comment]
I don't mind allowing only ActivitiesToRunEverywhere to bypass that.
I assume you meant that they *can* be forced to run at T1's, but can be forced to run anywhere else, too. Basically they can be made to run anywhere.

**Comment by belforte** [comment]
Yes. I thin that the easiest is to change these
https://github.com/dmwm/CRABServer/blob/eba483325e4fba333dc96f7c7b449b327d045172/src/python/TaskWorker/Actions/DagmanCreator.py#L918-L919
(or better the larger block containing those ) to simply set the list of availablesites the same as the input white list for those activities.

**Comment by belforte** [comment]
fix tested on my VM
