### ISSUE TITLE
replace fts3.cern.ch with fts3-cms.cern.ch

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6284]
see
https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC2641735
and
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5887/3/1/1.html

**Comment by belforte** [comment]
@dciangot can you take care ? So I keep looking at HC problem.

**Comment by dciangot** [comment]
Yeah, I'm on it

**Comment by dciangot** [comment]
open draft PR #6288

**Comment by belforte** [comment]
solved via #6288
