### ISSUE TITLE
move to Cx_Oracle 19 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6301]
we currently use oracle 11.2.0.4.0__10.2.0.4.0
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/oracle.spec

But am wondering if we need to move to oracle 19.
Reading the comments at the beginning of that spec file is quite scary in terms of "touching it".

The trigger for the worry is that Kate told us that devdb11 will be turned off in January
and moved my private DB from that to devdb19 where I have discovered that the
current binary is not good enough.

@amaltaro do you know anything about this oracle version thing ?
(Of course this is not urgent, and I plan to talk with Kate in January, but do not want to forget about it)

I discovered that for sqlplus access on lxplus one needs
```
setoraenv -s 19090
```
instead of the current
```
setoraenv -s prod
```
otherwise connection fails with
```
belforte@lxplus718/~> export ORACLE_CERN=/afs/cern.ch/project/oracle
belforte@lxplus718/~> . $ORACLE_CERN/script/profile_oracle.sh
belforte@lxplus718/~> setoraenv -s prod
belforte@lxplus718/~> sqlplus crab3_belforte/***mypasswordher**@devdb19

SQL*Plus: Release 11.2.0.3.0 Production on Mon Dec 21 12:00:22 2020

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

ERROR:
ORA-12650: No common encryption or data integrity algorithm


Enter user-name: 

```
instead of the usual

```
belforte@lxplus718/~> sqlplus crab3_belforte/**password**@devdb11

SQL*Plus: Release 11.2.0.3.0 Production on Mon Dec 21 12:01:43 2020

Copyright (c) 1982, 2011, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Real Application Clusters, OLAP, Data Mining
and Real Application Testing options

SP2-0310: unable to open file "?/sqlplus/admin/glogin.sql"
SQL> 

```
and when I tried to run CRABServer on my private VM pointing to devdb19, not so surprisingly, I get this:
```
[21/Dec/2020:11:56:08]  RESTSQL:odktKNBqXZUh instantiating a new connection
[21/Dec/2020:11:56:08]  DATABASE THREAD CONNECT ERROR crab3_belforte@devdb19 CRABInterface.RESTBaseAPI.RESTBaseAPI cx_Oracle.DatabaseError dbbb43967815e3d12a857b3ba44045a8 (ORA-12650: No common encryption or data integrity algorithm)
[21/Dec/2020:11:56:08]    Traceback (most recent call last):
[21/Dec/2020:11:56:08]      File "/data/srv/HG2101c-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.201216-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1477, in _connect
[21/Dec/2020:11:56:08]        dbh = (self.idle and self.idle.pop()) or self._new(s, trace)
[21/Dec/2020:11:56:08]      File "/data/srv/HG2101c-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.201216-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1522, in _new
[21/Dec/2020:11:56:08]        ret.update({"connection": s["type"].connect(s["user"], s["password"], s["dsn"], threaded=True)})
[21/Dec/2020:11:56:08]    DatabaseError: ORA-12650: No common encryption or data integrity algorithm
```

**Comment by amaltaro** [comment]
I suspect there isn't yet a production-like cluster running Oracle 19. This migration is something that we are very interested in WMCore as well, so please do share any news you get on it. Or perhaps we could just arrange an "informal" chat with Kate in January, such that we can start planning for this.

**Comment by belforte** [comment]
I need to talk with Kate in January anyhow because we can't user cx_Oracle 5.2 yet https://github.com/dmwm/CRABServer/issues/6046

**Comment by belforte** [comment]
@sharmaprajesh FYI, please note this as well.

**Comment by belforte** [comment]
@amaltaro Kate said back in December that CMS *MUST* move to Oracle19 early this year.
Given how little manpower we have in CRAB and problems we already have, I hope this does not end in something to do in a hurry. Can you make sure that it goes in Kevin+Kati list ?

**Comment by belforte** [comment]
Raised priority and put On Hold until there's a common CMS COMP strategy

**Comment by amaltaro** [comment]
>@amaltaro Kate said back in December that CMS MUST move to Oracle19 early this year.

I haven't been following this very closed and I didn't know it was already in such pressure. Actually, I did not even know CERN/CMS already had a production-like Oracle19 setup.

Stefano, if you have enough material from your discussion with Kate, would you mind forwarding it to me? Otherwise, I think we could plan for a meeting in the next week just to clarify the future of oracle versions/support within CERN and how we should plan for it.

**Comment by belforte** [comment]
**UPDATE**

* we have to move to Oracle19 by June
* we need a new Oracle19 library in comp_* rpms (Alan is taking care)
* we can stay with cx_oracle 7.3 and python2 [1]
* we can start testing on the prod clone which Kati prepared, in our old fashioned wayt to connect the new connection string is speficied as indicated by Kate [2]
* an Oracle19 based instance for preprod/dev is about to come, Kate will notify us

[1] from Kate

cx_oracle 7.2/7.3 is ok for Oracle 19 client so no need to move to python3 and cx_oracle 8 before you're ready
You will need to upgrade Oracl Client libraries but I guess this is something Alan and Imran will discuss and do.

I've upgraded the copy of database storing all CRAB/WMcore so you can test what you need:

Connection string to the copy:

cmsrn_clone=(
        DESCRIPTION=
        (ADDRESS= (PROTOCOL=TCP) (HOST=cms-nrac-scan.cern.ch) (PORT=10121) )
        (LOAD_BALANCE=on)
        (CONNECT_DATA=
                (SERVER=DEDICATED)
                (SERVICE_NAME=CMSRN_CLONE.cern.ch)
        )
)

[2] from Kate
access on sqlplus:
 cms_analysis_reqmgr_r@cmsrn_clone
 cms_analysis_reqmgr_w@cmsrn_clone

And for Lassi's REST you need to take the prod one (as it is a copy from PROD) and replace 
'dsn': 'cmsr'  with  'dsn': 'cmsrn_clone'

**Comment by belforte** [comment]
We tested CRABServer on the V19 clone of production: cmsrn_clone and everything worked.
So the transition will be fully transparent.
But we will need to move to new Oracle Client v12 or v19 once Alan has a build for it since later this year Oracle will be switched to encryption which is not supported in Client v11.

**Comment by belforte** [comment]
We are now running Oracle19 in all DB instances.
So this is really about migrating to Cx_oracle 19 in py3 context.
Renaming and assigning to Dario.

**Comment by belforte** [comment]
references:
https://github.com/dmwm/WMCore/issues/10414
https://github.com/dmwm/WMCore/issues/10415

**Comment by amaltaro** [comment]
FYI.: Erik tested the new oracle client (py3-cx-oracle that now depends on oracle19 instead of oracle.spec) and apparently there are only 9 new failures. I believe further feedback will be provided today in:
https://github.com/dmwm/WMCore/issues/10416

but bottom line is, it seems to be "pretty" compatible with client v11.

**Comment by belforte** [comment]
We are running with python3 and Oracle-19 in preprod instance now. Closing
