### ISSUE TITLE
DBS migration failed

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6306]
I have casually found a case of failed migrations (first time in years)

from Publisher log for task 201221_173351:mseidel_crab_runMassWeights_WplusJToMuNu_APVpreVFP_batch0

```
2020-12-22 23:32:09,497:INFO: 7 block migration requests successfully submitted.
2020-12-22 23:32:09,497:INFO: List of migration requests ids: [2986033, 2986201, 2985971, 2986287, 2985905, 2986122, 2985931]
2020-12-22 23:32:09,497:INFO: Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.Will monitor their status for up to 30 seconds.
2020-12-22 23:32:09,497:INFO: 7 block migrations in progress. Will check migrations status in 30 seconds.
2020-12-22 23:32:39,584:INFO: Migration id 2986033 terminally failed.
2020-12-22 23:32:39,820:INFO: Full status for migration id 2986033:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608600476, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#febf79a8-0075-402a-a665-a46fdc1341b9', 'migration_request_id': 2986033, 'last_modification_date': 1608600902}]
2020-12-22 23:32:39,842:INFO: Migration id 2986201 terminally failed.
2020-12-22 23:32:39,842:INFO: Full status for migration id 2986201:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608605900, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#6d54a904-322e-4d36-af78-359ebba93f6e', 'migration_request_id': 2986201, 'last_modification_date': 1608606338}]
2020-12-22 23:32:39,863:INFO: Migration id 2985971 terminally failed.
2020-12-22 23:32:39,863:INFO: Full status for migration id 2985971:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608597618, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#16661a8e-278b-407b-be7c-11e6944a9202', 'migration_request_id': 2985971, 'last_modification_date': 1608598051}]
2020-12-22 23:32:39,881:INFO: Migration id 2986287 terminally failed.
2020-12-22 23:32:39,881:INFO: Full status for migration id 2986287:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608609508, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#1124e5de-78bb-4926-be95-f148784154de', 'migration_request_id': 2986287, 'last_modification_date': 1608609938}]
2020-12-22 23:32:39,900:INFO: Migration id 2985905 terminally failed.
2020-12-22 23:32:39,900:INFO: Full status for migration id 2985905:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608595072, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#fa29118c-ad15-42f0-b6d4-929a34028569', 'migration_request_id': 2985905, 'last_modification_date': 1608595505}]
2020-12-22 23:32:39,922:INFO: Migration id 2986122 terminally failed.
2020-12-22 23:32:39,922:INFO: Full status for migration id 2986122:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608602812, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#4c4e8f72-368a-490e-a65f-9784a6f60414', 'migration_request_id': 2986122, 'last_modification_date': 1608603245}]
2020-12-22 23:32:39,942:INFO: Migration id 2985931 terminally failed.
2020-12-22 23:32:39,942:INFO: Full status for migration id 2985931:
[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608596869, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#598c4a68-035b-4264-8107-6aa8df30ec1f', 'migration_request_id': 2985931, 'last_modification_date': 1608597297}]
```

Need to follow up with @yuyiguo and find out if we need to put back code which removes old failed migration and tries again as done in May 2019  https://github.com/dmwm/CRABServer/issues/6026

I did not look if there are other examples. Error reporting in new publisher is still primitive.

The same log file shows many successful migration before the problem.

I will look into attaching the full log to this issue

**Comment by belforte** [comment]
here is full log
[201221_173351:mseidel_crab_runMassWeights_WplusJToMuNu_APVpreVFP_batch0.log](https://github.com/dmwm/CRABServer/files/5732321/201221_173351.mseidel_crab_runMassWeights_WplusJToMuNu_APVpreVFP_batch0.log)

**Comment by belforte** [comment]
it is a bit worrying how many times migrations had to be retried a couple times before succeeding.

**Comment by belforte** [comment]
more tasks from same user suffering of same problem, see #6309 

```
these two tasks contribute 13K acquired files:

201221_173351:mseidel_crab_runMassWeights_WplusJToMuNu_APVpreVFP_batch0 : 6327
201221_173755:mseidel_crab_runMassWeights_WplusJToMuNu_APVpreVFP_batch1 : 6736

and this is also looking bad

201218_095531:mseidel_crab_runMassWeights_WplusJToTauNu : 1382

```

**Comment by yuyiguo** [comment]
@belforte 
These migrations ran k8s servers, right?

**Comment by belforte** [comment]
no we use cmsweb.cern.ch for migrations and publications. We onl;y use k8s instance to read input data.
e.g. the last one in the initial comment

[{'migration_status': 9, 'create_by': 'service@crab-prod-tw02.cern.ch', 'migration_url': 'https://cmsweb.cern.ch:8443/dbs/prod/global/DBSReader', 'last_modified_by': 'service@crab-prod-tw02.cern.ch', 'creation_date': 1608596869, 'retry_count': 3, 'migration_input': '/WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#598c4a68-035b-4264-8107-6aa8df30ec1f', 'migration_request_id': 2985931, 'last_modification_date': 1608597297}]

I can find out more details and will send to you.
I guess I can also try to delete one migration and send it again.. there will still be plenty to investigate !

**Comment by yuyiguo** [comment]
I am checking the logs. Give me some time to find why theu failed.

**Comment by belforte** [comment]
thanks so much. I am having dinner now :-)

**Comment by yuyiguo** [comment]
@belforte 

Thanks !
I could not find which migration servers were handling these requests. I saw in cmsweb log there are status checks on these requests. But I did not find in the log files  cmsweb or k8s these migration was handled.  it is bad that we have both cmsweb and k8s running on the same db.

I am continuing searching ...

**Comment by belforte** [comment]
too many migration servers ?

**Comment by yuyiguo** [comment]
@belforte 
I reset the status and retry count for these migrations: [2986033, 2986201, 2985971, 2986287, 2985905, 2986122, 2985931].
They all migrated successfully. I am continuing looking for the reason why the failed at the beginning.

Do you have more migration for me to reset the status?

**Comment by yuyiguo** [comment]
Yes, there are migration servers on cmsweb and k8s prod and they all connect to the the same DBS prod db.

**Comment by belforte** [comment]
i will grep logs for a full list of failed migration ids. Maybe we can make a pattern out of submission time.
So migration servers sort of lurk on the DB for migrations to do no matter where they run ?

**Comment by belforte** [comment]
@yuyiguo there's been a dramatic improvement in the number of "stuck" publication requests around 7pm UTC, and almost all task named mentioned above in this issue have been resolved. I guess it was the effect of your resetting of failed migrations !
![Screenshot from 2020-12-23 22-13-35](https://user-images.githubusercontent.com/1837785/103037707-1badfa00-4532-11eb-8083-e9ae94ea7a00.png)

**Comment by yuyiguo** [comment]
--------------------Wed Dec 23 19:02:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#833edc95-0f0e-4a7c-827b-d82cd250d09a for request id: 2986201
--------------------Wed Dec 23 19:02:54 2020 Inserting block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#6d54a904-322e-4d36-af78-359ebba93f6e for request id: 2986201
--------------------Wed Dec 23 19:02:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#6d54a904-322e-4d36-af78-359ebba93f6e for request id: 2986201


--------------------Wed Dec 23 19:01:52 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#a3f12877-7cc3-4b49-86ad-42a9bb5e6200 for request id: 2985971
--------------------Wed Dec 23 19:01:52 2020 Inserting block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#16661a8e-278b-407b-be7c-11e6944a9202 for request id: 2985971
--------------------Wed Dec 23 19:01:52 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#16661a8e-278b-407b-be7c-11e6944a9202 for request id: 2985971



--------------------Wed Dec 23 18:47:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#c219a6cc-9a23-4757-a63e-7efa825e93c1 for request id: 2986033
--------------------Wed Dec 23 18:47:55 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#febf79a8-0075-402a-a665-a46fdc1341b9 for request id: 2986033
**_--------------------Wed Dec 23 18:47:55 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#febf79a8-0075-402a-a665-a46fdc1341b9 for request id: 2986033_**


**_--------------------Wed Dec 23 19:01:53 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#1d1ab467-4e28-42bf-b5d5-d56037942613 for request id: 2986287
--------------------Wed Dec 23 19:01:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#698fcef0-90f2-41f5-af38-7997f8328752 for request id: 2986287
--------------------Wed Dec 23 19:01:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#1124e5de-78bb-4926-be95-f148784154de for request id: 2986287
--------------------Wed Dec 23 21:10:48 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECO-106X_mcRun2_asymptotic_v13-v2/AODSIM#3540e7fb-659c-4490-a049-ac5236855376 for request id: 2986811_**


**_-------------------Wed Dec 23 19:02:53 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#2cf65e79-6a1c-4af0-8250-ce82cda098bc for request id: 2986122
-------------------Wed Dec 23 19:02:53 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#2cf65e79-6a1c-4af0-8250-ce82cda098bc for request id: 2986122
--------------------Wed Dec 23 19:02:53 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#4a159143-b087-4af0-a633-7981e7396a2e for request id: 2986122
--------------------Wed Dec 23 19:02:53 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#1f87def2-ea61-4ad5-aaa8-bcdbdf76eafe for request id: 2986122
--------------------Wed Dec 23 19:02:54 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#4c4e8f72-368a-490e-a65f-9784a6f60414 for request id: 2986122_**

**_--------------------Wed Dec 23 19:01:51 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16RECOAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/AODSIM#21730f43-7c14-400e-bc99-9705b21e4817 for request id: 2985931
--------------------Wed Dec 23 19:01:52 2020 Done insert block: /WplusJetsToMuNu_TuneCP5_13TeV-powhegMiNNLO-pythia8-photos/RunIISummer20UL16MiniAODAPV-106X_mcRun2_asymptotic_preVFP_v8-v2/MINIAODSIM#598c4a68-035b-4264-8107-6aa8df30ec1f for request id: 2985931_**

**Comment by yuyiguo** [comment]
@belforte 
Above listed blocks were written in bold and italic were processed by k8s although the requests were sent to cmsweb.  We cannot run k8s ann cmsweb for migration server at the same time.  We need to stop the k8s migration server. Do you, know how to contact Imran during the holiday time at CERN?

I will write him an email CC you, Valentin and Kevin.

**Comment by belforte** [comment]
here's a list of all failed migration for tasks of user "mseidel".
CRAB Publisher logs are now divided per task, which makes it easier to debug single things, but harder to get full picture...
I marked with (*) those which you reset earlier
```
Migration id 2985905 terminally failed. (*)
Migration id 2985931 terminally failed. (*)
Migration id 2985971 terminally failed. (*)
Migration id 2985982 terminally failed. 
Migration id 2986033 terminally failed. (*)
Migration id 2986051 terminally failed.
Migration id 2986122 terminally failed. (*)
Migration id 2986201 terminally failed. (*)
Migration id 2986287 terminally failed. (*)
Migration id 2986734 terminally failed.
```

**Comment by belforte** [comment]
OK. I just saw your last message. All CRAB migration and publication requests are done using these URL's.
```
2020-12-21 20:59:12,379:INFO: DBS Source API URL: https://cmsweb.cern.ch/dbs/prod/global/DBSReader
2020-12-21 20:59:12,380:INFO: DBS Global API URL: https://cmsweb.cern.ch/dbs/prod/global/DBSReader
2020-12-21 20:59:12,516:INFO: DBS Destination API URL: https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter
2020-12-21 20:59:12,516:INFO: DBS Destination read API URL: https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader
2020-12-21 20:59:12,517:INFO: DBS Migration API URL: https://cmsweb.cern.ch/dbs/prod/phys03/DBSMigrate
```

**Comment by belforte** [comment]
I do not fully understand the problem of running migration servers on K8s and CMSWEB, do they try to act on same migration request independently and somehow in competition ? Anyhow... you surely know better then me ! Did you try to find Imran on MatterMost ? he may be working or at least checking messages. I do not have a phone number to call.

**Comment by belforte** [comment]
I checked ALL logs I have, there are no other failed migrations, only the 10 listed above, 7 of which you reset earlier.

**Comment by belforte** [comment]
So if the failures are due to the K8s servers and we can't stop them "now",
I have code already in CRAB Publisher since last year which identifies failed migrations and reset them.
It currently only acts on migrations submitted in May 1-21, 2019. Should I enable it again ?
https://github.com/dmwm/CRABServer/blob/d72bad60dc8774f2f57ed18bb60c32e5796533d4/src/python/Publisher/TaskPublish.py#L291-L301

**Comment by belforte** [comment]
and now I see that a few spaces have been accidentally inserted in line 295. Will fix.

**Comment by yuyiguo** [comment]
I will manually enable 2985982, 2986051, and 2986734.

**Comment by belforte** [comment]
thanks. It is bed time here. And I will work close to nothing until next week. Wish you a Merry Christmas :-)

**Comment by yuyiguo** [comment]
I see there were a lot of errors in migration server logs because both cmsweb and k8s server were trying to migrate the same book. I am not sure if  Irman is available during the holiday. If you could, please start the script to remove the dead migrations at least we can have the job running during the holidays. I am leaving for vacation tomorrow morning. I will check the ticket before I leave.

**Comment by yuyiguo** [comment]
Thanks ! Wish you and your family a Merry Christmas too.

**Comment by yuyiguo** [comment]
All migrations in your list are done.

**Comment by belforte** [comment]
thanks Yuyi. All in all I'll leave things as they are now and in case remove failed migrations individually at some point.
I would not feel comfortable with a new automatism starting while I can't look at it.
In the end, 10 migration failed, but 6915 succeeded in last month !!

**Comment by yuyiguo** [comment]
This is a good plan Stefano !

**Comment by belforte** [comment]
four new failed migrations 
```
2020-12-24 13:20:13,412:INFO: Migration id 2986942 terminally failed.
2020-12-24 13:20:13,434:INFO: Migration id 2986938 terminally failed.
2020-12-25 19:20:44,776:INFO: Migration id 2987172 terminally failed.
2020-12-25 20:51:12,148:INFO: Migration id 2987183 terminally failed.

```

**Comment by belforte** [comment]
I removed and resubmitted them. Thing worked after that.

**Comment by belforte** [comment]
another one: 2986993

**Comment by belforte** [comment]
No more failed migrations in last days.
I still do not want to make automatic retries, since failed migrations need to be investigated, not hidden out. On the other hand we need some quick way to check and act in case.
So I converged on the following plan:
 1. when https://github.com/dmwm/CRABServer/blob/master/src/python/Publisher/TaskPublish.py finds a terminally failed migration, it will log it  (append) to a central file:  `/data/srv/Publisher_files/FailedMigrations/TerminallyFailedLog.txt` analogous to how we log Blocks which fail to publish in `/data/srv/Publisher_files/FailedBlocks/`. N.B. `/data/srv/Publisher_Files' is `config.General.taskFilesDir` in `PublisherConfig.py`
 2. once every few days or when grafana shows stuff stuck in Acquired, operators will check the `TerminallyFailedLog.txt` via a script which select unique failed migrationId, check current status, and print list of currently failed ones to console and to `/data/srv/Publisher_files/FailedMigrations/TerminallyFailedIds.txt`.
3. that list can be handed to Yuyi and/or we can use another script to remove failed migrations and resend them. Even if we no resend them, the `TaskPublish.py` script will do it as/when needed.
4. the last two steps can possibly be automated as a daily crontab, if needed

So I have following three actions
- [ ] inside `TaskPublish.py` log terminally failed migrations
- [ ] write standalone script to parse `TerminallyFailedLog.txt` and print which MigrationIds are in terminally failed now
- [ ] write standalone sript which reads a list of migrationIds, removes them optionally submits and tracks them again.

**Comment by belforte** [comment]
above mentioned commits are now tagged in v3.201229 and deployed in crab-prod-tw02

**Comment by belforte** [comment]
Needed utility scripts are now in the repository.
Preferred action path is that operators identify terminally failed migrations and simply report them to DBS expert(s) for investigation. But if needed, they also have a script to remove one failed migration at a time.
