### ISSUE TITLE
make sure that TW starts new tasks in clean tmp directory

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6331]
when TW stops abrutplty it may leave tasks in QUEUED status.
Currently those are FAILED when TW restarts, to make sure we only process task names never seen before.
But if we make sure that TW temporary directory is clean, we may be able to set those QUEUED tasks as NEW
and process them,
This requires some check in HandleNewTask
@ddaina ping we when you start to work on this, I will help you find your way in the TaskManager actions.

Need to also to think what will happen if task is eventually submitted to same schedd as it was
attempted earlier, since task name is the same it will use same web directory, buy should be a new clusterId with a new spool directory. This should be OK since https://github.com/dmwm/CRABServer/pull/6320 but it is worth testing, whcih requires ad hoc effort since we can't simply wait for a rare incident.

**Comment by belforte** [comment]
This will be a step toward being able to stop/restart TW at any time transparently to users and ops, so that we can fully automathize confol of it.

**Comment by belforte** [comment]
it needs to be verified by e.g. running a single task and following step by step, but it look slike the creation of the `/data/srv/tmp_<taskName>` directory happens here
https://github.com/dmwm/CRABServer/blob/ae875d83950e4fcd739a59f9820f40488cd92772/src/python/TaskWorker/Actions/Handler.py#L49-L55

**Comment by belforte** [comment]
since `tempfile.mkdtemp` used 6 random char in the file name, it is hard that consecutive calls on same task uses same dir. 
Maybe we need to get back to @mmascher and ask why he wanted to put queued tasks in fail rather than new at TW startup.

**Comment by ddaina** [comment]
looking into `tempfile.mkdtemp` implementation, method will try to create temp directory N times before giving up. And each time different sequence of 6 letters will be tried. And IIUC, N is equal to 10000.

https://github.com/python/cpython/blob/2.7/Lib/tempfile.py#L335

So, it is almost close to impossible that temp directory name will be same as before. I can still add a check to see if temp directory with given prefix `prefix='_' + self._task['tm_taskname']` exists and delete if yes. But is it actually needed given 
`tempfile.mkdtemp` implementation (?) maybe it would be simply an overload.

**Comment by belforte** [comment]
I had same doubt ! But was not sure that `mkdtemp` tries to make a new, unique directory. That being the case there is indeed nothing to do.

**Comment by belforte** [comment]
I exchanged a couple mails with Marco Mascheroni, and basically confirmed our understanding.
