### ISSUE TITLE
Rucio Experts must clarify Rucio permissions for Tape Recall

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6332]
@ericvaandering @nsmith- @dciangot @klannon 

In order to progress with tape recall via Rucio in CRAB I need you guys
to clarify permission details and give me clear instructions.
I gave gone by trial-and-error so far, but besides being slow, I am a bit stuck

The plan we agreed on was simple:
-1 user requests to process some list of blocks which is on tape
-2 CRAB creates a container with those
-3 CRAB creates a rule asking for that container to be on disk for N days
-4 CRAB stores the rule Id as part the TASK info in its DB and holds the taskl
-5 a periodic procedure checks the rule progress ad releases the task when data is recalled

I have now tested code in the release for -1 to -5.
Here's an example from running in my private VM[1]
6 will be easy and is nor so urgent, in the meanwhile user submission is failed and user is asked to check rule progress
and try later a new submission (see [1])

Of course it is not great to print "issue this rucio command" from a tool which runs in 
CMSSW siince rucio is broken in CMSSW env.... pfff..... is anybody going to fix that ?
(No. I do not want to be the one who maintains the CMSRucio command [2] !!!!) 

Now permission comes in. In the above "CRAB does this and that" makes no sense,
since Rucio is very strict about who can do what, and documentation does not explain.

I can do all the above if I use my personal DN and connect to Rucio as user.belforte, **but...**
CRAB server has a Rucio Client with account crab_server which is used for data
discovery. So I can deal with step 1.

But I already have a problem at step 2:
I can't put this container in user.crab_server scope
```
Rucio exception creating container: Access to the requested resource denied.
Details: Account crab_server can not add data identifier to scope user.crab_server
```
and I can't put it in the scope of the user who submits the task either:
```
Rucio exception creating container: Access to the requested resource denied.
Details: Account crab_server can not add data identifier to scope user.belforte
```

Do you want CRAB to grap user credential and authenticate to Rucio that way ?
(of couse I do not like to have multiple clients, they are also awfully verbose
when initialized and mess my logs.. but I _really_ must...)

Then we need to deal with the rule. AS discussed yesterday, you want the rule
in yet another rucio account "crab_tape_recall", which I have no access to with
the DN's used for crab_server.
How should I do that ? 

I am sorry to keep bugging you guys like this, I guess this is what I was afraid of when
I asked for "clean, working instructions" on how to things early on. Instead I got pointed
to a script which I can't run and I need to change anyhow, and we go by hit and kick
and scream with 7h latency. And it is a pain. It does not help that Rucio documentation
is incomplete and incorrect (and poorly designed).

I appreciate that you are all very busy. But so am I. And am a bit fed up now
with discovering one stumbling block after another,

Thanks a lot
Stefano

[1]
```belforte@lxplus7110/LOCAL> crab submit 
Will use CRAB configuration file crabConfig.py
Importing CMSSW configuration demoanalyzer.py
Finished importing CMSSW configuration demoanalyzer.py
Sending the request to the server at stefanovm.cern.ch
Success: Your task has been delivered to the dev CRAB3 server.
Task name: 210109_134122:belforte_crab_20210109_144117
Project dir: ./crab_20210109_144117
Please use ' crab status -d ./crab_20210109_144117 ' to check how the submission process proceeds.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/LOCAL/crab_20210109_144117/crab.log
belforte@lxplus7110/LOCAL> crab status -d ./crab_20210109_144117
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/LOCAL/crab_20210109_144117
Task name:			210109_134122:belforte_crab_20210109_144117
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - stefanovm
Status on the CRAB server:	SUBMITFAILED
Task URL to use for HELP:	https://stefanovm.cern.ch/crabserver/ui/task/210109_134122%3Abelforte_crab_20210109_144117
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=210109_134122%3Abelforte_crab_20210109_144117&from=1610196082000&to=now
In case of issues with the dashboard, please provide feedback to hn-cms-computing-tools@cern.ch
Failure message from server:	Task could not be submitted because there is no DISK replica for dataset /MuonEG/Run2016F-v1/RAW
				N.B.: the input dataset is stored at T0_CH_CERN_Tape, T1_US_FNAL_Tape, but those are TAPE locations.
				A disk replica has been requested to Rucio (rule ID: 07aac867db6049829e1e7bab589a86c4 )
				you can check progress via either of the following two commands:
				 rucio rule-info 07aac867db6049829e1e7bab589a86c4
				 rucio list-rules user.belforte:/TapeRecall/210109_134122.belforte_crab_20210109_144117/USER
				Please monitor recall progress via Rucio or DAS and try again once data are on disk.
Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/LOCAL/crab_20210109_144117/crab.log
belforte@lxplus7110/LOCAL> 


```

[2]
```
belforte@lxplus7110/LOCAL> alias 'CMSRucio=eval `scram unsetenv -sh`;source /cvmfs/cms.cern.ch/rucio/setup.sh; export RUCIO_ACCOUNT=`whoami`; rucio'
belforte@lxplus7110/LOCAL> CMSRucio list-rules user.belforte:/TapeRecall/210109_134122.belforte_crab_20210109_144117/USER
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py2/current/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:47: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
rucio 1.23.11.post4
/cvmfs/cms.cern.ch/rucio/x86_64/slc7/py2/current/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:47: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography import x509
ID                                ACCOUNT    SCOPE:NAME                                                                  STATE[OK/REPL/STUCK]     RSE_EXPRESSION      COPIES  EXPIRES (UTC)        CREATED (UTC)
--------------------------------  ---------  --------------------------------------------------------------------------  -----------------------  ----------------  --------  -------------------  -------------------
07aac867db6049829e1e7bab589a86c4  belforte   user.belforte:/TapeRecall/210109_134122.belforte_crab_20210109_144117/USER  WAITING_APPROVAL[0/0/0]  T3_IT_Trieste            1  2021-01-23 13:41:37  2021-01-09 13:41:37
belforte@lxplus7110/LOCAL> 

```

**Comment by ericvaandering** [comment]
Hi,

Your desire to create another container rather than use the CMS Dataset/container makes sense, but it introduced a ripple. The CRAB accounts did not have corresponding containers since that wasn't anticipated. I added them for both crab_server and crab_tape_recall. So that error should no longer happen. However, you cannot mix and match them as you saw. crab_server cannot create containers in the user.crab_tape_recall scope or the user.belforte scope.

The reason crab_server cannot create a rule on behalf of crab_tape_recall is because it doesn't have an attribute of "admin" (the same attribute would have also allowed it to access scopes it does not own). crab_tape_recall DOES have that attribute which allows it to bypass quotas when making rules.

So, if possible, I would suggest you do all tape recall-ish things with the crab_tape_recall account (to which I have added all the requested identities/DNs). With that account, you can make new containers in user.crab_tape_recall or user.[USERNAME] and make rules for the crab_tape_recall user which bypass quota.

**Comment by belforte** [comment]
sounds good Eric, I'll give it a a try. I am no sure if it is better to create containers in user scope or crab-tape-recall scope, let's start with crab_tape_recall. I thought we wanted a quota on recall anyhow, but maybe I misunderstood something

**Comment by ericvaandering** [comment]
We don’t have a quota on them now, but that was my original suggestion. Scope is not tied strictly to account for this case, so you can create them in the user scope if you like and make the rule with crab_tape_recall account.

**Comment by belforte** [comment]
I got it, but since we should have the user name as part of the container dataname anyhow, it may help to have all crab taper recall in the same scope, just to make make it easy to find them.
I guess we need some experience before putting the final word.

**Comment by belforte** [comment]
so far, so good ! I am almost there (need to finalize some internal bookkeeping)
Am till 
![Screenshot from 2021-01-10 18-45-25](https://user-images.githubusercontent.com/1837785/104130991-19420180-5374-11eb-8ebc-840de1115d6e.png)
