### ISSUE TITLE
Port TapeRecallStatus.py recurring action to Rucio

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6334]
@ericvaandering @nsmith-
More semantic to settle on !

Ideally I'd like to have a function to which I pass a Rucio rule Id and which  returns an output like Dynamo, i.e.
 - completed vs rejected
 -  and if rejected, a reason for.
 It seems good to define such a protocol even if initially no requests will be rejected.

Can you get me started by indicating which is proper python call to use ? It is not immediate to find the equivalent of
`rucio rule-info` and then I am not sure how to read the output of that. Of course it would be ideal if you could write that function and provide it as Rucio interface.

We also need to agree on a time range after which CRAB stops waiting. Should be shorter then the time duration of the rule.
If rule expires tomorrow, there's not much point in releasing task today.
Or do you want CRAB to extend the rule to be 14 days after data is on disk ?

**Comment by belforte** [comment]
code to change is
https://github.com/dmwm/CRABServer/blob/a6b37e51376311cdb267a3cceab7b8be49358940/src/python/TaskWorker/Actions/Recurring/TapeRecallStatus.py#L107-L127

**Comment by belforte** [comment]
looks like I can use
```
get_replication_rule(rule_id, estimate_ttc=False)
Get a replication rule.
Parameters: 
rule_id – The id of the rule to be retrieved
estimate_ttc – bool, if rule_info should return ttc information
Raises:
RuleNotFound


```

this returns a dictionary like
```
{u'locks_ok_cnt': 0, u'did_type': u'CONTAINER', u'weight': None, u'purge_replicas': False, u'rse_expression': u'T3_IT_Trieste', u'updated_at': datetime.datetime(2021, 1, 11, 13, 27, 58), u'meta': None, u'activity': u'Analysis Input', u'child_rule_id': None, u'id': u'e7d17c2f768542318d414618f5d44f86', u'ignore_account_limit': True, u'locks_stuck_cnt': 0, u'locks_replicating_cnt': 7, u'notification': u'NO', u'copies': 1, u'comments': u'Staged from tape for belforte', u'split_container': False, u'priority': 3, u'state': u'REPLICATING', u'scope': u'user.belforte', u'subscription_id': None, u'stuck_at': None, u'ignore_availability': False, u'eol_at': None, u'expires_at': datetime.datetime(2021, 1, 12, 12, 58, 17), u'source_replica_expression': None, u'account': u'belforte', u'locked': False, u'name': u'/TapeRecall/210111_111111.belforte_crab_210111_111111/USER', u'created_at': datetime.datetime(2021, 1, 11, 12, 58, 17), u'error': None, u'grouping': u'ALL'}
```
and it looks to me that all I need to do is to wait for `state='OK'`

I did not see any effect turning `estimate_ttc=True` (shoud it be estimated Time To Completion ?) so I guess i will ignore it for the time being.

**Comment by ericvaandering** [comment]
I'm not sure if TTC is enabled, but of course, those estimates if they exist are going to be very inaccurate given the chaos of the system.

**Comment by belforte** [comment]
thanks Eric, the important bit is whether I need to be aware of any status other than 'OK'.
Currently I am going for this simple logic
```
for two weeks, check rule status every few hours
    if status is OK ==> release the task
it not OK in two weeks, set the task as failed
```
if users want to know more during that time, they will have to do rucio rule-info

**Comment by belforte** [comment]
for my use: how to change task status to test automatic recall
```
X5curl -k -v -X POST https://cmsweb-testbed/crabserver/preprod/task -d "subresource=addddmreqid&workflow=210111_125027%3Abelforte_crab_20210111_135021&ddmreqid=4a8c89db0c5e42be8c167e123e956bdb&taskstatus=TAPERECALL"

```
to see the situation for a task. open this in browser
```
https://cmsweb.cern.ch/crabserver/preprod/task?subresource=search&workflow=210111_125027:belforte_crab_20210111_135021
```
or
```
X5curl -k -X GET "https://cmsweb.cern.ch/crabserver/preprod/task?subresource=search&workflow=210111_125027:belforte_crab_20210111_135021"
```

**Comment by belforte** [comment]
first version that sort of works is there. Runs OK with a a task in TAPERECALL and data not staged. Needs more testing (esp. with rule state = OK).

**Comment by ericvaandering** [comment]
OK is the only status you should release jobs on
