### ISSUE TITLE
TW should restart, not kill, tasks found in QUEUED

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABServer#6347]
To be able to automatically stop/restart TW at any time, we need to make sure that task that are set to `QUEUED` during TW stop, are set to `NEW` during TW start. Currently during restart they are set to `FAILED`.

Code to change is here:
https://github.com/dmwm/CRABServer/blob/7da48cc35592c3bbe3da593c92356207a0d57eba/src/python/TaskWorker/MasterWorker.py#L284-L288

Related issues: #6331 and #6151

**Comment by belforte** [comment]
We need to think a moment about what to do with commands KILL and RESUBMIT.
Mostly for my undersrtanding. I am sure I have seen already comments in the code like
"it is always safe to issue kill again". I am not sure why we do not do that already.

**Comment by ddaina** [comment]
I am working on this one now. Do I understand correctly that instead of updating `task['tm_task_command']` to `SUBMITFAILED, RESUBMITFAILED, KILLFAILED`, we should instead update `tm_task_status` from `QUEUED` to `NEW`? and leave `task['tm_task_command']` as is since it will always be one of the `SUBMIT, RESUBMIT, KILL`?*

*I understand that `KILL` and `RESUBMIT` might need different solution. Question is just more in general to understand the overall solution

**Comment by belforte** [comment]
you understand perfectly. You can replace the STATE_ACTION_MAP with 'NEW'. And also use better name than failstatus

**Comment by ddaina** [comment]
great, thank you!
