### ISSUE TITLE
Make CRAB work with current WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6373]
as a pre-requisite to make CRAB run with py3, we need to switch from old fork 1.3.6.crab which is py2 only, to the master branch which is supposed to run both in py2 and py3.

@ddaina @sharmaprajesh FYI

as first step I have built CRAB TaskWorker adding py2-future to the spec file and at least it starts

**Comment by amaltaro** [comment]
Stefano, just wanted to mention that WMCore isn't yet fully compatible with py2/py3. 
If you could list the WMCore packages used within CRAB, we could investigate whether those are fully compatible, and if not, we can try to prioritize them.

**Comment by belforte** [comment]
@amaltaro we are trying to align  back to WMCore master branch. I am using now tag 1.4.4
First issue:
```
				  File "/data/srv/TaskManager/v3.210128/slc7_amd64_gcc630/cms/crabtaskworker/v3.210128/lib/python2.7/site-packages/WMCore/JobSplitting/JobFactory.py", line 13, in <module>
				    from WMCore.WMBS.File import File as WMBSFile
				ImportError: No module named WMBS.File
```
Where is WMBS now ?
I looked at https://github.com/cms-sw/cmsdist/blob/comp_gcc630/wmagent.spec and there is nothing which rings a bell.
Compared with https://github.com/cms-sw/cmsdist/blob/comp_gcc630/crabtaskworker.spec I have removed cherrpy and added py2-future
(TW does not run a web site)

**Comment by belforte** [comment]
About py2/3 do you mean that some package does not run on py3 yet ?

**Comment by amaltaro** [comment]
> Where is WMBS now ?

Perhaps you haven't sourced the init.sh script to put packages in the python path? See:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMBS/File.py

> About py2/3 do you mean that some package does not run on py3 yet ?

Precisely! This GH project should give you a better idea of what is still left to be done:
https://github.com/dmwm/WMCore/projects/9

But as I said, if you have a list of packages, we could check those as well.

**Comment by belforte** [comment]
I suspect that when we build TW we only pur part in the rpms.
Now that I know where it is, I will take care. But do you acknowledge that this was changed recently ? That's all.
I agree that I need to make a list of dependencies...
As a start I did it for CRABClient. which has much fewer: 
https://github.com/dmwm/CRABClient/issues/4940

**Comment by belforte** [comment]
it works when I point PYTHONPATH to my WMCore GH close (sh start private.sh for @ddaina ). So it is really an rpm thing. I am scratching my memory cells.

**Comment by belforte** [comment]
Alan, is this what you need:
https://github.com/dmwm/WMCore/blob/ea14941d5b957a2f905b7d1299126c814a1e2b1a/setup_dependencies.py#L149-L152
Indeed at the moment it does not have WMCore.WMBS
I'll make a PR

**Comment by belforte** [comment]
Tasks are submitted once WMBS is fixed, but I forgot that we need to push py2-future also to the schedd's for the components which run there. WIll do.

**Comment by belforte** [comment]
@Alan, leaving "running with a python3 interpreter" aside for now, do you agree that there is no good reason why we should stay with 1.3.6.crab branch and should make a push to catch up with WMCore master ?

**Comment by amaltaro** [comment]
Keeping up with the latest releases of your dependency stack is always a good choice (something that I will ensure it happens once WMCore is in python3!). However, it might be that the amount of work with this "catching up" is going to be reasonable high.

Besides the many changes in WMCore between 1.3.6 and 1.4.5, other things that come to my mind are:
* CRAB specs - depending on WMCore - need to add a `Requires: py2-future`
* depending on how the CRAB job wrapper is, it could be that it needs to have access to python-future from the worker node as well (as we do for WMCore)
* strings are complicated, especially when running a mix of py2.7 and modernized code altogether. So something to be extra careful here.

**Comment by amaltaro** [comment]
Regarding CRAB migration to python3, I'd suggest to make a hard migration and drop support to python2 completely, if possible.

Note: I'm going to cut a final `1.4.5` release soon.

**Comment by belforte** [comment]
* We can do the hard migration for crabserver and crabtaskworker. And may need to for crabtaskworker anyhow since new HTCondor releases will only be python3 and we use their python bindings.
* But AFAIU crabclient needs to keep running in py2 as well. See the ad -hoc issue https://github.com/dmwm/CRABClient/issues/4940.
* On the WN we use python2 from CMS so should have no probem with future.
* Instead on schedd's so far we use system python. So it is not trivial. I'll make an ad-hoc issue to track it. Best way may be to use python from /cvmfs/cms.cern.ch

**Comment by belforte** [comment]
By the way, CRAB job wrapper currently runs with a mix of
/cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.6/etc/profile.d/init.sh
( nicely stable since 2015 ! ) and
/cvmfs/cms.cern.ch/slc7_amd64_gcc630/external/python/2.7.11/bin/python
( no good reason other than schizophrenia, of course)
which of course works for the simple python we run there, but ... we should modernize.
@amaltaro can you point me to what's done in WMAgent now for finding python on the WN's ?

Overall, first priority seems to put order in python2 usage !
https://github.com/dmwm/CRABServer/issues/6374

**Comment by amaltaro** [comment]
This is our production/wmagent job wrapper:
https://github.com/dmwm/WMCore/blob/master/etc/submit.sh

which, among other things, it loads the python future library (and python, of course) from the correct CVMFS path, according to the job REQUIRED_OS. Something around these lines:
https://github.com/dmwm/WMCore/blob/master/etc/submit.sh#L121-L152

**Comment by belforte** [comment]
thanks Alan. What about the schedd where you run WMCore with HTCondor ? Do you deploy via COMP rpm's or have a python in CVMFS which has condor in it ? We currently get the python bingind via yum install htcondor on schedd machines.

**Comment by belforte** [comment]
N.B. I have moved the python saga to an ad=hoc issue #6374 
Will use this issue here for code changes needed in CRAB to adapt to new WMCore.
e.g. #5900

**Comment by amaltaro** [comment]
We deploy it with the COMP RPMs:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/condor.spec

thus, the wmagent spec contains a `Requires: condor` line to pull this dependency together.

However, I have just found that HTCondor python bindings are also made available via Pypi:
https://pypi.org/project/htcondor/
we should definitely explore and adopt it in the near future.

**Comment by belforte** [comment]
did you try to use pip for Rucio ?

**Comment by amaltaro** [comment]
Yes, we use pip, but still put it in our own RPM:
https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-rucio-clients.spec

we have some effort towards a different mode of software build and packing in WMCore, but it will likely get more effort once python3 modernization is over.

**Comment by belforte** [comment]
To use new WMCore in running jobs (which we do) we need to use same python as them, see: https://github.com/dmwm/CRABServer/issues/6374#issuecomment-772558398
- [ ] new issue: #6378

**Comment by belforte** [comment]
I think this is now done for all CRAB components that we run "centrally".
CRABClient is a different story given its dependency from CMSSW and the need to support old architectures.
I propose to deal separately with CRABClient (see also https://github.com/dmwm/CRABServer/issues/6374#issuecomment-773108441) and keep building it with WMCore tag 1.3.6.crab6 for as long as needed.

@amaltaro @klannon your opinion is welcomed ! Please include any other who may be kind enough to hand out an expert advice on this. Maybe a topic for a short "debate" in a Wednesday meeting ?

**Comment by belforte** [comment]
unless there are objections, I will close this once  there's a WMCore tag with https://github.com/dmwm/WMCore/pull/10250
We can address problems which pop up later, if any, in new issues.

**Comment by amaltaro** [comment]
>@amaltaro @klannon your opinion is welcomed ! Please include any other who may be kind enough to hand out an expert advice on this. Maybe a topic for a short "debate" in a Wednesday meeting ?

Crabclient gets shipped with CMSSW (or cmssw common), so it seems to me that we need to keep supporting crabclient in many different python stacks (2.6, 2.7 and 3+), and that will likely be for at least a couple of years.
If this statement above is correct, then I think having a separate "project" for crabclient would be important, as well as not depending on any other DMWM software (but through HTTP/REST calls). This would make maintenance easier and provide a long time support for old releases.

**Comment by belforte** [comment]
thanks Alan. I think the assumption is that CRAB will keep working "for Run3 data analysis" which I suspect means O(6) years, until Run4 dawns.

**Comment by belforte** [comment]
as per https://github.com/dmwm/WMCore/pull/10250#issuecomment-773596552 WMCore 1.4.6.pre2 has all we need now.
I am running a final test of TW with that and the use of COMP python in the job wrapper #6383 . Then we can make a new tag concluding the porting or CRABServer, TW and Publisher.

**Comment by belforte** [comment]
everything works, submission, xfer, publication, automatic splitting.
All code changes merged and tagged as v3.210204

**Comment by amaltaro** [comment]
Wonderful, thanks for making it happen, Stefano!

**Comment by belforte** [comment]
oooppsss.
the victory claim was based on a CRABServer built with WMCore 1.4.4
Unfortunately building with 1.4.5 and later breaks things for us.
The immediate problem is that the WMCore/REST parameter validation was changed in
https://github.com/dmwm/WMCore/commit/d6b9591d0325b523bb63e5b693aa8aab75234e2d
so that check_str now returns a list of bytes
https://github.com/dmwm/WMCore/blob/a4f60f75d5cfea05e4d3f06d4e02f1acd23ba01a/src/python/WMCore/REST/Validation.py#L31

later inside CRABServer code such paramenter cominng from a user submisssion HTTP PUT is compared with e.g. a list of sites retrieved from CRIC (JSON, i.e. a list of unicode strigs) and while  `'a' is in [u'a']` is True, after the conversion of `'a'`to  `future.types.newbytes.newbytes` , that is False.

I fully agree that strings and bytes and unicode are different things and that the current code is just "sloppy".
But now that the careless handling of unicode in CRABServer has surfaced, I am afraid it will take some time and much more effort to make things work.

Almost only for confirmation of this interpretation I have managed to submit my test task through the CRABServer on cmsweb-test2, built with WMCore 1.4.6.pre2 changing this
https://github.com/dmwm/CRABServer/blob/35d6d99973607a4a12730a00db92f0f84aeb6355/src/python/CRABInterface/RESTUserWorkflow.py#L351
into
```python
 validate_ustrlist("sitewhitelist", param, safe, RX_CMSSITE) 
```
and similarly in other two places.

BUT I am no exercising all parameters, and I do not know if for others it is better such forces conversion to unicode or to leave them as `future newbytes`. And of course there are many other files full of HTTP call handling which use same
parameter validation and conversion:
https://github.com/dmwm/CRABServer/tree/v3.210204/src/python/CRABInterface
We can't go by trial & error.

@mapellidario can you enlighen us on how to proceed ?

**Comment by belforte** [comment]
oooppsss.
the victory claim was based on a CRABServer built with WMCore 1.4.4
Unfortunately building with 1.4.5 and later breaks things for us.
The immediate problem is that the WMCore/REST parameter validation was changed in
https://github.com/dmwm/WMCore/commit/d6b9591d0325b523bb63e5b693aa8aab75234e2d
so that check_str now returns a list of bytes
https://github.com/dmwm/WMCore/blob/a4f60f75d5cfea05e4d3f06d4e02f1acd23ba01a/src/python/WMCore/REST/Validation.py#L31

later inside CRABServer code such paramenter cominng from a user submisssion HTTP PUT is compared with e.g. a list of sites retrieved from CRIC (JSON, i.e. a list of unicode strigs) and while  `'a' is in [u'a']` is True, after the conversion of `'a'`to  `future.types.newbytes.newbytes` , that is False.

I fully agree that strings and bytes and unicode are different things and that the current code is just "sloppy".
But now that the careless handling of unicode in CRABServer has surfaced, I am afraid it will take some time and much more effort to make things work.

Almost only for confirmation of this interpretation I have managed to submit my test task through the CRABServer on cmsweb-test2, built with WMCore 1.4.6.pre2 changing this
https://github.com/dmwm/CRABServer/blob/35d6d99973607a4a12730a00db92f0f84aeb6355/src/python/CRABInterface/RESTUserWorkflow.py#L351
into
```python
 validate_ustrlist("sitewhitelist", param, safe, RX_CMSSITE) 
```
and similarly in other two places.

BUT I am no exercising all parameters, and I do not know if for others it is better such forces conversion to unicode or to leave them as `future newbytes`. And of course there are many other files full of HTTP call handling which use same
parameter validation and conversion:
https://github.com/dmwm/CRABServer/tree/v3.210204/src/python/CRABInterface
We can't go by trial & error.

@mapellidario can you enlighen us on how to proceed ?

**Comment by belforte** [comment]
And of course there can be many other places, besides REST call handling, where CRAB code suffers of string/unicode confusion. All in all  this code started in a time when people called "json" the string conversion of a python dictionary, and I have been fighting unicode confusion for years. Simply my cure usually was to cast everything to `str`. But with these `newstrings` around which are not really list of bytes anymore... more changes and more type safety may be needed.

**Comment by belforte** [comment]
FWIW I decided to give it a try with [1]
```
for f in `ls *py`; do sed -i -e 's/validate_str/validate_ustr/g' $f; done
```
and restarted crab-dev-tw01. And so far it works.

[1]
yeah...  issue it a couple of times because some line has >1 occurrences of validate_str this was just for fur

I am tempted to make a PR with that and build a new CRABServer.... But can't believe that fix is so easy

**Comment by belforte** [comment]
indeed it is not that simple, PostJob fails to update status of transferred files
```
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa ENTER cmsweb_analysis_dev@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (POST dev filetransfer
s) inuse=0 idle=1
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa (previously nNXxVzhvLYHs) connected, client: 11.2.0.4.0, server: 11.2.0.4.0, stmtcache: 50
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa ping
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa check [select sysdate from dual]
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa connection established
[05/Feb/2021:23:28:31]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.TypeError 750a966bb8be0c19dece3081c1af9dbe [instance: dev] (translate() takes exactly one argument (2 given)); last statement: None; binds: None, None; offset: None
[05/Feb/2021:23:28:31]    Traceback (most recent call last):
[05/Feb/2021:23:28:31]      File "/data/srv/HG2103a-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.210204/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1772, in dbapi_wrapper
[05/Feb/2021:23:28:31]        return handler(*xargs, **xkwargs)
[05/Feb/2021:23:28:31]      File "/data/srv/HG2103a-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.210204/lib/python2.7/site-packages/CRABInterface/RESTFileTransfers.py", line 167, in post
[05/Feb/2021:23:28:31]        ids = (kwargs['list_of_ids'].translate(None,"[ ]'")).split(",")
[05/Feb/2021:23:28:31]    TypeError: translate() takes exactly one argument (2 given)
[05/Feb/2021:23:28:31] crabserver-7b49f7f484-hv9zk 137.138.148.19 "POST /crabserver/dev/filetransfers HTTP/1.1" 500 Internal Server Error [data: 3119 in 745 out 11720 us ] [auth: OK "/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica Nucleare/CN=Stefano Belforte belforte@infn.it" "" ] [ref: "" "CRABServer/0.0.0" ]
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa disconnecting
[05/Feb/2021:23:28:31]  RESTSQL:vzrkOsniCXFa DISCONNECTED cmsweb_analysis_dev@int2r timeout=300 inuse=0 idle=0
```

**Comment by belforte** [comment]
better track in a separate issue:  #6388

**Comment by belforte** [comment]
No known problems at the moment

**Comment by belforte** [comment]
keeping it open until we have ran for a while with this in preprod.

**Comment by belforte** [comment]
tests in preprod aka cmsweb-testbed hit a very mysterious problem with Oracle authentication. Short summary is that right after post starts crabserver fails to connect to DB with:
```
[16/Feb/2021:14:58:38]  SERVER DATABASE ERROR 503/401 Database unavailable cx_Oracle.DatabaseError 2b25c4e055c71005e37f97830b7f6916 [instance: dev] (ORA-12545: Connect failed because target host or object does not exist); last statement: None; binds: None, None; offset: None
[16/Feb/2021:14:58:38]    Traceback (most recent call last):
[16/Feb/2021:14:58:38]      File "/data/srv/HG2103c-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.210210.py3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1480, in _connect
[16/Feb/2021:14:58:38]        dbh = (self.idle and self.idle.pop()) or self._new(s, trace)
[16/Feb/2021:14:58:38]      File "/data/srv/HG2103c-comp/sw.ddirmait/slc7_amd64_gcc630/cms/crabserver/v3.210210.py3-comp/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1525, in _new
[16/Feb/2021:14:58:38]        ret.update({"connection": s["type"].connect(s["user"], s["password"], s["dsn"], threaded=True)})
[16/Feb/2021:14:58:38]    DatabaseError: ORA-12545: Connect failed because target host or object does not exist
```
(I managed to add a log call before line 1525 in WMCore/REST/Server.py and the calues of `s["user"], s["password"], s["dsn"]` are correct) I searched in google for this error, but all answers are on the tune of "you try to connect to a DB which does not exist". I verified that the host where oracle int2r runs can be reached from the failing container (via ping and via ssh to the port used by oracle) but do not know a way to test an SQL connection from the container other then running the server. No sqlplus there.

That error usually stays there from about 20~30 min (even if we have seen it disappear in 10 or stay for almost 1h) and then disappear "by itself" and does not come back.
Same rpm's installed on my VM, works perfectly.

The problem is now affecting also cmsweb-test2. 

Daina and myself tried to blame all possible things and tried a dozen images in last two days, but could not find any good thread to follow. The very fact that problem disappears w/o apparent reason after a random time even if we do nothing, makes it impossible to correlate with things. And we can't debug the call Oracle more "down" that what done with the print.

This odd thing started on Feb 11.

We decided to wait until next week when Kate is back and can guide us from Oracle side.

Will also be good to take a breath and put order in current images mess, was a wild two days.

On the good side, apparently T0 has same problem as well now.  So we think it is not due to some change of ours.

On the better side, when we tried to blame httplib2 upgrade, we discovered that crabserver does not use it and now have removed 3 dependencies from our spec file : `py2-mysqldb, py2-sqlalchemy, py2-httplib2`

**Comment by muhammadimranfarooqi** [comment]
Hi,

After investigation of the issue, it seems it is related with the base `cmsweb` image which is now using latest CC7 image `20210201-1.x86_64`. After reverting back to the old cmsweb image that uses CC image `20201201-1.x86_64` does not has this problem. The problem appears in `crabserver` and `t0wmadatasvc` services.

**Comment by belforte** [comment]
thanks @muhammadimranfarooqi   !

**Comment by muhammadimranfarooqi** [comment]
Hi,

I have created new cmsweb image that uses lagest CC7 tag again. Then I created crabserver and t0wmadatasvc images based on this cmsweb image and deployed both in testbed. They both are working fine. May be there was problem with previous `cmsweb` image.

**Comment by belforte** [comment]
that's a very good news @muhammadimranfarooqi . Thanks !

**Comment by belforte** [comment]
@ddaina I am afraid that you need to rebuild the images which you just deployed so we have up to date code to test everywhere.

**Comment by ddaina** [comment]
I've rebuild images and deployed to test2 and testbed clusters. crabserver worked right away.

**Comment by belforte** [comment]
I am running some tasks through testbed, will check test2 as well. Everything is OK so far.

**Comment by belforte** [comment]
testbed is OK. including TW and Publisher running v3.2310218 (same tag as crabserver).
I am moving to test cmsweb-test2.

**Comment by belforte** [comment]
as far as I can tell, everything works.
At the moment there's no pending problem.
Back to: put in testbed the pythonMIgration tag from test2, validate again, and then possibly merge with master and consolidate a new starting point.

**Comment by ddaina** [comment]
I've updated testbed and now it runs `v3.210218.py3` tag

**Comment by belforte** [comment]
there's a log of failure accessing filetransfersdb in testbed since last night. I hav enot investigated yet. But it is possible that it is related :-(

**Comment by belforte** [comment]
All errors come from Publisher on preprod-tw01. I will check logs as soon as I have time

**Comment by belforte** [comment]
errors are due to this in the craberver REST
```
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW ENTER cmsweb_analysis_preprod@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (POST preprod filetransfers) inuse=0 idle=0
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW instantiating a new connection
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW connected, client: 11.2.0.4.0, server: 11.2.0.4.0, stmtcache: 50
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW ping
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW check [select sysdate from dual]
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW connection established
[22/Feb/2021:14:13:33]  SERVER DATABASE ERROR 500/403 Execution error __builtins__.IndexError fc852f4049879984d2e9e4ed1cd65bad [instance: preprod] (list index out of range); last statement: None; binds: None, None; offset: None
[22/Feb/2021:14:13:33]    Traceback (most recent call last):
[22/Feb/2021:14:13:33]      File "/data/srv/HG2103e-comp/sw.crab_pythonMigration/slc7_amd64_gcc630/cms/crabserver/v3.210218.py3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 1769, in dbapi_wrapper
[22/Feb/2021:14:13:33]        return handler(*xargs, **xkwargs)
[22/Feb/2021:14:13:33]      File "/data/srv/HG2103e-comp/sw.crab_pythonMigration/slc7_amd64_gcc630/cms/crabserver/v3.210218.py3/lib/python2.7/site-packages/CRABInterface/RESTFileTransfers.py", line 213, in post
[22/Feb/2021:14:13:33]        binds['fail_reason'] = [reasons[num]]
[22/Feb/2021:14:13:33]    IndexError: list index out of range
[22/Feb/2021:14:13:33] crabserver-8646bb54d6-fwxz2 188.184.89.161 "POST /crabserver/preprod/filetransfers HTTP/1.1" 500 Internal Server Error [data: 4395 in 745 out 65256 us ] [auth: OK "/DC=ch/DC=cern/OU=computers/CN=tw/crab-preprod-tw01.cern.ch" "" ] [ref: "" "CRABPublisher/v3.210218" ]
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW disconnecting
[22/Feb/2021:14:13:33]  RESTSQL:VYORkCMUsrvW DISCONNECTED cmsweb_analysis_preprod@int2r timeout=300 inuse=0 idle=0
```

Sounds like a code mismatch between Client (Publisher) and Server (Crabserver ). O can dig, but details aside, I am puzzled why it was not showing up on cmsweb-test2 where I ran publications too.

Maybe we forgot to update cmsweb-preprodtw01 containers to `py3` branch ?

**Comment by belforte** [comment]
I have updated TW and Publisher for testbed to v3.210218.py3 . Errors have gone away. Let's run more.

**Comment by belforte** [comment]
At this pont everything looks good. We have a working CRAB based on WMCore 1.4.6.pre2
Actions:
- [ ] merge master and pythonMigration branches
- [ ] tag new master and make a final round of test. Make sure include also https://github.com/dmwm/CRABServer/pull/6398
- [ ] deploy in production

Then we go back to "stay aligned with WMCore master" and will try to avoid a WMCore branch for CRAB.
@ddaina  FYI.  I hope you can take care of this next week.

**Comment by ddaina** [comment]
Thanks, I will take care. Will ping you before merging the branches.

**Comment by belforte** [comment]
In the end it worked, but some unicode confusion made Oracle do full table scans and was unacceptably slow.
See some details in:
https://github.com/dmwm/WMCore/issues/10335
After suggestion from Kate I have tried to modify WMCore/REST/Server to force "string" bind variables to type `cx_Oracle.STRING` and am not testing with success (so far). For the moment changes are in my branch https://github.com/belforte/WMCore/tree/OraFixes

**Comment by belforte** [comment]
update:
while we are still running in production code build with WMCore 1.3.6.crab6, we have changed the master branch rather extensively to add support for crabcache on S3 and some long-due code cleanup.
Code is now supposed to be able to work with both old crabcache and new S3,
This required changes to Client, REST, TW and (for consistency) Publisher.
I have now managed to run on latest tag v3.210427 on preprod (cmsweb-testbed) all tasks from https://github.com/dmwm/CRABServer/tree/master/test/tasks.

I have submitted a final 3k job task. But we are ready to rather make sure that we try all possible combination of arguments/options/commands. 

I am in favor of closing this (at last!). And open targeted issues if we find problems.
@ddaina  what do you think ?

**Comment by ddaina** [comment]
> I am in favor of closing this (at last!). And open targeted issues if we find problems.
> @ddaina what do you think ?

I agree with you Stefano. That summarizes talks that we had in private chats.

**Comment by belforte** [comment]
We are very strongly convinced that currently everything in CRAB works with WMCore 1.4.6.crab1

**Comment by amaltaro** [comment]
Wonderful!
