### ISSUE TITLE
 modify start for TW and Publisher to take two arguments

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6418]
modify start for TW and Publisher to take two arguments: --debug and --fromGH and take GH from env var (reuse bash code from runContainer.sh

**Comment by belforte** [comment]
@ddaina do you want to do this ? since it is  about adapting your bash code which I barely understand ?

**Comment by ddaina** [comment]
sure, I will take care of it!

**Comment by belforte** [comment]
@ddaina  I will like to make some changes to the start script to make it more straightforward and readable, like the Publisher one (see #6417). But we can merge later. Just focus on replacing the current bash `case` with proper option parsing and help like in the runContainer. I am testing new format as `run.sh`
