### ISSUE TITLE
deploy GH clones for CRABServer and WMCore inside the container

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6422]
Checkout same branch as used in building the image. And point $GHrepoDir to it ( or place in a standard location like /data/repos)

**Comment by belforte** [comment]
@ddaina you are the expert here, but if you think you have too much, let me know and I'll give it a try

**Comment by belforte** [comment]
oh well, since I was touching crabserver image creation... it looked like I can simply copy things here as well, so am giving it a try
https://github.com/belforte/CRABServer/tree/changes-to-docker-6422
Will test and report here

**Comment by ddaina** [comment]
@belforte , should I do something here or are you on it?

**Comment by belforte** [comment]
I will take care.
