### ISSUE TITLE
flag failed docker installation and other docker issues

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6430]
when install.sh inside Docker file fails (e.g. a wrong tag was given as input) it is difficult to notice the message
`error: unknown package: cms+crabtaskworker+v3.210218.py3`
in the dump since docker goes on and build an image w/o the TW inside.

I think there's a non-zero return code somewhere in [install.sh](https://github.com/dmwm/CRABServer/blob/master/Docker/install.sh) which we can catch and stop the building

By the way should this line
https://github.com/dmwm/CRABServer/blob/64c0335cad80ec58f113d791ccc2b59ad19bb364/Docker/install.sh#L14
be changed to use `comp.crab_master` ? with a comment indicating to switch branch name if needed ?

Also, we have now https://github.com/dmwm/CRABServer/tree/master/Docker but files in there acutally build `crabtaskworker`, not `crabserver` . We should find a more clear naming, especially to avoid confusion with https://github.com/dmwm/CMSKubernetes/tree/master/docker/crabserver

**Comment by belforte** [comment]
I am addressing the second point:
https://github.com/dmwm/CRABServer/compare/master...belforte:changes-to-docker-6422#diff-d67c08b05b11bd1f1f5e047f172b283cb930dbc3b7bfe4a7488f66ba288f5f95

**Comment by ddaina** [comment]
> By the way should this line
> CRABServer/Docker/install.sh
> 
>  `export REPO=comp.crab3 `
> 
> be changed to use comp.crab_master ? with a comment indicating to switch branch name if needed ?

we can either change it to `comp.crab_master` or simply leave `export REPO=FIXME` since I anyway make sure that jenkins replaces this line with proper `comp` repo based on which branch was used for building RPMs

> Also, we have now https://github.com/dmwm/CRABServer/tree/master/Docker but files in there actually build crabtaskworker, not crabserver . We should find a more clear naming, especially to avoid confusion with https://github.com/dmwm/CMSKubernetes/tree/master/docker/crabserver

what if we add subdirectory`Docker/taskworker`? OTOH, it is used not only for TW, but for Publisher as well

**Comment by belforte** [comment]
I know that in Jenkins you make things work. But it is better to have a working example in GH . See if you like what I did.
As to naming, I do not have an idea I really like yet.
First idea is to call this with the same name as in spec file and rpm, since that's what it is: docker instructions to build an image which runs a given version of the package... alas calles `crabtaskworker`. Not a nice name. But unless we change the name of the specfile and the install.sh.. that's the name we are stuck with. The fact that the same image can run different services may or may not be a simplification. If we were to start now, we may probably create a base image called crabservice and then layer a small customization on top to get a container specialised for being a TW or a Publisher_X or whatever.
But we also need to stop improving what works, at some point :-)

**Comment by ddaina** [comment]
Agree to all what you said. 

If I would have to choose between

1. calling directory `crabtaskworker` given as you wrote that we call spec file and RPMs this name 

OR 

2. changing dockerfile to build TW and Publisher_X separate  images

I would for sure go for calling directory `crabtaskworker`. At this point I don't see what clear benefits N different images would bring :)  up until now I really liked the idea of maintaining only one image which can start both services.

**Comment by belforte** [comment]
>  until now I really liked the idea of maintaining only one image which can start both services.
somehow the subtle point is "how does one start a service" ?
 answer 1: have a script which customizes and runs some set of binaries
 answer 2: package everything as a container which can only be run in one way

tastes aside, 2. is clearly the way to go if you have many instances of many kind of such things, and need to use K8s or equivalent. Also 2. forces one to fully specify everything in a single place. Of course 1. is more flexible.
