### ISSUE TITLE
add S3 container keys to CRABServer Kubernetes secrets

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6462]
to be done for all clusters. We will use same container for prod/preprod/test.. since task names are unique anyhow.

**Comment by ddaina** [comment]
I have deployed secret to following`k8s` environments: `test2, testbed`.
Secret has the following structure:
```
[ddirmait@lxplus770 crabserver]$ cat S3_Secrets
aws_access_key_id = XYZ
aws_secret_access_key = 123
```
It is stored in the same place as `CRABServerAuth.py`

Please let me know if you have any suggestion how secret should be stored. Otherwise I would also deploy it to `prod`.

**Comment by belforte** [comment]
Looks perfect.
Thanks

**Comment by ddaina** [comment]
I did not deploy secrets to `prod` cluster, so I kept issue open. maybe we can close this ticket and deploy secrets to `prod` cluster at the same time as we update image there?

**Comment by belforte** [comment]
I am a bit confused. I thougth that there is some place where secret content is "maintained" (some private GitLab repo) and that once the S3 keys are there any new deployment will get them.
Now you make it sound like an explicit action is needed.
I do not want  to learn too many new things if I can avoid.
But let's keep it open until at keys are either in production as well, or we know that they will get there automatically.

**Comment by ddaina** [comment]
@muhammadimranfarooqi please correct me here if I am wrong, but secrets are not stored in any repo. Whenever we want to deploy secrets, we have to manually put secret files in the [services_config](https://gitlab.cern.ch/cmsweb-k8s/services_config) repo in our local path and run `deploy-secrets.sh` [script](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/scripts/deploy-secrets.sh) from CMSKubernetes repo. I followed these instructions for deploying secrets: https://cms-http-group.docs.cern.ch/k8s_cluster/deploy-secrets/ 

It is the same with `CRABServerAuth.py` - secret content is not stored if any repo.

**Comment by belforte** [comment]
Indeed I never understtood how to pass secrete files to the deploy-secrets script. What @ddaina described will very easily end up with every operator keeping those files in clear text in their git clone directory on lxplus... hmm. not so great. Three years down the road we will have no idea where those secrtets have leaked to. Maybe HTTP group can come up with a better way, Andreas Pfeiffer surely knows many tricks with PGP keys and so on, (too bad I do not have his GH username at hand to tag hime), @muhammadimranfarooqi  may I suggest that you bring this up to the group ? It is not a K8s issue, it is simply that we need to keep several "secrets" around and allow them to be used by authorized people w/o exposing them, and the list of authorized people change in time.
As long as it was a "one password".. ok, "two passwords".. not so bad, but now list is growing. In addition to "our password" we have "the file which Imran gives us", the OpenStack keys, yesterday we've been discussion DockerHug token...
Time to put order. All in all Andreas and Panos lead CMSWEB *AND* Security !

**Comment by muhammadimranfarooqi** [comment]
@belforte 

In VM cluster, we had put secrets on cmsweb account afs private area. So, during deployment script, these were taken from this area.  However, in K8s, we followed different mechanism. Since, every service developer is responsible for his/her service, so secrets are also upto them to maintain. 

So, we proposed secrets to be maintain in the local repository of `services_config` as Daina pointed out above. Secrets are not put in gitlab repo due to security issue. They must be maintain in the secure area of developers local path.

**Comment by belforte** [comment]
yes, this is exactly what worries me. Give it a few years, and someone will accidentally leave a copy in their public directory.
We have no way to track who had access to secrets in the past, especially people who left, etc. etc.
> So, we proposed secrets to be maintain in the local repository of services_config as Daina pointed out above. Secrets are > not put in gitlab repo due to security issue. They must be maintain in the secure area of developers local path.

**Comment by muhammadimranfarooqi** [comment]
@belforte 

Even if its happen, `services_config` is not public repository. We have only provided access to the developers only.

**Comment by belforte** [comment]
I am not worried that much about the gitlab repository as to the local clone on AFS. Chances for good-faithed but ill-directed attempts at manipulating AFS ACL's and exposing things are not that small. Also we have no way to enforce people to clone in private area rather then public one.

**Comment by muhammadimranfarooqi** [comment]
Hmm.

Like in the VM approach, we can think of delegating the responsibility of maintaining secrets to the CMSWEB team. And for this, we have to adjust all service manifest files and scripts. I'll discuss during our next meeting.

**Comment by belforte** [comment]
OK. we will move elsewhere the discussion on best practice to manage secrets.
@ddaina let's keep this open until S3 keys are deployed in prod cluster cmsweb.cern.ch

**Comment by belforte** [comment]
S3 keys are not in new BcakEnd on cmsweb-prod. Since Imran will switch cmsweb.cern.ch to use that BE on May 20, no more action is nedded.
