### ISSUE TITLE
Make monitoring scripts run as a container

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6493]
see https://github.com/dmwm/CRABServer/issues/6486

we need to have a different setup where we have proper version control and can make sure that our monitoring script use up to date code to talk to CRAB services. Now thatose are CRABServer REST and htcondor, later we may also want to ping S3...

Ideas:
 *  a container which runs the crontabs that we use for monitoring
 *  a crontab which runs a container which starts, does the work, and stops
 * a crontab which executes a script inside a container via docker exec.
 * one container with crontabs inside controlled by K8s ?
 * something else ?
 *

**Comment by belforte** [comment]
see
https://cms-logbook.cern.ch/elog/Analysis+Operations/3814

TIME TO DO THIS !

@novicecpp @mapellidario Mot imporant: let me know if you disagree with the topic or the priority.

We have already discussed this, and IIUC consensus is for a script inside the TW container to be run with a modicied runContainer.sh or something similar. Something like the 3d bullet in top comment.



If OK, let me also know if you can take care, or shall I do this.

**Comment by mapellidario** [comment]
I have a small update about my progress on this topic: I managed to find a (ugly) solution to run GenerateMONIT.py inside a slightly modified TW docker contianer. Once CERN monit team will provide us with new opensearch endpoints, I will open a PR with the final version of the dockerfile and the GenerateMONIT script.

Then I will tackle:

- [ ] [aso_metrics_ora](https://github.com/dmwm/CRABServer/blob/master/src/script/Monitor/aso_metrics_ora.py) TW environment. needs to write to opensearch. maybe requires new endpoint, maybe can re-use endpoint for GenerateMONIT and just change producer, I still need to check it
- [ ] [CheckTapeRecall](https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/CheckTapeRecall.py), see also [list-tape-recalls.sh](https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/list-tape-recalls.sh): crabserver rest, rucio, pandas. needs to write to eos
- [ ] [ProcessBadFilesList](https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/ProcessBadFilesList.py). pandas. needs to write to eos

[1] https://cern.service-now.com/service-portal?id=ticket&is_new_order=true&table=u_request_fulfillment&sys_id=514d58158377b91070ceba65eeaad343

**Comment by mapellidario** [comment]
Another small update: I managed to write a file to our beloved eos directory [1] from inside a docker container in crab-dev-tw04. I do not see any blocker for running running CheckTapeRecall in a docker container, I will do it tomorrow :)

[1] /eos/project-c/cmsweb/www/CRAB

**Comment by mapellidario** [comment]
Et voila, after some fiddling with python environments and certificates for rucio and crabserver, I managed to run checktaperecall in a docker container on crab-dev-tw04, whose output I copied at [1].

Now it's time for a cleanup and opening a proper PR

[1] https://cms-docs.web.cern.ch/CRAB/dmapelli-RecallRules.html

**Comment by mapellidario** [comment]
- [ ] make sure that the docker container stdout contains relevant information about the error that caused the script to fail [1]

---

[1]

<details><summary>example of a proper stdout, with relevant information about a failure</summary>

```plaitnext
Cron <crab3@crab-prod-tw02> export loguuid=$(uuidgen); test -f /home/crab3/runContainer.sh && bash /home/crab3/runContainer.sh -v 20240126-monitpython -s TaskWorker_monit_checktaperecall -u ${loguuid} >/dev/null 2>&1 ; [ -f /tmp/monit-${loguuid}.txt ] && cat /tmp/monit-${loguuid}.txt
---

123 rules exist for account: crab_tape_recall
state
OK             103
REPLICATING      7
STUCK           13
dtype: int64
finding tape source for all pending rules (takes some time...)
Add (DBS) dataset name ...
... and size
Done!
find tasks using these rules
Fatal error trying to connect to https://cmsweb.cern.ch:8443/crabserver/prod/task using subresource=taskbyddmreqid&ddmreqid=908834b3d78f4379924a0ab8f84819cb. Error details: {'Date': 'Wed, 10 Apr 2024 21:25:27 GMT', 'Server': 'Apache', 'Content-Type': 'text/html', 'Content-Length': '160', 'CMS-Server-Time': 'D=180008117 t=1712784147657519'}
Traceback (most recent call last):
  File "/data/srv/monit/CheckTapeRecall.py", line 442, in <module>
    main()
  File "/data/srv/monit/CheckTapeRecall.py", line 108, in main
    pending_compact = createRulesDataframe(pending, rucio, crab, logger)
  File "/data/srv/monit/CheckTapeRecall.py", line 162, in createRulesDataframe
    pending['tasks'] = pending.apply(lambda x: findTasksForRule(crab, x.id), axis=1)
  File "/home/crab3/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 9423, in apply
    return op.apply().__finalize__(self, method="apply")
  File "/home/crab3/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 678, in apply
    return self.apply_standard()
  File "/home/crab3/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 798, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/crab3/.local/lib/python3.8/site-packages/pandas/core/apply.py", line 814, in apply_series_generator
    results[i] = self.f(v)
  File "/data/srv/monit/CheckTapeRecall.py", line 162, in <lambda>
    pending['tasks'] = pending.apply(lambda x: findTasksForRule(crab, x.id), axis=1)
  File "/data/srv/monit/CheckTapeRecall.py", line 349, in findTasksForRule
    res = crabRest.get(api='task', data=encodeRequest(data))
  File "/data/srv/monit/RESTInteractions.py", line 248, in get
    return self.server.get(uri, data)
  File "/data/srv/monit/RESTInteractions.py", line 118, in get
    return self.makeRequest(uri=uri, data=data, verb='GET')
  File "/data/srv/monit/RESTInteractions.py", line 168, in makeRequest
    response, datares = self['conn'].request(url, data, encode=True, headers=headers, verb=verb, doseq=True,
  File "/data/srv/monit/WMCore/src/python/Utils/PortForward.py", line 66, in portMangle
    return callFunc(callObj, newUrl, *args, **kwargs)
  File "/data/srv/monit/WMCore/src/python/WMCore/Services/pycurl_manager.py", line 353, in request
    raise exc
http.client.HTTPException: url=https://cmsweb.cern.ch:8443/crabserver/prod/task, code=504, reason=Gateway Time-out, headers={'Date': 'Wed, 10 Apr 2024 21:25:27 GMT', 'Server': 'Apache', 'Content-Type': 'text/html', 'Content-Length': '160', 'CMS-Server-Time': 'D=180008117 t=1712784147657519'}, result=b'<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```

</details>

<details><summary>example of an incomplete stdout, without relevant information about a failure</summary>

```plaintext
Cron <crab3@crab-prod-tw02> export loguuid=$(uuidgen); test -f /home/crab3/runContainer.sh && bash /home/crab3/runContainer.sh -v v3.240111.monittw -s TaskWorker_monit_generatemonit -u ${loguuid} >/dev/null 2>&1 ; [ -f /tmp/monit-${loguuid}.txt ] && cat /tmp/monit-${loguuid}.txt
---
Define environment for TASKWORKER in /data/srv/TaskManager
Lock created. Start data collection

```

</details>

**Comment by mapellidario** [comment]
Scripts are happily running inside docker containers since a while, I will close this.

(i will make sure that the generatemonit script also runs inside the pypi container, but I will out of scope with this issue, it is a simple action item on my to do list)
