### ISSUE TITLE
use a dictionary to define RESTServer

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6513]
instead of passing around connection information to REST as two indipendente parameters
1. a HTTPRequest object usually called restServer  or variation of it
2. at times the name of the DB instance, at times the uriNoApi `/crabserver/instance/`), use always a single dictionary object:
```python
REST = {'server': RESTServer, 'uriNoApi': uriNoApi}
```
hopefully will make code more readable, more terse, and consistent in all places.
Especially for new functions which deal with S3 where the db instance is not used, but still needs to be set in the URL due to the way it works the base WMCore class which all our REST calls inherit from.

@ddaina FYI

**Comment by belforte** [comment]
I guess a more professional way would be to create a class (CRABServerREST e.g.) and pass an object of that class,  instead of a dictionary, encapsulating the details of the definition.
Add this to https://github.com/dmwm/CRABServer/blob/master/src/python/RESTInteractions.py  ?

Maybe not that much more work.
@ddaina what do you think ?

**Comment by ddaina** [comment]
I am not very much familiar with RESTServer communications and its internals so it is difficult to provide valuable opinion. I'd need more time to deep dive into code and think about it.

**Comment by belforte** [comment]
well.. I think a dictionary as argument is too awkward to document properly and hard to extend. So will try a class. The question is always how much we want to  handle independently `crabserver` and `prod` in `crabserver/prod` etc. The same issue we tried to deal with when creating the CRAB SERVICE INSTANCES in
https://github.com/dmwm/CRABServer/blob/8522b63c679dde40e40b3f094ededb5ab03b9147/src/python/ServerUtilities.py#L35
Somehow we have not found the best abstraction yet.
So we have a a lot of lines which just work around this with similar but not identical implementations of the same basic concept.
I need "simplicity at the core".

**Comment by belforte** [comment]
I have added a new class
https://github.com/dmwm/CRABServer/pull/6517
And will start using it. A simple test was OK.
Forgot to include it in v3.210408. Oh well will be for tomorrows release, I do not need it in the server container.
