### ISSUE TITLE
allow flexible matching requirements

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6534]
esp. with GPU's and similar coming into operations users may need to specify more then RAM and nCores when submitting. Adding one DB column for each possible new matching attribute is not good.
But also extending use of obscure, undocumentend, born-for-expert additionalJdl is not the best way.

Maybe introduce an `additionalRequirements` parameter where a list of requirements can be givend and still be properly parsed and validated before being added to the submission JDL,  handled like a CLOB on Oracle side.

This will also allow to separate syntax for users and HTCondor and to change names of semantic on either side w/o affecting the other.

**Comment by belforte** [comment]
See also https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#How_can_I_tell_CRAB_to_run_jobs
The thing proposed here will therefore include and supersede #6194

**Comment by novicecpp** [comment]
I think this was done by https://github.com/dmwm/CRABServer/pull/7296 (`tm_user_config` column in `task` table).

Can we close this?

**Comment by belforte** [comment]
I think I had in mind something more general, which may surely be not urgent and maybe never needed.
Give me the time to review the topic and re-think. Assigning to me.

**Comment by belforte** [comment]
I will never have time to think more in detail. Clearly what we have is good enough and is a very good template for extending to other requirements if needed w/o adding columns to the DB.
Closing
