### ISSUE TITLE
Make dag_bootstrap.sh send output to console when debugging

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6535]
this is the needed follow up to #6475 
which I forgot to open when that was close

Currently dab_bootstrap.sh creates a log file and reports proper exit code (to condor), but behavior is unchanged when running interactively and there is no output to console when e.g. running PostJob interactively for debug.

Pasting here from #6475 

look for possible alternatives, and test them well, e.g. along what indicated here
https://stackoverflow.com/questions/1221833/pipe-output-and-capture-exit-status-in-bash

**Comment by belforte** [comment]
mark as top because I can't spend half an hour everytime I need to debug posjob to re-learn whey there is no output

**Comment by belforte** [comment]
@ddaina  I am assigning this to both of us since I believe that you can do this as well (or better) than me. Let's see who find first the time to work on it, as usual most time consuming part will be testing.

**Comment by ddaina** [comment]
@belforte if you didn't start to work on this, I will take it now.

**Comment by belforte** [comment]
thanks !!! My hands are quite full atm

**Comment by belforte** [comment]
@ddaina for your convenience, I think that the easiest way to test changed to dag_bootstrap.sh is to go to the spool directory of one task and run it interactively following the recipe for any of the use cases here
https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3OperatorDebugging#Development_Oriented_Tricks_I_di
which are accidentally listed by simplest to trickiest
![Screenshot from 2021-04-16 08-41-03](https://user-images.githubusercontent.com/1837785/114982265-82fc0b00-9e8f-11eb-97a1-a4fd81f883b0.png)

then one importat test is to check failures to bootstrap are properly handled, I do not suggest to break condor in an odd way to test this, putting a syntax error in the dag_bootstrap.sh should be enough. You can do this by changing the code  in the TW in /data/repos and use updateruntime.sh.  Ping me if you have any difficulty

**Comment by belforte** [comment]
@ddaina, did you forget to make a PR for this, or do you need help with testing first ? Since we'll need a new tag, we can put this in as well.

**Comment by ddaina** [comment]
I tested it, but not according to the instructions provided above. If that is enough, I create PR and we do more extensive testing within new tag.

**Comment by belforte** [comment]
I presume that you tested that tasks run with the change.
make PR please. That will make it east for me to pull it and use it so I can confirm that it works properly when debugging as well. Wi
