### ISSUE TITLE
modify logstash config to  catch TW and Publisher config

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6584]
depends on
https://github.com/dmwm/CRABServer/issues/6583

**Comment by ddaina** [comment]
this is done.

1. TW configuration can be seen using datasource `monit-timber-cms-crab-taskworker ` and adding following filter: `data.log_type:tw_config_data` 
2. PB configuration can be seen using datasource `monit-timber-cms-crab-publisher ` and adding following filter: `data.log_type:publisher_config_data`
