### ISSUE TITLE
make a plan for moving PROD CRAB to S3 compatible

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6589]
we need to set some firm point now, and deploy in production current latest CRABServer/TW/Publ and CRABClient, so that
 * we can switch cache to S3 via a config change (and try incrementally)
 * we can validate the code on old crabcache exposing it to real life variety
 
Currently we run in production:
* crabserver: v3.210110
* TW: v3.210318patch1
* Pub: v3.210312
* Client: v3.210323

**Comment by belforte** [comment]
usual caveats:
* REST can only be upgraded if all current Tasks (build with up to a month old TW version) have code which is compatible with new REST
* if REST is backward compatible, it is the "usual scenario", we change things whenever we like.
* in case of non backward compatible changes in REST, we update TW / Publ first in a backward compatible way (work with both old and new REST) and only when old tasks have drained out can update REST
* there is no known way to change both TW and REST in a backward non-compatible way other than flushing the current work and asking users to submit again.

**Comment by belforte** [comment]
tentative plan from Stefano: https://docs.google.com/document/d/1MqjeQoPCTKywWXsQN5_WEtL0qCgOOpem2sF69L_B3II/edit?usp=sharing

**Comment by ddaina** [comment]
here is from my side: https://docs.google.com/document/d/1Qltn1DVsirFXWALOsaxLzZMSFSsjm0gIRgSh8FMxpUU/edit?usp=sharing

I haven't looked yet at yours, doing it now.

**Comment by belforte** [comment]
Plan made, and CRAB update completed, details in Daina's gdoc which was updated with all tests and elog references:
 https://docs.google.com/document/d/1Qltn1DVsirFXWALOsaxLzZMSFSsjm0gIRgSh8FMxpUU/edit?usp=sharing
