### ISSUE TITLE
CRABServer GUI Main Tab broken

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#6624]
All links (MONIT, Webdir, DAS Input) are broken. Error from browser below. Browser used is Firefox.
![image](https://user-images.githubusercontent.com/646582/120009578-f87bf080-bf90-11eb-8f30-995973329e55.png)

Error:
```
Uncaught TypeError: Cannot read property '1' of null
    at loadGlobalDataFromTaskInfo (static?script/task_info.js:182)
    at loadOtherData (static?script/task_info.js:868)
    at Object.<anonymous> (static?script/task_info.js:212)
    at j (static?script/jquery/jquery.min.js:2)
    at Object.fireWith [as resolveWith] (static?script/jquery/jquery.min.js:2)
    at x (static?script/jquery/jquery.min.js:4)
    at XMLHttpRequest.b (static?script/jquery/jquery.min.js:4)
```

**Comment by belforte** [comment]
looks like this is due to the fact that `tm_output_dataset` returned by queries to crabserver DB is a bytestring instead of unicode, e.g. from https://cmsweb-test1.cern.ch/crabserver/ui/task/210530_102306%3Abelforte_crab_20210530_122256/dbver/preprod
```
tm_output_dataset    [b'/CRABTest/belforte-autotest-1622370176-216676be7e2696871905cfbff5c13c01/USER']
```

**Comment by belforte** [comment]
so far I see only another DB column with same problem : `tm_edm_outfiles`

**Comment by belforte** [comment]
hmm...
maybe this line
https://github.com/dmwm/CRABServer/blob/805191a1c1b284ef51fbd1702e6ccd47a368d3ce/src/python/CRABInterface/RESTTask.py#L339
skipped being fixed
https://github.com/dmwm/CRABServer/commit/f940c38fe9088c1a6f2047026dabb996ef6a1e80#diff-320d836812da8a5cd643fb20b7a8acde728bd696829f51de0e4aebd9b140a379

I guess I should test removing `str()` from there

**Comment by belforte** [comment]
@sharmaprajesh confirmed that this is a problem in writing to the DB
```
SQL> select TM_OUTPUT_DATASET  from tasks where TM_TASKNAME='210530_102306:belforte_crab_20210530_122256';
TM_OUTPUT_DATASET
--------------------------------------------------------------------------------
[b'/CRABTest/belforte-autotest-1622370176-216676be7e2696871905cfbff5c13c01/USER'
SQL>
```

**Comment by belforte** [comment]
with ref. to
https://github.com/dmwm/CRABServer/blob/805191a1c1b284ef51fbd1702e6ccd47a368d3ce/src/python/CRABInterface/RESTTask.py#L338-341
the wrapping `str()` needs to stay, since I need to pass a string variable, not a list, to the oracle api below
indeed in there any existing value in the DB is passed correctly as string in Line 338, the problems come from `kwargs['outputdatasets']` which is a list of strings in the format `[b'abcd']`

**Comment by belforte** [comment]
indeed it seems a use case like I had with site b/w list where it was needed to validate the REST argument as a list of unicode strings:
https://github.com/dmwm/CRABServer/blob/805191a1c1b284ef51fbd1702e6ccd47a368d3ce/src/python/CRABInterface/RESTUserWorkflow.py#L351-L354

**Comment by belforte** [comment]
Clearly list of lumis are done properly now, but it is also true that those are massaged extensively before insertion in Oracle, in
https://github.com/dmwm/CRABServer/blob/805191a1c1b284ef51fbd1702e6ccd47a368d3ce/src/python/CRABInterface/DataFileMetadata.py#L62

So better to go one thing at a time.
For `outputdataset` the change to `validate_ustrlist` appears safe. I will test a bit more though.

**Comment by belforte** [comment]
Validating to `ustrlist` has odd effects if I pass a list to the REST as argument:
```
subresource=addoutputdatasets&workflow=210607_122042%3Abelforte_crab_20210607_142031&outputdatasets=MyData3&outputdatasets=MyData4
```
results in this in the DB
```
"['/GenericTTbar/belforte-Stefano-Test-210506-bb695911428445ed11a1006c9940df69/USER', 'MyData', u'MyData4', u'MyData3', 'MyData2']"
```

**Comment by belforte** [comment]
OK. So it looks like getting proper data format from DB has been always a problem, the CRAB code is scattered with calls to   [literal_eval](https://docs.python.org/2.7/library/ast.html?highlight=literal_eval#ast.literal_eval)  apparently exactly to deal with things like converting
`u"[b'+CRAB_USE_NEW_PUBLISHER=True']"` to `['+CRAB_USE_NEW_PUBLISHER=True']`
https://github.com/dmwm/CRABServer/blob/805191a1c1b284ef51fbd1702e6ccd47a368d3ce/src/python/TaskWorker/Actions/DagmanCreator.py#L511

**Comment by belforte** [comment]
cmsweb-test2 is now running with this fix. Will test.
