### ISSUE TITLE
trigger tape_recall also for dataset partially on disk

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6666]
after discussing with  Nick Smith ( @nsmith- ), we agreed to enhance current tape recall
functionality in CRAB to also take care of datasets partially on disk .

Plan:
1. have a list of allowed data tiers in TW config (so we can start with e.t. MINIAOD* or similar, and only allow RAW or RECO if/when needed)
2. if dataset is not fully on disk, CRAB will treat it like nothing on disk. Make a Rucio rule requesting all of the dataset to be on disk for 14 days and hold the user task until the rule is OK.
3. as a possible optimization later on, depending on user demand and my time, I can look into the more complex possibility to add a configuration option to skip that and just process what's on disk.

1. and 2. may be done "by end of summer" compatibly with how tricky python3 support is. 3. is something I hope to never need to do.

**Comment by nsmith-** [comment]
I believe we can safely start with `*AOD*` as allowed data tiers

**Comment by belforte** [comment]
WIll do this next after #6438

**Comment by belforte** [comment]
example in https://cmsweb.cern.ch/crabserver/ui/task/210617_134032%3Ashilpi_crab_SinglePhotonRun2017F09Aug2019UL2017v1AOD
which uses as input `/SinglePhoton/Run2017F-09Aug2019_UL2017-v1/AOD` (DAS pointer: 
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FSinglePhoton%2FRun2017F-09Aug2019_UL2017-v1%2FAOD )

**Comment by belforte** [comment]
commit https://github.com/belforte/CRABServer/commit/ff0dd9af95cc3de4016b7d351a15fb07756e92dd always triggers a tape recall. Now need to add a filter on data tier.

**Comment by belforte** [comment]
filter added via https://github.com/dmwm/CRABServer/pull/6684/commits/8266f0df6e37c902ec3460540b982550844ce64c
and list of allowed tiers added to TaskWorkerConfig.py via https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/a6c03874bfb2dc1b959d20772f88fd20c0807d63

**Comment by belforte** [comment]
solved via https://github.com/dmwm/CRABServer/pull/6684
