### ISSUE TITLE
add docker system prune -af to CRAB PR Jenkins test

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6674]
see
https://cms-dmwm.slack.com/archives/C04KWAXHU/p1624450270060000

**Comment by belforte** [comment]
@ddaina do I understand correctly from your reporting last wednesday that this is done ?

**Comment by ddaina** [comment]
last week I reported that docker images older than 1month from CRAB TW machines are deleted: https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/3fc38455c568a11867f1c22e96ef79ca8b0b3b8c

but problem described in this issue is solved as well.
