### ISSUE TITLE
make it possible to pick CMSSW release/arch for Jenkins test from a list

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6680]
in https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/build?delay=0sec
there should be a box to say if to pick CMSSW release from a free-text field (so we enter whatever we want)
or to pick it from a list  of pre-defined ones to test as per https://github.com/dmwm/CRABServer/issues/6659
We also need to set the scram arch in a similar way i.e. the CHOICE list should have a list of release/arch pairs. While the free text choice should allow full freedom.

**Comment by ddaina** [comment]
#6701 now allows to set SCRAM_ARCHITECTURE manually (and jenkins was updated with the change), so half of the issue is solved. what is left - make jenkins allow to pick different combinations that are mentioned in #6659.
