### ISSUE TITLE
make a version of S3 utils in ServerUtiliies based on gocurl

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6685]
could start with:
* if `gocurl` is in the $PATH, use that in place of curl

that will allow to test easily in client.

We will decide later if we want to use it in place of current `curl/wget` also on TW and schedd

@ddaina if you want to work on this, fine with me, just change the Assignee. But it would be nice to give a feedback to Valentin very soon.

**Comment by ddaina** [comment]
as agreed during CRAB meeting, I will test `gocurl` to upload file to `s3` using `presignedURL`. I'll report results here by tomorrow morning.

**Comment by ddaina** [comment]
@belforte,

I've looked into the `s3` `upload` using `presignedURL`. Long story short - `gocurl` works and file was uploaded successfully. 

For testing purpose, I submitted one crab task and then from the task log file took command that was executed to upload file to `s3`. Here is the command:
```
curl -f -v -X POST  -H "User-Agent: CRAB" -F "key=ddirmait/sandboxes/84583ca65afaa9ff0f80ffce8b932c9e33b8e456eeb1e14c9a0d8e9ec9b54b60.tar.gz" 
-F "AWSAccessKeyId=FIX_ME" 
-F "policy=FIX_ME" 
-F "signature=FIX_ME" 
-F "file=@/afs/cern.ch/user/d/ddirmait/crab_tasks/crab_projects/crab_20210630_220652/inputs/debugFiles.tgz" 
"https://s3.cern.ch/crabcache_preprod"
```
and this curl command maps to this `gocurl` command:
```
[ddirmait@lxplus740 gocurl]$ ./main -verbose 2 
-method "POST" 
-header "User-Agent:CRAB" 
-form "AWSAccessKeyId=FIX_ME"  
-form "key=ddirmait/sandboxes/84583ca65afaa9ff0f80ffce8b932c9e33b8e456eeb1e14c9a0d8e9ec9b54b60.tar.gz" 
-form "policy=FIX_ME" 
-form "signature=FIX_ME" 
-form "file=@/afs/cern.ch/user/d/ddirmait/crab_tasks/crab_projects/crab_20210630_220652/inputs/debugFiles.tgz" 
-url "https://s3.cern.ch/crabcache_preprod"
```

I removed from the command `AWSAccessKeyId`, `policy` and `signature`, however, looking at the real values of these variables, they contain symbol `=`. For instance, `signature` can be equal to `adasbjfgai23==`. And at this place current `gocurl` code breaks here:
https://github.com/vkuznet/gocurl/blob/ce93c98d345351fb31e1663121bc569d4ae0977b/main.go#L107
 because it splits line on `=` sign. So, as a quick solution to it, I changed that line to be:
 ```
 arr := strings.SplitN(f, "=", 2)
 ```

**Comment by ddaina** [comment]
@belforte,

I've looked into the `s3` `upload` using `presignedURL`. 

For testing purpose, I submitted one crab task and then from the task log file took command that was executed to upload file to `s3` (before testing I delete associated file from `s3`). Here is the `curl` command:
```
curl -f -v -X POST  -H "User-Agent: CRAB" -F "key=ddirmait/sandboxes/84583ca65afaa9ff0f80ffce8b932c9e33b8e456eeb1e14c9a0d8e9ec9b54b60.tar.gz" 
-F "AWSAccessKeyId=FIX_ME" 
-F "policy=FIX_ME" 
-F "signature=FIX_ME" 
-F "file=@/afs/cern.ch/user/d/ddirmait/crab_tasks/crab_projects/crab_20210630_220652/inputs/debugFiles.tgz" 
"https://s3.cern.ch/crabcache_preprod"
```
then I mapped this curl command into this `gocurl` command:
```
[ddirmait@lxplus740 gocurl]$ ./main -verbose 2 
-method "POST" 
-header "User-Agent:CRAB" 
-form "AWSAccessKeyId=FIX_ME"  
-form "key=ddirmait/sandboxes/84583ca65afaa9ff0f80ffce8b932c9e33b8e456eeb1e14c9a0d8e9ec9b54b60.tar.gz" 
-form "policy=FIX_ME" 
-form "signature=FIX_ME" 
-form "file=@/afs/cern.ch/user/d/ddirmait/crab_tasks/crab_projects/crab_20210630_220652/inputs/debugFiles.tgz" 
-url "https://s3.cern.ch/crabcache_preprod"
```

However, current go curl code did not work for me because of the following reason:

I removed from the command above `AWSAccessKeyId`, `policy` and `signature` values, however, looking at the real values of these variables, they contain symbol `=`. For instance, `signature` can be equal to `adasbjfgai23==`. And at this place current `gocurl` code breaks here:
https://github.com/vkuznet/gocurl/blob/ce93c98d345351fb31e1663121bc569d4ae0977b/main.go#L107
 because it splits line on `=` sign which is part of our string. So, as a quick solution to it, I changed that line to be:
 ```
 arr := strings.SplitN(f, "=", 2)
 ```

And after this change I built new executable by running:
```
go build main.go
```

And now file should be uploaded to `s3` using command provided above.
This is `http` response:
```
2021/06/30 22:45:36 main.go:296: http response url https://s3.cern.ch/crabcache_preprod, dump HTTP/1.1 204 No Content
Content-Length: 0
Accept-Ranges: bytes
Bucket: crabcache_preprod
Date: Wed, 30 Jun 2021 20:45:36 GMT
X-Amz-Request-Id: tx0000000000000089443e6-0060dcd7f0-1c85081b-default

, error <nil>
```
Which has line `, error <nil>` I am not quite sure what it supposed to mean, but I assume it should be fixed (?)

Let me know if something is unclear and I should elaborate more.

**Comment by belforte** [comment]
thanks @ddaina . I do not understand what this line exactly means
```
arr := strings.SplitN(f, "=", 2)
```
but I think this should be reported to Valentin and let him figure the way he likes best to deal with it, including the odd error message.
OTOH could you check that the upload worked ? I.e. the file in the container was changed ?
Our PreSignedUrl's are valid for 60min (incidentally this means that it is safe to copy/paste hem around), So your test is not reproduccible. It would be better to modify temporarely e.g. cmsweb-test1 to get PSU valid for e.g. 15 days and hand a couple to Valentin for testing. I can do that this morning after I go buying groceries.

**Comment by belforte** [comment]
even better. We can use directly boto3 to generate ad-hoc PSU which write in a test bucket and hand Valenting also an URL to list content since he does not have OpenStack keys for CRAB project. I think I have core ready in my test notebook.

**Comment by ddaina** [comment]
> I do not understand what this line exactly means

It simply splits line into 2 parts using first found `=` operator.

> but I think this should be reported to Valentin and let him figure the way he likes best to deal with it, including the odd error message.

agree.

> OTOH could you check that the upload worked ? I.e. the file in the container was changed ?

yes, upload worked fine.

**Comment by ddaina** [comment]
FYI @vkuznet. Upload to `s3` using `gocurl` worked with a slight modification to this line https://github.com/vkuznet/gocurl/blob/ce93c98d345351fb31e1663121bc569d4ae0977b/main.go#L107 . Detailed explanation can be seen in the comment above: https://github.com/dmwm/CRABServer/issues/6685#issuecomment-871746489

**Comment by belforte** [comment]
@vkuznet for your testing convenience I have prepared a couple of S3 PresignedUrl's which are valid for 1 year. You can reuse them freely and every time the existing file will be overwritten.
I put those here in `curl` format (for my convenience !). I can generate more if you like. You can change the input file name after the `@` but not the filename (`key`) on S3 side.
```
curl -f -v -X POST  -H "User-Agent: myTest" -F "key=valentin/testfile-2.t2" -F "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -F "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -F "file=@/tmp/somedummyfile" "https://s3.cern.ch/crabcache_dev"
```
```
curl -f -v -X POST  -H "User-Agent: myTest" -F "key=valentin/testfile-1.t1" -F "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMS50MSJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODozM1oifQ==" -F "signature=t2wSDVOhukQi/irzja5PLoFpaE4=" -F "file=@/tmp/somedummyfile" "https://s3.cern.ch/crabcache_dev"
```
There are two CRAB Rest API's which you can use to check result:
* this lists file names (indeed its output will not change much)
```
belforte@lxplus780/~> gocurl -url "https://cmsweb-test2.cern.ch/crabserver/dev/cache?subresource=list&username=valentin"  -header "Accept:application/json"
{"result": [
 "st-from-stefano"
]}
```
*   * yes, that name `st-from-stefano` is no good, should have been `test-from-stefano`. Looks like there is a bug (feature?) in python `lstrip` which I use to remove `<username>/` from the S3 key name. It only kicks in with some char (`t`, `e`, `a` e.g.) after the `/` but not e.g with `s`. I will replace `lstrip` in my code with e.g. `split('/')[1:]` :-(

* this lists overall usage in MB (and should change if/as filesize changes)
```
belforte@lxplus780/~> gocurl -url "https://cmsweb-test2.cern.ch/crabserver/dev/cache?subresource=used&username=valentin"  -header "Accept:application/json"
{"result": [
 27
]}
```

**Comment by belforte** [comment]
I fixed the problem with `lstrip` and am building a new tag with it. In the meanwhile I switched cmsweb-test2 to run code from GH master so that it works properly now:
```
belforte@lxplus780/~> gocurl -url "https://cmsweb-test2.cern.ch/crabserver/dev/cache?subresource=list&username=valentin"  -header "Accept:application/json"
{"result": [
 "test-from-stefano"
]}
```

**Comment by vkuznet** [comment]
I fixed the code you pointed out and now it is committed. I put new executable to /afs/cern.ch/user/v/valya/public/gocurl too. But, when I run it I get some error coming from your crabserver, see
```
# curl call
curl -f -X POST  -H "User-Agent: myTest" -F "key=valentin/testfile-2.t2" -F "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -F "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -F "file=@/tmp/vk.test" "https://s3.cern.ch/crabcache_dev"

and it return zero status. But when I call go curl I get this:

./gocurl -method "POST" -header "User-Agent: myTest" -form "key=valentin/testfile-2.t2" -form "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -form "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMS50MSJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODozM1oifQ==" -form "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -form "file=@/tmp/vk.test" -url "https://s3.cern.ch/crabcache_dev"
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>crabcache_dev</BucketName><RequestId>tx000000000000008c57215-0060ddfeed-1c853219-default</RequestId><HostId>1c853219-default-default</HostId></Error>
```

Please try `gocurl` from your end since I think I lack of some access rights to upload the file.

**Comment by belforte** [comment]
thanks Valentin !
If I try, I get exactly same result. And indeed file on S3 is not replaced.
`curl` works, `gocurl` does not.
for odd that it sounds, it seems something different in the way curl and gocurl talk to the remote host.
I see that you are in vacation now, we can surely get back to this in August !

**Comment by belforte** [comment]
from looking at gocurl -v 2 and comparing with curl --trace I suspect that the problem is "file=@/tmp/vk.test", somehow it does not really send the data.
I wonder if in here
```
Content-Disposition: form-data; name="file"

@/tmp/sb.test
--01f0463b358899926c2bbcb9d6630185ea5a127f37aa6f4fb21ee7b891b9--
, error <nil>
```
the message `error <nil>` comes from the gocurl executable, not from the s3.cern.ch server

**Comment by vkuznet** [comment]
@belforte , the `error <nil>` means there is no error (I just print it in case if I'll do see the error).

Meanwhile, I made some additional changes and it would be nice if you'll try it out since I get the same access defined from both `curl` and `gocurl` clients. I think my credentials are expired. Could you please give it a shot. I updated both github tree and put new executable to `/afs/cern.ch/user/v/valya/public/gocurl`. Please post results here.

**Comment by belforte** [comment]
thanks @vkuznet . I still have no idea why you get an error with `curl`, it works finely for me and we are using it currently to upload flles everytime someone issues a crab submit !. You can certainly try a crab submit yourself and then look in crab.log for details.
Anyhow, when I try the latest gcurl I get exactly same behavior as before, ony difference is that if I use -v 2 the full input file is dumped to console as well
```
belforte@lxplus759/~> /afs/cern.ch/user/v/valya/public/gocurl -method "POST" -header "User-Agent: myTest" -form "key=valentin/testfile-2.t2" -form "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -form "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMS50MSJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODozM1oifQ==" -form "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -form "file=@/tmp/vk.test" -url "https://s3.cern.ch/crabcache_dev" 
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><BucketName>crabcache_dev</BucketName><RequestId>tx0000000000000095d6e70-0060e1d68e-1c853219-default</RequestId><HostId>1c853219-default-default</HostId></Error>
belforte@lxplus759/~> 

```

**Comment by belforte** [comment]
Maybe s3.cern.ch is particularly picky about some details of http post protocol. I wil look for a case where se use POST with CRAB so the call goes via cmsweb, and and can start testng that. We do not use forms in CRAB, but ,, it is not so important to solve this right away. It may be easier if you get your own S3 container and further debug with CERN S3 support.

**Comment by belforte** [comment]
this thing is very insersting an very promising for use, but my first priority still is to make CRAB workflows run in python3

**Comment by ddaina** [comment]
@belforte  @vkuznet ,

This command works with go curl.
```
/afs/cern.ch/user/v/valya/public/gocurl -verbose 2  -method "POST" -header "User-Agent:myTest" -form "key=valentin/testfile-2.t2" -form "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -form "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -form "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -form "file=@/tmp/vk.test" -url "https://s3.cern.ch/crabcache_dev"
```
Reason why it did not work for you:

1. somehow when you were trying to upload via `curl`, you had this policy in the command:
```
eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ
```
while when you were trying to upload via `gocurl` policy become (they are different):
```
eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMS50MSJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODozM1oifQ
```
and this policy which was used with `gocurl` was originally meant to be used to upload `"key=valentin/testfile-1.t1"` while you were using it with `"key=valentin/testfile-2.t2"` . See instructions from @belforte: https://github.com/dmwm/CRABServer/issues/6685#issuecomment-872093066

2. Also, notice that in my command i removed space before `myTest` word in this header: `-header "User-Agent:myTest"`, having space in the header results in this error:
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><Message>Key not specified</Message><BucketName>crabcache_dev</BucketName><RequestId>tx00000000000000985eacb-0060e2c2e1-1c850e81-default</RequestId><HostId>1c850e81-default-default</HostId></Error>, error <nil>
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><Message>Key not specified</Message><BucketName>crabcache_dev</BucketName><RequestId>tx00000000000000985eacb-0060e2c2e1-1c850e81-default</RequestId><HostId>1c850e81-default-default</HostId></Error>
```

**Comment by belforte** [comment]
I see, bottom lines:
1. Valentic's code is perfect as usual, thanks !
2. Daina is a genius ! THANKS !!!
3. Stefano is an old dump ass :-)
4. Amazon people be damned in ethernal for creating those stupid string which minimally differ from each other

I have some paperword to do, then will kneel, pour ashed over my head, and verify all of this.

**Comment by belforte** [comment]
quick testing from my self indicates that this message about Kye not specified
```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><Message>Key not specified</Message><BucketName>crabcache_dev</BucketName><RequestId>tx00000000000000985eacb-0060e2c2e1-1c850e81-default</RequestId><HostId>1c850e81-default-default</HostId></Error>, error <nil>
```
appears sort of at random about once every 3 times (by simply repeating seame gocurl) command, regardell of the space before `myTest` in the header.

**Comment by belforte** [comment]
OTOH, uploading same file repeadetely is not use case we have :-). It mau be a feature of S3 protocol tha tha key (i.e. object path in the bucket) is momentarely invalidated while it is bening uploaded.

**Comment by belforte** [comment]
apparetenly about 1/3 of the times it fails also at first attempt.
Needs to be better characterized and reported to Valenting with a way to reproduce it.

OTOH we do no particularly care to use gocurl for S3, as long as curl/wget from operating system work with it (it requires not special authentication, relies only on keys passed on via the pre-signed URL's).

But it may be good to replace the curl that we use on client (in place of WMCore pycurl_manager) so that Valenting can easily add token authentication for any op.sys..
Initial tests were OK, needs to test more.
Open an ad hoc issue ?

**Comment by ddaina** [comment]
@belforte, @vkuznet ,

Back to this odd problem `1 out of 3 times gocurl attempt to upload file to S3 fails`.

As I understood from various pieces of S3 documentation, file or content always has to be the last field in the form submitted. That being said, both `curl`, e.g. [1], and `gocurl` fails when `-F "file=@filename"` is not the last field in the form submitted and both uploads file successfully when `-F "file=@filename"` is the last field in the form.

`Gocurl` data structure which holds form’s key:value pairs https://github.com/vkuznet/gocurl/blob/main/main.go#L105 does not keep insertion order. That being said, sometimes when request is executed, file appears to be the last field in the `form`, the other times - not. And in the latter case upload failures happens.

so even though let's say this is how our `gocurl` request looks like:
```
./main  -verbose 1  -method "POST" -header "User-Agent:myTest" -form "key=valentin/testfile-2.t2" -form "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -form "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -form "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -form "file=@test1" -url "https://s3.cern.ch/crabcache_dev"
```
i.e. `-form "file=@test1" ` provided as the last field, it still randomly fails because as mentioned above insertion order is not preserved

[1] _correct insertion order, i.e. file is the last field in the form:_
```
[ddirmait@lxplus796 gocurl]$ curl -f -v -X POST  -H "User-Agent: myTest" -F "key=valentin/testfile-2.t2" -F "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -F "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" -F "file=@test1" "https://s3.cern.ch/crabcache_dev"
* About to connect() to s3.cern.ch port 443 (#0)
*   Trying 2001:1458:d00:3f::100:2d9...
* Connected to s3.cern.ch (2001:1458:d00:3f::100:2d9) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
* Server certificate:
* 	subject: CN=*.s3.cern.ch,O=Organisation européenne pour la Recherche nucléaire (CERN),L=Meyrin,ST=Genève,C=CH
* 	start date: Mar 10 00:00:00 2021 GMT
* 	expire date: Mar 10 23:59:59 2022 GMT
* 	common name: *.s3.cern.ch
* 	issuer: CN=Sectigo RSA Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> POST /crabcache_dev HTTP/1.1
> Host: s3.cern.ch
> Accept: */*
> User-Agent: myTest
> Content-Length: 833
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------f95c95624ee8
>
< HTTP/1.1 100 Continue
< HTTP/1.1 204 No Content
< Accept-Ranges: bytes
< Bucket: crabcache_dev
< Date: Thu, 30 Sep 2021 07:29:02 GMT
< X-Amz-Request-Id: tx000000000000012b95afb-006155673d-1e049857-default
```
_incorrect insertion order, i.e. file is **not** the last field in the form:_
```
[ddirmait@lxplus796 gocurl]$ curl -f -v -X POST  -H "User-Agent: myTest" -F "key=valentin/testfile-2.t2" -F "AWSAccessKeyId=53ac10f1b45442a2ab374a225b9bf213" -F "policy=eyJjb25kaXRpb25zIjogW3siYnVja2V0IjogImNyYWJjYWNoZV9kZXYifSwgeyJrZXkiOiAidmFsZW50aW4vdGVzdGZpbGUtMi50MiJ9XSwgImV4cGlyYXRpb24iOiAiMjAyMi0wNy0wMVQwODo0ODo1MVoifQ==" -F "file=@test1" -F "signature=6M0Q0Yjvdi5IEFZGSefFqVSMvfA=" "https://s3.cern.ch/crabcache_dev"
* About to connect() to s3.cern.ch port 443 (#0)
*   Trying 2001:1458:d00:3f::100:2bd...
* Connected to s3.cern.ch (2001:1458:d00:3f::100:2bd) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
* Server certificate:
* 	subject: CN=*.s3.cern.ch,O=Organisation européenne pour la Recherche nucléaire (CERN),L=Meyrin,ST=Genève,C=CH
* 	start date: Mar 10 00:00:00 2021 GMT
* 	expire date: Mar 10 23:59:59 2022 GMT
* 	common name: *.s3.cern.ch
* 	issuer: CN=Sectigo RSA Organization Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> POST /crabcache_dev HTTP/1.1
> Host: s3.cern.ch
> Accept: */*
> User-Agent: myTest
> Content-Length: 833
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=----------------------------980657599bd1
>
* Done waiting for 100-continue
< HTTP/1.1 100 Continue
* The requested URL returned error: 400 Bad Request
* Closing connection 0
curl: (22) The requested URL returned error: 400 Bad Request
[ddirmait@lxplus796 gocurl]$
```

**Comment by belforte** [comment]
for @vkuznet convenience I have created a GH issue in gocurl repository pointing to the above description

**Comment by vkuznet** [comment]
@ddaina I applied a change to gocurl, please try out master head (see commit https://github.com/vkuznet/gocurl/commit/cecac925c721f499975307faae37b5b852d7b69b)

**Comment by belforte** [comment]
the work indicated here was actually done by @ddaina with https://github.com/dmwm/CRABServer/pull/6698. Then we diverged into discussing gocurl issues and forgot to close.
