### ISSUE TITLE
use more templates for CI (Jenkins)

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6785]
need to expand template usage so that we can adapt Jenkins tests to multiple CMSSW releases

ideally starting from a CMSSW version the template should automatically pick:
- scram arch
- input dataset
- OS to use for submission 
the CMSSW version should be an env. var. so that in case we can further finely tune in the code like now when we stil vorole check for prod client.

list of CMSSW_version/scram_arch correspondence is in https://github.com/dmwm/CRABServer/issues/6659

I will also add the name of an input dataset, but currently do not have one that will allow to test e.g. use_parents on all.
We may all in all skip some checks for some older releases

Of course when tests needs to be run in SL6 image, we may need to investigate and detail more.

**Comment by belforte** [comment]
had a chat with @ddaina , here's some summary, which goes a bit beyond "templates":
1. Jenkins build-witth-parameter page will offer a pulldown menu with a predefinel list of CMSSW releases
2. each release will be associated (hardcoded) with  a scramarch and inputdataset, see #6659 
3. release, arch, dataset, crab instance, client version will all be env. var. in the eventual test script that will be run, so that we can use them in the test code (e.g. `config.data.inputDataset=os.getenv('inputDataset','somedefaultdset')` )
4. similarly we can e.g. skip use_parent set based on inputdataset name etc. there's quite some ad-hoc coding to do there, but it is not avoidable since we will have to adapt to what's available on disk
5. we want to run client tests in the same environment as users do, ideally "on lxplus", current env. is pretty much like lxplus7, but we need to care about other OS flavors
6. we debated a few possible way to run tests on SL6
    i. create another test container based on SL6 image
    ii. create another test container based on CMSSW CC6 singularity image
   iii. instead of starting a container in an otherwise undefine/undescripted Jenkins slave, make sure that there are slaves which e.g. already run CMSSW singularity image for the needed OS (sort of like grid WN)
    iv. simply do `cmssw-cc6 --command-to-run ./testscript.sh`
7. Daina will review that with Shahzad and figure out the most promising way
8. WIth so many tests possibly running at same time we are now drowning in mails and need better ways to keep track. Daina will look into having each Jenkins test open a GH ticket and track things in there via comment 

Daina, please edit/add as appropriate.

**Comment by ddaina** [comment]
from now on,  once user selects `CMSSW_release` value from a predefined list in `CRABServer_ExecuteTests` test, `inputDataset` and `SCRAM_ARCH` will be set automatically. Configuration map is stored currently in my fork of [CRABServer](https://github.com/ddaina/CRABServer/commit/f37e372a9304709d3b5217047ce84735cd045bb4) repo, will push to official repo later with other changes

**Comment by belforte** [comment]
@ddaina one month after last edit, time to wrap this up. I think we can close. What do you think ?
There are still 3 open tasks in above comment https://github.com/dmwm/CRABServer/issues/6785#issuecomment-932194734
I propose:
 1. skip use_parent, defer to when we have a clear use case and do then
 2. lxplus vs. container vs. singulairyt, I think has been sorted out and done
 3. tracking via GH issues is a different thing, but since you are about to wrap that up I guess we can wait until it is done to cose this as well instead of opening ad hoc issue, but up to you.

**Comment by ddaina** [comment]
@belforte let's close this issue. 
the only thing that is left I believe is `use_parent`, but as you say, lets do it when we have a clear use case
