### ISSUE TITLE
maxEvents is not correctly propagated in PSET by the wrapper

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6795]
from https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/6175/1/1/1/1/1/1/1/1.html

https://cmsweb.cern.ch:8443/scheddmon/0144/cms1038/211004_103055:melu_crab_WJet_pt100to250_MG265_1/job_out.1.0.txt
does indeed show a problem.
quoting from it:
--lastEvent=3000
== JOB AD: CRAB_AlgoArgs = "{"splitOnRun": false, "events_per_job": {"halt_job_on_file_boundaries": false, "events_per_lumi": 100, "algorithm": "EventBased", "applyLumiCorrection": true, "runs": [], "lumis": [], "splitOnRun": false, "events_per_job": 3000}, "halt_job_on_file_boundaries": false}"
Set attribute process.maxEvents.input to cms.untracked.int32(3000)
== CMSSW: %MSG-MG5 number of events requested = 30

the last line is at odd with previous ones and this point to a problem in CRAB.
And indeed its configuration
https://cmsweb.cern.ch:8443/scheddmon/0144/cms1038/211004_103055:melu_crab_WJet_pt100to250_MG265_1/debug/crabConfig.py
has config.Data.unitsPerJob = 3000

I will look into this.

**Comment by belforte** [comment]
PSet after the tweak has
```
process.externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/madgraph/GenValidation/V265_vs_V273/DYMLM_mll10to50/V5_2.7.3
/dyellell4j_mll10to50_5f_LO_MLM_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz'),
    nEvents = cms.untracked.uint32(30),
    numberOfParameters = cms.uint32(1),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh')
)

```

**Comment by belforte** [comment]
maybe something is wrong here
https://github.com/dmwm/CRABServer/blob/614f6148c261cd6215b13a7cd6f7cddde47b633c/scripts/TweakPSet.py#L177-L179

**Comment by belforte** [comment]
looking with `preparelocal` the final PSet has
```
process.externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/UL/13TeV/madgraph/V5_2.6.5/EWparamSync/WJets_FxFx_Ptbin_updated/wellnu012j_wpt-70to280_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz'),
    nEvents = cms.untracked.uint32(30),
    numberOfParameters = cms.uint32(1),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh')
)
```
even if it also has
```
process.maxEvents = cms.untracked.PSet(
    input = cms.untracked.int32(3000),
    output = cms.optional.untracked.allowed(cms.int32,cms.PSet)
)
```
and `PSetTweak.json` has
```
"process.maxEvents.input": "customTypeCms.untracked.int32(3000)
```

**Comment by belforte** [comment]
while running with `preparelocal` the "old" job
I find the same externalLHEProducer config. in the original PsetDUmp.py
but the PSet.pkl after the tweak has
```
process.externalLHEProducer = cms.EDProducer("ExternalLHEProducer",
    args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/UL/13TeV/madgraph/V5_2.6.5/EWparamSync/WJets_FxFx_Ptbin_updated/wellnu012j_wpt-70to280_slc7_amd64_gcc700_CMSSW_10_6_19_tarball.tar.xz'),
    nEvents = cms.untracked.uint32(3000),
    numberOfParameters = cms.uint32(1),
    outputFile = cms.string('cmsgrid_final.lhe'),
    scriptName = cms.FileInPath('GeneratorInterface/LHEInterface/data/run_generic_tarball_cvmfs.sh')
)

```
so "something" was changing the config for externalLHEProducer whcih is not done anymore.

I have not found a reference ot LHEProducer in old nor new WMCore or CRAB.
WIll need to run the old tweak with pdb.

**Comment by belforte** [comment]
I think that the new TweakPset.py needs to call `cmssw_handle_nEvents.py` like in
https://github.com/dmwm/WMCore/blob/85d6d423f0a85fdedf78b65ca8b7b81af9263789/src/python/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py#L448-L465

**Comment by belforte** [comment]
@khurtado @davidlange6 can you quickly think of something else which I may have overlooked and need to call instead ?
So far I am using:

edm_pset_tweak.py
cmssw_enable_lazy_download.py
cmssw_handle_random_seeds.py
cmssw_handle_nEvents.py

**Comment by davidlange6** [comment]
sorry, is the context that your last commit did not fix the problem discussed here?

**Comment by belforte** [comment]
no I think that last commit worked. But am worried that I may still be missing some needed tweak.

**Comment by belforte** [comment]
I mean something that is only important/needed in some use case which I have not tested. I had verified plaint Pythia generation, but not with LHE input. Do not know all things which may be out there :-)

**Comment by davidlange6** [comment]
Not that I would know:) - but perhaps best if you knew and then crosscheck starting from what tweaks were applied before to crab jobs?

**Comment by belforte** [comment]
like if that were ever documented ! well at least now it looks like I know where
to put my hands if issues arise, sort of the best one can hope for
