### ISSUE TITLE
use WebDAV endpoints in stageout check and deal with case it is missing

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6805]

**Comment by belforte** [comment]
Isn't this volume the amount of stageout that we do with gsiftp ~now ? i.e. once last big T2's and FNALLPC has moved ?
Then wqe can measure in ~December/January 

I am wondering if we can fine tune more.
When a job runs at executionSite, it knows if storageSite is davs capable ? Can it know what executionSite is capable of, w/o making queries to Rucio from grid jobs  (e.g. some classAd) ? If it could tell, we could enable direct stageout only where absolutely needed.

**Comment by belforte** [comment]
thanks Stephan ! All good than.

**Comment by stlammel** [comment]
@belforte  Yes, do complain to your Site Support team!
I'll take a look at the two sites and get things corrected. SAM tests still allow fallback to the old config, thus us not having realized this. I ask Hector/Pau to check all sites.
Thanks for your message!
- Stephan

**Comment by stlammel** [comment]
There are 11 sites with missing storage.json, they have been notified.   - Stephan

**Comment by belforte** [comment]
thanks @stlammel and Hector/Pau.
ls  $SITECONFIG_PATH also checked ? I think that current approach based on JOB_CMSSite is reasonably solid atm, and looking in cvmfs only sites where we do not run jobs do not have the storage.json.
But I suspect it may not properly take subsites into account. So I guess I should switch to that once deployment is complete for sites we may actually run jobs at.

**Comment by stlammel** [comment]
@belforte Hallo Stefano,
we are down to three sites. While changing the SAM test, i was reminded that not all
sites will have a storage.json. Storage-less sites will not have a file. For them, the TFC
for the stage-out needs to be taken from the site referenced in site-local-config.xml.
I wanted to make sure you realize this "feature".
Thanks,
- Stephan
