### ISSUE TITLE
Stress test CRAB REST server - investigate http 503 errors

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#6832]
Related to #6708

In order to better understand how to address #6708, we need to replicate these errors in a controlled environment.

The idea is to hit `test1`, `test2` or `testbed` cluster with production-like heavy http calls.

Steps:
- [x] use tcpflow to get a sample of production-like http calls (run tcpflow into a k8s container while submitting and running a task)
- [x] replicate a GET call (light-ish for the server)
- [x] replicate a POST/PUT call (heavier)
  1. parse a tcpflow connection file
  2. use https://github.com/dmwm/CRABClient/tree/master/src/python/CRABAPI, as in https://belforte.web.cern.ch/belforte/misc/TestRest.html
- [x] write a script to run the stress test

**Comment by mapellidario** [comment]
After some discussion on https://github.com/dmwm/CMSKubernetes/pull/950 , I have some new ideas on how to address this issue.

It mainly boils down to how to use `hey`: https://cms-http-group.docs.cern.ch/k8s_cluster/benchmark/#usage-of-hey-tool , which with some tweaks from Valentin is perfectly suited for our purposes.

example on usage

```bash
#setup
ssh lxplus
voms-proxy-init --rfc --voms cms -valid 192:00
export X509_USER_PROXY=/tmp/x509up_u$UID

# simple test
/cvmfs/cms.cern.ch/cmsmon/hey \
-disable-keepalive -T "*/*" -A "*/*" \
-N 1 \
-n 100 -c 10 \
https://cmsweb-testbed.cern.ch/crabserver/preprod/info
```

How to devise a proper test:

```bash
# multiple tests randomizing the URL across requests
cat urls.txt 
> https://cmsweb-testbed.cern.ch:8443/crabserver/preprod/info
> https://cmsweb-test1.cern.ch:8443/crabserver/dev/info

/cvmfs/cms.cern.ch/cmsmon/hey -disable-keepalive -T "*/*" -A "*/*" -N 10 -n 10 -c 5 -o csv -U ./urls.txt
```

Plan for stressing the REST server via concurrent heavy GET requests (`filemetadata` api endpoint):

- [ ] get a list of task currently in the system. I still have to figure out why, some tweaking with crab api may be necessary
- [ ] use list of tasks to create a write in `./urls.txt` a list of urls of the form `https://cmsweb-testbed.cern.ch:8443/crabserver/preprod/filemetadata?taskname=<taskname>&filetype=EDM`
- [ ] run `/cvmfs/cms.cern.ch/cmsmon/hey -disable-keepalive -T "*/*" -A "*/*" -N 10 -n 10 -c 5 -o csv -U ./urls.txt`

**Comment by mapellidario** [comment]
#### API that does not talk to DB: harder than it seems/looks

I tried adding a new endpoint that does not require the oracle DB, at `/info?subresource=infonodb` [1], however it still talks to the DB before performing the request [2], in particular this function is executed at every request:

https://github.com/dmwm/WMCore/blob/3e1eaf01792340fd8db9f07c1591b92dafff7741/src/python/WMCore/REST/Server.py#L1531

If we really want an API that does not require the DB, we will have to tinker a bit with WMCore/REST...

[1] using

```diff
diff --git a/src/python/CRABInterface/RESTServerInfo.py b/src/python/CRABInterface/RESTServerInfo.py
index 2cf86489..ad2d3c25 100644
--- a/src/python/CRABInterface/RESTServerInfo.py
+++ b/src/python/CRABInterface/RESTServerInfo.py
@@ -39,6 +39,9 @@ class RESTServerInfo(RESTEntity):
             next(self.api.query(None, None, "select NULL from DUAL")) #Checking database connection
             return [{"crabserver":"Welcome","version":__version__}]

+    def infonodb(self, **keys):
+        return [{"crabserver":"Welcome","version":__version__}]
+
     @conn_handler(services=['centralconfig'])
     def delegatedn(self, **kwargs):
         yield {'services': self.centralcfg.centralconfig['delegate-dn']}
diff --git a/src/python/CRABInterface/Regexps.py b/src/python/CRABInterface/Regexps.py
index 308e8c50..126e2705 100644
--- a/src/python/CRABInterface/Regexps.py
+++ b/src/python/CRABInterface/Regexps.py
@@ -83,7 +83,7 @@ RX_CERT = re.compile(r'^[-]{5}BEGIN CERTIFICATE[-]{5}[\w\W]+[-]{5}END CERTIFICAT
 RX_SUBRESTAT = re.compile(r"^(errors|report2|logs|data|logs2|data2|resubmit|resubmit2|proceed|publicationstatus|taskads)$")

 #subresources of the ServerInfo (/info) and Task (/task) resources
-RX_SUBRES_SI = re.compile(r"^(delegatedn|backendurls|version|bannedoutdest|scheddaddress|ignlocalityblacklist)$")
+RX_SUBRES_SI = re.compile(r"^(infonodb|delegatedn|backendurls|version|bannedoutdest|scheddaddress|ignlocalityblacklist)$")
 RX_SUBRES_TASK = re.compile(r"^(allinfo|allusers|summary|search|taskbystatus|getpublishurl|addwarning|deletewarnings|addwebdir|addoutputdatasets|addddmreqid|webdir|webdirprx|counttasksbystatus|lastfailures|updateschedd|updatepublicationtime)$")
```

[2] 

```
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy ENTER cmsweb_analysis_dev@int2r CRABInterface.RESTBaseAPI.RESTBaseAPI (GET dev info) inuse=0 idle=1
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy (previously cBOPeqoHLjJs) connected, client: 19.11.0.0.0, server: 19.13.0.0.0, stmtcache: 50
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy ping
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy check [select sysdate from dual]
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy connection established
[11/May/2022:18:05:58] crabserver-868d9c5dfb-cpr29 127.0.0.1 "GET /crabserver/dev/info?subresource=infonodb HTTP/1.1" 200 OK [data: 319 in 69 out 3171 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ]
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy release with rollback
[11/May/2022:18:05:58]  RESTSQL:abgjYZrUnsFy RELEASED cmsweb_analysis_dev@int2r timeout=300 inuse=0 idle=1

```

**Comment by novicecpp** [comment]
Something like wishlist I want to do,
- [ ] Using curl inside pod to test 2 endpoint
  -  endpoint that does not interact with DB (ex. /cache). As Dario metion above, it still connect to db (check connectivity) when request serve by REST.
- [ ] Simple ORACLE client scripts connect to dev/preprod/prod that can run inside pod, to test connectivity with database.

**Comment by mapellidario** [comment]
I am building a new crabserver image with this private WMCore tag: https://github.com/mapellidario/WMCore/releases/tag/2.0.3.pre7crab

Starting from the currnt masters, edit `crabserver.spec` (cmsdist)

```diff
diff --git a/crabserver.spec b/crabserver.spec
index 37100b6b7..a29429a90 100644
--- a/crabserver.spec
+++ b/crabserver.spec
@@ -1,4 +1,4 @@
-### RPM cms crabserver v3.220301
+### RPM cms crabserver v3.220507

 # This specfile accepts both following types of tags:
 # - v3.210701 -> builds py2 environment
@@ -11,8 +11,8 @@
 %define webdoc_files %{installroot}/%{pkgrel}/doc/

 %define python_runtime %(echo python3)
-%define wmcrepo dmwm
-%define wmcver 1.5.7
+%define wmcrepo mapellidario
+%define wmcver  2.0.3.pre7crab
 %define crabrepo dmwm
 Requires: python3 py3-cherrypy py3-pycurl py3-cx-oracle py3-memory-profiler
 Requires: py3-retry py3-boto3 py3-future py3-pyOpenSSL py3-htcondor rotatelogs jemalloc
```

- build the specfile with `pkgtools/cmsBuild -c cmsdist --repository comp -a slc7_amd64_gcc630 --builders 8 -j 5 --work-dir w --upload-user=$USER upload comp`

- (still to complete, i will update this comment as i progress)

**Comment by mapellidario** [comment]
### monitoring: use `cpy_exporter`

Currently, when i try to retrieve the data with

```plaintext
[_crabserver@crabserver-67c5b76d84-cptrb data]$ cmsweb-ping --url=http://localhost:8270/crabserver/stats --authz=/etc/hmac/hmac -verbose 1
```

i get

```plaintext
[13/May/2022:14:50:13] HTTP
Traceback (most recent call last):
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 794, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
[13/May/2022:14:50:13] HTTP
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:8270
  USER-AGENT: Go-http-client/1.1
  ACCEPT: */*
  CMS-AUTH-STATUS: OK
  CMS-AUTHN-HMAC: 0af6ab4752bf1591491b355004f941ce0bf5bff5
  CMS-AUTHN-LOGIN: ping-monitor
  CMS-AUTHN-METHOD: PingMonitor
  CMS-AUTHN-NAME: Ping Monitor
  ACCEPT-ENCODING: gzip
[13/May/2022:14:50:13] crabserver-67c5b76d84-cptrb 127.0.0.1 "GET /crabserver/stats HTTP/1.1" 500 Internal Server Error [data: 295 in 824 out 1689 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ]
```

so there is no trivial solution, we may need to get the hands a bit dirty inside WMCore...

**Comment by belforte** [comment]
Maybe need to specify JSON? Sent from. Stefano's phoneOn May 13, 2022 14:54, Dario Mapelli ***@***.***> wrote:
monitoring: use cpy_exporter
Currently, when i try to retrieve the data with
***@***.*** data]$ cmsweb-ping --url=http://localhost:8270/crabserver/stats --authz=/etc/hmac/hmac -verbose 1

i get
[13/May/2022:14:50:13] HTTP
Traceback (most recent call last):
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/data/srv/HG2204f-6c487c159e288d0e44f529d975910555/sw.crab_master/slc7_amd64_gcc630/external/py3-cherrypy/17.4.0-comp2/lib/python3.8/site-packages/cherrypy/_cprequest.py", line 794, in __set__
    raise ValueError(self.unicode_err)
ValueError: Page handlers MUST return bytes. Use tools.encode if you wish to return unicode.
[13/May/2022:14:50:13] HTTP
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:8270
  USER-AGENT: Go-http-client/1.1
  ACCEPT: */*
  CMS-AUTH-STATUS: OK
  CMS-AUTHN-HMAC: 0af6ab4752bf1591491b355004f941ce0bf5bff5
  CMS-AUTHN-LOGIN: ping-monitor
  CMS-AUTHN-METHOD: PingMonitor
  CMS-AUTHN-NAME: Ping Monitor
  ACCEPT-ENCODING: gzip
[13/May/2022:14:50:13] crabserver-67c5b76d84-cptrb 127.0.0.1 "GET /crabserver/stats HTTP/1.1" 500 Internal Server Error [data: 295 in 824 out 1689 us ] [auth: OK "" "" ] [ref: "" "Go-http-client/1.1" ]

so there is no trivial solution, we may need to get the hands a bit dirty inside WMCore...

**Comment by mapellidario** [comment]
Our latest ideas about using the `cpy_exporter` should be superseeded by https://github.com/dmwm/CRABServer/issues/7515.

Moreover, I added some time ago a script to make many concurrent post requests: https://github.com/dmwm/CRABServer/blob/master/scripts/Utils/StressTest_REST_POST.py (yes i know, past me chose a very bad name)

As discussed in a private chat, this issue can be closed, eventually
