### ISSUE TITLE
add py3 to spec file for TW/Pub

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6882]
do the same as just done for crabserver for crabtaskworker.spec, so that we can build TaskWorker and Publisher in python3 env.

**Comment by mapellidario** [comment]
work being traked in: https://github.com/cms-sw/cmsdist/pull/7479

**Comment by belforte** [comment]
@mapellidario should we close this as "done" ? and possibly track ldap thing in a separate one ?

**Comment by mapellidario** [comment]
Or we can just update this one? I don't know, it is the same for me

**Comment by belforte** [comment]
closing this as done.
