### ISSUE TITLE
make TaskWorker run in Py3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6899]
an amazingly small set of changes seems sufficient, see https://github.com/belforte/CRABServer/tree/make-tw-work-in-py3

* https://github.com/dmwm/CRABServer/commit/5c2110ae28f8012450b4a9c940a380afc25205d9
* https://github.com/dmwm/CRABServer/commit/0bd861dad1644153c59c2a250ad675d80d344cdd

besides the obvious "use py3"
* https://github.com/dmwm/CRABServer/commit/83e1d6881d36faf1bcc5eb7cdd0c8fbb5f3d8f37
* https://github.com/dmwm/CRABServer/commit/bccb9750a18d783ba176e3c19e6de226d7ad3d9d

and the temporary workardound for missing ldap in the build ref #6898 
* https://github.com/dmwm/CRABServer/commit/ccc9b49e8c3e5d47ac46d02f908cfa70edd8ded4
(code was already surviving ldap failure, but not import failure, trivial change)

But now I am stuck in handling output of AuthenticatedSuprocess called in
https://github.com/dmwm/CRABServer/blob/a5cb8ff990424298eee12ab55832c7af5fb75b11/src/python/TaskWorker/Actions/DagmanSubmitter.py#L523-L534
The `rpipe` variable there has type  `'_io.TextIOWrapper' ` and even if I set `pickleOut=False` I can't find a way to read it into some string.
Maybe we need to hands into the forking code, untouched sine Brian wrote it and never understood by me !
https://github.com/dmwm/CRABServer/blob/a5cb8ff990424298eee12ab55832c7af5fb75b11/src/python/HTCondorUtils.py#L42

The same function is present in WMCore
https://github.com/dmwm/WMCore/blob/15067b9916fbd01b6599d5329aa6825940654bf6/src/python/WMCore/Services/PyCondor/PyCondorUtils.py#L32
 but not referenced anywhere, so there's no working example to go through

**Comment by belforte** [comment]
@mapellidario once you are done with all the work which you have currently in your hand, I think I will need your help here. But let's do one thing at a time. Maybe I find a solution in google.

**Comment by mapellidario** [comment]
After a quick read, I have a suggestion. Maybe we want to open the files that `AuthenticatedSubprocess` uses in binary mode by changing

https://github.com/dmwm/CRABServer/blob/a5cb8ff990424298eee12ab55832c7af5fb75b11/src/python/HTCondorUtils.py#L53-L54

with

```diff

- self.rpipe = os.fdopen(self.r, 'r') 
+ self.rpipe = os.fdopen(self.r, 'rb') 
- self.wpipe = os.fdopen(self.w, 'w') 
+ self.wpipe = os.fdopen(self.w, 'wb') 
```

**Comment by belforte** [comment]
i had briefly thought about that Dario,  but the fact that things still file if pickle is switched off makes it doubtful that it works. I am rather thinking of replaing the obscure AuthenticatedSubprocess with a simpler context manager used only to setup the needed env. and call HTCondor API directly. At first sight all I loose the timeout, but  there should be ways to implement it anyhow, esp. in python3.

**Comment by belforte** [comment]
I stand corrected. Thanks @mapellidario , you fix work. I had got confused between a file descriptor and a string and did a mess when trying to bypass pickle.
Now I can submit tasks !

**Comment by mapellidario** [comment]
Wow! This is really promising! thanks for checking!

**Comment by belforte** [comment]
this should be closed when we merge https://github.com/dmwm/CRABServer/pull/6901

**Comment by belforte** [comment]
closed via #6901

**Comment by belforte** [comment]
serendipitous finding:
```
  File "/data/repos/CRABServer/src/python/HTCondorUtils.py", line 74, in __exit__
    self.wpipe.write("OK")
TypeError: a bytes-like object is required, not 'str'
```
a fall out of this fix https://github.com/dmwm/CRABServer/issues/6899#issuecomment-986828183
since we open pipes in binary mode for pickle, this line also needs changing
https://github.com/dmwm/CRABServer/blob/e74b065b57906ddbe53f399097ff59a6e8b245e5/src/python/HTCondorUtils.py#L74

**Comment by belforte** [comment]
also, we need to always set `pickle=True` when calling `authentictedSubprocess` else things fails in
https://github.com/dmwm/CRABServer/blob/e74b065b57906ddbe53f399097ff59a6e8b245e5/src/python/TaskWorker/Actions/DagmanKiller.py#L95-L101
because `results` is `b'OK'`, not `"OK"`
Or (more elegantly) write bytes/string in the pipe depending on pickle being used or not.

**Comment by belforte** [comment]
hmm... nope. The code was alreayd writing byte/strings depending on pickle and that is what was causing previous error.
I seem to get success by opening pipes in binary/non=ginary mode if usePickle is true/false.

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6927
