### ISSUE TITLE
TW still fails in py3 inside WMCore/Credential

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6912]
I do not know why this did not surface earlier... anyhow looks pretty "standard"

```   output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
  File "/data/srv/TaskManager/py3.211213-b444c6ef2cda45af29ca0fe543718abe/slc7_amd64_gcc630/cms/crabtaskworker/py3.211213-b444c6ef2cda45af29ca0fe543718abe/lib/python3.8/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 80, in execute
    (userproxy, usergroups) = self.tryProxyLogon(proxycfg=proxycfg)
  File "/data/srv/TaskManager/py3.211213-b444c6ef2cda45af29ca0fe543718abe/slc7_amd64_gcc630/cms/crabtaskworker/py3.211213-b444c6ef2cda45af29ca0fe543718abe/lib/python3.8/site-packages/TaskWorker/Actions/MyProxyLogon.py", line 35, in tryProxyLogon
    userproxy = proxy.getProxyFilename(serverRenewer=True)  # this only returns a filename
  File "/data/srv/TaskManager/py3.211213-b444c6ef2cda45af29ca0fe543718abe/slc7_amd64_gcc630/cms/crabtaskworker/py3.211213-b444c6ef2cda45af29ca0fe543718abe/lib/python3.8/site-packages/WMCore/Credential/Proxy.py", line 263, in getProxyFilename
    proxyFilename = os.path.join(self.credServerPath, sha1(
TypeError: Unicode-objects must be encoded before hashing


```

**Comment by amaltaro** [comment]
https://github.com/dmwm/WMCore/issues/10912
?

**Comment by belforte** [comment]
indeed I had fixed it in my private fork
https://github.com/belforte/WMCore/commit/1be8e3c564f39f67eaa948a758a82b0b734811c8
I guess I failed to communicate this to @mapellidario in order to be added to the branch which we use now in the build. Sorry Dario, another build is needed.

**Comment by belforte** [comment]
yes Alan. Sorry, my memory is so bad :-( Anyhow, just a matter of "being thorough and careful"

**Comment by belforte** [comment]
@mapellidario I have switched crab-dev-tw01 to run from GH using my WMCore fork above and CRAB py3.21213 and it is OK now. (yeah.. I have also hacked cmsweb-test1 a bit slipping my personal proxy in to avoid the expired hostcert... good for 7 days or next pod restart, whichever comes first).

**Comment by belforte** [comment]
Dario, I assign this to you as a reminder. You can close once you have a build with the fix.

**Comment by belforte** [comment]
spec file with a working build was created via https://github.com/cms-sw/cmsdist/pull/7502
@mapellidario can we close ? Or do you want to keep it open to remind us what to check when we'll want to switch back to to dmwm/WMCore repository ?
There are a few things which now you have fixed only in your branch besides this, maybe better to keep an ad hoc issue ?

**Comment by mapellidario** [comment]
I think that we can close this issue. 

in our private branch at the moment we have three changes:

- (TW) same commit as in https://github.com/dmwm/WMCore/pull/10918, which has been merged by Alan. If we move back to building TW with dmwm/WMCore at their next release, then we will be fine.
- (REST) same commit as https://github.com/dmwm/WMCore/pull/10917, which has been merged, so  If we move back to building crabserver with dmwm/WMCore at their next release, then we will be fine.
- (REST) https://github.com/mapellidario/WMCore/commit/23fef9beb426c3600ca8fa9a7c3687db4cb0f193 which raises an exception when we have unexpected types being inserted into the DB. I would keep this change into our crabserver build for as long as reasonably possible.

Therefore 
- `crabtaskworker.spec`: we can switch to the new `dmwm/WMCore` version, when they release a new one.
- `crabserver.spec` : I would continue using my own private branch

**Comment by belforte** [comment]
thanks Dario, What  about point 4 still open in https://github.com/dmwm/CRABServer/issues/6830 ?
I think you mentioned that it was something in WMCore, can you add some comment there ?
![Screenshot from 2021-12-16 16-10-01](https://user-images.githubusercontent.com/1837785/146397238-866bf1d9-5a74-42e9-8092-c7cc413fdefe.png)
