### ISSUE TITLE
DagmanResubmitter fails in py3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6918]
from 211214_160639:cmsbot_crab_20211214_170637 via
https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/493/

```
				  File "/data/srv/TaskManager/py3.211214-92571258f517766654e1f9de5b749eae/slc7_amd64_gcc630/cms/crabtaskworker/py3.211214-92571258f517766654e1f9de5b749eae/lib/python3.8/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 98, in executeInternal
				    if isinstance(p, unicode):
				NameError: name 'unicode' is not defined
				

```

**Comment by belforte** [comment]
full dump
```
belforte@lxplus766/bot> crab status  crab_20211214_170637/
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20211214_170637
Task name:			211214_160639:cmsbot_crab_20211214_170637
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-preprod-tw01
Status on the CRAB server:	RESUBMITFAILED
Task URL to use for HELP:	https://cmsweb-testbed.cern.ch/crabserver/ui/task/211214_160639%3Acmsbot_crab_20211214_170637
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=cmsbot&var-task=211214_160639%3Acmsbot_crab_20211214_170637&from=1639494399000&to=now
Warning:			The following sites appear in both the user site blacklist and whitelist: [u'T2_ES_IFCA']. Since the whitelist has precedence, these sites are not considered in the blacklist.
Failure message from server:	Problem handling 211214_160639:cmsbot_crab_20211214_170637 because of name 'unicode' is not defined failure, traceback follows
				Traceback (most recent call last):
				  File "/data/srv/TaskManager/py3.211214-92571258f517766654e1f9de5b749eae/slc7_amd64_gcc630/cms/crabtaskworker/py3.211214-92571258f517766654e1f9de5b749eae/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 80, in executeAction
				    output = work.execute(nextinput, task=self._task, tempDir=self.tempDir)
				  File "/data/srv/TaskManager/py3.211214-92571258f517766654e1f9de5b749eae/slc7_amd64_gcc630/cms/crabtaskworker/py3.211214-92571258f517766654e1f9de5b749eae/lib/python3.8/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 165, in execute
				    self.executeInternal(*args, **kwargs)
				  File "/data/srv/TaskManager/py3.211214-92571258f517766654e1f9de5b749eae/slc7_amd64_gcc630/cms/crabtaskworker/py3.211214-92571258f517766654e1f9de5b749eae/lib/python3.8/site-packages/TaskWorker/Actions/DagmanResubmitter.py", line 98, in executeInternal
				    if isinstance(p, unicode):
				NameError: name 'unicode' is not defined
				
Status on the scheduler:	FAILED

Jobs status:                    failed       		  2.0% (  2/100)
				finished     		 98.0% ( 98/100)

Publication status of 1 dataset(s):	done         		 98.0% ( 98/100)
(from CRAB internal bookkeeping in transferdb)
					unsubmitted  		  2.0% (  2/100)

Output dataset:			/GenericTTbar/cmsbot-autotest-1639497997-94ba0e06145abd65ccb1d21786dc7e1d/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FGenericTTbar%2Fcmsbot-autotest-1639497997-94ba0e06145abd65ccb1d21786dc7e1d%2FUSER&instance=prod%2Fphys03

Error Summary: (use crab status --verboseErrors for details about the errors)

  2 jobs failed with exit code 50664

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.

Warning: the average jobs CPU efficiency is less than 50%, please consider to improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task

Summary of run jobs:
 * Memory: 25MB min, 746MB max, 231MB ave
 * Runtime: 0:01:03 min, 1:00:04 max, 0:04:53 ave
 * CPU eff: 0% min, 23% max, 4% ave
 * Waste: 8:11:52 (50% of total)

Log file is /afs/cern.ch/work/b/belforte/CRAB3/TC3/dbg/bot/crab_20211214_170637/crab.log
belforte@lxplus766/bot> 

```

**Comment by belforte** [comment]
Dario, please be aware that I do not understand what the affected code really is about, that talking about htcondor vs. unicode is quite suspicious and I do not see why we should have anything different from when plain `submit` is done. Or in any case why we can't simply enforce ASCII everywhere in these params. It is also possible that modern HTCondor just takes unicode in the py3 python bindings.  Also it is curious that the similar task https://cmsweb-testbed.cern.ch/crabserver/ui/task/211214_160627%3Acmsbot_crab_20211214_170622 can be resubmitted w/o problems.
So, if you see a simple way to deal with this w/o caring what the code does, OK. Otherwise we need to look at it together and figure out what exactly one needs to achieve.

The resubmission in CRAB is indeed a tricky and poorly understood business waiting for a full rewrite : #6270

**Comment by mapellidario** [comment]
This issue was spotted by `futurize` and is one of the suggested changes in this branch https://github.com/dmwm/CRABServer/compare/python3...mapellidario:python3-sugggestions-futurize

What I propose is that we stop bug-driven modernization for the time being (1d? 1w? i do not know), i go back and check every suggestion from futurize in the aforementioned branch, make an appropriate number of PRs (maybe one will be enough, maybe more will be needed), lastly we resume the bug-hunting.

**Comment by belforte** [comment]
OK. we can live with 'crab resubmit fails' in preprod for a while. Pleae go ahead with that.  But let's be 'cricital', we do not care for py2 compatibility so no need for overriding builtins etc. hopefully we forget all about Python2 asap.
We will need a way to ensure that client and serverUtilities stay py2 compatible though, but the idea there is to keep those as simple as possible. We may even move some things out of serverUtilities if they are not used by Client, will make things easier to understand and support.

**Comment by mapellidario** [comment]
This was addressed in #6921. We run some tests in preprod the last couple of days and one of the tasks from the [last battery of tests](https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_CheckTestResults/421/) had some 15 jobs that have been resubmitted: 
- `220105_172231:cmsbot_crab_20220105_182226`, [grafana](https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&from=now-2d&to=now&var-site=All&var-user=cmsbot&var-task=220105_172231:cmsbot_crab_20220105_182226&var-schedd=059&var-cmsUserId=cms1866)

@belforte do you think we can close this? do i understand correctly that to test this problem has been fixed, it is enough to see that failed jobs have been resubmitted?

**Comment by belforte** [comment]
yes, if `crab resubmit` does resubmit the failed jobs, we are OK. I think we can close

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6921
