### ISSUE TITLE
[cleanup] Make sure that files are closed after being opened.

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#6934]
### description

During the python3 migration, we notices a couple of occurrences of files that are opened, read but not closed.

A couple of examples are

  - https://github.com/dmwm/CRABServer/blob/0b1c2ec6bbe34f81460403bc7b604a5085c3f4ca/scripts/cmscp.py#L913 
  - https://github.com/dmwm/CRABServer/blob/0b1c2ec6bbe34f81460403bc7b604a5085c3f4ca/src/python/CMSGroupMapper.py#L78

### desired solution

We should make sure that every file is opened within a context manager, so that we are sure it is going to be properly closed, eventually.

**Comment by belforte** [comment]
of course `cmscp.py` is a script which is executed once in per job in the WorkerNode. So everything is closed when it exits. ANd besides this, `cmscp.py` could surely use a good cleanup and refactoring. 
But we need to be very careful with persistent processes which may result in file descriptor leaks.

**Comment by belforte** [comment]
pylint now poiints out those cases
