### ISSUE TITLE
assess compatibility of py3 branch with current prod

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6938]
Need to figure out a plan for migration production to the python3 version of TW/Pub/REST.
Whenever we deploy a new version, there will be task in the system running with TW code
from older TW version and records in the DB written with previous version of TW/Pub/Client/REST
which will need to be read via new code.
So we need to understand what is compatible with what and make a proper plan both
of testing and of deployment.

@mapellidario it wiill take some time and quite some testing to figure out, but I think it will be good that you look at this and so are forced to become aware of the various pieces and how they communicate.
Of course one can simply use preprod to test various migration scenarios, but unless we put dedicated thought it is very easy to overlook some compatibility check becasue it is not easy to have in preprod tasks which "do things" both before and after servers are migrated (e.g. publish some files with one version and of the publisher and switch to new version before they complete and/or multiply by the possible REST changes).

**Comment by mapellidario** [comment]
### Facts and prerequisites.

We want to deploy the following services in a py3 env:

- crabserver: `k8s`, `cmsweb`
- TW: `docker` inside our own VM `crab-prod-tw01`
- PUB: `docker` inside our own VM `crab-prod-tw01`

? do we need to target the migration of any other script/program?

We need the system to keep running while we perform the migration. 

- We can not afford to drain the system
- We want running tasks submitted with py2 REST to be handled correctly by py3 REST/TW after the migration.
- we do not want to stop submissions during the migration -> do not switch off crabserver

### plan

My idea for the migration is:

1. stop the TW py2 and PUB py2
2. k8s rollout of crabserver py3
3. deploy TW py3 and PUB py3

pros:

- we will not have to deal with keeping crabserver-py3 compatible with TW-py2 and PUB-py2
- we will not have to make TW-py3 work with crabserver-py2

cons:

- TW and PUB will be down for some ~5min (enough time to make sure that all the crabserver-py2 pods are destroyed)

### tests

I want to perform at least once the migration in preprod, as an exercise.

working full py2 stack to preprod:
- check that full py2 stack works
  - deploy full py2 stack
  - submit tasks and check they succeed

working full py3 stack works as expected
- check that the full py3 stack is backward compatible
    - deploy full py2 stack
    - submit tasks (short and long, data analysis and mc generation)
    - while they run, deploy full py3 stack
    - check that all the submitted tasks succeed
    - repeat the previous steps until we feel comfortable. more info at (1)
- check that the full py3 stack works
    - deploy full py3 stack
    - submit tasks and check they succeed


(1) The most critical and unknown part of the previous test schedule is how the running tasks behave when chaning the TW version:

- (crabserver) make sure that the k8s rollot work as expecetd
    - launch a script that submit the same task continuously for 5min]
    - with a replica=2, do a k8s rollout to the new image
    - check that all submissions are ok
- (TW) make sure that running jobs of running tasks are not lost
    - submit a task with long jobs.
    - when some jobs are in running, deploy the new version
    - check that the task succeeds
- (TW) make sure that transferring jobs are not lost 
    - submit a task with large output (? do we have any?).
    - when some jobs are in transferring, deploy the new version
    - check that the task succeeds
- (TW) ? is it possible that the postJob trigger that starts the transferring is lost when we switch off/on the TW?
- (TW) ? is it there any potential downside to not having any TW running for ~5min?
-  (PUB) make sure that updating the publisher is transparent
    - ? how can we check that the publisher started working on a task? How long does it usually take to publish the output? ~1min per task, ~1m per file, ~10min per file? (I guess I have no detailed idea of how the publishing works)

? do we need more tests for updating the TW?

**Comment by belforte** [comment]
test1. new rest with old tw/pub.

**Comment by mapellidario** [comment]
Currently, the preprod instance is running: 

- REST: `registry.cern.ch/cmsweb/crabserver:py3.220105.nodbs`
- TW: `v3.211008`
- PUB: `v3.211111`

Successfull tasks:
- `220107_165040:dmapelli_crab_20220107_175035` 

Launched, to be monitored:
- https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/501/artifact/submitted_tasks_TS/*view*/

**Comment by mapellidario** [comment]
`test3`.

- i deployed full py2 stack
- i submitted `220110_163256:dmapelli_crab_20220110_173252` and let it run a bit (34 jobs in total)
- when it will start publishing data, i will deply python3 REST
- final status:
  - jobs finished ??
  - published: done ??

#### version details

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.211008`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220105.nodbs`

**Comment by mapellidario** [comment]
`test4`: (in progress)

#### actions

- i deployed full py2 stack
- i submitted `??` and let it run a bit (34 jobs in total)
- I deployed full python3 stack when status was
  - jobs: ??/34 finished, ??/34 transferring
  - published: ??/34 done, ??/34 acquired, ??/34 unsubmitted
- final status:
  - jobs finished ??/34 finished
  - published: ??/24 done, ??/34 failed
  - 
#### version details

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.211008`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220105.nodbs`
- py3 TW: `py3.220105`
- py3 PUB: `py3.220105`

**Comment by mapellidario** [comment]
`test3b`: in progress 

same as test3, test again with more logging

#### actions

- i deployed full py2 stack
- i submitted `220112_122438:dmapelli_crab_20220112_132432` and let it run a bit (34 jobs in total)
- I deployed python3 REST when status was
  - jobs: xx/34 finished, x/34 transferring
  - published: xx/34 done, x/34 acquired, x/34 unsubmitted
- final status:
  - jobs finished xx/34 finished
  - published: xx/24 done, xx/34 failed. (DAS shows xx files in the published dataset)

**Comment by mapellidario** [comment]
### test 

`test5`

- i deployed mixed py2 py3 stack (REST py3 (with these changes applied on top python3...mapellidario:6938-test3b-log0), TW py2, PUB py2)
- i submitted `220114_152316:dmapelli_crab_20220114_162313` (data analysis) and let it run a bit (10 jobs in total)
- I deployed TW py3, PUB py3 when status was
  - jobs: ???/10 finished, ??/10 transferring
  - published: ???/10 done, ???/10 failed, ???/10 unsubmitted, ???/10 new
- final status:
  - jobs finished ???/10 finished
  - published: ???/10 done, ???/10 failed

### versions

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.211008`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220105.nodbs`
- py3 TW: `py3.220105`
- py3 PUB: `py3.220105`

**Comment by mapellidario** [comment]
### test

`test6`: in progress

- i deployed full py3 stack
- i submitted `220114_193957:dmapelli_crab_20220114_203953` (data analysis) 
- final status:
  - jobs finished ??/74 finished
  - published: ??/74 done, ??/74 failed

**Comment by mapellidario** [comment]
#### `test4b`: success

actions

- i deployed full py2 stack
- i submitted `220117_152046:dmapelli_crab_20220117_162038` and let it run a bit (100 jobs in total)
- I deployed full python3 stack when status was
  - jobs: 1/100 running, 99/100 transferring
  - published: 00/100 done, 00/100 acquired, 00/100 unsubmitted
- final status:
  - jobs finished 100/100 finished
  - published: 100/100 done, 0/100 failed
  
#### `test4c`: success

actions

- i deployed full py2 stack
- i submitted `220117_151925:dmapelli_crab_20220117_161921` and let it run a bit (76 jobs in total)
- I deployed full python3 stack when status was
  - jobs: 6/76 running, 70/76 transferring
  - published: 00/76 done, 00/76 acquired, 00/76 unsubmitted
- final status:
  - jobs finished 76/76 finished
  - published: 76/76 done, 0/76 failed

#### version details

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.211008`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220105.nodbs`
- py3 TW: `py3.220117`
- py3 PUB: `py3.220117`

**Comment by mapellidario** [comment]
#### `test7a` : in progress

`test4`: success

- i deployed mixed stack: REST-py3, TW-py2, PUB-py2
- i submitted `220120_161838:dmapelli_crab_20220120_171834` and let it run a bit (34 jobs in total)
- I deployed full python2 stack when status was
  - jobs: ??/34 running, ??/34 transferring
  - published: 00/34 done, 00/34 acquired, 00/34 unsubmitted
- final status:
  - jobs finished 34/34 finished
  - published: 34/34 done, 0/34 failed
 
#### `test7b` : in progress

- i deployed mixed stack: REST-py3, TW-py2, PUB-py2
- i submitted `???` and let it run a bit (34 jobs in total)
- I deployed full python2 stack when status was
  - jobs: 00/34 running, 00/34 transferring, 34/34 finished
  - published: 00/34 done, 00/34 acquired, 34/34 new, 00/34 unsubmitted
- final status:
  - jobs finished 34/34 finished
  - published: 34/34 done, 0/34 failed

#### version details

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.211008`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220120`
- py3 TW: `py3.220105`
- py3 PUB: `py3.220105`

**Comment by mapellidario** [comment]
#### `test8a` : in progress

- i deployed mixed stack: REST-py3, TW-py2, PUB-py3
- i submitted `220121_155441:dmapelli_crab_20220121_165437` and let it run a bit (34 jobs in total)
- I deployed REST-py3, TW-py2, PUB-py2 stack when status was (x->y: x == just before deploy, y== after deploy finished)
  - jobs: ????/34 running, ?????/34 transferring, ????/34 finished
  - published: XX/34 done, ????/34 acquired, YYY/34 new, ZZZ/34 unsubmitted
- some files have been published (info taken from the logs), but crab status was not reporting it. after restarting the container (publication process is run again on container startup) crab status started reporting correct information
- final status:
  - jobs finished 34/34 finished
  - published: 34/34 done, 0/34 failed

**Comment by mapellidario** [comment]
#### `test9a` : in progress

- i deployed full py3 stack: REST-py3, TW-py3, PUB-py3
- i submitted `220124_103312:dmapelli_crab_20220124_113307` and let it run a bit (34 jobs in total)
- I deployed REST-py3, TW-py2, PUB-py3 stack when status was (x->y: x == just before deploy, y== after deploy finished)
  - jobs: ??? /34 running, ??? /34 transferring, ??? /34 finished
  - published: ??? /34 done, ??? /34 acquired, ??? /34 new, ??? /34 unsubmitted
- final status:
  - jobs finished 34/34 finished
  - published: 34/34 done, 0/34 failed
  - 
#### version details

- py2 TW: `v3.220107`
- py3 REST: `py3.220120`
- py3 TW: `py3.220117`
- py3 PUB: `py3.220117`

**Comment by mapellidario** [comment]
#### `test10a` : in progress

- i deployed mixed stack: REST-py3, TW-py2, PUB-py3
- i submitted `220124_141925:dmapelli_crab_20220124_151922` and let it run a bit (34 jobs in total)
- I deployed REST-py3, TW-py2, PUB-py2 stack when status was (x->y: x == just before deploy, y== after deploy finished)
  - jobs: ??? /34 running, ??? /34 transferring, ??? /34 finished
  - published: 7/34 done, 0/34 acquired, 0/34 new, 27/34 unsubmitted
- final status:
  - jobs finished 34/34 finished
  - published: 34/34 done, 0/34 failed
  - 
#### version details

- py2 REST: `HG2108h-v3-stable`
- py2 TW: `v3.220107`
- py2 PUB: `v3.211111`
- py3 REST: `py3.220117`
- py3 REST: `py3.220117`
- py3 PUB: `py3.220120`

**Comment by belforte** [comment]
@mapellidario I thinjk we have clear evidence that new REST works with old TW and Publisher. I propose to go on and update TaskWorker.

**Comment by mapellidario** [comment]
After having merged #7104, I suggest that we close this issue! :) :tada: 

@belforte do you agree or do you want to run `v3.22MMDD` in production before calling this a victory?

**Comment by belforte** [comment]
can close

**Comment by mapellidario** [comment]
Let's close this, then! :)
