### ISSUE TITLE
job wrapper should pass  XrdSecGSISRVNAMES (if set) to cmsRun

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6953]
see discussion in  https://ggus.eu/index.php?mode=ticket_info&ticket_id=155272
 XrdSecGSISRVNAMES env. variable is needed on some nodes at T1_UK_RAL in order to communicate with local storage

**Comment by belforte** [comment]
Note that to execute `cmsRun` I rely on WMCore's `Scram` module `call` method
https://github.com/dmwm/CRABServer/blob/34495b6ca950259740a9d40e9b32c5ecf3a2d6fc/scripts/CMSRunAnalysis.py#L601-L605
which by default cleans the environment in order to avoid clashes between COMP and CMSSW environments
https://github.com/dmwm/WMCore/blob/d0ed741473e45224b47a03457abd219076948dc1/src/python/WMCore/WMRuntime/Tools/Scram.py#L325
@khurtado @amaltaro I thought that I was following same way as WMCore/WMAgent here. I.e. that you also use `Scram` to start`cmsRun` in a clean environment, and I do not find a place in WMCore where this cleanEnv is set to False. But after I already had to "add by hand" `$X509_USER_PROXY` and `$HOME` and now this `$XrdSecGSISRVNAMES` ... I have to fear that I have not understood how things should be used.
Before I discover many other similar problems via error reports. can you try to guide me on what to do ?
Which environment does WMA use to run cmsRun  (better stated, to run `scram project`) ?

**Comment by amaltaro** [comment]
Stefano, just to make sure I understand this problem. When `cmsRun` is executed, it needs to access data in a given storage and the only way to reach/auth/authz those is through that environment variable. Is that correct?

On what concerns `cmsRun` commands, I understand that we do not use anything other than the CMSSW environment.
@khurtado is likely in a better position to explain this setup though.

**Comment by belforte** [comment]
you understand correctly Alan, and more on the topic, while that oddily named var is specific of RAL, I have always been puzzled that you can access data "at large" w/o X509_USER_PROXY define, maybe WMA puts the proxy in some "otherwise reacheable" place. But I had to pass it explicitely in the command executed via Scram.
Yes, I am questioning whether "empty environment + CMSSW" is enough to run out applications.

**Comment by amaltaro** [comment]
Shahzad is probably the best person to answer this question. But I believe scram itself "discovers" some of those environment variables and make sure it's available for CMSSW/cmsRun

**Comment by cajbrew** [comment]
@belforte The current fix is working which is great, but I slightly share your concern about maintaining an ad hoc list of site specific environment variables in the code. We do set `XrdSecGSISRVNAMES` in `SITECONF/local/JobConfig/cmsset_local.(c)sh` along with a couple of other (historic)n site specific environment variables.

Is that the right place to put site specifics? Should that be sourced after Crab cleans the environment?

**Comment by belforte** [comment]
@cajbrew it looks to me that when COMP and CMSSW were separated for python3 support some history was forgotten and overwritten. We need to do a reset. Current situation looks fragile to me as well.
This point was discussed a bit in today's WMA chat. @amaltaro  maybe it will be better to move to an hoc issue in WMCore repo ? We may need to make sure that also SI and SiteSupport are in the loop.
We need to keep 3 things in mind and handle them separately:
1. document what WMCore RunTime does now 
2. agree between CMS sites and CMS COMP on which customizations are needed and where they should be kept
   - there is also a tension between "we run in a container" and "we need X and Y from the local host" 
3. details of how specific environment requirements are implemented in CRAB vs WMCore RunTime which may have to be done with different code,  but should respect same semantics (point 2. above). We also need to be very clear about what the responsibilities are of SI (i.e. our pilot) and of COMP. E.g. what do we rely on for finding grid client (voms-proxy*, gfal*) ?

The good part is that @khurtado understand all of this very well now.

I would like to close this specific issue since `XrdSecGSISRVNAMES` is now OK in CRAB.

**Comment by cajbrew** [comment]
@belforte That sounds good to me. This specific issue is fixed and understood. I think we at RAL know enough to at least spot it should it reoccur or for some reason start to affect Production jobs. The wide fix can be tracked elsewhere and prioritised against other work.
