### ISSUE TITLE
check CRABServer memory usage and stop restarting it

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6958]
since "ever" CRABServer deployment carries in a crontab which restarts it every 4 days to prevent memory leaks.
https://github.com/dmwm/deployment/commit/af6e9a8442b08bab457b67fdb7e9238cc43920a6
This should not be needed in the K8s deployment where K8s daemons keep pods withing specified boundaries.
Moreover, there are likely no leaks any more.

We should check memory usage in the servers and remove the crontab.

Assigning to Dario temporarely, until we can assign to Wa

**Comment by belforte** [comment]
now that assignement is finalized, let's use correct priority. This is not urgent (we have been running like this for years), but we want to get it out of the way.

**Comment by novicecpp** [comment]
https://github.com/dmwm/deployment/commit/4d61704934fd18a3193cb0260e59cc021ed164f2

Done.
