### ISSUE TITLE
install fts-rest-client on all sched's via puppet

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7053]
needed to complete #6909 

so far itwas done only for vocms059 via
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/master/code/manifests/node.pp#L32-45

**Comment by belforte** [comment]
I have temporary extendend the hack via `node.pp` to cover all schedd's, waiting for a cleaner solution
* master branch
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/6447d4031f1271c31117fff5477078a15347cbe8
* qa branch
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/bbe0660e0b8b288759e4260a5d6d98ffad80ede3

**Comment by novicecpp** [comment]
Done by Stefano from migrating schedd to alma9 https://github.com/dmwm/CRABServer/issues/8258#issuecomment-1969450020.
