### ISSUE TITLE
test Publisher with DBS-GO server

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7075]
as @vkuznet wrote in #6969 

try out new code against the following

    host    = 'https://cmsweb-test3.cern.ch'
    migUrl  = host + '/dbs2go-migrate'
    phy3Url = host + '/dbs2go-writer'
    globUrl = 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader'

    globalApi   = DbsApi(url=globUrl)
    destReadApi = DbsApi(url=phy3Url)
    migrateApi  = DbsApi(url=migUrl)

The cmsweb-test3 points to dbs3_int_phys01 DBS DB which does not have much datasets. I was able to successfully migrate few datasets from DBS global to this instance. For my tests I copied part of this code (functions: migrateByBlockDBS3 and requestBlockMigration) and run it. But I did not run TaskPublish.py as is and it would be nice to test it in your environment. Please report in this PR or independently about results of the migration tests.

**Comment by belforte** [comment]
the new dbs20 writer is now available on testbed. Here's relevant messages from mail exchange
```


Stefano, Dario,
I would like to inform you that we plan to perform a switch to Go based
DBSWriter server on cmsweb testbed. I performed original tests with WMAgent
and we verified the functionality of DBSWriter. It also passed all current
unit/integration tests which exist in DBS Python codebase.

Please let me know if you're comfortable with this. If there are some
pending activities which you want to complete on testbed please let us know.
I don't think we need to ask you explicitly to perform tests with new DBSWriter
server, since we can perform a switch and see how it will go. But if it is
required you may easily do so by accessing
https://cmsweb-testbed.cern.ch/dbs2go-writer
instead of
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter

After we perform the switch on FEs, the new Go-based DBSWriter server will be
accessible at usual URL:
https://cmsweb-testbed.cern.ch/dbs/int/global/DBSWriter

Best,
Valentin.
```
```
Stefano,
I think CRAB should still int/phys03 instance rather than int/global.
We do have DBSMigrate on testbed, and when we'll do a switch of DBSWriter
we'll switch both /dbs/int/global/DBSWriter and /dbs/int/phys03/DBSWriter.
But we will NOT switch DBSMigrate. Therefore, ths dbs migration process will
follow the logic of python DBSMigrate server, while the requests to DBSWriter
will go to new Go based server.

The switch of DBSMigrate will be done after we put in production DBSWriter.

Best,
Valentin.
```

**Comment by belforte** [comment]
after DBSWriter was switched, block insertion fails: see https://its.cern.ch/jira/browse/CMSKUBERNETES-140

**Comment by vkuznet** [comment]
@belforte please provide full set of details how you construct or obtain JSON which you later try to inject into DBSWriter. I'm talking about the one you posted on mattermost and which is shown on https://its.cern.ch/jira/browse/CMSKUBERNETES-140. The insertion expects specific naming conventions which I'm trying to align with DBS Python implementation. And, the errors seems to me very simple and related to this part of JSON:
```
file_parent_list': [{'logical_file_name': '/store/user/belforte/GenericTTbar/Stefano-Test-220331/220405_200122/0000/kk_1.root',
                       'parent_logical_file_name': '/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root'}],
```
I found that in Python server some APIs uses `logical_file_name` attribute but others `this_logical_file_name`. Therefore, the actual question here is how did you obtain this JSON.

Please provide your workflow details, I need pointers to CRAB code where it obtains data and where it constructs the data (JSON), etc. which later it sends to DBSWriter.

**Comment by belforte** [comment]
@vkuznet indeed there needs to be agreement on the block dictionary format, starting with key names ! I have used that since ever, I can look for the original example which gave the start to this, anyhow this format is working finely with current server.

**Comment by belforte** [comment]
here it is sort of "best to my knowledge". Indeed a formal definition of this dictionary was never given and I think it was crafted starting from that single example plus interctions with Yuyi when needed. All of this happened 7 years ago, memory is fuzzy.

https://github.com/dmwm/DBS/blob/14df8bbe8ee8f874fe423399b18afef911fe78c7/Client/tests/dbsclient_t/unittests/blockdump.dict#L101-L103

CRAB code created the dictionary from scratch, if can be made anything.. I do not import it from outside. I suspect there is nothing to learn from CRAB code here but "it creates parent list in the format [{'logical_file_name': ..., 'parent_logical_file_name':  ...},...]". Anyhow code is here
https://github.com/dmwm/CRABServer/blob/01c1bdd55853164a55a669cfa581212d17cf5682/src/python/Publisher/TaskPublish.py#L48-L76

**Comment by vkuznet** [comment]
ok, here is the issue:
- the DBS blockdump API uses different naming convention, e.g.
```
blk="/TTToSemiLeptonic_hdampUP_TuneCP5_13TeV-powheg-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM%23dc3dd519-0929-485e-be14-9bdfc10c9bce"
scurl "https://cmsweb-testbed.cern.ch/dbs2go/blockdump?block_name=$blk" | jq
...
  "file_parent_list": [
    {
      "this_logical_file_name": "/store/mc/RunIISummer20UL17MiniAODv2/TTToSemiLeptonic_hdampUP_TuneCP5_13TeV-powheg-pythia8/MINIAODSIM/106X_mc2017_realistic_v9-v1/140000/C82161D1-E1AA-E246-869C-BE9284264498.root",
      "parent_file_id": 692967877,
      "parent_logical_file_name": "/store/mc/RunIISummer20UL17RECO/TTToSemiLeptonic_hdampUP_TuneCP5_13TeV-powheg-pythia8/AODSIM/106X_mc2017_realistic_v6-v2/120001/F230159D-6EF1-D141-8EF5-39C16C9713AD.root"
    },
```

This API is used for DBS migration.

And, at the same time as you code shows DBS python server supports a different structure:
```
'file_parent_list': [{'logical_file_name': '/store/user/belforte/GenericTTbar/Stefano-Test-220331/220405_200122/0000/kk_1.root',
                       'parent_logical_file_name': '/store/mc/HC/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/00000/8ADD04E5-1776-E711-A1BA-FA163E6741E0.root'}],
```
which uses `logical_file_name` name.

I need time to align this together and make it backward compatible.

What is the dbsAPI you used once you construct your JSON to insert it into DBS?

**Comment by belforte** [comment]
I think you nailed it, thanks.

> What is the dbsAPI you used once you construct your JSON to insert it into DBS?

I use `insertBulkBlock()` from python client
https://github.com/dmwm/CRABServer/blob/01c1bdd55853164a55a669cfa581212d17cf5682/src/python/Publisher/TaskPublish.py#L906

**Comment by vkuznet** [comment]
yes, I figure out that your code uses insertBulkBlocks. And, WMA uses blockdump DBS API which as I said use different naming convention, i.e. `this_logical_file_name`, but apparently within DBS Python code both are accepted. So I'll need to make necessary changes to make it work with both use-cases.

**Comment by vkuznet** [comment]
@belforte I fixed the issue on DBS server side and updated all DBS Go servers to new version on testebed. Could you please test again the insertion of the blocks with your Publisher and let me know.

**Comment by belforte** [comment]
looks to me that WMA uses same `insertBulkBlock()` https://github.com/dmwm/WMCore/blob/01cc3d341dcc1fc1d183e94469de0090ad6f2a64/src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py#L92
maybe that used to accept two different kind of dictionaries :-(
