### ISSUE TITLE
review new WMCore Runtim Doc and update code as needed

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7084]
see
https://github.com/dmwm/WMCore/issues/10970#issuecomment-1039742503
and especially
https://github.com/dmwm/WMCore/wiki/Notes-about-environment-variables-passed-to-the-Scram-environment-or-modified-when-running-the-CMSSW-executable

**Comment by belforte** [comment]
thanks. Wow, that's ancient stuff (2015 !). Given that the original thread was hinting at xroot client v.4.2 being a possible solutionc wrt 4.0.4 m and that we now run v4.5.0 now, I am not going to worry.

$HOME is a different story, it is still needed.

**Comment by belforte** [comment]
this is also the time to find a definitive solution to https://github.com/dmwm/WMCore/issues/10257
Basically to put on firm ground the CRAB vs. WMCore JobWrapper.
Is there some common environment and code that we can share ?

**Comment by belforte** [comment]
Alan asked for a google doc as a start, but I found it easier to start with a GH wiki which can hopefully be turned into a bit of permanent documentation for CRAB developers. 
https://github.com/dmwm/CRABServer/wiki/RunTime-CRAB-vs-WMCore

Anyhow I also copied the markdown text here
https://docs.google.com/document/d/13IIxPGbQS3a3k0Vl0j3o9ivJSO0ZoMtg5D8XN8xXSFE/edit?usp=sharing

@mapellidario please review and let's make sure that it makes sense from our side first, then we will ask Alan to have a chat about it

**Comment by mapellidario** [comment]
As I progress with the review of our jobwrapper, comparing it with the current WMCore one, I will add here a list of action items:

- [ ] Make sure that we run our jobwrapper code in python3, as mentioned in https://github.com/dmwm/CRABServer/issues/7210#issuecomment-1191199502

**Comment by belforte** [comment]
I am not sure that multiple architectures makes sense for CRAB unless we drastically change other things.

**Comment by belforte** [comment]
almost time to raise priority to critical: https://cms-talk.web.cern.ch/t/crab-test-cmssw-12-6-x-invalid-site-local-config/15423/1

**Comment by mapellidario** [comment]
I addressed this issue in the PRs:

- [x] https://github.com/dmwm/CRABServer/pull/7441
- [x] https://github.com/dmwm/CRABServer/pull/7491
- [x] https://github.com/dmwm/CRABServer/pull/7510

Al these are included in the latest CRABServer tag https://github.com/dmwm/CRABServer/releases/tag/v3.230220 and are running in production since wednesday morning.

I consider this issue as completed and move further discussion about the jobwrapper to new issues. If anybody does not agree, feel free to re-open this issue!
