### ISSUE TITLE
pass output dataset name from PostJob to task_wrapper ASAP

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7088]
the new Rucio_transfers.py need the name of the output dataset from the beginning, in order to create Rucio dataset and container names.
Current code instead computes it only late in output processing and writes it in oracle as part of output file metadata uploading:
https://github.com/dmwm/CRABServer/blob/82e032dcebd3f68b4f971d8349dd2b722b92e3cb/src/python/TaskWorker/Actions/PostJob.py#L2316-L2366

But the needed information is immediately available in FJR as soon as the first job completes (the PSET hash is computed by running edmProvDump on the output file, there is no simple way to do this at e.g. submission time, it would be easier in case to deprecate this hash or replace it with the actual has of the pset, which would not be as thorough as current one and may still allow to mix in the same dataset files with different provenance).
So the idea is to compute the final DBS dataset name as soon as the first PostJob runs and make it available to task_process_wrapper.sh

things to do
- [x] verify that current postJob does it in those lines as the first time
- [x] find how exactly this is passed to current publisher/transfer tool:
   * PublisherMaster finds it in filemetadatadb https://github.com/dmwm/CRABServer/blob/82e032dcebd3f68b4f971d8349dd2b722b92e3cb/src/python/Databases/FileMetaDataDB/Oracle/Create.py#L31 for each file to be published and puts it in the json file in PublisherFiles, TaskPublish just picks it from the first file in the document https://github.com/dmwm/CRABServer/blob/82e032dcebd3f68b4f971d8349dd2b722b92e3cb/src/python/Publisher/TaskPublish.py#L475
   * the output dataset name ends also in Task table https://github.com/dmwm/CRABServer/blob/82e032dcebd3f68b4f971d8349dd2b722b92e3cb/src/python/Databases/TaskDB/Oracle/Create.py#L78 with the same PostJob method `upload_output_files_metadata` at https://github.com/dmwm/CRABServer/blob/82e032dcebd3f68b4f971d8349dd2b722b92e3cb/src/python/TaskWorker/Actions/PostJob.py#L2403
- [x] define with @dciangot how to pass it to RUCIO_Transfers.py instead
- [ ] implement new way

reference: https://github.com/dmwm/CRABServer/pull/7087

**Comment by dciangot** [comment]
about: `how to pass it to RUCIO_Transfers.py instead` 
The cleanest way I think is to add an `outputdataset` field to the doc we dump here https://github.com/dmwm/CRABServer/blob/python3/src/python/TaskWorker/Actions/PostJob.py#L897

**Comment by belforte** [comment]
i.e. add to `task_process/transfers.txt` . Yes, same idea here. I find it non-elegant to repeat same info in every line, but it may be the safest way. 
to be concreate now every line is a small json document like
```json
{"id": "d65a5799c27abb8c5efe5af18b6b40a352546ca68f41254ef4bf4532", "username": "belforte", "taskname": "220218_205213:belforte_crab_20220218_215206", "start_time": 1645217717, "destination": "T2_CH_CERN", "destination_lfn": "/store/user/belforte/GenericTTbar/Stefano-Test-220218/220218_205213/0000/kk_44.root", "source": "T1_RU_JINR_Disk", "source_lfn": "/store/temp/user/belforte.be1f4dc5be8664cbd145bf008f5399adf42b086f/GenericTTbar/Stefano-Test-220218/220218_205213/0000/kk_44.root", "filesize": 41583222, "publish": 0, "transfer_state": "NEW", "publication_state": "NOT_REQUIRED", "job_id": "44", "job_retry_count": 0, "type": "output", "rest_host": "cmsweb-testbed.cern.ch:8443", "rest_uri": "/crabserver/preprod", "publishname": "Stefano-Test-220218-00000000000000000000000000000000", "checksums": {"adler32": "720a2cf3", "cksum": "3819769379"}}
```
I believe that `publishname` is totally useless now, was there for the old RUCIO_Transfers.py shall we remove that at the same time as adding `outputdataset` ?

**Comment by dciangot** [comment]
yeah, correct

**Comment by belforte** [comment]
`task_process/transfers.txt` is written in
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L897
by `UpdateOrInsertDoc`
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L805 during 
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L499
at
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L763
`inject_to_aso()` is right at the start of ASOServerJob.Run https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L472  in PostJob/perform_transfer
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L2094

So first thing is
- [ ] check if info needed for building outpudataset name is already in what is passed to ASOServerJob

**Comment by belforte** [comment]
but to ASO we only pass `self.publisj_name' which at this point is the "useless"
```
(Pdb) print(self.publish_name)
Stefano-Test-220221-00000000000000000000000000000000
(Pdb) 
```
if would very easy to e.g. insert the pset hash in place of `00000000000000000000000000000000` need to check if this breaks anything.

**Comment by belforte** [comment]
PostJob `self.publish_name` becomes `self.publishname` in ASOServerJob
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L291
and that propagates inside `updateOrInsertDoc()`
https://github.com/dmwm/CRABServer/blob/772689924434ab57512ff0f9667badcfda423d07/src/python/TaskWorker/Actions/PostJob.py#L805

**Comment by dciangot** [comment]
Ok, we should not only put the hash in place of the 000000000...000 but also calculate the whole dataset name as we do in [here](https://github.com/dmwm/CRABServer/blob/python3/src/python/TaskWorker/Actions/PostJob.py#L2343)

Maybe that was already included in your plan, but just wanted to make it explicit

**Comment by belforte** [comment]
yes, working on that. As usual takes some effort to reconstruct the information flow in PostJob and then a lot of care to change w/o unexpected side effects. Currently I am asking myself if I should try to preserve the code which deals with multiple datasets to publish, or scratch it. If I keep it, I do not want to break it, even if this functionality is currently not supported in Publisher, one may still think of adding it. But at the same time there is no easy way to check that I do not break it. All in all at some point in the past it was working.

Usual PostJob pains... it is well structured, but very long and data structures are undocumented.

**Comment by belforte** [comment]
sorry if I use this GH issue to track my progresses, I find that I need to write things down, my memory can't be relied upon.

**Comment by belforte** [comment]
now I have outputdataset in self.output_files_info[0]['output_dataset'] in PostJob. Need to pass it to ASOServerJob
https://github.com/dmwm/CRABServer/blob/7103882699e57d1a4d87b9485b4d39bf672f1c0d/src/python/TaskWorker/Actions/PostJob.py#L2108-L2119

**Comment by belforte** [comment]
hmm... psethash was already available as
```
self.job_report_output['output'][0]['pset_hash']
```

**Comment by belforte** [comment]
maybe better minimize changes and roll back the definition of `outputdataset` from  inside PostJob, I can do everything in ASOServerJob

**Comment by belforte** [comment]
I think that `outputdataset` must become part of the `doc` passed to `updateOrInsertDoc` in `injectToAso` so that it can be customized for each file, i.e. maintain the possibility of having multiple datasets

**Comment by belforte** [comment]
the above is indeed explained in https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling#Output_dataset_names_in_DBS   Now I have finally connected that to the code.

**Comment by belforte** [comment]
since there are now multiple places where we need to construct and pass around the output dataset name (both from PostJob class and from ASOServerJob class) I have created a standalone function to capture the logic from https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling#Output_dataset_names_in_DBS and will use it everywhere.  Things are still way more complicated that they could due to duplication of info in various places, abuse of `self` and all known problems in PostJob. But hopefully new version is not any more obscure than before and I did add some comments to explain.

I will put in a first version where old and new code for getting output dataset name are both present and consistency is checked. If OK after more testing we can remove the duplication and do things in one place only.

**Comment by belforte** [comment]
I have decided against passing output dataset name to ASOServerJob. Too risky to mess with existing data structures, in spice of the redundancy between `self.job_report_output` and `self.output_files_info` inside PostJob class at the moment where ASOServerJob is called. In particular it is not clear how possibly multiple output files per single output modules are handled, nor if it is possible etc. But it should be possibely in `upload_metadata` to reuse the `self.output_files_info` structure w/o computing dataset name again. Basically move "up" at the FJR parsing time the code which creates the output dataset name and add the name to each `file_info` dictionary.
In the first implementation I was wrongly assuming that there is a single outputdataset name for the whole PostJob and overlooked this, so my latest branch calls `computer_output_dataset` three times instead of two.
