### ISSUE TITLE
Create crab-dev-tw02

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7108]

**Comment by novicecpp** [comment]
I am done learning from [configtraining.web.cern.ch](https://configtraining.web.cern.ch).
Also, recommend skimming [configdocs.web.cern.ch](https://configdocs.web.cern.ch) at least once.

To create new machine, ssh to aiadm.cern.ch (required 2nd factor) and run this command:
```bash
ai-bs --nova-flavor m2.medium --cc7 --foreman-environment production -g vocmsglidein/crab crab-dev-tw03 --landb-responsible CMS-SERVICE-CRAB3HTCONDOR-ADMINS --landb-mainuser CMS-SERVICE-CRAB3HTCONDOR --landb-ipv6ready
```
`--landb-responsible` and `--landb-mainuser` I just grab it from `crab-dev-tw01`. I guess it is e-group that bind with our Openstack "CMS CRAB" project. 
For information about other arguemnts: https://configdocs.web.cern.ch/nodes/create/index.html

For Puppet configuration of `crab-dev-tw02`, I will track it in https://github.com/dmwm/CRABServer/issues/7113.

@mapellidario I give decision to close this issue to you.

**Comment by belforte** [comment]
I suggest to close once crab-dev-tw02 is working.
Please make sure that instructions are correctly reported in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABDocker
feel free to help in updating/restructiring all that documentation which indeed has a lot of pre-docker/pre-k8s stuff, some of which still matters, but most does not.

**Comment by mapellidario** [comment]
I will list here some things that we may want to add to the documentation:

- [ ] add the new DB instance to the crabserver web UI, as in https://github.com/dmwm/CRABServer/pull/7352

**Comment by belforte** [comment]
I think we may be better off asking Ceyhun. Can you do Wa?

**Comment by novicecpp** [comment]
Sure.
