### ISSUE TITLE
Deploy TW and Publisher_sched on crab-dev-tw02

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7113]

**Comment by novicecpp** [comment]
Plan: 
* Create 2 machine
  * crab-dev-tw02 for `production` (foreman environment)
  * crab-dev-tw03 for `crab_playground` 
* Request whitelist myproxy, and CRIC users.

From yesterday's meeting, we have new Puppet code refactoring tasks (https://github.com/dmwm/CRABServer/issues/7172). But I will try to bring up a new VM for Taskworker without refactoring code first. It could help me understand our situation with puppet code and how we could improve it better.

**Comment by novicecpp** [comment]
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/55

Note that Taskworker/Publisher_schedd in `crab-dev-tw03` does not intend to run parallel with `crab-dev-tw02`, but for code refactoring test only. I will create both VM to get IP and request access to myproxy.cern.ch. Also, let Puppet apply config to VM to generate host/service certificates and register it to cms VOMS and CRIC server. So, I do not need to do it again when I refactor code.

**Comment by belforte** [comment]
FYI there is no problem if you start multiple TW's in parallel pointing to same database. But for experimental machines it is better not to point to prod !

**Comment by mapellidario** [comment]
Don't we risk having the two TW process the same task twice? Or the time it takes for a TW to set the status of a task from NEW to QUEUED is so small that we dont risk anything?
Moreover, if a TW is processing some tasks, having set them to QUEUED, if in the meantime we start a new TW, doesnt this new TW start processing these QUEUED tasks as well? 

Or simply these are tests tasks (not critical and never too many to have long queues of tasks to process), so we dont really care if such a race happens?

In any case, if we are developing a new feature on TW in test2 and we submit a task, should we stop TW in test1 to make sure it doesnt "steal" it?

I am just trying to understand how to best operate the test instances if they risk getting so intertwined

**Comment by belforte** [comment]
> Don't we risk having the two TW process the same task twice? 

No. TW is designed for this and relies on Oracle for atomic transaction to pick and lock task to a given TW host.
Otherwise we would indeed be exposed to all races conditions which you indicate.

**Comment by belforte** [comment]
>In any case, if we are developing a new feature on TW in test2 and we submit a task, should we stop TW in test1 to make sure it doesnt "steal" it?

YES, there is no way to submit a task asking for one specific TW to proces it. TW was designed so to be able to run multiple TW's at same time for load sharing and resiliency. We simply found that one is enough, but keep crab-prod-tw02 as "hot spare"

**Comment by novicecpp** [comment]
https://cmscrab.docs.cern.ch/technical/crab-taskworker/introduction.html
Done
