### ISSUE TITLE
Our logstash cluster gone after internal incident

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7115]
Maybe this is the time to move our logstash to CMSMONIT system.

**Comment by novicecpp** [comment]
New ticket to CMSMONIT team: https://its.cern.ch/jira/projects/CMSMONIT/issues/CMSMONIT-460

**Comment by novicecpp** [comment]
Thanks to Imran and Ceyhun, now we have seperate logstash instances for `crabtaskworker`, running in `crab` namespace inside **CMSWEB k8s** cluster. Logstash config is moved to https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/monitoring/crab/logstash.conf.

So, we need to change filebeat config to what Ceyhun suggested here: https://github.com/dmwm/CMSKubernetes/pull/985#issuecomment-1071938453, https://github.com/dmwm/CMSKubernetes/pull/1001
* change endpoint to`[CMSWEB_DNS_ALIAS:30044]`.
* add proper tags

Currently filebeat config that deploy on VMs is here: https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/master/code/manifests/profiles/crabtaskworker.pp#L341 ([monitor.sh](https://github.com/dmwm/CRABServer/blob/db170c6254b493b0c3a17e1cb3792957bdec2fc9/Docker/monitor.sh#L7) start filebeat with args that read config from `hostdisk` path, which is mounted by [runContainer.sh](https://github.com/dmwm/CRABServer/blob/db170c6254b493b0c3a17e1cb3792957bdec2fc9/src/script/Container/runContainer.sh#L50)).

**Comment by belforte** [comment]
will https://github.com/dmwm/CRABServer/tree/master/src/script/Monitor/logstash become obsolete  ? (and therefore we should remove it)

**Comment by novicecpp** [comment]
> will https://github.com/dmwm/CRABServer/tree/master/src/script/Monitor/logstash become obsolete ? (and therefore we should remove it)

Yes, it safe to remove it now (I will do it).


For context of 2h latency issue https://github.com/dmwm/CRABServer/issues/6786, please see what Ceyhun explain [here](https://its.cern.ch/jira/browse/CMSMONIT-458?focusedCommentId=4269114&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4269114).
