### ISSUE TITLE
Need to recreate some CRAB VM before Openstack network migration run.

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7118]
Cloud team will cold migrate all VM that still use old network stack to the new one. New VMs are only deploy on new network stack. 
We will have down time for 1-2 hour when migration kick in, but IP and MAC addresses of the VMs will be kept.

Migration start in the end of March.

Affect resources in "CMS CRAB" projects (according to https://gitlab.cern.ch/-/snippets/2022): 
```
| crab-preprod-tw01                                     | ACTIVE    | CMS CRAB                                                      |
| vocms0106                                             | ACTIVE    | CMS CRAB                                                      |
| vocms0122                                             | ACTIVE    | CMS CRAB                                                      |
```
For more information: https://indico.cern.ch/event/1122757/contributions/4760609/attachments/2401343/4106780/VM%20Cold%20Migration%20Campaign%20-%20ASDF03MAR2022.pdf

------------------------------------------------------
For Taskworker VM, I think we can destroy and spawn new one by:
- take disk snapshot
- back hostcert+servicecert+schedd_token
- destroy, and spawn new one
- redeploy Taskworker and Publisher_schedd

For Schedd machine, I don't know.

Plan B is cold migrate but do it ourselve, by spawn new VM from snapshot.
Or Plan C is lets cloud team migrate VM for us.

**Comment by belforte** [comment]
assigning to me for outlining a proper plan.
THanks @novicecpp for having opened this and for having researched the relevant information.

**Comment by novicecpp** [comment]
Thanks Stefano, I will do it.

**Comment by novicecpp** [comment]
To drain node, just change `weightfactor` of `vocms0106` and `vocms0122` to `0` (like `vocms059`) in [cmsweb-schedd-config.json](https://gitlab.cern.ch/crab3/CRAB3ServerConfig/-/blob/master/cmsweb-shedds-config.json)
No need to apply anything. Crabserver will reload this configuration every 30 minutes.

Draining 2 or 3 days before migration start is enough, wait until [number of running jobs per schedd](https://monit-grafana.cern.ch/d/CsnjLe6Mk/crab-overview?orgId=11&editPanel=62) drop to few hundred of job. To reduce number of job restart that we do not want to stress HTCondor Central Manager too much.

Now we are waiting for migration schedule's email from CERN IT team.

For load distribution in Schedd, we can look at `number of running dagmans per schedd` metrics [here](https://monit-grafana.cern.ch/d/CsnjLe6Mk/crab-overview?orgId=11&viewPanel=60). Soft limit before Schedd gone wrong is 250 (according to Stefano). We have 15 machines, drain 2 machin will increase number of dagman running by 15%.

**Comment by belforte** [comment]
Time to act on this. See this message from Germano:
```
Good day. IT department has started a cold migration campaign ([OTG0069820](https://cern.service-now.com/service-portal?id=outage&n=OTG0069820), related ASDF [presentation](https://indico.cern.ch/event/1122757/#2-cloud-infrastructure-cold-mi)).
I am contacting you as the owner of the project CMS CRAB

Your VMs
crab-preprod-tw01
vocms0122
vocms0106

has been scheduled to be cold migrated to a new hypervisor machine on date
crab-preprod-tw01 2022.09.20 0:00
vocms0122 2022.09.29 8:00
vocms0106 2022.10.18 0:00

Cold Migration implies a downtime depending on the amount of data on the disk and the load on the infrastructure during the migration. Migrations may last from 15 minutes to 8 hours.
* m2.small and m2.medium less than 1 hour
* m2.large 30 minutes to 2 hours
* m2.xlarge 2 to 4 hours

If you cannot afford an undetermined downtime during cold migration, we can plan the creation of new machines that will replace the old ones
Best regards

-- 
Germano Massullo
CERN CMS experiment VOC
Esplanade de Particules, 1
CH-1211 Geneva 23
https://home.cern/
e-mail: [germano.massullo@cern.ch](mailto:germano.massullo@cern.ch)
```

**Comment by novicecpp** [comment]
15 September, Thursday next week, I will put vocms0122 to draining mode.

**Comment by novicecpp** [comment]
vocms0122 is in drain mode on September 20
https://cms-logbook.cern.ch/elog/Analysis+Operations/3761

**Comment by novicecpp** [comment]
vocms0122 is done in this morning.  Elog: https://cms-logbook.cern.ch/elog/Analysis+Operations/3769

I put it in drain mode 10 days ago. 
We have 7 dagmans still running, average running dagman per schedd at peak is 145 (max 181).  
Well, draining prior 2 week is not bad but clearly should not do 2 days earlier.

Thanks Dario again to put them on hold before migration start.

Next is `vocms0106 2022.10.18 0:00`, I will put it in drain mode on 4 October.

**Comment by novicecpp** [comment]
Comment from Stefano I think it worth to put here before it lost in my mailbox:

```
I suggest to do it now, so there's one thing less to remember.
By the way I am not sure that holding tasks makes much difference.
The only difference between a quick reboot and a cold migration
could be that in the former case some of the remote jobs running
on the grid may manage to reconnect and do not get killed. Timeout
for such reconnection is 20 minutes. But even in a quick reboot it
takes quite some time for the schedd to restart so not all jobs
manage to keep running. With a 2h or so migration, all remote jobs
will need to be restarted. The aim of the drain is to avoid
having to restart O(5k) jobs in a short time, bad for HTCondor
and quite a waste of CPU.

A different story would be if we were to fully retire a scheduler
host, then we'd need to wait for all tasks to complete and be
purged, one month. 
```

But, I will drain next machine in 4 Oct as I plan (note in my own calendar). I would like to avoid changing anything on Friday if it not urgent.

**Comment by novicecpp** [comment]
This is already done. Everything works as usual.
