### ISSUE TITLE
Improve error checking in jenkins_build_docker script

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7133]
A recent build of [CRABServer_BuildImage](https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_BuildImage/24/console) failed to build the crabserver docker image, but the script exited successfully anyway [1]. We can do better.

[1]

```plaintext
[...]
16:26:56 Registry #### registry.cern.ch/cmsweb
16:26:56 ### build cmssw/crabserver
16:26:56 Sending build context to Docker daemon   21.5kB
16:26:56 Step 1/17 : FROM registry.cern.ch/cmsweb/cmsweb:20220301-stable
16:26:56 unknown: artifact cmsweb/cmsweb:20220301-stable not found
16:26:56 Error response from daemon: No such image: cmssw/crabserver:v3.220315
16:26:56 Error response from daemon: No such image: cmssw/crabserver:latest
16:26:56 ### existing images
[...]
16:26:56 Using default tag: latest
16:26:56 The push refers to repository [docker.io/cmssw/crabserver]
16:26:56 An image does not exist locally with the tag: cmssw/crabserver
16:26:57 Using default tag: latest
16:26:57 The push refers to repository [registry.cern.ch/cmsweb/crabserver]
16:26:57 An image does not exist locally with the tag: registry.cern.ch/cmsweb/crabserver
16:26:57 The push refers to repository [docker.io/cmssw/crabserver]
16:26:57 An image does not exist locally with the tag: cmssw/crabserver
16:26:57 The push refers to repository [registry.cern.ch/cmsweb/crabserver]
16:26:57 An image does not exist locally with the tag: registry.cern.ch/cmsweb/crabserver
16:26:57 Images was uploaded to docker hub, time to clean-up, press CTRL+C to interrupt...
16:27:02 Error: No such image: cmssw/crabserver
16:27:02 Error: No such image: registry.cern.ch/cmsweb/crabserver
16:27:02 Error: No such image: cmssw/crabserver:v3.220315
16:27:02 Error: No such image: registry.cern.ch/cmsweb/crabserver:v3.220315
16:27:02 
16:27:02 To remove all images please use this command
16:27:02 docker rmi $(docker images -qf "dangling=true")
16:27:02 docker images | awk '{print "docker rmi -f """}' | /bin/sh
16:27:02 Checking console output
16:27:02 Run condition [Text Finder] preventing perform for step [Execute shell]
16:27:02 [WS-CLEANUP] Deleting project workspace...
16:27:02 [WS-CLEANUP] Deferred wipeout is used...
16:27:02 [WS-CLEANUP] done
16:27:02 Finished: SUCCESS
```

**Comment by novicecpp** [comment]
Error come from [install.sh](https://github.com/dmwm/CMSKubernetes/blob/master/docker/build.sh) that we depend when build crabserver image. 

It would be better if we move whole [CMSKubernetes/docker/crabserver](https://github.com/dmwm/CMSKubernetes/tree/master/docker/crabserver) to here.

**Comment by mapellidario** [comment]
And that would still not cover everything because we still have some scripts in `dmwm/deployment`. I know we can greatly improve the managed of the build/deployment scripts, but for the time being i would simply add a check at the end of our jenkins_build_docker that checks if the desired docker image reached the desired registry. A simple check that covers all possible errors. Checking all the potential source of errors in the scripts can be a bit tedious...

**Comment by belforte** [comment]
I assigned to @mapellidario before reading @novicecpp 's comment. It is indeed an old question whether to move crabserver build scripts from CMSKubernetes to our repo. I think it is good to review pro's and con's with Imran. My feeling is that it would mean that he can't build crabserver anymore, which may be OK. But maybe I miss something.

**Comment by belforte** [comment]
overridden by migration to new PyPi based build
