### ISSUE TITLE
allow users to process a partially-on-disk dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7135]
currently if the input dataset is partially on disk, CRAB submits a tape recall request to Rucio and waits for all files to be on disk before running the task.
Yet some user may prefer to be able to quickly process what's currently on disk.
See  e.g. https://cms-talk.web.cern.ch/t/submitfailed-generator-object-has-no-attribute-next-failure/8204/9

At first sight this will require a new config. parameter, hence a new column in TaskDB. It may be a good time to add just one CLOB column instead where to put a `key:value` dictionary of additional parameters so to give us freedom for the future.

**Comment by belforte** [comment]
adding a column requires time. Let's try to use as a temporary hack
```
config.Data.runRange = '0'
```

**Comment by belforte** [comment]
The temporary hack indicated above is now deployed in master branch and in preprod instance and works in my tests.
The long term fix will be to add the configuration parameter `usePartialDataset` with default `False`
https://github.com/dmwm/CRABServer/blob/6ae0db121c229838a2782ce2e00c4b224de735f7/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L403-L408

**Comment by belforte** [comment]
reduce priority for next step which requires changes in CRABClient, CRAB REST and database as well.

**Comment by novicecpp** [comment]
Summary of progress on this issue

**CRABServer/Taskworker**
- We have new generic user config kv for store static user configuration. 
  - New column in `TASKS`: `tm_user_config`
  - New field `user_config` in RESTUserWorkflow API and set default value there. 
  - TaskWorker/Publisher access values RESTWorkerWorkflow (via CRABRest client) as dictionary (e.g. `kwargs['task']['tm_user_config']['partialdataset']` in DBSDataDiscovery.py)
- User can use `config.Data.runRange = '0'`, will remove 3 month later(?) after officially announce this feature.
- New code are deployed on production.

**CRABClient**
- Only add new config to `ClientMapping.py` and proper convert boolean value when talk with CRABServer.
- Tested and deployed in `crab-dev`. 
- Production version is merged in cmsdist repo https://github.com/cms-sw/cmsdist/pull/8011. Waiting for CMSSW admin cutting new release.

**Comment by belforte** [comment]
all done and deployed in production.
I think that we only need to
- [ ] update documentation

@novicecpp please confirm

**Comment by novicecpp** [comment]
Done!
