### ISSUE TITLE
Improve jenkins_build_rpm to allow building from new branches

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7138]
Creating a backport means creating a new branch, but in the deploy script we couple the name of the branch that a tag points to to last part of the rpm repo name in https://github.com/dmwm/CRABServer/blob/60d28b0d41bed49fb32cacd2de182bfa9212d160/cicd/build/jenkins_build_rpm.sh#L59

This has been usually fine, since we had tags pointing to `master` or `python3` branches, and we have both [comp.crab_master](https://cmsrep.cern.ch/cmssw/repos/comp.crab_master/slc7_amd64_gcc630/latest/RPMS.json) and [comp.crab_python3](https://cmsrep.cern.ch/cmssw/repos/comp.crab_master/slc7_amd64_gcc630/latest/RPMS.json).

It would be nice being able to use jenkins to build from a generic github branch. I dont have an implementation in mind yet, I am open to suggestions!

**Comment by mapellidario** [comment]
> It is the upload which gives troubles because we do not want to create a new repo for each branch for ./pkgtools

yes! 

> I am not sure why we need different repositories for every branch.

This was my first impulsive thought, but we learnt that we should not really trust my first ideas, they are full of often wrong assumptions! Thanks for confirming, then. 

So, I would suggest that we only use `comp.crab_master`, changing

https://github.com/dmwm/CRABServer/blob/db170c6254b493b0c3a17e1cb3792957bdec2fc9/cicd/build/jenkins_build_rpm.sh#L59

```diff
- ./pkgtools/cmsBuild -c cmsdist --repository comp -a slc7_amd64_gcc630 --upload-tmp-repository crab_${BRANCH} --builders 8 -j 5 --work-dir w upload comp | tee logUpload
+ ./pkgtools/cmsBuild -c cmsdist --repository comp -a slc7_amd64_gcc630 --upload-tmp-repository crab_master --builders 8 -j 5 --work-dir w upload comp | tee logUpload
```
(i would also need to change a couple of other lines, but that's the jist).

**Comment by belforte** [comment]
why `crab_master` ? I'd rather not have the name of a particular branch if the idea is to put there latest rpm's no matter what branch, simply identified by a tag.
FWIW here's the list of "crab" repos at the moment:
```
comp.crab_210318patch/
comp.crab_210701patch/
comp.crab3/
comp.crab_master/
comp.crab_py2only/
comp.crab_py3_211103/
comp.crab_python3/
comp.crab_pythonMigration/
comp.CRABServer_v3_201022/
comp.CRABServer_v3_201025/
comp.CRABServer_v3_201026/
comp.crab_test_new_CMSRunAnalysis/
comp.crab_test_WMCore149/
```
I am all for reducing noise and confusion if we can.

**Comment by mapellidario** [comment]
This is a valid point, `comp.crab3`?

**Comment by belforte** [comment]
we can certainly try until we hit a problem which makes me remember why Daina introduced multiple repositories. Or maybe create `comp.crab`

**Comment by mapellidario** [comment]
Stefano correctly pointed out that my problem was caused by the github branch containing characters (the dot `.`) that are not allowed in the rpm repository name.

This was even pretty clear in the error message in Jenkins:

> ERROR: Tmp upload repository name 'crab_patch-v3.220314' contains invalid characters. Allowed characters are: a-zA-Z0-9_

After he created a new branch with a proper name (`220314patch`), the rpm repository has been automatically created: https://cmsrep.cern.ch/cmssw/repos/comp.crab_220314patch/

I will close this issue since it is not a problem, it was my mistake!

Thanks Stefano!
