### ISSUE TITLE
crabserver REST - slow HTTP queries, affecting all CMSWEB services

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7149]
slow HTTP queries starting Tuesday 2022-03-02 and affecting all CMSWEB services.

- Symptom is that queries sort of hang for 2 or 4 minutes then completes in secondes. If they are held stuck longer, they hit 5min timeout in FE. Deep reason still unknown.
- Since Imran moved CRABServer REST pods to a different K8s cluster things are very good for us.
- Dario tried to reproduce this on preprod with one pod, was running more queries per time unit than production, but no problems. Next step would be to try with multiple pods.
- We decide to use CRABServer/test or create a similar directory for this kind of test script.
- We are currently waiting for Imran and Valentin for coming up with a plan of the next steps.

This has been discussed also in:

- https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3074993
- https://its.cern.ch/jira/projects/CMSKUBERNETES/issues/CMSKUBERNETES-114?filter=allopenissues

**Comment by belforte** [comment]
this was fixed by Valentin et al. via changes for CMSWEB FrontEnd configuration: https://mattermost.web.cern.ch/cms-o-and-c/pl/6rkm47y5kp86bekbzj7c4f1faa
