### ISSUE TITLE
crabtaskworker - docker unix group membership

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7150]
Make sure that membership in docker unix group in `crab-*tw*` VM's is managed via e-group, not explicit user list, in puppet.

i.e we basically want a way of getting rid of [this](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/ec6ebc26c41dcc03b1406013213c9b0070c8ad7e/code/manifests/node.pp#L25) hardcoded list line

**Comment by novicecpp** [comment]
Done [commit 73089c9e in docker.pp#L21](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/73089c9e84c1118e7a41f29523454fc79c968ed4/code/manifests/crabtaskworker/docker.pp#L21)
and deployed in production.
