### ISSUE TITLE
Add py3 pylint checks when a PR is created and updated

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7152]
We should deprecate the use of py2-pylint, use py3-pylint.

Moreover, we may want to have a broader look at all the checks that WMCore is using, we may want to add some of those, too.

**Comment by amaltaro** [comment]
@mapellidario if you keep working on this, we might exchange some information and try to converge on a setup that would work for both projects.
Today - and in the past week - @goughes and I had a chat on this and we are considering the creation of a smaller image for static code analysis (pylint / pycodestyle). 
Erik can give you more details on this, but the idea is exactly the same, have in the environment only what is really necessary (baseline code, python dependencies and python devtools).

Anyhow, just making a bridge here ;)

**Comment by mapellidario** [comment]
Trying to adapt the current CRAB setup feels like as much work as starting from scratch with a very simple image with only pylint/pycodestyle inside. If you are already planning on doing that, then I will quickly jump aboard! :)
Thanks Alan for stepping in!
I will try something easy tomorrow morning and I will come back to you!

**Comment by mapellidario** [comment]
Taking inspiration from [1] (thanks Alan and Eric for providing it!) and [2], I eventually came back to this.

So far it is looking promising [3], but there are some things to polish (i will update this list while working on this subject):

- [ ] Despite the comment correctly contains `Python3 Pylint check: failed `, this is not reflected visually in [4]

[1] https://github.com/dmwm/Docker/pull/132
[2] https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-PR-pylintpy3/
[3] https://github.com/dmwm/CRABServer/pull/7309#issuecomment-1163267684
[4] ![image](https://user-images.githubusercontent.com/16376695/175099178-9bedfcac-08de-42eb-8a5b-bfefb69950b7.png)

**Comment by mapellidario** [comment]
Since [1], all PRs in both dmwm/CRABServer and dmwm/CRABClient will be tested with py3 pylint, therefore I will close this issue.

I noticed that the reports are quite verbose, we can discuss at a later stage what to do about it. I see a couple of options:

1. Disable the most verbose and unlikely-necessary warnings
1. Switch off all errors/warnings and only enable a selected few that we know that we can benefit from (syntax errors, undefined variables, ... something like this), taking suggestion from [2]

Nothing urgent, just some low-priority chat ahead us.

[1] https://cmssdt.cern.ch/dmwm-jenkins/view/CRAB/job/DMWM-CRABServer-PR-test/1292/
[2] https://pythonspeed.com/articles/pylint/

**Comment by belforte** [comment]
yes, we should disable some "expected" things like 
` doesn't conform to '([a-z][a-zA-Z0-9]*$|^_$)' pattern`

I also doubt that we'll ever fix the too many.... in existing code.

**Comment by belforte** [comment]
I do not understand
` Formatting a regular string which could be a f-string`
so can't say if it is worth to have it

**Comment by belforte** [comment]
I see. I do not think we want to change that everywhere in old code, but it may be nice if I too can learn for new code, will try. But we e should fix the `logger...('blah %s' % string)`
