### ISSUE TITLE
Oracle DB - setup all tables for partitioning

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7154]
setup all tables preprod and dev DB instances for partitioning. Now only preprod FILETRANSFERDB is correct

**Comment by mapellidario** [comment]
### Plan

documentation

- [x] create a new page where to collect all the most recent knowledge about Oracle management: https://cmscrab.docs.cern.ch/technical/crab-rest/database-admin.html
- [ ] Fill in all the `TODO` in the page mentioned at the previous bullet

partitions

- [x] create new branch in dmwm/CRABServer where to save all the code for administrating the Oracle DB that we want to keep around: https://github.com/dmwm/CRABServer/compare/master...mapellidario:CRABServer:20230726_oracle_mgmt
- [ ] edit the procedures in prod. the emails should not arrive from Prajesh's address.
- [ ] compare the code on prod and on preprod 
- [ ] add to the code instructions for creating the PTNAME table (used to store the next partitions that should be dropped)
- [ ] port the code that we have on prod to `partitions.sql`
- [ ] delete all procedures in preprod, then use the code in `partitions.sql` to create the procedures from scratch


indexes. 

We currently have no instructions in the code on how to create indexes, and the one we have is broken (it creates two indexes with the same name [1] creating confusion [2])

- [ ] make a list of the indexes that we have in prod and preprod
- [ ] adjust code in dmwm/CRABServer/Databases/**/Oracle/Create.py accordingly.
- [ ] run on devtwo and make sure it is the same as in prod (with better names)
- [ ] run on preprod, and make sure it is the same as in prod (with better names)
- [ ] document the index names mapping across DB instances (i do not want to touch the indexes in prod, so i would leave the current names there)

---

[1] 

https://github.com/dmwm/CRABServer/blob/1ebaa01e363c4ed6c0e31564f1590548a7dfb962/src/python/Databases/FileTransfersDB/Oracle/Create.py#L27-L28

[2] All the errors in https://cmscrab.docs.cern.ch/technical/crab-rest/database.html#create-table should disappear :)

**Comment by belforte** [comment]
sorry for [1], indeed it was never tested and I wrote it w/o understanding that there is name there that should be different. I do not know how to list indexes via SQL !
I guess we can ask Kate if there's a clean way to get prod DB to use indexes with new names. Otherwise I would rather keep same names everywhere as she defined in prod.
