### ISSUE TITLE
WMARchive is not running on vocms0198/121

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7159]
on a good scheduler:
```
belforte@vocms0199/~> systemctl status WMArchiveUploader
● WMArchiveUploader.service - LSB: The WMArchive Uplader
   Loaded: loaded (/etc/rc.d/init.d/WMArchiveUploader; bad; vendor preset: disabled)
   Active: active (exited) since Wed 2021-09-29 23:20:58 CEST; 5 months 20 days ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0
   Memory: 0B
belforte@vocms0199/~> 

```
but on the two in the subject:
```
root@vocms0198 belforte]# systemctl status WMArchiveUploader
● WMArchiveUploader.service - LSB: The WMArchive Uplader
   Loaded: loaded (/etc/rc.d/init.d/WMArchiveUploader; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2022-03-21 14:34:25 CET; 55min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1907129 ExecStart=/etc/rc.d/init.d/WMArchiveUploader start (code=exited, status=1/FAILURE)

Mar 21 14:34:25 vocms0198.cern.ch systemd[1]: Starting LSB: The WMArchive Uplader...
Mar 21 14:34:25 vocms0198.cern.ch sudo[1907132]:     root : TTY=unknown ; PWD=/ ; USER=condor ; COMMAND=/bin/bash -c {
                                                             export LD_LIBRARY_PATH=
                                                             export PYTHONPATH=/data/srv/SubmissionInfrastructureScrip...
Mar 21 14:34:25 vocms0198.cern.ch sudo[1907132]: pam_limits(sudo:session): Could not set limit for 'nofile': Oper...itted
Mar 21 14:34:25 vocms0198.cern.ch WMArchiveUploader[1907129]: Starting WMArchiveUploader.py: sudo: pam_open_session...ied
Mar 21 14:34:25 vocms0198.cern.ch WMArchiveUploader[1907129]: sudo: policy plugin failed session initialization
Mar 21 14:34:25 vocms0198.cern.ch systemd[1]: WMArchiveUploader.service: control process exited, code=exited status=1
Mar 21 14:34:25 vocms0198.cern.ch systemd[1]: Failed to start LSB: The WMArchive Uplader.
Mar 21 14:34:25 vocms0198.cern.ch systemd[1]: Unit WMArchiveUploader.service entered failed state.
Mar 21 14:34:25 vocms0198.cern.ch systemd[1]: WMArchiveUploader.service failed.
```

```
[root@vocms0121 belforte]# systemctl status WMArchiveUploader
● WMArchiveUploader.service - LSB: The WMArchive Uplader
   Loaded: loaded (/etc/rc.d/init.d/WMArchiveUploader; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2022-03-21 14:49:46 CET; 41min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2187225 ExecStart=/etc/rc.d/init.d/WMArchiveUploader start (code=exited, status=1/FAILURE)

Mar 21 14:49:46 vocms0121.cern.ch systemd[1]: Starting LSB: The WMArchive Uplader...
Mar 21 14:49:46 vocms0121.cern.ch sudo[2187228]:     root : TTY=unknown ; PWD=/ ; USER=condor ; COMMAND=/bin/bash -c {
                                                             export LD_LIBRARY_PATH=
                                                             export PYTHONPATH=/data/srv/SubmissionInfrastructureScrip...
Mar 21 14:49:46 vocms0121.cern.ch sudo[2187228]: pam_limits(sudo:session): Could not set limit for 'nofile': Oper...itted
Mar 21 14:49:46 vocms0121.cern.ch WMArchiveUploader[2187225]: Starting WMArchiveUploader.py: sudo: pam_open_session...ied
Mar 21 14:49:46 vocms0121.cern.ch WMArchiveUploader[2187225]: sudo: policy plugin failed session initialization
Mar 21 14:49:46 vocms0121.cern.ch systemd[1]: WMArchiveUploader.service: control process exited, code=exited status=1
Mar 21 14:49:46 vocms0121.cern.ch systemd[1]: Failed to start LSB: The WMArchive Uplader.
Mar 21 14:49:46 vocms0121.cern.ch systemd[1]: Unit WMArchiveUploader.service entered failed state.
Mar 21 14:49:46 vocms0121.cern.ch systemd[1]: WMArchiveUploader.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@vocms0121 belforte]# 

```

**Comment by novicecpp** [comment]
Dario and I try to figure it out  what is wrong with this issue whole afternoon. 

I also saw error it in `/var/log/secure` when tried to run `sudo su condor`
```
Mar 24 21:08:00 vocms059.cern.ch sudo: pam_limits(sudo-i:session): Could not set limit for 'nofile': Operation not permitted
```

I suspected that something wrong with ulimit configuration of `condor` user in `/etc/security/limit.d/99-htcondor.conf`. So, I tried to modify `nofile` values to `1048576`
```diff
[root@vocms059 limits.d]# diff -u 99-htcondor.conf 99-htcondor.conf.mod
--- 99-htcondor.conf    2022-03-24 21:28:51.781488093 +0100
+++ 99-htcondor.conf.mod        2022-03-24 22:15:48.467977776 +0100
@@ -1,7 +1,7 @@
 # Custom HTCondor limits file
 # Raise number of allowed open files
-condor soft nofile unlimited
-condor hard nofile unlimited
+condor soft nofile 1048576
+condor hard nofile 1048576
```

I test `sudo su condor` again and nofile error disappear.
```
Mar 24 21:21:31 vocms059.cern.ch sudo: tseethon : TTY=pts/0 ; PWD=/etc/security/limits.d ; USER=condor ; COMMAND=/sbin/nologin -c bash
Mar 24 21:21:31 vocms059.cern.ch sudo: pam_unix(sudo-i:session): session opened for user condor by tseethon(uid=0)
```

WMArchiveUplader.service error changed too when tried to start service:
```
Mar 24 21:14:30 vocms059.cern.ch systemd[1]: Starting LSB: The WMArchive Uplader...
Mar 24 21:14:30 vocms059.cern.ch sudo[2418171]:     root : TTY=unknown ; PWD=/ ; USER=condor ; COMMAND=/bin/bash -c {
                                                            export LD_LIBRARY_PATH=
                                                            export PYTHONPATH=/data/srv/SubmissionInfrastructureScripts//WMCore/src/python
                                                        
                                                        # start daemon
                                                            /data/srv/SubmissionInfrastructureScripts//WMArchiveUploader.py start ;}
Mar 24 21:14:30 vocms059.cern.ch sudo[2418171]: pam_limits(sudo:session): Could not set limit for 'nofile': Operation not permitted
Mar 24 21:14:30 vocms059.cern.ch WMArchiveUploader[2418168]: Starting WMArchiveUploader.py: sudo: pam_open_session: Permission denied
Mar 24 21:14:30 vocms059.cern.ch WMArchiveUploader[2418168]: sudo: policy plugin failed session initialization
Mar 24 21:14:30 vocms059.cern.ch systemd[1]: WMArchiveUploader.service: control process exited, code=exited status=1
Mar 24 21:14:30 vocms059.cern.ch systemd[1]: Failed to start LSB: The WMArchive Uplader.
Mar 24 21:14:30 vocms059.cern.ch systemd[1]: Unit WMArchiveUploader.service entered failed state.
Mar 24 21:14:30 vocms059.cern.ch systemd[1]: WMArchiveUploader.service failed.
Mar 24 21:21:54 vocms059.cern.ch systemd[1]: Starting LSB: The WMArchive Uplader...
Mar 24 21:21:54 vocms059.cern.ch sudo[2418797]:     root : TTY=unknown ; PWD=/ ; USER=condor ; COMMAND=/bin/bash -c {
                                                            export LD_LIBRARY_PATH=
                                                            export PYTHONPATH=/data/srv/SubmissionInfrastructureScripts//WMCore/src/python
                                                        
                                                        # start daemon
                                                            /data/srv/SubmissionInfrastructureScripts//WMArchiveUploader.py start ;}
Mar 24 21:21:54 vocms059.cern.ch WMArchiveUploader[2418794]: Starting WMArchiveUploader.py: pidfile /data/srv/WMArchiveWD/WMArchiveUploader.lock already exist. Daemon already running?
Mar 24 21:21:54 vocms059.cern.ch systemd[1]: WMArchiveUploader.service: control process exited, code=exited status=1
Mar 24 21:21:54 vocms059.cern.ch systemd[1]: Failed to start LSB: The WMArchive Uplader.
Mar 24 21:21:54 vocms059.cern.ch systemd[1]: Unit WMArchiveUploader.service entered failed state.
Mar 24 21:21:54 vocms059.cern.ch systemd[1]: WMArchiveUploader.service failed.
```

I do not know where is `99-htcondor.conf` file come from but it replace when sometime pass (I did not find it in Puppet code).

Search in google found other people encounter this problem too https://unix.stackexchange.com/questions/432057/pam-limits-so-making-problems-for-sudo/444033#444033. They said it is a bug of pam_limits but no reference to bug report.

**Comment by belforte** [comment]
isn't this the reason why it does not start ? stale lock file needs to be remove by hand :-(

On 24/03/2022 22:24, Thanayut Seethongchuen wrote:
> |Mar 24 21:21:54 vocms059.cern.ch WMArchiveUploader[2418794]: Starting WMArchiveUploader.py: pidfile /data/srv/WMArchiveWD/WMArchiveUploader.lock already exist. Daemon already running?|


this used to happen when machine reboots "at the wrong time". We can look into making this thing
more robust, or, as I mention to Dario, review whether this WMArchive thing is really useful, in the end.
You should not sped much time on this. But we need to get rid of those stale directories
containing millions of files. Can't do "rm *' :-(

**Comment by novicecpp** [comment]
Yes, but we need sometime to figure it out how to fix this properly.

> I mention to Dario, review whether this WMArchive thing is really useful, in the end.

Aha, then, it is up to you @mapellidario. 

> You should not sped much time on this

I am just curious and have nice chat with Dario about this too, try to understand why it happen. I got your point that it is not so important, nothing break. :)

Also, you can delete file by `find <path> -type -f -delete`. `rm *` will report too much arguments.

**Comment by belforte** [comment]
I have no idea about `/etc/security/limit.d/99-htcondor.conf` either (part of htcondor install ?) but I think we have never been able to do `sudo su condor`. What bothers me is that IIUC just two schedulers out of 15 which have identical configuration show this. What's different on those ?
(btw on "good" scheds the  99-htcondor.conf has the `nofile unlimited` as well).

Yeah.. I know `find -delete` but removing those directories will be a pain anyhow, we've been through this already in the past :-(

**Comment by belforte** [comment]
I guess we should talk about this in a zoom chat at some point, the issue is getting too long !

**Comment by belforte** [comment]
cleaning of `/data/srv/WMArchiveWD/new` was also needed and now is in progress [1]. Let's see if it helps
[1] https://cms-logbook.cern.ch/elog/Analysis+Operations/3647

**Comment by novicecpp** [comment]
This is clue where `99-htcondor.conf` come from. Logs from run `puppet agent -t`.
```
Notice: /Stage[main]/Hg_vocms::Schedd_htcondor::Tuning/File[/etc/security/limits.d/99-htcondor.conf]/content:
--- /etc/security/limits.d/99-htcondor.conf     2022-03-30 14:40:04.360779990 +0200
+++ /tmp/puppet-file20220330-3347403-1lau7dr    2022-03-30 14:44:02.635911362 +0200
@@ -1,7 +1,7 @@
 # Custom HTCondor limits file
 # Raise number of allowed open files
-condor soft nofile 1048576
-condor hard nofile 1048576
+condor soft nofile unlimited
+condor hard nofile unlimited

 # Giving condor unlimited address space limit
 condor hard as unlimited

Info: Computing checksum on file /etc/security/limits.d/99-htcondor.conf
Info: /Stage[main]/Hg_vocms::Schedd_htcondor::Tuning/File[/etc/security/limits.d/99-htcondor.conf]: Filebucketed /etc/security/limits.d/99-htcondor.conf to puppet with sum d61483c0e20cf521a60705df8805a30cba27acded9157556c1bc8d5f3776043e
Notice: /Stage[main]/Hg_vocms::Schedd_htcondor::Tuning/File[/etc/security/limits.d/99-htcondor.conf]/content:

Notice: /Stage[main]/Hg_vocms::Schedd_htcondor::Tuning/File[/etc/security/limits.d/99-htcondor.conf]/content: content changed '{sha256}d61483c0e20cf521a60705df8805a30cba27acded9157556c1bc8d5f3776043e' to '{sha256}460b7c8d8dd868df95287ebf01a0c009e73aa445c20efccfd63c750253325286' (corrective)
```

Note that I changed values in `99-htcondor.conf`. It need to edit to start WMArchiveUploader with `systemctl` and make puppet not to report error.

**Comment by belforte** [comment]
Do you really want to keep a different `99-htcondor.conf` file in these two VM's ? Or am I confused ?

**Comment by novicecpp** [comment]
No, I just change values temporary (the diff in https://github.com/dmwm/CRABServer/issues/7159#issuecomment-1078379733 just to point out what I changed in this file), and then run `puppet agent -t` to restore the file back to the old one.
From puppet logs, `99-htcondor.conf` file come from `Hg_vocms::Schedd_htcondor::Tuning`, which we import [here in our puppet code](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/qa/code/manifests/modules/condor.pp#L44). 

After some digging here, I discovered that Saqip import it 5 month ago [here](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/88dd1792cfdcaf4b58cf776e013788bff744d25c).

**Comment by belforte** [comment]
maybe the way people configured this WMARchiveUploader daemon was somehow not perfect and not compatible with current SL7, e.g. condor daemon run happily as user condor, but use some different setup

**Comment by belforte** [comment]
should we move this to from @mapellidario to @novicecpp ? I am not capable to deal with systemctl properly here

**Comment by novicecpp** [comment]
Sure. I will take care of it.

**Comment by novicecpp** [comment]
I think the easiest way to workaround this is replcae `nofile` in `99-htcondor.conf` from `unlimited` to `1048576`, which we may not reach the point that single process use 1M fds simultaneously. We can fix it later if we know this data still be use by data pipeline somewhere.

**Comment by belforte** [comment]
yeah, that's easy but it is a bit like sweeping the dust under the carpet. Why do condor daemons start w/o problems even with the current `99-htcondor.conf` ?
But if we can't find out what is different between starting condor and starting WMArchiveUploader...
Maybe another option is to run this WMARchiveUploader with a different username, like `crabtw` or even `root` ? I have no idea why it runs as user `condor`. Looking e.g. at vocms059, files in `/data/srv/WMArchiveWD/new` are owned by `crabtw` so that user should be able to move/delete them as needed.

**Comment by belforte** [comment]
I tested on vocms0121 to ser `RUNUSER=crabtw` in `/etc/rc.d/init.d/WMArchiveUploader` and I could start the daemon and it seems to be running, although busy in I/O now and I can't verify progress yet.

**Comment by belforte** [comment]
hmmm.. daemon runs, but fails with a permission error

2022-04-12 23:15:40,812:ERROR:WMArchiveUploader,263:Error uploading docs: url=https://cmsweb.cern.ch:8443/wmarchive/data/, code=403, reason=Forbidden, headers={'Date': 'Tue, 12 Apr 2022 21:15:40 GMT', 'Connection': 'close', 'Content-Type': 'text/html', 'CMS-Server-Time': 'D=3675 t=1649798140801044', 'Server': 'Apache'}

I do not know if this could be due to the username change, odd that remove HTTP server may care for local username.  Must be the certificate..
```
[root@vocms0121 WMArchiveWD]# cat /data/certs//servicecert.pem|grep pem
[root@vocms0121 WMArchiveWD]# cat /etc/wmarchive.json |grep pem
 "UPLOAD_CERT" : "/data/certs//servicecert.pem",
 "UPLOAD_KEY" : "/data/certs//servicekey.pem",
[root@vocms0121 WMArchiveWD]# ls -l /data/certs//service*pem
-rw-r--r-- 1 condor root 2923 Jun 26  2021 /data/certs//servicecert.pem
-r-------- 1 condor root 1828 Aug  9  2017 /data/certs//servicekey.pem
[root@vocms0121 WMArchiveWD]# 

```

**Comment by belforte** [comment]
I did this
```
[root@vocms0121 WMArchiveWD]# chown crabtw:zh /data/certs//service*.pem
```
and now docs are being uploaded from vocms0121

I do not know if those `/data/certs/service*pem` files are used anywhere else on schedd. I am not feeling comfortable here.

**Comment by belforte** [comment]
we should try to run interactively as user condor to check what else may be affecting permission. Or maybe try same as above on vocms059 which was working until a few days ago.

**Comment by belforte** [comment]
can you pick it up from here, or should I investigate more ?

**Comment by novicecpp** [comment]
Ok. Leave it to me.

**Comment by belforte** [comment]
the permission error is puzzling, but we should be able to figure it out.

**Comment by belforte** [comment]
ooppsss !!!! thanks. Let's see that it works and then it will need to be puppettized

**Comment by belforte** [comment]
2 answers:
1. files are written by the PostJob.py script which DAGMAN executes whenever one job completes on grid
   https://github.com/dmwm/CRABServer/blob/11443806c0bbcacdcd8bc56f070f1dd9cb00335a/src/python/TaskWorker/Actions/PostJob.py#L2980
2.  it is always very difficult to be sure of "one thing never happens", but I can't think of anything else.
    Everything which has to do with processing a task uses the x509 proxy to communicate with cmsweb,
    I do not know of any other process which persists all of the time and needs its own credential other than this WMArchiveUploader. If there is... we'll find out.

**Comment by novicecpp** [comment]
This command need to apply manually in each machine:
```
chown crabtw:zh /data/certs/service*.pem
ls -alh /data/certs
systemctl stop WMArchiveUploader
puppet agent -t
systemctl start WMArchiveUploader
ps aux | grep WMArchiveUploader
tail -f /data/srv/WMArchiveWD/wmarchiveprocess.log
```

Sometime, `WMArchiveUploader.py` process does not get kill. You need to kill it manually (use SIGTERM to make it clear PID file and exit gracefully).

**Comment by belforte** [comment]
Was this the known stale lock file problem, or a new failure mode like process stuck in trying to reach crab wmarchive server? Sent from. Stefano's phone

**Comment by novicecpp** [comment]
> Was this the known stale lock file problem, or a new failure mode like process stuck in trying to reach crab wmarchive server? Sent from. Stefano's phone

Yes. `systemctl stop WMArchiveUploader` does not stop the process properly. The process was still there, and/or lock file was not removed.
Not hard to fix it, but manual intervention is required.

**Comment by novicecpp** [comment]
![Screenshot from 2022-06-03 14-50-01](https://user-images.githubusercontent.com/2346664/171857800-c3cf37f7-914b-4cc1-a029-735581d99cce.png)

All green. 
@belforte if there is no further concern, I will close this issue.

**Comment by belforte** [comment]
We need to fix process start to remove stale lock. I thought we had a gh issue already. If not, let's doSent from. Stefano's phoneOn Jun 3, 2022 14:54, Thanayut Seethongchuen ***@***.***> wrote:

Was this the known stale lock file problem, or a new failure mode like process stuck in trying to reach crab wmarchive server? Sent from. Stefano's phone

Yes. systemctl stop WMArchiveUploader does not stop the process properly. The process was still there, and/or lock file was not removed.
Not hard to fix it, but manual intervention is required.

**Comment by belforte** [comment]
Sure. Sent from. Stefano's phoneOn Jun 3, 2022 14:55, Thanayut Seethongchuen ***@***.***> wrote:

All green.
@belforte if there is no further concern, I will close this issue.

**Comment by novicecpp** [comment]
> We need to fix process start to remove stale lock. I thought we had a gh issue already. If not, let's do.

Done. Closing issue.
