### ISSUE TITLE
Cleanup temporary file in PublisherMaster

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7164]
the temporary file created here needs to be deleted after read,
so not to blow up /tmp space usage over time !!!
https://github.com/dmwm/CRABServer/blob/db170c6254b493b0c3a17e1cb3792957bdec2fc9/src/python/Publisher/PublisherMaster.py#L369-L380

**Comment by mapellidario** [comment]
After having merged #7177, can we close this issue? 

My bad, i should have mentioned this issue in the PR description!
