### ISSUE TITLE
when enough time has passed, remove all /home/grid/cmsxxxxx directories and remove the puppet code which creates them.

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7168]

**Comment by belforte** [comment]
Time to do this

**Comment by belforte** [comment]
@novicecpp  I see you are giving final touches (?) to puppet refactoring. We have this minor cleanup to do which I did not want to push while all that work is in progress. Is now a good time ? Should I try to make a PR in puppet repo to verify that I can find my way around the new setup ?

**Comment by belforte** [comment]
wel..  I think I got the code OK, but did not know how to make a Merge request, so qa is changed already

**Comment by novicecpp** [comment]
It is up to you. Either,
- Merge to `crabdev_schedd` branch and test in `crab-preprod-scd03`. Feel free to `git reset` to your feature branch.
- Merge to `crabdev_schedd` branch and pull `vocms059` to `crabdev_schedd` env. 
- Merge to `qa` (not reccommend, `qa` intend to be a stable environment)

**Comment by belforte** [comment]
I had siimply forgotten how to make a fork, and that I had a fork already :( 
thanks for clarifying how to use `cradev_schedd` branch

**Comment by belforte** [comment]
anyhow new qa runs OK on vocms059

**Comment by belforte** [comment]
* puppet code for dir creation removed from `qa` and `crabdev_schedd` branches
* next:
- [ ] remove all dirs on `crab-preprod-scd03` and `vocms059` and see what happens
- [ ] push changes to master
- [ ] remove `/home/grid/cms*` everywhere

**Comment by belforte** [comment]
@novicecpp I forgot where we stand on this. I think that puppet change in `qa` is well validated now and it can be pushed to `master`. Can you do that ?

**Comment by novicecpp** [comment]
Let me do it after I came back to CERN.

**Comment by novicecpp** [comment]
The puppet changes were in master two days ago, so all machines are applied by now.

@belforte How do you remove `/home/grid/cms*`  when you run in `vocms059` machine? 
Did you just ssh to the machine and run `rm -rf /home/grid/cms*`

**Comment by belforte** [comment]
>  @belforte How do you remove /home/grid/cms* when you run in vocms059 machine?
>  Did you just ssh to the machine and run rm -rf /home/grid/cms*?

I am afraid so. If there's a better way, I do not know it.
Hopefully those directories are empty by now, but maybe some files escaped deletion by our crontab

**Comment by novicecpp** [comment]
It is not that bad. I will do it.

**Comment by novicecpp** [comment]
Done.
