### ISSUE TITLE
Develop a "What CRAB is used for" historical dashboard

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7169]
see SummerStudent work proposal #1 in https://docs.google.com/document/d/1Rk3uxp2UdGMD3lko8n2Mp4jyOn5Av4YfoakvExub71c/edit

We'd like to have a "persistent" way to ask questions like "how much MC was run via CRAB in last N months ? How much CPU did it take ? How much analysis ? On which datasets ?" going to details which are not available in current job historical dashbaord but need to go back to information archived in HDFS via Spark.

Starting point is this work from Diego C. reported on May 15, 2019 in https://indico.cern.ch/event/820760/contributions/3430997/attachments/1844840/3030313/ClassAds-Studies.pdf

**Comment by novicecpp** [comment]
To-do:
- [ ] Waiting for https://github.com/dmwm/CRABServer/issues/7798 to close.

**Comment by novicecpp** [comment]
Done
