### ISSUE TITLE
Disk space on root drive in crab-dev-tw01 is too low.

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7182]
We get disk alert from `crab-dev-tw01` here:
```plaintext 
Thu Mar 24 13:00:02 CET 2022 : [CRITICAL_PATH@crab-dev-tw01.cern.ch](mailto:CRITICAL_PATH@crab-dev-tw01.cern.ch):
/dev/vda2        20G   17G  3.7G  82% /
overlay          20G   17G  3.7G  82% /var/lib/docker/overlay2/824419019a731d552a0bf0b7abc8075c33772759bb58719fc928446b727be38d/merged
overlay          20G   17G  3.7G  82% /var/lib/docker/overlay2/11b43c47e427af558a33967f650482642947a412b324853dc2a9abcbd042cb33/merged
```

I free disk space up by prune all docker image that not use (from Stefano suggestion).
We have cron that prune image older than 1 week: https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/master/code/manifests/profiles/crabtaskworker.pp#L262.
Checking disk space for root is only 20GB which is too low. 

I will try to increase it to, at least, 50GB.
And I think it is good to filter `overlay2` out when we checking free space in `diskTest.sh`.

**Comment by belforte** [comment]
IIRC 20GB is the max local disk for a VM. But we should, like done on other TW machines, direct overalay2 to /data disk where we have 500GB !

**Comment by belforte** [comment]
I guess that until recently crab-derv-tw01 was used lightly, mostly to change code in /data/repos and test, with rare container changes, so the different setup was not noticed. Sorry.

**Comment by belforte** [comment]
hmm... sorry, sounds like my memory is confused, forget last comment. I have this on my personal VM where I have a 50B CEPH volume
```
belforte@stefanovm/~> sudo ls -l /var/lib/docker
lrwxrwxrwx. 1 root root 14 May  6  2021 /var/lib/docker -> /vmdata/docker
belforte@stefanovm/~> df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G   12G  8.2G  60% /
belforte@stefanovm/~> df -h /vmdata
Filesystem      Size  Used Avail Use% Mounted on
/dev/vdb         50G   19G   32G  37% /vmdata
belforte@stefanovm/~> 
```
but am not sure about crab-* machines.

**Comment by belforte** [comment]
>  And I think it is good to filter overlay2 out when we checking free space in diskTest.sh.

?? do you mean counting the space it uses as free ? or just a matter of how to compute the percentage ?
The 80% alert threshold is not a precise value, only to give us a heads up before we are in a critical situation, I'd go for whatever is simpler

**Comment by novicecpp** [comment]
> but am not sure about crab-* machines.

dev01 => 20GB,
preprod01 => 80GB,
prod01 => 160GB,
This is why I think we can increasing it somehow. Need to check how to do.

**Comment by belforte** [comment]
available local disk  depends on the VM flavour in openstack. It is not a free parameter, since in the end it is a fraction of the local disk of the hypervisor (underlaying "bare metal"). While mounted CEPH volumes can be anything.

**Comment by novicecpp** [comment]
> I meant to say that I am not sure if we directed overlay2 to /data on crab* machines before, sorry for not being clear, and for my memory confusion.

Docker daemon still use `/var/lib/docker` (included `overlay2`) as data dir in all VM. But I see some docker data in `/data` directory. Maybe you tried it sometime ago and revert it back. Digging in the puppet repos may find answer :)

> ?? do you mean counting the space it uses as free ? or just a matter of how to compute the percentage ?
The 80% alert threshold is not a precise value, only to give us a heads up before we are in a critical situation, I'd go for whatever is simpler

Sorry. I mean, we should add `overlay2` to this line in [diskTest.sh](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/95691b81aef24983d81b66984be6df9eb0c7ad02/code/files/profiles/crabschedd/diskTest.sh#L24) to ignore `overlay2` report by `df` command.

**Comment by belforte** [comment]
On 24/03/2022 22:10, Thanayut Seethongchuen wrote:
> Sorry. I mean, we should add |overlay2| to this line in diskTest.sh <https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/95691b81aef24983d81b66984be6df9eb0c7ad02/code/files/profiles/crabschedd/diskTest.sh#L24> to ignore |overlay2| report by |df| command.
> 

I get it now, thanks. But currently there's no |overlay2| in `df -h` output anyhow

**Comment by novicecpp** [comment]
It only show when run `df` with root privilege.

Anyway, I close this issues as "won't do" because it too much work for too little gain.
If alert is back, just clear docker disk with `docker system prune` and Taskworker/Publisher logs.

**Comment by belforte** [comment]
anyhow this is only a problem on dev instance. production TW has 160GB as local disk
