### ISSUE TITLE
use SCRAM_TO_OS mapping from WMCore

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7188]
replace this piece of code
https://github.com/dmwm/CRABServer/blob/bdbb9be0f6c1c9dc64d1869a831675fdf8cd8046/src/python/TaskWorker/Actions/DagmanCreator.py#L494-L501
with calls to common functions in WMCore, see https://github.com/dmwm/WMCore/pull/11060

See also MatterMost fragment around this comment https://mattermost.web.cern.ch/cms-o-and-c/pl/its6ik3apfn1zrhqjohd7pj3ry

We need to clarify if `REQUIRED_OS` (only thing set by CRAB atm) is enough.

**Comment by belforte** [comment]
@amaltaro I do no understand the relative role of `scramArchtoRequiredOS` and `scramArchtoRequiredArch` since CRAB does not define any Arch request atm.  Let's see if @mmascher clarifies.

**Comment by belforte** [comment]
Dario, take it easy and do not rush to a fix. The idea was exactly to think about what is the best way ahead, and to include you in the the overall debate on how we define where to run.

**Comment by mapellidario** [comment]
@belforte, i think that mentioning this in #7191 made GH automatically close this issue, too. Please re-open it if you think that we should continue evaluating how to address this issue
