### ISSUE TITLE
file check_sum in DBS is string not int

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7200]
with move to new DBS server in GO, type checking will be more strict.
For some historicval reason CRAB Publishing code send file_checksum as integer, see this print fragment
```
           'logical_file_name': '/store/user/belforte/GenericTTbar/Stefano-Test-220331/220401_093832/0000/kk_1.root'},
           {'adler32': '48bc3f94',
            'check_sum': 282054062,
            'event_count': 300,
            'file_lumi_list': [{'lumi_section_num': 592, 'run_num': 1}],
            'file_size': 561304,
            'file_type': 'EDM',
            'logical_file_name': '/store/user/belforte/GenericTTbar/Stefano-Test-220331/220401_093832/0000/kk_2.root'}],
```
But in DBS schema it is defined as string
https://github.com/dmwm/dbs2go/blob/4fd477b845886b024ddc2efc46d6af317cb49d3e/static/schema/DDL/create-oracle-schema.sql#L727
and it always was
https://github.com/dmwm/DBS/blob/14df8bbe8ee8f874fe423399b18afef911fe78c7/Schema/DDL/create-oracle-schema.sql#L727
and now this is enforced in the server code as well
https://github.com/dmwm/dbs2go/blob/811c97749915aadd586e4a94d1e8b18cf7b31528/dbs/files.go#L239

**Comment by belforte** [comment]
Publisher code does not set type for this, so it must be coming as int from filemetadata retrieve :-(

**Comment by belforte** [comment]
the problem is deep at the core in the filemetadata DB defintion:
https://github.com/dmwm/CRABServer/blob/6a7ac86dbb9f3cfec87912dbb3bef4f1a7e2c07e/src/python/Databases/FileMetaDataDB/Oracle/Create.py#L40-L42

A proper fix would require to change that and result in backward-not-compatible code.
As a start I can force a string in the JSON passed to DBS block insert API, but maybe we should go for a proper fix.

**Comment by belforte** [comment]
We can go in steps, since pyhon3's str() is idempotent:
1. convert to str in TaskPublish
2. convert to str in DataFileMetadata https://github.com/dmwm/CRABServer/blob/6a7ac86dbb9f3cfec87912dbb3bef4f1a7e2c07e/src/python/CRABInterface/DataFileMetadata.py#L52 once this is in production we hack in 1. becomes not-needed.

it is much more difficult to change type in DB since it requires chaging REST and code which writes to REST (PostJob) which needs to be done ayncronously via some backward comaptible trick. At the moment I do not see anything better than adding one column with the cksum as a string at the same time as  changing https://github.com/dmwm/CRABServer/blob/6a7ac86dbb9f3cfec87912dbb3bef4f1a7e2c07e/src/python/CRABInterface/RESTFileMetadata.py#L14 to support both the "old" int and an optional "new" string. The migrate PostJob over the course of a couple months. And finally cleanup.

@mapellidario @novicecpp I am open to suggestions

**Comment by belforte** [comment]
first thing is of course to verify that 1. above is safe for DBS, which it should.

**Comment by mapellidario** [comment]
I am always very conservative when it comes to changes in order to adapt to surrounding systems. I prefer changing our code as least as possible. 
Changing our schema every time someone around us requires a new/different type seems a bit of a work, especially it if would make our code backward-incompatible. I would leave our logic intact and only change the type as late as possible, in this case only when we pass data to DBS.

However, it is also true that we drop our data after 30d, so any data inserted in the DB is temporary by default and we can plan a schema update around that. I am not a fan of such changes, but it would be a nice didactic experience! So, i am in favor of

> At the moment I do not see anything better than adding one column with the cksum as a string [...]

but I hope we will not have do to this too often!

**Comment by vkuznet** [comment]
at least, you should put in BOLD comment about type conversion changes in CRAB code and explain the reason of such conversion. Correct data-type is serious issue, and data-types mis-match in different DBs can lead to different issues if these data are extracted and analyzed. It is less an issue if data is purely local though.
