### ISSUE TITLE
refactor retrieve of filemetadata

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7204]
We clearly suffer of a cmsweb-independend problem with GET filemetadata since at time Publisher needs to retrieve >100MB in one call which has  a high chance of timing out at 5min. 
The problem starts with the fact that all filemetadata for a given task are retrieved in one operation. For tasks with thousands of jobs and large list of lumis for each file this leads to huge JSON structures.

Solution is not obvious.

This is not really a bug (things are working atm) but as datasets with many lumis become more common, it could be a show stopper.

We may need to find a solution before it becomes critical.

**Comment by mapellidario** [comment]
I would start removing the hack needed to make Publisher-py2 compatible with REST-py3, https://github.com/dmwm/CRABServer/blob/f608e7ebcfde7b9bd39dc213ec1be9dce8380093/src/python/CRABInterface/DataFileMetadata.py#L61

If we see that the performance does not improve much, then we can spend more time thinking about some refactoring.

**Comment by belforte** [comment]
thanks for remembering this. Yes !! go ahead.

**Comment by belforte** [comment]
We definitely have serious problems here, filemetadata retrieve can be up to serveral 100MB's and that appears to stall things in the FE with spiraling down very bad effects
https://mattermost.web.cern.ch/cms-o-and-c/pl/cgirkaxpyffyxk8so9kzwrypse and following entries

**Comment by mapellidario** [comment]
Another option that came out of today's brainstorming was to compress the data streamed. I run some tests and this looks like a promising option:

considering the task `220503_132244:mabarros_crab_DR_Jpsi_25to45_Dstar_DPS_2018_13TeV_03-05-2022`, its filemetadata weights 174MB. I run some benchmarks on lxplus to measure how much we would save:

| program | compression level | final size (MiB) | fraction of original size | time taken |
|-|-|-|-|-|
|  gzip | 1 |  29.5 | 17% | 3s |
|  gzip | 5 |  24.2 | 14% | 5s |
|  gzip | 9 |  21.5 | 12% | 30s |
|  zstd | 1 |  29.5  | 17% | 2s |
|  zstd | 3 |  20.8 | 12% | 2s |
|  zstd | 5 |  19.6  | 11% | 2s |
|  zstd | 8 |  17.7  | 10% | 3s |
|  zstd | 10 |  18.4  | 10% | 5s |
|  zstd | 12 |  18.7  | 11% | 9s |
| lz4 | 1 | 43.2 | 25% | 3s |
| lz4 | 5 | 38.1 | 22% | 4s |
| lz4 | 10 | 36.6 | 21% | 12s |

zstd with compression level 5 or 8 seems to be the sweet spot for us.


<details><summary>More info</summary>
run the commands with

```bash
# replace `$N` with the compression level
time gzip -f -S .$N.tgz -$N  input.json
time zstd -$N -o output.json.$N.zst input.json
time lz4 -f -$N input.json output.json.$N.lz4
```

get the task with:

```bash
> time curl --cert $X509_USER_PROXY --key $X509_USER_PROXY  "https://cmsweb-testbed.cern.ch/crabserver/prod/filemetadata?taskname=220503_132244%3Amabarros_crab_DR_Jpsi_25to45_Dstar_DPS_2018_13TeV_03-05-2022&filetype=EDM" > filemetadata_mabarros.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  173M    0  173M    0     0  2455k      0 --:--:--  0:01:12 --:--:-- 2394k
curl --cert $X509_USER_PROXY --key $X509_USER_PROXY  >   0.53s user 7.02s system 9% cpu 1:22.35 total
>
```

reading the file from disk takes 0.5s

```plaintext
> time dd if=filemetadata_mabarros.json of=/dev/null
356116+1 records in
356116+1 records out
182331422 bytes (182 MB, 174 MiB) copied, 0.426413 s, 428 MB/s
dd if=filemetadata_mabarros.json of=/dev/null  0.12s user 0.31s system 99% cpu 0.431 total
>
```

measure file size in MiB with

```plaintext
> dc --expression="2 k $(du filename.ext | awk '{print $1}') 1024 / p"
```

</details>

**Comment by belforte** [comment]
I think that retrieving only the needed data is easier to implement and a saner approach than retrieving hundreds of MB's of useless stuff and compressing it. Let's try to do the right thing then, and come back to other options only if that fails.
One useful think to pursue in parallel to my looking at code is to investigate whether we need a new index in the DB when making a new query like
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/Databases/FileMetaDataDB/Oracle/FileMetaData/FileMetaData.py#L42
but adding a `fmd_lfn` in the WHERE . I think we'll need to make one SQL query for each LFN, but that may be my ignorance of how eactly this works https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/REST/Server.py#L2120

**Comment by belforte** [comment]
I found that we already debated this 2 years ago, and at the time was scared of touching REST code https://github.com/dmwm/CRABServer/issues/6124
I guess now the need is more clear and I am more familiar with REST.

**Comment by vkuznet** [comment]
@belforte quick look at your code reveals the following (I think it is an issue):
- the WMCore/REST/Server.py `def query` returns the generator to ORACLE cursor, see https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/REST/Server.py#L2165
- the `rows` function is defined here https://github.com/dmwm/WMCore/blob/3882e1ff7c55fd9a3054807f9ab8aebd8029d769/src/python/WMCore/REST/Server.py#L2387
- The CRAB server code `get` API calls `self.jobmetadata.getFiles` API here https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/RESTFileMetadata.py#L104
- the `getFiles`API is defined here: https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/DataFileMetadata.py#L27
- now, if you look at what `getFiles` API is doing it reads rows here https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/DataFileMetadata.py#L34 and then process every single row, see lines 35-98. Now, since query is a generator, your code still holding ORACLE connection while doing the processing. And, if you look at lines 35-98 you have four nested for loops (!!!), so your code is O(N^4) function. In other words, your ORACLE connection is holding to `N^4` time where N is number of lfns in a task. This explains **WHY** your connection taking so much time.

**How to fix this?**
You should load all ORACLE results before making four for loops, e.g.
```
# instead of 
        rows = self.api.query(None, None, self.FileMetaData.GetFromTaskAndType_sql, **binds)
        for row in rows:
         ..... # your entire block which makes three additional for loops

# you should do
        # get all rows content in local variable and release ORACLE connection
        rows = [r for r in self.api.query(None, None, self.FileMetaData.GetFromTaskAndType_sql, **binds)]
        # may be add here call to release explicitly ORACLE connection (I don't know if WMCore provides this API
        # but may be it should be added)
        # then you can iterate over results
        for row in rows:
```
By reading all rows from ORACLE you can release the ORACLE connection. But this will increase your process RAM since your ORACLE rows will be held in your function. Then, you can iterate (again try to remove four for loops) and yield results back to upstream/client.

**Comment by vkuznet** [comment]
And, in fact you have similar problem in many places of CRABServer code. I just grep through your code and searched for `self.*query` pattern and here are the results:
```
./src/script/Monitor/GenerateMONIT.py
164:            result = self.coll.query(htcondor.AdTypes.Schedd,

./src/python/TaskWorker/Actions/PostJob.py
1056:                self.logger.info("Using the cache since it is up to date (last_query=%s) and it is after we submitted the transfer (aso_start_timestamp=%s)", last_query, self.aso_start_timestamp)
1067:                    self.logger.debug("Changing query_view back to true")
1874:                self.logger.info('History file not found in ./finished_jobs. Create it by querying schedd')

./src/python/TaskWorker/Actions/DagmanSubmitter.py
326:            self.logger.debug("Duplicate check is querying the schedd: %s", rootConst)

./src/python/CRABInterface/DataFileMetadata.py
34:        rows = self.api.query(None, None, self.FileMetaData.GetFromTaskAndType_sql, **binds)
134:        row = self.api.query(None, None, self.FileMetaData.GetCurrent_sql,

./src/python/CRABInterface/DataWorkflow.py
64:        return self.api.query(None, None, self.Task.GetTasksFromUser_sql, username=username, timestamp=timestamp)
261:        row = self.api.query(None, None, self.Task.ID_sql, taskname = workflow)
335:                origValues = next(self.api.query(None, None, self.Task.GetResubmitParams_sql, taskname = workflow))
389:        row = self.api.query(None, None, self.Task.ID_sql, taskname = workflow)
420:        row = self.Task.ID_tuple(*next(self.api.query(None, None, self.Task.ID_sql, taskname=workflow)))

./src/python/CRABInterface/RESTServerInfo.py
39:            next(self.api.query(None, None, "select NULL from DUAL")) #Checking database connection

./src/python/CRABInterface/RESTFileTransfers.py
295:            rows = self.api.query(None, None, self.transferDB.GetVOMSAttr_sql, **binds)
357:                rows = self.api.query(None, None, sqlQuery, **binds)
378:                rows = self.api.query(None, None, sqlQuery, **binds)
395:                rows = self.api.query(None, None, sqlQuery, **binds)
402:            rows = self.api.query(None, None, sqlQuery, **binds)
408:            rows = self.api.query(None, None, sqlQuery, **binds)
411:            rows = self.api.query(None, None, self.transferDB.GetActiveUsers_sql, asoworker=asoworker)
414:            rows = self.api.query(None, None, self.transferDB.GetActiveUserPublication_sql, asoworker=asoworker)

./src/python/CRABInterface/RESTTask.py
57:        rows = self.api.query(None, None, self.Task.ALLUSER_sql)
62:        rows = self.api.query(None, None, self.Task.IDAll_sql, taskname=kwargs['workflow'])
69:        rows = self.api.query(None, None, self.Task.TASKSUMMARY_sql)
84:            row = next(self.api.query(None, None, self.Task.QuickSearch_sql, taskname=kwargs["workflow"]))
102:        rows = self.api.query(None, None, self.Task.TaskByStatus_sql, username_=kwargs["username"], taskstatus=kwargs["taskstatus"])
112:            row = self.Task.ID_tuple(*next(self.api.query(None, None, self.Task.ID_sql, taskname=workflow)))
122:            row = next(self.api.query(None, None, self.Task.GetPublishUrl_sql, taskname=kwargs['workflow']))
140:            row = self.Task.ID_tuple(*next(self.api.query(None, None, self.Task.ID_sql, taskname=workflow)))
181:        rows = self.api.query(None, None, self.Task.CountLastTasksByStatus, minutes=kwargs["minutes"])
193:        rows = self.api.query(None, None, self.Task.LastFailures, minutes=kwargs["minutes"])
221:#        rows = self.api.query(None, None, "SELECT tm_task_warnings FROM tasks WHERE tm_taskname = :workflow", workflow=workflow)#self.Task.TASKSUMMARY_sql)
222:        rows = self.api.query(None, None, self.Task.ID_sql, taskname=workflow)#self.Task.TASKSUMMARY_sql)
254:#        rows = self.api.query(None, None, "SELECT tm_task_warnings FROM tasks WHERE tm_taskname = :workflow", workflow=workflow)#self.Task.TASKSUMMARY_sql)
255:        rows = self.api.query(None, None, self.Task.ID_sql, taskname=workflow)#self.Task.TASKSUMMARY_sql)
332:        row = self.Task.ID_tuple(*next(self.api.query(None, None, self.Task.ID_sql, taskname=workflow)))

./src/python/CRABInterface/RESTWorkerWorkflow.py
91:        rows = self.api.query(None, None, self.Task.GetReadyTasks_sql, **binds)

./src/python/CRABInterface/RESTFileUserTransfers.py
239:            return self.api.query(None, None, self.transferDB.GetById_sql, **binds)
258:            return self.api.query(None, None, self.transferDB.GetTaskStatusForTransfers_sql, **binds)
270:            return self.api.query(None, None, self.transferDB.GetTaskStatusForPublication_sql, **binds)

./src/python/CRABInterface/HTCondorDataWorkflow.py
45:        row = next(self.api.query(None, None, self.Task.ID_sql, taskname = workflow))
56:            self.logger.debug("Running condor query for task %s." % taskName)
62:                self.logger.exception("Exception while querying schedd")
105:        row = next(self.api.query(None, None, self.Task.ID_sql, taskname = workflow))
112:        rows = self.api.query(None, None, self.FileMetaData.GetFromTaskAndType_sql, filetype = ','.join(filetype), taskname = workflow, howmany = howmany)
140:        row = next(self.api.query(None, None, self.Task.ID_sql, taskname = workflow))
154:        rows = self.api.query(None, None, self.FileMetaData.GetFromTaskAndType_sql, filetype='EDM,TFILE,FAKE,POOLIN', taskname=workflow, howmany=-1)
196:        row = self.api.query(None, None, self.Task.ID_sql, taskname = workflow)
498:        res = list(self.api.query(None, None, self.transferDB.GetTaskStatusForPublication_sql, **binds))

./scripts/get_pool_status.py
23:        for slot in self.coll.query(htcondor.AdTypes.Startd, 'AccountingGroup isnt undefined && GLIDEIN_CMSSite isnt undefined', ['GLIDEIN_CMSSite', 'GLIDEIN_SEs', 'AccountingGroup']):
48:        for entry in self.coll.query(htcondor.AdTypes.Any, 'MyType =?= "glideresource"', ["GlideFactoryMonitorStatusIdle", "GLIDEIN_CMSSite", "GlideFactoryName"]):

./test-old/python/CRABInterface_t/RESTFileUserTransfers_t.py
105:                result = self.server.get('/crabserver/dev/fileusertransfers', data=encodeRequest({'subresource': query,
```
Since I don't see that you actually read results from ORACLE when using `self.xxx.query` method all of this instances inherit the same problem of not releasing ORACLE connection back to the pool until  generator will be exhausted through iteration. And, if your iteration is not trivial (i.e. takes time, construct new objects, etc.) it will hold your ORACLE connections.
```

**Comment by vkuznet** [comment]
@belforte I only shown the root of the problem. How you'll address it is up to CRAB team. Of course, changing ORACLE query to provide final result set and then stream it back to client is the best and cheapest solution (in terms of connection and resources). But you can quickly address of connection issue by using trick I shown with fetching results from query API via list comprehension, and keep changes to a minimum.

**Comment by belforte** [comment]
as warming up I modified REST so that one can get FMD for just one file. NOw in my branch https://github.com/belforte/CRABServer/tree/support-list-of-LFNs-for-FMD-GET
I will look next into passing a list of files, but I have not been able to find an example in other API's.
Will be worth to check what happens with a loop in file names, all in all most of the times it is O(100) or less.

**Comment by belforte** [comment]
thanks Dario !

**Comment by belforte** [comment]
I am having a look at how to retrieve FMD for several files (i.e. several DB rows) in one call.
But in spite of the fact that our basic calls go via some `executemany` function
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/RESTBaseAPI.py#L68
https://github.com/dmwm/WMCore/blob/61f35e0d323d3415fc465f065e7865932f23beba/src/python/WMCore/REST/Server.py#L2102
The only example which I found in CRAB code of using lists in queries (besides insert/read a list of things in one column as a blob or a long varchar) is this where the CRABServer code makes an explicit loop on the input list, calling the oracle connection N times with a single argument every time
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/RESTFileTransfers.py#L159-L166

So I will look into imitating that API and looping instead on `self.api.query` i.e. the same DB call I do now
https://github.com/belforte/CRABServer/blob/9ef158245b5048611b90bdfd23d560f9f640dac9/src/python/CRABInterface/DataFileMetadata.py#L39-L40

**Comment by belforte** [comment]
OK. I have introduced a new argument for GET FILEMETADATA: `lfnList` to be used in alternative to `filetype` (if you know the list of files for which you want the metadata, there's no need to indicate if you want one filetype or another) and of course `howmany` is ignored in this case.
Usage is like:
```python
dataD={}
dataD['taskname'] = task
dataD['lfnList'] = [file1, file2]
# but followind would work as well
#dataD['lfnList'] = file3
data = encodeRequest(dataD)
try:
    result = crabServer.get(api='filemetadata', data=data)
```
perfectly similar to current one:
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/Publisher/PublisherMaster.py#L297-L303

**Comment by belforte** [comment]
- [ ] also need to take care of FMD retrieval by CRAB Client during `crab report` https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/HTCondorDataWorkflow.py#L151-L155

**Comment by belforte** [comment]
looking into comparing old and new way of doing filemetadata get in Publisher, I discovered that new API returns metadata which have
```python
'filetype': None
```
instead of

```python
'filetype': 'EDM'
```
investigating

**Comment by belforte** [comment]
ok, problem is that I did not change this piece of code
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/DataFileMetadata.py#L37-L41
when `filetype` is not an argument of the `getFiles` function, it needs to come from `rows`

**Comment by belforte** [comment]
@mapellidario IIUC we can now remove this piece of code
https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/CRABInterface/DataFileMetadata.py#L61-L96
But I am very confused in these days, so please help me make sure what the condition for doing this is.
