### ISSUE TITLE
improve site placement for tape-recall

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7207]
see:
https://cms-talk.web.cern.ch/t/running-on-not-fully-dataset-available-on-disk-with-crab/8893/10

**Comment by belforte** [comment]
proposal:
 dataset < 10TB like now
 dataset > 10TB
 make a list of RSEs with at least 1PB disk and 100TB free
 pick datasetsizeintb/10 SEs at randome from that list

**Comment by belforte** [comment]
possible optimizations:
* use size/10+1 or +2, do not "force 10TB at each site" 
* skip RSE's which are currently full (`ddm_quota<1TB`)

**Comment by nsmith-** [comment]
This looks I believe rather similar to the MSTransferor logic, so that's good. Though MSTransferor makes a rule per block so it can (eventually) clean up at a finer level of granularity. For CRAB I think we want to relax the cleanup with the hope the recalled data may be used again soon.

**Comment by belforte** [comment]
thanks @nsmith- CRAB rules expire in 7 days, upon your advice, and work finely in that respect so fare, let's not worry about cleanup.

**Comment by nsmith-** [comment]
https://monit-grafana.cern.ch/d/mtQFDScGk/cms-fts-metrics?orgId=11&refresh=5m&var-vo=cms&var-group_by=activity&var-src_rse=All&var-dst_rse=All&var-fts_server=All&var-activity=Analysis%20Input&var-protocol=All&var-bin=1d&from=now-90d&to=now&viewPanel=13 gives some idea how much recall is happening. If it gets too large, one might consider re-tuning the lifetime or trying to get smarter. (btw why is there a one month gap?)

**Comment by belforte** [comment]
no idea here about the gap

**Comment by mapellidario** [comment]
It seems nobody asked to process data that was not on disk in those days

**Comment by belforte** [comment]
After discussion with @KatyEllis and @dciangot we think that it is better to try to consolidate tape recall at only one or max. two sites.

**Comment by belforte** [comment]
here's the current algorithm (not deployed in production yet)
https://github.com/dmwm/CRABServer/blob/5d445711be6aee49192c1f2aafb3d739a91d5713/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L155-L183

**Comment by belforte** [comment]
reference, current status of Rucio RSE's
```
                     NAME             Size(PB)     ddm_quota(TB)
               T2_US_Wisconsin         3.5         334
                T2_FR_GRIF_LLR        1.45         136
                T2_US_Nebraska       4.324         411
                    T2_IT_Bari         2.0         204
                     T2_US_MIT       4.829         363
                    T2_BE_IIHE       3.925         381
               T2_FR_GRIF_IRFU         1.3         119
           T2_UK_London_Brunel         0.8         432
                 T2_US_Florida        3.52         387
                    T2_IT_Rome        2.35         613
                    T2_CH_CSCS        2.43         627
               T1_US_FNAL_Disk       28.75        2601
                    T2_DE_DESY         5.5         335
               T1_IT_CNAF_Disk         9.4         763
             T2_UK_SGrid_RALPP        1.55         140
                    T2_TR_METU       0.925         158
                  T2_US_Purdue        2.99         214
                T1_ES_PIC_Disk         3.1         368
            T1_FR_CCIN2P3_Disk         8.0         840
                T1_UK_RAL_Disk        5.25         456
               T2_UK_London_IC         6.3        1365
                     T2_BE_UCL       1.757         151
                  T2_BR_SPRACE         2.0         175
                    T2_DE_RWTH        2.04         178
                    T2_RU_JINR        1.57         154
                 T2_EE_Estonia        1.38         116
                    T2_IN_TIFR        11.0        5135
                     T2_PK_NCP       0.401         203
                T1_DE_KIT_Disk        6.75         641
                    T2_IT_Pisa         2.5         236
                 T2_IT_Legnaro         3.6         352
                  T2_ES_CIEMAT         2.3         194
                    T2_FR_IPHC        1.75         151
              T2_US_Vanderbilt       5.676         181
```

**Comment by dciangot** [comment]
I agree with 1-3. About 4 I just want to make sure that we are not overdoing. I mean, if that cases are rare enough, can we say that keeping the datasets spread like they are right know should not impact that much overall? Or are they the dominant contribution on the HTC clustering problem?

**Comment by belforte** [comment]
I see your point, but still would not want to see a 60TB AOD spread over 30+ sites. We have no big operational problems, and it is very difficult to quantify things which "simply annoy" like this (3TB dataset on 53 sites)
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FCharmonium%2FRun2018A-UL2018_MiniAODv2-v1%2FMINIAOD . But looking forward I'd like to start introducing a small push toward "less dispersion".

**Comment by belforte** [comment]
a rea life example (a dataset which I got from some user task):
/EGamma/Run2018C-12Nov2019_UL2018-v2/AOD
46TB over 35 sites :-(
https://cmsweb.cern.ch/das/request?instance=prod/global&input=site+dataset%3D%2FEGamma%2FRun2018C-12Nov2019_UL2018-v2%2FAOD

**Comment by dciangot** [comment]
Yeah, otoh I wonder how much error prone can be to pre-select a subset of RSE based on their current free space. In principle I agree with you, and it should be a pretty safe way to proceed, but it was something worth to be thought more then twice ^^

**Comment by belforte** [comment]
> I wonder how much error prone can be to pre-select a subset of RSE based on their current free space.

it mostly depends on details of Rucio working. What happens when rules are created ? Does it immediately updates the used space accounting at destination site(s) to reserve space ? Or does it simply queue transfers, which then overlap with other  requests created later and possibly lead to hitting max limit ?

**Comment by belforte** [comment]
I think I need to add code to deal with the extreme situation that there's no site with 100TB of free space. Hope it does not happen, but code should not crash.

**Comment by KatyEllis** [comment]
I was curious about the low amount of space shown as 'free' according to the ddm_quota in your table. I think this value may be calculated incorrectly, and not take into account the space taken by unlocked/dynamic data at a site, which in theory should make way for any new data arriving on site. For example at RAL, according to Nick's bar chart, which is shown at the CompOps meeting every week, about 50% of space at RAL (around 2.6PB) is 'dynamic'. But according to Rucio, the ddm_quota is only about 400TB. I'm following up with data management. Maybe we have more space available than we think.

**Comment by KatyEllis** [comment]
In terms of Rucio's management of space, it should add the space taken by each rule, even if transfers are incomplete. Rucio should refuse to create any rule that would cause that RSE to go over the available space. I guess the exception to this is for subscriptions, or containers, where the full data size is not defined when the rule is created...

**Comment by belforte** [comment]
AFAIU (from Felipe who pointed me to the code which computes it),. ddm_quota is basically the disk amount which the sites declares available to CMS Data Ops (not the pledge.. let's not go there) minus the disk quick RUcio knows it is using (rucio quota) - 15TB (some safety ?)
https://github.com/dmwm/CMSRucio/blob/4bbe00403e0401585c9d42d887f1acce20dc78f7/DMOps/dynamic_ddmquota_update.py#L34-L46

IIUC that's what Ops usually use as weght in dataset placing. Maybe I am wrong in calling it "free space" in deciding which sites as free disk for new data ! But I am not sure it other metrics are available as RSE attributes, I surely do not want to list all locks.

**Comment by belforte** [comment]
More on "ddm_quota vs. Nick's bar chart etc.": it would be great to have a good description of how we manage data, what rules we use etc. etc. !!! But in the meanwhile I suspect that we really consider dynamic space as "used", and only ddm_quota available for writing data, as ddm_quota is fille, the amount of disk used will rise above the 90% watermark and Rucio will deletd unlocked files (if any) bringing again ddm_quota to the previous value. The easy way to "see" that we have more space avaiable, would be to be more aggressive with the watermark, i.e. lower the `> target occupancy` tick in Nick's chart. That will also get rid of the "old replicas from when dataset was created which are lingering around doing more harm than good". But I suspect that this is a difficult topic to talk about.

**Comment by belforte** [comment]
sorry, another comment:
somehow looks like "only Nick has some magic code which continuously update the amount of Locked/Dynamic/.... space count for all sites" while the best DataOps operator can do is to compute ddm_quota with the script above. We lack a way to consume in the code the metrics exposed in Nick's chart. Would be great if Data Management could make this available. Have a single place where all locks and rules are parsed and the various use source accounted. Then we can tailor policies with much more wisdom.

**Comment by KatyEllis** [comment]
Yes, that's exactly what I'm thinking - although I may be able to guess where Nick's chart gets its info from. Again using RAL Disk as an example, I can see that 'expired data' is about the right size to represent the 'dynamic' data in the chart:
    source: expired
    total: 2587616286512339
This is 2.6PB and would represent 50% of RAL's total space available for CMS.
I would think this expired data would also be available to the ddm_quota script. I'm still convincing the L3s (Lisa and Benedikt) that this is more meaningful, but here is a quote from Felipe after I got him to look at this:

[Felipe Gómez-Cortés]
The ddm_quota as is defined right now, is a very closed value to the minfreespace attribute (defined as the 10% of the pledge).
ddm_quota is not taking into account that the dynamic space can be used for new transfers.

[Katy]
yes, that's what i'm saying

[Felipe Gómez-Cortés]
and ddm_quota is a static value.
It only changes if the site overpasses the target occupancy (as FNAL and CERN usually do)

**Comment by belforte** [comment]
thanks Katy. Indeed "expired" may very well mean "present but not locked". And then there's likely some subtlety which I am missing on how exactly to compute "dynamic|. Oh well... I am ready to get better guidance. It may also be good to check how wmcore picks sites.

**Comment by KatyEllis** [comment]
Because the way Rucio/CMS manages data is to keep all sites ~full at all times. Some of this data is locked, and that space is ineligible to be written. Some of this data is from expired rules (but still managed by Rucio, and, I think, accounted for in the 'Rucio' usage) but this space should be eligible for being written by new data - such as CRAB tape recalls.

**Comment by nsmith-** [comment]
FWIW my plot is all generated from Rucio REST API queries, see https://github.com/nsmith-/dmwmclient/blob/master/dmwmclient/cli/ruciosummary.py for the source. None of the metrics require extensive computation, they are all either RSE usage counters, account usage counters, or combinations thereof.

**Comment by dciangot** [comment]
Well wait. Usage information without expired part is easy to get, right? So explicitly I meant (in Rucio terms): static - rucio + expired

**Comment by belforte** [comment]
glad that we are converging on a common understanding of what those numbers are ! We are into "which policy". I am curious how other people/tool who place data at sites decides how eligible they are. I am not even sure who they are atm ! wmcore_transferor ? is popular data still being replicated ? by whom ?

Yes, I can easily check static-rucio+expired and use it, if there's agreement. I am sure there was a rational for using ddm_quota, we should review it, even if it means bugging Eric.

**Comment by dciangot** [comment]
Thx @nsmith- , that is the main point. I think we already have everything available from the api. Without messing with ddm static quotas. We do have the real time occupancy information directly

**Comment by nsmith-** [comment]
`ddm_quota` is a terrible name (my fault) it is only supposed to weight the decision of which RSEs to pick based on their relative free size.
All quotas would need to be either set on the crab recall account or queried before every rule. As soon as a rule is made, its volume is counted towards any quota (not waiting for data to get there. The pink in my chart, "unavailable" represents data that is supposed to be there but is not yet)

**Comment by belforte** [comment]
I see. I guess I can educate myself about accounts and then will be able to reproduce any bar in the plot. Thanks Nick !

> it is only supposed to weight the decision of which RSEs to pick based on their relative free size

we are debating what "free size" exactly is !

**Comment by belforte** [comment]
>  As soon as a rule is made, its volume is counted towards any quota 

can a rule be made on a dataset/container and its size increased later
(attaching more dids e.g.) ?

**Comment by KatyEllis** [comment]
Yes, I think this is the exception.

**Comment by belforte** [comment]
details of how datasets are injected in the system by WMA (and Diego's code next) define it that's the exception or the norm !

**Comment by belforte** [comment]
@dciangot asked to check locations only for replicas which are not locked. I did and did not find any difference with previous plots. Here's a couple examples of #sites (Y axis) vs. #blocks(X axis) (one point per dataset)
I only list datasets created in 2021-2022. First plot is MINIAODSIM second plot is MINIAOD
This has nothing to do with CRAB tape recall (which places all datasets up to 30TB on a single site),
but since we have switched a bit to discuss data placement policies here, and I needed a place to save plots:

![image](https://user-images.githubusercontent.com/1837785/165928994-7efcd199-c37c-4d9b-972e-5904b52482a9.png)
![image](https://user-images.githubusercontent.com/1837785/165929408-029bf70e-1797-4904-8367-6d276a1baf96.png)

**Comment by belforte** [comment]
thanks @nsmith- . But (my bugs aside) I think i plotted replicas not associated to a rule, so that specific bug should not apply. I suspect that those are the production leftovers. WMA runs at "all sites" to produce MINI*, outputs get merged locally and one or more blocks/datasets are created at each site where it ran and injected in Rucio. The MINI rule will make a replica in US, but not delete the old locations.  This was also Alan's observation, old data stick around for quite long time at all those odd locations  and this "disturbs" reprocessing. Also for (the part of) MINI* produced in the US, will Rucio really try to enforce the grouping=ALL, or when it finds that all datasets are in US consider the rule satisfied and be happy with current situation without any data movement ?

**Comment by belforte** [comment]
summary:
latest code will not split datasets unless > 50TB. Looks good enough to me.
As I have time I can replace check on ddm_quota > 100TB with check on "available" space taking `expired` into account and "discover" that single sites can happily host any dataset. But that can wait.
