### ISSUE TITLE
make sure CRAB job Wrapper does not use WMCore CMSSW executor

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7215]
in particular this part about USER_TARBALL
https://github.com/dmwm/WMCore/blob/748fb8df96a9328600b254b934c8f96ced00505c/src/python/WMCore/WMSpec/Steps/Executors/CMSSW.py#L404

**Comment by belforte** [comment]
@mapellidario @khurtado FYI

**Comment by belforte** [comment]
If you agree, I will close.

**Comment by khurtado** [comment]
@belforte I made the following PR removing ` $USER_TARBALL` and `$USER_FILES` from it.

https://github.com/dmwm/WMCore/pull/11114

But I am also deleting this file and I just wanted to be sure CRAB indeed doesn't use this file at all (I couldn't find any reference here to it other than old github issues)
https://github.com/dmwm/WMCore/blob/f5f71549d5ebb6befd794049b5518cfd179d2c7d/src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py

**Comment by belforte** [comment]
thanks for cheking @khurtado . Yes, no problem, that's not used anywhere. Looks like some old thing from pre-HTCondor times when job wrappers had to pull tarballs themselves from some central storage.

**Comment by khurtado** [comment]
@belforte Great, thank you!
