### ISSUE TITLE
adapt Publisher to latest Rucio_transfer

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7223]
a few changes to current Puvlisher are needed.
First one is to take DBS block name from Rucio_transfer, not create it in Publisher.
So we need a place in TRANSFERSDB.

with ref. to #7087
in TRANSFERSDB table we have these two which are not useful anymore, even if PostJob is currently filling them, there is no place where we use them:

tm_rest_host VARCHAR(50) NOT NULL,
tm_rest_uri VARCHAR(255) NOT NULL,

I propose to change the latter to VARCHAR(1000) and rename to tm_publish_block

We can do the VARCHAR change immediately, so that we  can write using the tm_rest_uri name for tests, but of course we want to change REST code to have a good name.

@dciangot what do you think ?

**Comment by dciangot** [comment]
Fine with me. So we are going to need also a patch for the update transfer on the REST end right?

**Comment by belforte** [comment]
I did on lxplus8
```
belforte@lxplus8s22/~> export ORACLE_CERN=/afs/cern.ch/project/oracle; . $ORACLE_CERN/script/profile_oracle.sh; setoraenv -s prod; 
belforte@lxplus8s22/~> sqlplus cmsweb_analysis_dev@int2r

SQL*Plus: Release 11.2.0.3.0 Production on Mon May 2 11:56:14 2022

Copyright (c) 1982, 2011, Oracle.  All rights reserved.

Enter password: 

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

SP2-0310: unable to open file "?/sqlplus/admin/glogin.sql"
SQL> describe filetransfersdb
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 TM_ID					   NOT NULL VARCHAR2(60)
[...]
 TM_REST_URI				   NOT NULL VARCHAR2(255)
[...]

SQL> alter table filetransfersdb modify TM_REST_URI varchar(1000) NULL;         

Table altered.

SQL>    quit
Disconnected from Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
belforte@lxplus8s22/~> 
```
and I verrified that TM_REST_URI is listed as `VARCHAR2(1000)` w/ot the `NOT NULL` so now empty values are acceptable. We sill stop filling this column in PostJob and let Rucio_transfers use it to store dbs-block/rucio-dataset name

**Comment by belforte** [comment]
I used same commad to remove NOT_NULL constrain also from TM_REST_HOST
and am going to apply same changes to preprod DB

**Comment by belforte** [comment]
changes appear harmless. I am ready to test writing from `RUCIO_trasnfers.py` into `tm_rest_uri`. Progress tracked in my branch https://github.com/belforte/CRABServer/tree/new-publisher-for-rucio-7223

**Comment by belforte** [comment]
pff.. we can PUT a new record in filetransfersdb with whatever `tm_rest_uri` but when it comes to updating POST does not accept all args. atm.  
https://github.com/dmwm/CRABServer/blob/093d8ffb7ede2a5103303409238583e8c85c862c/src/python/CRABInterface/RESTFileUserTransfers.py#L61-L80
https://github.com/dmwm/CRABServer/blob/093d8ffb7ede2a5103303409238583e8c85c862c/src/python/CRABInterface/RESTFileUserTransfers.py#L145-L165

**Comment by belforte** [comment]
we need a new REST in order to make progress :-(

**Comment by belforte** [comment]
since I need to make a new REST version, will deal first with completing asourl/db cleanup https://github.com/dmwm/CRABServer/pull/6930

**Comment by belforte** [comment]
the desired cleanup (#6930) is done

**Comment by belforte** [comment]
High level design of this functionality now in https://github.com/dmwm/CRABServer/wiki/ASO-via-Rucio/

**Comment by belforte** [comment]
I need a clean action plan, stuff written initially is no good. I'd rather add new columns than mess around with reusing old ones:

- [ ] modify [Oracle/Create.py](https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/FileTransfersDB/Oracle/Create.py) and [updateOracle.sql](https://github.com/dmwm/CRABServer/blob/master/etc/updateOracle.sql) to allow NULL values on deprecated-and-soon-to-be-removed `tm_rest_uri` and `tm_rest_host` and add new columns `tm_dbs_blockname`, `tm_block_complete`
- [ ] apply `updateOracle.sql` to all current DB's
   - [ ] dev
   - [ ] devtwo
   - [ ] devthree
   - [ ] preprod
   - [ ] prod
   - [ ] stefano
   - [ ] dciangot
- [ ] modify [RESTFileUserTransfer](https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/RESTFileUserTransfers.py) to accept queries w/o the old `tm_rest_..` values and/or with the new ones
   - [ ] once that is deployed, modify `PostJob` not to write `tm_rest_*` anymore 

 * create 2 new columns in transfersdb table
 * modify REST to accept them as optional args in PUT and POST and deploy
 * modify RT.py to fill them

**Comment by belforte** [comment]
replaced by #7480
