### ISSUE TITLE
rename and consolidate Jenkins tests

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7226]
we must get rid of all COPYCAT things and make sure we only have the proper things in Jenkins
https://cmssdt.cern.ch/dmwm-jenkins/

**Comment by mapellidario** [comment]
Moreover, if we close this issue, we can close also:

- #6925 
- #7109

**Comment by belforte** [comment]
the new Jenkins dashboard looks good to me.
I am fine with closing this and the related ones which you mentioned.

**Comment by mapellidario** [comment]
Thanks Stefano, closing!
