### ISSUE TITLE
Setup new database instance for dev2 environment.

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7229]
We have some schemas in some Oracle DB instances not in used anywhere in current system.
After Stefano and Dario discuss with Kate (Oracle support from CERN IT, if I understand correctly), we can use it for new development environment.

In summary, `cmsweb_crab_9r_dev@int9r` will be new Schema for our `dev2` environment.

Stefano already reset password of this db schema and last time Dario told me there is no table there.
So, we need to initialize and test it with crabserver.

**Comment by belforte** [comment]
this should help: https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabRESTInterface#Install_Scratch_Update_the_Oracl
