### ISSUE TITLE
Bring up new crab development environment (dev2)

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7230]
I will call new crab development environment `dev2`. This new env is consist of:
- [x] New TaskWorker/Publisher machine https://github.com/dmwm/CRABServer/issues/7113
- [x] New cmsweb-test cluster for new dev env https://its.cern.ch/jira/browse/CMSKUBERNETES-144
  - Thanks to CMSWEB team for provided us new cmsweb-test cluster called `cmsweb-test11`.
- [x] New database instance https://github.com/dmwm/CRABServer/issues/7229
- [x] Documents of both dev environment and how to use it to develop crab.

**Comment by belforte** [comment]
- [ ] a new "instance name" (i.e. a handy nickname to use in crabClient and TW/Pub configutation) in  https://github.com/dmwm/CRABServer/blob/1a823b40b15bda1a84b5a9d002c6278bc58c85eb/src/python/ServerUtilities.py#L46

**Comment by novicecpp** [comment]
All item in list are done!
