### ISSUE TITLE
 Request size and time produced by cherrypy httpcall is not match with frontend/client time

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7247]
We saw requests size and time produced by cherrypy httpcall log is not match with frontend/client, mostly, the value in cherrypy is much lesser.

I think it because cherrypy produce it too early (for time). You can reproduce by:
- Follow log of crabserver
- call API that return large data. e.g. `curl -vL -o /dev/null --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem 'https://cmsweb-test11.cern.ch:8443/crabserver/prod/filemetadata?taskname=220503_132244%3Amabarros_crab_DR_Jpsi_25to45_Dstar_DPS_2018_13TeV_03-05-2022&filetype=EDM'`
- You will see crabserver produced log before curl exit.

But for size, I am not sure why.

Before investigate this, we need to make sure first which API affect or it affect all log. I guess it only affect API that do streaming data to client and only affect requests that will get large data.

**Comment by novicecpp** [comment]
Reference I found in cherrypy docs about cherrypy `access_log` [here](https://docs.cherrypy.dev/en/latest/pkg/cherrypy._cplogging.html#cherrypy._cplogging.LogManager.access).

**Comment by belforte** [comment]
> You will see crabserver produced log before curl exit.

maybe crabserver really ends before curl exit and writes log when crabserver/cherrypy ends, but curl needs more time to get data from its socket, write to stdout/disk, close connection with FrontEnd ?

**Comment by novicecpp** [comment]
2 year has passed and I still do not have any idea how to fix this.

I am closing it for now.  We can reopen later when needed or encounter "too many fd" issue again.

**Comment by belforte** [comment]
yeah.. some things are just doomed to be a mystery forever :black_circle:
