### ISSUE TITLE
[monitoring] crabserver and frontend timber have some inconsistencies

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7261]
#### crabserver timber

I noticed that in [crabserver timber](https://monit-grafana.cern.ch/d/VML5DJEnk/crab-crabserver-timber?orgId=11&) does not contain data that we expect. Some of the followings should be easily fixed, some other are may require some investigation

- [x] it does not contain data from preprod/testbed.
- [ ] bytes sent/received does not match the value in FE timber, tracked here https://github.com/dmwm/CRABServer/issues/7247#issuecomment-1126271102

#### frontend timber

- [ ] requests from curl/hey to `/info` do not appear in grafana, despite appearing in [kibana](https://monit-timberprivate.cern.ch/kibana/app/discover#/doc/571b2d60-cd1c-11ec-9cca-9f64af2c2bfb/monit_private_cmswebk8s_logs_frontend-2022-06-04?id=2db68ee2-455b-d2b0-6aeb-2870a51ae28d)

FYI: @novicecpp 

I am assigning both of us, because we already spotted these days ago and it is better we continue to have a look in the coming days, when we have some spare time

**Comment by novicecpp** [comment]
Note that WMCore use [self.time()](https://github.com/dmwm/WMCore/blob/5e654f59a28cb95eb0759272f49ad4c7a33d731c/src/python/WMCore/REST/Main.py#L121) as timestamp in access() function. It is time when access function execute using `datetime.datetime.now()`, not starting request [(ref)]( https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/REST/Main.py#L121). But we still have `cherrypy.request.start_time` to use if we want to stamp time when it request first come.

Not sure if we need to change this.

**Comment by mapellidario** [comment]
> Not sure if we need to change this.

more than changing anything, i think we should just accept this as a fact of life. just write this down and keep it in mind when we look at the plots. cherrypy prints the log at the end of the request, with the timestamp of the end of the request.

**Comment by novicecpp** [comment]
> it does not contain data from preprod/testbed.

After discussing in private chat, this one is solved.
Previously, config of logstash in preprod is not update. Now it up-to-date, Maybe Imran update it some time ago.

**Comment by novicecpp** [comment]
Put note in grafana that body size metric still broken.

**Comment by belforte** [comment]
only remaining issue from here is tracked in #7247
