### ISSUE TITLE
Understand (and fix) long-lasting calls to S3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7268]
we see that when `cache` API is uset to get a PreSignedUrl, at times it takes 1,2,3... up to 6 minutes. And when this happens the whole pod stalls. Other quries are queued and dealyed or may all time out.

Even if this is not critically bad, it is something to be understood and solved.

**Comment by novicecpp** [comment]
Thanks a lot Dario.I have learn a lot from your docs.

I already ask Imran and he got this problem too. Copy from Mattermost (sorry in advance if I misunderstand what he said):
```
I asked him, he said he encounter this problem with s3.cern.ch too.
He said Spyros fix it a month ago (which he did not know the detail) but it temporary fix, when some time pass it happen again and no update from Spyros.

I suggest to open tickect to CMSKubernetes JIRA for tracking this issue with Imran.
```

**Comment by belforte** [comment]
quick summary
* problem is due to timeout when connecting to IPV6 address of s3.cern.ch
* not limited to s3, other IPV6 address do the same (e.g. `cmsgwms-collector-global.cern.ch`)
* it was noticed already in cmsweb K8s, fixed temporarely, came back (from @muhammadimranfarooqi ) consistently with [our observation](https://mattermost.web.cern.ch/files/7u4i7z7bgig79fpb5k83qfc4xa/public?h=tWt2sGPJ1EcahFHUBIjpOYwcZ96D2Njk1Oeoy-Z1s_k) in [this](https://mattermost.web.cern.ch/cms-o-and-c/pl/we913xwxnpbu8yfe8kesbiut6c) MatterMost thread
* other hosts we connect to (cmsweb, cric) do not give problems because they do not have IPV6
* problem is there also for gitlab.cern.ch which has IPV6. But this only affects CRABServer at startup when it loads [external config](http://gitlab.cern.ch/crab3/CRAB3ServerConfig/raw/master/cmsweb-rest-config.json) so it results in an un-noticed delay at startup

**Comment by belforte** [comment]
my fix above #7270 broke `crab submit`  and needs to be rolled back
- [ ]  already done in K8s (deployed yesterday's tag v3.220525)
- [ ] to be done in master branch

I think I can make a different change to RESTCache which will keep `crab submit` work. But will test things first this time !
* The problem is that CRABClient uses `curl` from CLI with host authentication enabled (the defaul) and when it uses a numeric host name (an IPV4 address for s3.cern.ch) the host name does not match what is in the certificate (`s3.cern.ch`). Apparently WMCore/pycurl_manager has host authentication disabled.

**Comment by belforte** [comment]
I deployed [v3.220527](https://github.com/dmwm/CRABServer/releases/tag/v3.220527)  in Production. This has a proper fix fr forcing IPV4 https://github.com/dmwm/CRABServer/pull/7273  Now we are "immune" to IPV6 problems. But need to keep `verify=False` in boto3 client instantiation.

**Comment by belforte** [comment]
@mapellidario I leave it to you to put final words and close

**Comment by mapellidario** [comment]
I would actually wait for

- [ ] Spyros to close the [snow](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3147173) ticket
- [ ] Us to merge #7271

**Comment by mapellidario** [comment]
Since we did all we could and now it is CERN IT job to follow up [1], I will lower the priority and remove the "in progress" label.

[1] https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3147173
