### ISSUE TITLE
WMArchiveUploader not properly restart when try to do it with systemctl

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7284]
When I try to restart WMArchiveUploader with `systemctl restart WMArchiveUploader` when doing https://github.com/dmwm/CRABServer/issues/7159 issue, sometime daemon process does not exit. Sometime, process are gone but lock file still there which prevent new process to start.

We need to fix it to make it work well with `systemctl {start,stop,restart}` command.

**Comment by novicecpp** [comment]
@belforte please review https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/63
Sorry if you already seen notification email from gitlab.

**Comment by belforte** [comment]
yes. I got the noticed, but had not acted yet (lunch ?)

**Comment by novicecpp** [comment]
Ok, next time I will not ping you in github again.

**Comment by novicecpp** [comment]
New changes has merged into master. But it only solve problem when you restart it manually (via systemctl) or machine has been restarted. 
Problem is process start by systemd but does not monitor by systemd. Systemd just mark as active when finished run script without error. So, we never know when WMArchiveUploader is crash until we got alert about disk grow in `WMArchiveWD/new` directory.

Solution I know is to convert init script to proper systemd unit,  using `Type=forking` and tell systemd where the pid file is.

**Comment by novicecpp** [comment]
In any case, when `/data/srv/WMArchiveWD/new/` consume disk space more than threshold (10GB?), we will get email alert with subject like this:
```
[Alert] /data/srv/WMArchiveWD/new: Size critical:10419 MB at vocms0199.cern.ch from clean_WMArchiveWD_processed.sh@vocms0199.cern.ch
```
That is mean, WMArchiveUploader process already gone (crash/oom kill). We need to manual restart it.

**Comment by belforte** [comment]
we should fix this, but also review our use of crontabs vs. systemctl things in schedd's and possibly unify

**Comment by novicecpp** [comment]
Done
