### ISSUE TITLE
Recent failed publications - "fail to inject FL chunk"

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7286]
Two blocks failed to be published with a non-trivial error message [1]. We will need to debug them.

@belforte , feel free to self-assign this issue if you feel like, otherwise I can give it a try.

Affected files:

- `/data/srv/Publisher_files/FailedBlocks/failed-block-at-16547*`
- `/data/srv/Publisher_files/FailedBlocks/failed-block-at-165510*`, `16551*`, `165512*`

[1] 

```plaintext
[crab3@crab-prod-tw01 Publisher]$ for f in `ls /data/srv/Publisher_files/FailedBlocks/fail*`; do echo $f; python3  /data/repos/CRABServer/scripts/Utils/DebugFailedBlockPublication.py --file `basename $f`; done
/data/srv/Publisher_files/FailedBlocks/failed-block-at-1654761490.4525504.txt
Block is meant to be added to dataset
/Pythia8_DPStoJJ/jiayis-MC2016APV_SKIM_JinfengLiu_Tight-dda27a7811ffa4b67e73293de719a929/USER
Block contains 58 files
No obvious reason for Publication failure found, try to insert again
DBS Server error: [{'error': {'reason': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil', 'message': '1110674de26422d6867e4f56c8afffc16fc3be00271699ec7039cffe113e9728 unable to insert FileLumis records for /store/user/jiayis/MC2016APV/CrossSection/Tight/Pythia8_DPStoJJ/MC2016APV_SKIM_JinfengLiu_Tight/220609_071838/0000/BPHSkim_74.root, fileID 1079121521, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil', 'function': 'dbs.bulkblocks.InsertBulkBlocksConcurrently', 'code': 110}, 'http': {'method': 'POST', 'code': 400, 'timestamp': '2022-06-09 08:23:36.988802198 +0000 UTC m=+673231.182715618', 'path': '/dbs/prod/phys03/DBSWriter/bulkblocks', 'user_agent': 'DBSClient/Unknown/', 'x_forwarded_host': 'dbs-prod.cern.ch', 'x_forwarded_for': '137.138.31.95', 'remote_addr': '137.138.45.202:55726'}, 'exception': 400, 'type': 'HTTPError', 'message': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:1110674de26422d6867e4f56c8afffc16fc3be00271699ec7039cffe113e9728 unable to insert FileLumis records for /store/user/jiayis/MC2016APV/CrossSection/Tight/Pythia8_DPStoJJ/MC2016APV_SKIM_JinfengLiu_Tight/220609_071838/0000/BPHSkim_74.root, fileID 1079121521, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil'}]
Publication failed with exception:
HTTP Error 400: Bad Request
/data/srv/Publisher_files/FailedBlocks/failed-block-at-1654761512.1470711.txt
Block is meant to be added to dataset
/Pythia8_DPStoJJ/jiayis-MC2016_SKIM_JinfengLiu_Tight-1a63e6f612b052cd471eba7c61423146/USER
Block contains 56 files
No obvious reason for Publication failure found, try to insert again
DBS Server error: [{'error': {'reason': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil', 'message': '2205249f5d9a3d2e96e09dd83f6a7eacfb3977224a8ad50e922dd84dbf640df9 unable to insert FileLumis records for /store/user/jiayis/MC2016/CrossSection/Tight/Pythia8_DPStoJJ/MC2016_SKIM_JinfengLiu_Tight/220609_071655/0000/BPHSkim_74.root, fileID 1079123841, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil', 'function': 'dbs.bulkblocks.InsertBulkBlocksConcurrently', 'code': 110}, 'http': {'method': 'POST', 'code': 400, 'timestamp': '2022-06-09 08:23:57.873601922 +0000 UTC m=+520449.587181971', 'path': '/dbs/prod/phys03/DBSWriter/bulkblocks', 'user_agent': 'DBSClient/Unknown/', 'x_forwarded_host': 'dbs-prod.cern.ch', 'x_forwarded_for': '137.138.31.95', 'remote_addr': '10.100.209.0:39934'}, 'exception': 400, 'type': 'HTTPError', 'message': 'DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:2205249f5d9a3d2e96e09dd83f6a7eacfb3977224a8ad50e922dd84dbf640df9 unable to insert FileLumis records for /store/user/jiayis/MC2016/CrossSection/Tight/Pythia8_DPStoJJ/MC2016_SKIM_JinfengLiu_Tight/220609_071655/0000/BPHSkim_74.root, fileID 1079123841, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil'}]
Publication failed with exception:
HTTP Error 400: Bad Request
```

**Comment by belforte** [comment]
Looks like DBS problem. Convert block to JSON, zip if large , and hand to Valentinsent from Stefano's mobile

**Comment by belforte** [comment]
@mapellidario did you send the block to Valentin yet ? If not, let's do. We can pick a smallish one like failed-block-at-1655296385.5612102.txt  (100KB)

**Comment by mapellidario** [comment]
I did not. I never did and I am not sure what information he needs. I tried to look in my emails but i did not find anything. sorry

**Comment by belforte** [comment]
let me know if you prefere to turn that twiki into a MD doc in gitlab. If so it will be more efficient if you can kickstart it and paste here the gitlab url

**Comment by belforte** [comment]
here's an example of how to convert those block dumps to json (will take care of twiki later)
```
>>> import json
>>> filePath='fail_to_inject_FL_chunk.txt'
>>> with open(filePath) as fp: blockData = fp.read()
... 
>>> block = eval(blockData)
>>> ofile=filePath.replace('txt','json')
>>> print(ofile)
fail_to_inject_FL_chunk.json
>>> with open(ofile,'w') as fp: json.dump(block,fp)
... 
>>> 
```

the shortest example I have found is a 600KB file:
`/afs/cern.ch/user/b/belforte/public/BadBlocks/fail_to_inject_FL_chunk.json`
in the same directory I have also the gzipped version (42KBytes !)
`/afs/cern.ch/user/b/belforte/public/BadBlocks/fail_to_inject_FL_chunk.json.gz`

**Comment by belforte** [comment]
and after quite some effort to find the correct URL, here's the output of the simple curl test as per https://github.com/dmwm/dbs2go/blob/master/docs/DBSWriter.md

belforte@lxplus8s18/BadBlocks> curl --cert $X509_USER_PROXY  --key $X509_USER_PROXY -H "Content-type: application/json" -d@/afs/cern.ch/user/b/belforte/public/BadBlocks/fail_to_inject_FL_chunk.json  https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter/bulkblocks
[{"error":{"reason":"DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil","message":"6bf548cb1ead5b67471c907a06c890cc06684240c1eb1331d2a88bb2b283a24a unable to insert FileLumis records for /store/user/jinfeng/CrossSection/MC2016/Tight/Pythia8_DPStoJJ/MC2016_SKIM_JinfengLiu_Tight/220615_103610/0000/BPHSkim_86.root, fileID 1115340921, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil","function":"dbs.bulkblocks.InsertBulkBlocksConcurrently","code":110},"http":{"method":"POST","code":400,"timestamp":"2022-06-22 14:13:45.676802433 +0000 UTC m=+68891.739753330","path":"/dbs/prod/phys03/DBSWriter/bulkblocks","user_agent":"curl/7.59.0","x_forwarded_host":"cmsweb-k8s-prodsrv.cern.ch","x_forwarded_for":"137.138.154.184","remote_addr":"10.100.196.128:51854"},"exception":400,"type":"HTTPError","message":"DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.InsertBulkBlocksConcurrently Message:6bf548cb1ead5b67471c907a06c890cc06684240c1eb1331d2a88bb2b283a24a unable to insert FileLumis records for /store/user/jinfeng/CrossSection/MC2016/Tight/Pythia8_DPStoJJ/MC2016_SKIM_JinfengLiu_Tight/220615_103610/0000/BPHSkim_86.root, fileID 1115340921, error DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil"}]belforte@lxplus8s18/BadBlocks>

**Comment by belforte** [comment]
I have opend a DBS ticket for Valentin: https://github.com/dmwm/dbs2go/issues/53

**Comment by vkuznet** [comment]
@belforte I deployed the fix on testbed, but using your JSON I hit another problem with parentage which says:
unable to find parent_logical_file_name file_id for pfn='/store/user/jinfeng/MC2016/v2/Pythia8_DPStoJJ/MC2016_RECO_JinfengLiu_v2/220608_145522/0008/BPH-RECO-13TeV_8673.root'

Therefore, I can't test it using testbed DB (which has different content from production phys03). There are two routes here:
- either you populate (migrate) testbed DB with parents dataset/blocks (I see that this LFN has this block `/Pythia8_DPStoJJ/jinfeng-MC2016_RECO_JinfengLiu_v2-5842781364b9b434fe5e0aacdebb1b31/USER#88e1584d-8965-4247-af3e-6f9f8d212ae9` in production DB)
- or, I can deploy new version of DBSWriter to production k8s cluster (but to be on a safe side only to /dbs/phys03 end-point) and you can inject your data over there

Let me know which solution do you prefer. Again, I have only one hour or less of  my time for today as I need to prepare stuff for my time off tomorrow.

**Comment by belforte** [comment]
thanks a lot Valentin, but its late here as well. We'll get back to this after your time off. We are humans, you too ;-)

**Comment by belforte** [comment]
problem is understood and situation is not critical (some kind of exceptional dataset). No reason to label as critical, and no more actions needed on CRAB side besides validating fix.

**Comment by belforte** [comment]
I wanted to test fix, so I tried to migrate that parent dataset from `prod/phys03` to `int/phys03`
```
from :  https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader
  to :  https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate
```
dataset is `/Pythia8_DPStoJJ/jinfeng-MC2016_RECO_JinfengLiu_v2-5842781364b9b434fe5e0aacdebb1b31/USER`
so I used
```python
data= {'migration_url': globUrl, 'migration_input': dataset}
result=apiMig.submitMigration(data)
```
and `result` shows that 664 (sic!) migrationIds where created. Large number of migrations is OK, since parents of parents need to be migrated as well, looks like that RECO dataset comes from a SIM dataset and that from a GEN, all of fhem in `prod/phys03` with `USER` tier.
But migrations are all failing with messages in Migration log like

[2022-06-24 15:20:17.710933468 +0000 UTC m=+160463.970618333] migrate.go:780: insert bulkblocks for mid 65001 error DBSError Code:109 Description:DBS DB ID error for provided entity, e.g. there is no record in DB for provided value Function:dbs.bulkblocks.InsertBulkBlocks Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.GetRecID Message: Error: nested DBSError Code:113 Description:DBS validation error, e.g. input parameter does not match lexicon rules Function:dbs.primarydstypes.Insert Message: Error: nested DBSError Code:115 Description:DBS decode record failure, e.g. mailformed JSON Function:dbs.DecodeValidatorError Message: Error: validation error

I guess we can try again once @vkuznet is back.

Maybe there is a specific problem when migrationg from `prod/phys03`

**Comment by belforte** [comment]
I tried to insert a dataset from prod/global which has no parents (keep things simple). But got same error

this is the migration toward  https://cmsweb-testbed.cern.ch:8443/dbs/int/phys03/DBSMigrate
```
[{'create_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di Fisica '
               'Nucleare/CN=Stefano Belforte belforte@infn.it',
  'creation_date': 1656240500,
  'last_modification_date': 1656240500,
  'last_modified_by': '/DC=org/DC=terena/DC=tcs/C=IT/O=Istituto Nazionale di '
                      'Fisica Nucleare/CN=Stefano Belforte belforte@infn.it',
  'migration_input': '/MuonEG/Run2016B-v1/RAW#86bc5e3e-1519-11e6-a3f4-001e67ac06a0',
  'migration_request_id': 80001,
  'migration_status': 3,
  'migration_url': 'https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader',
  'retry_count': 1}]
```

and this is from  dbs2go-phys03-migration-d5d855db8-kptsb.log-20220626 on vocms0750 grepping for ` 8000` `


[2022-06-26 10:49:05.71892103 +0000 UTC m=+316991.978605895] migrate.go:780: insert bulkblocks for mid 80001 error DBSError Code:110 Description:DBS DB insert record error Function:dbs.bulkblocks.InsertBulkBlocks Message: Error: nested DBSError Code:110 Description:DBS DB insert record error Function:dbs.filelumis.insertFLChunk Message:fail to inject FL chunk Error: nil

**Comment by vkuznet** [comment]
@belforte I start looking into errors associated with migration failure, and for the request of 65001 I see the following:
```
[2022-06-24 15:20:17.687881874 +0000 UTC m=+160463.947566741] dbs.go:655: fail to get ID from table OUTPUT_MODULE_CONFIGS
output_mod_config_id for [app_exec_id parameter_set_hash_id release_version_id output_module_label global_tag] values [1 35001 40001 o crab3_tag]
...
[2022-06-24 15:20:17.708937691 +0000 UTC m=+160463.968622556] dbs.go:107: DBS structure JSON representation
{
   "primary_ds_type_id": 4,
   "primary_ds_type": ""
}
key=PRIMARY_DS_TYPE type=string value=, constrain required
[2022-06-24 15:20:17.709221631 +0000 UTC m=+160463.968906496] primarydstypes.go:50: unable to validate record DBSError Code:115 Description:DBS decode record failure, e.g. mailformed JSON Function:dbs.DecodeValidatorError Message: Error: validation error
```
So, this implies that during migration process the migration request failed since we do not have enough info about associated meta-data (in this case primary_ds_type , output module config) in testbed DB. In other words, in order to migrate the dataset you asked certain meta-data should be presented in DB which I bet exists in production DB. I'll try to run your migration in my dev environment to see what is missing and how DBS migration service should handle this missing info.

**Comment by belforte** [comment]
could it be that new server does not migrate parents first, but sort of tries to do all blocks at same time ?

**Comment by vkuznet** [comment]
yes, this is the issue, the new server did not have proper order. I already have code in place but I need time to validate it properly. Your particular example with USER dataset is useful. Indeed, it has 664 blocks for migration, 3 USER based and one PREMIX. The validation process is very tedious in this case as it takes O(1h) to migrate all of these blocks (on my laptop) and I'm fixing issues as I find them. So, please be patient with that, I'm working on this issue.

**Comment by vkuznet** [comment]
Stefano, do you have another example of failed dataset. This one is extremely hard to debug since it has so many blocks and so many file-lumis info that my logs are gigantic and the entire process slows down. I need a similar example but with much less number of blocks/filelumis. If you happen to know any other failures please post them here that I can check their occupancy and may be pick up another dataset which will simplify debugging process.

**Comment by belforte** [comment]
Yes, that was kind of extraordinary in size etc. Those USER datasets can really be anything. Let me try to find e.g. a RECO which should have a single parent dataset, better yet a small one. I need to take the day off today (family) so can't work on this more, but maybe the HammerCloud dataset is the right use case, can you try this: /GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM

**Comment by vkuznet** [comment]
ok, thanks, I"ll check its parentage.

**Comment by belforte** [comment]
as to less trivial but still sensible.. I will have to look. Will get you something though.

**Comment by vkuznet** [comment]
great, this one has only 8 blocks to migrate, I'll use this one for debugging.

**Comment by belforte** [comment]
a less trivial but realistic example:
/EGamma/Run2018C-12Nov2019_UL2018-v2/AOD has 133 blocks and a single parent dataset: /EGamma/Run2018C-v1/RAW which has 41 blocks and no parents (as proper for RAW).

You can easily find more by simply skimming over what's being used currently in ES: https://monit-kibana.cern.ch/kibana/goto/a7a09a8d25da5ad4ace0e401261f16d6
I suggest that you test on a few different realistic examples (MC, data, AOD, MINIAOS, NANO*, RECO..)

Maybe easier and cover more ground than picking random migrationId's from prod/phys03 DBSMigrate and trying to replicate them (which also would be a way).

I am stopping current migration cloning and will look into detecting those that fails when replicated on INT, that should be a more sensible thing to run for a couple weeks. I will use https://github.com/dmwm/CRABServer/issues/7290 to track that work.

**Comment by belforte** [comment]
I am closing this since all such issues are now tracked in https://github.com/dmwm/dbs2go/issues/53#
