### ISSUE TITLE
Test DBSMigrate service on testbed

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7290]
Valentin asked to test the new go-based DBSMigrate server that they deployed on testbed.

More info on the specific endpoints available is in [this ticket](https://its.cern.ch/jira/projects/CMSKUBERNETES/issues/CMSKUBERNETES-148?filter=allissues)

**Comment by belforte** [comment]
set prio to top as I fear that moving to new DBSMigrate may be only solution to https://github.com/dmwm/dbs2go/issues/51

**Comment by belforte** [comment]
I have done some initial testing while looking at migration failures in https://github.com/dmwm/dbs2go/issues/51
At first sight DBSMigrate works exactly like it should. In any case we do not make intensive use, migrations are relatively "rare". So "it worked in a couple test calls" is as good as "tested", I think,

But so far it looks to me that testbed is still running the old python version of DBS Migration

**Comment by belforte** [comment]
the problem in testbed was tracked to race among multiple migration servers (running by mistake) and solved. The problem in production has been defined "not solvable", it something that has beem there since the beginning, simply we now noticed because of much much better monitoring.

We can proceed with testing more migrations in testbed.

I will try to think of some way.

**Comment by belforte** [comment]
I tried to migrate one dataset from `prod/phys03` to `int/phys03` which would be needed for testing the fix to `FL chunk inject` problem #7286 . But got errors. To be followed up when Valentin comes back. I will put details in #7286

**Comment by belforte** [comment]
Parasitic migration is now active.

**Comment by belforte** [comment]
as discussed in https://github.com/dmwm/CRABServer/issues/7286#issuecomment-1168777156 and following comments: I am stopping current migration cloning and will look into detecting those that fails when replicated on INT

**Comment by belforte** [comment]
I have reverted Publisher to normal operation. Waiting for clarifications on how to detect failed migrations in new server. Being followd up in a couple issues in dbs2go

**Comment by belforte** [comment]
Time to try the real thing
