### ISSUE TITLE
Information about Rucio rule to be added to CRAB status

### ISSUE THREAD

**Issue by KatyEllis** [dmwm/CRABServer#7302]
When using Rucio stage out it would be good to provide the user with information about their output dataset in Rucio - e.g. the name of the DID. Then the User can easily query it in Rucio. 

For example when doing 'crab status' on my job, print out could include:

Container name in Rucio: user.kellis:/DoubleMuon/kellis-CRAB3_tutorial_outputToRucio_3-b1383949992720d255012d17dde44e2f/USER

This can then be checked in Rucio even if the output dataset is not published to DBS.

**Comment by dciangot** [comment]
https://github.com/dmwm/CRABServer/issues/6041

**Comment by belforte** [comment]
@dciangot w/o me looking at the code, is there a unique rule for a task ? or could it change over time ?

**Comment by dciangot** [comment]
There is a single rule for each datasets/block.  And should never chamge

**Comment by KatyEllis** [comment]
@belforte this is what some of my rules looked like in my last test:

`rucio list-rules --account kellis | grep Displaced
c40dcdc3fe31491bb945157333593793  kellis     user.kellis:/DisplacedJet/kellis-CRAB3_tutorial_output_partialDataset_testPartialTrue-5df524ae15c58ec3570d3432c992b903/USER#ac3534ef-9dfb-46bb-8a5e-502e9cdea29b  OK[103/0/0]             T2_UK_SGrid_RALPP  1                              2022-08-11 18:10:25
54846809f5f14b6e81663423b3c80170  kellis     user.kellis:/DisplacedJet/kellis-CRAB3_tutorial_output_partialDataset_testPartialTrue-5df524ae15c58ec3570d3432c992b903/USER#88bd76f5-b80e-462b-8904-bbe48f9cb539  OK[117/0/0]             T2_UK_SGrid_RALPP  1                              2022-08-11 17:19:33
`

**Comment by KatyEllis** [comment]
First value is the Rucio rule ID
Second value is my user name
Third value is the 'DID' (dataset identifier) including the scope, which in this case is 'user.kellis'
Fourth value is the status of the rule - OK in this case, which is fully satisfied
Fifth value is the destination site
Sixth value is the number of copies (always 1 in this situation)
Seventh value is the date the rule was created (the expiry date in this case is blank, as users are going to manage their own space, and perform their own deletions as necessary)

**Comment by dciangot** [comment]
In terms of python api, I think we will need `list_content' on the container name (crab output dataset) and then a list_rules for every dataset

**Comment by belforte** [comment]
hmm... so multiple rules in the end, ok.  Will think of some "compact" message to users. I am not enthusiast about crab client making calls to Rucio, if nothing else becasue Rucio client does not work inside CMSSW env. We can write a script for users to run but do not have an obvious way to distribute it.

**Comment by belforte** [comment]
let me note down useful Rucio commands, to make sure we print out proper hints.
By the way, it looks to me that we have no documentation anywhere about stageout to Rucio

 * `rucio list-dids user.belforte:*` shows "too much"
 * `rucio list-dids user.belforte:* --filter 'type=CONTAINER'`  to show the containers aka DBS-datasets
 * given one container:
   * `  rucio list-files user.belforte:/GenericTTbar/belforte-Stefano-Test-220506-94ba0e06145abd65ccb1d21786dc7e1d/USER ` shows what's expected
   * `rucio list-file-replicas user.belforte:/GenericTTbar/belforte-Stefano-Test-220506-94ba0e06145abd65ccb1d21786dc7e1d/USER` shows also replicas on `Temp` RSE's, which have not been purged several months after written :disappointed: 
 * `rucio list-rules user.belforte:/GenericTTbar/belforte-Stefano-Test-220506-94ba0e06145abd65ccb1d21786dc7e1d/USER`shows that the rule never expires and status of replica to destination site. Can list rules for container or for dataset
 * `rucio list-rules --account belforte` shows what's expected
 * `rucio delete-rule` free file replicas in my Rucio storage from locks, so that they can be removed by Rucio's Reaper
   * note that rule is deleted 1 hour after the command was issued. "oops" time!

**Comment by belforte** [comment]
so it looks like in the end the only useful bit  from crab status is the `container name` and hint to run
 * `rucio list-content <containername>`  : shows the datasets/blocks
 * `rucio list-dataset-replicas <containername>` : show replica summary for each dataset/block
 * `rucio list-rules <containername>` : for advanced use, main point is that rules id are needed to delete rules and free disk space

Or maybe
 * only print out container name and pointer to documentation, like we do for automatic splitting.

**Comment by belforte** [comment]
I was trying to figure out how to pass container name from RUCIO_Transfers.py back to client, then realized that container name is the output dataset name which is already known. There's also a column for it in Task table of DB, but looks like it is not filled when publication is disabled. But I see it in the `task_process/transfers.txt` file as
```
outputdataset": "/GenericTTbar/belforte-Stefano-Test-220506-94ba0e06145abd65ccb1d21786dc7e1d/USER
```

that name is created in PostJob, which eventually put it in Task table when doing output_file_metadata_uploading which happen only when output transfer is completed. I could move these lines up in the PJ flow
https://github.com/dmwm/CRABServer/blob/6eadbd944b1aecbc6cf02bb73f73de02c4aa3511/src/python/TaskWorker/Actions/PostJob.py#L2474-L2490

e.g. around here
https://github.com/dmwm/CRABServer/blob/6eadbd944b1aecbc6cf02bb73f73de02c4aa3511/src/python/TaskWorker/Actions/PostJob.py#L2744

**Comment by belforte** [comment]
Of course a change is needed also in CRAB Client: 

In my private branch now `crab status` output looks like this
```
elforte@lxplus8s16/TC3> crab status 
CRAB project directory:		/afs/cern.ch/work/b/belforte/CRAB3/TC3/crab_20221014_190156
Task name:			221014_170159:belforte_crab_20221014_190156
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-dev-tw01
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-test2.cern.ch/crabserver/ui/task/221014_170159%3Abelforte_crab_20221014_190156
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=belforte&var-task=221014_170159%3Abelforte_crab_20221014_190156&from=1665763319000&to=now
Status on the scheduler:	COMPLETED

Jobs status:                    finished     		100.0% (2/2)

Rucio Container:  user.belforte:/GenericTTbar/belforte-crab_20221014_190156-94ba0e06145abd65ccb1d21786dc7e1d/USER

No publication information (publication has been disabled in the CRAB configuration file)

...
```

I tried to keep changes minimal, but still we need to make sure that no use case is broken.
We can then elaborate on what to write beside the container name !

**Comment by belforte** [comment]
testing with Jenkins  https://github.com/dmwm/CRABServer/issues/7433 one problem pops up in PostJob when using `disableAutomaticOutputCollection` in crabConfig
all other tests were successful.

```
Mon, 17 Oct 2022 19:46:28 CEST(+0200):INFO:PostJob ====== Starting to parse job report file jobReport.json.1.
Mon, 17 Oct 2022 19:46:28 CEST(+0200):ERROR:PostJob Failure during post-job execution.
Traceback (most recent call last):
  File "/data/srv/glidecondor/condor_local/spool/6030/0/cluster88296030.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 1639, in execute
    retval, retmsg = self.execute_internal()
  File "/data/srv/glidecondor/condor_local/spool/6030/0/cluster88296030.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 1976, in execute_internal
    if self.parse_job_report():
  File "/data/srv/glidecondor/condor_local/spool/6030/0/cluster88296030.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2645, in parse_job_report
    self.fill_output_files_info() ## Fill self.output_files_info by parsing the job report.
  File "/data/srv/glidecondor/condor_local/spool/6030/0/cluster88296030.proc0.subproc0/TaskWorker/Actions/PostJob.py", line 2766, in fill_output_files_info
    self.output_dataset = outdataset # we do not support multiple output datasets anymore
UnboundLocalError: local variable 'outdataset' referenced before assignment
Mon, 17 Oct 2022 19:46:28 CEST(+0200):INFO:PostJob ====== Starting to prepare error report.
```

**Comment by belforte** [comment]
client side done as well, point users to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#Stageout_with_Rucio via https://github.com/dmwm/CRABClient/pull/5177

**Comment by belforte** [comment]
damn... i somehow managed to loose relevant PostJob lines !

**Comment by belforte** [comment]
need to startover :-(

**Comment by belforte** [comment]
tomorrow

**Comment by belforte** [comment]
should be ok now. keep it open in order to

- [ ] clean up PostJob removing  `Uploading output datasets` code  from `upload_output_files_metadata` function
