### ISSUE TITLE
add parasitic migration to cmsweb-testbed to TaskPublish

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7315]
see #7290 This will allow to validate new go-based migration service as per https://its.cern.ch/jira/projects/CMSKUBERNETES/issues/CMSKUBERNETES-148

**Comment by belforte** [comment]
thanks @vkuznet . Yes I think I know how to check migration status. Simply my first logging was mixing ID's for prod and testbed. I am trying to get  a clean list of migration ids to check, that's all.
Sorry about the noise. I use GH issue as my worklog/diary, sorry about all details, but I need to write things down. When I have a post which is worth for you to read, I will flag it. Do not waste your time on these notes.

**Comment by belforte** [comment]
with ref. to https://its.cern.ch/jira/browse/CMSKUBERNETES-148?focusedCommentId=4398066&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4398066
I verified that in Publlisher buildf we have py3-dbs3-client/4.0.8/ so will introduce `debug` flag in dbs API calls.

 I am not sure how to find failed migrations in new server due to https://its.cern.ch/jira/browse/CMSKUBERNETES-148?focusedCommentId=4398985&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4398985

**Comment by vkuznet** [comment]
Please refer to documentation about APIs over here: https://github.com/dmwm/dbs2go/blob/master/docs/MigrationServer.md It provides all the examples for each API call.

**Comment by belforte** [comment]
I am reading the documentation. Believe me. Let's follow up in https://github.com/dmwm/dbs2go/issues/56 and https://github.com/dmwm/dbs2go/issues/57
The problem is not lack of knowledge of "how to query" is about detailed understanding of the situation.

**Comment by belforte** [comment]
The parasitic migration is there and working fine. Need to turn to support for new migration server in production.
