### ISSUE TITLE
Grafana dashboard update 2022-07-19

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7337]
I will add the list of update we should do in grafana. Feel free to add any comment.

- [ ] add memory usage panel like my [private cloned](https://monit-grafana.cern.ch/d/xJ3UbG87k/user-tseethon-crabserver-cmsweb-20220407?orgId=11&from=now-6h&to=now) to [cmsweb crabserver](https://monit-grafana.cern.ch/d/cmsweb_crabserver/crabserver-cmsweb?orgId=11)
  - [ ] change it name to "CRAB crabserver prometheus"
  - [ ] update panel name to more easier to understand and put description, link to documents.

**Comment by mapellidario** [comment]
I had some suggestions, then time passed and i forgot them. I will write them down here as I recall them.

The first that I propose is to have a panel with "FTS transfers failed grouped by destination site" in "CRAB Overview" dashboard.

something like going from (current "CRAB Overview")

![image](https://user-images.githubusercontent.com/16376695/180163267-c5653ea5-db5c-4722-a8df-e6e59145f778.png)

to (implemented [here](https://monit-grafana.cern.ch/d/_01i1XP7z/user-dmapelli-crab-overview-3?orgId=11))

![image](https://user-images.githubusercontent.com/16376695/180163326-a015620f-3804-4751-8094-6e3b07388948.png)

**Comment by belforte** [comment]
looks good Dario, I like how you combined the first two plots. Feel free to go ahead and do.

**Comment by belforte** [comment]
I think that adding a new API for this is not worth.  But I guess it could be a warming up exercise for you or Wa. Surely it has very low priority since that odd thing only happens one/month and you can make it disappear by looking at last 24h or so

**Comment by belforte** [comment]
> looks good Dario, I like how you combined the first two plots. Feel free to go ahead and do.

you haven't done it yet, have you ? The more you wait the more effort it will be

**Comment by mapellidario** [comment]
> you haven't done it yet, have you ? The more you wait the more effort it will be

Yes, I did it on `2022-07-22 11:35:04`, version 75 of the dashboard. sorry i did not mention it explicitly it here.

**Comment by belforte** [comment]
thanks Dario, for some reason my firefox tab refused to show the new version until today. All OK.

**Comment by mapellidario** [comment]
After this morning problems with cmsweb timber monitoring, I added a row at the end of the "CRAB cmsweb timber" [dashboard](https://monit-grafana.cern.ch/goto/2NQQFYIVz?orgId=11) to check the consistency of data (# of requests / time bin) coming from the frontend (apache, at the moment) and from crabserver itself. 

I did not use the dashboard variables in these two panels, I fixed the values for production cluster. This is because the name of the columns in the two indexes is not the same and I do not want to be confused by some selections being applied only to one of the panels.

As you can see, everything looked fine until yesterday, when crabserver timber started lacking some data, while today it is cmweb/frontend timber that seems to lack some.

![image](https://user-images.githubusercontent.com/16376695/196138706-fba0a3b2-37ab-4b9a-9d23-a2652528071c.png)

**Comment by belforte** [comment]
thanks Dario. But should we maybe close this issue now if we see a problem open a new one. While "improving grafana" is sort of a continuously ongoing effort and it is enough to log in e-log for information. If we had a handbook on how to read/use our monitoring what to look for etc... we could track in there, but I do not see how we can even start that this year.

**Comment by mapellidario** [comment]
As a follow up to https://cms-logbook.cern.ch/elog/Analysis+Operations/3781, I propose to change the titles of our dashboards. My idea is to use the naming scheme `crab $(service) - $(details)` to improve clarity. These are only my suggestions, I am definitely open to any comment!

- crab asometrics -> crab ASO - internals
- crasb metrics -> (delete) I am not sure if we still use this, i think we can delete this dashboard.
- crab crabserver timber -> crab rest - crabserver pods
- crab FE timber + pods -> crab rest - fe pods
- crab overflow via jobrouter -> crab grid jobs - overflow via jobrouter 
- crab overview: ok
- crasb s3 cache: ok
- crab schedd instant load -> crab schedd - condor stats
- crab status summary -> crab VM's and pods - overview
  - i dont really like this name, but i really cannot come up with anything better
- crab taskworker internals -> crab tw + pub - internals
- crab vm's host metrics -> crab  tw+pub+schedd - vms  influx db
- crabserver cmsweb -> crab rest - k8s pods prometheus
- node exporter fuill cram VMs -> crab schedd - vms prometheus
- node exporter server metrics - crab multiple servers -> crab tw+pub+schedd - vms prometheus

**Comment by belforte** [comment]
thanks. some are way too long IMHO. Some are a bit too technical and non informative, AFAIU, but I understand so little !
but improving is delicate process, I agree. Need time to think. Maybe have a spreadsheet where we can add names and eventually "vote" ?
crab metrics is not really superseded by crab overvies, the latter has 1h time bins (to have uniformity) while the former has finer (automatic) bins and is better if you want to see sort of real time. Of course we can put the time bin as a global var. in the overview. I was not good/patient enough to do this when I created that dashboard.

**Comment by mapellidario** [comment]
And I found another thing that i would like to improve.

- [ ] It is not clear to me how often we run the RemovetmpDir TWw action [1] and it does not seem to be logged in the "TW internals" [2] dashboard. Maybe we just need to add a new line on our logstash config.


[1]

```plaintext
> grep -r "Checking for dirname older" /data/container/TaskWorker/logs/
/data/container/TaskWorker/logs/twlog.txt.2022-10-21:2022-10-22 17:30:33,945:INFO:RemovetmpDir,19:Checking for dirname older than 0.5 days..
/data/container/TaskWorker/logs/twlog.txt.2022-11-09:2022-11-10 17:47:11,061:INFO:RemovetmpDir,19:Checking for dirname older than 0.5 days..
^C
```

[2] https://monit-grafana.cern.ch/goto/bNx7Nld4k?orgId=11

**Comment by novicecpp** [comment]
Thanks for reminding me of this task :)  I will close it as soon as I can.
But it is better to be a new issue because it is more than adjusting the dashboard (i.e. finding out why there is no recurring action metrics).

**Comment by belforte** [comment]
about Dario's last comment, that plot was born from the desire to see whey at times processing a task could take very long times, so recurring actions were not cosidered. If you touch it, it may be good to add all of them.
At some point we will want to understand how can DBS_data_discover take hours...

**Comment by mapellidario** [comment]
While I organize my to-do-list, let me paste here the pointer to the discussion with monit about creating a new dashboard for alerts [1].

- [ ] (dario) setup new "production" alerting system, from grafana to mattermost

In the next few days I will collect all of my ideas about our monitoring and think about how to split them into consistent smaller issues. Sorry for the noise in this old issue!

[1] https://its.cern.ch/jira/projects/CMSMONIT/issues/CMSMONIT-513

**Comment by belforte** [comment]
everything that we wanted to do at the time was done. I needs arise, we will act.
