### ISSUE TITLE
Plot time (and size) use by new execute(), executemany(), query_load_all_rows() in Grafana

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7338]
https://github.com/dmwm/CRABServer/pull/7255 is merged and deployed in production.
The next step is 
- Make Filebeat send `CRAB-*` logs to Logstash.
- Extract execution time (and data size) measure from `execute()`/`executemany()`/`query_load_all_rows()` function.
- Save Logstash output to ES (new index?). 
- Create new panel on Grafana.

**Comment by novicecpp** [comment]
Done

1. Output measure size of obj to logger in same format as measure time.  Also, tweak log format to make it easier to parse with grok in logstash. (https://github.com/dmwm/CRABServer/pull/7345)
 
2. Output of 1) are in `crabrest` log (`CRAB-*`). New change applied to filebeat/logstash config to process this logs and save to new ES index same place as httpcall/taskworker/publisher log (https://github.com/dmwm/CMSKubernetes/pull/1132)

3. Thanks @mrceyhun for review new Logstash config and ask MONIT to save it to new index.

4. Panel in Grafana are in [CRAB crabserver timber](https://monit-grafana.cern.ch/d/VML5DJEnk/crab-crabserver-timber?orgId=11&editPanel=52). Feel free to edit and/or have any comment.
![image](https://user-images.githubusercontent.com/2346664/182917233-f49b7462-b19f-4fc2-b6ab-88615a87bc31.png)

If no more discussion, I will close this issue tomorrow.

**Comment by belforte** [comment]
I think we need that you walk us through these plots to make sure we understand. Regardless of whether you close or not, I propose to do that in our next meeting

**Comment by novicecpp** [comment]
Ok, let discuss in next meeting.

What I wish for query time of execute/executemany is to differentiate between read and write SQL query.
Maybe I should put MeasureTime in `query()` instead (we use `query()` for SELECT statement only) :thinking:
