### ISSUE TITLE
extend ASO_Timeout when using Rucio

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7339]
in DagmanCreator should set CRAB_ASOTimeout classAd to a larger value for tasks using Rucio for stageout.
Rucio is supposed to keep trying almost forever !

Should also investigate a way to stop transfer attempts at that time, "detach_dids" ?
Doing that will prepare the ground for changing LFN in the resubmit step.

See https://github.com/dmwm/CMSRucio/issues/297#issuecomment-1188891772

@dciangot @KatyEllis FYI

**Comment by dciangot** [comment]
> well detaching dids from dataset is better left out here. We need to decide if we want to place calls to Rucio in the PostJob or make it somehow communicate with Rucio_transfers.py and keep all Rucio interactions in the latter. @dciangot

Can we evaluate a scenario where this happens at resubmission time? At that point we can put everything in the task_process, meaning:
- if user resubmits the job the task process will know that the this is a second try and should look for any previous try lfn and remove it from the dataset
- in case no resubmission happens, RUCIO will try until the rule expires. This is the tricky part, I think we should eventually converge toward a scenario where by default every crab made rule has an expiration time ( 1y? 1m? ) and more importantly PASS THIS MESSAGE to the users

**Comment by belforte** [comment]
@KatyEllis @dciangot  it turns out that current CRAB code is not "as careful as it should" and so although not desired, any user can overrride ASO_Timeout at submission time
just put this in crabConfig.py
```
timeout = 60*60*24*7  # 7 days in seconds
classAd = '+CRAB_ASOTimeout=%s' % timeout
config.Debug.extraJDL = [classAd]
```
so you can (ask your colleagues) to start testing with extended timeout already even before I put in production a modified TW. Even better this way, since you try different values, eventually we my have to hardcode a single value.

**Comment by belforte** [comment]
> Can we evaluate a scenario 
yes, but in a different issue, let's keep this focused on "allow a differente timeout for Rucio" and discuss elsewhere what the value should be etc. etc.

hmmm.. maybe I could simple add a secondd value to TW configuration, to give us some flexibility

**Comment by belforte** [comment]
- [ ] add ASORucioTimeout also in TW config. templates in puppet

**Comment by belforte** [comment]
puppet template changed [1] . Verified that new config. param is on `/data/container/TaskWorker/cfg/TaskWorkerConfig.py`

all done, ready to go

[1]
https://github.com/dmwm/CRABServer/issues/7339
