### ISSUE TITLE
TaskPublish tries to insert illegal dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7359]
in this task
https://cmsweb.cern.ch/crabserver/ui/task/220801_190609%3Aapresyan_crab_VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000_batch2_v1

CRAB eventually construct this output dataset name

/VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000/lpcdihiggsboost-NanoTuples-V2p0_lpclonglived-crab_PrivateProduction_Fall18_DR_step3_VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000_batch3_v1-3ee3afd6b5a1410aea6d0b4d52723d06-cd471944433cef30a1e69a7cb38aa7e8/USER

which is illegal (second piece between `/` is 200-char long instead of a max of 199)
so when TaskPublish tries to use it, it fails immediately at
https://github.com/dmwm/CRABServer/blob/644156d5b5e4bb8db199112055e84c5fe9e50418/src/python/Publisher/TaskPublish.py#L663
when trying to check what was published already (if any) becasue DBS server rejects the dataset name

checking the dataset name above with Lexicon.dataset returns

AssertionError: '/VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000/lpcdihiggsboost-NanoTuples-V2p0_lpclonglived-crab_PrivateProduction_Fall18_DR_step3_VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000_batch3_v1-3ee3afd6b5a1410aea6d0b4d52723d06-cd471944433cef30a1e69a7cb38aa7e8/USER' does not match regular expression ^/[a-zA-Z0-9\-_]{1,99}/[a-zA-Z0-9\.\-_]{1,199}/[A-Z\-]{1,50}$

**Comment by belforte** [comment]
so the question is how 


tm_publish_name = NanoTuples-V2p0_lpclonglived-crab_PrivateProduction_Fall18_DR_step3_VLLPair_VLLToTauS_MVLL1000_MS10_ctau1000_batch3_v1-3ee3afd6b5a1410aea6d0b4d52723d06-00000000000000000000000000000000

passed through the checks in 
https://github.com/dmwm/CRABServer/blob/644156d5b5e4bb8db199112055e84c5fe9e50418/src/python/CRABInterface/RESTUserWorkflow.py#L82

**Comment by belforte** [comment]
FWIW I verified that removing one char from the publishname, the `listDatasets` DBS query returns the expected empty list `[]` w/o any exception.

**Comment by belforte** [comment]
first finding. In that task submission, when RESTUserWorkflow is called, the argument
`kwargs['publishgroupname']` is set to 0 (False), so the check is done using `username` in place of `groupname` and since groupname=lpcdihiggsboost is 15 char, while username=apresyan is 8 char, the check is OK.

this suggest a possible general issue that `publishgroupname` is not set anymore.

**Comment by belforte** [comment]
Problem is likely in PostJob and likely there since a long time, if not ever :-(

**Comment by belforte** [comment]
problem started with this commit https://github.com/dmwm/CRABServer/commit/86cc6a519a119ce14fa35f7ac537e007dcf46deb

So it is 5 months that we always put groupname in outputdataset name even if the user did not ask for it. It looks like this new naming is not bothering anybody and maybe at this point is better to live with this and simply remove the flexibility. One parameter less to worry about.

actions:

- [ ] make sure that I undertand what exactly the previous code was doing. Do not want to miss things again.
- [ ] if all OK, change REST to sort of enforce `publishWithGroupName=True`
- [ ] remove this paramater from Client and from documentation

**Comment by belforte** [comment]
looks like in that commit lines like these
https://github.com/dmwm/CRABServer/blob/33bffcac8858925c445c8f9b920727218b932569/src/python/TaskWorker/Actions/PostJob.py#L2340-L2345
became like
https://github.com/dmwm/CRABServer/blob/86cc6a519a119ce14fa35f7ac537e007dcf46deb/src/python/TaskWorker/Actions/PostJob.py#L2724-L2733

i.e. I did not port over the check on `self.job_ad['CRAB_PublishGroupName']`

**Comment by belforte** [comment]
so the question is wheter to do 1. or 2. 

1. restore behaviour like until March ?
2. keep current one make check at submit time consistent so that it prevents illegal file names to seep through

@mapellidario @novicecpp @dciangot  @KatyEllis  any advice ? (I like to share blame for difficult decisions !)

I am leaning for 1. as indicated above in https://github.com/dmwm/CRABServer/issues/7359#issuecomment-1205427825 

maybe we can talk about this next Tuesday, hopefully the failure which made me look is a rare one.

**Comment by mapellidario** [comment]
I may have misunderstood something. 

In your comment https://github.com/dmwm/CRABServer/issues/7359#issuecomment-1205427825 you are suggesting to keep the current behavior and drop the support for `publishWithGroupName`, forcing it to true every time, aren't you? This would be option two, wouldn't it?

And thanks for investigating this, it really doesn't seem trivial!

**Comment by belforte** [comment]
sorry. I have indeed exchanged 1. and 2. in my previous posting. Let me edit and delete these comment

**Comment by KatyEllis** [comment]
I'd say prevent the illegal names seeping through, but I may not have understood the full consequences.

**Comment by belforte** [comment]
let's recap. In the following you can assume `PrimaryDataSet` to be some string defined by CRAB specific ot this task.

**Behavior 1:** no matter where user sends the output, data is published in a dataset named like
`/<PrimaryDataSet>/username-<userdefinetag>-<some-hash-added-by-CRAB>/USER`
 **unless** user does both these things:
 1  send output files to `/store/group/<groupname>/.....`
 2  sets in crabConfig. file the flag `publishWithGroupName=True`
in which case dataset name becomes
`/<PrimaryDataSet>/groupname-<userdefinetag>-<some-hash-added-by-CRAB>/USER`

**Behavior 2**: the configuration flag `publishWithGroupName` becomes irrelevant and whenever output files are sent to  `/store/group/<groupname>/.....`, output data is published in a dataset named
`/<PrimaryDataSet>/groupname-<userdefinetag>-<some-hash-added-by-CRAB>/USER`

WHere problem arise:
 Behavior 1 was working until version 3.220315 . At that point the code which creates the dataset name for publication was changed to be the same as in 2, while name checking was left as in 1. Users did not notice/complain that their datsets started being named after the group rather than themselves. But the dataset nema check at submission time is not coherent anymore with the actual naming. Hence an illegal dataset name can sneak through.

There are two possible solutions:
S1: properly restore behavior 1, needs a small change to PostJob code. Will suddenly change dataset naming for users (again)
S2: properly code behavior 2: needs a small change to CRAB Rest, will be transparent to users. We can then deprecate the `publishWithGroupName` parameter, cleanup all code and documentation which refers to it and overall simplify things.
I guess one could check in Task table of CRAB Oracel DB to find out how much that parameter was used in the past. I suspect one of those features added on  "one user whim" and which people can live without.

Hope I made things more clear. I agree that it is not easy to pick, but I do not want to have a "referendum" among users either.

**Comment by novicecpp** [comment]
> I guess one could check in Task table of CRAB Oracel DB to find out how much that parameter was used in the past. I suspect one of those features added on "one user whim" and which people can live without.

`SELECT COUNT(*) FROM TASKS t WHERE TM_PUBLISH_GROUPNAME != 'F' AND TM_START_TIME > TO_TIMESTAMP('2021-01-01', 'YYYY-MM-DD')`
Only 47 tasks from 2021-01-01 to now.
7 tasks from 2022-01-01 to now.

**Comment by belforte** [comment]
so conclusion is that currently we publish as `/primaryds/groupname-...` even if users did not ask for it (since so few did) and nobody noticed/complained of this change. Interesting data point !

**Comment by belforte** [comment]
we reached consensus on sticking with Behavior 2. I.e. keep current dataset names and
- [ ] fix REST to do the proper check and remove  `publishWithGroupName` from it
- [ ] remove  `publishWithGroupName` from documentation
- [ ] remove  `publishWithGroupName` from Client

**Comment by belforte** [comment]
hmmm.. need to remove extra option from client first, or server will complain about extra keyword.
In similar cases in the past we tried to make server compatible with both ways etc. etc., but it is a pain.
Since it is not urgent I will explore changing client first and rearrange order of boxes above.

**Comment by belforte** [comment]
CRABClient updated (tag [v3.221004](https://github.com/dmwm/CRABClient/releases/tag/v3.221004) ) and on its way to IB crab-dev https://github.com/cms-sw/cmsdist/pull/8118

**Comment by belforte** [comment]
REST and TW changes are now in [my branch](https://github.com/belforte/CRABServer/tree/deprecate-publishgroupname) and I checked that things works using new client from GH.
Will wait until new client is in production as crab-prod before making a PR.

**Comment by belforte** [comment]
one bit was still missing in REST side. I updated https://github.com/dmwm/CRABServer/issues/7359#issuecomment-1214138378
and testing now with Jenkins on `test2` with `crab-dev` client using code from https://github.com/belforte/CRABServer/tree/deprecate-publishgroupname on both `cmsweb-test2` and `crab-dev-tw01`

**Comment by belforte** [comment]
all good  [my branch](https://github.com/belforte/CRABServer/tree/deprecate-publishgroupname) is validated and ready to be merged as soon as CRAB Client v3.221004 is in production: https://github.com/dmwm/CRABServer/pull/7411

**Comment by belforte** [comment]
crab client update requested in https://github.com/cms-sw/cmsdist/pull/8159

**Comment by belforte** [comment]
CRABClient is not updated:
```
belforte@lxplus765/TC3> which crab
/cvmfs/cms.cern.ch/common/crab
belforte@lxplus765/TC3> crab --version
CRAB client v3.221018
```
time to finalize

**Comment by belforte** [comment]
tagged in v3.221114

**Comment by belforte** [comment]
v3.221114 deployed in preprod and validated https://github.com/dmwm/CRABServer/releases/tag/v3.221114
Closing
