### ISSUE TITLE
adapt FTS_Transfers.py to new rucio interface

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7364]
### description

When we ask FTS to make a transfer, we check via `rucio` if the source and destination RSE share a viable protocol that can be used to make the transfer. We use `from rucio.rse.rsemanager import find_matching_scheme` here

https://github.com/dmwm/CRABServer/blob/87489db86c04ec4bfa6b59ed5e9ba2dd2fce83e6/scripts/task_process/FTS_Transfers.py#L405-L411

This function uses the same data that is retrieved with 

```python
from rucio.client import Client
client = Client()
client.get_protocols("T2_CH_CERN")
```

historycally, the data that `get_protocols()` returned had a `third_party_copy` key

```plaintext
[{'domains': {'lan': {'delete': 0, 'read': 0, 'write': 0},
   'wan': {'delete': 1,
    'read': 1,
    'third_party_copy': 1,
    'write': 1}},
  ...
   'scheme': 'davs'}]
```

two months ago a backward compatible change was introduced and the data returned contained two more keys `third_party_copy_read` and `third_party_copy_write`

```plaintext
[{'domains': {'lan': {'delete': 0, 'read': 0, 'write': 0},
   'wan': {'delete': 1,
    'read': 1,
    'third_party_copy': 1,
    'third_party_copy_read': 1,
    'third_party_copy_write': 1,
    'write': 1}},
   ...
  'scheme': 'davs'}]
```

And yesterday (2022-08-18) Eric deployed Rucio 1.29. The last change is not backwards compatible with how we use `find_matching_scheme`, since it removes `third_party_copy` key

```plaintext
[{'domains': {'lan': {'delete': 0, 'read': 0, 'write': 0},
   'wan': {'delete': 1,
    'read': 1,
    'third_party_copy_read': 1,
    'third_party_copy_write': 1,
    'write': 1}},
  ...
  'scheme': 'davs'}]
```

thanks @flgomezc for providing the details!

The effect of such change on CRAB was that all ASO transfers failed. Logs reported

```plaintext
  -----> ASO log start -----
  ["Failed to map lfn to pfn: 'third_party_copy"]
  <----- ASO log finish ----
```

coming from https://github.com/dmwm/CRABServer/blob/87489db86c04ec4bfa6b59ed5e9ba2dd2fce83e6/scripts/task_process/FTS_Transfers.py#L421

Just a simple note to my future self: `crab checkwrite` was also failing.

However, not all output files transfer failed. Many sites had problems with local stageout, so some output files have been copied directly from the worker node to the destination site, skipping altogether the ASO. This task is an example [1]

As always, thank you @belforte for the precious help!

### mitigation

We sadly had to turn off CRAB. See https://cms-talk.web.cern.ch/t/emergency-crab-shutdown/14036

- [x] turn off TW
- [x] turn off REST
- [x] turn off all schedds

### solution(s)

For new tasks, we need to update how `FTS_Transfer.py` selects which protocol to use. Let's discuss it in a PR.

For already submitted tasks, we asked rucio operators to rollback the rucio version. Then we turn on CRAB again.

### more info

[1] https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&from=now-12h&to=now&var-site=All&var-user=dmapelli&var-task=220818_072508:dmapelli_crab_20220818_092504&var-schedd=0121&var-cmsUserId=&var-current_url=https:%2F%2Fmonit-grafana.cern.ch%2Fd%2FcmsTMDetail%2Fcms_task_monitoring&var-task_str=dmapelli_crab_20220818_092504&var-status=All&var-crabid=All&var-rest_host=https:%2F%2Fcmsweb.cern.ch:8443

**Comment by belforte** [comment]
also need to change crab client (for crab checkwrite) and TaskWorker (stageout check was still working using fallback protocol, but this is no good and wold not work for all destination sites)
.

**Comment by mapellidario** [comment]
In the `StageOutcheck.py` 

https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/src/python/TaskWorker/Actions/StageoutCheck.py#L96

we call `RucioUtils.py:getWritePFN()`

https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/src/python/RucioUtils.py#L48-L52

At the moment the production TW fails to check the `third_party_copy` operation via rucio client. 

```plaintext
2022-08-19 09:10:07,593:WARNING:RucioUtils,50:Try Rucio lfn2pn with operation third_party_copy
2022-08-19 09:10:07,631:DEBUG:connectionpool,452:https://cms-rucio.cern.ch:443 "GET /rses/T3_KR_KNU/lfns2pfns?operation=third_party_copy&lfn=cms%3A%2Fstore%2Fuser%2Fkimj
e%2FCRAB_PrivateMC%2FZZTo4mu_8p16TeV-pythia6%2F220819_070925%2F0008 HTTP/1.1" 500 113
2022-08-19 09:10:07,632:WARNING:RucioUtils,55:Rucio lfn2pfn resolution for third_party_copy failed with:
RSE does not support requested operation.
Details: Operation third_party_copy is not supported
Try next one.
2022-08-19 09:10:07,632:WARNING:RucioUtils,50:Try Rucio lfn2pn with operation write
2022-08-19 09:10:07,659:DEBUG:connectionpool,452:https://cms-rucio.cern.ch:443 "GET /rses/T3_KR_KNU/lfns2pfns?operation=write&lfn=cms%3A%2Fstore%2Fuser%2Fkimje%2FCRAB_Pr
ivateMC%2FZZTo4mu_8p16TeV-pythia6%2F220819_070925%2F0008 HTTP/1.1" 200 220
2022-08-19 09:10:07,660:INFO:RucioUtils,65:Will use gsiftp://cluster142.knu.ac.kr:2811/pnfs/knu.ac.kr/data/cms/store/user/kimje/CRAB_PrivateMC/ZZTo4mu_8p16TeV-pythia6/22
0819_070925/0008 as stageout location
```

This is something I noticed yesterday when checking fixing the stageout and that I fixed with this commit in #7365 https://github.com/dmwm/CRABServer/pull/7365/commits/030485155a15c36e67daf4e89c4fbff5d6f54174

notice that even with rucio 1.28.3 this is the help for `lfns2pfns`. It seems that `third_party_copy` is no longer among the supported operations

```python
from rucio.client import Client
help(Client.lfns2pfns)
```

```plaintext
lfns2pfns(self, rse, lfns, protocol_domain='ALL', operation=None, scheme=None)
    Returns PFNs that should be used at a RSE, corresponding to requested LFNs.
    The PFNs are generated for the RSE *regardless* of whether a replica exists for the LFN.

    :param rse: the RSE name
    :param lfns: A list of LFN strings to translate to PFNs.
    :param protocol_domain: The scope of the protocol. Supported are 'LAN', 'WAN', and 'ALL' (as default).
    :param operation: The name of the requested operation (read, write, or delete).
                      If None, all operations are queried.
    :param scheme: The identifier of the requested protocol (gsiftp, https, davs, etc).

    :returns: A dictionary of LFN / PFN pairs.
    :raises RSENotFound: if the RSE doesn't exist.
    :raises RSEProtocolNotSupported: if no matching protocol entry could be found.
    :raises RSEOperationNotSupported: if no matching protocol entry for the requested
                                      operation could be found.
```

I have two questions:

- was my fix for the stageout ok or is it causing problems?
- at the stageoutcheck, is it ok just to remove the `third_party_copy` among the operations that we check?

**Comment by mapellidario** [comment]
the plot thickens: the function `lfns2pfns()` accepts as arguments for "operation" also `third_party_copy_(read|write)`, not only `(read|write)`, but these two seem to give the same result.

```python
src_rse = "T2_IT_Legnaro"
dst_rse = "T3_CH_CERNBOX"
#src_rse = 'T2_DE_RWTH'
#dst_rse = 'T2_US_Caltech'
#src_rse = 'T2_BE_UCL'
#dst_rse = 'T2_US_Vanderbilt'
dids = ["cms:/store/user/ncsmith/my_file.root"]
dst_scheme, src_scheme, _, _ = find_matching_scheme(
    {"protocols": client.get_protocols(dst_rse)},
    {"protocols": client.get_protocols(src_rse)},
    "third_party_copy_read",
    "third_party_copy_write",
#     "third_party_copy",
#     "write",
)
pprint.pprint(dst_scheme)
pprint.pprint(src_scheme)

print("---")
src_pfns = client.lfns2pfns(src_rse, dids, operation="read", scheme=src_scheme)
dst_pfns = client.lfns2pfns(dst_rse, dids, operation="write", scheme=dst_scheme)
pprint.pprint(src_pfns)
pprint.pprint(dst_pfns)
print(src_pfns[dids[0]])
print(dst_pfns[dids[0]])
print("---")
src_pfns = client.lfns2pfns(src_rse, dids, operation="third_party_copy_read", scheme=src_scheme)
dst_pfns = client.lfns2pfns(dst_rse, dids, operation="third_party_copy_write", scheme=dst_scheme)
pprint.pprint(src_pfns)
pprint.pprint(dst_pfns)
print(src_pfns[dids[0]])
print(dst_pfns[dids[0]])
```

gives

```plaintext
DEBUG:dogpile.lock:value creation lock <dogpile.cache.region.CacheRegion._LockWrapper object at 0x7f0c7d60af40> acquired
DEBUG:dogpile.lock:Calling creation function for previously expired value
DEBUG:dogpile.cache.region:Cache value generated in 0.000 seconds for key(s): "host_to_choose_choice['http://cms-rucio.cern.ch']"
DEBUG:dogpile.lock:Released creation lock
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T3_CH_CERNBOX/protocols?protocol_domain=ALL HTTP/1.1" 200 830
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T2_IT_Legnaro/protocols?protocol_domain=ALL HTTP/1.1" 200 667
'davs'
'davs'
---
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T2_IT_Legnaro/lfns2pfns?scheme=davs&operation=read&lfn=cms%3A%2Fstore%2Fuser%2Fncsmith%2Fmy_file.root HTTP/1.1" 200 135
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T3_CH_CERNBOX/lfns2pfns?scheme=davs&operation=write&lfn=cms%3A%2Fstore%2Fuser%2Fncsmith%2Fmy_file.root HTTP/1.1" 200 106
{'cms:/store/user/ncsmith/my_file.root': 'davs://t2-xrdcms.lnl.infn.it:2880/pnfs/lnl.infn.it/data/cms/store/user/ncsmith/my_file.root'}
{'cms:/store/user/ncsmith/my_file.root': 'davs://eosuserhttp.cern.ch:443/eos/user/n/ncsmith/my_file.root'}
davs://t2-xrdcms.lnl.infn.it:2880/pnfs/lnl.infn.it/data/cms/store/user/ncsmith/my_file.root
davs://eosuserhttp.cern.ch:443/eos/user/n/ncsmith/my_file.root
---
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T2_IT_Legnaro/lfns2pfns?scheme=davs&operation=third_party_copy_read&lfn=cms%3A%2Fstore%2Fuser%2Fncsmith%2Fmy_file.root HTTP/1.1" 200 135
DEBUG:urllib3.connectionpool:http://cms-rucio.cern.ch:80 "GET /rses/T3_CH_CERNBOX/lfns2pfns?scheme=davs&operation=third_party_copy_write&lfn=cms%3A%2Fstore%2Fuser%2Fncsmith%2Fmy_file.root HTTP/1.1" 200 106
{'cms:/store/user/ncsmith/my_file.root': 'davs://t2-xrdcms.lnl.infn.it:2880/pnfs/lnl.infn.it/data/cms/store/user/ncsmith/my_file.root'}
{'cms:/store/user/ncsmith/my_file.root': 'davs://eosuserhttp.cern.ch:443/eos/user/n/ncsmith/my_file.root'}
davs://t2-xrdcms.lnl.infn.it:2880/pnfs/lnl.infn.it/data/cms/store/user/ncsmith/my_file.root
davs://eosuserhttp.cern.ch:443/eos/user/n/ncsmith/my_file.root

```

**Comment by novicecpp** [comment]
> the plot thickens: the function lfns2pfns() accepts as arguments for "operation" also third_party_copy_(read|write), not only (read|write), but these two seem to give the same result.

Do you have reference on this that `lfns2pfns` really accept both?

**Comment by mapellidario** [comment]
no reference, I just tried and it worked. 

the best reference that I can think of is `help(lfns2pfns)` which only mentions `(read|write|delete)`. We may want to ask Felipe. @flgomezc what do you think?

**Comment by belforte** [comment]
All of those calls "come from Nick and/or Eric", originally as per https://twiki.cern.ch/twiki/bin/view/CMSPublic/RucioUserDocsLocation#LFN_to_PFN_conversion then adapted upon suggestions/conversation with either of them. There may be something useful in commit history (see blame in GH), but I am not sure, even if I am the one who put that code in there.
It is of no use to complain that Rucio documentation stinks, they know.

The point is that copying one file from local disk to a remote Rucio Storage Element (RSE) is different from moving data between two RSE's.  At first sigh I'd claim that 
*  **YES** at the stageoutcheck, is it ok just to remove the third_party_copy among the operations that we check

and it was there due to historical reasons, transition perdiod from gsiftp to webdav etc. etc., in a world where : all RSE have a webdav endpoint and we only want to use that, things should be simpler.

But we may need to do some tests together on MMost/Zoom

**Comment by belforte** [comment]
next time please leave out those annoying messages from Rucio's dogpile.

**Comment by belforte** [comment]
and from urllib3.connectionpool

**Comment by belforte** [comment]
beware that different args. my give same output for one specific RSE, but not necessarely for all. It depends what's in the RSE config of each site. Need to spend some time with Felipe to be told **authoritatively** what to use. In the end it is not as much Rucio as "what CMS DataOps write in each RSE config". They (CMS Data Transfer team) decide which protocol is associated with each key", in combination with Site Support and site admins of course, so Felipe may send you to Pau who may defer to Lammel etc. etc... You know how it works by now. Hopefully on this line will stop with Eric (at worst), no need to reach up to Brian.

**Comment by mapellidario** [comment]
I spent the afternoon at Felipe's office and I will try to summarize here what I discovered. I am sorry if I add some information that Stefano is already aware of.

### overview

When we use `from rucio.rse.rsemanager import find_matching_scheme` or `from rucio.client import Client; Client().lfns2pfns()`, rucio retrieves the information from the same oracle table. We can access the same data via the rucio CLI and it looks something like:

```plaintext
> rucio-admin rse info T2_IT_Pisa
[...]
Protocols:
==========
  davs
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 2, "write": 2, "delete": 2, "third_party_copy_read": 1, "third_party_copy_write": 1}}'
    [...]
    scheme: davs
  srm
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy_read": 2, "third_party_copy_write": 2}}'
    [...]
    scheme: srm
```
Every protocol has two domains:

- "lan" for local transfers. If I understand correctly our code, we do not use rucio to negotiate the protocol to use for the local stageout, we just use `srm` [1]. Therefore, I would not care about this domain.
- "wan" for remote access. This is what I would focus our attention on.

Every domain can have multiple "operations"

- `read` / `write` / `delete`: these are related to gfal operations, which we use for the direct stageout, if I understand correctly.
- `third_party_copy_write` / `third_party_copy_read`: these are related to FTS operations, which we use for ASO.

every operation has an integer value:

- zero: disabled
- non-zero: enabled. the lower the number, the higher the priority. -> `1` is the highest priority

Taking `T2_IT_Pisa` as an example, the information pasted above mean that 

- local operations are disabled
- remote operations are enabled. When using FTS, then davs has higher prio than srm. When using gfal, srm has higher prio than davs.

General observations:

- all of the RSEs that we care about for FTS or direct stageout transfers have `third_party_copy_(read|write)` enabled on davs protocol.
- the RSEs that do not have it are either tapes, tests or RSEs that have been decomissioned and that need to be removed from the aforementioned rucio oracle table. 

### how does this relate to our codebase

Now we can get to some practical consideration about how we retrieve information from this rucio table in our code.

1. In general, we used to often rely on the "operation" `third_party_copy` when getting information about available protocols and PFNs. however this column has been removed from rucio table since v1.29,  see https://github.com/rucio/rucio/issues/5634 . This column has been superseded by the two columns `third_party_copy_(read|write)`.
1. in `FTS_Transfers.py` we use rucio to select a scheme common between source and destination, here https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/scripts/task_process/FTS_Transfers.py#L406 Instead of `third_party_copy` we should use `third_party_copy_(read|write)` This has been fixed in #7365 
1. in `FTS_Transfers.py` we use rucio to get the PFNs to pass to FTS, here https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/scripts/task_process/FTS_Transfers.py#L412-L415 Instead of `third_party_copy` we should use `third_party_copy_(read|write)`. In #7365 i replaced `third_party_copy` with `(read|write)`, which is conceptually wrong. I suspect we did not notice yet because often the endpoints are the same, but we'd better fix it. The proper solution is on his way in #7369 .
2. If I understand correctly, in `DagmanCreator.py` we call `RucioUtils.py:getWritePFN()` to select a PFN for the direct stageout. https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/src/python/TaskWorker/Actions/DagmanCreator.py#L612 Here we should not care about FTS, so we should look for `write` operation only. A fix is coming in #7369 
3. In `StageoutCheck.py` we call again `RucioUtils.py:getWritePFN()` to select a PFN for checking the Stageout. If I understand correctly, here we want to check the ASO only, so we should focus on FTS only, so we should consider PFNs from `third_party_copy_(read|write)` only. https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/src/python/TaskWorker/Actions/StageoutCheck.py#L96 A fix is coming in #7369 
4. In CRABClient, in the command `checkwrite`, we use gfal commands to check if a user can write a destination site. https://github.com/dmwm/CRABClient/blob/353922ee52d89d1c59e54c5aa6603c35fda0da64/src/python/CRABClient/Commands/checkwrite.py#L182 Since we do not use FTS for this, we should simply stick to `(read|write)` and simply drop `third_party_copy`. a fix is coming in https://github.com/dmwm/CRABClient/pull/5171 

### conclusion

thanks @flgomezc for the guidance. Now that your name is here, you will get part of the blame is something goes wrong :)

I hope this answers some questions that may arise about my recent PRs. As always, I am aware that I may have misunderstood something and I am open to suggestions

### more info

[1] https://github.com/dmwm/CRABServer/blob/1a616ba65ca76ffd21629c512de186fddcf66e4b/scripts/cmscp.py#L1254

**Comment by belforte** [comment]
thanks for having got a description of how those protocols/operation/priority fields are used ! This is enlightening and I dearly missed until now !!!

OTOH I am not happy to have a different check on 5. and 6. I think I see the reasons for your choices, but in the end there's no 'clearly right/clearly wrong' here. We need to make some tradeoff. And we may need more experience with DAVs.

**Comment by novicecpp** [comment]
Thanks a lot Dario. That is awesome discovery!

I think 6. should be `third_party_copy_(read|write)` because it will be use in FTS later. Example is a site allow direct read/write but not allow third_party_copy, users jobs will failed transfer to those site even though users check it with `crab checkwrite` and it passed.

**Comment by belforte** [comment]
I made a mistake: it is not
>  tell me which protocol this site will use when asked to do a third-party-copy operation 

but rather:
`tell me which protocol to use when I want to ask this site to take part in a third-party-copy operation`

and the fact that we now have `third_party_read` and `third_party_write` means that we want (need ?) to be prepared for a site (better stated a Rucio Storage Element RSE) to require clients to use two different protocols for read and write. Which I think there is no example of so far.

So technically speaking, if we do a direct gfal-copy from local disk to the RSE, i.e. not a 3rd party copy operation, we may find that it does not work because the site wants a different protocol for this, again, currently there is no example of such thing.

Somehow we (CRAB) is doing something bad here, we use a direct copy operation to test the capability of the remote RSE to perform a TPC. OTOH we do  not want to debug protocol mismatches here, only verify that the user has write access and did not fill the disk/quota. 

All of this is irrelevant as long as (like now) we can use the TPC protocol (davs) also for direct copy. But.. one day... this may break. I do not see any good solution atm rather than "be aware".

Of course we could do a TPC for the test, placing a test file on e.g. CERN EOS, but will need to make sure that we can interprete the error messages at least to tell an error due to CERN (always possible) from an error from the remote RSE.
Would that be a smart thing to do ? Or a stupid overkill ?

**Comment by mapellidario** [comment]
I think this all boils down to the fact that crab checkwrite is a test and first we think about what we want to test, then we think about how to test it.

1. Do we want to test that the user has write permission on a specific RSE? Then we may live fine with a direct copy from lxplus to the destination site.
1. Do we want to test that the site accepts TPC on behalf of the user? Then we create a file on lxplus, we copy it to CERNBox with gflal, then we use TPC from CERNBox to the destination RSE.

I think we can have both tests in `crab checkwrite`, I do not think they should be mutually exclusive.

**Comment by belforte** [comment]
+1 @mapellidario 
(although this is diverging into an issue more suited for CRAB Client)
let me also comment that as you point out "what we want to test" is clearly arbitrary and may change as operation status change. So far emphasis was on "user has write access and is not over quota", in a future Rucio stageout scenario these becomes less important. So we also need to:
* know what we are doing
* be prepared to change

the nature of CRAB is to hide users from the outside world, the only way to provide a constant interface and uniform experience is to continuously adapt the tool.

**Comment by belforte** [comment]
time to close this ? Maybe there's some non critical action still to be followed up opening ad hoc issues, but a critical issue still open after one month makes little sense

**Comment by belforte** [comment]
shall we close ? @mapellidario

**Comment by mapellidario** [comment]
Yes, I agree. We should be good to go both in TW and in the client. Closing.
