### ISSUE TITLE
TaskPublisherGo - small bug in checkBlockMigration

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7379]
While reading `tasks/mlink/220824_154340:mlink_crab_QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8.log `, i noticed

```plaintext
2022-08-26 16:24:15,898:INFO: 43 block migrations in progress. Will check migrations status in 30 seconds.
2022-08-26 16:24:46,026:ERROR: migration terminally failed for /QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#bb86957c-1dc6-4757-a079-d2c102773c83

2022-08-26 16:24:46,027:ERROR: migration status details:
9
2022-08-26 16:24:46,027:ERROR: Could not get migration status for /QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#bb86957c-1dc6-4757-a079-d2c102773c83:
'int' object is not subscriptable
```

Migration status detail is clear, status `9` should be terminally failed, but while parsing the response from `DBSMigrate/status` something goes bad and we fall back to " Could not get migration status ..." instead of the proper "Migration terminally failed".

I think this is caused by this line https://github.com/dmwm/CRABServer/blob/cf47500951e11fc4ae2ef01f069c2d0efd54f93d/src/python/Publisher/TaskPublishGo.py#L297

I will provide a fix, which I have not tested but it is better than nothing anyways

**Comment by mapellidario** [comment]
The migration status taken directly from the DBS is

```
> curl -L --key $X509_USER_PROXY --cert $X509_USER_PROXY "https://cmsweb-prod.cern.ch/dbs/prod/phys03/DBSMigrate/status?migration_rqst_id=3311435" 

[
{"create_by":"service@crab-prod-tw01.cern.ch","creation_date":1659539136,"last_modification_date":1659539562,"last_modified_by":"service@crab-prod-tw01.cern.ch","migration_input":"/QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#bb86957c-1dc6-4757-a079-d2c102773c83","migration_request_id":3311435,"migration_server":null,"migration_status":9,"migration_url":"https://cmsweb-prod.cern.ch:8443/dbs/prod/global/DBSReader","retry_count":3}
]
```

**Comment by mapellidario** [comment]
for future reference: I found this file with

```plaintext
find tasks -type f -iname "2208*log" -exec stat --format '%Y :%y %n' "{}" \; | sort -nr | cut -d: -f2- | head -n500 | awk '{print $4}' | xargs -n1 grep -m 1 -l "check migration status" 
```

**Comment by belforte** [comment]
these lines make no sense
```
2022-08-26 16:24:46,026:ERROR: migration terminally failed for /QCD_Pt-120To170_MuEnrichedPt5_TuneCP5_13TeV-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM#bb86957c-1dc6-4757-a079-d2c102773c83
2022-08-26 16:24:46,027:ERROR: migration status details:
9
```
assuming that they come from 
https://github.com/dmwm/CRABServer/blob/19765c6a1a1fa2986de70ef180b9fd988a59d606/src/python/Publisher/TaskPublishGo.py#L308-L309
`result` is a list of dictionaries, why `9` ia printed ?

**Comment by belforte** [comment]
btw https://github.com/dmwm/CRABServer/blob/cf47500951e11fc4ae2ef01f069c2d0efd54f93d/src/python/Publisher/TaskPublishGo.py#L297 looks good to me

**Comment by mapellidario** [comment]
> this line makes no sense

Is it possible that the line you mention is simply from before I deployed #7380 to production?

**Comment by belforte** [comment]
yes it is. Shall we close then ? And wait for more reproducible issues ?

**Comment by mapellidario** [comment]
Yeah, you are right. #7380 has been running in production since days and we can claim it has been tested enough at this point. Thanks Stefano for having a look and forcing some cleanup of the issues I open!

I will close this issue
