### ISSUE TITLE
disaster recovery - periodically clone GH repo to gitlab.cern.ch

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7394]
This involves at least two things (please, feel free to change the issue description if you want to add action items):

- [ ] periodically clone code from GH to gitlab
- [ ] periodically clone issues from GH to gitlab

The main official doc on how to perform this is available at https://docs.gitlab.com/ee/user/project/import/github.html, but I had only a quick look and further guides may be required.

**Comment by novicecpp** [comment]
Can we change this issue to general discussion about disaster recovery?
I want to add disaster recovery's runbook to the TODO list in here.

**Comment by belforte** [comment]
is this going to happen as a side-product of the import in gitlab for the new CI pipeline ?

**Comment by novicecpp** [comment]
Yes.
Let's keep this issue open and wait until [#8267](https://github.com/dmwm/CRABServer/issues/8267) is solved.

**Comment by novicecpp** [comment]
Done indirectly by https://github.com/dmwm/CRABServer/pull/8483#issuecomment-2160387235
