### ISSUE TITLE
If a task is on taperecall, crab kill should remove rucio rule

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7406]
When a task goes into taprecall status, a rucio rule is created to copy the data from tape to disk.
If the user then decides that he does not need the full dataset to be replicated and for example prefers using `partialDataset` option, it would be better if he/she kill the original task in taperecall and crab deletes the rucio rule.

Supersedes #6342

**Comment by belforte** [comment]
but still the action described in #6342 should be done:
 - [ ] do not call the kill `execute_internal` action which will try to stop a non-exiting DAG and fail

**Comment by belforte** [comment]
time to raise priority

**Comment by belforte** [comment]
review of needed actions:
- [ ] 1. introduce KILLRECALL status as per #5608 
- [ ] 2. deal with it in periodic action https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/TapeRecallStatus.py
- [ ] 3. fix https://github.com/dmwm/CRABServer/issues/7406#issuecomment-1259609833

**Note** can't deploy 1. unless a tested fix for 2. is also in the TW.

**Comment by belforte** [comment]
review of needed actions:
- [ ] 1. introduce KILLRECALL status as per #5608 
- [ ] 2. deal with it in periodic action https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/TapeRecallStatus.py
- [ ] 3. fix https://github.com/dmwm/CRABServer/issues/7406#issuecomment-1259609833

**Note** can't deploy 1. unless a tested fix for 2. is also in the TW.
