### ISSUE TITLE
make it easy to notice sched restart in dashboards

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7409]
would be good to notice clearly when a condor scheduler restarted in our dashboard(s).
Currently the best way is this panel in the CRAB Metric dashboard
![image](https://user-images.githubusercontent.com/1837785/193218430-c383314f-59ea-4250-804c-b066cf6819e4.png)

Problems:
 * this is not visible in Overview dashboard since it uses 1h binning. We could switch to `auto` but than granularity is not the same as other panels anymore
 * restarts are only visible there if they last "long enough"
 * restarts may anyhow become invisible if the time range of the panel is longish
 
is this a good use case for annotations ?

**Comment by belforte** [comment]
FYI @novicecpp

**Comment by novicecpp** [comment]
Thanks for open an issue, Stefano.
I will looking for solution.

I think put restart/uptime metrics here would be better (plus alert?).

**Comment by belforte** [comment]
brain dump follows, feel free to ignore and even delete !
maybe use annotation to put a cyan vertical bar when something relevant (for us) happened ? Monitor group (aka Ceyhun) enabled this some time ago, but the annotations they send are "all messages in some CERN list" which are mostly irrelevant so I keep them disabled. Something like this would have the advantage that you can e.g. look back in time and see the restarts,
while a text panel with restart messages would be good for current ops but not for past. A time series like panel with vertical bars would be somehow like annotations but how do we know what exactly was restarted ?

**Comment by belforte** [comment]
too difficult to do for too little gain
