### ISSUE TITLE
task monitor UI transfers tab needs changes for Rucio

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7421]
when a task uses Rucio as ASO, the transfer tab of the server UI presents the Rucio rule-id in place of the FTS logurl.
![image](https://user-images.githubusercontent.com/1837785/194058738-7f8eaae3-d000-4ef6-9ec2-2b92d60588f0.png)

This is good, but 
 - [ ] `FTS job` column mane should be changed to `Rucio rule`
 - [ ] the pointer associated to the rule now is formatted as a broken ftsmon url `https://fts3-cms.cern.ch:8449//fts3/ftsmon/#/job/1eaf5ed07c4f4e8798dc40b41b405118`, should be instead a pointer to Rucio rule info page `https://cms-rucio-webui.cern.ch/rule?rule_id=1eaf5ed07c4f4e8798dc40b41b405118#locks`

**Comment by belforte** [comment]
@dciangot is this something you can do quickly and easily (it is your code) or should we assign to me or check if Dario or Wa have some js experience already  and can do ?

**Comment by dciangot** [comment]
For reference before I forget it:

Column title here: https://github.com/dmwm/CRABServer/blob/master/src/html/index.html#L258

Conditional link address here: https://github.com/dmwm/CRABServer/tree/master/src/script#L458-L465

**Comment by dciangot** [comment]
Do you think it would be possible to work "live" this on a testbed pod @belforte ?

**Comment by belforte** [comment]
Yes. I cannot help atm. Talk to Wa for access to test11sent from Stefano's mobileOn Oct 6, 2022 2:54 PM, dciangot ***@***.***> wrote:
Do you think it would be possible to work "live" this on a testbed pod @belforte ?

**Comment by novicecpp** [comment]
Fixed in https://github.com/dmwm/CRABServer/pull/7801
