### ISSUE TITLE
Rucio ASO should cleanup file replica in temp

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7423]
with reference to https://github.com/dmwm/CMSRucio/issues/159#issuecomment-1270713057
When transfer is completed, the script should launch a gfal-rm, like it is done currently, to limit reliance on site's crontab.
Once it will be possible we will also remove the replica information from Rucio.

**Comment by belforte** [comment]
we need to understand how Temp_RSe and RSE deal with /store/temp/user, who has quota, who can delete, where does Reaper run etc.

**Comment by novicecpp** [comment]
@dynamic-entropy told me that we should treat Temp_RSE as read-only data source for Rucio.  No quota, no reaper.
We may need to ask Site Support instead on how sites operate on `/store/temp/` area.

**Comment by belforte** [comment]
I disagree with @dynamic-entropy . That's the same disk directory where we currently put files that will be moved by FTS and do actively try to delete them after transfer via gfla-rm.  We also ask sites to run a crontab which deletes file after a max 3 weeks, so actual replicas will be gone one way or another. The sooner the better because we need the temporary space. What would be different from the site manager "rm" and our "gfal-rm" other than issued a bit sooner or later ? We surely need to make Rucio aware that those replicas are gone and the sooner Rucio "knows" that they are gone, the better. Once the transfer rule is satisfied, there will be no locks on the replica in the Temp_RSE. IIUC the Reaper will delete the unlocked replica and remove it from Rucio's DB. If we do not run the Reaper, how do we achieve this ? We can't keep Rucio thinking forever that there is a file there.

**Comment by dynamic-entropy** [comment]
Hi @belforte 
That is the state of the system right now. I completely agree with you. 
But as far as I remember, we all have been aware of this for more than a year now (@dciangot ) but never created an action plan for replicas on Temp RSEs. 
Cheers

**Comment by belforte** [comment]
can we start by listing what is technically possible ?
Maybe running the Reaper is not :-)

What will happen if we call `rucioClient.delete_replicas()` ? Does it simply remove the entry from the DB ? Or does it purge the physical file as well ?

Maybe we have a problem of file ownership ? Rucio DN can possibly not delete files created by user DN, that's why a gfal-rm issued with user proxy by CRAB script may be better. Waiting for tokens...
