### ISSUE TITLE
ci/cd - consolidate crabserver rpms build from private branches

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7451]
### problem description

Building crabserver rpms from private branches with https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_BuildOnRelease/ is not the best experience ever. 

Right now It requires passing:

- the repo, for example `mapellidario/CRABServer`
- the branch name, for example [20221026_jobwr](https://github.com/mapellidario/CRABServer/tree/20221026_jobwr)
- the release tag that points to the last commit of the aforementioned branch, for example https://github.com/mapellidario/CRABServer/releases/tag/v3.221026.dario.6

### solution

I would need to improve the [jenkins_build_rpm.sh ](https://github.com/mapellidario/CRABServer/blob/20221026_jobwr/cicd/build/jenkins_build_rpm.sh) script so that repo+branch or repo+tag are enough to build the rpm.

### work in progess

A first draft of what I would like to implement is at https://github.com/dmwm/CRABServer/compare/master...mapellidario:20221103_rpm  , but it still lacks the final touches. I will open a PR when it is ready.

fyi: @novicecpp

**Comment by mapellidario** [comment]
See comments in https://github.com/dmwm/CRABServer/pull/7474

builds from tags on dmwm/CRABServer works as before, while build from private repos can be made providing:

- [x] repo, branch, tag. available since some time
- [x] repo, tag: done in #7474 
- [ ] repo, branch. this requires either asking for helpl to Shahzad or a manual change of cms-sw/pkgtools/cmsBuild. I will explore some options in the coming days.

**Comment by belforte** [comment]
is `repo, branch` really needed ? an exta trag in private repo is very cheap. Why do you want to waste time investigating ?

**Comment by mapellidario** [comment]
not needed anymore, superseded by new ci/cd
