### ISSUE TITLE
Jenkins integration tests - which cmssw/scram arch versions should we use?

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7464]
The file [testingConfig](https://github.com/dmwm/CRABServer/blob/master/test/testingConfigs) provides the list of the cmssw version and scram arch pairs that we use to test CRAB with our integration tests [1]. The full list of available cmssw versions is at [2].

Action items:

- [x] add cmssw 12_5 / el8
- [x] fix tests for scram_arch el8 [3]
    - [x] why did we not use the singularity container for https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_CheckTestResults/ ? I need to dig into the scripts
    - [ ] work in progress at: https://github.com/dmwm/CRABServer/compare/master...mapellidario:20221121_py3executetest
- [x] update cmssw 12_6 after it is released
- [x] remove 12_0? do we want to do it, or do we want to keep testing cmssw 12 with slc7?
- [ ] we should run tests on other archs, but there still some open questions
  - [ ] can we? do we have arm nodes connected to jenkins? 
  - [ ] can we submit a non-x86 job from an x86 machine?

If anybody else has suggestions, they are welcome!

Issue spawned from this comment by Stefano: https://github.com/dmwm/CRABServer/pull/7449

---

[1] https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/
[2] https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML
[3] If we use slc7 continainer for running tests that require el8, we get and error

<details><summary>using slc7 for el8</summary>

https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/336/console

```plaintext
17:17:30 Status: Downloaded newer image for registry.cern.ch/cmscrab/crabtesting:220701
17:17:32 WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
17:17:53 WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
17:17:53 WARNING: Developer's area is created for architecture el8_amd64_gcc10 while your current OS is slc7_amd64.
17:17:56 /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/bin/python3: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:56 /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/bin/python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:56 /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/bin/python3: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:56 /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/bin/python3: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:56 git: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by git)
17:17:57 python3: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:57 python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:57 python3: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:57 python3: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:57 taskSubmission.sh: line 68: cd: CRABServer/test/clientValidationTasks/: No such file or directory
17:17:57 
17:17:57 Starting task submission for Client Validation testing.
17:17:57 
17:17:57 
17:17:57 Submitting file: ./testingScripts/statusTracking.py
17:17:57 python3: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0) python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0) python3: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0) python3: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
17:17:57 + export ERR=true
17:17:57 + ERR=true
17:17:57 + cd /build/cmsbld/jenkins/workspace/CRABServer_ExecuteTests
```

</details>

<details><summary>using cc8 for el8</summary>

https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/337/console

```plaintext
17:38:54 + /cvmfs/cms.cern.ch/common/cmssw-cc8 -- ./taskSubmission.sh
17:39:00 WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
17:39:39 WARNING: In non-interactive mode release checks e.g. deprecated releases, production architectures are disabled.
17:39:40 /cvmfs/cms.cern.ch/share/lcg/SCRAMV1/V3_00_53/bin/scram: line 10: /cvmfs/cms.cern.ch/el8_aarch64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_aarch64_gcc10/bin/python3: cannot execute binary file: Exec format error
17:39:42 /cvmfs/cms-ib.cern.ch/nweek-02758/share/cms/crab-prod/v3.221018.00/bin/crab: line 7: /cvmfs/cms.cern.ch/el8_aarch64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_aarch64_gcc10/bin/python3: cannot execute binary file: Exec format error
17:39:42 /cvmfs/cms-ib.cern.ch/nweek-02758/share/cms/crab-prod/v3.221018.00/bin/crab: line 7: /cvmfs/cms.cern.ch/el8_aarch64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_aarch64_gcc10/bin/python3: Success
17:39:42 
17:39:42 Starting task submission for Client Validation testing.
17:39:42 
17:39:42 
17:39:42 Submitting file: ./crabConfiguration.py
17:39:42 /cvmfs/cms-ib.cern.ch/nweek-02758/share/cms/crab-prod/v3.221018.00/bin/crab: line 7: /cvmfs/cms.cern.ch/el8_aarch64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_aarch64_gcc10/bin/python3: cannot execute binary file: Exec format error /cvmfs/cms-ib.cern.ch/nweek-02758/share/cms/crab-prod/v3.221018.00/bin/crab: line 7: /cvmfs/cms.cern.ch/el8_aarch64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/external/el8_aarch64_gcc10/bin/python3: Success
17:39:42 + export ERR=true
17:39:42 + ERR=true
17:39:42 + cd /build/cmsbld/jenkins/workspace/CRABServer_ExecuteTests
17:39:42 + mv /build/cmsbld/jenkins/workspace/CRABServer_ExecuteTests/artifacts/failed_tasks /build/cmsbld/jenkins/workspace/CRABServer_ExecuteTests/
17:39:42 + true
17:39:42 + echo -e 'Something went wrong during task submission. Find submission log [here](https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_ExecuteTests/337/console). None of the downstream jobs were triggered.'
17:39:42 + sleep 20
```

</details>

**Comment by belforte** [comment]
@mapellidario I am not sure what is the question about singularity (you say "why we use" here and "why we do not use" in the comment in the jenkins build file). Maybe we can exapand in MatterMost ? Anyhow this may simply be that you can run crab status from e.g. lxplus7 SL7 environment for a task submitted from the singularity SL6 env. CRABClient code works the same way in either and files read from other places are all JSON or PKL so py2/3 independent.

**Comment by belforte** [comment]
as to testing CMSSW_12 on slc7 instead of el8, I think we want to go with the default production architecture, i.e. whatever happens on lxplus7 when you do `cmsrel CMSSW_12_x`. The goal is to test the environment which users are using. if I look at your [2], switch from scl7 to el8 happens when moving from CMSSW_12_3 to CMSSW_12_4

**Comment by belforte** [comment]
btw IMHO we do no want to have a Jenkins test for each 12_N, 13_N etc. one test for each major series should be enough to check that we stay compatible.

**Comment by mapellidario** [comment]
> I am not sure what is the question about singularity

yeah, i missed a negation here in the issue description, sorry! 

> Anyhow this may simply be that you can run crab status from e.g. lxplus7 SL7 environment for a task submitted from the singularity SL6 env

aaah ok, I see. this was quicker than checking the scripts, thanks!

> whatever happens on lxplus7 when you do cmsrel CMSSW_12_x

eh, it depends! If you do a straight `cmsrel CMSSW_12_x`, then you have

```
# lxplus7
> cmsrel CMSSW_12_5_2
WARNING: Developer's area is created for non-production architecture slc7_amd64_gcc10. Production architecture for this release is el8_amd64_gcc10
```

otherwise

```
# lxplus7
> export SCRAM_ARCH=el8_amd64_gcc10
> cmsrel CMSSW_12_5_2
WARNING: Developer's area is created for architecture el8_amd64_gcc10 while your current OS is slc7_amd64.
```

However, I would suggest that since the production architecture for 12_4, 12_5 and likely all the next ones is `el8`, one should not use lxplus7 to submit jobs with cmssw 12_4 and newer

```
# lxplus8
> cmsrel CMSSW_12_5_2
ERROR: Unable to find release area for "CMSSW" version "CMSSW_12_5_2" for arch cs8_amd64_gcc10.
       Please make sure you have used the correct name/version.
       You can run "scram list CMSSW" to get the list of available versions.
> export SCRAM_ARCH=el8_amd64_gcc10
> cmsrel CMSSW_12_5_2
```

**Comment by mapellidario** [comment]
I made a couple of tests with lxplus7, since I haven't been touching it since a long time:

with 

- el8_amd64_gcc10
- CMSSW_12_6_0_pre4, CMSSW_12_5_0

I get

```bash
> [19:31] lxplus723 4-script
> export CRABCONFIGINSTANCE=prod && crab submit
python3: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_pre4/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
python3: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_pre4/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
python3: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_pre4/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
python3: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /cvmfs/cms.cern.ch/el8_amd64_gcc10/cms/cmssw/CMSSW_12_6_0_pre4/external/el8_amd64_gcc10/lib/libpython3.9.so.1.0)
```

while with

- slc7_amd64_gcc10 (default, no export required)
- CMSSW_12_5_2

I can properly submit a task

**Comment by belforte** [comment]
is it supported to use el8 arch on lxplus7 ?
Sorry for not being clear with "whatever happens on lxplus7". In the end I meant
 use slc7 arch for CMSSW_12_0/1/2/3
 use el8 arch for CMSSW_12_4 or higher
 and for each arch submit from whatever Shahzad says is the supported platform (i.e. where they test things).
Maybe we should move to Mattermost or zoom, it is not good to go back and forth like this in an issue.
In the end we do not want to validate CMSSW on various places, and already Shahzad runs a crab test in CMSSW continuous integration, so they will not break it badly in a new release w/o noticing (as it happened in the past). Jenkins tests for us are more about testing multiple use cases to make sure we do not have bad side effects from out changes, and that we do not put in CRABClient code which does not work on older python versions. The key point is that we pick python from CMSSW and the version associated with a given release will never change.

* N.B. you may have noticed that several crab client commands are not tested in sl6, exactly because in case of need users can do a crab remake on sl7 (if they do not have a shared directory on both OS) and e.g. do crab getoutput where it works.

Maybe I miss something, maybe our set of Jenkins tests is already too long. But before we get sidetracked, let's make sure that we have the goals under control.

**Comment by belforte** [comment]
We did all we could and are happy now
