### ISSUE TITLE
recent TW docker images require explicit permission to use old openssl version

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7475]
Similar to what we observed for crabserver REST long time ago, now also TW and likely Publisher need some manual confirmation for using older version of openssl.

#### how it was discovered

All the jenkins tests failed! 

- cmssw 12 https://github.com/dmwm/CRABServer/issues/7471
- cmssw 10 https://github.com/dmwm/CRABServer/issues/7472
- cmssw 7 https://github.com/dmwm/CRABServer/issues/7473

<details><summary>example. from client valiadtion, cmssw 12 </summary>

```plaintext
13:58:17 Task name:			221124_123257:cmsbot_crab_20221124_133251
13:58:17 Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-preprod-tw01
13:58:17 Status on the CRAB server:	SUBMITFAILED
13:58:17 Task URL to use for HELP:	https://cmsweb-testbed.cern.ch/crabserver/ui/task/221124_123257%3Acmsbot_crab_20221124_133251
13:58:17 Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=cmsbot&var-task=221124_123257%3Acmsbot_crab_20221124_133251&from=1669289577000&to=now
13:58:17 Failure message from server:	Process-2: I just had a failure for You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
13:58:17 					workid=0
13:58:17 					task=221124_123257:cmsbot_crab_20221124_133251
13:58:17 				Traceback (most recent call last):
13:58:17 				  File "/data/srv/TaskManager/v3.221121-51234b662ec6b9ff99ed431f52292abe/slc7_amd64_gcc630/cms/crabtaskworker/v3.221121-51234b662ec6b9ff99ed431f52292abe/lib/python3.8/site-packages/TaskWorker/Worker.py", line 99, in processWorkerLoop
13:58:17 				    outputs = work(resthost, dbInstance, WORKER_CONFIG, task, procnum, inputargs)
13:58:17 				  File "/data/srv/TaskManager/v3.221121-51234b662ec6b9ff99ed431f52292abe/slc7_amd64_gcc630/cms/crabtaskworker/v3.221121-51234b662ec6b9ff99ed431f52292abe/lib/python3.8/site-packages/TaskWorker/Actions/Handler.py", line 154, in handleNewTask
13:58:17 				    rucioClient =
13:58:17 				[... message truncated to the first 1000 chars ...]
```

</details>

#### solution 

It is enough to add 

```diff
#==== START THE SERVICE

+export CRYPTOGRAPHY_ALLOW_OPENSSL_102=true
+
case $MODE in
```

to https://github.com/dmwm/CRABServer/blob/815c09cec98e31e82809af20706186bbe684a130/src/script/Deployment/TaskWorker/start.sh#L63-L65

This is what TW and publisher are currently running with in preprod. 

#### open question

Where has this been introduced? Since we properly build our images with tag `v3.221114`, I would start pointing fingers at one of these changes.

- https://github.com/cms-sw/cmsdist/pull/8184
- https://github.com/cms-sw/cmsdist/pull/8185
- https://github.com/cms-sw/cmsdist/pull/8190
- https://github.com/cms-sw/cmsdist/pull/8196

All in all, even if we do not understand where this was introduced, we have a solution/mitigation. I would not spend too much time wondering why this happened.

**Comment by belforte** [comment]
:+1: :+1: 
> . I would not spend too much time wondering why this happened.
