### ISSUE TITLE
Find out why schedd machine got OOM and prevent it in the future

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7488]
Action item of postmortem [CRAB TaskWorker went down after too many task submissions](https://cmscrab.docs.cern.ch/incident/2022-11-15-crab-taskworker-went-down.html#action-item)

We have a situation where schedd machine suddenly freezes, but we never know why it happens. It causes misbehavior of other services run inside the VM, such as systemd (Wa: I cannot run any `systemctl` command), WMArchiveUploader, etc.
Sometimes manually restarting VM is required, but mostly sched daemon can survive and continue handling the job properly (at least no user reports errors caused by schedd).

This task aims to improve the stability of schedd machine and also allows us to understand resource utilization in schedd.

**Comment by mapellidario** [comment]
From current monitoring we noticed that usually when a schedd machine freezes, the CPU utilization reaches around 100%. 

I think that instead of blindly shooting in the dark to improvev "stability of the schedd machine", we should gather some data before deciding what should be improved.

I would suggest that the first action item to complete this task would be to identify what is the offending process that causes the cpu utilization to spike. For example, we can even ask Ceyhun to write a simple exporter in go that returns the name of the command that uses more cpu at any moment, then retrieve this with prometheus and save it to ES.

**Comment by belforte** [comment]
this could be a very large and long effort which may lead nowhere. I suggest to be very careful in putting time on something which so far has been almost non-noticeable.

**Comment by mapellidario** [comment]
After having a couple of chats with Panos and Nikodemas, I think we can start with writing a simple python script that runs on the schedd executes `top` (or something equivalent) and sends the data to es-cms.cern.ch using [osearch](https://github.com/dmwm/CMSSpark/tree/master/src/python/CMSSpark/osearch)

**Comment by belforte** [comment]
@mapellidario can setup such monitoring in 1 day

**Comment by belforte** [comment]
Let's also talk with SI people. In the end it is addtional work (setup, document, maintain, look at that monitor) for little gain (it happens a handful of times a year). It is difficult to imagine that we find a single, clear cause to fix and may end up in having to reboot the machine when it happens

**Comment by mapellidario** [comment]
Monit enabled on vocms0106, vocms059, vocms068, vocm069. 

An example of how related panels would look like is available in the row "dev" of this dashboard https://monit-grafana.cern.ch/goto/E0kVm8BIR?orgId=11 .  Note that the table allows filtering by "pid". In case that does not work, we can resort to using opensearch to map the pid to the full command line.

**Comment by mapellidario** [comment]
The script only sends to opensearch information about the 25 processes that consume more memory, i doubt that the condor shadows will end up in that list for production schedds

**Comment by mapellidario** [comment]
monitoring script is running and sending data to grafana at the end of "schedd instant load dashboard" [1]. I will put this on hold, waiting for a schedd to die :)

[1] https://monit-grafana.cern.ch/d/byfWUEhZk/crab-schedds-instant-load?orgId=11

**Comment by mapellidario** [comment]
no schedd died yet, but the monitoring is there :)
