### ISSUE TITLE
Make TW container easier to switch config between deployed by puppet and adhoc

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7489]
Action item of postmortem [CRAB TaskWorker went down after too many task submissions](https://cmscrab.docs.cern.ch/incident/2022-11-15-crab-taskworker-went-down.html#action-item)

(This issue is for tracking progress, I will do it myself)

We already have a solution summarized by Stefano:

>I think we agreed in the meeting that a script is an overkill for changing a symlink and best we can do is to do this in the container: create a local config and a remote (puppet managed) config and set current/TaskConfiguration.py to be a symlink to the remote. This way the needed action to quickly ban some user is simply to move the link to the local version and edit that, which needs no script/

**Comment by belforte** [comment]
sorry . that can not work. We agree that creating a symlink on the spot when needed is best. We can put 5 line to copy/pat in doc....
