### ISSUE TITLE
pass existing $SITECONFIG_PATH to process running CMSSW

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7516]
see
https://ggus.eu/index.php?mode=ticket_info&ticket_id=160313

since new jobwrapper may take a while to be deployed, we should push an urgent fix to https://github.com/dmwm/CRABServer/blob/65e3b434420299f8ee4a232c405d46323a4c7c40/scripts/CMSRunAnalysis.py#L642
along the lines of e.g. https://github.com/dmwm/CRABServer/blob/65e3b434420299f8ee4a232c405d46323a4c7c40/scripts/CMSRunAnalysis.py#L640

**Comment by belforte** [comment]
should check this at a couple suspected sites (besides KIT,  but IIUC it does not always happen at KIT), see https://cms-talk.web.cern.ch/t/crab-job-8001-exit-code-on-t2-ch-cern/19942/6

**Comment by mapellidario** [comment]
After having deployed the new jobwrapper, this is solved.

check for example this [job](https://cmsweb.cern.ch:8443/scheddmon/059/dmapelli/230224_153009:dmapelli_crab_20230224_162926_jobwr/job_out.1.0.txt), where I dump the environment where `cmsRun` is executed in: 

```plaintext
== CMSSW: SITECONFIG_PATH=/cvmfs/cms.cern.ch/SITECONF/local
```
