### ISSUE TITLE
Use CRAB task to import existing dataset into RUCIO

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#7537]
Minimal use case::
- I'm a user with a dataset published on phys03 DBS and I want to import this into RUCIO namespace/control

We can already work on provide an example task that will read data from data on `/store/user/<username>` and register a copy as a RUCIO owned file in `/store/rucio/user/`

Improvements/open items:

- [ ] crab data discovery of user scoped data in rucio
- [ ] RUCIO dataset dbs publication

**Comment by belforte** [comment]
after discussion, we are not sure how much needed this is now that @dynamic-entropy has a script which does the same. Pending further discussion with Rahul and @dciangot , let's lower priority/.

**Comment by belforte** [comment]
addressed in https://github.com/dmwm/CRABServer/issues/7755
