### ISSUE TITLE
document inputblocks

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7553]
new `inputblocks` feature needs to be documented in
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile

ref #7528

**Comment by novicecpp** [comment]
(draft)
```
| =inputBlocks= | list of string | (Analysis) Specify blocks to process in the form of DBS block name or block UUID string. CRAB will only discover (do tape recall if necessary) and process these blocks. See [[this FAQ][https://linktofaq]] about tape recall. Require =Data.inputDataset= to be set.|
```

**Comment by belforte** [comment]
Sorry. I had not noticed the first line and have independently put a description of inputBlocks in the config, param twiki. Feel free to change it. 

you should not be afraid of putting this in the twiki. We can always edit it again ! Few people if any will read unless/until we point them to it.

This is actually more than I asked for, but it is good. I think we should expand it be general FAQ about "my data is (partially) on tape (and partially on disk)".

**Comment by novicecpp** [comment]
I have updated FAQ https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#My_dataset_is_partially_on_tape, make it more general as you suggested, include how tape recall work (not sure if it too technical) and small mention to Data.partialDataset.

**Comment by belforte** [comment]
very nice thanks. But le me rephrase a bit for clarity.

**Comment by belforte** [comment]
Done. Check if you still like it. Then feel free to close.
With hindsight, 5TB is really very small, let's set config.TaskWorker.maxTierToBlockRecallSizeTB = 10

**Comment by novicecpp** [comment]
Thanks a lot for rephrasing. I will change config tomorrow and close this issue.

**Comment by novicecpp** [comment]
Done. 
https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/a8773a9070dc64df253c75156499653a065f328e
