### ISSUE TITLE
tune RSE list for large dataset recalls

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7610]
this is to keep track of discussion which we started today in CRAB Meeting.
current policy:
*  if dataset < 50TB --> use `grouping=ALL` : Rucio places data in a single site
 * otherwise, pick (size/50TB+1) RSE's from the list and hand those to Rucio using `grouping=DATASET`

Questions:
1. keep 50TB as threshold ? move to 100 TB ?
2. there are recall requests for 450TB samples, does it make sense to scatter in 10 sites ? Should we put a cap on the number of sites ?
3. how does `grouping=DATASET` work ? Will Rucio try to spread evenly, or try to put all at a single site if that site has enough quota ? Rucio [documentation](https://rucio.cern.ch/documentation/client_api/ruleclient#add_replication_rule) says:
   * ALL -  All files will be replicated to the same RSE.
    * DATASET - All files in the same dataset will be replicated to the same RSE.
    * NONE - Files will be completely spread over all allowed RSEs without any grouping considerations at all.

 
@KatyEllis volunteered to follow up on 3. with Rucio developers

**Comment by belforte** [comment]
in todays CRAB meeting we agreed to simply use `grouping=alll` for all datasets. And monitor how it goes.

As a matter of caution, I will keep current code in place, simply raise the current limit for dataset splitting from 50 to 1000 TB.
https://github.com/dmwm/CRABServer/blob/f785d252ec2153bd207127b765f8f756ffeea1cc/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L175
We reject anyhow requests above 1PB.
https://github.com/dmwm/CRABServer/blob/f785d252ec2153bd207127b765f8f756ffeea1cc/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L140-L141

**Comment by KatyEllis** [comment]
That sounds like a good plan. Let's monitor how it goes.
