### ISSUE TITLE
puppet - some things can be improved

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7656]
The puppet repository that we use to configure our VMs can be improved.

- [x] Stop using https://gitlab.cern.ch/CMSSI/SubmissionInfrastructureScripts for our schedds
    - instead, clone to our repo only the scripts that we know we need.
    - for example, `JobCleanup.py` is needed :)
    - JobCleanup.py: use `time.time()` instead of `ServerTime` from the schedd.query python binding (which is broken until condor 10.0.2 or 10.2 at least)  : done by @mapellidario https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/50bd097df10d968003fe258163a3e7d0863a2b67
- [x] review libcurl deployment : not needed in alma9
- [x]  WMArchiveUploader : done by @novicecpp  
- [x] (stefano) make sure all scripts can run in python3 - being done for alma9 #8257

**Comment by belforte** [comment]
we need to do something about WMArchiveUploader too (too big a task for this issue, I guess) which comes with its own very old WMCore version inside :-(

And of course move all scripts to python3 !

**Comment by belforte** [comment]
@mapellidario  I have updated task list at top. I think this can be closed. Pls review and if you agree, close. Thanks

**Comment by belforte** [comment]
@mapellidario can we close ?

**Comment by mapellidario** [comment]
yes, sure we can, sorry for keep you waiting!
