### ISSUE TITLE
test building with new htcondor binding in WMCOMP

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7736]
see https://github.com/cms-sw/cmsdist/pull/8582

**Comment by belforte** [comment]
It is not easy to tell what in CRABInterace is used and what it is not. Marco M. and predecessors have been too smart here. It depends on CRABServer configuration which kind of workflows is called.
This is why I have never dared to remove files in there.
OTOH e.g. crab status was redesigned long time ago to use the cached file prepared by task wrapper on the scheduler, we do no try to ask condor.

Of course first thing is to check that we can still build and run. Code cleanup will come later.

**Comment by belforte** [comment]
you can also test "removing dependencies" as simply as "delete files in `/data/srv/current/sw.crab_master/slc7_amd64_gcc630/external/` (even simply rename in order to quickly revert). And if you end up in a mess, just restart the pod and the container will be refreshed.

**Comment by mapellidario** [comment]
The test were ok. A couple of jobs failed, mainly at MIT and vanderbilt, likely for problems with the storage. 

I am inclined to consider  the use of the recent version of  `py3-htcondor` in TW validated. Stefano, do you agree?

**Comment by mapellidario** [comment]
Good, thanks, let's close then! :)
