### ISSUE TITLE
add time range to CrabServer UI MONIT pointer

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7767]
since the default is 30min, now it almost always fails to find the task as it builts URL like

https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=santocch&var-task=230714_100021:santocch_crab_singlemu-2017f

Need the same as in `crab status`

https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=santocch&var-task=230714_100021%3Asantocch_crab_singlemu-2017f&from=1689325221000&to=now

where from is in `msec` fom epoch, see
https://github.com/dmwm/CRABClient/blob/00d5e3ced6389fe328fe429eb41941a2a6a7f1d6/src/python/CRABClient/Commands/status.py#L460-L470

**Comment by novicecpp** [comment]
The trick is move time range to 30 days. Always work for me.

I will do.

**Comment by belforte** [comment]
not all of the times for me. It may depend on whether the task has jobs submitted in last 30min so that it appears in the initial dashboard and can stick in the selection menu.

thanks !
