### ISSUE TITLE
Publication is broken when using Rucio container as  input dataset

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7769]
with e.g.
```
config.Data.inputDataset = cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM
```
TaskWorker part works and jobs run but `taskPublish.py` fails because it tries to insert that in DBS as input dataset
```
2023-07-17 22:50:29,099:INFO:PublisherMaster,696:TaskPublishScript done : b'DBS Server error: [{\'error\': {\'reason\': "DBSError Code:114 Description:DBS validation error when wrong pattern is provided Function:dbs.validator.Check Message:unable to match \'dataset\' value \'cms:/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM\' Error: invalid parameter(s)"
```

I guess we can start by disabling publication in this case. Because in general we have no way to ensure that this rucio container maps to a dataset properly described in DBS `prod/global`.

Stick to
 * Publication in DBS requires input data in DBS.

**Comment by belforte** [comment]
one simple, if crude, way could be to disable publication check in 

https://github.com/dmwm/CRABServer/blob/d22b6c243edfefa3856343d6bcf0e70a8e4cf90e/test/container/testingScripts/statusTracking.py#L66
when ` task['taskName']` contains the 'nopub' string

**Comment by belforte** [comment]
.hmm... all in all.. if data processing produces valid FJRs and we have metadata for DBS.. why not simply stripping the initial scope in this case ?
@dciangot what do you think ?

**Comment by dciangot** [comment]
I think it will not hurt to disable it. If your input is from Rucio and not from DBS, It might be reasonable to say "I'm sorry, I can't do it"

**Comment by belforte** [comment]
supporting is at least clear. DIsabling I am not sure if to do in client or in server, where exactly, how to communicate... too many decisions !
Let me try the easy way (stripping) and see if it works

**Comment by belforte** [comment]
fix tested OK on publisher_schedd.  Need to verity on Publisher_rucio

**Comment by belforte** [comment]
OK with Publisher_Rucio as well
