### ISSUE TITLE
Remove dependency on htcondor from HTCondorDataWorkflow.py

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7782]
We are not using anymore the functions in HTCondorDataWorkflow.py that require talking directly to the schedulers.

However, maybe in the future we will find a good reason for talking to the schedds from crabserver, so we do not want to remove the rpm from py3-htcondor specfile from the crabserver image and we want to keep HTCondorDataWorkflow.py around in the current state (maybe freeze the file in its current forms in a copy with "old" appended at the end).

A good starting point would be https://github.com/dmwm/CRABServer/compare/master...mapellidario:20230717_py3htc10

**Comment by belforte** [comment]
we can remove htcondor from spec file unti needed, FWIW. I only worry about loosing code which we may not easily re-invent

**Comment by belforte** [comment]
item moved to #8338
