### ISSUE TITLE
jenkins PR check - failed with manual trigger

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7787]
I manually triggered a jenkins check on the PR #7759 and  the jenkins job failed. I will need to

The relevant builds (which I marked such that they are kept forever) are

- ✅ (prerequisite, pylint) https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-CRABServer-PR-pylintpy3/377/
- ⛔ (pylint output parser) https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-CRABServer-PR-test/1632/

**Comment by belforte** [comment]
we stop using this
