### ISSUE TITLE
allow tape recall of any data tier as long as size is small

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7841]
In the end, there's no point in asking users who want a small Alca/RAW/DQM/GEN... whatever to ask DataOps for small datasets.

It is OK to ask for a list of blocks in case the dataset is too big and then verify that the list is below a certain threshold, but when the full dataset is below that threshold.. why bother ?

This will limit requests on cms-talk/jira and overal save us time.

**Comment by belforte** [comment]
@novicecpp this seems a natural extension of the work which you did to support list of blocks, so hopefully it is OK for you to do. If not, feel free to assign to me.

**Comment by novicecpp** [comment]
https://cms-talk.web.cern.ch/t/stage-request-for-hi-virgin-raw-data/28554/3
