### ISSUE TITLE
restrict access to our vms - force 2FA for schedds and TW's

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#8096]
We would like to restrict the access to TW VM's and schedd machines, forcing two factor authentication.

We have multiple options:

- 1) make VM's  available only via aiadm
- 2) enable 2fa on the hosts themselves [1]

---

[1] https://config.docs.cern.ch/access/multifactor.html
~~https://indico.cern.ch/event/1267808/contributions/5324574/attachments/2616286/4522008/From%20IT%20with%20Love.pdf slide 4, `include multifactor`. We may ask nikos, spyros or other friends from cern it how to do it :)~~

**Comment by mapellidario** [comment]
@belforte and @novicecpp I am experimentig with two factor authentication on crab-dev-tw02, I followed instructions at [1].

Can you confirm that:

- from lxplus, you need to insert the second factor, and that you can login into crab-dev-tw02
- from aiadmin, you do not need to insert the second factor to login into crab-dev-tw02
- that this is the desired behaviour

?

thanks! :)

[1] https://config.docs.cern.ch/access/multifactor.html#trusting-aiadm

**Comment by belforte** [comment]
Yes to all. Thanks a lot !

**Comment by novicecpp** [comment]
Same to me. Very nice. Thanks.

Could you apply to tw03 too? I want test ansible with multiple node. Single node is working fine.

**Comment by mapellidario** [comment]
Good! thanks for confirming. I will apply to all dev and preprod machines

- [x] `crabdev_taskworker`: `crab-dev-tw*`
- [ ] `crabdev_schedd`: vocms068 vocms069, crab-preprod-sch03
- [ ] `qa` : `vocms059`, `crab-preprod-*`

If we like it, I will apply the changes also to prod machines on monday

**Comment by novicecpp** [comment]
Running Ansible with multiple machines works. Thanks.
However, you need to establish a socket to aiadm (`ControlMaster=auto`) and provide 2nd factor before running it. Otherwise, Ansible will pass the 2nd factor to only one node, and the other node's connection will fail.

**Comment by belforte** [comment]
Please, update Ansible instructions in https://github.com/dmwm/CRABServer/tree/master/scripts/Utils/crab-shutdown
(the only place where we have them :-( )
Better yet, a page in https://cmscrab.docs.cern.ch/technical/crab-schedd/how-tos.html on "how to execute a command on all schedds"

**Comment by belforte** [comment]
**OUCH** 
Jenkins can not log on TW VM's anymore in order to deploy new images.

We can of course login ourselves and do it by hand. Yet it is not as convenient, also Jenkins has the nice feature of seding a msg and recording log.

Ideas ?

**Comment by novicecpp** [comment]
Like `$_aiadm_ips` in https://config.docs.cern.ch/access/multifactor.html#trusting-aiadm but we need to ask Shahzad what IP (or hostgroup) of the Jenkins instance.

**Comment by belforte** [comment]
can you create an alma9 VM, gave it a quick test and then we go for 4) ? it seems the least effort

**Comment by mapellidario** [comment]
Restricting the whitelist to cmsjenkinsNN.cern.ch machines in `vocmssdt/jenkins` hostgroup should be enough to run our jenkins job and does not break ssh daemon config. 

I deployed it to dev machines, the jenkins job does what it is supposed to, but then failes with a weird and likely transient java error. [1]

[1] https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_Deploy_TW/547/console

**Comment by belforte** [comment]
very strange. error is not transient though. https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_Deploy_TW/548/console

**Comment by belforte** [comment]
I added a couple lines to the bash script to make sure that it completes OK and it looks like it does
and the log file is there. It is really archiving of logFile.txt in the PostBuild which fails.

```
21:01:49 + ssh -o StrictHostKeyChecking=no crab3@crab-dev-tw02.cern.ch 'docker ps'
21:01:50 + echo '$ERRR is false'
21:01:50 $ERRR is false
21:01:50 + false
21:01:50 + echo 'ALL OK'
21:01:50 ALL OK
21:01:50 + ls /var/lib/jenkins/workspace/CRABServer_Deploy_TW
21:01:50 isServiceRunning.log
21:01:50 logFile.txt
21:01:50 Archiving artifacts
21:01:50 ERROR: Step ‘Archive the artifacts’ aborted due to exception: 
```
I am out of ideas

**Comment by belforte** [comment]
I tried crab-dev-tw01 and got
```
 crab3@crab-dev-tw01.cern.ch: Permission denied (gssapi-with-mic,keyboard-interactive).
```
also after I ran puppet on the machine just in case it was needed to refresh some "who can get here w/o 2FA"

I am confused

**Comment by mapellidario** [comment]
that's because `crab-dev-tw01` is in `qa` environment, I have not ported the fix for 2fa for jenkins to qa yet. I wanted to give it a try on dev machines first. but ok, I will apply the fix to qa as well

```plaintext
[root@crab-dev-tw01 ~]# puppet agent -tv
Info: Certificate revocation is disabled, skipping CRL download
Info: Using environment 'qa'
[...]
```

**Comment by mapellidario** [comment]
Deploy from jenkins to crab-dev-tw01 worked [1]. Everything should work on prod, preprod and dev machines now, I am closing this issue. please open a new one if you find any problem.

---

[1]

https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_Deploy_TW/562/
