### ISSUE TITLE
add support for `SCRAM_ARCH=el9...`

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8098]
With reference to
https://cms-talk.web.cern.ch/t/jobs-failing-with-exit-code-10040/32699
and
https://cms-talk.web.cern.ch/t/crab-announcement/32724

currenly submission with `SCRAM_ARCH=el9...`  is broken.

It seems natural that some users may want to use el9 builds, it is not validated for Physics, but I understand from Matti that all recent releases are built for that as well, and with CERN now having `el9` as default for `lxplus` and `lxbatch` people may prefer to build their private executable for that OS.

Currently jobs submitted with `el9` SCRAM_ARCH have in their JDL `+REQUIRED_OS=Any` which makes them run in the default glideInWMS container which is `rhel7`.

The best solution looks to me to add the correct ARCH to OS mapping in WMCore, in:
https://github.com/dmwm/WMCore/blob/87ea437f508308b5e1d544a234a80e2a9911d5c1/src/python/WMCore/WMRuntime/Tools/Scram.py#L43-L46

which is used by CRAB in
https://github.com/dmwm/CRABServer/blob/94a11eb7bf795a1f344efb64fe0cea7c960386ff/src/python/TaskWorker/Actions/DagmanCreator.py#L524-L526

What do yoy think @amaltaro @mmascher @smuzaffar ?

FYI @mapellidario

**Comment by belforte** [comment]
I think that maybe there was a good reason in the past, pre-singularity era, for falling back to `"any"` in case `ARCH_TO_OS` returns nothing. But I suspect that now we should better raise a NotSupported exception ! What's the view from SI/CMSSW side ? Can we expect that for every scram arch there is a well defined container to be use

That will at least give clear and immediate feedback to users in this and possibly future cases.

**Comment by mapellidario** [comment]
I had a chat with @mmascher during the latest O&C week. Apart from changing WMCore arch to os mapping, the only missing piece that I could find was in the frontend configuration. Even if we specify the proper classads, the frontend is not equipped yet to spawn an el9 container on the WN. Marco said it should not be a big change, just a simple change in the config, but the priority felt low and I forgot to follow up.

**Comment by belforte** [comment]
I am happy to say that we do no support `el9` until `SI` does !

**Comment by belforte** [comment]
let's add the exception then

**Comment by smuzaffar** [comment]
@belforte 
> It seems natural that some users may want to use el9 builds, it is not validated for Physics, but I understand from Matti that all recent releases are built for that as well, and with CERN now having el9 as default for lxplus and lxbatch people may prefer to build their private executable for that OS.

I do not think that user ( who mostly have complained about this issue)  want to build/test for el9. They just follow the instructions which starts with `login to lxplus`. This had worked till 7th of Dec as lxplus was `CentOS7`  which is one of our production/validation arch. Now `lxplus` is `el9` and though we are building for `el9` but it is not validation yet.

> Can we expect that for every scram arch there is a well defined container to be use

Yes, for all enterprise linux based archs we have well defined container. For every SCRAM_ARCH there is `cmssw/rhelN` container ( available under /cvmfs/singularity.opensciencegrid.org/cmssw).

**Comment by belforte** [comment]
Thanks @smuzaffar , yes. I understand that. CMSSW users should stick with validated releases.
I am not advocating for that. But some users may find it useful to have el9 custom applications so that they can run on lxplus, lxbatch and grid too. All I am saying is that it would be good to add an entry to
ARCH_TO_OS mapping

**Comment by belforte** [comment]
@mmascher reported that EL9 container is now available from the factory.
We should test this and then update ARCH_TO_OS  mapping.

**Comment by belforte** [comment]
no change to CRAB code is required. In order to test we only need to edit https://github.com/dmwm/WMCore/blob/87ea437f508308b5e1d544a234a80e2a9911d5c1/src/python/WMCore/WMRuntime/Tools/Scram.py#L43-L46 in the TW container

**Comment by belforte** [comment]
I will make a PR for WMCore

**Comment by belforte** [comment]
moved to https://github.com/dmwm/WMCore/issues/11895

**Comment by belforte** [comment]
Here's the PR in WMCore: https://github.com/dmwm/WMCore/issues/11895
keep this open in Hold until that's merged, so we remember to ping if it does not happen

**Comment by belforte** [comment]
WMCore PR was merged. Closing
