### ISSUE TITLE
new format/location for MONIT secret file on schedulers

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8231]
with ref. to https://github.com/dmwm/CRABServer/pull/8214#issue-2112910251
we (Stefano, Dario, Wa) discussed and agreed to change to

filename :  `/data/certs/monit.d/MONIT-CRAB.json`

content:
```python
{
 "url": "https://monit-metrics.cern.ch:10014/crab",
  "username": "crab", 
  "password": "PutRealPasswordHere"
}
```

we will use puppet in case we want to push to user `crab-test` instead of `crab`

@mapellidario please correct me if my memory failed me !

**Comment by belforte** [comment]
@mapellidario is it on you or on me to deploy the secret file ?

**Comment by mapellidario** [comment]
I deployed the secrets to all machines. dev, qa and master puppet branches.

- filename:  `/data/certs/monit.d/MONIT-CRAB.json` (as asked in this private message https://mattermost.web.cern.ch/cms-o-and-c/pl/mtdnsqsmeibbpcg6p4en64dxee)
- content: schema described in puppet, for example here for [tw](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/57c90b999134d10a76a7481923ecb798a245467b/code/manifests/crabtaskworker/certificate.pp#L117)
- I created a new page on our docs with a mapping between producers, credential files in tbag, opensearch instance and index:  https://cmscrab.docs.cern.ch/technical/crab-monitoring/crab-opensearch.html

check to which machines the file has been deployed with

```bash
wassh -c vocmsglidein -l root "ls /data/certs/monit.d/"
```

**Comment by mapellidario** [comment]
Not a problem changing the file name, I will do it :)

**Comment by belforte** [comment]
Please no changes anymore. I do not want to edit the file again.
