### ISSUE TITLE
move all schedulers to Alma9

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8258]
Needs to be completed by end of May, as per request from Submission Infrastructure

Code developments needed:
- [x] Depends on #8256

**Comment by belforte** [comment]
**The plan**
* Stefano and Marco discussed a possible plan, and Marco also talked with Jaime.
* HTCondor23 is very little changed from HTCondor10 (it is effectively an Htcondor11, they decide to change numeration of versions to use the year as major version number, htcondor24 is still not out !)
* We can expect full compatibility:
   1). a scheduler with HTCondor23 can run in a pool where CentralManagers are HTCondo10 and viceversa. We can independently update schedulers one at a time and SI can independently work on collector and negotiator as they like
   2).  current python bindings (HTCcondor10) work with schedulers at HTC23. We can update all schedulers and only later worry about having HTC23 bindings in TW
   3) there is no change in condor logs format, so we can upgrade to HTC23 a running scheduler and it will resume all jobs which were running when it was stopped.
   4) corrollary of 3) : since all condor information is on /data disk (a CEPH volume) we expect to be able to shutdown one scheduler, rebuild the same VM on alma9, reconnect same CEPH volumes, and restart having it pickup where it left.

**Comment by belforte** [comment]
**STATUS as of Feb 22**

I have moved  [1] `crab-preprod-scd03` to HTCondor23 (`23.0.2-1.el7`) and it is working in ITB pool with current TW which uses HTCondor10 python bindings, this verifies 1) and 2) above.

I am running more jobs while looking at adding an alma9 machine.

[1] list of actions I took, before I forget
 * [change]( https://gitlab.cern.ch/ai/it-puppet-environments/-/commit/b572a1640b995e0a2292c9039fe74efbed9a8780) the `crabdev_schedd` puppet environment so that it picks `vocmshtcondor` module from `update_condor` branch in SI repo
    * that is needed because the master and qa branches in their repo do not have the settings for the HTCondor23 repository [ref](https://gitlab.cern.ch/ai/it-puppet-module-vocmshtcondor/-/compare/master...update_htcondor?from_project_id=10641&straight=false) 
 * [change](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/commit/c5b3cdd16ebd0c3f36f6534145ad3c6937152e83
) YAML file for `crab-preprod-scd03` in `crabdev_schedd` branch of you repository to use  `condor_version: 23.0.2-1.el7` 
 * `condor_off`, run puppet, `condor_on` .. it took a bit, but it came up OK. Not very challenging since there was no running jobs. We need to do it again on a busy schedd

**Comment by belforte** [comment]
**Alma9**

I created a puppettized VM with
```
belforte@aiadm01/~> ai-bs  --landb-responsible cms-service-crab3htcondor-admins    --nova-flavor m2.medium --alma9 --foreman-environment "crabdev_schedd" -g "vocmsglidein/crabschedd" crab-sched-901
```

but puppet fails with

Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, On 23rd August 2023 UMD repsitories do not exist for for EL8 and newer - please report if this is no longer true (file: /mnt/puppetnfsdir/environments/crabdev_schedd/modules/umd/manifests/init.pp, line: 24, column: 5) on node crab-sched-901.cern.ch

Looks like we need a new puppet environment where to test changes to the pupper configuration. This is quickly getting more work than I thought.

**Comment by belforte** [comment]
My ignorance run deeper. I have created that test sched on CC7, expecting something that "works like crab-preprod-scd03" but this time puppet fails with
```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error:
Function lookup() did not find a value for the name 'glidecondor_pool' on node crab-sched-701.cern.ch
```
and I can't log on the machine, do not know if because puppet did not complete or because something else is/was wrong.
```
belforte@aiadm84/~> ssh crab-sched-701
belforte@crab-sched-701: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

**Comment by belforte** [comment]
maybe ` did not find a value for the name 'glidecondor_pool' on node crab-sched-701.cern.ch` is because there was no YAML file for this host in `/data/fqdns` in gitlab. I [added it](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/130) let's see what happens when puppet runs again

**Comment by belforte** [comment]
after consulting with @novicecpp I decided to go for a new puppet environment  `crab_alma9`. I will aim to create a simlple VM where I can log in first and then add various packages.

**Comment by belforte** [comment]
**Update on alma9**
(I will delete previous comments)

There are now two small VM's running with alma9 puppettized as CRAB schedulers.
* `crab-sched-901`  currently runs `HTCondor 10.2.0-1.el9`
* `crab-sched-901`  currenlty runs `HTCondor 23.0.3-1.el9`

Both are part of ITB poo.. Both are in Foreman hostgroup [vocmsglidein/crabschedd](https://judy.cern.ch/hosts?search=hostgroup_title+%3D+%22vocmsglidein%2Fcrabschedd%22) using  puppet environment [crab_alma9](https://gitlab.cern.ch/ai/it-puppet-environments/-/blob/master/crab_alma9.yaml?ref_type=heads) i.e. puppet manifests and from [crab_alma9](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/tree/crab_alma9?ref_type=heads) branch of our repo

The way to get there was:
1. start with `crab_alma9` branch from current `qa`
1. create VM's with ` ai-bs  --landb-responsible cms-service-crab3htcondor-admins    --nova-flavor m2.medium --alma9 --foreman-environment "crab_alma9" -g "vocmsglidein" crab-sched-901`  to have minimal set of manifests. Create `data/fqdns` for them as a copy of another sched. Slowly change things in the manifest until errors are gone and I can log in. Trickiest part was AFS where a reboot was needed. At this point one can only login with a K5 token using `ssh root@crab-sched-901`
2. move machine to `vocmsglidein/crabschedd` hostgroup and again go through puppet errors solving one module at a time, now faster because I can use `puppet agent -tv`.
3. history of changes is not very useful (likely) and is in gitlab history for the `crab_alma9` branch
4. ask Florian to add repository for condor 10 on el9 to their [yum_repos.pp](https://gitlab.cern.ch/ai/it-puppet-module-vocmshtcondor/-/blob/update_htcondor/code/manifests/yum_repos.pp?ref_type=heads) (branch `update_condor`) so that condor install works
5. ask Florian to put condor tokens in tbag

7. ask Florian to put tokens for the new machines in tbag

**Comment by belforte** [comment]
TO DO

 - [ ] Install FTS python client
 - [ ] Test Rucio client from CVMFS
 - [ ] WMArchiveUploader setup fails in puppet ( #8265 )
 - [ ] There's a bunch of scripts in `code/files/crabschedd` which need to be adapted to `python3`, not `python` (scripts which come with CRAB submission already run in python3)
    - [ ]  cron.wrapper.sh
    - [ ] CrabDag.py
    - [ ] JobCleanuipAlarms.py
    - [ ] glexec_errors.py (a gWMS leftover to remove ?)
    - [ ] jobhistoryfeeder.py
    - [ ] JobCleanup.py
    - [ ] checl_maxdags.py
    - [ ] htcondor_ads.py
 - [ ] Install FTS python client
 - [ ] Test Rucio client from CVMFS

**Comment by belforte** [comment]
I can now submit with CRAB to e.g. `crab-sched-901` which runs condor 10 on alma9. But
still need to work on the httpd retrieval of crab status_cache file.

**Comment by belforte** [comment]
**Status update**
I have ported changes for alma9 to `qa` branch and modified `crab_alma9` environment to use that (still need an ad hoc env in order to override vocmshtcondor with the version which has alma9 repo, i.e. condor_update branch in there).

Now both vocms059 (in qa) and crab-sched-901/3 work using "same puppet".

I.e. we are technically ready to more more schedulers to alma9. 

Actions
- [ ] fix WmaUploader for alma9 in qa #8265 
- [ ] fix Prometheus for alma9
- [ ] move one of the new alma9 schedd's to gobal pool
- [ ] move vocms059 to alma9 and run all jenkins tests
- [ ] align `master` to `qa` in puppet
- [ ] test moving crab-preprod-scd03 to alma9 while it has some active tasks (roll it back to HTC 10 before, to limit confusion)
- [ ] drain one production scheduler and do the same
- [ ] schedule same action for other schedds

**Comment by belforte** [comment]
When running Jenkins tests on `crab-sched-901` it ran out of memory and could not be recovered. I deleted the VM and am re-creating with 15GB of RAM

**Comment by belforte** [comment]
**small issue**
the new "unified" `qa` branch did not have the switch to pick gfal2 form epel for alma9. Some things only appears when creating a new VM !
Fixed via https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/159

**Comment by belforte** [comment]
**NEW PROBLEM**
`/usr/bin/time` is missing on alma9. Although `time` command works. This breaks ASO-Rucio in
https://github.com/dmwm/CRABServer/blob/f6a59639d8614fb094f3444c97325f28ef16f10b/scripts/task_process/task_proc_wrapper.sh#L19

need to get it via `yum install time`

**Comment by belforte** [comment]
all Jenkins tasks ran finely, including resubmission and stageout.
Publication for ASO-Rucio was not done. I will investigate, possibly an unrelated problem.

**Comment by belforte** [comment]
test of "time to switch"
- issued ` ai-rebuild --cc7 crab-preprod-scd03.cern.ch` at 16:07
- at same time changed condor version in puppet from  `23.0.2-1.el9` to `23.0.2-1.el7`

..hm... VM is no stuck in`error` . From `openstack show server crab-preprod-scd03` I get the fault message `{'code': 500, 'created': '2024-03-26T15:07:28Z', 'message': 'libvirtError'} `

Tried to issue `ai-rebuild` again, but 
```
Couldn't rebuild node (Invalid volume: volume 'a4540dd2-033b-48d5-b98d-1e1998bfeb7b'
 status must be 'in-use'. Currently in 'reserved' status (HTTP 400) 
(Request-ID: req-65dc91ce-625a-49df-be24-07393bcab84c))

```

**Comment by novicecpp** [comment]
> asked IT for help: https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3803299

Could you add me to watchlist? I do not have permission to see it.

**Comment by belforte** [comment]
Done. Added @mapellidario too.

**Comment by belforte** [comment]
time for an update, before I loose track of all things I have done
* TaskWorker in production now runs code good for alma9. We expect new submissions to work.
* vocms059 with alm9, passes tests, but not in production (as usual) - final
* vocms0106 with alma6 is not in production and filled with user jobs. - final
* vocms0107 is ready with alma6, but not enabled in production yet
   * we should submit some test tasks and then enable if vocms0106 shows no issues
* vocms0119 and vocms0120 are "Prepared" i.e. went through the [Preparation step](https://codimd.web.cern.ch/LZFd9zUfTIa9wjeYLYKhjw?view#Preparation)
* vocms0121, 122, 137, 144, 155 are in draining

**Comment by belforte** [comment]
I think we need a table for production schedulers that we'll keep editing


|scheduler | draining | drained | environment | [prepared](https://codimd.web.cern.ch/LZFd9zUfTIa9wjeYLYKhjw?view#Preparation) | [migrated](https://codimd.web.cern.ch/LZFd9zUfTIa9wjeYLYKhjw?view#Migration) | OS | InProduction|
|--- | --- | --- | --- | --- | --- | --- | --- | 
| vocms0106 | - | Y | crab_alma9 | Y | Y | Alma9| Y|
| vocms0107 | Y | Y | crab_alma9 | Y | Y | Alma9 | Y|
| vocms0119| Y | Y | crab_alma9 | Y | Y | Alma9 | N|
| vocms0120 | Y | Y | crab_alma9 | Y | Y | Alma9 | N|
| vocms0121 | Y | N| production | N | N | CC7 | Y|
| vocms0122 | Y | N| production | N | N | CC7 | Y|
| vocms0137 | Y | N| production | N | N | CC7 | Y|
| vocms0144 | Y | N| production | N | N | CC7 | Y|
| vocms0155 | Y | N| production | N | N | CC7 | Y|
| vocms0194 | N | N| production | N | N | CC7 | Y|
| vocms0195 | N | N| production | N | N | CC7 | Y|
| vocms0196 | N | N| production | N | N | CC7 | Y|
| vocms0197 | N | N| production | N | N | CC7 | Y|
| vocms0198 | N | N| production | N | N | CC7 | Y|
| vocms0199 | N | N| production | N | N | CC7 | Y|

**Comment by belforte** [comment]
All CRAB schedulers are running on Alma9 hosts now.

**Comment by amaltaro** [comment]
This is amazing! 
Stefano, did you use the same Openstack project as the current SLC7 CRAB schedds? I see you are also putting these nodes into the hostgroup [vocmsglidein/crabschedd](https://judy.cern.ch/hosts?search=hostgroup_title+%3D+%22vocmsglidein%2Fcrabschedd%22).

I am just curious, in the end I think we/WM will stick with whatever SI recommends us to use, in terms of hostgroup, puppet templates and HTCondor version.

**Comment by belforte** [comment]
yes to both. It was mostly an exercise in puppet, several things changed since CC7 times.
We kept nodes in same openstack project and hostgroup as they were before.

Do you use puppet to install the agent ? If not.. none of this matters for you !

To be on the safe side  I did the changes in qa and moved schedulers from master to qa in puppet when migrating them. We already reconciled qa and master branches but need one last touch to SI's master to put schedulers back in production. We build on top of SI htcondor puppet module and the way puppet works, by default it picks the same branch there than in our repo. SI master will be Alma9-ready in a couple of weeks (from Florian).

You can also have a new puppet environment, I started that way for my first tests so not to affect not even ITB schedulers in qa. But IMHO there is no reason to use different openstack project unless you need to mix puppet branches from different gitlab repositories, which I hope you don't.

Then there are a few things due to "moving a shedulers that has jobs and DAGs in". Depending on your eventual plan, we can go into details.

If I manged to confuse you, we can have a chat !

**Comment by amaltaro** [comment]
Thank you for this clarification, Stefano.

We do not use puppet to manage/install the agent, only to bootstrap the node and set condor up. I try to stay away of puppet templating as much as I can, but I remember back in the days that the gitlab repositories for vocms and for glideinwms were separated. I honestly have no idea how the situation is nowadays.

For now, SI provided us new nodes in qa and (I guess) under their own Openstack project. But before moving to production - and master branch - I think we will have to recreate those nodes under CMS Production project. Thanks!

**Comment by belforte** [comment]
I would imagine that whatever the arrangement is now, it can continue. 

IIUC your machines are now in hostgroup `vocms/production/sched` so manifests in there need to be made 'alma9 ready'. I see that Bockjoo is actively working on this in  https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocms  in these days.
Which makes me wonder why you asked SI, not Bockjoo, to get you new nodes.

But the "vocms" thing with its multiple OS project and 3 layers of hostgroups is too much for me to really understand.

Most likely I am simply confused.
Indeed I should wonder if it would be better to unify also CRAB and SI under the VOCMS umbrella for easier sharing of things. 
That was my dram several years ago... but people working on puppet at the time, could not manage to do it, possibly because of operators coming and going and so many things going on and.. all usual problems. And now that we diverged and learnt how to change things w/o asking our friendly VOC's...it is not clear thate the effort would be worth. oh my.. so much duplicated work :-(
