### ISSUE TITLE
Abandon storage.xml in favor of storage.json (Issue from WMCore upstream)

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8264]
Blocked by [Abandon storage.xml in favor of storage.json for stage-in and stage-out](https://github.com/dmwm/WMCore/issues/11703). 
We will wait until the upstream issue is solved.

Comments move from meeting minutes:
- Wa will give this an initial round of check by building TW with their modified WMCore. Still an open issue in WMCore. Wait until they close this on their side.
- Good time to review cmscp.py and possibly refactor and simplify, hoping that the new implementation does not require (large) changes on our side to use it.

**Comment by novicecpp** [comment]
https://monit-grafana.cern.ch/goto/OEPl3mxIg?orgId=11

All sites are working fine with TW v3.240325 Stefano deployed on preprod. 
(Failed jobs are all exceed wall clock time (10mins).

![image](https://github.com/dmwm/CRABServer/assets/2346664/c7befe27-7666-4881-882b-ebae0ab40c55)

**Comment by novicecpp** [comment]
Keep issue open until new TW is on prod at least 1 week.

**Comment by belforte** [comment]
TW was put in production on Apr 2

**Comment by novicecpp** [comment]
Done
