### ISSUE TITLE
use robot certificate to retrieve proxies from myproxy

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8316]
* Maarten [says](https://ggus.eu/index.php?mode=ticket_info&ticket_id=166121) that a robot cert is fine 
* we can use the [current one](https://cmscrab.docs.cern.ch/technical/cmscrab-service-account.html#create-robot-certificate) which is already available in TW 
   * of course need to have it added to authorized retrievers via e.g. GGUS
* need simply to change the [TW config](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/qa/code/templates/crabtaskworker/taskworker/TaskWorkerConfig.py.erb#L114-115) in puppet in order to use it 
* then there will be no need to ask for adding host cert etc.  Everything taken care of by [puppet](https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/blob/qa/code/manifests/crabtaskworker/certificate.pp#L97-113)
* we should update documentation of what the robot cert. is used for

**Comment by belforte** [comment]
@novicecpp may I assign this to you ?

**Comment by belforte** [comment]
I have added the request to enable the robot certificate to [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=166121)

Once they say that they did it, please give it a try

**Comment by belforte** [comment]
reference: https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/208

**Comment by belforte** [comment]
@mapellidario @novicecpp can we close this ?

**Comment by novicecpp** [comment]
Yes. Thanks to Dario for taking care deployment.
https://cms-talk.web.cern.ch/t/prod-tw-uses-new-robot-cert-for-myproxy/42569

**Comment by belforte** [comment]
thanks !
