### ISSUE TITLE
Set FRONTIER_ID variable 

### ISSUE THREAD

**Issue by vzokay** [dmwm/CRABServer#8366]
Hello,

The Frontier team would like to ask for the addition of an environmental variable `FRONTIER_ID` in CRAB jobs. The reason for this is to get more information in our logs in order to diagnose intermittent slowdowns we've observed with some jobs in the last couple of months. 
As mentioned during a chat with @mapellidario, this is already done in WMAgent, to which he quickly found the relevant PR: 
   * dmwm/WMCore#5038 

Thank you @mapellidario @belforte for looking into this and for your time!

All the best,
Vaiva

**Comment by vzokay** [comment]
Thank you for your prompt response! I'm passing Dave D's message:

> That would work.  Actually it would improve our squid log parsing a little bit if there wasn't a space in it, since the wmagent id doesn't have one.  So either delete the space or replace it with an underscore or hyphen

**Comment by belforte** [comment]
Doesn't Dave D. have a GH account so we can speed up communication w/o bother 3rd parties (you) ?

OK. I will add an hyphen `-`

**Comment by belforte** [comment]
not it is
`CRAB-240425_061854:xiaoyul_crab_20240425_081720`

**Comment by vzokay** [comment]
Sure, apologies for the inconvenience.
Passing it over to @DrDaveD
