### ISSUE TITLE
replace schedd.xquery with schedd.query

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8447]
`xquery` is being retired by HTC developers as dicussed with Todd Miller in the context of
testing `htcondor2` bindings
https://github.com/dmwm/CRABServer/issues/8272#issuecomment-1986688214

From the documentation:
![image](https://github.com/dmwm/CRABServer/assets/1837785/f19c0fe7-6b74-487e-bed8-d680faad3474)

**Comment by amaltaro** [comment]
Just a heads up, I will have a bunch of questions about HTCondor upgrade in a couple of months from now ;)

**Comment by belforte** [comment]
any time @amaltaro :-)
