### ISSUE TITLE
decouple our qa from epel testing

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8463]
by default qa gets rpms from epel-testing, not epel.
This introduces too many unknwon, uncontrolled chances, especially hen for one reason or another we have several machiines in qa. At the very least we need to be aware. Better yet be ready to disable/enable as proper. Here are instructions ([MM](https://mattermost.web.cern.ch/it-dep/pl/57tx84o9didm5mxjmo1f8xkt6h)):

![image](https://github.com/dmwm/CRABServer/assets/1837785/b40a9bed-b0ca-4c11-b0c9-0482cb109a34)

**Comment by belforte** [comment]
assigning to me to remember to bfing it up for discussion

**Comment by belforte** [comment]
we discussed in the meeting today. Pending a final review with @mapellidario the conclusions are:

- stick to epel production for all our VM’s even in qa
- Let other people test epel-testing
- Lock FTS client version anyhow, like we do for HTCondor and when an updated comes upstream, validate it.

**Comment by mapellidario** [comment]
uh! this was not easy to catch, good job Stefano (and Wa also?)!
I definitely agree with all your decisions

**Comment by aspiringmind-code** [comment]
Fixed by disabling epel-testing in `data/hostgroup/vocmsglidein.yaml` See https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/204

Test passed on crab-dev-tw03 See https://gitlab.cern.ch/ai/it-puppet-hostgroup-vocmsglidein/-/merge_requests/205
