### ISSUE TITLE
capture MasterWorker/Publisher log

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8496]
IIUC this lines
https://github.com/dmwm/CRABServer/blob/e6eb58703768825380e22efebd14889411d8c52a/cicd/crabtaskworker_pypi/TaskWorker/manage.sh#L44
https://github.com/dmwm/CRABServer/blob/e6eb58703768825380e22efebd14889411d8c52a/cicd/crabtaskworker_pypi/Publisher/manage.sh#L44
make the stdout/stderr of Master* get lost. While it previously was saved in the `nohup.out` file.

This makes it hard to debug crashes. Esp. if coming at the start.

Or am I simply unable to find the log ?

**Comment by novicecpp** [comment]
For now, it should printout to container's stdout/err. 
Run `docker logs TaskWorker` to see the logs. 

However it will not save to container's stdout properly when you re-start service by `./start.sh -c`  again.

**Comment by novicecpp** [comment]
This PR https://github.com/dmwm/CRABServer/pull/8658 also put the startup logs to `logs/nohup.out`.
