### ISSUE TITLE
avoid exiting container on command error

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8539]
when inside e.g. TW container with `docker exec -ti TaskWorker bash`, after I do
`source env.sh` or `source env.sh -g` to test things locally, the `set -eou pipefile` "persists" so that any command with non zero exit status results in exiting the container.

Would it be possible to add `set +e` at the end of `env.sh` ? Or will it cause problems elsewhere ?

**Comment by novicecpp** [comment]
> Would it be possible to add `set +e` at the end of `env.sh` ? 

Yes. 
You can put a whole `set +eou pipefile` to avoid annoying unbound variable errors and the pipe failing too.

**Comment by belforte** [comment]
I tried various things but while "exit on failed command" is gone at first approximation, if I run `source env.sh -g` again it fails to detect the mode, complains, and exit the bash shell. Maybe the consequence of the `set -auo pipefail` in the container itself. I leave it to you

**Comment by novicecpp** [comment]
Sure, I will have a look tomorrow.

**Comment by belforte** [comment]
not urgent
