### ISSUE TITLE
Process fds count in REST is broken in new PyPI image

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8568]
In REST, we depend monitoring scripts/binaries from [RPM version of cmsweb image](https://github.com/dmwm/CMSKubernetes/blob/0cb2d75f9b74ff4aea5b80f679c04651aadcf14c/docker/cmsweb/Dockerfile#L72-L81).
And then we add our entrypoint, [monitor.sh](https://github.com/dmwm/CMSKubernetes/blob/0cb2d75f9b74ff4aea5b80f679c04651aadcf14c/docker/crabserver/monitor.sh) to [our RPM image](https://github.com/dmwm/CMSKubernetes/blob/0cb2d75f9b74ff4aea5b80f679c04651aadcf14c/docker/crabserver/Dockerfile#L26).

This step is lost when migrating to a new PyPI image, [making the monitoring fail](https://mattermost.web.cern.ch/cms-o-and-c/pl/ezawwczcojndbgtzsdz1qyan5o).

Note that process fds count is a must for REST service.

**Comment by mapellidario** [comment]
A very similar thing happened for the TW image, should we re-open this issue or should we create a new one?


![image](https://github.com/user-attachments/assets/25f7d390-bba8-44a5-96f4-c52876a51766)

**Comment by belforte** [comment]
new one
