### ISSUE TITLE
monit - TW stopped sending data to logstash-opensearch after latest deployment to production

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#8573]
The most recent TW image `v3.240716-stable` does not send data to logstash-opensearch, so some panels in "CRAB Overview" dashboard are now empty [1].

This issue is similar to https://github.com/dmwm/CRABServer/issues/8568

fyi: @novicecpp 

---

[1] https://monit-grafana.cern.ch/goto/IG-A4MrSR?orgId=11

<details>

![image](https://github.com/user-attachments/assets/25f7d390-bba8-44a5-96f4-c52876a51766)

</details>

**Comment by belforte** [comment]
fixed
