### ISSUE TITLE
add Client_Validation_Suite and Client_Configuration_Validation to cicd pipeline

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8588]
maybe not run them all of the times. Definitely we do not need to validate client every time that we build TaskWorker.
But in view of getting rid of Jenkins, we need a way to do that.
CCV is important for REST and TW code validation.

**Comment by aspiringmind-code** [comment]
Done in https://github.com/dmwm/CRABServer/pull/8696 and https://github.com/dmwm/CRABServer/pull/8800
