### ISSUE TITLE
CRAB monitoring diagram

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8679]
We have 4 different log pipelines. 
We need to write it down and put into our docs. Otherwise we forget.

Diagram will serve as map how monitoring services are connected and starting point for debugging.

**Comment by belforte** [comment]
When I looked at the non-timber [one](https://monit-opensearch-lt.cern.ch/dashboards/goto/31d6e610962e003ce8adc89217e18896)  I was also annoyed by the fact that we have 7 CRAB indexes. I surely have some fault there. 
We may not want to call it "7 OS pipelines plus 3 FileBeat pipelines", but the need for clarification runs deep !
Or do we have 4 filebeat (log) pipelines ? REST, TW, Publisher + ?

**Comment by novicecpp** [comment]
https://cmscrab.docs.cern.ch/technical/crab-monitoring/monitoring-pipelines.html
Partially done. Next is to add grafana side (the [datasources.json](https://github.com/dmwm/CMSMonitoring/blob/master/static/datasources.json)),
and extras:
- TW metrics page. 
- REST metrics page.

**Comment by belforte** [comment]
great job ! English needs finessing though. Tastes a bit like "robotic translation from a Thai source". But I can understand none the less.
Hand to Vijay ?

**Comment by novicecpp** [comment]
No. Let me do it. It still not complete. 
Then feel free to changes whatever you want.

**Comment by novicecpp** [comment]
Done.
I am closing this issue. @belforte if you want @aspiringmind-code to modify it, feel free to reopen this issue.

**Comment by belforte** [comment]
looks good now. Thanks !
