### ISSUE TITLE
Release pipeline broken without anybody notice

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#8701]
The [release pipeline of v3.240904](https://gitlab.cern.ch/crab3/CRABServer/-/pipelines/8057298) is broken, all jobs complete except last job that tagging crabtwmonit image to release tag (which cause by a bug in CI config but that separate issue).
Nobody noticed it, including me, who received the mail, thought that it was my "usual broken" dev pipeline

This cause monitoring cron to fail because image not found.

This happened today after we merge puppet qa to master which contains bump cron image verison to `v3.240904-stable`.

**Comment by novicecpp** [comment]
Self-reminder: fix the pipeline before doing anything tomorrow.

**Comment by belforte** [comment]
we got "No Data" alert in MatterMost. NObody noticed :-(

**Comment by belforte** [comment]
I believe that this was fixed.
