### ISSUE TITLE
GH repos inside TW container must be owned by crab3 user

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8703]
looks like this
https://github.com/dmwm/CRABServer/blob/3c8607f723248dff957d6146a25162d8f8128fbb/cicd/crabtaskworker_pypi/Dockerfile#L101-L104

should be changed to be like
https://github.com/dmwm/CRABServer/blob/3c8607f723248dff957d6146a25162d8f8128fbb/cicd/crabserver_pypi/Dockerfile#L58-L63

**Comment by belforte** [comment]
@novicecpp I have tried this in my test pipeline, but it seems to have no effect.
Any idea ?

**Comment by novicecpp** [comment]
yes, if you use ci to build.

**Comment by belforte** [comment]
thanks for confirming. Forgive me for such a stupid mistake.
