### ISSUE TITLE
`ddm_quota` is deprecated, use `dm_weight`

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#8724]
and while we are at this, do not rely only on `ddm_weight=0` to avoid test RSE's, but explicitely avoid RSE's of type TEST

should modify

https://github.com/dmwm/CRABServer/blob/e8149dda5ff7a4fee80d3b25d5c038ead60c711d/src/python/TaskWorker/Actions/RucioActions.py#L119

https://github.com/dmwm/CRABServer/blob/e8149dda5ff7a4fee80d3b25d5c038ead60c711d/src/python/TaskWorker/Actions/RucioActions.py#L68

**Comment by amaltaro** [comment]
@belforte in case it makes your life easier, the expression to avoid Test RSEs that we have implemented in WMCore uses `\cms_type=test`, e.g.:
```
"rse_type=TAPE&wmcore_output_tape=True\cms_type=test"
```
HTH.

**Comment by belforte** [comment]
it does help, thanks !  in particular the reminder about the special use of `\` !

**Comment by belforte** [comment]
sounds like a good day to do this

**Comment by belforte** [comment]
https://github.com/dmwm/CRABServer/blob/e8149dda5ff7a4fee80d3b25d5c038ead60c711d/src/python/TaskWorker/Actions/RucioActions.py#L119
changed to
```python
allRses = r"(tier=1|tier=2)&rse_type=DISK\cms_type=test\cms_type=temp"
```

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/8762
